-- ===============================================================
-- UPDATE chunk 4/8: surgery (25 questions)
-- ===============================================================

begin;

update public.mcq_questions
set choices = '[{"label":"A","text":"Oral antibiotic only"},{"label":"B","text":"Acute pilonidal abscess — incision + drainage"},{"label":"C","text":"Observation only"},{"label":"D","text":"Total proctectomy"},{"label":"E","text":"Discharge home, follow up 1 week"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** **Acute pilonidal abscess — incision + drainage**: (1) **I&D off-midline** — local anesthesia + small lateral incision (off-midline preferred — better healing than midline); evacuate pus + debride hair + necrotic tissue; loose packing; no closure; (2) **No routine antibiotic** unless: cellulitis spreading, immunocompromised, sepsis — if needed: cover skin flora (cefalexin, dicloxacillin) or MRSA (clindamycin, doxycycline, TMP-SMX) per local prevalence; (3) **Wound care**: regular dressing change, sitz baths; (4) **Definitive treatment after acute episode resolved**: elective management of pilonidal disease — - **Pit picking / Bascom''s procedure** (minimally invasive, off-midline) - **Excision + secondary intention healing** (open wound, longer healing) - **Excision + primary closure off-midline** (Karydakis flap, Limberg/rhomboid flap) — lower recurrence than midline closure - **Laser ablation** (newer); (5) **Lifestyle**: hair removal (shaving, laser depilation) at natal cleft, hygiene, weight loss, avoid prolonged sitting; (6) **Recurrence** 10-30% — choice of definitive procedure affects

---

**Pilonidal disease** — chronic sinus / abscess in natal cleft, usually 15-35 yr males with deep cleft + hair + sweating. Etiology: hair penetrates skin → foreign body reaction + sinus → recurrent infection. **Acute abscess**: I&D off-midline (better healing); systemic antibiotic for surrounding cellulitis only. **Chronic / recurrent disease**: - Conservative: hair removal (shaving, laser depilation — Conroy meta-analysis supports laser), hygiene - Pit picking (Bascom) — minimally invasive - Excision + healing by secondary intention — longer wound care - Excision + flap closure off-midline (Karydakis, Limberg rhomboid) — lower recurrence than midline primary closure - Endoscopic pilonidal sinus treatment (EPSiT), laser ablation — newer **Wound closure principle**: avoid midline closure (poor healing, recurrence) — off-midline flap preferred. **Risk factors**: obesity, sedentary, sweating, hairy, family history. **Prevention**: hair removal, hygiene. A ผิด — abscess ต้อง I&D. C ผิดอย่างยิ่ง. D ผิดเกินจริง. E ผิด.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'surgery'
  and scenario = 'ชายไทยอายุ 35 ปี ปวดบริเวณก้นกบ 3 วัน + บวมแดงร้อน + ไข้ต่ำ

Exam: tender erythematous swelling 4 cm at lower sacrum + central pit + small purulent discharge
Hair tuft present
No signs of cellulitis spreading

คำถาม: management';

update public.mcq_questions
set choices = '[{"label":"A","text":"Total proctocolectomy + ileal pouch-anal anastomosis (IPAA)"},{"label":"B","text":"Crohn''s disease with stricturing + penetrating phenotype — selective surgical approach (bowel preservation principle)"},{"label":"C","text":"Refuse surgery in all Crohn''s"},{"label":"D","text":"Total colectomy + permanent ileostomy first-line"},{"label":"E","text":"Whipple procedure"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** **Crohn''s disease with stricturing + penetrating phenotype — selective surgical approach (bowel preservation principle)**: (1) **Optimize medical therapy** — biologic optimization (adalimumab trough + ADA), switch class if loss of response (anti-TNF → ustekinumab, vedolizumab, risankizumab, upadacitinib JAK), corticosteroid bridging, nutritional optimization; (2) **Surgical indications in Crohn''s**: failed medical therapy, intestinal obstruction (stricture), perforation, hemorrhage, fistula refractory, cancer/dysplasia, growth failure (pediatric); (3) **Surgical principles** — BOWEL PRESERVATION: - **Strictureplasty** (Heineke-Mikulicz, Finney, Michelassi for long strictures) — preserve bowel length, avoid short gut - **Limited segmental resection** with histologically clean margins (~ 2 cm grossly normal — no need wider; recurrence not reduced) - Avoid wide resection; (4) **Ileocecal resection** for distal ileal disease — standard; recent LIR!C trial (Ponsioen Lancet GH 2017) — early surgery non-inferior to infliximab in selected; (5) **Perianal fistulas** — multidisciplinary: seton placement for drainage, MRI mapping; biologic therapy (anti-TNF); local excision/LIFT; mesenchymal stem cell therapy (darvadstrocel — ADMIRE-CD); (6) **No IPAA in Crohn''s** — high failure + complications; reserved for UC; (7) **Post-op recurrence prophylaxis** — clinical features (smoking, fistulizing, prior resection) → start biologic 4-8 weeks post-op; (8) **Surveillance for dysplasia/cancer** — chronic colitis at risk; (9) **Smoking cessation absolute** in Crohn''s — strongest modifiable risk; (10) Multidisciplinary IBD team

---

**Crohn''s disease surgical principles**: 1. Crohn''s is not curable surgically — recurrence common — preserve bowel 2. Common indications: stricture (obstruction), fistula (enteroenteric, enterovesical, enterocutaneous), abscess, perforation, hemorrhage, dysplasia/cancer, refractory disease, growth retardation 3. Surgical options: - Strictureplasty (Heineke-Mikulicz < 10 cm, Finney for medium, Michelassi side-to-side isoperistaltic for long > 25 cm) — preserves length - Limited segmental resection with 2 cm grossly normal margin (Fazio Ann Surg 1996 — no benefit to wider margins for recurrence) - Drainage of abscess (often percutaneous first) - Diversion stoma sparingly 4. AVOID: extensive resection, IPAA (high failure in Crohn''s), pouch in Crohn''s 5. Recurrence — endoscopic 70% at 1 yr, surgical 30% at 10 yr 6. Postoperative prophylaxis: anti-TNF or other biologic based on risk (POCER trial — colonoscopy-guided step-up) 7. Smoking cessation absolute Perianal fistulas: complex anatomy (Park classification — intersphincteric, transsphincteric, suprasphincteric, extrasphincteric); MRI mapping; multidisciplinary management: drainage seton + biologic + local procedure (LIFT, fistula plug, advancement flap); mesenchymal stem cells (allogeneic adipose-derived darvadstrocel) for refractory complex perianal Crohn''s fistulas. A ผิด — IPAA = UC. C E ผิดอย่างยิ่ง. D ผิด — bowel-preserving.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'surgery'
  and scenario = 'หญิงไทยอายุ 28 ปี Crohn''s disease 10 ปี on adalimumab + budesonide แต่ flare ใหม่ 1 เดือน ปวดท้อง RLQ + ถ่ายเหลว 6 ครั้ง/วัน + น้ำหนักลด 4 kg + perianal fistula chronic

MRI enterography: active inflammation distal ileum 15 cm + stricture + small bowel obstruction features + complex perianal fistula (Park''s type)
Colonoscopy: focal colitis + skip lesions

คำถาม: surgical considerations';

update public.mcq_questions
set choices = '[{"label":"A","text":"Continue azathioprine + steroid same dose"},{"label":"B","text":"Acute Severe Ulcerative Colitis (ASUC) — toxic megacolon possible, medical rescue OR colectomy"},{"label":"C","text":"Discharge home with oral steroid"},{"label":"D","text":"Antidiarrheal medication"},{"label":"E","text":"Total proctectomy alone, leave colon"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** **Acute Severe Ulcerative Colitis (ASUC) — toxic megacolon possible, medical rescue OR colectomy**: (1) **Hospitalization + supportive care**: NPO, NG decompression if megacolon, IV fluid, electrolyte correction (K), VTE prophylaxis (UC = high VTE risk), correct anemia, nutritional support (parenteral if needed); rule out CDI + CMV (stool toxin + sigmoidoscopy biopsy CMV IHC); (2) **IV corticosteroid** — methylprednisolone 60 mg/day OR hydrocortisone 100 mg q6h — first 72h; (3) **Day 3 assessment** (Travis criteria): CRP > 45 + > 8 stools/day = > 80% likely need colectomy → consider rescue OR surgery; (4) **Medical rescue if no response by day 3-5**: - **Infliximab** 5 mg/kg IV (consider higher dose 10 mg/kg in severe inflammation given clearance) — accelerated induction - **Cyclosporine** IV 2-4 mg/kg/day - **Tofacitinib** rapid acting — emerging - **JAK inhibitors** upadacitinib emerging; (5) **Colectomy indication** — emergent: toxic megacolon (transverse colon > 6 cm + signs sepsis), perforation, massive hemorrhage, failed medical rescue 5-7 days; subacute: failed medical optimization; (6) **Surgery**: **subtotal/total colectomy with end ileostomy + Hartmann pouch** (preserve rectum) — emergent / unstable / steroid-dependent; later reconstruction with IPAA (ileal pouch-anal anastomosis) in 3-stage approach; (7) **Avoid antimotility** + opioids (precipitate toxic megacolon); (8) Long-term post-IPAA — pouchitis common (15-50%) — treat antibiotic

---

**Acute Severe UC (ASUC)** — Truelove-Witts criteria: ≥ 6 bloody stools/day + 1+ systemic (HR > 90, fever > 37.8, Hb < 10.5, ESR > 30, albumin < 30, CRP elevated). Mortality without colectomy historically 30%; modern era < 1% with rescue medical + timely surgery. **Day 3 assessment** (Oxford / Travis predictors of colectomy): - CRP > 45 + 3-8 stools/day OR > 8 stools/day on day 3 → 80% need colectomy **Rescue therapy options** (failed IV steroid day 3-5): 1. Infliximab — increasingly preferred; consider accelerated dosing (10 mg/kg, repeat 7 days) — CONSTRUCT trial 2. Cyclosporine IV 2-4 mg/kg/day — historical efficacy similar 3. JAK inhibitor (tofacitinib, upadacitinib) — emerging, rapid onset 4. Sequential rescue (cyclo → IFX or vice versa) not recommended — bone marrow + infection risk **Surgery (colectomy)** indications: toxic megacolon (≥ 6 cm + sepsis), perforation, hemorrhage, failed rescue 5-7 days. **Approach**: total/subtotal colectomy + end ileostomy + Hartmann (preserve rectum) — emergent; staged IPAA later (2 or 3 stages depending on patient). **Toxic megacolon**: KUB transverse colon > 6 cm + systemic toxicity (3+ of fever, HR > 120, WBC > 10.5k, anemia) + 1+ of dehydration, AMS, electrolyte, hypotension. **VTE prophylaxis** essential — UC active disease is hypercoagulable. A ผิด — current regimen failed. C ผิด — severe ต้อง IV. D ผิด — โครงสร้าง megacolon. E ผิด — leave colon = recurrent.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'surgery'
  and scenario = 'หญิงไทยอายุ 24 ปี Ulcerative colitis 5 ปี on mesalamine + azathioprine + steroid; ตอนนี้ admit ICU ด้วย severe acute UC flare 10 วัน — diarrhea 12 ครั้ง/วัน + bloody + abdominal distention + ไข้ + tachycardia

VS: BP 102/64, HR 116, Temp 38.4°C
Abdomen: distended, tender, decreased bowel sounds
Lab: Hb 8.2, albumin 2.4, CRP 180, K 3.0
KUB: transverse colon dilated 7 cm + ''thumbprinting'' edema
Colonoscopy (limited): severe ulcerated mucosa + Mayo 3

Truelove-Witts severe
CT scan: rule out perforation, megacolon';

update public.mcq_questions
set choices = '[{"label":"A","text":"NG decompression only, no further workup"},{"label":"B","text":"Meconium ileus in neonate — likely cystic fibrosis-associated"},{"label":"C","text":"Outpatient referral pediatric surgery"},{"label":"D","text":"Emergent total colectomy"},{"label":"E","text":"Observation 48 hr"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** **Meconium ileus in neonate — likely cystic fibrosis-associated**: (1) **Initial resuscitation**: NPO, NG decompression, IV fluid, broad-spectrum antibiotic; (2) **Cystic fibrosis evaluation** — sweat chloride test + CFTR genetic testing — > 80% of meconium ileus have CF; refer pulmonology, genetics; (3) **Therapeutic Gastrografin enema** — hypertonic water-soluble contrast under fluoroscopy — both diagnostic + therapeutic (osmotic effect draws fluid → soften + flush meconium); success rate 50-70% in uncomplicated meconium ileus; risks: bowel perforation (~5%), fluid shift → hypovolemia (preceded by IV fluid resuscitation); (4) **Surgery indications**: failed contrast enema (3 attempts), complications (perforation, volvulus, atresia), complicated meconium ileus (meconium peritonitis, ileal atresia, pseudocyst); (5) **Surgical options**: enterotomy + meconium evacuation + irrigation; resection of non-viable segment + primary anastomosis or temporary stoma (Bishop-Koop, Mikulicz); (6) **Postop**: enzyme replacement therapy, nutritional optimization (CF-specific), antibiotic, follow CF specialist long-term; (7) Genetic counseling for family planning

---

**Meconium ileus** — distal small bowel obstruction in neonate from thick inspissated meconium; > 80% have cystic fibrosis (CFTR mutation → abnormal mucus). Other causes: pancreatic insufficiency, Hirschsprung''s (DDx), small left colon syndrome (maternal DM). **Presentation**: bilious vomiting + abdominal distention + failure to pass meconium > 24h. **X-ray**: dilated bowel + ''soap bubble'' appearance RLQ (meconium-gas), absent rectal gas. **Contrast enema (Gastrografin)**: microcolon (disuse) + filling defects in ileum from meconium. **Therapeutic enema**: hypertonic water-soluble (Gastrografin) — osmotic action; success 50-70% uncomplicated; risks: perforation 3-5%, fluid shift → hypovolemia (IV pre-hydration mandatory); repeat 1-2 times if partial success. **Surgery**: failed enema, complications. Options: enterotomy + irrigation, resection + anastomosis vs stoma (Bishop-Koop double-barrel, Mikulicz, Santulli). **CF evaluation**: sweat chloride > 60 mEq/L diagnostic; CFTR mutation analysis; pulmonology follow-up; pancreatic enzyme replacement therapy (PERT); nutritional optimization (high calorie, fat-soluble vitamins); long-term CF center care; precision therapy (CFTR modulators — ivacaftor, elexacaftor-tezacaftor-ivacaftor) for specific mutations.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'surgery'
  and scenario = 'ทารกแรกเกิดอายุ 1 วัน อาเจียน bilious 12 ชั่วโมง + abdominal distention + ไม่ผ่าน meconium 24 hr

VS stable
Abdomen: distended, no peritonitis
X-ray: dilated loops bowel + ''soap bubble'' appearance RLQ + no rectal gas
Contrast enema: microcolon + dilated proximal small bowel + filling defects in distal ileum';

update public.mcq_questions
set choices = '[{"label":"A","text":"Observation"},{"label":"B","text":"Hirschsprung disease (congenital aganglionic megacolon) — staged management"},{"label":"C","text":"Total colectomy + ileostomy without diagnosis"},{"label":"D","text":"Discharge with laxative"},{"label":"E","text":"Endoscopic dilation"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** **Hirschsprung disease (congenital aganglionic megacolon) — staged management**: (1) **Initial**: bowel decompression with rectal stimulation / irrigation (saline irrigation); broad-spectrum antibiotic; NG decompression; (2) **Confirm diagnosis**: rectal suction biopsy gold standard (absence of ganglion cells + hypertrophic nerve trunks + calretinin negative); (3) **Modern approach — single-stage pull-through** in stable infant after decompression: - **Soave** (endorectal pull-through) — preserve muscular cuff - **Swenson** (full-thickness rectosigmoidectomy + coloanal anastomosis) - **Duhamel** (retrorectal pull-through with side-to-side anastomosis) — common, less pelvic dissection - **Transanal endorectal pull-through (TERPT/De La Torre)** — increasingly preferred, no laparotomy in standard-length disease; (4) **Staged approach** for very ill / total colonic Hirschsprung / late presentation: leveling colostomy in ganglionic bowel → pull-through 4-6 mo later → closure of stoma; (5) **Post-op complications**: enterocolitis (Hirschsprung-associated enterocolitis HAEC — life-threatening; treat aggressive antibiotic + irrigation), constipation, soiling, recurrent enterocolitis; (6) **Long-term follow-up** for functional outcomes; (7) **Genetic counseling** — 10-15% have RET mutation (also MEN2); other genes (EDNRB, EDN3); associated syndromes (Down, MEN2A, Waardenburg)

---

**Hirschsprung disease** — congenital absence of ganglion cells (Meissner + Auerbach plexus) in distal bowel → functional obstruction. Etiology: arrest of neural crest migration; genetic (RET, EDNRB, EDN3, GDNF). Associations: Down syndrome (most common — 5-15% Down have Hirschsprung), MEN2A (RET), Waardenburg-Shah. **Clinical**: 90% present in neonate with delayed passage meconium (> 48h), abdominal distention, bilious vomiting; relief with rectal exam (explosive release); failure to thrive; chronic constipation. **Diagnosis**: 1. Contrast enema: transition zone (proximal dilated, distal narrow aganglionic) — operator-dependent in neonates 2. Anorectal manometry: absent rectoanal inhibitory reflex (RAIR) 3. Rectal suction biopsy: absent ganglion cells + hypertrophic nerve trunks + calretinin neg (immunohistochemistry) — gold standard **Length of aganglionosis**: - Short segment (80% — rectosigmoid) - Long segment - Total colonic Hirschsprung (TCHA) - Total intestinal aganglionosis (rare, fatal without transplant) **Surgery options**: pull-through procedures — Swenson, Soave, Duhamel; modern TERPT (transanal endorectal pull-through). Single-stage in stable patients; staged for very ill / very young / long-segment. **HAEC (Hirschsprung-associated enterocolitis)** — serious complication preop or postop; clinical: fever, abdominal distention, foul stool, lethargy → treat: NPO, NG, antibiotic broad (metronidazole + cephalosporin), rectal irrigation aggressive.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'surgery'
  and scenario = 'ทารกแรกเกิดอายุ 36 ชม. ไม่ผ่าน meconium + ท้องอืด + อาเจียน feculent

Exam: explosive watery stool + flatus on rectal exam (digital examination relief)
Contrast enema: transition zone at sigmoid; dilated proximal + narrow distal
Rectal suction biopsy: aganglionosis in rectum';

update public.mcq_questions
set choices = '[{"label":"A","text":"Observation"},{"label":"B","text":"Incarcerated pediatric inguinal hernia — urgent management"},{"label":"C","text":"Outpatient referral 3 months"},{"label":"D","text":"Antibiotic only"},{"label":"E","text":"Discharge home, follow up 1 week"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** **Incarcerated pediatric inguinal hernia — urgent management**: (1) **Attempt manual reduction (taxis)** — sedation + analgesia + Trendelenburg + cold compress + gentle constant pressure; success rate > 80% in children; (2) **Successful reduction** → admit + observe 24h + **scheduled elective herniorrhaphy within 24-72h** (delayed re-operation has higher recurrence + complication); (3) **Failed reduction OR signs of strangulation** (peritonitis, sepsis, dark/edematous bulge, severe pain, irreducible after attempts) → **emergent surgical exploration**: high ligation of patent processus vaginalis (no mesh in children); assess viability of bowel / testis (in boys — testicular ischemia possible); resect non-viable bowel + primary anastomosis; (4) **Pediatric hernia repair**: high ligation alone (Marcy) — no mesh; very low recurrence (< 1-2%); laparoscopic increasingly utilized — allows contralateral inspection (5-10% have contralateral patent processus vaginalis); (5) **Postop**: monitor for testicular issues, recurrence, wound; (6) **Differentiate from communicating hydrocele**: transilluminates, reducible into peritoneum, often spontaneous resolution if simple; surgery for persistent > 12-24 mo

---

**Pediatric inguinal hernia** — most common pediatric surgery. Always indirect (patent processus vaginalis). Higher rate of incarceration in pediatric (5-20%) than adult, especially < 1 yr. **Boys** > girls (6-10:1), preterm > term (higher patent processus vaginalis). **Bilateral** — ~10% (more in preterm, family history). **Acute incarcerated hernia**: 1. Attempt taxis with sedation + analgesia + position (Trendelenburg) — success > 80% in pediatric 2. Successful → elective repair within 24-72h (don''t discharge — recurrence + complication risk) 3. Failed / strangulation → emergent surgery **Repair principles** (pediatric): - High ligation of hernia sac (patent processus vaginalis) — Marcy procedure - NO MESH (growing patient) - Open or laparoscopic — both acceptable; laparoscopic allows contralateral evaluation **Contralateral exploration**: controversial — laparoscopy allows easy inspection; if patent processus vaginalis on other side → repair concurrently (5-30% bilateral patent on lap evaluation). **Complications**: testicular atrophy / ischemia (10-20% incarcerated), recurrence (1-2%), wound infection. **Hydrocele** vs hernia in child: communicating hydrocele (patent processus vaginalis, fluid varies) — observe until 12-24 mo; if persistent → repair (same as hernia). Non-communicating — observe (resolves spontaneously).'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'surgery'
  and scenario = 'เด็กชายอายุ 2 ปี มา ED ด้วยอาการบวมที่ขาหนีบขวา 4 ชั่วโมง คลื่นไส้อาเจียน ร้องไห้ ไม่ยอมเดิน

Exam: tender erythematous bulge right inguinal region 3 cm, not reducible, no overlying skin changes severe, mild scrotal swelling
VS stable

คำถาม: management';

update public.mcq_questions
set choices = '[{"label":"A","text":"Observation indefinitely"},{"label":"B","text":"Thyroglossal duct cyst (TGDC) — surgical excision (Sistrunk procedure)"},{"label":"C","text":"Aspiration only"},{"label":"D","text":"Total thyroidectomy"},{"label":"E","text":"Radioactive iodine therapy"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** **Thyroglossal duct cyst (TGDC) — surgical excision (Sistrunk procedure)**: (1) **Confirm orthotopic thyroid present** — pre-op US thyroid to ensure not ''ectopic thyroid'' (rare — would result in iatrogenic hypothyroidism if excised); (2) **Sistrunk procedure**: excise cyst + middle portion of hyoid bone + tract to foramen cecum at tongue base — reduces recurrence from ~50% (simple excision) to ~5% (Sistrunk); developed by Sistrunk 1920; (3) **Pre-op**: thyroid function (TSH, free T4); imaging (US adequate; CT/MRI for atypical); FNA if suspicious or atypical features; (4) **Risk of carcinoma in TGDC** ~1% (papillary thyroid carcinoma most common type within TGDC); recommendations: total thyroidectomy + RAI if positive — controversial vs local Sistrunk alone with surveillance; refer to thyroid surgery if found; (5) **Differential**: thyroglossal duct cyst, ectopic thyroid, branchial cleft cyst (lateral), dermoid cyst, lymph node, lipoma; (6) Postop: surveillance for recurrence + wound

---

**Thyroglossal duct cyst (TGDC)** — most common congenital neck mass in children. Embryology: thyroid descends from foramen cecum at tongue base through hyoid bone to anterior neck; thyroglossal duct usually obliterates but may persist as cyst. **Clinical**: midline neck mass, anterior to hyoid bone (75%) or below; elevates with swallowing + tongue protrusion (anatomical attachment to hyoid); may become infected. **Diagnosis**: clinical + US (confirm cystic + identify orthotopic thyroid — critical before excision; ectopic thyroid in TGDC location = avoid resection, would cause hypothyroidism). **Sistrunk procedure**: excise cyst + central hyoid (1-2 cm) + tract to foramen cecum (tongue base) — historic + still gold standard. Recurrence with simple excision ~ 50%, Sistrunk ~ 5%. **Carcinoma in TGDC**: ~1% — papillary thyroid carcinoma most common (~75-80% of TGDC cancers); follicular, mixed; treat: Sistrunk + total thyroidectomy ± neck dissection ± RAI for high-risk features (controversy — some advocate Sistrunk alone + surveillance for small intracystic PTC). **Branchial cleft anomalies** (differential): 2nd most common, lateral neck (along SCM); 1st (preauricular, periotic), 2nd (most common, along SCM), 3rd (lower lateral), 4th (rare); excise complete tract.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'surgery'
  and scenario = 'เด็กหญิงอายุ 5 ปี มาด้วย neck mass anterior midline midway hyoid bone โต 1 ปี ไม่เจ็บ; เคลื่อนขึ้นลงเวลากลืน + protrude tongue

FNA: cyst with thyroid-like epithelium; no malignancy
US: cystic mass 2 cm anterior midline, separate from thyroid (normal thyroid orthotopic)

คำถาม: management';

update public.mcq_questions
set choices = '[{"label":"A","text":"Normal post-op finding, ignore"},{"label":"B","text":"Post-Nissen fundoplication complications"},{"label":"C","text":"Total gastrectomy"},{"label":"D","text":"PPI lifelong only"},{"label":"E","text":"No follow-up needed"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** **Post-Nissen fundoplication complications**: (1) **Dysphagia** — common transient (50% first 2-4 weeks) due to: edema at wrap, wrap too tight, wrap herniation, slipped wrap; (2) **Gas bloat syndrome** — inability to belch due to competent valve mechanism; common; usually improves over time; (3) **Pathophysiology of fundoplication**: 360° wrap around lower esophagus (Nissen) creates one-way valve preventing reflux but may restrict belching/vomiting; (4) **Investigations**: contrast esophagram (rule out slipped wrap, paraesophageal recurrence), EGD (visualize wrap, exclude obstruction), high-resolution manometry, pH study; (5) **Management**: - Conservative: dietary modification (small bites, chewing well, soft texture, no carbonation), pro-motility, time (resolves 4-8 wk typically) - Endoscopic dilation if persistent moderate (3-6 mo post-op) - Re-do surgery if persistent severe + anatomical issue (slipped, twisted, too tight) — convert Nissen to partial (Toupet 270° posterior, Dor 180° anterior) - Partial wraps (Toupet/Dor) have lower dysphagia but slightly higher reflux long-term; (6) **Selection**: severe dysmotility on manometry pre-op → consider partial wrap to begin with; (7) Patient counseling — most resolves

---

**Anti-reflux surgery (fundoplication)**: surgical treatment of GERD refractory / complicated. Options: - Nissen (360° complete wrap) — most reflux control, highest dysphagia - Toupet (270° posterior partial) — less dysphagia, reasonable reflux control - Dor (180° anterior partial) — used with Heller myotomy for achalasia, less reflux control - LINX (magnetic sphincter augmentation) — newer, restorative **Principles**: 1. Complete hiatal dissection 2. Crural repair (close hiatus) 3. Adequate intra-abdominal esophageal length (3-5 cm) 4. Wrap construction over bougie 5. Short floppy wrap (Donahue technique) **Complications**: - Dysphagia (transient 50%, persistent 5-10%) - Gas bloat — inability to belch - Slipped wrap (Nissen → migration above diaphragm) - Twisted wrap — anatomic distortion - Wrap dehiscence - Recurrent reflux **Pre-op evaluation essential**: EGD + manometry + pH study + esophagram to exclude motility disorder (achalasia, scleroderma) which contraindicates Nissen → use partial. **GERD surgical indication**: refractory medical therapy (PPI failure), complications (Barrett''s, stricture, recurrent aspiration), patient preference, large hiatal hernia, esophagitis with PPI tolerance issues. LOTUS trial — long-term PPI vs Nissen similar outcomes.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'surgery'
  and scenario = 'หญิงไทยอายุ 42 ปี post-laparoscopic Nissen fundoplication 3 วันก่อน complaining of new-onset persistent dysphagia ทุกครั้งที่ดื่มน้ำ + ไม่สามารถเรอได้ + gas bloat

คำถาม: pathophysiology + management';

update public.mcq_questions
set choices = '[{"label":"A","text":"Cancel surgery indefinitely"},{"label":"B","text":"Perioperative cardiac risk assessment + optimization"},{"label":"C","text":"Coronary angiography before all surgery"},{"label":"D","text":"Start beta-blocker day of surgery"},{"label":"E","text":"Stop all medications 2 weeks before"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** **Perioperative cardiac risk assessment + optimization**: (1) **Calculate cardiac risk** — RCRI (Revised Cardiac Risk Index — Lee): high-risk surgery, ischemic heart disease, HF, CVA, insulin-dependent DM, Cr > 2.0 — this patient: yes IHD, possible DM (insulin?), Cr (eGFR 40) → 2-3 points = intermediate to high (1-2% MACE) OR NSQIP MICA calculator; (2) **Functional capacity assessment** — METs > 4 = good; < 4 = poor (cannot climb 2 flights) — this patient marginal; (3) **Step-wise approach (ACC/AHA + ESC guidelines)**: - Emergent → proceed - Active cardiac condition (unstable angina, decompensated HF, severe valve dz, arrhythmia) → defer + treat - Low risk surgery + good MET → proceed - Intermediate-high risk + poor MET → consider non-invasive testing (stress test, echo) if results would change management; (4) **Investigations** consider: ECG, echo (LV function), stress test if poor MET + high-risk surgery; coronary angiography only if would change management (PCI before non-cardiac surgery NOT routinely indicated — DECREASE-V, CARP trials show no benefit of prophylactic revascularization); (5) **Medical optimization**: continue beta-blocker (if on chronic — DO NOT initiate new on day of surgery per POISE trial — increased stroke + death), statin continue, ACE-I hold on day of surgery (hypotension), antiplatelet management (aspirin continue per POISE-2 except for high bleed surgery; DAPT — delay surgery for elective until 6-12 months post-DES or 30 days BMS; bridging not routinely needed), DM control (sliding scale + adjusted long-acting; HbA1c < 8 ideal), CKD optimize, anemia treat (iron + EPO if needed); (6) **Counsel** + multidisciplinary; (7) Post-op: troponin surveillance in high-risk (MINS — myocardial injury after noncardiac surgery — associated with mortality)

---

**Perioperative cardiac risk assessment**: 1. RCRI (Lee): 6 factors — high-risk surgery (intraperitoneal, intrathoracic, suprainguinal vascular), ischemic heart disease, HF, CVA/TIA, insulin-dependent DM, preop Cr > 2.0 — 0 pts <1%, 1: 1%, 2: 2.4%, ≥3: >5% MACE 2. NSQIP MICA calculator — more individualized 3. Functional capacity (METs) — 4 METs = climb 2 flights, walk uphill briskly **Stepwise approach (ACC/AHA 2014, ESC 2022)**: - Emergent → proceed with optimal medical management - Active condition → defer + treat - Risk + functional capacity → testing only if would change management **Medical management evidence**: - Beta-blocker: continue if chronic; DO NOT initiate same day (POISE trial — death + stroke up) - Statin: continue / initiate beneficial - Aspirin: continue except if high-risk bleed (POISE-2) - ACE-I/ARB: hold day of surgery (hypotension) - Antiplatelet for stent: 30 days BMS, 6-12 mo DES delay elective; bridging not routinely needed - DM: hold sulfonylureas + meglitinides; metformin OK day before per CKD/contrast; insulin adjust - Anticoagulation: bridge per stratified risk (BRIDGE trial — most non-mechanical valve AF don''t need bridging) **Prophylactic revascularization** for asymptomatic CAD pre-op = NOT beneficial (CARP, DECREASE-V) **MINS** — myocardial injury after noncardiac surgery — troponin elevation alone (without symptoms) — high mortality; consider surveillance in high-risk.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'surgery'
  and scenario = 'ผู้ป่วยอายุ 65 ปี ได้รับการเตรียมการผ่าตัด elective colorectal surgery มา clinic ขอ pre-op evaluation

Underlying: HT, DM type 2 (HbA1c 8.2), CKD stage 3 (eGFR 40), prior MI 2 ปีก่อน on aspirin + clopidogrel + statin + beta-blocker; functional capacity 4 METs (walks 2 blocks)

คำถาม: pre-operative cardiac evaluation';

update public.mcq_questions
set choices = '[{"label":"A","text":"Treat in order of arrival"},{"label":"B","text":"Mass Casualty Incident (MCI) triage + trauma activation"},{"label":"C","text":"Send all to ICU regardless"},{"label":"D","text":"Discharge green patients home immediately without exam"},{"label":"E","text":"Operate on all 4 patients simultaneously"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** **Mass Casualty Incident (MCI) triage + trauma activation**: (1) **Pre-arrival**: full trauma team activation for red patient — surgeon, anesthesia, ER physician, OR availability, blood bank notified MTP, IR/CT availability; (2) **Triage system (START / Simple Triage and Rapid Treatment)** or SALT (Sort-Assess-Lifesaving-Treatment-Transport): - **Red (Immediate / T1)**: life-threatening, salvageable with immediate intervention (e.g., airway, breathing, circulation compromise) - **Yellow (Delayed / T2)**: serious but stable, can wait 30-60 min - **Green (Minor / T3)**: walking wounded, minimal injury - **Black (Expectant)**: dead or non-salvageable; (3) **JumpSTART** for pediatric (< 8 yr); (4) **Resource allocation**: red patients get immediate trauma bay + team; yellow next; green to alternative area; (5) **Activation criteria** (universal trauma criteria): physiologic (SBP < 90, GCS < 13, RR < 10 or > 29), anatomic (penetrating head/neck/torso/extremity proximal, flail chest, > 2 long bone fractures, paralysis, amputation), mechanism (high-velocity MVC, falls > 3 m, ejection, extrication > 20 min); (6) **MCI command**: incident command system (ICS), unified command if multi-agency, communication coordinator; (7) **Tertiary survey** after primary stabilization to detect missed injuries; (8) **Documentation, family notification, mental health support, debrief**

---

**Mass Casualty Incident (MCI) management** — system-level coordination required. **Triage systems**: 1. **START** (Simple Triage and Rapid Treatment) — adults, 30-second assessment: walking (green), respirations (rate, present/absent → red/black), perfusion (radial pulse, cap refill), mental status (commands) 2. **JumpSTART** — pediatric (< 8 yr or weight) — modifications for respiratory: 5 rescue breaths before declaring black 3. **SALT** (Sort-Assess-Lifesaving-Treatment-Transport) — global sorting → individual assessment → lifesaving interventions (airway, hemorrhage, decompression) → triage category → transport **Triage categories**: - **Red / Immediate / T1**: life-threatening salvageable - **Yellow / Delayed / T2**: serious, stable - **Green / Minor / T3**: minor injuries, ambulatory - **Black / Expectant**: dead or non-salvageable in available resources **Trauma team activation criteria** (Tier 1 — full activation): - Physiologic: SBP < 90, GCS ≤ 8 (or motor < 6), RR < 10 or > 29, need airway - Anatomic: penetrating to head/neck/torso, flail chest, > 2 long bone fractures, amputation proximal wrist/ankle, paralysis, crushed mangled extremity, pelvic fracture - Mechanism: high-velocity MVC, ejection, > 20 min extrication, fall > 6 m **Incident Command System (ICS)** — unified command structure; communication; logistics; safety; finance. **Resource management** — when overwhelmed, shift paradigm: ''greatest good for greatest number'' (vs individual patient focus).'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'surgery'
  and scenario = 'ทีม EMS วิทยุแจ้ง trauma center ว่า กำลังนำส่งผู้ป่วย MVC ระดับ red ที่ป่าจังหวัด ETA 20 min; multiple casualties 4 ราย ระดับความรุนแรงต่างกัน — ผู้ป่วย 1: GCS 8, hypotensive (red); ผู้ป่วย 2: GCS 15, ขาหัก (yellow); ผู้ป่วย 3: GCS 14, abdominal pain (yellow); ผู้ป่วย 4: walking wounded (green)

คำถาม: trauma team activation protocol + triage system';

update public.mcq_questions
set choices = '[{"label":"A","text":"Restart chemotherapy"},{"label":"B","text":"Post-gastrectomy nutritional deficiency syndrome + cancer survivorship — integrative multimodal care"},{"label":"C","text":"TPN lifelong"},{"label":"D","text":"Observation only"},{"label":"E","text":"Antibiotic prophylaxis"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** **Post-gastrectomy nutritional deficiency syndrome + cancer survivorship — integrative multimodal care**: (1) **Diagnose specific deficiencies + replete**: - B12: parenteral 1000 mcg IM (loading: weekly × 4, then monthly lifelong) — oral cannot absorb without intrinsic factor (loss with total gastrectomy) - Iron: IV iron (gastrectomy impairs absorption); avoid oral if malabsorption - Folate: oral 1-5 mg daily - Vit D + Ca: high dose oral 50,000 IU/wk + Ca 1,500 mg/day - Mg, Zn: oral repletion; monitor - Vit ADEK: empiric supplementation; (2) **Nutritional optimization**: dietician, small frequent high-protein high-calorie meals, enzyme support if needed; address dumping syndrome (small meals, low carb); (3) **Subacute combined degeneration** treatment — B12 repletion early; neurological recovery may be incomplete if delayed; (4) **Long-term surveillance for recurrence**: clinical, CT chest/abd q6 mo × 2 yr then annual × 5 yr, EGD periodically; CA 19-9 if elevated initially; (5) **Bone health**: DEXA, treatment of osteoporosis (bisphosphonate if T-score ≤ -2.5 or fragility fracture); (6) **Functional rehabilitation**: PT, OT, neuropathy management; (7) **Psychological support**: cancer survivorship clinic, peer support, mental health; (8) **Lifestyle**: exercise as tolerated, smoking cessation, moderate alcohol, vaccination (pneumococcal, influenza, COVID); (9) **Survivorship care plan** — written summary of treatment received + future surveillance + risk factors + lifestyle + contacts; (10) **Multidisciplinary**: oncology, surgery, nutrition, psychology, physical therapy, primary care

---

**Post-gastrectomy nutritional consequences** — chronic, lifelong. Deficiencies: - B12 — total gastrectomy eliminates intrinsic factor production → no B12 absorption → require parenteral lifelong - Iron — gastric acid + duodenal absorption impaired → IV iron or aggressive oral - Folate — variable; oral repletion - Vit D + Ca — duodenal absorption; oral supplementation - Fat-soluble vitamins (ADEK) — fat malabsorption with dumping/rapid transit - Mg, Zn, Cu — variable - Protein — low intake + malabsorption → weight loss, sarcopenia **Dumping syndrome** — early + late (see prior question) **Subacute combined degeneration**: B12 deficiency → dorsal column + lateral corticospinal tract demyelination → paresthesia, ataxia, weakness, cognitive impairment. Treat with B12 — neurological recovery may be incomplete if delayed > months. **Cancer survivorship**: surveillance for recurrence, second primary cancer, late effects of treatment (chemo neuropathy, cardiotoxicity, secondary malignancy from RT), physical fitness, psychological, lifestyle modification, vaccination, family genetic risk assessment. **Survivorship care plan** (IOM recommendation): written summary of treatment, surveillance schedule, late effects, lifestyle, contact information for transitioning care. Multidisciplinary survivorship clinics — integrate medical, nutritional, psychological, social, financial, vocational, sexual health.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'surgery'
  and scenario = 'ชายไทยอายุ 70 ปี ผ่า total gastrectomy + D2 dissection for advanced gastric cancer 18 เดือนก่อน + adjuvant chemotherapy completed

Now มาด้วยอาการ severe fatigue + weight loss + diarrhea + leg edema + paresthesia + difficulty walking + recurrent infection

Lab: Hb 8.4 (microcytic + macrocytic mixed), albumin 2.6, B12 80 (low), folate 3 (low), iron 18, ferritin low, vit D low, Ca low, Mg low, Zn low
MRI brain: subcortical demyelination consistent with subacute combined degeneration
No recurrence on imaging

คำถาม: integrative survivorship management';

update public.mcq_questions
set choices = '[{"label":"A","text":"Observation + repeat US 6 months"},{"label":"B","text":"Elective AAA repair indicated (≥ 5.5 cm men, ≥ 5.0 cm women, OR rapid growth > 0.5 cm/6 mo, OR symptomatic)"},{"label":"C","text":"Beta-blocker only"},{"label":"D","text":"Endovascular thrombolysis"},{"label":"E","text":"No treatment needed"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** **Elective AAA repair indicated (≥ 5.5 cm men, ≥ 5.0 cm women, OR rapid growth > 0.5 cm/6 mo, OR symptomatic)**: (1) **Pre-op evaluation**: cardiac risk (RCRI, stress test if poor MET — vascular = high-risk surgery), pulmonary, renal, optimize comorbidities + medications (statin, antiplatelet, BP control, smoking cessation absolute); (2) **EVAR (Endovascular Aneurysm Repair) — preferred first if anatomy suitable**: - Lower 30-day mortality (1.6% vs 4.7% open per EVAR-1, DREAM trials) - Less invasive, shorter LOS, faster recovery - Anatomic criteria: proximal neck ≥ 10-15 mm length, angulation < 60°, diameter < 32 mm; iliac access; (3) **Open repair alternative**: - Younger / longer life expectancy (durability advantage long-term) - Unsuitable anatomy for EVAR - Connective tissue disease (Marfan, EDS) - Surgeon/patient preference; (4) **Long-term EVAR surveillance**: CT at 1 mo + annually for endoleak (type I-V), sac size, migration; secondary intervention rate 10-20%; (5) **Open long-term**: less surveillance needed; (6) **Continued medical**: statin, antiplatelet, BP control lifelong + smoking cessation; (7) **Family screening** — first-degree relatives ≥ 60 OR younger if early-onset family history

---

**AAA — Abdominal Aortic Aneurysm**. Definition: ≥ 3 cm infrarenal aortic diameter. **Screening (USPSTF)**: one-time abdominal US in men 65-75 with smoking history. **Rupture risk by size**: < 4 cm: < 0.5%/yr; 4-5: 0.5-5%/yr; 5-6: 3-15%/yr; > 6 cm: 15-40%/yr. **Elective repair indications**: - ≥ 5.5 cm men, ≥ 5.0 cm women (lower threshold — higher rupture rate per size) - Rapid growth > 0.5 cm/6 mo or > 1 cm/yr - Symptomatic (pain, embolic, large) regardless of size - Inflammatory or mycotic — earlier repair **EVAR vs Open**: - EVAR-1 (Lancet 2005, 2016): EVAR lower perioperative mortality + early benefit but at 8 yrs equivalence then open better long-term (graft failure, secondary intervention) - DREAM (NEJM 2005, 2010): similar findings - OVER (NEJM 2012): no late benefit of open in 7 years - Modern era: EVAR ~ 70-80% of elective repairs **EVAR limitations**: anatomic criteria (proximal neck, iliac access, tortuosity); endoleak (type I-V); sac enlargement; need for lifelong surveillance + reintervention. **Open**: durable, no endoleak; higher perioperative morbidity. **Medical management of AAA**: statin, BP control (especially β-blocker — limited evidence for growth retardation), smoking cessation, exercise, diet. Surveillance for sub-threshold AAA: 3-3.9 cm q2-3 yr, 4-4.9 cm q6-12 mo, 5-5.4 cm q6 mo. A ผิด — meets criteria. C D ผิด — definitive repair needed. E ผิด.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'surgery'
  and scenario = 'ชายไทยอายุ 78 ปี smoker, HT, DM มา routine clinic วันนี้สังเกตเห็น pulsatile abdominal mass บริเวณ epigastrium

VS: BP 142/86, HR 76, asymptomatic
US abdomen screening: infrarenal AAA 5.8 cm diameter, no signs of impending rupture
CT angiography: 5.8 cm fusiform AAA, neck 18 mm length good, iliac access acceptable, no thrombus

คำถาม: management';

update public.mcq_questions
set choices = '[{"label":"A","text":"Observation 24 hr"},{"label":"B","text":"Acute Limb Ischemia (ALI) — Rutherford IIB (immediately threatened, motor + sensory deficit)"},{"label":"C","text":"Primary amputation"},{"label":"D","text":"Aspirin only"},{"label":"E","text":"Discharge home with follow-up"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** **Acute Limb Ischemia (ALI) — Rutherford IIB (immediately threatened, motor + sensory deficit)** — emergent intervention: (1) **Immediate anticoagulation** with IV heparin bolus + infusion (target aPTT 1.5-2.5 control); (2) **Etiology determination**: embolic (cardiac — AF, MI, valve; aneurysm; tumor) vs thrombotic (atherosclerotic, hypercoagulable, dissection, popliteal aneurysm thrombosis); this patient: thrombotic on atherosclerosis; (3) **Intervention timing**: Rutherford IIB (immediately threatened) requires intervention within hours (6-8h ideal — beyond → tissue death + reperfusion injury); (4) **Treatment options**: - **Surgical thromboembolectomy** (Fogarty catheter) — for embolic ALI; quicker hemostasis - **Endovascular catheter-directed thrombolysis (tPA, urokinase, alteplase)** + thrombectomy — for thrombotic ALI; 12-24h infusion; STILE, TOPAS trials support endovascular as comparable to surgery for limb salvage in selected; - **Hybrid procedure** (endo + open) — common in modern practice - **Bypass surgery** for chronic atherosclerotic occlusion with non-restorable in-situ flow; (5) **Compartment syndrome surveillance** post-revascularization — measure compartment pressures; fasciotomy if pressures elevated + symptoms or prolonged ischemia (> 4-6h); (6) **Reperfusion syndrome**: hyperkalemia (release K), acidosis, myoglobinuria → RHABDOMYOLYSIS — IV fluid, urinary alkalinization, monitor K, AKI prevention; (7) **Address underlying cause** — workup for source: ECG (AF), echo (thrombus, valve), screen for hypercoagulability; antiplatelet + statin lifelong + smoking cessation; (8) Rehab, secondary prevention

---

**Acute Limb Ischemia (ALI)** — sudden decrease in limb perfusion threatening viability. **6 Ps**: pain, pallor, pulselessness, paresthesia, paralysis, poikilothermia (cold). **Rutherford Classification**: - **I — viable**: not immediately threatened, no sensory/motor deficit; audible arterial Doppler - **IIA — marginally threatened**: mild sensory loss only, salvageable with prompt treatment; audible venous Doppler, inaudible arterial - **IIB — immediately threatened**: sensory + mild motor; salvageable with immediate intervention - **III — non-viable**: profound anesthesia + paralysis, irreversible damage; primary amputation **Etiology**: - Embolic (30%) — cardiac (AF 80%, MI, valve), proximal aneurysm, paradoxical, tumor - Thrombotic (40-50%) — atherosclerotic plaque rupture, bypass graft, popliteal aneurysm - Other: dissection, trauma, vasospasm, hypercoagulable **Management**: 1. Immediate IV heparin 2. Rutherford I/IIA — workup + planned intervention 3. Rutherford IIB — emergent intervention within 6h 4. Rutherford III — primary amputation (limb non-salvageable + reperfusion would cause systemic toxicity) **Intervention**: - Embolic → Fogarty thromboembolectomy (open) - Thrombotic → catheter-directed thrombolysis ± aspiration thrombectomy ± stent/bypass - Hybrid common **Reperfusion injury**: hyperkalemia, acidosis, myoglobinuria, AKI, compartment syndrome — anticipate, monitor, treat. Fasciotomy if compartment pressures elevated. Rhabdomyolysis: IV fluid 1-2 L/h initially, alkalinize urine (pH > 6.5), monitor K. A ผิด — Rutherford IIB ฉุกเฉิน. C ผิด — limb still salvageable. D ผิดอย่างยิ่ง. E ผิด.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'surgery'
  and scenario = 'ชายไทยอายุ 65 ปี HT, smoker มาด้วยอาการ unilateral severe limb pain + paresthesia + pallor + pulselessness 4 ชั่วโมง ของขาขวา + power 3/5

VS: BP 158/92, HR 92 (regular sinus), Temp 36.8°C
Leg: cold, pale right foot, no distal pulse, motor weakness, sensation reduced
ABI: not measurable
Doppler: no signal popliteal + distal
CT angiography: acute thrombotic occlusion right SFA + popliteal (likely on chronic atherosclerosis); other limb patent';

update public.mcq_questions
set choices = '[{"label":"A","text":"Warfarin start immediately"},{"label":"B","text":"Acute proximal DVT in pregnancy — LMWH (pregnancy-safe anticoagulation)"},{"label":"C","text":"DOAC (apixaban) immediately"},{"label":"D","text":"Aspirin only"},{"label":"E","text":"No treatment"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** **Acute proximal DVT in pregnancy — LMWH (pregnancy-safe anticoagulation)**: (1) **LMWH first-line** in pregnancy — enoxaparin 1 mg/kg SC q12h OR dalteparin — does not cross placenta, safe; (2) **Avoid**: warfarin (teratogen — embryopathy 1st trimester, fetal hemorrhage 3rd trimester), DOACs (limited safety data, cross placenta — avoid in pregnancy + breastfeeding), aspirin alone (insufficient); (3) **UFH alternative**: bridging if delivery imminent or invasive procedure planned (shorter half-life, reversible); (4) **Compression stockings** + ambulation as tolerated; (5) **Delivery planning** — multidisciplinary OB + hematology + anesthesia: - Discontinue LMWH 24h before scheduled induction / cesarean to allow neuraxial anesthesia (24h for therapeutic dose) - UFH bridging in interim if high VTE risk - Restart anticoagulation 12-24h post-delivery (4-6h post-neuraxial); (6) **Continue postpartum** total at least 6 weeks postpartum + total ≥ 3 months from DVT onset; (7) **Breastfeeding safe** with warfarin + LMWH (not DOACs); transition to warfarin or continue LMWH; (8) **IVC filter** only if contraindication to anticoagulation or recurrent VTE despite adequate anticoagulation; (9) **Future pregnancies** — prophylaxis with LMWH; (10) **Thrombophilia workup** post-pregnancy (factor V Leiden, prothrombin, protein C/S, antiphospholipid — clinical decision)

---

**VTE in pregnancy** — leading cause of maternal mortality in developed countries. Pregnancy = hypercoagulable state (factors VII, VIII, X, fibrinogen increase; protein S decrease; stasis from uterine compression). **Anticoagulation choice in pregnancy**: - **LMWH** — first-line, safe; doesn''t cross placenta; weight-based dosing - **UFH** — alternative, shorter half-life (useful pre-delivery, severe renal impairment); risk: HIT, osteoporosis with long-term use - **Warfarin** — TERATOGENIC (warfarin embryopathy: nasal hypoplasia, stippled epiphyses, CNS abnormality especially 6-12 wk gestation; fetal hemorrhage late pregnancy); SAFE postpartum + breastfeeding; mechanical valves may use cautiously - **DOAC (apixaban, rivaroxaban, dabigatran, edoxaban)** — avoid pregnancy + breastfeeding; cross placenta, limited safety data **Delivery planning**: - Discontinue therapeutic LMWH 24h before scheduled delivery (neuraxial anesthesia safety) - Resume LMWH 12-24h after vaginal delivery, 24-48h after cesarean - Convert to UFH near term for shorter washout flexibility - Bridge to warfarin postpartum if long-term needed **Duration**: minimum 3 months total + at least 6 weeks postpartum **Compression stockings** — adjunct, especially post-thrombotic syndrome prevention. **Thrombolysis** — only for life-threatening (massive PE with shock); pregnancy-specific risks (placental abruption, hemorrhage). **Surgical thrombectomy** — selected. **IVC filter** — only for true anticoagulation contraindication. **Prevention** in subsequent pregnancies — prophylactic LMWH if history VTE.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'surgery'
  and scenario = 'หญิงไทยอายุ 35 ปี G3P2 in third trimester (36 weeks) มาด้วยอาการ unilateral leg swelling + pain 2 วัน + low-grade fever

VS stable
Leg: left calf swollen 4 cm > right, tender, Homan''s positive
D-dimer 6,800 (elevated, expected in pregnancy)
US Doppler: extensive DVT left iliofemoral + femoropopliteal

คำถาม: management';

update public.mcq_questions
set choices = '[{"label":"A","text":"Pneumonectomy"},{"label":"B","text":"Stage IVA NSCLC adenocarcinoma EGFR-positive with oligometastatic brain disease — multidisciplinary curative-intent approach"},{"label":"C","text":"Chemo alone, no targeted"},{"label":"D","text":"Hospice referral"},{"label":"E","text":"Surgery alone, no systemic"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** **Stage IVA NSCLC adenocarcinoma EGFR-positive with oligometastatic brain disease — multidisciplinary curative-intent approach**: (1) **Multidisciplinary tumor board**: thoracic surgery, neurosurgery, radiation oncology, medical oncology; (2) **Systemic targeted therapy first-line** — **osimertinib** (3rd-generation EGFR TKI) — preferred per FLAURA trial (OS benefit vs 1st-gen TKI) + CNS penetration (treats brain mets in many); (3) **Brain metastasis management**: - Stereotactic radiosurgery (SRS) for 1-3 brain mets (preferred over WBRT — better cognitive preservation per N107C, NRG-CC003 trials) - Surgical resection for solitary larger met (> 3 cm, symptomatic, or for diagnosis); single brain met + controlled systemic = surgery + SRS to cavity reasonable - WBRT reserved for diffuse mets or salvage; (4) **Primary tumor + mediastinal** in oligometastatic setting — selected cases: - SBRT to primary if not surgical candidate - Surgical resection in highly selected (OMD — oligometastatic disease, well-controlled extracranial) per SABR-COMET and LungART evidence; (5) **Continued osimertinib** lifelong (until progression / intolerance); (6) **Surveillance**: CT chest q3 mo + brain MRI q3 mo first 2 yr; (7) **Second-line on progression**: tissue + plasma biopsy for resistance mechanism (T790M, C797S, MET amplification, transformation) → guide next therapy (amivantamab + lazertinib MARIPOSA; chemo + immunotherapy if non-driver); (8) **Smoking cessation, palliative care integrated, supportive

---

**Lung cancer (NSCLC)** — paradigm shift in advanced disease management. **Histology-driven + molecular-driven**: - Adenocarcinoma: EGFR, ALK, ROS1, KRAS G12C, BRAF V600E, MET ex14, RET, HER2, NTRK - Squamous: less driver mutations; FGFR, PIK3CA emerging - Small cell: chemo + IO **EGFR-mutant NSCLC**: - 1st-line: osimertinib (3rd-gen, FLAURA OS benefit, CNS active) - Resistance: T790M (1st-gen TKI resistance → osi), C797S, MET amplification, small cell transformation - Amivantamab + lazertinib (EGFR + MET bispecific + 3rd-gen TKI) emerging (MARIPOSA, MARIPOSA-2) **Oligometastatic NSCLC** (1-5 metastases, often single organ): - Aggressive local therapy (SBRT, surgery) + systemic — improved survival in selected (SABR-COMET, LungART) - Brain mets: SRS for 1-3 (preferred over WBRT — neurocognitive preservation per N107C); surgery for solitary large/symptomatic - Adrenal, liver, bone solitary mets — local therapy considered **Stereotactic Radiosurgery (SRS)** for brain mets — single high-dose radiation; preserves cognition vs WBRT; effective for ≤ 3 lesions ≤ 3-4 cm. **Surveillance** post local + targeted — q3 mo first 2 yr then q6 mo. **Liquid biopsy** (ctDNA) — useful for monitoring + identifying resistance non-invasively. A ผิด — pneumonectomy not for stage IV. C ผิด — EGFR+ benefits from targeted. D ผิด — curative intent feasible. E ผิด — systemic essential.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'surgery'
  and scenario = 'ชายไทยอายุ 68 ปี smoker ผ่าน CT incidental พบ lung nodule 1.8 cm RUL + 2 enlarged mediastinal lymph nodes + brain MRI: 1 lesion 1 cm frontal; PET: SUV 8 primary, SUV 4 mediastinum, brain enhanced

Bronchoscopy + biopsy: adenocarcinoma
Mutations: EGFR exon 19 deletion positive
PS 1
No other metastases

Clinical T1c N2 M1b (single brain met) Stage IVA';

update public.mcq_questions
set choices = '[{"label":"A","text":"Continue IV antibiotic alone"},{"label":"B","text":"Stage III (organized) pleural empyema — needs drainage + decortication"},{"label":"C","text":"Pneumonectomy"},{"label":"D","text":"Observation only"},{"label":"E","text":"Antifungal alone"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** **Stage III (organized) pleural empyema — needs drainage + decortication**: (1) **Light''s empyema staging**: - Stage I (exudative): thin fluid, free-flowing — thoracentesis or simple chest tube - Stage II (fibrinopurulent): loculated, fibrin deposition — chest tube + intrapleural fibrinolytic (tPA + DNase per MIST-2) - Stage III (organized): thick pleural peel, entrapped lung — VATS or open decortication; (2) **VATS decortication** preferred — first-line for stage II-III; lower morbidity than thoracotomy in selected; remove fibrinous peel + drain pus + re-expand lung; (3) **Open thoracotomy decortication** — failed VATS, dense adhesions, chronic disease; (4) **Continued IV antibiotic** — culture-directed (empyema flora — strep, staph including MRSA, anaerobes); duration 2-6 weeks typically; (5) **Chest tube + monitoring** post-op until drainage minimal + lung expanded; (6) **Treat underlying cause** — pneumonia, esophageal perforation (Boerhaave), thoracic surgery, trauma; (7) **Empyema necessitatis** — spontaneous extension to soft tissue/skin — drain + treat infection; (8) **Long-term**: monitor for restrictive deficit, recurrence; pulmonary rehabilitation

---

**Pleural empyema** — pus in pleural space, complication of bacterial pneumonia 5-10% (parapneumonic effusion 20-40%, empyema 5-10%). **Light''s criteria for exudative effusion**: protein ratio > 0.5, LDH ratio > 0.6, LDH > 2/3 ULN serum. **Empyema staging** (American Thoracic Society): - Stage I (exudative, 1-2 wk): clear fluid, low WBC, low protein, no loculation — drainage with thoracentesis OR small chest tube - Stage II (fibrinopurulent, 2-4 wk): thick fluid, loculations, fibrin — chest tube + intrapleural fibrinolytics (MIST-2: tPA 10 mg + DNase 5 mg BID × 3 days improves drainage + reduces surgery) - Stage III (organized, > 4 wk): thick pleural peel, entrapped lung — surgical decortication **VATS vs Open**: - VATS preferred first-line stage II-III if feasible — less morbidity, similar outcomes - Conversion to open if dense adhesions, anatomic difficulty - Open thoracotomy for chronic, failed VATS, complex anatomy **Antibiotic**: empiric cover community-acquired (strep, staph, anaerobes — amoxicillin-clavulanate, ceftriaxone + metronidazole, ampicillin-sulbactam); MRSA cover (vanco) if risk; nosocomial cover broader. Duration 2-6 weeks. **Drainage**: small-bore (12-14 Fr) effective for thin fluid; large-bore for thick pus; large-bore catheter (28-32 Fr) for empyema commonly. **Complications**: bronchopleural fistula, empyema necessitatis, restriction, sepsis. A ผิด — drainage essential. C ผิด — too radical. D E ผิด.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'surgery'
  and scenario = 'ชายไทยอายุ 55 ปี chronic empyema 6 สัปดาห์หลัง pneumonia ใช้ antibiotic IV หลายชนิดอยู่นาน

VS: BP 118/76, HR 88, Temp 38.0°C, SpO2 92% room air
Chest: dull percussion + decreased breath sound right base, no peritonitis
CT chest: right pleural empyema with loculated fluid + thickened pleura + entrapped lung
Thoracentesis: thick pus, gram-positive cocci, glucose < 40, pH 7.0, LDH 1,800

คำถาม: management';

update public.mcq_questions
set choices = '[{"label":"A","text":"CT pulmonary angiography immediately for all"},{"label":"B","text":"Suspected PE in pregnancy — stepwise diagnostic approach to minimize fetal radiation while excluding life-threatening PE"},{"label":"C","text":"D-dimer alone — exclude PE if low"},{"label":"D","text":"Empiric anticoagulation without imaging"},{"label":"E","text":"Observation only"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** **Suspected PE in pregnancy — stepwise diagnostic approach to minimize fetal radiation while excluding life-threatening PE**: (1) **Risk stratification**: clinical features (hemodynamic instability + tachypnea + hypoxia = high suspicion); (2) **First step — bilateral leg compression US Doppler** — if positive DVT (especially proximal) → diagnose VTE + treat (avoids further imaging); (3) **CXR (low radiation, mandatory)** — rule out other diagnoses (pneumothorax, pneumonia, etc.); (4) **If CXR normal → V/Q scan (preferred next per ESC + RCOG guidelines)** — perfusion-only scan (low ventilation portion sometimes omitted to reduce fetal dose); lower fetal radiation than CTPA but higher maternal breast dose; (5) **If CXR abnormal → CTPA** — better diagnostic in abnormal CXR; modern dose-reduced; fetal dose < 0.1 mGy (well below teratogenic threshold of 50 mGy); maternal breast dose higher than V/Q; (6) **Hemodynamically unstable** — bedside echo (RV strain), CTPA emergent regardless; (7) **Pregnancy-adapted YEARS or DiPEP** — algorithms incorporating clinical + D-dimer thresholds (adjusted in pregnancy) can safely exclude PE without imaging in low-risk; (8) **Diagnostic confirmation** → therapeutic LMWH (see prior question); (9) **MRI pulmonary angiography** — emerging but limited availability + sensitivity

---

**PE in pregnancy** — leading cause of maternal mortality. Pregnancy = hypercoagulable + venous stasis → high PE risk. **Diagnostic challenges**: - Symptoms (dyspnea, tachycardia) overlap with pregnancy physiology - D-dimer physiologically elevated (negative may exclude in low-risk; positive non-specific) - Imaging considerations: fetal radiation, maternal breast radiation (CTPA), iodinated contrast **Stepwise approach (ESC 2019, RCOG)**: 1. Clinical pre-test probability (Wells, Geneva, YEARS adapted for pregnancy) 2. Bilateral leg compression US Doppler — if proximal DVT positive → diagnose VTE + treat (no further imaging) 3. CXR — to rule out alternative diagnoses + guide next imaging 4. CXR normal → V/Q scan (perfusion-only modification reduces fetal dose) 5. CXR abnormal → CTPA 6. Hemodynamically unstable → emergent bedside echo + CTPA **Radiation exposure**: - Fetal dose: V/Q ~ 0.5 mGy, CTPA ~ 0.05-0.1 mGy (both well below 50 mGy teratogenic threshold) - Maternal breast dose: CTPA higher than V/Q (lifetime breast cancer risk consideration) **Pregnancy-adapted YEARS algorithm**: 3 clinical criteria (DVT signs, hemoptysis, PE most likely diagnosis) + D-dimer threshold adjusted — can rule out PE in 39% of pregnant women without imaging (Artemis study NEJM 2019). **CHEST + ASH guidelines** — supportive of risk-stratified approach + leg US first. **Treatment** if confirmed: LMWH (see prior question). A ผิด — first US legs. C ผิด — D-dimer alone insufficient. D ผิด — confirm diagnosis. E ผิดอย่างยิ่ง.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'surgery'
  and scenario = 'หญิงไทยอายุ 24 ปี G1P0 1st trimester 10 weeks gestation มาด้วยอาการ chest pain + dyspnea sudden onset 3 ชั่วโมง

VS: BP 92/58, HR 124, RR 28, SpO2 88% room air
Chest: clear breath sounds, no wheeze
Lab: D-dimer 4,200 (interpretation in pregnancy challenging — physiologically elevated)

คำถาม: diagnostic approach for suspected PE in pregnancy';

update public.mcq_questions
set choices = '[{"label":"A","text":"Standard management same as non-transplant"},{"label":"B","text":"Cancer in transplant recipient — increased risk + management nuances"},{"label":"C","text":"Stop all immunosuppression"},{"label":"D","text":"No treatment"},{"label":"E","text":"Sacrifice graft (allow rejection)"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** **Cancer in transplant recipient — increased risk + management nuances**: (1) **Multidisciplinary**: transplant nephrology, medical oncology, surgical oncology, infectious disease; (2) **Immunosuppression adjustment**: - Reduce overall immunosuppression cautiously — balance graft rejection vs cancer progression - Switch from calcineurin inhibitor (CNI — tacrolimus, cyclosporine: pro-cancer) to mTOR inhibitor (sirolimus, everolimus: anti-tumor effect, less malignancy risk) in selected — particularly for some cancers (skin, Kaposi''s) - Mycophenolate may continue at lower dose - Prednisone continue (avoid adrenal crisis); (3) **Surgical resection** of CRC: right hemicolectomy + standard oncologic resection; (4) **Liver met evaluation**: resectable oligometastatic → potentially resection; multidisciplinary; (5) **Adjuvant chemotherapy** — adjust dosing for renal function + drug interactions: - Tacrolimus + 5-FU/oxaliplatin (FOLFOX): monitor levels (5-FU may alter CNI metabolism) - Avoid nephrotoxic chemotherapy when possible; cisplatin avoid - Capecitabine may be preferred over IV 5-FU (oral, dose adjust renal); (6) **Targeted therapy considerations**: - Anti-EGFR (cetuximab/panitumumab) — KRAS mutated → NOT effective (excluded) - Anti-VEGF (bevacizumab) — wound healing + bleeding + HT issues; caution post-surgery - Immune checkpoint inhibitors (atezolizumab, pembrolizumab in MSI-H) — risk of graft rejection (controversial — may be considered with intensified monitoring; case series); (7) **Infection prophylaxis** intensified during chemo (PJP, CMV); (8) **Renal function monitoring** essential — adjust drug doses; (9) **Long-term**: increased risk other malignancies (skin — q6-12 mo dermatology, PTLD post-transplant lymphoproliferative disorder); (10) **Survivorship + palliation integration**

---

**Malignancy in transplant recipients** — 2-5 fold increased risk vs general population (immunosuppression + chronic inflammation + viral oncogenesis). **Common cancers post-transplant**: - Skin (especially SCC — UV + immunosuppression) - PTLD (post-transplant lymphoproliferative disorder — EBV-driven) - Kaposi''s sarcoma (HHV-8) - Cervical, anal (HPV) - Renal cell, urothelial (especially native kidney in failed transplant) - Colorectal, breast, lung — slightly increased **Management principles**: 1. **Immunosuppression modification**: - Reduce total burden cautiously - Switch CNI → mTOR inhibitor (sirolimus, everolimus) for certain cancers (less tumorigenic, mTOR has anti-tumor effect) - Consider rituximab for PTLD 2. **Standard oncologic care** with modifications: - Surgical resection — same principles - Chemotherapy — dose-adjust for renal/hepatic, drug interactions (CNI metabolism — azole, macrolide affect levels) - Radiation — same - Targeted therapy — case-by-case 3. **Immune checkpoint inhibitors** — controversial; graft rejection risk significant (40% in case series); requires careful selection, intensified monitoring, multidisciplinary; benefit may outweigh risk in selected aggressive cancers without alternatives 4. **Infection prophylaxis** — PJP, CMV, fungal — intensified during chemotherapy 5. **Screening + surveillance** — increased frequency for skin, cervical, anal, renal **PTLD** — most common post-transplant cancer (5-20% kidney recipients); EBV-driven B-cell proliferation; treat: reduce immunosuppression + rituximab + chemo if needed.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'surgery'
  and scenario = 'ผู้ป่วยอายุ 45 ปี post-renal transplant 5 ปี on tacrolimus + mycophenolate + prednisone มาด้วยอาการปวดท้องตื้อๆ 2 สัปดาห์ + 5 kg loss

US abdomen: cholelithiasis + GB wall 5 mm, mildly thickened, no fluid; suspicious mass at colon

CT abdomen: 3 cm mass right colon + few enlarged regional LNs + 2 liver lesions 1 cm each suspicious
Colonoscopy + biopsy: poorly differentiated adenocarcinoma, MSI-stable, KRAS mutated
Further staging: no other distant disease

คำถาม: management considerations in post-transplant patient';

update public.mcq_questions
set choices = '[{"label":"A","text":"Observation + IV fluid"},{"label":"B","text":"Postpartum Hemorrhage (PPH) — uterine atony most likely (80% of PPH cause)"},{"label":"C","text":"Discharge to ward"},{"label":"D","text":"Steroid IV"},{"label":"E","text":"Hysterectomy first-line"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** **Postpartum Hemorrhage (PPH) — uterine atony most likely (80% of PPH cause)**: (1) **Activate massive transfusion protocol** + 2 large-bore IV + type & crossmatch 4 units PRC + FFP + platelet 1:1:1 ratio; (2) **Identify cause — 4 Ts**: - **Tone** (atony 80%) — most common - **Trauma** (lacerations, hematoma, rupture) - **Tissue** (retained placenta, products) - **Thrombin** (coagulopathy); (3) **For uterine atony — stepwise**: a. **Empty bladder** (Foley) — bladder distention impairs uterine contraction b. **Bimanual uterine compression + massage** c. **Uterotonic medications**: - **Oxytocin** 10-40 units IV/IM (first-line) - **Methylergonovine** 0.2 mg IM q2-4h (avoid in HT) - **Carboprost (15-methyl PGF2α)** 250 mcg IM q15 min (avoid in asthma) - **Misoprostol** 800-1000 mcg PR/SL (alternative); (4) **TXA 1 g IV** within 3 hours (WOMAN trial — reduces mortality from bleeding); (5) **If atony persists** — uterine balloon tamponade (Bakri balloon) or condom catheter (low-resource); (6) **Surgical interventions if continued bleeding**: - Uterine artery embolization (IR — if available + stable enough) - B-Lynch suture (compression suture) - O''Leary uterine artery ligation - Internal iliac artery ligation - **Hysterectomy** — last resort but life-saving in massive hemorrhage; (7) **Resuscitation**: vasopressors, calcium replacement, fibrinogen monitoring (target > 200), avoid hypothermia, correct acidosis; (8) **Postpartum monitoring** ICU, monitor for Sheehan''s, DIC, organ dysfunction

---

**Postpartum Hemorrhage (PPH)** — leading cause of maternal mortality globally. **Definition**: blood loss ≥ 500 mL vaginal delivery, ≥ 1000 mL cesarean OR any blood loss with hemodynamic compromise. **4 Ts of PPH etiology**: 1. **Tone (70-80%)** — uterine atony — most common; risk factors: prolonged labor, multiparity, multiple gestation, polyhydramnios, chorioamnionitis, oxytocin use, magnesium sulfate 2. **Trauma (15-20%)** — lacerations (cervical, vaginal, perineal), hematoma, uterine rupture, inversion 3. **Tissue (10%)** — retained placenta, placental fragments, abnormal placentation (accreta) 4. **Thrombin (1%)** — coagulopathy (HELLP, AFE, sepsis, abruption, DIC) **Stepwise management of uterine atony**: 1. Bimanual massage + empty bladder 2. Uterotonics in sequence: oxytocin → methylergonovine → carboprost → misoprostol 3. TXA 1 g IV within 3h (WOMAN trial — Lancet 2017 — reduces death from bleeding by 1/3) 4. Mechanical: balloon tamponade (Bakri) 5. Surgical: compression sutures (B-Lynch), uterine artery ligation (O''Leary), internal iliac ligation, IR embolization 6. Hysterectomy — last resort **Massive transfusion**: 1:1:1 ratio PRC:FFP:Plt; calcium (citrate binds); avoid hypothermia; fibrinogen > 200 (cryo or fibrinogen concentrate). **Trauma sources**: inspect lower genital tract systematically; consider US/CT for hematoma. **Retained tissue** — manual removal, D&C, methotrexate for accreta spectrum (selected). **Coagulopathy** — workup (PT, aPTT, fibrinogen, platelets, TEG/ROTEM), correct deficits. A ผิด — active hemorrhage. C E ผิด. D ผิด — steroid ไม่ first-line.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'surgery'
  and scenario = 'หญิงไทยอายุ 32 ปี G3P2 immediate post-vaginal delivery 1 hr ago — มี profuse vaginal bleeding 1,500 mL persistent

VS: BP 78/48, HR 132, RR 24, alert
Fundus boggy, atonic, deviated to right
No lacerations evident, no retained products on examination

คำถาม: management of postpartum hemorrhage';

update public.mcq_questions
set choices = '[{"label":"A","text":"Esophagectomy for all Barrett''s with HGD"},{"label":"B","text":"Barrett''s esophagus with HGD + T1a intramucosal adenocarcinoma — endoscopic eradication therapy (organ-preserving)"},{"label":"C","text":"Observation alone"},{"label":"D","text":"Chemotherapy alone"},{"label":"E","text":"Total gastrectomy"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** **Barrett''s esophagus with HGD + T1a intramucosal adenocarcinoma — endoscopic eradication therapy (organ-preserving)**: (1) **Confirm pathology** — pathology review by GI pathologist; staging: EUS, CT chest/abd, PET; (2) **Endoscopic eradication therapy (EET)**: - **Endoscopic mucosal resection (EMR)** for nodular / focal lesion — both diagnostic (accurate staging — distinguish T1a from T1b) + therapeutic - **Endoscopic submucosal dissection (ESD)** — for larger / en-bloc resection of larger areas - **Radiofrequency ablation (RFA)** of residual flat Barrett''s — eradicates intestinal metaplasia + dysplasia - **Combination EMR + RFA** standard approach; (3) **Pathology criteria for endoscopic vs surgical management of T1**: - T1a (intramucosal): EET acceptable — low nodal risk (~2%) - T1b superficial (sm1, < 500 μm submucosal): EET selected centers vs surgery — controversial; nodal risk 7-15% if high-risk features (poor differentiation, LVI) - T1b deep (sm2-3): surgery (esophagectomy + lymphadenectomy) — high nodal risk; (4) **Post-EET surveillance**: EGD q3 mo × 1 yr, then q6 mo × 1 yr, then annual lifelong — detect recurrence; (5) **Long-term PPI** — high dose, lifelong; lifestyle modification; smoking cessation; weight loss; (6) **Family screening** — first-degree relatives with Barrett''s; (7) **Esophagectomy** if: ESD/EMR fails to achieve R0, T1b deep, multifocal HGD not amenable to EET, patient preference, recurrent dysplasia despite EET

---

**Barrett''s esophagus** — intestinal metaplasia in distal esophagus (premalignant). Risk factor for esophageal adenocarcinoma (lifetime ~3-5% for non-dysplastic Barrett''s; higher with dysplasia). **Surveillance**: 1. No dysplasia: EGD q3-5 yr 2. Low-grade dysplasia (LGD): EET (RFA preferred) OR EGD q6-12 mo with biopsies 3. High-grade dysplasia (HGD): EET (mandatory) OR esophagectomy 4. Intramucosal carcinoma (T1a): EET (preferred for organ preservation) 5. T1b superficial: EET vs surgery (case-by-case) 6. T1b deep (sm2-3) or higher: esophagectomy + lymphadenectomy **Endoscopic Eradication Therapy (EET)**: - **EMR/ESD** for nodular/focal lesions — provides accurate staging + treats lesion - **RFA** for flat Barrett''s — eradicates remaining intestinal metaplasia + dysplasia - **Cryotherapy** alternative for select - **Combination EMR + RFA** — most common approach **EET advantages over esophagectomy**: lower morbidity (mortality ~ 0.1% EET vs 2-5% esophagectomy), preserves esophagus + function, comparable oncologic outcomes for T1a + selected T1b. **EET success**: 80-90% complete eradication of dysplasia + intestinal metaplasia at 2 years; recurrence ~ 8-10%/yr → lifelong surveillance + PPI. **Esophagectomy** indications: failed EET, T1b deep, multifocal disease, high-risk features, patient preference. **Aspirin chemoprevention** for high-risk Barrett''s — AspECT trial showed slight benefit + acceptable safety profile.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'surgery'
  and scenario = 'ชายไทยอายุ 60 ปี GERD chronic 20 ปี, smoker, BMI 32 มา EGD พบ Barrett''s esophagus segment 4 cm + nodule 1 cm at GEJ; biopsy = high-grade dysplasia + intramucosal adenocarcinoma (T1a)

No lymphadenopathy on EUS, no distant disease on staging CT/PET

คำถาม: management of Barrett''s + early adenocarcinoma';

update public.mcq_questions
set choices = '[{"label":"A","text":"PPI long-term only"},{"label":"B","text":"Achalasia (classic — type I per Chicago Classification) — treatment options"},{"label":"C","text":"Esophagectomy first-line"},{"label":"D","text":"Observation + no treatment"},{"label":"E","text":"Antifungal only"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** **Achalasia (classic — type I per Chicago Classification) — treatment options**: (1) **Goal**: relieve obstruction at LES — symptomatic relief + prevent complications (megaesophagus, sigmoid esophagus, aspiration, esophageal Ca); (2) **Treatment options**: a. **Pneumatic dilation (PD)** — endoscopic dilation 30-40 mm balloon — graded; effective 50-90% short-term; perforation risk 2-5%; may repeat b. **Heller myotomy (laparoscopic) + partial fundoplication (Dor anterior 180° or Toupet posterior 270°)** — definitive surgery; division of LES muscle; fundoplication prevents post-op reflux; success 85-95%, durable c. **Per-Oral Endoscopic Myotomy (POEM)** — endoscopic incision of LES via submucosal tunnel; equivalent to Heller in short-medium term (POEM vs Heller trials Inoue, others); higher post-op reflux than Heller + fundoplication (no antireflux component — though anterior POEM may reduce); d. **Botox injection** to LES — 100 units endoscopic — temporary (3-6 mo); reserve for elderly / unfit / bridge; e. **Calcium channel blocker, nitrate** — limited efficacy, side effects; (3) **Choice depends on**: age, comorbidity, surgical fitness, achalasia subtype (II classic responds best to all, III spastic to POEM), patient preference, local expertise; (4) **Subtype-specific** (Chicago): - Type I (classic): all options - Type II (panesophageal pressurization): best response - Type III (spastic): POEM (longer myotomy) preferred; (5) **Long-term surveillance**: 10-fold increased esophageal SCC risk → EGD periodically; reflux surveillance post-procedure

---

**Achalasia** — primary esophageal motility disorder. Pathophysiology: loss of inhibitory ganglion cells in myenteric (Auerbach) plexus → failure of LES relaxation + absent peristalsis. Etiology mostly idiopathic; secondary (pseudoachalasia) from infiltrating malignancy at GEJ, Chagas disease (T. cruzi). **Clinical**: dysphagia (solids + liquids paradoxically — distinguishing from peptic stricture), regurgitation, chest pain, weight loss, aspiration. **Diagnosis**: 1. **Barium swallow** — bird''s beak narrowing + dilated esophagus + sigmoid esophagus (advanced) 2. **EGD** — exclude malignancy at GEJ (pseudoachalasia), assess esophagitis 3. **High-resolution manometry** — diagnostic + subtyping (Chicago Classification): - Type I: classic — failed relaxation + absent peristalsis (no pressurization) - Type II: panesophageal pressurization — best response to treatment - Type III: spastic contractions + failed relaxation **Treatment options**: 1. **Heller myotomy + partial fundoplication (laparoscopic)** — gold standard for surgical candidates; 85-95% effective, durable 2. **POEM** — endoscopic alternative; equivalent short-medium term; higher post-op reflux; preferred for type III (longer myotomy) 3. **Pneumatic dilation** — graded balloon; ~ 50-70% durable response; may need repeat; perforation risk 4. **Botox** — temporary, for non-operative candidates 5. **Medical** (CCB, nitrate) — limited efficacy **Post-treatment surveillance**: GERD (PPI), esophageal Ca risk (10-fold ↑ — surveillance EGD periodically). **End-stage achalasia** (megaesophagus, sigmoid): esophagectomy considered.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'surgery'
  and scenario = 'ชายไทยอายุ 50 ปี smoker, BMI 28 มาด้วยอาการ heartburn + regurgitation 5 ปี + dysphagia เป็นๆ หายๆ + วันนี้ regurgitation ของอาหารที่กินเมื่อ 6 ชั่วโมงก่อน + chest tightness severe

VS: BP 138/86, HR 102, RR 18, Temp 36.8°C
Chest: clear breath sound

EGD: severe dilation of distal esophagus + ''bird''s beak'' narrowing at GEJ + retained food + no esophagitis severe
High-resolution manometry: failed relaxation LES + absent peristalsis = achalasia (subtype I — classic)
Barium swallow: dilated esophagus + bird''s beak';

update public.mcq_questions
set choices = '[{"label":"A","text":"Observation + IV fluid"},{"label":"B","text":"Esophageal atresia with distal TEF (Gross type C, 85%) — staged management"},{"label":"C","text":"Total esophagectomy at birth"},{"label":"D","text":"Feeding through NG tube"},{"label":"E","text":"Discharge home"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** **Esophageal atresia with distal TEF (Gross type C, 85%) — staged management**: (1) **Pre-op stabilization**: - Head up 30-45° position - Suction esophageal pouch (Replogle tube — continuous low-pressure suction) - NPO - IV fluid + maintenance - Antibiotic prophylaxis (aspiration pneumonia risk) - Ventilator avoid high pressures (distends stomach via fistula → respiratory distress + aspiration); (2) **Workup for VACTERL association** (vertebral, anal, cardiac, tracheoesophageal, renal, limb) — echocardiogram (cardiac anomalies 30-40%, including R-sided arch — affects surgical approach), spine X-ray, renal US, anorectal exam, limb exam; (3) **Timing of surgery**: - Stable + term: primary repair within 24-72h - Premature / unstable / pulmonary issues: delayed primary repair (gastrostomy for feeding + fistula ligation as initial); (4) **Surgical approach**: - **Right thoracotomy** (or thoracoscopy in experienced centers) for left-sided aortic arch (most common — 95%) — extrapleural approach traditionally - **Left thoracotomy** if right-sided aortic arch (3-5% — important for echo screening pre-op); (5) **Repair**: - Ligate + divide TEF - Esophageal anastomosis end-to-end (primary if proximal/distal pouches reachable) - Long-gap atresia (> 3 vertebral bodies): staged — gastrostomy + delayed repair (4-12 wk) or esophageal lengthening (Foker procedure) or gastric pull-up / colon interposition for ultra-long-gap; (6) **Post-op complications**: anastomotic leak (10-20%), anastomotic stricture (~30% — endoscopic dilation), recurrent fistula (5-10%), GERD common (lifelong PPI often), tracheomalacia, dysphagia, motility disorder; (7) **Long-term**: pediatric GI follow-up, growth, neurodevelopmental, swallowing therapy

---

**Esophageal Atresia (EA) ± Tracheoesophageal Fistula (TEF)** — congenital. Incidence 1:3,000-4,500. **Gross Classification**: - Type A — Pure EA without TEF (~ 8%) — long gap - Type B — EA with proximal TEF (~ 1%) - Type C — EA with distal TEF (~ 85%) — most common - Type D — EA with both proximal + distal TEF (~ 1%) - Type E (H-type) — Isolated TEF without EA (~ 5%) — presents later **Presentation**: - Polyhydramnios prenatal (inability to swallow amniotic fluid) - Drooling, choking, cyanosis with feeding - Cannot pass NG tube (coils at pouch) - Type E may present later — recurrent pneumonia, choking with feeding **CXR findings**: - Coiled NG tube in upper pouch - Air in stomach = distal TEF present - No gas in abdomen = pure EA or proximal TEF only **VACTERL association**: - V — Vertebral - A — Anorectal (imperforate anus) - C — Cardiac (30-40%) - TE — Tracheoesophageal - R — Renal - L — Limb (radial — thumb) Screen with echo (priority), spine X-ray, renal US, anorectal exam, limb exam. **Pre-op stabilization** principles: head-up, continuous suction of upper pouch, NPO, avoid high-pressure ventilation. **Surgical approach**: right thoracotomy/thoracoscopy (left aortic arch — 95%); confirm aortic arch position by echo. **Long-term outcomes**: most do well with appropriate care. Long-term issues: GERD, dysphagia, anastomotic stricture, motility, tracheomalacia, growth.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'surgery'
  and scenario = 'ทารกแรกเกิดอายุ 12 ชั่วโมง มาด้วย excessive drooling + cyanosis with feeding + can''t pass NG tube into stomach (coil at upper esophagus)

CXR: NG tube coiled in upper esophagus + air in stomach (suggesting distal TEF)
Clinical diagnosis: esophageal atresia with distal tracheoesophageal fistula (TEF Type C — Gross — most common 85%)';

update public.mcq_questions
set choices = '[{"label":"A","text":"Bag-mask ventilation"},{"label":"B","text":"Congenital Diaphragmatic Hernia (CDH) — neonatal emergency, physiology-first stabilization before surgery"},{"label":"C","text":"Emergent operative repair within 1 hour"},{"label":"D","text":"Observation"},{"label":"E","text":"Total gastrectomy"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** **Congenital Diaphragmatic Hernia (CDH) — neonatal emergency, physiology-first stabilization before surgery**: (1) **Avoid bag-mask ventilation** (distends bowel in chest → worsens lung compression + cardiopulmonary compromise); (2) **Immediate intubation + gentle ventilation** — low pressure, permissive hypercapnia (PaCO2 50-70), preductal SpO2 > 85% acceptable; lung-protective; (3) **NG tube decompression** — empty stomach/bowel in chest; (4) **Pre-op stabilization** (''gentle ventilation'' era — physiologic stabilization first, surgery delayed until stable — improved outcomes): - Surfactant if preterm - Inotropes for hypotension - Pulmonary hypertension management: iNO (inhaled nitric oxide), sildenafil, milrinone - Persistent PHTN: ECMO bridge (criteria — preductal SpO2 < 85%, OI > 25, refractory hypotension); (5) **Workup for associations**: echocardiogram (cardiac anomalies common — 25%), chromosomal (trisomy 13, 18, 21), syndromes (CHARGE, Pallister-Killian); (6) **Surgical repair after stabilization** (typically days, not hours): - Approach: subcostal or laparotomy (more common in CDH) - Reduce abdominal contents from chest - Primary diaphragm closure (small defects) or patch repair (large defects) — Gore-Tex, biological mesh; - Liver position critical (intrathoracic liver = worse prognosis); (7) **Postop**: continued ventilator support, gradual weaning; PHTN monitoring; (8) **Long-term**: ~ 60-80% survival in modern era (depends on side, liver position, size of defect, associated anomalies); long-term issues: BPD, PHTN, GERD, growth delay, hearing loss, neurodevelopmental delay

---

**Congenital Diaphragmatic Hernia (CDH)** — defect in diaphragm allowing abdominal contents into chest → pulmonary hypoplasia + persistent pulmonary HTN. Incidence ~ 1:2,500. **Types**: - **Bochdalek (90%)** — posterolateral, more often left (80%) - **Morgagni (5%)** — anterior/retrosternal - **Central** (rare) **Pathophysiology**: - Pulmonary hypoplasia (both lungs, worse ipsilateral) - Persistent pulmonary hypertension (PPHN) — high resistance, R-to-L shunt - Heart compression + mediastinal shift **Presentation**: - Antenatal US — diagnostic - Birth: respiratory distress, scaphoid abdomen, barrel chest, bowel sounds in chest, decreased breath sounds **Management evolution**: ''Surgery is not the emergency, physiology is.'' - Pre-1990s: emergent surgery → high mortality - Modern: ''gentle ventilation'' + delayed surgery after stabilization → improved survival 1. **Immediate**: avoid bag-mask, intubate, NG decompression 2. **Ventilation**: low PIP (< 25), permissive hypercapnia (PaCO2 50-70), preductal SpO2 > 85% 3. **PPHN management**: iNO, sildenafil, milrinone, prostaglandin if ductal-dependent 4. **ECMO** for refractory: VV or VA; criteria include OI > 25, refractory hypotension, hypoxia 5. **Surgical repair** when stable (days, not hours): - Reduce viscera - Primary closure or patch (large defects) - Approach: abdominal (subcostal) most common 6. **Postop**: continued ventilation, weaning, PHTN monitoring 7. **Long-term**: ~ 60-80% survival; BPD, PHTN, GERD, scoliosis, growth, neurodevelopmental issues **Prognosis** depends on: lung size (LHR — lung-to-head ratio prenatal), liver position (intrathoracic liver = worse), associated anomalies. **Fetal intervention** (FETO — fetal endoscopic tracheal occlusion) — for severe CDH with high mortality risk; improves lung growth (TOTAL trial NEJM 2021).'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'surgery'
  and scenario = 'ทารกแรกเกิดอายุ 1 วัน มาด้วยภาวะ respiratory distress severe + scaphoid abdomen + barrel chest + bowel sounds in chest

CXR: bowel loops in left hemithorax + mediastinal shift to right + small RUL
ABG: pH 7.20, PaCO2 65, PaO2 50

คำถาม: management';

update public.mcq_questions
set choices = '[{"label":"A","text":"Continue oral feeding"},{"label":"B","text":"Necrotizing Enterocolitis (NEC) — Bell stage IIB (definite NEC with systemic signs + portal gas) — medical management"},{"label":"C","text":"Observation only"},{"label":"D","text":"Discharge home"},{"label":"E","text":"Whipple procedure"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** **Necrotizing Enterocolitis (NEC) — Bell stage IIB (definite NEC with systemic signs + portal gas) — medical management**: (1) **NPO + bowel rest** 7-14 days + NG decompression; (2) **TPN** — central venous access for parenteral nutrition; (3) **IV broad-spectrum antibiotics** — cover enteric flora + anaerobes — typically **ampicillin + gentamicin + metronidazole** OR meropenem alone — 7-14 days; (4) **Respiratory + circulatory support** as needed — mechanical ventilation, vasopressor, blood products (platelets often consumed); (5) **Serial abdominal exams + KUB q6-12h** — monitor for progression to perforation (free air → Bell stage III → surgical); (6) **Surgical indications** (Bell stage III): - Pneumoperitoneum (free air) - Worsening clinical despite medical - Palpable mass / fixed loops on serial X-ray - Erythema of abdominal wall - Hemodynamic instability; (7) **Surgical options**: - **Laparotomy + bowel resection** of necrotic + primary anastomosis OR diverting stoma + ''clip-and-drop'' (damage control) for damage control - **Primary peritoneal drainage (PPD)** in extremely premature/unstable — bedside placement of drain in RLQ; NEC NEONATAL Trial showed PPD + laparotomy comparable in some subgroups; (8) **Long-term complications**: short gut syndrome (extensive bowel loss), strictures (~ 20%), TPN-related liver disease, neurodevelopmental delay; (9) **Prevention** strategies: breast milk feeding (protective vs formula — NEC reduction), standardized feeding protocols, probiotics (controversial — some evidence), prevention of premature birth

---

**Necrotizing Enterocolitis (NEC)** — most common GI emergency of preterm infant. Incidence ~ 5-10% VLBW infants (< 1500 g). **Pathophysiology**: multifactorial — prematurity (immature gut barrier + immune), formula feeding (vs breast milk protective), enteral feeds advancement, intestinal ischemia, bacterial translocation, hypoxia-reperfusion. **Bell Staging**: - **I (suspected)**: clinical + non-specific imaging — supportive - **II (definite)**: A pneumatosis intestinalis on imaging; B + portal venous gas / systemic signs — NPO, IV abx, TPN, supportive - **III (advanced)**: A peritonitis + acidosis + DIC; B + perforation (pneumoperitoneum) — SURGICAL **Clinical**: feeding intolerance, abdominal distention, bilious aspirate, bloody stool, lethargy, temperature instability, apnea, bradycardia, shock. **Imaging**: pneumatosis intestinalis (pathognomonic), portal venous gas (advanced), fixed dilated loop, free air (perforation). Serial KUB essential. **Medical management** (Bell I-II): - NPO 7-14 days - TPN central line - Broad-spectrum antibiotics (ampicillin + gentamicin + metronidazole OR meropenem) - Decompress (NG) - Serial assessment - Blood products as needed **Surgical management** (Bell III): - Laparotomy + resection of necrotic bowel + stoma or primary anastomosis (depending on bowel length + viability + patient stability) - Primary peritoneal drainage (PPD) for unstable / extremely premature — drain alone; NECsteo + NEC NEONATAL trials show comparable outcomes in some subgroups - ''Clip-and-drop'' damage control: resect necrotic + temporary closure; second look 24-48h; restore continuity later **Outcomes**: mortality 20-30% overall; higher for surgical NEC + extreme prematurity. Long-term: short gut, strictures, neurodevelopmental delay (worse with surgical NEC). **Prevention**: human milk feeding (DOPPS evidence), standardized feeding advancement, probiotics (controversial), donor milk if mom''s unavailable.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'surgery'
  and scenario = 'ทารกแรกเกิดอายุ 1 วัน born premature 30 weeks GA, weight 1,400 g, ในวันที่ 5 มี feeding intolerance, abdominal distention, bloody stool

VS: BP 64/38, HR 168, Temp 36.0°C
Abdomen: distended, erythema over abdominal wall, sluggish bowel sounds, tenderness

Lab: WBC 18,000, Plt 80,000 (down from 230,000), CRP 78, lactate 4.2
KUB: pneumatosis intestinalis + portal venous gas + dilated bowel loops; no free air yet

คำถาม: management';

update public.mcq_questions
set choices = '[{"label":"A","text":"Observation"},{"label":"B","text":"Suspected Amniotic Fluid Embolism (AFE) — life-threatening obstetric emergency"},{"label":"C","text":"PPI alone"},{"label":"D","text":"Discharge home"},{"label":"E","text":"Antibiotic alone"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** **Suspected Amniotic Fluid Embolism (AFE) — life-threatening obstetric emergency**: (1) **Differential consideration**: AFE, PE, hemorrhage with DIC, sepsis, anaphylaxis, cardiac (MI, dissection), tension pneumothorax — but clinical context (peripartum, sudden hypoxia, hypotension, coagulopathy) → AFE most likely; (2) **AFE clinical triad**: sudden cardiovascular collapse + hypoxia + DIC during/immediately after labor/delivery; (3) **Diagnosis is clinical** (no specific test); pathology: fetal squames + lanugo + mucin in maternal circulation (postmortem); rule out other causes; (4) **Management — supportive multidisciplinary**: - **Resuscitation** ABC: intubate + mechanical ventilation, vasopressor (norepi + epinephrine), IV fluid cautiously; - **Hemodynamic support**: pulmonary vasodilators (iNO, sildenafil, milrinone) for RV failure; consider ECMO bridge for refractory cardiogenic shock + hypoxia; - **DIC management**: aggressive blood product replacement — PRC, FFP, platelets, cryoprecipitate (fibrinogen target > 200, low fibrinogen drives bleeding), TXA, factor concentrates; massive transfusion protocol; - **Atropine + ondansetron + ketorolac (A-OK regimen)** — emerging anecdotal supportive therapy for AFE (case series, not RCT) - **Address surgical bleeding** — uterine compression sutures, balloon tamponade, hysterectomy if uncontrolled; (5) **Mortality** 20-60% historically; modern aggressive management improves; survivors high morbidity (neurological, cardiac, hematologic); (6) **Postpartum care**: ICU, multidisciplinary (OB, ICU, hematology, cardiology); (7) **Counseling for future pregnancies** — recurrence rare but considered; case-by-case

---

**Amniotic Fluid Embolism (AFE)** — rare (1:8,000-1:80,000 deliveries) but catastrophic obstetric emergency. **Pathophysiology**: amniotic fluid components enter maternal circulation → pulmonary vascular obstruction + biphasic hemodynamic response (initial PHTN + RV failure → then LV failure) + anaphylactoid/inflammatory response + DIC. Modern understanding: more akin to anaphylaxis (anaphylactoid syndrome of pregnancy) than embolic obstruction. **Clinical features (sudden, peripartum or up to 30 min postpartum)**: - Severe hypotension - Hypoxia - Coagulopathy / DIC - Altered mental status, seizures - Cardiac arrest (uncommon presenting feature) **Diagnosis** — clinical, exclude alternatives. No pathognomonic test. **Management — supportive**: 1. ABC: intubate, mechanical ventilation 2. Aggressive hemodynamic support: vasopressors (norepi, epinephrine), inotrope, IV fluid (judicious — RV failure) 3. Pulmonary vasodilators (iNO, sildenafil, milrinone, prostacyclin) for RV failure 4. ECMO (VA) for refractory cardiogenic shock 5. Massive transfusion (PRC:FFP:Plt 1:1:1) + cryoprecipitate (fibrinogen target > 200) + TXA 6. Treat ongoing surgical bleeding 7. Multidisciplinary (OB, ICU, anesthesia, hematology) **A-OK regimen** (atropine, ondansetron, ketorolac) — anecdotal, proposed mechanism: blunt vagal + serotonin + thromboxane response; not RCT-proven. **Mortality**: 20-60% historic; better in modern centers. Survivors significant morbidity. Recurrence in future pregnancy uncertain — likely low but counsel risk.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'surgery'
  and scenario = 'หญิงไทยอายุ 28 ปี ผ่า cesarean section 6 ชั่วโมงก่อน มาขอ consult ICU เพราะปวดท้อง + tachycardia + tachypnea + hypoxic

VS: BP 84/52, HR 138, RR 32, SpO2 86%, Temp 37.8°C
Gen: alert but distressed
Lab: D-dimer 8,000, Hb 9.2 (preop 11), fibrinogen 100 (low), platelets 80,000, INR 1.8, troponin 0.04
ECG: sinus tach
CXR: bilateral pulmonary edema
Echo: RV dilation, decreased RV function, no IVC collapse

คำถาม: differential diagnosis + management';

commit;
