-- ===============================================================
-- UPDATE chunk 8/8: ob_gyn (25 questions)
-- ===============================================================

begin;

update public.mcq_questions
set choices = '[{"label":"A","text":"Maternal immune system rejects fetus"},{"label":"B","text":"Maternal-fetal immunology"},{"label":"C","text":"Methotrexate"},{"label":"D","text":"All autoimmune worsens in pregnancy"},{"label":"E","text":"Hysterectomy"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Maternal-fetal immunology: (1) **fetus = semi-allograft** (50% paternal antigens); maternal immune system tolerates rather than rejects via multiple mechanisms; (2) **maternal-fetal interface** — trophoblast (no classical HLA-A/B, expresses HLA-G/E/F + non-classical), decidua (specialized immune cells), syncytiotrophoblast barrier; (3) **immune tolerance mechanisms**: (a) **regulatory T cells (Tregs)** ↑ — anti-inflammatory; (b) **Th1/Th2 shift** — Th2-biased (anti-inflammatory) during pregnancy; (c) **HLA-G on trophoblast** — inhibits NK + T cells; (d) **uterine NK cells** (uNK — different from peripheral NK) — promote spiral artery remodeling, support not attack trophoblast; (e) **indoleamine 2,3-dioxygenase (IDO)** — depletes tryptophan, inhibits T cell; (f) **progesterone** — immunomodulatory (PIBF, regulates cytokines); (g) **complement regulation** — DAF, MCP, CD59 on trophoblast prevent complement-mediated damage; (4) **trimester immune phases** — 1st trimester pro-inflammatory (implantation), 2nd trimester anti-inflammatory (growth), 3rd trimester pro-inflammatory (labor preparation); (5) **autoimmune diseases** — variable: (a) **flare/improve** — RA often improves (Th2 shift), SLE variable, MS often improves, AS may worsen; (b) **postpartum flares common** — return to baseline immune state; (c) **thyroiditis postpartum** common; (6) **alloimmune complications**: (a) **Rh isoimmunization** — IgG anti-D crosses placenta — hemolytic disease of newborn; (b) **fetal/neonatal alloimmune thrombocytopenia (FNAIT)** — anti-HPA-1a IgG; (c) **neonatal lupus** — anti-Ro/La cross placenta — congenital heart block; (d) **antiphospholipid syndrome (APS)** — recurrent loss, thrombosis; (7) **infection susceptibility** — pregnancy ↑ severity of certain (influenza, varicella, listeria, malaria, COVID-19) due to altered immunity; (8) **vaccines** — inactivated safe (flu, Tdap, COVID); live attenuated avoided (MMR, varicella — pre-pregnancy or postpartum); (9) **HIV** — pregnancy doesn''t worsen disease; vertical transmission key concern; (10) **HELLP/preeclampsia** — abnormal trophoblast invasion + immune dysregulation

---

Maternal-fetal immunology: tolerance via Tregs, Th2 shift, HLA-G, uNK, IDO, progesterone, complement regulation. Trophoblast invasion. Trimester phases. Autoimmune variable in pregnancy; postpartum flares. Alloimmune: Rh, FNAIT, neonatal lupus, APS. Infection susceptibility (flu, listeria, COVID). Inactivated vaccines safe.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'ob_gyn'
  and scenario = 'Resident ถามอาจารย์เรื่อง maternal immunology + tolerance of fetus + autoimmune in pregnancy';

update public.mcq_questions
set choices = '[{"label":"A","text":"Skip data collection"},{"label":"B","text":"Maternal Mortality + Severe Morbidity Review systems"},{"label":"C","text":"Hide data"},{"label":"D","text":"Methotrexate"},{"label":"E","text":"Refuse review"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** **Maternal Mortality + Severe Morbidity Review systems**: (1) **Maternal Mortality Review Committee (MMRC)** — multidisciplinary committee (OB, midwife, anesthesia, ICU, pathology, public health, social work, community); review all maternal deaths within 1 yr of pregnancy; (2) **case identification** — ICD coding, hospital reports, death certificates, vital statistics linkage, lay report; (3) **review process** — abstract chart + interviews (clinicians, family if appropriate), classify cause + pregnancy-relatedness + preventability + contributing factors (clinician, system, patient, social), identify opportunities + recommendations, track implementation; (4) **classification systems** — WHO ICD-MM (direct, indirect, incidental, unspecified); pregnancy-related vs pregnancy-associated (any cause, expanded definition); (5) **WHO ''Three Delays'' framework** — delay seeking care (knowledge, finances, family), delay reaching care (transport, distance), delay receiving care (facility readiness, staff, supplies); guide system interventions; (6) **near-miss + severe maternal morbidity (SMM)** also reviewed — wider lens for learning (deaths small numerator); (7) **data registry** — standardized variables, anonymized, secure, longitudinal, linked to vital records + neonatal outcomes; (8) **public reporting + accountability** — disaggregated by region/SES/race/ethnicity; address disparities; (9) **action-oriented** — implementation, training, policy change, AIM bundle adoption, telemedicine, transport network; (10) **legal protections** — peer review + confidentiality + immunity from discoverability (varies by jurisdiction; Thai context evolving); (11) **WHO ICD-MM coding standardization**; (12) **integration with global** — Maternal Mortality Estimation Inter-agency Group (MMEIG), UN SDG 3.1 (reduce maternal mortality < 70/100,000 by 2030); Thai progress noted; (13) **community engagement + family disclosure** ethically; (14) **continuous quality improvement cycle (PDSA)** — review → recommendations → implement → measure → re-review

---

MMRC: multidisciplinary review of maternal deaths + SMM. WHO Three Delays framework. Identify preventable + system factors. Data registry. Public reporting + equity. Action-oriented. Legal protections. SDG 3.1 target. Continuous quality improvement.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'ob_gyn'
  and scenario = 'Thai Ministry establishes National Maternal Mortality Review Committee (MMRC) + perinatal data registry';

update public.mcq_questions
set choices = '[{"label":"A","text":"Quality measures useless"},{"label":"B","text":"Obstetric Quality Measures + Performance Dashboards"},{"label":"C","text":"Hide data from clinicians"},{"label":"D","text":"Methotrexate"},{"label":"E","text":"Refuse measurement"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** **Obstetric Quality Measures + Performance Dashboards**: (1) **rationale** — what''s measured improves; benchmarking; transparency + accountability + patient choice; reimbursement (US — value-based purchasing); (2) **process measures** — antenatal steroids for preterm, GBS prophylaxis, antibiotic timing pre-incision C/S, immediate postpartum LARC, prenatal CRT/PE workup, screening (depression, IPV, GDM); (3) **outcome measures** — NTSV C-section rate (CMS benchmark < 23.6%), VBAC rate, episiotomy rate (Cochrane → restrictive), birth trauma, OASIS, postpartum hemorrhage > 1500 mL, blood transfusion, severe maternal morbidity (CDC 21 indicators), maternal mortality, ICU admission, exclusive breastfeeding rate, neonatal Apgar < 7, NICU admission, perinatal mortality, severe HT treatment within 60 min, ECV success; (4) **balancing measures** — ensure no unintended harm (e.g., reducing C/S doesn''t ↑ perinatal mortality); (5) **patient-reported** — Patient-Reported Outcome Measures (PROM) — birth experience, postpartum recovery, breastfeeding satisfaction; (6) **safety culture** — AHRQ Safety Attitudes Questionnaire; (7) **collaboratives** — California Maternal Quality Care Collaborative (CMQCC) — AIM bundle implementation + benchmarking; AIM nationwide; Joint Commission Perinatal Care measures; Leapfrog; (8) **data governance** — definitions standardized (NTSV = nulliparous + term + singleton + vertex, denominator), risk adjustment, data quality audit; (9) **public reporting** — Hospital Compare (US); CMS Hospital Compare; (10) **provider feedback** — individual + group; bell curve discussions; coaching; (11) **PDSA cycles** — small tests of change; (12) **dashboards real-time** — EMR integration, alerts; (13) **Thai context** — RTCOG quality initiatives, MOPH HA accreditation; (14) **equity** — disaggregate by sociodemographic; address disparities; (15) **rewards/recognition** + financial alignment

---

OB quality measures: process + outcome + balancing + patient-reported. NTSV C/S, severe HT timing, exclusive BF, OASIS, transfusion, SMM. CMQCC + AIM + Joint Commission. Dashboards + real-time + risk adjusted. Feedback + PDSA. Equity disaggregation. Thai HA accreditation.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'ob_gyn'
  and scenario = 'Hospital implements obstetric quality measure dashboards (NTSV C-section, episiotomy, blood transfusion, severe hypertension treatment timeliness, exclusive breastfeeding)';

update public.mcq_questions
set choices = '[{"label":"A","text":"Cesarean immediately"},{"label":"B","text":"Distinguishing SLE flare vs preeclampsia in pregnancy"},{"label":"C","text":"Methotrexate"},{"label":"D","text":"Discharge home"},{"label":"E","text":"Hysterectomy"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** **Distinguishing SLE flare vs preeclampsia in pregnancy** — both can present with HT + proteinuria + thrombocytopenia + renal dysfunction — but management + prognosis differ; **may co-exist** — treat both: (1) **features favoring SLE flare**: (a) **complement low (C3/C4)** — falls in active SLE; complement usually NORMAL or ↑ in preeclampsia; (b) **anti-dsDNA rising** — SLE; (c) **active extra-renal manifestations** — arthritis, rash, serositis, hematologic; (d) **urine sediment active** — cellular casts (red cell, granular), dysmorphic RBC; (e) **uric acid normal-to-low** in SLE vs ↑ in preeclampsia; (f) **timing** — can occur any gestation in SLE; preeclampsia after 20 wk; (g) **hypertension less prominent** in flare; (2) **features favoring preeclampsia**: (a) **uric acid markedly elevated**; (b) **normal/↑ complement**; (c) **AST/ALT ↑** (HELLP), LDH ↑ (hemolysis), low fibrinogen; (d) **no active SLE serology**; (e) **fetal growth restriction** with abnormal Doppler; (f) **after 20 wk**; (g) **sFlt-1/PlGF ratio elevated** > 38 (helpful biomarker); (3) **this patient** — low complement + ↑ anti-dsDNA + active SLE serology + uric acid 7.5 borderline → favors **flare more than pure preeclampsia, but may co-exist + severe HT**; (4) **management** — (a) **treat HT** acutely — labetalol/hydralazine; (b) **MgSO4** seizure prophylaxis (if severe features), neuroprotection (< 32 wk); (c) **↑ immunosuppression for flare** — pulse methylprednisolone 500-1000 mg × 3 d if severe lupus nephritis; ↑ azathioprine; continue HCQ + low-dose prednisone; cyclophosphamide avoided pregnancy; mycophenolate avoided; (d) **renal biopsy** rarely needed pregnancy — defer if possible; (e) **fetal surveillance** + delivery planning — at 26 wk balance prematurity vs disease — steroid course + may extend stabilization, but deliver if maternal/fetal deterioration; (f) **postpartum** — high flare risk continues; continue immunosuppression; (5) **multidisciplinary** — rheum + MFM + nephrology + neonatology; (6) **future pregnancy** — preconception planning + control × 6 mo + safer meds + aspirin

---

SLE flare vs preeclampsia: low complement + ↑ anti-dsDNA + active SLE serology + normal uric acid → flare. ↑ uric acid + AST/ALT + sFlt-1/PlGF + abnormal Dopplers → preeclampsia. May co-exist. Treat both. Pulse steroid for flare. MgSO4 + antihypertensive for PE. Multidisciplinary. Preconception planning future.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'ob_gyn'
  and scenario = 'หญิงตั้งครรภ์ G2P1 GA 26 wk underlying SLE on stable HCQ + low-dose prednisone — มาด้วยอาการ acute new onset BP 160/100, proteinuria 4+, severe headache, plt 110K + Cr 1.1 — รบกวน distinction between SLE flare vs preeclampsia

V/S: BP 160/100, HR 96, RR 18
Gen: malar rash unchanged + arthritis mild active
Fetal: FHR 144 reactive, EFW 750 g (10th percentile — borderline)
Lab: plt 110 (down from 240 baseline), AST/ALT WNL, Cr 1.1, uric acid 7.5, urine protein/Cr 4.5, anti-dsDNA elevated × 3-fold from baseline, low C3/C4, anti-Ro/La positive (known), aPL negative';

update public.mcq_questions
set choices = '[{"label":"A","text":"Discharge home"},{"label":"B","text":"Postpartum stroke (ischemic) with large vessel occlusion"},{"label":"C","text":"Methotrexate"},{"label":"D","text":"Hysterectomy"},{"label":"E","text":"Refuse imaging"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** **Postpartum stroke (ischemic) with large vessel occlusion** — postpartum hypercoagulable + preeclampsia/eclampsia/HT + cardiac (PPCM) + autoimmune + amniotic fluid embolism + cervical artery dissection (Valsalva push) + RCVS + cerebral venous sinus thrombosis (CVST): (1) **time-critical activation ''stroke code''**; (2) **ischemic stroke + large vessel occlusion + within window**: (a) **IV thrombolysis (tPA alteplase)** — within 4.5 hr — postpartum bleeding contraindication relative (consider risk-benefit); MTP 6 d post-delivery → caution; (b) **endovascular thrombectomy** — within 6-24 hr (DAWN/DEFUSE-3); preferred in postpartum (avoids systemic lysis); (3) **manage BP** — permissive HT up to 220/120 if not thrombolysis candidate (avoid hypoperfusion); if thrombolysis < 185/110; (4) **rule out + treat alternative causes**: (a) **postpartum cerebral angiopathy / reversible cerebral vasoconstriction syndrome (RCVS)** — thunderclap headache, segmental vasoconstriction, calcium channel blocker; (b) **cerebral venous sinus thrombosis (CVST)** — headache + papilledema + seizure → CTV/MRV → anticoagulation LMWH; (c) **PRES (posterior reversible encephalopathy)** — HT + visual + seizure + occipital edema → control BP + seizure; (d) **eclampsia** even postpartum (up to 6 wk); MgSO4 + BP; (5) **workup** — echo (cardiac embolic source — PPCM, valve), Doppler carotid, hypercoagulable + APS, autoimmune; (6) **anticoagulation** — depends on etiology (CVST yes, embolic source yes after acute, aspirin for non-cardioembolic ischemic); LMWH postpartum preferred; (7) **rehabilitation** — early; long-term recovery; (8) **breastfeeding** — most meds compatible; (9) **psychosocial + childcare** — significant family impact; social work; (10) **future pregnancy** — recurrence risk; multidisciplinary planning + LMWH thromboprophylaxis; (11) Thai stroke network + EMS

---

Postpartum stroke: ischemic + hemorrhagic; ↑ risk first 6 wk. Causes — HT/PE, hypercoag, PPCM, AFE, RCVS, dissection, CVST. Stroke code. tPA + thrombectomy (postpartum bleed risk — risk-benefit). Distinguish RCVS, CVST, PRES, eclampsia. Anticoag depends on etiology. Breastfeeding mostly compatible. Future pregnancy planning.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'ob_gyn'
  and scenario = 'หญิงอายุ 28 ปี G1P1 NSD 5 d ago — มาห้องฉุกเฉินด้วยอาการอ่อนแรงครึ่งซีก L + พูดไม่ชัด + ปวดศีรษะรุนแรง + ตามัวข้างซ้าย

V/S: BP 168/108, HR 96, RR 18
Gen: alert but confused
Neuro: L hemiparesis + dysarthria + L homonymous hemianopia
Fetal/Baby: at home with family, breastfeeding
CT brain: R MCA territory hypodense + no hemorrhage
CTA: R MCA M1 occlusion';

update public.mcq_questions
set choices = '[{"label":"A","text":"Force termination"},{"label":"B","text":"Perinatal palliative care for lethal fetal anomaly"},{"label":"C","text":"Hysterectomy"},{"label":"D","text":"Methotrexate"},{"label":"E","text":"Refuse care"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** **Perinatal palliative care for lethal fetal anomaly** — family-centered, individualized: (1) **multidisciplinary team** — MFM + neonatology + nursing + chaplain + social worker + bereavement counselor + perinatal palliative care specialist if available + family; (2) **respectful counseling** — present options (termination if legal + within Thai law, continue with palliative perinatal care); validate choice; explore meaning + values; (3) **birth plan creation** — preferences for delivery (vaginal preferred, avoid C/S for non-survivable, except maternal indication), pain management, monitoring during labor (limited interventions per family), presence of family, religious/cultural rituals, memory making (footprints, photos, memory box), naming, baptism/blessing, breastfeeding/colostrum if desired; (4) **maternal care** — routine ANC with attention to maternal complications (polyhydramnios from anencephaly — preterm labor, PROM, dystocia), maternal mental health (high risk depression + PTSD + grief), social support; (5) **monitoring** — minimal fetal monitoring (no interventions for fetal distress); maternal monitoring intact; (6) **labor + delivery** — usually term but may be earlier; vaginal delivery preferred; consider amnioreduction if symptomatic polyhydramnios; oxytocin + epidural standard; avoid C/S unless maternal indication (no fetal benefit); (7) **at birth** — focus on comfort + family bonding; no resuscitation per advance plan; warm wrap, hold, time as long as desired; pain management for infant (morphine, comfort); allow death naturally with dignity; (8) **postpartum** — lactation suppression options (or donor milk if desired), bereavement support, memorial, follow-up; future pregnancy counseling — recurrence risk + folate 4 mg + screening; (9) **community + cultural** — Thai Buddhist rituals, family practices, respectful integration; (10) **bereavement counseling** — perinatal loss support groups; complicated grief screening; (11) **multidisciplinary debrief** + staff support (moral distress); (12) **legal/documentation** — birth + death certificates, autopsy if family wishes, genetic counseling; (13) **whole family** — siblings, grandparents — pediatric/child life support

---

Perinatal palliative care: multidisciplinary, family-centered. Birth plan, memory making, comfort care at birth. Vaginal delivery preferred; avoid C/S without maternal indication. Polyhydramnios mgmt for symptomatic. Bereavement + future pregnancy counseling (recurrence + folate). Cultural integration. Staff support for moral distress.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'ob_gyn'
  and scenario = 'หญิงอายุ 28 ปี G2P1 GA 24 wk — fetal anencephaly (lethal anomaly) confirmed on US — couple opts to continue pregnancy with palliative perinatal care

V/S: BP 116/72, HR 76
Gen: well, supportive partner + family
Fetal: confirmed anencephaly + acrania + polyhydramnios mild + otherwise grossly normal
Lab: amniotic fluid AFP high, no other anomaly';

update public.mcq_questions
set choices = '[{"label":"A","text":"Discharge home"},{"label":"B","text":"Acute Fatty Liver of Pregnancy (AFLP)"},{"label":"C","text":"Methotrexate"},{"label":"D","text":"Hysterectomy"},{"label":"E","text":"Wait for liver to recover before delivery"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** **Acute Fatty Liver of Pregnancy (AFLP)** — rare but life-threatening (mortality 10-20% maternal, 20-30% perinatal) — microvesicular fatty infiltration of hepatocytes; 3rd trimester typically; associated with **fetal LCHAD deficiency** (long-chain 3-hydroxyacyl-CoA dehydrogenase — fetal fatty acid oxidation defect → toxic intermediates to mother); **Swansea criteria** (≥ 6 of 14): vomiting, abdominal pain, polydipsia/polyuria, encephalopathy, ↑ bilirubin, hypoglycemia, ↑ urate, leukocytosis, ascites/bright liver, ↑ transaminases, ↑ ammonia, ↑ Cr, coagulopathy, microvesicular steatosis on biopsy; (1) **differential** — HELLP (overlapping), severe preeclampsia, viral hepatitis (AVH), drug-induced, TTP, intrahepatic cholestasis of pregnancy (ICP — usually milder), acute viral hepatitis; (2) **management — STAT delivery** is definitive (do not delay for steroids in stable; deliver promptly): (a) **stabilize** — correct hypoglycemia (D10 infusion), correct coagulopathy (FFP, cryo, plt, vit K), correct electrolytes, blood products; (b) **MgSO4** seizure prophylaxis (often co-exists with preeclampsia features); (c) **antihypertensive** if needed; (d) **deliver** — mode per obstetric — vaginal if feasible + safe, C/S if compromised; consider preinduction maternal stabilization; (e) **multidisciplinary** — MFM + hepatology + ICU + neonatology; (3) **postpartum** — supportive in ICU; usually improves over days-weeks; liver transplant for fulminant failure (rare); monitor + correct coagulopathy; (4) **neonatal — test for LCHAD deficiency** — newborn screen + acylcarnitine + genetic; if affected → MCT-based diet + restriction long-chain fatty acids; (5) **future pregnancy** — recurrence ~ 20-70% if mother heterozygous + partner heterozygous + fetus homozygous → counsel + prenatal testing; (6) **counseling** + family support

---

AFLP: rare, life-threatening. Hypoglycemia + coagulopathy + ↑ bilirubin/transaminases + ↑ urate + AKI. Swansea criteria. Fetal LCHAD deficiency association. STAT delivery is definitive after stabilization. Correct hypoglycemia + coagulopathy. ICU. Neonatal LCHAD screen. Recurrence ~ 20-70%.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'ob_gyn'
  and scenario = 'หญิงตั้งครรภ์ G2P1 GA 32 wk underlying chronic HT + GDM — มาด้วยอาการ malaise + nausea + ปวด RUQ × 3 d + jaundice mild × 1 d

V/S: BP 138/86, HR 102, RR 18, Temp 37.0
Gen: jaundiced + RUQ tenderness + no encephalopathy
Fetal: FHR 158 reactive, EFW 1,650 g (50th)
Lab: AST 580, ALT 480, total bilirubin 5.2, glucose 52 (hypoglycemia!), plt 95K, INR 1.6, fibrinogen 180, Cr 1.3, uric acid 8.5, urine protein 1+
US abdomen: liver echogenic (fatty)';

update public.mcq_questions
set choices = '[{"label":"A","text":"Cesarean immediately without TPE"},{"label":"B","text":"Thrombotic Thrombocytopenic Purpura (TTP) in pregnancy"},{"label":"C","text":"Methotrexate"},{"label":"D","text":"Discharge home"},{"label":"E","text":"Hysterectomy"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** **Thrombotic Thrombocytopenic Purpura (TTP) in pregnancy** — pentad: hemolytic anemia + thrombocytopenia + neurologic + renal + fever (often incomplete); **ADAMTS13 < 10% activity** + anti-ADAMTS13 IgG → acquired (immune-mediated) TTP; distinguish from severe preeclampsia/HELLP, AFLP, HUS, DIC, sepsis-DIC, APS catastrophic — overlapping features but ADAMTS13 deficit pathognomonic; (1) **STAT plasma exchange (TPE)** — daily 1.5× plasma volume with FFP replacement → removes anti-ADAMTS13 Ab + replaces ADAMTS13 + vWF cleaving; continue until plt > 150K × 2 d + clinical improvement; (2) **corticosteroid** (prednisolone 1 mg/kg/d) — adjunct immunosuppression; (3) **caplacizumab** (anti-vWF nanobody) — new effective; pregnancy data limited, individual risk-benefit; (4) **rituximab** — for refractory + relapsing — used in pregnancy with consideration; (5) **avoid platelet transfusion** unless life-threatening bleeding (theoretical worsens microthrombi); RBC + FFP OK; (6) **fetal monitoring**; (7) **delivery timing** — TTP itself not indication for delivery; treat TTP first; deliver per obstetric indications; if fetal compromise + TTP severe → multidisciplinary decision; (8) **multidisciplinary** — hematology + MFM + nephrology + neuro + ICU; (9) **postpartum** — continue treatment; recurrence ~ 30% in next pregnancy → close monitoring + prophylactic plasma infusion; (10) **congenital TTP (Upshaw-Schulman)** — inherited ADAMTS13 deficit — recurrent in pregnancy → prophylactic FFP infusion; (11) **differential** — preeclampsia/HELLP improves with delivery (TTP usually doesn''t); AFLP has hypoglycemia + coagulopathy; HUS — Shiga toxin or atypical (complement-mediated); APS — antiphospholipid Ab; (12) **mortality** untreated > 90%, with TPE < 20%

---

TTP in pregnancy: pentad (anemia + thrombocytopenia + neuro + renal + fever — often incomplete). ADAMTS13 < 10% + Ab → acquired TTP. STAT TPE + steroid (+ caplacizumab/rituximab). Avoid plt transfusion. Distinguish from HELLP/AFLP/HUS/DIC. Delivery per obstetric — not TTP indication. Recurrence high. Mortality high untreated.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'ob_gyn'
  and scenario = 'หญิงอายุ 26 ปี G1P0 GA 28 wk underlying healthy — มาด้วย hemolytic anemia + thrombocytopenia + AKI + altered mental status

V/S: BP 132/82, HR 110, Temp 37.4
Gen: petechiae + jaundice + altered mental status (confused)
Fetal: FHR 144 reactive
Lab: Hb 7.2, MCV 90, retic 8%, schistocytes ++, plt 15K, LDH 1,800, haptoglobin < 8, indirect bilirubin 4.5, Cr 2.8 (was 0.6), ADAMTS13 activity < 10% (severely reduced), anti-ADAMTS13 IgG positive, AST/ALT mildly ↑, INR normal, fibrinogen 320';

update public.mcq_questions
set choices = '[{"label":"A","text":"Forced termination"},{"label":"B","text":"Cervical cancer in pregnancy"},{"label":"C","text":"Methotrexate"},{"label":"D","text":"Discharge — wait until delivery without further workup"},{"label":"E","text":"Hysterectomy at 18 wk without considering options"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** **Cervical cancer in pregnancy** — multidisciplinary GYN-onc + MFM + neonatology + family — individualized: (1) **multidisciplinary discussion + patient preference** (desire to continue pregnancy, GA, stage, growth pattern); (2) **early pregnancy (< 22-24 wk) with early-stage**: (a) **delay treatment to fetal viability** if microscopic/early IA-IB1 stable + close monitoring (clinical + MRI q 4-8 wk); deliver 34-37 wk + post-delivery definitive surgery (radical hysterectomy or CRT); (b) **immediate treatment** (treatment supersedes pregnancy) for advanced or rapidly progressive — chemotherapy 2nd-3rd trimester (cisplatin + paclitaxel safer than CRT in pregnancy) → delay surgery to postpartum + adjuvant; (c) **termination if family chooses** + definitive treatment; (3) **later pregnancy (≥ 22-24 wk)**: (a) wait for fetal lung maturity, antenatal steroids 24-34 wk, deliver 34-37 wk (or earlier ถ้า progression) → C/S + radical hysterectomy en bloc at same operation, or staged; (b) avoid radiation in pregnancy ถ้า possible; (4) **fertility-sparing trachelectomy** — not feasible during pregnancy typically; (5) **delivery mode** — **cesarean** preferred to avoid vaginal birth (theoretical tumor seeding + bleeding); vaginal previously thought OK for very early lesion but C/S safer; (6) **at C/S** — radical hysterectomy + pelvic lymphadenectomy + BSO consideration based on age + path (preserve ovaries young if reasonable); send ovarian mass to frozen — likely benign physiologic at this GA; (7) **adjuvant** — RT + cisplatin per indications postpartum; (8) **lymph node assessment during pregnancy** — sentinel LN (technetium-99m safe), pelvic LND if needed; some delay; (9) **counseling** — survival similar to non-pregnant matched; fetal outcomes good with planned management; psychological + multidisciplinary support; (10) **chemotherapy in pregnancy 2nd-3rd trimester** — generally accepted safety for limited regimens (cisplatin, paclitaxel)

---

Cervical cancer in pregnancy: multidisciplinary + individualized. Early GA + early stage: delay until viability, antenatal steroid, C/S + radical hysterectomy. Chemo 2nd-3rd tri (cisplatin/paclitaxel) if needed. Avoid RT pregnancy. C/S preferred mode. Sentinel LN. Counseling + family choice — termination option.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'ob_gyn'
  and scenario = 'หญิงอายุ 34 ปี G1P0 GA 18 wk routine US — finding ovarian mass 6 cm complex on R + Pap smear last year ASCUS HPV+, colposcopy + biopsy: invasive SCC of cervix Stage IB1 (tumor 2.5 cm)

V/S: BP 116/72, HR 80
Gen: well
Fetal: anatomy scan normal otherwise, growth appropriate
MRI pelvis: cervical tumor 2.5 cm, no parametrial involvement, no nodal involvement; ovarian mass complex 6 cm — separately, R, likely physiologic vs benign
No metastasis on CXR';

update public.mcq_questions
set choices = '[{"label":"A","text":"Hysterectomy"},{"label":"B","text":"Asherman Syndrome (intrauterine adhesions)"},{"label":"C","text":"Methotrexate"},{"label":"D","text":"Discharge home"},{"label":"E","text":"Antibiotic alone"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** **Asherman Syndrome (intrauterine adhesions)** — fibrous bands in endometrial cavity → menstrual abnormalities, infertility, pregnancy complications; etiology: D&C (most common, esp post-miscarriage/postpartum), infection (TB, schistosomiasis), surgery, radiation: (1) **classification** — March/AFS (mild/moderate/severe by extent + type); ESH/Hamou; (2) **diagnosis** — HSG (filling defects), SIS, **hysteroscopy gold standard** (direct + treatment); (3) **treatment — hysteroscopic adhesiolysis** — scissors, hook, monopolar/bipolar — preserve healthy endometrium; outpatient or staged for extensive; (4) **prevention of recurrence post-adhesiolysis** — variable methods (no single proven best): (a) **intrauterine device/balloon** — Foley balloon or IUD for 1-2 wk to keep walls separated; (b) **hyaluronic acid gel** intracavitary; (c) **estrogen therapy** — high-dose estrogen (conjugated estrogen 5 mg/d or estradiol 4 mg/d) × 4-8 wk → stimulate endometrial regrowth; (d) **second-look hysteroscopy** at 6-8 wk to lyse new adhesions; (5) **stem cell / G-CSF** — emerging therapies for endometrial regeneration; (6) **fertility outcomes** — depend on severity + initial endometrial damage; ~ 60-90% restoration of menses; pregnancy 30-70%; (7) **pregnancy complications post-Asherman** — preterm, FGR, abnormal placentation (accreta — implantation on scar), abortion → close monitoring; (8) **counseling** — recurrence, fertility outcomes, alternative parenthood options (gestational surrogacy if severe); (9) **prevention** — D&C avoidance when possible (use medical management for early miscarriage), gentle technique, postpartum care; (10) **co-existing infertility workup** — semen, ovulation, tubes

---

Asherman: intrauterine adhesions from D&C/infection. Diagnosis: hysteroscopy. Treatment: hysteroscopic adhesiolysis + prevent recurrence (balloon, hyaluronic gel, estrogen, second-look). Pregnancy complications: preterm, FGR, accreta. Prevention: avoid unnecessary D&C, gentle technique. Surrogacy if severe.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'ob_gyn'
  and scenario = 'หญิงอายุ 32 ปี G2P0A2 prior 2 D&C for missed abortion — มาด้วยอาการประจำเดือนไม่มา 1 yr post-D&C + cyclic pelvic pain + infertility, β-hCG negative

V/S: BP 116/72, HR 78
Gen: well
Pelvic: WNL
Lab: TSH normal, prolactin normal, FSH 6, LH 4, AMH 3.2 normal, β-hCG negative
HSG: filling defects + irregular cavity outline (suggesting adhesions)
Hysteroscopy: extensive intrauterine adhesions involving > 75% cavity';

update public.mcq_questions
set choices = '[{"label":"A","text":"Methotrexate"},{"label":"B","text":"Hyperandrogenism with virilization + ovarian mass"},{"label":"C","text":"PCOS — treat with COCP"},{"label":"D","text":"Hysterectomy"},{"label":"E","text":"Antibiotic alone"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** **Hyperandrogenism with virilization + ovarian mass** — workup for **androgen-secreting tumor** (ovarian or adrenal); high testosterone + virilization signs (rapid onset, deep voice, clitoromegaly, balding) → likely ovarian: (1) **differential**: (a) **ovarian — Sertoli-Leydig cell tumor (most common androgen-secreting), thecoma, hilus cell tumor, granulosa cell**; (b) **adrenal — adenoma, carcinoma**; (c) **PCOS** — typically lower T < 150, slower onset, no virilization; (d) **non-classic CAH** — 17-OHP elevated post-ACTH stim; (e) **Cushing''s** — cortisol; (f) **exogenous** — anabolic steroids, DHEA supplements; (2) **workup** — **DHEAS high → adrenal**; **testosterone very high → ovarian**; both → adrenal carcinoma; **17-OHP basal + ACTH-stim** for CAH; **dexamethasone suppression test** for Cushing; (3) **imaging** — TVS + MRI pelvis (ovarian); CT/MRI adrenal; sometimes selective venous sampling for occult source; (4) **management — surgical removal**: (a) **ovarian Sertoli-Leydig** — unilateral salpingo-oophorectomy + staging (frozen section); fertility-sparing in young; (b) bilateral if perimenopausal/completed family; (c) **adrenal mass** — adrenalectomy with workup of malignancy; (d) **histology** — guides adjuvant; (5) **post-removal** — androgens normalize within weeks; virilization improves but voice + balding may not regress fully; (6) **counseling** — fertility preservation (egg cryopreservation if anticipated bilateral surgery), psychological support; (7) **follow-up** — recurrence + tumor markers (inhibin); (8) **cosmetic + dermatology** — laser hair removal, eflornithine cream for residual hirsutism; (9) **HRT** if surgical menopause; (10) Sertoli-Leydig — DICER1 mutation association → genetic counseling

---

Severe hyperandrogenism with virilization + rapid onset + T > 150 → androgen-secreting tumor (Sertoli-Leydig ovarian or adrenal). Workup DHEAS, testosterone, 17-OHP, dexamethasone. Imaging. Surgical removal. Sertoli-Leydig DICER1 association. Fertility preservation. Cosmetic adjunct. Distinguish from PCOS (lower T, slow onset, no virilization).'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'ob_gyn'
  and scenario = 'หญิงอายุ 24 ปี nulligravid มา OPD ด้วยอาการ hirsutism progressive + acne refractory + voice deepening + clitoromegaly + amenorrhea 6 mo × 1 yr

V/S: BP 134/86, HR 80
Gen: temporal balding, deep voice, hirsutism Ferriman-Gallwey 18, clitoromegaly mild
Lab: testosterone total 220 (markedly elevated; PCOS usually < 150), DHEAS WNL, 17-OHP normal, β-hCG negative, TSH normal, prolactin normal, FSH 5, LH 8, cortisol normal, ACTH-stim 17-OHP normal
US pelvis: R ovarian mass 4 cm solid + hypervascular
MRI: R ovarian solid mass with vascular pedicle, no metastasis';

update public.mcq_questions
set choices = '[{"label":"A","text":"Refuse care"},{"label":"B","text":"Vulvodynia (vulvar pain without identifiable cause ≥ 3 mo)"},{"label":"C","text":"Methotrexate"},{"label":"D","text":"Hysterectomy"},{"label":"E","text":"Antibiotic alone"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** **Vulvodynia (vulvar pain without identifiable cause ≥ 3 mo)** — diagnosis of exclusion; subtypes: (a) **localized provoked vestibulodynia (LPV)** — pain at vestibule with provocation (Q-tip, intercourse); (b) **generalized unprovoked** — burning vulva; mixed; (1) **diagnosis** — clinical + exclude infection (culture, wet mount), dermatosis, hormonal, neuropathic, neoplasia, trauma; (2) **multimodal management — biopsychosocial**: (a) **vulvar care** — avoid irritants (perfumed soap, panty liners, tight clothes), cotton underwear, lubricants, sitz baths; (b) **topical** — lidocaine 5% ointment (esp before intercourse), topical estrogen (if atrophy), topical compounded amitriptyline-baclofen-gabapentin; (c) **systemic** — TCAs (amitriptyline 10-50 mg QHS), SNRIs (duloxetine, venlafaxine), gabapentin/pregabalin (titrate, slow) — for neuropathic; (d) **pelvic floor physical therapy** — high-evidence intervention — relieve hypertonic pelvic floor; biofeedback; dilators; (e) **psychotherapy** — CBT, mindfulness, sex therapy, couples therapy; address coping + relationship; (f) **interventional** — pudendal nerve block, trigger point injection, **Botox injection** (refractory); (g) **surgical — vestibulectomy** for refractory LPV (success ~ 70-90% select cases) — partial vestibulectomy + perineorrhaphy; (h) **complementary** — acupuncture, hypnotherapy; (3) **chronic pain syndromes co-occur** — IBS, fibromyalgia, IC/PBS, endometriosis, vaginismus, chronic fatigue → comprehensive approach; (4) **mental health screening** — depression, anxiety, sexual abuse history; (5) **counseling + education** — validate, partner involvement; (6) **multidisciplinary** — gyn + PFPT + mental health + pain specialist; (7) **support groups** — National Vulvodynia Association; (8) **NEVER** dismiss as psychological — real pain disorder

---

Vulvodynia: diagnosis of exclusion. LPV vs generalized. Multimodal: vulvar care, topical lidocaine, TCAs/SNRIs/gabapentin, PFPT (high evidence), CBT/sex therapy, Botox/vestibulectomy refractory. Mental health screening + chronic pain comorbidity. Validate + multidisciplinary. Don''t dismiss.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'ob_gyn'
  and scenario = 'หญิงอายุ 38 ปี nulligravid มา OPD ด้วยอาการ vulvar burning pain × 6 mo + dyspareunia + tender to touch + no visible lesion + Q-tip test positive at vestibule + no infection + no skin disease

V/S: BP 122/76, HR 78
Gen: anxiety, no depression
Vulva: normal-appearing, no erythema/lesion, Q-tip test exquisitely tender at vestibule
Wet mount: WNL, KOH negative, culture negative';

update public.mcq_questions
set choices = '[{"label":"A","text":"One dose OTC cream + done"},{"label":"B","text":"Recurrent Vulvovaginal Candidiasis (RVVC, ≥ 4 episodes/yr)"},{"label":"C","text":"Methotrexate"},{"label":"D","text":"Hysterectomy"},{"label":"E","text":"Antibiotic broad-spectrum"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** **Recurrent Vulvovaginal Candidiasis (RVVC, ≥ 4 episodes/yr)** — distinguish from uncomplicated/single episode; identify species (C. albicans 80-90%, others — C. glabrata, krusei — fluconazole resistance): (1) **confirm diagnosis** — wet mount + KOH + **culture** for species + sensitivity (esp recurrent); (2) **rule out predisposing factors** — uncontrolled diabetes (HbA1c), HIV/immunosuppression, recent broad-spectrum antibiotics, COCP (mild risk), pregnancy, douching, vaginal irritants, tight clothing; (3) **induction therapy** — extended course: (a) **fluconazole 150 mg PO q 72 hr × 3 doses** (or 100-200 mg/d × 14 d); OR (b) **topical azole (miconazole, clotrimazole, terconazole)** × 7-14 days; (4) **maintenance therapy** — **fluconazole 150 mg PO weekly × 6 mo** (CDC, ACOG); alternative: clotrimazole 500 mg PV weekly; (5) **C. glabrata** — fluconazole-resistant — treat with **boric acid 600 mg PV daily × 14 d** (compounded) OR nystatin PV; (6) **C. albicans azole-resistant** rare — boric acid or oteseconazole (newer); (7) **partner treatment** — not routinely indicated (yeast not classically STI); treat partner ถ้า symptomatic; (8) **lifestyle** — cotton underwear, avoid tight, less douching, manage moisture, avoid panty liners daily, consider probiotic Lactobacillus (mixed evidence); (9) **follow-up** — culture + symptom assessment q 3 mo; (10) **post-maintenance** ~ 50% recurrence after stopping — reassess + discuss longer maintenance vs alternative therapies; (11) **specific scenarios** — **pregnancy** topical azole 7 d (avoid oral fluconazole 1st tri); diabetic — optimize glucose; HIV — treat as RVVC + manage immune; (12) **counseling** — natural history, lifestyle, expectations

---

RVVC: ≥ 4 episodes/yr. Culture for species + sensitivity. Rule out DM/HIV/antibiotic predisposition. Induction: fluconazole 150 mg q 72 hr × 3 (or topical 7-14 d). Maintenance: fluconazole 150 mg weekly × 6 mo. C. glabrata: boric acid 14 d. Lifestyle. Counseling.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'ob_gyn'
  and scenario = 'หญิงอายุ 24 ปี G0P0 มา OPD ด้วยอาการ recurrent vaginal yeast infection × 6 episodes/yr × 2 yr, ทุกครั้งหายเองหลังครีม OTC แต่กลับมา

V/S: BP 116/72, HR 78
Gen: well
Vagina: erythema mild + curdy discharge
Wet mount: yeast + pseudohyphae
Culture: Candida albicans
Fasting glucose normal, HbA1c 5.4, HIV negative, no immunosuppression, no recent antibiotics';

update public.mcq_questions
set choices = '[{"label":"A","text":"Discharge home + observation"},{"label":"B","text":"Pelvic Inflammatory Disease (PID)"},{"label":"C","text":"Methotrexate"},{"label":"D","text":"Hysterectomy"},{"label":"E","text":"Antifungal alone"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** **Pelvic Inflammatory Disease (PID)** — polymicrobial (GC, CT, anaerobes, gardnerella, mycoplasma); long-term sequelae: tubal infertility, ectopic, chronic pelvic pain (CPP): (1) **diagnosis CDC** — sexually active reproductive-age woman + lower abdominal/pelvic pain + 1+ of (a) cervical motion tenderness, (b) uterine tenderness, (c) adnexal tenderness; low threshold to treat empirically (often subtle); supportive: fever, purulent discharge, ↑ ESR/CRP, GC/CT NAAT positive, US findings; (2) **outpatient treatment (mild-moderate)**: (a) **ceftriaxone 500 mg IM × 1** + **doxycycline 100 mg PO BID × 14 d** + **metronidazole 500 mg PO BID × 14 d** (CDC 2021 updated); (b) follow-up 72 hr; (3) **inpatient treatment indications** — pregnancy, severe illness (high fever, vomiting), tubo-ovarian abscess (TOA), failure outpatient, immunocompromised, surgical emergency cannot exclude, unable to tolerate oral, non-adherence: (a) **cefotetan/cefoxitin 2 g IV q 12 hr + doxycycline 100 mg PO/IV q 12 hr** OR (b) **clindamycin + gentamicin** OR (c) **ampicillin/sulbactam + doxycycline**; transition to oral after improvement to complete 14 d (with metronidazole for anaerobic); (4) **TOA** — admit, IV antibiotics, percutaneous drainage if not resolving 48-72 hr or large (> 7-9 cm), surgery if rupture/sepsis; (5) **partner notification + treatment** — sexual partners last 60 d → empirical GC/CT treatment (DOXY-PEP rationale, expedited partner therapy); abstain until treatment complete; (6) **STI screening** — HIV, syphilis, HBV, HCV, GC/CT, trichomoniasis; (7) **IUD considerations** — recent IUD insertion ↑ PID risk; if IUD-related PID, leave IUD unless no improvement 48-72 hr antibiotic; (8) **education + prevention** — condoms, limit partners, regular STI testing, HPV vaccine, vaccination Hep A/B; (9) **HIV PrEP** consideration if high risk; (10) **follow-up** — 3 mo STI rescreen + symptom check + sequelae assessment

---

PID: CDC criteria + low threshold treatment. Outpatient: ceftriaxone IM + doxycycline + metronidazole × 14 d. Inpatient if severe/TOA/pregnancy/fail. Treat partners + STI screen. IUD-related PID — leave IUD unless no improvement. Sequelae: tubal infertility, ectopic, CPP. Prevention: condoms, vaccination.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'ob_gyn'
  and scenario = 'หญิงอายุ 25 ปี nulligravid มา OPD ด้วยอาการปวด lower abdomen ค่อยๆ + ตกขาวเหลืองหนา + ปัสสาวะแสบ × 5 d + ไข้ low-grade + sexually active multiple partners + no condom

V/S: BP 118/74, HR 92, Temp 37.8
Gen: ill-looking mild
Pelvic: cervical motion tenderness, adnexal tenderness bilateral, purulent cervical discharge, no mass
Lab: WBC 13.5K, CRP 42, β-hCG negative, NAAT GC + CT positive, HIV negative, syphilis VDRL negative
US: thickened tube + adnexal complexity bilateral but no abscess';

update public.mcq_questions
set choices = '[{"label":"A","text":"Outpatient management"},{"label":"B","text":"Postpartum Preeclampsia / Severe HT crisis"},{"label":"C","text":"Methotrexate"},{"label":"D","text":"Cesarean (already delivered)"},{"label":"E","text":"Hysterectomy"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** **Postpartum Preeclampsia / Severe HT crisis** — preeclampsia can present **up to 6 wk postpartum** (new onset or worsening of antepartum); same severity criteria + management as antepartum: (1) **immediate admission** + IV access; (2) **antihypertensive within 30-60 min** for severe-range BP — **IV labetalol 20-40-80 mg q 10 min** (max 220-300 mg) or **IV hydralazine 5-10 mg q 20 min** or **oral nifedipine immediate-release 10-20 mg q 30 min**; target BP < 150/100; AIM bundle; (3) **MgSO4** for seizure prophylaxis (severe features present — thrombocytopenia, transaminitis, cerebral symptoms) — 4-6 g loading + 1-2 g/hr × 24 hr; (4) **rule out other causes** — postpartum cardiomyopathy (echo, BNP), PRES, stroke, RCVS, eclampsia, sepsis, AFLP late, TTP/HUS, drug effects; (5) **NSAIDs** controversial — generally OK in HT, but caution + acetaminophen preferred; (6) **maintenance antihypertensive** — labetalol 200-800 mg q 8-12 hr, nifedipine ER 30-120 mg/d, hydralazine, methyldopa; ACEI/ARB now OK postpartum (and breastfeeding — enalapril/captopril preferred; lisinopril etc. — Hale L3 compatible); (7) **monitor labs** — CBC + LFT + Cr + urine — often worsens 24-72 hr postpartum then improves; (8) **discharge planning** — BP daily home for 7-10 d + weekly + recheck PE labs; education for warning signs (HA, vision, RUQ pain, swelling, SOB, AMS — return for evaluation); (9) **breastfeeding** — all common antihypertensives compatible; (10) **future pregnancy** — recurrence 15-65% (depending on severity); preconception planning + aspirin 81-150 mg from 12 wk; (11) **lifelong CV risk** — postpartum PE = 2-4× lifelong CV disease + HT + stroke risk → cardiology referral + lifestyle modification; (12) **postpartum follow-up** — close, especially first 2 wk highest risk; consider home BP monitoring + telehealth check-ins; (13) **psychosocial** — childcare support + breastfeeding support; (14) **document + counsel**

---

Postpartum preeclampsia: up to 6 wk. Treat severe HT < 30-60 min (AIM). MgSO4 if severe features. Rule out PPCM, stroke, PRES, TTP/HUS. ACEI/ARB OK postpartum + breastfeeding (enalapril/captopril preferred). Future pregnancy aspirin + recurrence. Lifelong CV risk 2-4×.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'ob_gyn'
  and scenario = 'หญิงอายุ 32 ปี G1P1 NSD 7 d ago — มาด้วย postpartum hypertensive crisis BP 188/118 + severe headache + visual disturbance + epigastric pain, mom is at home with newborn

V/S: BP 188/118, HR 96, RR 22
Gen: hyperreflexia 4+, photophobia
Fetal/Baby: at home with grandmother, breastfeeding
Lab: plt 95K, AST 145, Cr 1.2, urine protein 3+, LDH 580';

update public.mcq_questions
set choices = '[{"label":"A","text":"Hysterectomy without considering options"},{"label":"B","text":"Fertility-sparing management for early-stage endometrial cancer"},{"label":"C","text":"Methotrexate"},{"label":"D","text":"Refuse fertility consideration"},{"label":"E","text":"Antibiotic alone"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** **Fertility-sparing management for early-stage endometrial cancer** — strict criteria + multidisciplinary GYN-onc + REI + counseling: (1) **criteria for fertility-sparing**: (a) endometrioid type, **grade 1**, (b) **stage IA** + **NO myometrial invasion** on MRI, (c) **NO LVSI**, (d) **NO extrauterine disease**, (e) reproductive age + strong fertility desire, (f) **Rh ER/PR positive** (predicts response), (g) understands risks + agrees close surveillance + hysterectomy after childbearing; (2) **first-line treatment — high-dose progestin**: (a) **LNG-IUD (Mirena)** — local high-dose progestin — increasingly preferred (less systemic SE; effective; can combine with oral); (b) **megestrol acetate 160-320 mg/d PO** OR **medroxyprogesterone acetate 200-600 mg/d PO**; (c) duration 6-12 mo with re-evaluation; (3) **GnRH agonist** — adjunct or alternative for obesity/PCOS; (4) **metformin** — adjunct for obesity/insulin resistance; (5) **weight loss** — bariatric surgery if BMI > 40 — reduces recurrence + improves response; (6) **surveillance during treatment** — **endometrial sampling (hysteroscopy + biopsy) every 3 mo** until complete response (CR — no carcinoma or atypical hyperplasia on biopsy); usually 6-9 mo; (7) **after CR** — proceed to fertility treatment (often need ART/IVF — 50-60% pregnancy success); maintenance progestin until pregnancy attempted; (8) **after childbearing complete — definitive hysterectomy** (high recurrence risk if uterus retained) + consider BSO based on age + Lynch screening; (9) **recurrence rate** — 30-40% after initial CR; close monitoring; re-treat or definitive; (10) **multidisciplinary** + counseling — risks + outcomes + lifelong surveillance even after hysterectomy; (11) **Lynch syndrome universal screening** (MSI/IHC) — affects family + future cancer surveillance; (12) **contraindication fertility-sparing** — high-grade, deep myometrial invasion, LVSI, extrauterine, non-endometrioid

---

Fertility-sparing endometrial cancer: strict criteria (grade 1, stage IA, no myometrial/LVSI, ER/PR+, fertility desire). LNG-IUD + megestrol high-dose progestin. Sampling q 3 mo until CR. Then fertility treatment (IVF often). Definitive hysterectomy after childbearing. Recurrence 30-40%. Lynch screen. Multidisciplinary.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'ob_gyn'
  and scenario = 'หญิงอายุ 35 ปี G0P0 ตัดสินใจ desire fertility-sparing — diagnosed early endometrial cancer Stage IA grade 1 endometrioid + no myometrial invasion + no LVSI + no nodal involvement, BMI 35

V/S: BP 132/82, HR 80
Gen: BMI 35, mild hirsutism
MRI: no myometrial invasion, no nodal involvement
Endometrial biopsy: endometrioid grade 1 + ER/PR strongly positive + no atypical features';

update public.mcq_questions
set choices = '[{"label":"A","text":"Ignore — pain is normal"},{"label":"B","text":"first-line — NSAIDs"},{"label":"C","text":"Methotrexate"},{"label":"D","text":"Hysterectomy"},{"label":"E","text":"Antibiotic alone"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** **Primary dysmenorrhea** (no underlying pathology — cyclic prostaglandin-mediated uterine cramping) — most common in adolescents, peak 16-25 yr; vs **secondary** (endometriosis, adenomyosis, fibroids, PID, obstructed Müllerian — bicornuate with non-communicating horn — etc.): (1) **first-line — NSAIDs** — **mefenamic acid 500 mg q 6 hr** or **ibuprofen 400-800 mg q 6 hr** or **naproxen 220-500 mg q 8-12 hr** — start 1-2 d before expected menses + continue through pain; prevent prostaglandin synthesis at source; (2) **second-line — hormonal**: (a) **combined OCP** (cyclic or continuous) — suppresses ovulation + thins endometrium → ↓ PG production + cramping; also contraception (relevant if becomes sexually active); (b) **progestin alone** — POP, DMPA, implant (Nexplanon — adolescent option, no estrogen concern); (c) **LNG-IUD (Mirena)** — also adolescent option per ACOG/AAP (lower failure, reduces HMB + dysmenorrhea + endometriosis); (3) **non-pharmacological adjuncts** — heat (heating pad), exercise, dietary (omega-3, magnesium — limited evidence), TENS, yoga, acupuncture, stress management, sleep; (4) **refractory dysmenorrhea or atypical features** → consider **secondary dysmenorrhea** workup — endometriosis (suspect if pain worsening, dyspareunia, dyschezia, infertility), Müllerian anomaly (obstructed) — TVS/MRI, **diagnostic laparoscopy**; (5) **endometriosis treatment** — covered separately (NSAIDs + COCP + progestin + GnRH agonist if refractory); (6) **adolescent endometriosis** — increasingly recognized; refer if refractory; (7) **education + reassurance** — primary dysmenorrhea common + treatable; menstrual hygiene + tracking + cycle predictability; (8) **school accommodation** — emphasize importance of not missing school; pain management ahead of menses; (9) **mental health screening** — anxiety + depression often co-occur; (10) **parental involvement** + adolescent autonomy; (11) Thai school health programs + youth-friendly clinics

---

Primary dysmenorrhea: NSAIDs first-line (start before menses), COCP/progestin/LNG-IUD second. Adolescent-friendly. Refractory → suspect endometriosis or anomaly (US/MRI + laparoscopy). Non-pharma adjuncts. Education + school accommodation. Mental health. Adolescent endometriosis increasingly recognized.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'ob_gyn'
  and scenario = 'หญิงอายุ 14 ปี nulliparous มา OPD ด้วยอาการปวดประจำเดือนรุนแรงตอน menses + ปวดท้อง + คลื่นไส้ + อาเจียน + ขาดเรียน × 1 yr ตั้งแต่ menarche 2 ปีก่อน, no pelvic pathology suspected, sexually inactive

V/S: BP 110/68, HR 80
Gen: well, no signs PCOS
Pelvic: external exam normal
US TV: deferred (virgin); abdominal US WNL';

update public.mcq_questions
set choices = '[{"label":"A","text":"Discharge home with PO antibiotic"},{"label":"B","text":"Tubo-Ovarian Abscess (TOA)"},{"label":"C","text":"Methotrexate"},{"label":"D","text":"Hysterectomy"},{"label":"E","text":"Antibiotic outpatient"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** **Tubo-Ovarian Abscess (TOA)** — complication of PID with abscess formation; polymicrobial (GC, CT, anaerobes, gram-negatives): (1) **admit + IV access + IV antibiotics**: (a) **cefoxitin/cefotetan 2 g IV q 12 hr + doxycycline 100 mg IV/PO q 12 hr** OR (b) **clindamycin 900 mg IV q 8 hr + gentamicin 5 mg/kg q 24 hr** OR (c) **ampicillin-sulbactam 3 g IV q 6 hr + doxycycline**; (2) **continue IV** until afebrile + improving 24-48 hr, then transition to **oral × 14 d total** with metronidazole 500 mg BID + doxycycline; (3) **drainage**: (a) **percutaneous (IR-guided)** — preferred for abscess > 7-9 cm + accessible + no improvement on antibiotics 48-72 hr OR initially for large abscess; minimally invasive; (b) **transvaginal drainage** alternative; (c) **surgical (laparoscopic or open)** — for rupture, sepsis, failed minimally invasive, or large unresponsive; (4) **IUD management** — IUD-associated TOA — leave IUD initially if responding to antibiotics, remove if not improving 48-72 hr or recurrent (CDC); (5) **STI screen + partner notification + treatment** (GC/CT empirically partners; HIV/syphilis/hepatitis screen); (6) **monitor** — temperature, WBC, CRP, abdo exam, US/CT q 48-72 hr to assess abscess size; (7) **complications** — sepsis, rupture (surgical emergency), chronic pelvic pain, infertility (tubal damage), ectopic risk; (8) **education** — STI prevention, condoms, regular screening, follow-up; (9) **discharge** when afebrile + improving + tolerate oral + arranged follow-up; (10) **outpatient** — complete antibiotic, follow-up 3 mo for symptom + STI re-screen + sequelae; (11) **prevention** — condoms, vaccination (HPV, Hep B), regular STI screen high-risk populations; (12) **counseling** — fertility implications; STI partner + Thai DDC reporting (some)

---

TOA: hospitalize + IV antibiotic (cefoxitin + doxycycline or clinda + gent or amp-sulb + doxy). Drainage for > 7-9 cm or no improvement 48-72 hr (IR-guided percutaneous preferred). Surgery if rupture/sepsis. IUD — leave if responding. STI + partner + screen. Complications: rupture, infertility. Total 14 d antibiotic with metronidazole.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'ob_gyn'
  and scenario = 'หญิงอายุ 32 ปี nulligravid IUD copper × 5 yr มา OPD ด้วยอาการ acute lower abdominal pain + fever 38.6 + N/V + RLQ pain + peritonitis × 2 d

V/S: BP 102/68, HR 124, Temp 38.8, RR 22
Gen: ill, peritonitis lower abdomen
Pelvic: cervical motion + adnexal tenderness, R adnexal mass 7 cm tender
Lab: WBC 22K with left shift, CRP 120, β-hCG negative, NAAT GC + CT positive, lactate 2.4
US: complex adnexal mass 7 cm with debris suggesting **tubo-ovarian abscess (TOA)**';

update public.mcq_questions
set choices = '[{"label":"A","text":"Refuse all treatment"},{"label":"B","text":"Severe vasomotor symptoms (VMS) in breast cancer survivor"},{"label":"C","text":"Methotrexate"},{"label":"D","text":"Hysterectomy"},{"label":"E","text":"Antibiotic alone"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** **Severe vasomotor symptoms (VMS) in breast cancer survivor** — MHT contraindicated; **non-hormonal management**: (1) **first-line non-hormonal pharmacotherapy**: (a) **SSRIs/SNRIs** — **paroxetine 7.5 mg/d** (FDA-approved for VMS), **venlafaxine ER 37.5-150 mg/d**, escitalopram, citalopram, desvenlafaxine; **avoid paroxetine + fluoxetine with tamoxifen** (strong CYP2D6 inhibitors — ↓ active metabolite; consider venlafaxine/escitalopram instead with tamoxifen — but this patient on aromatase inhibitor not tamoxifen so paroxetine OK); (b) **gabapentin 300-900 mg QHS** — also helps sleep; (c) **pregabalin** alternative; (d) **clonidine** — limited effect, SE; (e) **oxybutynin 2.5-5 mg BID** — anticholinergic; (f) **fezolinetant** — new (2023) neurokinin-3 (NK3) receptor antagonist — FDA-approved VMS, hormonal pathway-independent — promising for cancer survivors; (2) **non-pharmacologic**: (a) **CBT** — strong evidence — symptom + sleep + mood; (b) **mindfulness-based stress reduction (MBSR)**; (c) **clinical hypnosis** — moderate evidence; (d) **acupuncture** — limited evidence; (e) **lifestyle** — cool environment, layered clothing, avoid triggers (hot drinks, spicy, alcohol, caffeine), weight management, exercise (paradoxical short-term ↑ but long-term improvement), smoking cessation; (3) **vaginal estrogen** for GSM — controversial in breast cancer history → MDT discussion with oncology — low-dose vaginal estrogen (esp non-systemic forms — DHEA prasterone, ospemifene) generally acceptable after counseling + MDT; (4) **other** — black cohosh + soy isoflavone — mixed evidence + concern in ER+; (5) **sleep hygiene** + treatment of insomnia (CBT-I, melatonin); (6) **mood + anxiety screening** (often comorbid); (7) **support groups** + counseling; (8) **switching aromatase inhibitor** to alternative (anastrozole vs letrozole vs exemestane) sometimes helps; oncology consult; (9) **bone health** — DEXA, Ca/vit D, bisphosphonate (AI ↑ bone loss); (10) **lifelong oncology surveillance + survivorship care**

---

Breast cancer survivor + severe VMS: non-hormonal pharmacotherapy (SSRI/SNRI, gabapentin, clonidine, oxybutynin, fezolinetant new). CBT + MBSR + hypnosis + lifestyle. Avoid paroxetine + fluoxetine with tamoxifen (CYP2D6). Vaginal estrogen for GSM after MDT discussion. Bone surveillance + AI. Survivorship care.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'ob_gyn'
  and scenario = 'หญิงอายุ 56 ปี postmenopausal × 4 yr มาด้วย hot flashes severe 15+/d + night sweats + insomnia, ก่อนหน้านี้ history of breast cancer ER+ × 4 yr ago, completed tamoxifen, currently NED, on aromatase inhibitor anastrozole — exacerbating VMS

V/S: BP 124/76, HR 78
Gen: well, distressed by VMS
Lab: no current cancer findings, mammogram recent normal
No CV disease, no VTE history';

update public.mcq_questions
set choices = '[{"label":"A","text":"Fetal thyroid produces TSH from gestation"},{"label":"B","text":"fetal hypothalamus-pituitary axis"},{"label":"C","text":"Methotrexate"},{"label":"D","text":"Maternal T4 doesn''t cross placenta"},{"label":"E","text":"Hysterectomy"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Fetal endocrinology: (1) **fetal hypothalamus-pituitary axis** develops 8-12 wk; (2) **fetal thyroid** — synthesizes hormones from ~ 10-12 wk; before that **maternal T4 critical** (crosses placenta — T4 > T3); maternal hypothyroidism untreated → fetal neurodevelopmental impairment (1st trimester critical); (3) **maternal iodine** — ↑ requirement 250 mcg/d (Thai dietary salt iodination); deficiency → cretinism; (4) **fetal thyroid hormones** — TBG synthesized fetal liver; T4 rises through gestation; **TSH** detectable from ~ 12 wk + rises late; (5) **at birth** — TSH surge (newborn screen at 48-72 hr), T4 ↑ acutely; newborn screening for **congenital hypothyroidism (CH)** mandatory (Thai national program; ~ 1/3,000); cretinism preventable; (6) **anti-thyroid drugs maternal** — PTU + methimazole cross placenta; PTU preferred 1st trimester (less teratogenic than methimazole — aplasia cutis, choanal/esophageal atresia); methimazole 2nd-3rd; (7) **Graves'' with TRAb +** — crosses placenta → fetal Graves'' (tachy, IUGR, goiter, craniosynostosis) — monitor fetal HR + thyroid US; (8) **fetal adrenal** — large in 2nd-3rd trimester (fetal zone — makes DHEAS → estriol via fetoplacental unit); regresses postnatally; (9) **cortisol from fetal adrenal** — required for lung maturation (surfactant), gut, brain; ↑ at birth helps lung; (10) **antenatal corticosteroid (betamethasone/dexamethasone)** — crosses placenta — accelerates fetal lung maturation + reduces RDS, IVH, NEC, mortality — 24-34 wk routinely (extend 34-36+6 wk ALPS); (11) **maternal cortisol** ↑ in pregnancy (estrogen ↑ CBG + free; physiologic hypercortisolism); usually not Cushingoid; (12) **CAH** — fetal 21-hydroxylase deficiency → virilization (female fetus) — prenatal dexamethasone to suppress fetal HPA controversial (rare research-protocol); (13) **fetal pancreas** — insulin from ~ 12 wk; **fetal hyperinsulinemia** in maternal hyperglycemia → macrosomia + hypoglycemia at birth

---

Fetal endocrinology: maternal T4 critical 1st trimester (fetal thyroid from 10-12 wk); newborn screen TSH at 48-72 hr (CH 1/3,000). Iodine 250 mcg. PTU 1st trimester, methimazole 2nd-3rd. Graves TRAb crosses → fetal Graves. Fetal adrenal large (DHEAS → estriol). Antenatal corticosteroid → lung maturation. CAH. Fetal insulin → macrosomia.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'ob_gyn'
  and scenario = 'Resident ถามอาจารย์เรื่อง fetal endocrinology + maternal-fetal thyroid + adrenal axis';

update public.mcq_questions
set choices = '[{"label":"A","text":"GFR decreases in pregnancy"},{"label":"B","text":"Renal physiology in pregnancy"},{"label":"C","text":"Methotrexate"},{"label":"D","text":"Cr 0.9 normal in pregnancy"},{"label":"E","text":"Hysterectomy"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Renal physiology in pregnancy: (1) **anatomic changes** — kidney enlarges ~ 1-1.5 cm (vascular + interstitial); **physiologic hydroureter + hydronephrosis** (R > L due to dextrorotation of uterus; progesterone smooth muscle relaxation) — late 1st trimester onward; persists 4-6 wk postpartum; can mimic obstruction; (2) **renal plasma flow** ↑ 60-80% by 2nd trimester; (3) **GFR** ↑ 50% by mid-pregnancy (peak ~ 200 mL/min from baseline ~ 120); via ↑ renal plasma flow + ↑ filtration fraction; (4) **lab implications**: (a) **serum creatinine ↓** to 0.4-0.7 (lab upper limit pregnancy ~ 0.8); **Cr 0.9-1.0 considered abnormal in pregnancy** (impaired renal function); (b) **BUN ↓** to ~ 8-10; (c) **uric acid ↓** in early pregnancy → rises slightly late; ↑ in preeclampsia; (d) **proteinuria** — physiologic up to 300 mg/24 hr; > 300 mg/24 hr or urine protein/Cr > 0.3 = pathologic (preeclampsia, renal disease); urine dipstick poor; (e) **glycosuria** — common (↓ tubular reabsorption + ↑ GFR) — physiologic; not always GDM; (f) **bicarbonate ↓** to ~ 19-22 (compensated respiratory alkalosis from ↑ tidal volume); (5) **water + electrolyte** — Na ↓ slightly (135-138), osmolality ↓ 5-10 mOsm/kg (resetting osmostat by hCG/relaxin); RAAS activated (↑ renin/angiotensin/aldosterone) — paradoxical hypervolemia with low colloid pressure; (6) **acid-base** — compensated respiratory alkalosis (PaCO2 28-32, HCO3 19-22); (7) **clinical implications**: (a) drugs renally cleared — adjust doses (LMWH, magnesium, gentamicin); (b) **CKD pregnancy** — Cr > 1.4 = ↑ risk progression + adverse outcomes; (c) **AKI in pregnancy** — preeclampsia/HELLP, AFLP, sepsis, hemorrhage, TTP/HUS, pyelonephritis, obstruction; (d) **preeclampsia** — endotheliosis, glomerular swelling, podocyte injury, proteinuria; (e) **postpartum AKI** — can be sentinel for atypical HUS (complement-mediated); (f) **dialysis pregnancy** — possible but complex; (8) **chronic HT/PE/preeclampsia long-term renal risk**

---

Pregnancy renal: GFR ↑ 50%, RPF ↑ 60-80%. Cr ↓ to 0.4-0.7 — Cr 0.9 abnormal pregnancy. Proteinuria > 300 mg/24h pathologic. Glycosuria common. Hydronephrosis R > L physiologic. Compensated respiratory alkalosis. Drug dosing adjusted. CKD Cr > 1.4 high-risk. AKI causes: PE/HELLP/AFLP/sepsis/TTP-HUS.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'ob_gyn'
  and scenario = 'Resident ถามอาจารย์เรื่อง renal physiology in pregnancy + interpretation of labs';

update public.mcq_questions
set choices = '[{"label":"A","text":"Vaginal flora not important"},{"label":"B","text":"Vaginal microbiome + immunology"},{"label":"C","text":"Methotrexate"},{"label":"D","text":"Hysterectomy"},{"label":"E","text":"Antibiotic continuously"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** **Vaginal microbiome + immunology**: (1) **normal vaginal flora** — dominated by **Lactobacillus** (L. crispatus most protective, L. gasseri, L. jensenii, L. iners less so); produce **lactic acid** + H2O2 → **acidic pH (3.8-4.5)** → inhibits pathogens; bacteriocins, biosurfactants; (2) **community state types (CSTs)**: I (L. crispatus), II (L. gasseri), III (L. iners — less stable), IV (diverse anaerobes, gardnerella — dysbiosis); (3) **dysbiosis** — ↓ Lactobacillus + ↑ anaerobes (Gardnerella, Atopobium, Mobiluncus, Prevotella) → BV, ↑ STI susceptibility, ↑ preterm birth, ↑ PID; (4) **hormonal influences** — estrogen ↑ glycogen in epithelium → Lactobacillus substrate; **postmenopause** ↓ estrogen → ↓ glycogen → ↓ Lactobacillus → ↑ pH 5-7 → atrophy, ↑ UTI/BV; pregnancy → ↑ Lactobacillus dominance (estrogen effect); (5) **factors disrupting** — douching, antibiotics, intercourse (semen alkaline), menstruation, smoking, IUD insertion (transient), STIs; (6) **innate immunity in genital tract** — antimicrobial peptides (defensins, cathelicidin, lactoferrin, lysozyme, SLPI, elafin); IgA + IgG mucosal Ab; mucus barrier; cervical plug (pregnancy); macrophages, DCs; PRRs (TLRs) recognize PAMPs; (7) **adaptive** — mucosal IgA + tissue-resident memory T cells; (8) **clinical correlates**: (a) **BV diagnosis + treatment** — covered separately; (b) **probiotics** — Lactobacillus crispatus + reuteri studied for BV recurrence + UTI prevention — mixed evidence; (c) **vaginal microbiome transplant (VMT)** — research for recurrent BV; (d) **HIV transmission** — dysbiotic flora ↑ susceptibility; (e) **preterm birth** — dysbiosis association with PTB; investigating screening + treatment; (f) **fertility + IVF** — dysbiosis may impair; (9) **prevention** — avoid douching, manage estrogen (postmenopause local estrogen), condom use, treat partners selectively, treat BV; (10) **research** — microbiome modulation therapies

---

Vaginal microbiome: Lactobacillus dominant → lactic acid + acidic pH protective. CST I (crispatus) most stable. Dysbiosis (CST IV) → BV, STI, preterm. Estrogen → glycogen → Lactobacillus. Postmenopausal ↓ flora. Innate immunity (defensins, IgA, mucus). Probiotics + VMT research. Prevention: avoid douching, condom, treat BV.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'ob_gyn'
  and scenario = 'Resident ถามอาจารย์เรื่อง vaginal microbiome + immunology + dysbiosis';

update public.mcq_questions
set choices = '[{"label":"A","text":"Provider decides everything"},{"label":"B","text":"Shared decision-making (SDM) + patient-centered care in OB"},{"label":"C","text":"Methotrexate"},{"label":"D","text":"Discharge if patient disagrees"},{"label":"E","text":"Hysterectomy"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** **Shared decision-making (SDM) + patient-centered care in OB**: (1) **definition** — collaborative process where patient + provider make decisions together based on best evidence + patient values/preferences/circumstances; (2) **elements (Charles)** — both parties involved, information sharing both ways, deliberation, decision; (3) **components**: (a) discuss decision needed; (b) present **best evidence options + risks + benefits + uncertainty**; (c) elicit patient values + preferences; (d) deliberate + decide; (e) review/revisit; (4) **tools**: (a) **decision aids** — written, video, interactive (e.g., MFMU VBAC calculator, BWH decision aids, BabyCenter); (b) **birth plans** — preferences documented (positions, pain mgmt, monitoring, support, episiotomy, immediate skin-to-skin, delayed cord clamping, breastfeeding, family); written + flexible; (c) **OPTION scale** for measurement; (5) **specific OB SDM opportunities** — TOLAC vs ERCD, IOL vs expectant, prenatal screening (NIPT, amnio), epidural choice, induction methods, mode of breech delivery, fertility-sparing cancer options, postpartum contraception, breastfeeding decisions, advance directives (rare); (6) **respectful maternity care** — WHO statement — autonomy, consent, dignity, no abuse/coercion/discrimination; (7) **informed consent** continuous, not one-time; (8) **trauma-informed care** — recognize prior trauma + adjust approach; (9) **cultural humility** — language, beliefs, family roles; medical interpreters; (10) **doulas + companions** — improve outcomes + experience; ACOG endorses; Medicaid coverage expanding; (11) **patient-reported outcomes** + experience measures (PROMs, PREMs); (12) **provider training** — communication skills, SDM-OPTION, motivational interviewing; (13) **system support** — time, EMR tools, scheduling, decision-aid distribution; (14) **balance** — SDM doesn''t mean patient decides alone — guidance from provider; emergency situations differ; (15) Thai context — patient rights expanding; transition from paternalistic to partnership model

---

SDM in OB: collaborative — both parties — info + values + deliberation. Decision aids + birth plans + OPTION scale. Specific opportunities: TOLAC, IOL, screening, contraception, breech. Respectful maternity care (WHO). Trauma-informed + cultural humility + doulas. Provider training + system support. Balance — not abdication of expertise.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'ob_gyn'
  and scenario = 'OB unit implements shared decision-making (SDM) tools + birth plans + patient-centered care for delivery preferences';

update public.mcq_questions
set choices = '[{"label":"A","text":"Hide and deny"},{"label":"B","text":"Disclosure + apology + just culture after adverse outcome"},{"label":"C","text":"Methotrexate"},{"label":"D","text":"Refuse to discuss"},{"label":"E","text":"Hysterectomy"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** **Disclosure + apology + just culture after adverse outcome**: (1) **Patient + family disclosure** — ethical + many jurisdictions legal requirement: (a) timely (within 24-48 hr after event), (b) honest factual account, (c) acknowledge harm + expression of empathy/apology, (d) commitment to investigation + sharing findings, (e) ongoing support; (2) **''Apology laws''** — many US states protect expressions of sympathy from being used as admissions of liability — encourage transparency; Thai legal landscape — encourage open disclosure; (3) **Communication and Resolution Programs (CRPs)** — institutional approach (Michigan model, AHRQ CANDOR toolkit) — investigate + disclose + compensate when appropriate → reduces litigation + costs vs deny-defend; (4) **second victims** — providers + staff involved in adverse events suffer psychological harm — provide peer support, employee assistance, debriefing; (5) **investigation**: (a) **Root Cause Analysis (RCA)** — systematic identification of contributing factors (system, communication, equipment, training, fatigue, cognitive bias); (b) **fishbone, 5-whys** tools; (c) **avoid blame** — Just Culture framework; (6) **Just Culture** — distinguish: (a) human error (console + system fix), (b) at-risk behavior (coach), (c) reckless behavior (discipline); (7) **implementation of corrective actions** — protocol changes, equipment, training, simulation; track outcomes; (8) **morbidity + mortality (M&M) conferences** — confidential learning forum; (9) **patient safety culture** — Safety Attitudes Questionnaire; psychological safety; (10) **ongoing care + support** — continuity of care for harmed patient + family; mental health; spiritual support; (11) **bereavement + perinatal loss** — comprehensive support; (12) **legal counsel** — institutional; risk management; (13) **document** factually; (14) **share learning broadly** — lessons → other institutions; (15) **measure** — disclosure + resolution outcomes; (16) Thai context — Medical Council ethical guidelines + Thai Patient Safety Goals (2P safety, 3P safety frameworks)

---

Disclosure + apology: timely, honest, empathetic, ongoing. CRP institutional approach (CANDOR) — reduces litigation. Second victim support. RCA + Just Culture (human error vs at-risk vs reckless). M&M. Corrective actions + tracked. Safety culture. Bereavement support. Thai Patient Safety Goals. Share learning.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'ob_gyn'
  and scenario = 'Hospital reviews disclosure + apology after adverse outcome — neonatal HIE following missed CTG abnormality leading to delayed C/S';

update public.mcq_questions
set choices = '[{"label":"A","text":"Discharge home"},{"label":"B","text":"COVID-19 in pregnancy with moderate-severe disease"},{"label":"C","text":"Methotrexate"},{"label":"D","text":"Refuse all treatment"},{"label":"E","text":"Hysterectomy"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** **COVID-19 in pregnancy with moderate-severe disease** — pregnancy ↑ risk severe + adverse outcomes (preterm, stillbirth, ICU, mortality, VTE): (1) **admit + supportive care** + multidisciplinary (MFM + ID + pulmonary + ICU); (2) **oxygen** — target SpO2 ≥ 95% for fetal well-being; nasal cannula → HFNC → NIV → intubation as needed; awake proning encouraged (oxygenation + delays intubation); LUD when supine; (3) **antiviral** — **remdesivir** safe in pregnancy (acceptable per CDC/IDSA — limited but reassuring data) — 5-d course for moderate-severe; **nirmatrelvir-ritonavir (Paxlovid)** for mild-moderate outpatient if early (within 5 d) + risk factors — limited pregnancy data but generally acceptable per IDSA/RECOVERY; (4) **dexamethasone** — recommended for severe (requiring O2) per RECOVERY trial — improves mortality; cross placenta but benefit > risk in severe maternal disease; consider standard antenatal corticosteroid course concurrently if preterm risk (24-34 wk); (5) **anticoagulation** — VTE risk markedly ↑ in COVID + pregnancy — **prophylactic LMWH** for all hospitalized; therapeutic for confirmed VTE; (6) **immunomodulators** — **tocilizumab** (IL-6 inhibitor) for severe + escalating O2 needs — limited pregnancy data but RECOVERY/REMAP-CAP support; baricitinib alternative; (7) **antibiotics** — only if bacterial coinfection (procalcitonin); (8) **fetal monitoring** — continuous EFM, daily NST, growth + Doppler if FGR; (9) **delivery considerations** — COVID not indication for delivery; deliver per obstetric indication or maternal deterioration; if maternal ICU + respiratory failure → may improve respiratory status with delivery (controversial); preterm delivery for failing maternal status; (10) **mode of delivery** — vaginal preferred unless obstetric indication; PPE for staff; (11) **postpartum** — continue treatment + monitor; thromboprophylaxis 6 wk postpartum; (12) **breastfeeding** — encouraged with precautions (mask, hand hygiene; SARS-CoV-2 not transmitted via milk; antibodies transferred); (13) **vaccination** — recommend mRNA COVID vaccine + boosters in pregnancy + postpartum + breastfeeding (CDC/ACOG); (14) **neonatal** — monitor + universal precautions; (15) **mental health + family support** + telehealth follow-up

---

COVID-19 pregnancy moderate-severe: admit + multidisciplinary. O2 target ≥ 95%. Remdesivir + dexamethasone (severe) + LMWH prophylaxis. Tocilizumab severe. Continuous fetal monitoring. Not indication for delivery — per obstetric. Vaginal preferred. Vaccine recommended pregnancy + postpartum. Breastfeeding safe with precautions. VTE 6 wk postpartum. Awake proning.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'ob_gyn'
  and scenario = 'หญิงตั้งครรภ์ G2P1 GA 28 wk underlying healthy — มาห้องฉุกเฉินด้วย acute COVID-19 (PCR-confirmed) — moderate-severe symptoms (SpO2 91% on RA, dyspnea, fever, fatigue) + bilateral infiltrates on CXR

V/S: BP 118/72, HR 110, RR 26, Temp 38.6, SpO2 91% RA
Gen: dyspneic, distressed
Fetal: FHR 158 reactive, no contractions
Lab: WBC 10K, CRP 95, D-dimer 2,400, ferritin 950, LDH 380, lymphocytes 0.8
CXR: bilateral ground-glass + lower lobe infiltrates
No prior COVID vaccination';

commit;
