-- ===============================================================
-- UPDATE chunk 7/8: psychiatry (25 questions)
-- ===============================================================

begin;

update public.mcq_questions
set choices = '[{"label":"A","text":"Random"},{"label":"B","text":"Limbic System + Emotional Regulation"},{"label":"C","text":"No relevance"},{"label":"D","text":"Single mechanism"},{"label":"E","text":"Surgery"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Limbic System + Emotional Regulation: (1) **Amygdala** — fear, threat detection, emotional salience; hyperactive in anxiety + PTSD + depression; CBT + exposure reduce reactivity; amygdala-prefrontal connectivity key; (2) **Hippocampus** — declarative memory, contextual conditioning; reduced volume in PTSD + chronic depression + AD; chronic stress + cortisol damage; antidepressants + ECT + exercise increase BDNF + may restore; (3) **Anterior cingulate cortex (ACC)** — emotion regulation, error monitoring, attention; dorsal ACC cognitive; ventral ACC affective; subgenual ACC (SCC, Brodmann 25) — depression hyperactive; deep brain stimulation target for TRD (Mayberg); (4) **Prefrontal cortex (PFC)** — top-down regulation of amygdala; impaired in depression + PTSD + ADHD + schizophrenia; medial PFC default mode + self-referential rumination in depression; dorsolateral PFC — executive + TMS target for depression; (5) **Insula** — interoception, emotional awareness, body sensations; alexithymia + somatic disorders involve insula; (6) **Nucleus accumbens** — reward, motivation; addiction, anhedonia in depression; ketamine + psychedelics modulate; (7) **Default mode network (DMN)** — medial PFC + posterior cingulate + precuneus — self-referential, rumination, hyperactive in depression; psilocybin reduces DMN activity (mechanism); (8) **Salience network** — anterior insula + dorsal ACC — switching between DMN + executive control; dysfunction in psychosis; (9) **Executive control network** — dorsolateral PFC + posterior parietal; ADHD impaired; (10) **Clinical implications**: dimensional understanding — circuits cross diagnostic categories (RDoC framework); treatments target circuits not just diagnosis

---

Limbic + circuits: amygdala (fear), hippocampus (memory, PTSD/depression atrophy), ACC (SCC TRD target), PFC (top-down regulation), insula (interoception), NAc (reward), DMN (rumination depression). RDoC dimensional framework. Treatments target circuits.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'psychiatry'
  and scenario = 'Resident ถามเรื่อง limbic system + emotional regulation in psychiatric disorders';

update public.mcq_questions
set choices = '[{"label":"A","text":"Random"},{"label":"B","text":"GABA + Glutamate Balance + Psychiatric"},{"label":"C","text":"No relevance"},{"label":"D","text":"Single mechanism"},{"label":"E","text":"Surgery"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** GABA + Glutamate Balance + Psychiatric: (1) **GABA** — primary inhibitory neurotransmitter (40% of CNS): - GABA-A — ligand-gated Cl-; benzodiazepine + barbiturate + alcohol + zolpidem + propofol + neurosteroid binding sites; subunit composition determines effects (α1 = sedation, α2/3 = anxiolysis, α5 = memory); - GABA-B — metabotropic (baclofen for spasticity, GHB/sodium oxybate for narcolepsy); - Reduced GABA in depression + anxiety; (2) **Glutamate** — primary excitatory neurotransmitter; — NMDA, AMPA, kainate, metabotropic receptors; - Excitotoxicity in stroke, neurodegeneration; - **Ketamine/esketamine** = NMDA antagonist → rapid antidepressant (synaptic plasticity, BDNF); - **Memantine** = NMDA antagonist (AD); - **Riluzole** = glutamate modulator (research depression); - **D-cycloserine** = NMDA partial agonist (research augmentation of exposure therapy); (3) **Anxiety**: GABA-glutamate imbalance; benzodiazepines enhance GABA-A; pregabalin + gabapentin reduce glutamate; (4) **Depression**: glutamate excess in some circuits; reduced GABA; ketamine + glutamate modulators; (5) **Schizophrenia**: NMDA hypofunction hypothesis — PCP/ketamine produce schizophrenia-like sx; agents enhancing NMDA function research (glycine, D-serine); (6) **Bipolar**: glutamate dysregulation; lithium + valproate + lamotrigine modulate; (7) **PTSD**: glutamate excess in fear circuits; (8) **Substance use**: alcohol enhances GABA + blocks NMDA → withdrawal = GABA withdrawal + NMDA hyperactivity (seizure, hyperexcitability); (9) **Modern**: rapid antidepressants targeting glutamate (ketamine + analogs) major therapeutic advance

---

GABA-glutamate: GABA inhibitory (BZD, EtOH, barbiturate target); glutamate excitatory (NMDA — ketamine antidepressant). Anxiety/depression — imbalance. Schizophrenia NMDA hypofunction. Rapid antidepressants target glutamate.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'psychiatry'
  and scenario = 'Resident ถามเรื่อง GABA + glutamate balance + psychiatric implications';

update public.mcq_questions
set choices = '[{"label":"A","text":"Random"},{"label":"B","text":"Norepinephrine + Adrenergic System"},{"label":"C","text":"No relevance"},{"label":"D","text":"Single mechanism"},{"label":"E","text":"Surgery"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Norepinephrine + Adrenergic System: (1) **Locus coeruleus** — major NE source; project widely; arousal, attention, stress response; hyperactive in PTSD + panic; (2) **Receptors**: - **Alpha-1**: postsynaptic — prazosin antagonism reduces PTSD nightmares (sympathetic to dreams); orthostatic SE (most antidepressants, antipsychotics); - **Alpha-2**: presynaptic autoreceptor (negative feedback) + postsynaptic; clonidine + guanfacine agonist for ADHD, anxiety, opioid withdrawal; mirtazapine alpha-2 antagonist (increases NE + 5-HT); - **Beta**: cardiac + bronchial primarily; propranolol non-selective antagonist for performance anxiety + somatic anxiety (tremor, tachycardia); essential tremor + akathisia; (3) **Disorders**: - **PTSD**: NE excess in fear circuits; prazosin nightmares; propranolol for somatic; - **Panic**: NE hyperactivity; SSRI/SNRI reduce; - **ADHD**: NE deficit attention; SNRI (atomoxetine), alpha-2 agonists (guanfacine, clonidine); stimulants increase NE + DA; - **Depression**: NE deficit hypothesis (one of monoamine theories); SNRI dual mechanism; bupropion NE + DA reuptake; - **Withdrawal syndromes**: opioid + alcohol → autonomic NE hyperactivity; clonidine + lofexidine for opioid withdrawal autonomic sx; - **Anxiety performance**: propranolol PRN; (4) **Cardiovascular consideration**: stimulants + SNRI raise BP/HR — monitor; (5) **Adrenergic medications side effects**: hypotension (alpha-1 antagonism — most antipsychotics, antidepressants), orthostatic, sedation

---

NE adrenergic: alpha-1 (prazosin PTSD nightmares), alpha-2 (clonidine ADHD/anxiety, mirtazapine antagonist), beta (propranolol performance anxiety, akathisia). PTSD/panic/ADHD/depression/withdrawal all involve NE. CV monitoring stimulants/SNRI.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'psychiatry'
  and scenario = 'Resident ถามเรื่อง norepinephrine + adrenergic system in psychiatric disorders';

update public.mcq_questions
set choices = '[{"label":"A","text":"Random"},{"label":"B","text":"Acetylcholine + Cognition + Psychiatric"},{"label":"C","text":"No relevance"},{"label":"D","text":"Single mechanism"},{"label":"E","text":"Surgery"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Acetylcholine + Cognition + Psychiatric: (1) **Cholinergic pathways**: nucleus basalis of Meynert → cortex (cognition, memory); brainstem cholinergic → REM sleep, autonomic; (2) **Receptors**: - **Muscarinic (M1-M5)**: postganglionic parasympathetic + CNS; - **Nicotinic**: neuromuscular junction + CNS; (3) **Alzheimer''s disease**: cholinergic deficit (cortical + hippocampal); cholinesterase inhibitors (donepezil, rivastigmine, galantamine) — modest cognitive benefit; (4) **Anticholinergic burden**: - Major iatrogenic harm in elderly — falls, cognition, delirium, urinary retention, constipation, dry mouth, blurred vision, mydriasis, tachycardia; - **Drugs**: TCA (especially amitriptyline, doxepin), low-potency typical antipsychotics, anticholinergics (benztropine, trihexyphenidyl), diphenhydramine + 1st-gen antihistamines, oxybutynin + bladder antimuscarinics, scopolamine; - Cumulative anticholinergic burden scoring (ACB scale); avoid in elderly; (5) **Anticholinergic toxicity**: mad/hot/dry/red/blind/full; physostigmine antidote; (6) **Smoking + nicotine**: - Nicotine activates nicotinic receptors → DA release → reward; - Smoking cessation: varenicline (partial agonist α4β2), NRT, bupropion; - Schizophrenia high smoking (50-90%) — partial self-medication of cognitive sx, smoking induces CYP1A2 (lowers clozapine, olanzapine levels); (7) **REM sleep + cholinergic**: cholinergic activation during REM; anticholinergics reduce REM; (8) **Delirium**: anticholinergic + cholinergic deficit contribute; cholinesterase inhibitors in some studies modest delirium prevention/treatment; (9) **Beers Criteria**: avoid anticholinergic in elderly; (10) **Schizophrenia + cholinergic**: emerging — xanomeline (KarXT muscarinic agonist M1/M4) FDA approved 2024 schizophrenia — novel mechanism without D2 blockade; (11) **Psychogenic + autonomic**: vagal nerve stimulation for TRD (FDA approved)

---

Acetylcholine + cognition: AD cholinergic deficit (cholinesterase inhibitors). Anticholinergic burden major iatrogenic harm elderly (Beers). Toxicity → physostigmine. Smoking + nicotine + schizophrenia. Xanomeline (KarXT) novel muscarinic schizophrenia (FDA 2024).'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'psychiatry'
  and scenario = 'Resident ถามเรื่อง acetylcholine + cognitive function + psychiatric medications';

update public.mcq_questions
set choices = '[{"label":"A","text":"Random"},{"label":"B","text":"Inflammation + Immune System + Psychiatry — Growing Field"},{"label":"C","text":"No relevance"},{"label":"D","text":"Single mechanism"},{"label":"E","text":"Surgery"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Inflammation + Immune System + Psychiatry — Growing Field: (1) **Sickness behavior** — cytokines (IL-1, IL-6, TNF-α) induce depression-like behavior (anorexia, anhedonia, fatigue, social withdrawal, sleep) — overlap with depression; (2) **Cytokine inducible depression**: interferon-α treatment (HCV, melanoma) — high rate depression — historical demonstration of inflammation-depression link; (3) **Depression inflammation hypothesis**: - Subgroup of MDD with elevated CRP, IL-6; - Chronic inflammation (autoimmune, obesity, infection) → depression risk; - **Anti-inflammatory adjuvant therapy** for depression — research: NSAIDs (mixed), omega-3, minocycline, anti-TNF (infliximab in elevated CRP subgroup); (4) **Schizophrenia immune**: - Maternal infection → offspring schizophrenia risk (epidemiology); - HLA region in GWAS; - Inflammation hypothesis; - Anti-NMDA encephalitis (autoimmune) mimics schizophrenia; (5) **Bipolar inflammation**: elevated inflammatory markers in mood episodes; (6) **PANS/PANDAS** — Pediatric Acute-onset Neuropsychiatric Syndrome / following streptococcal — abrupt onset OCD + tics + behavioral changes; treatment includes antibiotic + immunomodulation; controversial diagnosis; (7) **Autoimmune encephalitis**: anti-NMDA, LGI1, GABA-B, CASPR2 — present with psychiatric sx + neurological; treatable; tumor association; (8) **Multiple sclerosis psychiatric sx**: depression (50%), anxiety, cognitive, pseudobulbar affect; treatments — same + address MS disease; (9) **HIV**: cognitive (HAND), depression, mania; (10) **Microbiome-gut-brain axis** — emerging — gut bacteria influence mood + behavior; psychobiotics research; (11) **Modern**: precision psychiatry stratifying by inflammatory biomarkers — emerging trials; immunomodulatory therapy adjunct selected patients

---

Inflammation + psychiatry: sickness behavior, depression-inflammation link (subgroup with elevated CRP/IL-6), interferon-induced depression, schizophrenia (maternal infection), PANS/PANDAS, autoimmune encephalitis (anti-NMDA), MS psychiatric. Microbiome-gut-brain axis emerging.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'psychiatry'
  and scenario = 'Resident ถามเรื่อง inflammation + immune system + psychiatric disorders';

update public.mcq_questions
set choices = '[{"label":"A","text":"No theoretical basis"},{"label":"B","text":"CBT Theoretical Foundations + Mechanisms"},{"label":"C","text":"Single technique"},{"label":"D","text":"Surgery"},{"label":"E","text":"No evidence"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** CBT Theoretical Foundations + Mechanisms: (1) **Beck''s cognitive model**: thoughts → feelings → behaviors (cognitive triad of depression — self, world, future); cognitive distortions (catastrophizing, all-or-nothing, mind reading, etc.); identify + modify; (2) **Behavioral**: - Conditioning (Pavlov, Skinner); - Exposure + response prevention (extinction of conditioned fear, OCD, phobias); - Behavioral activation (depression — increase reinforcing activities); - Habit reversal (BFRBs); (3) **Cognitive techniques**: - Identifying automatic thoughts; - Examining evidence; - Cognitive restructuring; - Behavioral experiments; - Decatastrophizing; (4) **Mechanism of change**: - Neural — fMRI shows changes in amygdala-PFC connectivity, reduced amygdala reactivity, increased PFC regulation; - Behavioral — learning new responses + reducing avoidance; - Cognitive — schema modification; (5) **Evidence base**: most studied psychotherapy; effective for depression, anxiety, OCD, PTSD, eating disorders, insomnia, psychosis (CBTp), pain, somatic; (6) **Specific protocols**: - **MDD**: Beck CBT, behavioral activation; - **GAD**: cognitive restructuring + worry exposure; - **Panic**: interoceptive + in vivo exposure; - **OCD**: ERP; - **PTSD**: PE, CPT; - **Insomnia**: CBT-I; - **Social anxiety**: cognitive + exposure (group effective); - **Eating disorders**: CBT-E (Fairburn); - **Substance use**: CBT, MET, relapse prevention; - **Psychosis**: CBTp; - **BPD**: DBT (modified CBT); - **Pain**: CBT for chronic pain; (7) **Format**: individual, group, online, app-based (effectiveness comparable for many disorders); (8) **Combination with medication**: synergistic for many disorders; (9) **Therapist factors**: training + adherence + alliance important; (10) **Limitations**: not all respond; some require psychodynamic, family, or other approaches

---

CBT: Beck cognitive triad + behavioral conditioning. Identifying automatic thoughts + cognitive restructuring + behavioral experiments + exposure. Mechanism: amygdala-PFC connectivity changes. Most studied. Disorder-specific protocols. Available online/app.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'psychiatry'
  and scenario = 'Resident ถามเรื่อง CBT theoretical foundations + mechanisms';

update public.mcq_questions
set choices = '[{"label":"A","text":"No evidence base"},{"label":"B","text":"Psychodynamic Therapy — Theoretical Foundations + Modern Practice"},{"label":"C","text":"Single school of thought"},{"label":"D","text":"Surgery"},{"label":"E","text":"Only short-term"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Psychodynamic Therapy — Theoretical Foundations + Modern Practice: (1) **Origins**: Freud psychoanalysis (unconscious, defense mechanisms, drive theory, transference); evolved through object relations (Klein, Winnicott, Mahler), self-psychology (Kohut), relational + interpersonal (Sullivan, Mitchell), attachment-informed (Bowlby + modern); (2) **Core concepts**: - **Unconscious mental processes** influence behavior; - **Defense mechanisms** (denial, projection, displacement, sublimation, intellectualization, splitting, etc.); - **Transference + countertransference** — patient''s feelings toward therapist + vice versa as therapeutic material; - **Insight** — understanding patterns; - **Working through** — repeated processing for change; - **Resistance** — barriers to insight + change; (3) **Modern psychodynamic**: - Brief dynamic therapy (Strupp, Davanloo, Sifneos) — 16-30 sessions, focused; - Mentalization-Based Treatment (MBT — Bateman + Fonagy) — BPD, understand mental states; - Transference-Focused Psychotherapy (TFP — Kernberg) — BPD, narcissistic; - Supportive psychodynamic; (4) **Evidence base** (Shedler): - Effective for depression, anxiety, personality disorders, complex trauma; - Effects sustained + grow after treatment ends (unlike some other modalities); - Equivalent to CBT for many disorders; (5) **Indications**: - Personality disorders; - Complex trauma; - Chronic interpersonal patterns; - Depression with personality features; - Patients seeking insight + meaning; - Treatment-resistant after symptom-focused therapies; (6) **Distinguish from psychoanalysis**: psychoanalysis (3-5×/wk, couch, intensive — limited modern use clinical) vs psychodynamic psychotherapy (1-2×/wk, face-to-face); (7) **Therapeutic alliance** central — Norcross + Wampold common factors research; (8) **Cultural adaptation** important; (9) **Combination with medication** acceptable; (10) **Modern psychodynamic** integrates neuroscience, attachment, emotion regulation

---

Psychodynamic: unconscious + defense mechanisms + transference + insight + working through. Modern: brief dynamic, MBT, TFP. Evidence base (Shedler) — effects sustained + grow. BPD, complex trauma, depression with personality, insight-seeking patients. Alliance central.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'psychiatry'
  and scenario = 'Resident ถามเรื่อง psychodynamic therapy + theoretical foundations';

update public.mcq_questions
set choices = '[{"label":"A","text":"Stop all medications in pregnancy"},{"label":"B","text":"Pregnancy + Lactation Psychiatric Pharmacology"},{"label":"C","text":"Continue valproate"},{"label":"D","text":"Surgery"},{"label":"E","text":"Avoid SSRI absolutely"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Pregnancy + Lactation Psychiatric Pharmacology: (1) **Foundational**: untreated psychiatric illness has risks (untreated depression — preterm, LBW, postpartum depression risk, infanticide/suicide, impaired bonding, child development); medication risks; balance with shared decision-making; (2) **SSRIs**: - **Sertraline** generally preferred (extensive data, low milk transfer); - **Escitalopram, fluoxetine** acceptable; - **Paroxetine** — Ebstein cardiac anomaly (small absolute risk, controversial; avoid initiating in pregnancy); - Late pregnancy SSRI — 30% neonatal adaptation (transient); PPHN slight risk; do NOT routinely discontinue (relapse risk > NAS); (3) **SNRIs**: venlafaxine, duloxetine — acceptable; similar profile; (4) **Bupropion**: limited data but no clear teratogenicity; consider; (5) **Mirtazapine**: acceptable; appetite + sleep benefit hyperemesis; (6) **Mood stabilizers**: - **Lithium** — Ebstein anomaly small absolute risk; monitor levels closely (renal changes pregnancy); preferred over valproate; - **Valproate** — AVOID — NTD 1-2% + cognitive deficits + Major Congenital Malformations; FDA black box; - **Carbamazepine** — NTD + facial anomalies + folate supplement; avoid if possible; - **Lamotrigine** — acceptable; levels may decrease in pregnancy (monitor); breastfeeding compatible; (7) **Antipsychotics**: - Typical + atypical generally acceptable; - Gestational diabetes monitoring (olanzapine, quetiapine, clozapine); - Discontinuation late pregnancy not recommended; (8) **Benzodiazepines**: - 1st trimester — cleft palate small risk; - Late pregnancy — floppy infant syndrome + withdrawal; - If essential, short-term lowest dose; - AVOID alprazolam if possible; (9) **ECT**: safe in pregnancy + lactation; consider for severe depression/psychosis; (10) **Lactation**: most SSRI low transfer (sertraline preferred); benefits of breastfeeding generally outweigh medication exposure; LactMed resource; (11) **Resources**: MotherToBaby, LactMed, REPROTOX, OB-psychiatry consultation; (12) **Shared decision-making + informed consent**; (13) **Postpartum highest risk for relapse** — close monitoring + medication continuation often important; (14) **Multidisciplinary**: psychiatry, OB, primary care, pediatrics, lactation

---

Pregnancy/lactation psychiatry: balance untreated illness vs medication. Sertraline preferred. Valproate AVOID (NTD). Lithium monitor closely. Lamotrigine acceptable. ECT safe. BZD cautious. Postpartum relapse high — continue often. MotherToBaby, LactMed. Multidisciplinary.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'psychiatry'
  and scenario = 'Resident ถามเรื่อง psychiatric medication in pregnancy + lactation safety';

update public.mcq_questions
set choices = '[{"label":"A","text":"No monitoring needed"},{"label":"B","text":"Psychotropic Medication Monitoring"},{"label":"C","text":"Single test only"},{"label":"D","text":"Surgery"},{"label":"E","text":"Random"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Psychotropic Medication Monitoring: (1) **Antipsychotics — atypical metabolic monitoring** (APA/ADA consensus): - **Baseline**: weight + BMI + waist circumference, BP, HbA1c or fasting glucose, fasting lipid panel, personal + family hx CV/DM; - **Follow-up**: weight + BP at 4, 8, 12 wk, then quarterly; HbA1c + lipids at 12 wk, then annually; - More frequent for high-risk agents (olanzapine, clozapine); (2) **Clozapine specific**: - **ANC**: weekly × 6 mo → biweekly × 6 mo → monthly thereafter; discontinue ANC < 1000 (severe < 500); - **Cardiac**: troponin + CRP + ECG at baseline + as indicated; monitor first 4-8 wk for myocarditis (chest pain, fever, dyspnea); - **Bowel**: monitor constipation/ileus; - **Drug levels**: target 350-600 ng/mL; check after dose change, smoking change; (3) **Lithium**: - **Baseline**: CMP (renal — Cr, BUN, eGFR), TSH, Ca + PTH (parathyroid), pregnancy, EKG > 50 yo or CV; - **Levels**: 12h post dose; therapeutic 0.6-1.2 mEq/L (lower for elderly, maintenance); after dose change in 5-7d; with medication changes (NSAID, ACE-I, diuretic); - **Routine**: levels q6-12 mo stable patients; TSH + Ca + Cr q6-12 mo; (4) **Valproate**: - **Baseline + monitoring**: LFT, CBC (thrombocytopenia), levels (50-125 mg/L); ammonia if encephalopathic features; pregnancy testing; (5) **Carbamazepine**: - CBC (aplastic anemia, agranulocytosis), LFT, Na (hyponatremia), levels (4-12 mg/L); HLA-B*1502 testing (Asian) before initiation (SJS risk); (6) **Lamotrigine**: - No routine labs; — SJS/TEN rash monitoring (slow titration); (7) **Stimulants**: - BP + HR baseline + monitoring; pre-existing CV considerations; - Height + weight (peds); - Misuse + diversion assessment; (8) **TCA, MAOI**: less used currently; EKG if cardiac risk; (9) **Antidepressant general**: - Na (SSRI/SNRI elderly — SIADH); - Sexual SE, GI, sleep, suicidality (especially adolescents — FDA boxed warning); (10) **Patient education** about monitoring + adherence essential

---

Psychotropic monitoring: atypical metabolic (weight, glucose, lipids, BP); clozapine (ANC, troponin/CRP/ECG); lithium (level, renal, thyroid, Ca); valproate (LFT, CBC, level); carbamazepine (CBC, LFT, Na, level, HLA-B*1502); lamotrigine (SJS rash); stimulants (BP, HR).'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'psychiatry'
  and scenario = 'Resident ถามเรื่อง psychotropic side effect monitoring + labs';

update public.mcq_questions
set choices = '[{"label":"A","text":"No predictability"},{"label":"B","text":"Risk + Protective Factors for Psychiatric Disorders"},{"label":"C","text":"Single factor"},{"label":"D","text":"Random"},{"label":"E","text":"Surgery"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Risk + Protective Factors for Psychiatric Disorders: (1) **Biological risk**: - Genetics (heritability varies by disorder); - Family history; - Perinatal: maternal infection, malnutrition, obstetric complications, prematurity, maternal substance use; - Childhood TBI; - Medical illness (chronic, neurologic, endocrine); - Hormonal (perinatal, perimenopausal); - Sleep disorders; - Substance use; (2) **Psychological risk**: - Childhood trauma + adverse childhood experiences (ACEs — Felitti) — dose-response with adult mental + physical illness; - Insecure attachment; - Negative cognitive style; - Personality factors (neuroticism); - Prior psychiatric episodes (recurrence predictor); (3) **Social risk**: - Poverty + low SES; - Social isolation; - Discrimination (minority stress); - Migration + acculturation stress; - Adverse environment (community violence); - Family dysfunction; - Bullying; - Unemployment; - Housing instability + homelessness; (4) **Protective factors**: - Stable + supportive relationships; - Social connection + community; - Sense of purpose + meaning (religion, vocation); - Self-efficacy + coping skills; - Emotional regulation; - Healthy lifestyle (exercise, sleep, diet); - Treatment engagement when needed; - Cognitive flexibility; - Optimism (within reason); - Resilience traits; (5) **Specific examples**: - **Depression**: female sex, family hx, ACEs, chronic illness, isolation, loss, perimenopause, postpartum, low SES; - **PTSD**: trauma exposure + low cortisol pre-trauma + lack of social support; - **Schizophrenia**: family hx, prenatal/perinatal complications, cannabis (high-potency, adolescent), urban birth, migration, paternal age; - **Substance use**: family hx, ACEs, peer use, mental health comorbidity, early initiation, low SES; - **Suicide**: prior attempt (biggest), mental illness, substance use, isolation, recent loss, access to means; (6) **Life course perspective**: developmental periods + cumulative risk; (7) **Modifiable** vs **non-modifiable** distinction useful clinically; (8) **Intersectionality**: multiple identities + adversities compound; (9) **Universal + selective + indicated prevention** based on risk level; (10) **Multidisciplinary + multilevel** intervention

---

Risk + protective factors: biological (genetics, perinatal), psychological (ACEs, attachment, cognitive style), social (poverty, isolation, discrimination). Protective: relationships, purpose, coping. Disorder-specific patterns. Life course + intersectional + cumulative.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'psychiatry'
  and scenario = 'Resident ถามเรื่อง risk + protective factors for psychiatric disorders';

update public.mcq_questions
set choices = '[{"label":"A","text":"Adolescent brain same as adult"},{"label":"B","text":"Childhood + Adolescent Brain Development + Psychiatric Implications"},{"label":"C","text":"No critical periods"},{"label":"D","text":"Random"},{"label":"E","text":"Surgery"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Childhood + Adolescent Brain Development + Psychiatric Implications: (1) **Brain development**: - Prefrontal cortex matures last (~ age 25); - Limbic system + reward circuits mature earlier (adolescence); - Synaptic pruning + myelination through adolescence; - Plasticity high in childhood + adolescence — critical periods; (2) **Adolescent risk-taking**: imbalance reward circuits (mature) vs prefrontal regulation (immature) → impulsivity, risk-taking, sensation-seeking — normative; substance use + accidents peak; psychiatric disorder onset peak (50% by age 14, 75% by age 24); (3) **Vulnerability**: - **Substance use**: adolescent brain especially vulnerable; cannabis affects executive function + may increase psychosis risk especially with family hx + high potency + early initiation; alcohol impacts hippocampus + frontal; - **Stress + trauma**: ACEs more impactful in critical periods; epigenetic effects; - **Depression + anxiety**: adolescent onset common — different risk factors + treatment considerations than adult; - **Eating disorders**: adolescent peak; - **First episode psychosis** in young adulthood; - **Suicide risk** adolescent — peer + media + bullying + LGBTQ+ minority stress; (4) **Medication considerations in youth**: - **SSRI** — FDA boxed warning increased SI in adolescents (CAMS trial — combination SSRI + CBT optimal for adolescent anxiety); benefit > risk for most; close monitoring; - **Stimulants** — growth + appetite + sleep + CV monitoring; - **Antipsychotic** — greater metabolic vulnerability in youth; weight gain; - **Lithium + valproate + AED**: monitoring; valproate avoided in adolescent girls (NTD if pregnancy); (5) **Psychotherapy modifications**: - Family involvement essential; - Developmentally appropriate techniques; - School coordination; - Trauma-informed; (6) **Confidentiality + consent**: assent + parental consent for minors; confidentiality between adolescent + provider (with limits for safety) — important for engagement; (7) **Transitions to adult care**: gap in services; transition planning; (8) **Modern**: prevention + early intervention — return on investment in adolescent mental health; (9) **Adolescent-specific clinics + programs**; (10) **Digital interventions** appeal to youth (apps, online)

---

Adolescent brain: PFC matures last (~25), limbic earlier. Imbalance → risk-taking. Critical periods + plasticity. Substance vulnerability. CAMS — SSRI + CBT for adolescent anxiety. Family + school coordination. Confidentiality with safety limits. Prevention + early intervention.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'psychiatry'
  and scenario = 'Resident ถามเรื่อง childhood + adolescent brain development + psychiatric implications';

update public.mcq_questions
set choices = '[{"label":"A","text":"No relevance"},{"label":"B","text":"Trauma-Informed Care (TIC) — SAMHSA Framework"},{"label":"C","text":"Single approach"},{"label":"D","text":"Surgery"},{"label":"E","text":"Avoid all patients with trauma"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Trauma-Informed Care (TIC) — SAMHSA Framework: (1) **Four R''s**: - **Realize** widespread impact of trauma; - **Recognize** signs + symptoms; - **Respond** with knowledge + integration; - **Resist re-traumatization**; (2) **Six key principles**: - Safety (physical + psychological); - Trustworthiness + transparency; - Peer support; - Collaboration + mutuality; - Empowerment, voice, choice; - Cultural, historical, gender issues; (3) **Trauma prevalence**: 70%+ adults experience trauma; psychiatric populations even higher; (4) **Universal approach**: assume potential trauma in all patients — don''t require disclosure; (5) **Practical applications**: - Avoid retraumatization triggers (restraint, seclusion, forced disrobing, sudden touching, loud noises); - Trauma screening — ACE, PTSD; - Patient choice + collaboration; - Explanation + consent; - Address physical + emotional safety; - Predictability + transparency; - Strengths-based vs deficit-based; (6) **Clinical contexts**: - Mental health treatment; - Substance use treatment; - Primary care; - Emergency departments (restraint debriefing); - Inpatient (open units when possible, choice in care, education for staff); - Pediatric — adverse childhood experiences screening; - Refugees + immigrants (cultural trauma); - Indigenous communities (historical trauma); - Domestic violence + sexual assault; - LGBTQ+ (minority stress trauma); (7) **Provider self-care**: - Vicarious traumatization; - Burnout prevention; - Supervision + peer support; (8) **System-level**: - Policy changes; - Training all staff (not just clinical); - Trauma champion roles; - Continuous improvement; (9) **Distinguish from trauma treatment**: TIC is approach to all care; trauma treatment is specific (PE, CPT, EMDR for PTSD); (10) **Modern integration**: TIC standard in healthcare systems + criminal justice + education + child welfare

---

Trauma-Informed Care: SAMHSA 4 R''s (Realize, Recognize, Respond, Resist retraumatization) + 6 principles (safety, trust, peer, collaboration, empowerment, cultural). Universal — assume trauma. Practical: avoid retraumatization, choice + collaboration, screening. TIC = approach; trauma treatment = specific.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'psychiatry'
  and scenario = 'Resident ถามเรื่อง trauma-informed care + practical application';

update public.mcq_questions
set choices = '[{"label":"A","text":"No scales useful"},{"label":"B","text":"Psychiatric Assessment Tools + Rating Scales"},{"label":"C","text":"Single scale all"},{"label":"D","text":"Random"},{"label":"E","text":"Surgery"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Psychiatric Assessment Tools + Rating Scales: (1) **Depression**: - **PHQ-9** (most widely used screening + monitoring; 9 items; cut-offs); - **Beck Depression Inventory (BDI-II)**; - **Hamilton Depression Rating Scale (HAM-D)** — clinician-rated; - **MADRS** — clinician; - **GDS** — geriatric (less somatic); - **EPDS** — perinatal; (2) **Anxiety**: - **GAD-7** (most widely used); - **HAM-A**; - **Beck Anxiety Inventory**; - **Penn State Worry Questionnaire (PSWQ)** — GAD specific; - **Liebowitz Social Anxiety (LSAS)**; - **Panic Disorder Severity Scale (PDSS)**; (3) **OCD**: - **Y-BOCS** — Yale-Brown — gold standard; (4) **PTSD**: - **PCL-5** — self-report screen; - **CAPS-5** — gold standard clinician-rated; (5) **Mania**: - **Young Mania Rating Scale (YMRS)**; - **MDQ** — Mood Disorder Questionnaire — bipolar screening; (6) **Psychosis**: - **PANSS** (Positive + Negative Syndrome Scale) — schizophrenia, research; - **SAPS, SANS**; - **BPRS**; (7) **Suicide**: - **Columbia Suicide Severity Rating Scale (C-SSRS)**; - **Beck Scale for Suicide Ideation**; (8) **Substance use**: - **AUDIT** (alcohol); - **DAST** (drug); - **CIWA-Ar** (alcohol withdrawal); - **COWS** (opioid withdrawal); - **ASSIST** (WHO); (9) **Cognitive**: - **MMSE** (most known but copyright); - **MoCA** (Montreal — sensitive MCI); - **SLUMS**; - **Mini-Cog**; - **AD8** (informant); (10) **ADHD**: - **ADHD Rating Scale** (parent + teacher); - **Conners**; - **Vanderbilt**; - **ASRS-v1.1** (adult screening); (11) **Eating disorders**: - **EDE-Q**; - **SCOFF** (screening); (12) **Quality of life + functioning**: - **GAF** (historical); - **WHODAS** — WHO Disability Assessment Schedule; (13) **Personality**: - **PID-5** (DSM-5 dimensional); - **NEO PI-R**; (14) **Modern**: - Measurement-based care — routine outcomes; - Patient-Reported Outcomes Measurement Information System (PROMIS); - Digital + computerized adaptive testing emerging; (15) **Cultural + linguistic adaptation** important

---

Rating scales: PHQ-9 (depression), GAD-7 (anxiety), Y-BOCS (OCD), PCL-5/CAPS-5 (PTSD), YMRS (mania), C-SSRS (suicide), AUDIT/DAST (substance), MoCA (cognitive), ASRS (adult ADHD), EDE-Q (eating), WHODAS (function). Measurement-based care.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'psychiatry'
  and scenario = 'Resident ถามเรื่อง assessment tools + rating scales in psychiatry';

update public.mcq_questions
set choices = '[{"label":"A","text":"Culture irrelevant"},{"label":"B","text":"Culture affects all aspects"},{"label":"C","text":"Single approach"},{"label":"D","text":"Random"},{"label":"E","text":"Surgery"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Cultural Psychiatry: (1) **Culture affects all aspects**: - Symptom expression + interpretation; - Help-seeking patterns; - Treatment preferences; - Family + community role; - Stigma; - Spirituality + religion; - Causation beliefs; - Trust in healthcare; (2) **DSM-5 Cultural Formulation Interview (CFI)**: - Cultural definition of problem; - Cultural perceptions of cause + context + support; - Cultural factors affecting self-coping + past help-seeking; - Cultural factors affecting current help-seeking; (3) **Culture-bound (now ''cultural concepts of distress'' DSM-5)**: - **Susto** (Latin — fright illness); - **Ataque de nervios** (Latin — uncontrolled grief/anger); - **Dhat syndrome** (South Asia — semen loss anxiety); - **Koro** (Asia — genital retraction); - **Khyâl cap** (''wind attacks'' Cambodia); - **Taijin kyofusho** (Japan — fear of offending others); - **Ghost sickness** (Native American); - **Maladi moun** (Caribbean); (4) **Thai cultural context**: - Buddhist concepts of suffering, karma, mindfulness; - Family-centered decision-making; - Stigma for severe mental illness; - Spirit + ancestor beliefs influence; - Somatization more accepted than psychological complaints; - Respect for hierarchy + face-saving; (5) **Immigrant/refugee mental health**: - Pre-migration trauma, migration trauma, post-migration adversity; - Acculturation stress; - Discrimination; - Family separation; - Language barriers; - Healthcare access; (6) **LGBTQ+ minority stress** (Meyer): - Distal stressors (discrimination); - Proximal stressors (concealment, internalized stigma); - Increased mental health disorders + suicide risk; - Affirming care reduces; (7) **Indigenous mental health**: - Historical trauma; - Colonization effects; - Cultural healing practices; - Community-based approaches; (8) **Language services**: - Professional interpreter (not family) for clinical interactions; - Translated materials; - Culturally adapted instruments; (9) **Provider cultural humility** vs cultural competence — ongoing learning + self-reflection; (10) **Multidisciplinary**: cultural consultants, traditional healers integration where appropriate, peer support; (11) **Avoid stereotyping** — individual variation within cultures; (12) **Modern**: cultural psychiatry integrated into all training; global mental health priority

---

Cultural psychiatry: culture affects symptom expression + help-seeking + treatment. DSM-5 CFI tool. Cultural concepts of distress (susto, ataque, dhat, koro). Thai Buddhist context. Immigrant/refugee considerations. LGBTQ+ minority stress. Language services. Cultural humility.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'psychiatry'
  and scenario = 'Resident ถามเรื่อง cultural psychiatry + considerations';

update public.mcq_questions
set choices = '[{"label":"A","text":"No measurement needed"},{"label":"B","text":"Measurement-Based Care (MBC) + Quality Improvement"},{"label":"C","text":"Single visit assessment"},{"label":"D","text":"Random"},{"label":"E","text":"Surgery"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Measurement-Based Care (MBC) + Quality Improvement: (1) **MBC definition**: routine use of standardized rating scales + symptom measures to guide clinical decisions; (2) **Components**: - Baseline assessment with validated scale; - Repeat measurements at regular intervals (typically each visit); - Use results to guide treatment decisions (continue, augment, switch); - Patient + clinician collaborative review; (3) **Common scales for MBC**: PHQ-9 (depression), GAD-7 (anxiety), AUDIT (alcohol), C-SSRS (suicide); standardized + brief + free + sensitive to change; (4) **Evidence**: - **STAR*D** + replication — MBC improves outcomes vs usual care; - Earlier identification of non-response; - Reduces treatment-as-usual variability; - Patient engagement + activation; (5) **Quality measures**: - Screening rates; - Treatment initiation; - Response + remission rates; - Suicide screening + follow-up; - Adherence; - Patient satisfaction; (6) **Implementation challenges**: - Time constraints; - Workflow integration; - EHR design; - Training; - Reimbursement; (7) **Solutions**: - Digital + patient portal pre-visit assessment; - Brief scales; - Integration into EHR + dashboards; - Care team workflow; - Reimbursement incentives (HEDIS, MIPS); (8) **Collaborative Care Model integration** — MBC core component (IMPACT trial); (9) **Population health**: - Registry-based; - Stepped care; - Outreach for non-improvers; (10) **Outcomes-based reimbursement**: pay-for-performance, value-based; (11) **Patient-Reported Outcome Measures (PROMs)**: increasing use; PROMIS measures; (12) **Equity considerations**: validity across populations; language; literacy; (13) **AIMS Center, APA, NIMH** advocacy + resources; (14) **Modern psychiatric quality** indicators: depression screening, follow-up after psych discharge, antipsychotic monitoring, adherence, suicide risk follow-up; (15) **Cochrane** + APA endorse MBC

---

Measurement-Based Care: routine rating scales (PHQ-9, GAD-7) guiding treatment decisions. Evidence STAR*D shows improved outcomes. Quality measures + implementation via EHR + collaborative care. Stepped care + outreach. Reimbursement incentives. Modern psychiatric quality.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'psychiatry'
  and scenario = 'Resident ถามเรื่อง measurement-based care + quality improvement in psychiatric practice';

update public.mcq_questions
set choices = '[{"label":"A","text":"No alliance needed"},{"label":"B","text":"Therapeutic Alliance + Common Factors"},{"label":"C","text":"Technique only"},{"label":"D","text":"Random"},{"label":"E","text":"Surgery"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Therapeutic Alliance + Common Factors: (1) **Common factors theory** (Frank, Wampold): - Effectiveness of psychotherapy partially due to specific techniques but largely due to shared ''common factors'' across orientations; - Therapeutic alliance, expectancy, empathy, positive regard, congruence, goal consensus, collaboration; (2) **Therapeutic alliance** (Bordin): - Bond (emotional connection); - Agreement on goals; - Agreement on tasks; - Most robust predictor of outcomes across modalities (effect size 0.5-0.6); - Patient + clinician perspectives — patient perception more predictive than clinician; - Early alliance (sessions 3-5) predictive of outcome; - Alliance ruptures inevitable — repair process therapeutic; (3) **Therapist factors**: - Empathy (Rogers — accurate empathy + unconditional positive regard + congruence); - Microskills + warmth + non-judgmental; - Training + experience matter but less than expected; - Therapist effects exceed treatment effects; (4) **Patient factors**: - Engagement + motivation; - Severity of illness; - Comorbidity; - Previous treatment experience; (5) **Cultural alliance**: - Cultural humility; - Adaptation; - Match (sometimes patient preference); - Language; (6) **Communication skills** essential: - Open-ended questions; - Reflection; - Summary; - Motivational interviewing; - Non-verbal awareness; (7) **Boundaries** + professional behavior; (8) **Ruptures**: identify, address, repair — often growth opportunity; (9) **Telepsychiatry alliance** — comparable to in-person for most; some challenges (technology, non-verbal); (10) **Group + family therapy alliance** — multiple alliances simultaneously; (11) **Provider self-care + supervision** — important for sustaining ability to form alliance; burnout impairs; (12) **Outcomes**: alliance contributes 5-15% of outcome variance (significant despite small percentage); (13) **Modern**: precision matching of therapist + patient — research limited but emerging

---

Therapeutic alliance + common factors: alliance (Bordin — bond + goals + tasks) most robust outcome predictor across modalities. Common factors theory (Wampold). Empathy + warmth + congruence (Rogers). Ruptures + repair therapeutic. Patient perspective key. Telepsychiatry comparable.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'psychiatry'
  and scenario = 'Resident ถามเรื่อง therapeutic alliance + common factors in psychotherapy';

update public.mcq_questions
set choices = '[{"label":"A","text":"Office-based weekly visits only"},{"label":"B","text":"Assertive Community Treatment (ACT) — Evidence-Based Community Care Model"},{"label":"C","text":"No multidisciplinary team"},{"label":"D","text":"Surgery"},{"label":"E","text":"Standard outpatient"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Assertive Community Treatment (ACT) — Evidence-Based Community Care Model: (1) **Population**: severe + persistent mental illness (schizophrenia, severe BP, severe MDD) with high service utilization (frequent hospitalizations, ED visits), housing instability, treatment non-adherence, dual diagnosis; (2) **Core principles**: - **Team-based**: multidisciplinary team (psychiatry, nursing, social work, peer support, substance use specialist, vocational specialist, housing specialist); - **In vivo** services — community + home + workplace, not office-based; - **24/7 availability**; - **Low caseload** — 10:1 patient:staff ratio; - **Time-unlimited** services; - **Frequent contact** (multiple visits/week); - **Comprehensive** services (medication, psychotherapy, case management, employment, housing, social, family); (3) **Outcomes** (Stein + Test Wisconsin original): - Reduces hospitalizations + ED visits; - Improves housing stability; - Improves community functioning; - Improves quality of life; - Cost-effective despite intensive services; (4) **Fidelity matters**: DACTS scale (Dartmouth Assertive Community Treatment Scale); programs varying in fidelity have varying outcomes; (5) **Variations**: - **Forensic ACT (FACT)** — criminal justice involved; - **CTI** (Critical Time Intervention) — time-limited transition support; (6) **Integration**: - Substance use treatment integrated (dual diagnosis); - Vocational rehabilitation (supported employment); - Housing (Housing First model); - Primary care coordination; - Family involvement; (7) **Modern adaptations**: - Telepsychiatry component; - Recovery-oriented (peer support, choice, strengths-based); - Trauma-informed; (8) **Limitations**: cost, workforce, urban vs rural feasibility; (9) **Compared to alternatives**: ACT > standard case management for severe illness; ACT not necessary for moderate illness; (10) **Long-term**: chronic illness model; not ''cure'' but sustained support

---

Assertive Community Treatment (ACT): severe mental illness, multidisciplinary team, in vivo, 24/7, low caseload, time-unlimited, comprehensive. Reduces hospitalization, improves housing + function. Fidelity matters (DACTS). Variations FACT, CTI. Modern: recovery + trauma-informed + telepsych.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'psychiatry'
  and scenario = 'Hospital implementing assertive community treatment (ACT) program for severe mental illness';

update public.mcq_questions
set choices = '[{"label":"A","text":"ED-only response"},{"label":"B","text":"Crisis Services Continuum — Comprehensive Approach"},{"label":"C","text":"No crisis services"},{"label":"D","text":"Surgery"},{"label":"E","text":"Random"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Crisis Services Continuum — Comprehensive Approach: (1) **988 Suicide + Crisis Lifeline** (US 2022 — equivalent in Thailand 1323): national hotline + text + chat; (2) **Mobile crisis teams**: - Community-based response to mental health crisis; - Police diversion (CIT model); - In-person assessment + de-escalation in person''s environment; - Bridge to services; - Reduce involuntary holds + arrests + ED visits; (3) **Crisis stabilization units / short-term observation**: - 23-72h stays; - Alternative to ED + hospitalization; - Comfortable, less restrictive setting; - Trauma-informed; - Bridge to outpatient; (4) **Crisis residential**: 7-14 days, peer-supported, less restrictive than hospital, voluntary; (5) **Peer-run respite**: alternative model, peer-led; (6) **CIT (Crisis Intervention Team) for police**: - 40-hour mental health training; - Diversion vs arrest for mental health crises; - Co-response models (police + clinician); (7) **Psychiatric ED**: dedicated psychiatric emergency services; (8) **Reduce ED boarding** (psychiatric patients in medical ED awaiting psych bed): - Real-time bed registries; - Telepsychiatry consultation; - Expedited transfer protocols; - Alternatives to hospitalization (crisis services); - Address upstream — outpatient access, social determinants; (9) **Post-crisis follow-up**: caring contacts (postcards, calls — reduce re-attempts), warm handoffs to outpatient, safety planning (Stanley-Brown); (10) **Continuum integration**: hotline → mobile crisis → stabilization → residential → outpatient — varying intensity; person-centered; (11) **System level**: data + tracking, outcomes monitoring, equity (disparities in access + outcomes), payment reform; (12) **Modern**: ''Crisis Now'' framework (SAMHSA + NASMHPD) — 3 components: regional crisis call center + mobile crisis + crisis receiving + stabilization facilities; (13) **Multidisciplinary**: psychiatry, nursing, social work, peer support, police partnership, hospital

---

Crisis services continuum: 988/1323 hotline, mobile crisis, crisis stabilization (23-72h), residential, peer respite, CIT police. Reduces ED boarding + involuntary holds. Post-crisis follow-up (caring contacts, warm handoff). ''Crisis Now'' framework. Multidisciplinary.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'psychiatry'
  and scenario = 'Healthcare system planning to reduce psychiatric ED boarding + improve crisis services';

update public.mcq_questions
set choices = '[{"label":"A","text":"No solutions available"},{"label":"B","text":"Mental Health Workforce + Access — Multi-pronged Approach"},{"label":"C","text":"Specialty referral only"},{"label":"D","text":"Surgery"},{"label":"E","text":"Random"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Mental Health Workforce + Access — Multi-pronged Approach: (1) **Workforce shortage** (global + national): - Psychiatrist shortage particularly rural + child + addiction + geriatric; - WHO global mental health workforce gap; - Loan forgiveness programs (NHSC US, HRSA); - Pipeline programs (URM, rural-track residencies); (2) **Task-sharing** + workforce expansion: - Mental health nursing, social work, psychology, peer support, community health workers; - WHO mhGAP (Mental Health Gap Action Programme) for low-resource settings; - **Friendship Bench** (Zimbabwe — lay health workers, evidence-based); - Primary care integration; (3) **Collaborative Care Model** (Wagner Chronic Care + Unützer IMPACT): - Integration mental health + primary care; - Care manager + psychiatric consultant + measurement-based care; - 2× improvement vs usual care; - Cost-effective; - Workforce multiplication — one psychiatrist serves many primary care patients; (4) **Telepsychiatry** + digital expansion: - Specialist reach extension; - Rural + underserved; - Reimbursement parity post-COVID; - Asynchronous (eConsult); - Mobile apps + digital therapeutics; (5) **Cultural + linguistic workforce**: - Diversity of providers improves access for diverse populations; - Trained interpreters; - Cultural adaptation training; (6) **Equity considerations**: - Insurance coverage parity (Mental Health Parity Act US); - Geographic distribution; - Out-of-network barriers; - Stigma; - Transportation; - Child care; - Work schedules; (7) **Prevention + early intervention** reduce downstream needs: - School-based mental health; - Pediatric primary care; - Workplace mental health; (8) **Self-management + lower-intensity options**: - Digital CBT (Sleepio, Woebot); - Bibliotherapy; - Peer-led groups; - Apps + online resources; - Self-help (NAMI, etc.); (9) **Stepped care**: matching intensity to severity; (10) **Modern**: precision matching + flexible delivery + integration

---

Mental health workforce shortage: task-sharing (WHO mhGAP, Friendship Bench), Collaborative Care (IMPACT), telepsychiatry, primary care integration, peer support, digital therapeutics, equity initiatives. Prevention + early intervention reduce need. Stepped care. Modern: flexible + precision delivery.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'psychiatry'
  and scenario = 'Mental health system addressing workforce shortage + access disparities';

update public.mcq_questions
set choices = '[{"label":"A","text":"No safety planning needed"},{"label":"B","text":"Inpatient Psychiatric Quality + Safety"},{"label":"C","text":"Restraints first-line"},{"label":"D","text":"Surgery"},{"label":"E","text":"Random"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Inpatient Psychiatric Quality + Safety: (1) **Safety measures**: - **Suicide prevention** on inpatient units: - Environmental risk assessment (ligature points, accessible hazards); - Reduce ligature risk (psychiatric-safe rooms, fittings, doors); - Sharp + chemical access control; - Monitoring + 1:1 observation policies; - Patient property search; - Visitor screening; - Suicide assessment + safety planning; - Post-discharge transition (highest risk period); - **Caring contacts** post-discharge reduce re-attempts; - **Zero Suicide initiative**; (2) **Violence prevention**: - Risk assessment (BVC — Brøset Violence Checklist); - De-escalation training (Project BETA); - Environment (safety, no weapons access); - Adequate staffing; - Trauma-informed; (3) **Restraint + seclusion reduction**: - Last resort principle; - 6 Core Strategies (NASMHPD); - Comfort rooms, sensory modulation; - Debrief after events; - Staff training; - Trauma-informed; (4) **Medical safety**: - Falls; - VTE prophylaxis; - Medication errors (especially psychotropic); - Metabolic monitoring; - Medical comorbidity attention (acute issues not missed in psychiatric setting); - Pneumonia, sepsis screening; (5) **Quality measures**: - HBIPS (Hospital-Based Inpatient Psychiatric Services) — Joint Commission measures: - Hours of physical restraint use; - Hours of seclusion; - Patients discharged on multiple antipsychotics with justification; - Continuing care plan; - Multiple antipsychotic with appropriate justification; - Follow-up after psychiatric hospitalization; (6) **Patient experience + recovery-orientation**: - Patient + family voice; - Choice in treatment; - Education; - Discharge planning early + collaborative; (7) **Transitions of care**: - Discharge summary; - Outpatient appointment within 7 days (HBIPS quality measure); - Warm handoffs; - Medication reconciliation; - Communication with PCP + family; (8) **Staff well-being**: - Training; - Supervision; - Critical incident debrief; - Burnout prevention; (9) **Continuous quality improvement**: - Adverse event review; - Patient feedback; - Outcomes tracking; (10) **Multidisciplinary**: nursing, psychiatry, social work, OT, peer support, administration

---

Inpatient psychiatric safety: suicide prevention (Zero Suicide, environmental, caring contacts), violence prevention (BVC, BETA), restraint reduction (6 Core Strategies), medical safety, HBIPS quality measures, transitions of care, staff well-being. Multidisciplinary.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'psychiatry'
  and scenario = 'Hospital implementing inpatient psychiatric quality + safety program';

update public.mcq_questions
set choices = '[{"label":"A","text":"Symptom focus only"},{"label":"B","text":"Recovery-Oriented Mental Health Services"},{"label":"C","text":"Provider-directed"},{"label":"D","text":"Random"},{"label":"E","text":"Surgery"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Recovery-Oriented Mental Health Services: (1) **Recovery definition** (SAMHSA): - Process of change through which individuals improve health + wellness, live self-directed life, strive to reach full potential; - Distinct from symptom remission; - Person-centered, hopeful, sustained; (2) **Recovery dimensions**: - Health (physical + mental); - Home (stable housing); - Purpose (meaningful activities, work, education); - Community (relationships, social networks); (3) **CHIME framework** (Connectedness, Hope, Identity, Meaning, Empowerment — Leamy); (4) **Components of recovery-oriented services**: - **Person-centered planning** — individual goals + strengths + preferences; - **Peer support specialists** — lived experience, hope, recovery role models — emerging evidence-based workforce; - **Shared decision-making** — collaborative treatment decisions; - **Strengths-based** vs deficit-based approach; - **Self-management + self-advocacy** education; - **Wellness Recovery Action Plan (WRAP)**; - **Trauma-informed care**; - **Cultural responsiveness**; - **Family + community integration**; - **Reduce coercion** — voluntary engagement, alternatives to involuntary; - **Housing First** (immediate housing + supports); - **Supported employment** (IPS — Individual Placement + Support — evidence-based); - **Supported education**; (5) **Distinct from + complementary to medical model**: - Both clinical treatment + recovery support; - Both ''recovery in'' (symptom reduction) + ''recovery of'' (meaningful life despite illness); (6) **System changes**: - Peer workforce integration; - Recovery-oriented training for all staff; - Outcome measures including QoL, function, not just symptoms; - Anti-stigma initiatives; (7) **Modern**: - Recovery-oriented systems of care (ROSC) for substance use; - Mental Health Recovery Network; - International evidence base growing (UK, Australia, New Zealand leadership); (8) **Critiques + integration**: balance recovery with severity of illness, persistent disability needs, family advocacy; (9) **Outcomes**: improved engagement, satisfaction, function, reduced re-hospitalization

---

Recovery-oriented services (SAMHSA): person-centered, CHIME framework (Connectedness, Hope, Identity, Meaning, Empowerment). Peer support, shared decision-making, strengths-based, WRAP, Housing First, IPS supported employment. Both ''recovery in'' + ''recovery of''.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'psychiatry'
  and scenario = 'Healthcare system developing recovery-oriented mental health services';

update public.mcq_questions
set choices = '[{"label":"A","text":"Abstinence only requirement"},{"label":"B","text":"Addiction Medicine + Harm Reduction Integration"},{"label":"C","text":"No harm reduction"},{"label":"D","text":"Surgery"},{"label":"E","text":"Random"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Addiction Medicine + Harm Reduction Integration: (1) **Addiction as chronic disease**: - Brain disease model; - Treat with evidence-based interventions like other chronic diseases; - Reduce moralizing + stigma; - ASAM clinical model; (2) **Harm reduction principles**: - Meet people where they are; - Reduce harms of substance use while not requiring abstinence; - Pragmatic + compassionate; - Reduce stigma; - Save lives first; - Continuum: harm reduction → MAT → abstinence (individual journey); (3) **Specific interventions**: - **Naloxone distribution** + training (community + family + first responders) — reduces opioid overdose deaths; OTC in many places; - **Syringe service programs (SSP)** — clean needles, prevent HIV/HCV transmission; - **Drug checking** — fentanyl test strips, drug analysis; - **Safe consumption sites** (controversial in US, established in Europe, Canada, Australia) — supervised injection, prevent overdose, link to services; - **Medication-assisted treatment (MAT)** — buprenorphine, methadone, naltrexone — evidence-based, reduces mortality 50%; ASAM model; - **Low-threshold treatment** (no abstinence required for entry); - **Mobile + low-barrier services**; (4) **Integration into healthcare**: - **SBIRT** (Screening, Brief Intervention, Referral to Treatment) primary care; - **ED-initiated buprenorphine** (D''Onofrio JAMA 2015 — increases engagement); - **Hospitalization as opportunity** for treatment initiation; - **Addiction medicine consultation** — improves outcomes; - **Outpatient buprenorphine** — primary care + specialty; (5) **Address structural barriers**: - X-waiver removed 2023 (US — easier to prescribe buprenorphine); - Methadone access (clinics — restrictive); - Insurance coverage; - Stigma in healthcare; (6) **Co-occurring disorders** (dual diagnosis): - Integrated treatment essential; - Address mental health + substance use simultaneously; (7) **Hepatitis C treatment** regardless of active use — curative DAAs; (8) **HIV PrEP + treatment**; (9) **Modern**: - Stimulant use disorder no MAT yet — contingency management evidence-based; - Cannabis use disorder no FDA medication; - Opioid epidemic + fentanyl crisis = urgent harm reduction expansion; (10) **Multidisciplinary**: addiction medicine, primary care, psychiatry, infectious disease, social work, peer recovery support

---

Addiction + harm reduction: chronic disease model. Harm reduction (naloxone, SSP, drug checking, safe consumption, MAT) saves lives. SBIRT + ED-initiated buprenorphine + addiction consult. Integrated co-occurring treatment. HCV/HIV treatment. Stimulant — contingency management. Stigma reduction.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'psychiatry'
  and scenario = 'Hospital integrating addiction medicine + harm reduction approaches';

update public.mcq_questions
set choices = '[{"label":"A","text":"Individual responsibility only"},{"label":"B","text":"Healthcare Worker Mental Health + Burnout"},{"label":"C","text":"No support needed"},{"label":"D","text":"Surgery"},{"label":"E","text":"Random"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Healthcare Worker Mental Health + Burnout: (1) **Burnout** (Maslach): emotional exhaustion + depersonalization + reduced personal accomplishment; (2) **Prevalence high**: 40-60% physicians + nurses; worsened by COVID-19 pandemic; (3) **Consequences**: - Personal — depression, anxiety, substance use, suicide (physicians at elevated risk), divorce; - Patient care — medical errors, lower quality, reduced empathy; - System — turnover, absenteeism, workforce shortage; (4) **Drivers** (system-level not individual): - Workload + EHR documentation burden; - Lack of autonomy; - Inefficient processes; - Moral injury (constraints prevent providing care believed needed); - Toxic culture; - Insufficient support; - Inadequate staffing; (5) **System-level interventions** (essential — individual interventions alone insufficient): - **Reduce administrative burden** (EHR optimization, scribes); - **Leadership development**; - **Workload management**; - **Schedule flexibility**; - **Team-based care**; - **Stanford WellMD model**; (6) **Individual-level support**: - **Confidential mental health services** (separate from credentialing); - **Peer support programs** (Code Lavender, second victim); - **Employee assistance programs**; - **Wellness initiatives**; - **Mindfulness, exercise, sleep**; (7) **Stigma reduction**: - Mental health licensing questions — many states reformed to focus on impairment not history; - Confidential treatment; - Modeling — leadership disclosing own mental health; (8) **Substance use** in healthcare: - Higher rates in some specialties (anesthesiology, EM); - Physician Health Programs (PHP) — confidential treatment + monitoring; - Recovery support; (9) **Physician suicide**: - Higher rate especially female physicians; - Means restriction (medication access); - Address contributors; - Resources (988, NAMI, AMA, AFSP); (10) **Trainee mental health**: - Residents particularly vulnerable; - ACGME requirements + duty hour limits; - Resident wellness programs; - Mentorship; (11) **Pandemic-specific**: PTSD, moral injury, exhaustion — ongoing recovery; (12) **Multidisciplinary leadership + culture change** essential; (13) **Modern**: AMA + Joint Commission emphasis on system-level + Quintuple Aim including workforce well-being

---

Healthcare worker burnout: 40-60%; system-level drivers (workload, EHR, moral injury, culture). System interventions (reduce admin burden, leadership, workload), individual support (confidential care, peer support, EAP), stigma reduction (licensing), PHP for substance use, physician suicide prevention. Modern: Quintuple Aim.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'psychiatry'
  and scenario = 'Healthcare system improving mental health for healthcare workers + burnout';

update public.mcq_questions
set choices = '[{"label":"A","text":"Single specialty"},{"label":"B","text":"HIV + Stimulant Use Disorder + Depression + Social Instability — Integrated Multidisciplinary"},{"label":"C","text":"Refuse care due to non-adherence"},{"label":"D","text":"Surgery"},{"label":"E","text":"Random"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** HIV + Stimulant Use Disorder + Depression + Social Instability — Integrated Multidisciplinary: (1) **HIV care**: ART adherence + viral suppression — link to HIV care; ART medication interactions check (avoid ritonavir + many antidepressants); HCV/STI testing; CD4 + VL monitoring; PrEP for partners; (2) **Cocaine use disorder**: - NO FDA medication; - Contingency management most evidence-based; - CBT, motivational interviewing; - 12-step (CA, NA); - Address triggers + cravings; - Harm reduction (fentanyl test strips, naloxone availability — fentanyl contamination of cocaine); (3) **Depression**: - SSRI (sertraline, escitalopram — check ART interactions); - CBT, IPT; - Address comorbid; - Suicide assessment; (4) **Social determinants** (foundational — without addressing, treatment won''t stick): - **Housing First** — immediate stable housing reduces substance use, mental health symptoms, healthcare costs; - Income support, benefits, SSDI; - Employment (when ready) — Individual Placement + Support; - Health insurance enrollment; - Transportation; - Food security; - Legal assistance (civil + criminal); (5) **Adherence support**: - Pill organizers + reminders; - Directly observed therapy (DOT) for HIV in some models; - Address mental health + substance — major adherence drivers; - Patient-centered care; - Peer navigators; (6) **Integrated care site** ideal — co-located HIV, mental health, substance use, primary care, social work, case management; (7) **Trauma-informed care** — many at intersection have trauma history; (8) **Cultural + LGBTQ+ + minority affirmation** if applicable; (9) **Multidisciplinary**: infectious disease, psychiatry, addiction medicine, primary care, social work, peer support, housing specialist; (10) **Long-term**: chronic illnesses + chronic social complexity; sustained care + flexibility

---

Complex HIV + stimulant use + depression + unstable housing: integrated multidisciplinary essential. HIV care + ART (check interactions). Cocaine — contingency management. Depression SSRI + CBT. SOCIAL DETERMINANTS foundational (Housing First). Integrated site + peer support. Trauma-informed.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'psychiatry'
  and scenario = 'ผู้ป่วยอายุ 35 ปี HIV+ + cocaine use disorder + depression + medication non-adherence + unstable housing — multidisciplinary integrative management';

update public.mcq_questions
set choices = '[{"label":"A","text":"Escalating opioids"},{"label":"B","text":"Chronic Pain + OUD + PTSD + Insomnia + CVD — Integrative Multidisciplinary"},{"label":"C","text":"Single specialty"},{"label":"D","text":"Surgery first-line"},{"label":"E","text":"Random"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Chronic Pain + OUD + PTSD + Insomnia + CVD — Integrative Multidisciplinary: (1) **Bidirectional relationships**: pain ↔ depression ↔ PTSD ↔ sleep ↔ substance use; CVD added complexity; (2) **OUD treatment foundational**: - **Buprenorphine** — treats addiction + provides analgesia (partial mu agonist); ideal in this profile; less CV stress than methadone; lower diversion than oral opioids; - Methadone alternative; - Naltrexone after detox; - Reduces mortality 50%; (3) **Chronic pain non-opioid + non-pharmacologic**: - **CBT for chronic pain** (evidence-based); - **PT + graded exercise**; - **Mindfulness-based stress reduction**; - **Acceptance + commitment therapy**; - **SNRI** (duloxetine — pain + depression + reasonable CV profile); - **Topical** (lidocaine, capsaicin); - **Anticonvulsant** (gabapentin, pregabalin — caution misuse + falls + sedation); - **Procedure** (selective steroid injection, RFA); - AVOID escalating opioids beyond MAT; (4) **PTSD treatment**: - **Trauma-focused therapy** — PE, CPT, EMDR; - **SSRI** (sertraline, paroxetine FDA-approved); - **Prazosin** for nightmares; - AVOID benzodiazepines (worsen PTSD); - May address pain via stress reduction; (5) **Insomnia**: - **CBT-I** gold standard; - AVOID benzodiazepines + nightly opioids; - Melatonin agonist, DORA, low-dose trazodone, doxepin alternatives; - Sleep hygiene; (6) **CV considerations**: - SNRI duloxetine generally OK; - AVOID TCAs (cardiac toxicity); - AVOID stimulants if used; - Buprenorphine relatively cardiac-safer than methadone; - Methadone QTc — monitor ECG; - SSRI generally CV-safe; - Address modifiable CV risk (BP, lipids, glucose, smoking); (7) **Address comorbidity**: depression (very common), anxiety, sleep apnea (high CV risk + comorbid); (8) **Functional goals** > pain elimination; (9) **Multidisciplinary**: pain medicine, addiction medicine, psychiatry, cardiology, PT, behavioral health, primary care, social work, peer support; (10) **Trauma-informed** throughout; (11) **Patient education + self-management + safety planning** (naloxone available, suicide risk)

---

Chronic pain + OUD + PTSD + insomnia + CVD: integrative. Buprenorphine MAT foundation (treats OUD + pain). Non-opioid chronic pain (CBT, PT, duloxetine). PTSD trauma-focused + SSRI (AVOID BZD). CBT-I for sleep. CV-safe medications (avoid TCA). Multidisciplinary + trauma-informed.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'psychiatry'
  and scenario = 'ผู้ป่วยอายุ 45 ปี chronic pain (LBP) + opioid use disorder + PTSD + insomnia + comorbid CV disease — integrative care plan';

commit;
