-- ===============================================================
-- UPDATE chunk 6/8: psychiatry (25 questions)
-- ===============================================================

begin;

update public.mcq_questions
set choices = '[{"label":"A","text":"Repeat diagnostic workup at every visit"},{"label":"B","text":"Somatic Symptom Disorder (DSM-5: somatic symptoms distressing or disruptive + excessive thoughts/feelings/behaviors about sx + ≥ 6 mo; replaces somatization, undifferentiated somatoform)"},{"label":"C","text":"Long-term opioid for chronic pain"},{"label":"D","text":"Surgery"},{"label":"E","text":"Dismiss complaints"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Somatic Symptom Disorder (DSM-5: somatic symptoms distressing or disruptive + excessive thoughts/feelings/behaviors about sx + ≥ 6 mo; replaces somatization, undifferentiated somatoform): (1) **Validate symptoms** — patients suffer real distress; avoid dismissive language; (2) **Establish therapeutic alliance** with **single primary care provider** — regular scheduled visits (not symptom-driven); limit doctor shopping + repeat testing; (3) **CBT for somatic symptoms** — first-line; address catastrophic thinking, fear avoidance, attention to symptoms; behavioral activation; (4) **Antidepressants** can help — SSRI (especially with comorbid depression/anxiety), SNRI (duloxetine for chronic pain component); modest evidence; (5) **Avoid**: unnecessary procedures + diagnostic tests + medications + surgery; iatrogenic harm common (especially opioids); (6) **Address comorbidity**: depression (60%), anxiety, PTSD, panic, personality features; (7) **Mindfulness-based therapies + acceptance**; (8) **Function-focused** rather than cure-focused goals; (9) **Family education + support**; (10) **Distinguish**: - Illness anxiety disorder (preoccupation with having illness, minimal somatic sx); - Conversion/FND (neurological); - Factitious (intentional sx for sick role); - Malingering (external gain); - Medical illness — comorbid + may have actual medical issues; (11) **Long-term**: chronic; care coordination critical; gradual improvement; (12) **Multidisciplinary**: primary care (key), psychiatry, mental health, social work

---

Somatic Symptom Disorder: real symptoms + excessive thoughts/feelings/behaviors. Validate. Single PCP + limit repeat testing. CBT first-line. SSRI/SNRI for comorbid + chronic pain. AVOID iatrogenic harm (opioids, procedures). Function-focused. Distinguish from IAD/FND/factitious/malingering.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'psychiatry'
  and scenario = 'หญิงไทยอายุ 45 ปี × 5 ปี — multiple persistent somatic symptoms (pain, fatigue, GI, neurological complaints) + excessive thoughts/feelings/behaviors about them (high anxiety about health, persistent worry, time/energy excessively devoted) + medical workup repeatedly negative; functional impairment

MSE: somatic preoccupation + anxiety
No identifiable single medical disease explaining all sx';

update public.mcq_questions
set choices = '[{"label":"A","text":"Continue invasive testing"},{"label":"B","text":"Limited treatment outcomes"},{"label":"C","text":"Discharge with judgment"},{"label":"D","text":"Surgery"},{"label":"E","text":"Confront aggressively"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Factitious Disorder Imposed on Self (Munchausen syndrome — DSM-5: falsification of physical/psychological signs OR induction of injury/disease + deceptive behavior + presents self as ill/impaired/injured + absence of obvious external rewards): (1) **Confirmation** challenging — direct observation, video surveillance (ethical considerations), inconsistent labs, identifying injected substances; (2) **Sensitive confrontation** — collaborative approach with mental health professional; avoid hostile or punitive; offer ''face-saving'' alternative framing; many deny + leave; (3) **Treatment**: - **Psychotherapy** if patient accepts — psychodynamic, CBT; addresses underlying needs (sick role, attention, identity); - **Address comorbidity**: depression, personality disorder (especially borderline), trauma history common; - **Limited treatment outcomes** typically — chronic, recurrent; (4) **Avoid invasive procedures + medications when possible** — risk of iatrogenic harm + reinforcement; (5) **Document carefully** — across institutions if possible; coordinate care; (6) **Distinguish**: - Malingering (external gain — financial, legal, evasion); - Somatic symptom disorder (real symptoms, no fabrication); - Conversion disorder (involuntary); - Factitious imposed on another (Munchausen by proxy — child abuse — separate); (7) **Mandatory reporting if factitious imposed on another** (child) = child abuse; (8) **Ethical considerations**: hospital surveillance, confidentiality, informed consent; (9) **Multidisciplinary**: psychiatry, hospital ethics, primary care, social work; (10) **Healthcare provider burnout** — challenging cases; team support

---

Factitious Disorder: intentional production/feigning of sx without external reward (vs malingering). Sensitive confrontation + offer face-saving. Limited treatment outcomes. Avoid further invasive procedures. Address comorbid (BPD, trauma). Distinguish from malingering, somatic sx, conversion. Factitious imposed on another = abuse.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'psychiatry'
  and scenario = 'หญิงไทยอายุ 32 ปี nurse — recurrent hospitalizations × 5 ปี กับ varied symptoms (fever, abdominal pain, hematuria) ที่หา cause ไม่พบ + investigators discover she has been injecting saline + small amounts of bacteria into IV ทำให้เกิด fever + intentionally causing UTI by self-catheterization; ผู้ป่วยปฏิเสธ; ไม่มี external incentive (no insurance fraud, no disability claim, no legal motivation)

MSE: cooperative initially; becomes hostile when confronted with evidence';

update public.mcq_questions
set choices = '[{"label":"A","text":"Accept all reported symptoms without assessment"},{"label":"B","text":"Recognition through standardized assessment"},{"label":"C","text":"Provide requested diagnosis"},{"label":"D","text":"Surgery"},{"label":"E","text":"Refuse to engage"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Malingering — Intentional Production or Exaggeration of Symptoms for Identifiable External Reward (legal, financial, drug, military, disability) — NOT a psychiatric diagnosis in DSM but clinically relevant: (1) **Recognition through standardized assessment**: - **Validity testing** — TOMM (Test of Memory Malingering), MFAST, SIRS (Structured Interview of Reported Symptoms); - **Inconsistencies** across exams + time + collateral; - **Improbable or atypical symptoms**; - **External incentive** identified; (2) **High prevalence in forensic settings** — ~ 15-20% in some studies; (3) **Documentation careful**: objective findings, validity testing, inconsistencies — avoid ''diagnosing'' malingering definitively unless evidence robust; descriptive ''invalid presentation'' + ''symptom exaggeration'' acceptable; (4) **Coexistence** with real disorder possible — malingering + true PTSD; assess both; (5) **Differential**: - Factitious (no external reward — internal sick role); - Conversion/FND (involuntary); - True psychiatric disorder; (6) **Approach**: confront sensitively, offer alternative explanation, focus on functional capacity assessment for forensic question (competency, NGRI); (7) **Forensic implications**: court testimony, opinion stated as expert; (8) **Avoid moralizing** — clinical detachment; (9) **Provider safety + boundaries**; (10) **Modern**: complexity recognized — partial malingering, secondary gain spectrum, primary vs secondary

---

Malingering: intentional feigning for external reward (NOT DSM diagnosis). Validity testing (TOMM, SIRS). Documentation: objective findings + inconsistencies. May coexist with real disorder. Distinguish from factitious (no external) + conversion (involuntary). Forensic implications.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'psychiatry'
  and scenario = 'ชายไทยอายุ 30 ปี facing criminal charges — presents with claimed PTSD + cognitive impairment + ''voices'' affecting competency to stand trial; symptoms inconsistent on testing (improbable symptoms, exaggeration on validity testing, inconsistent across exams), atypical presentation, external incentive obvious (legal)

MMSE inconsistent (passes some hard items, fails easy)
Validity testing: TOMM fails (suggests poor effort)
SIRS: positive for feigning';

update public.mcq_questions
set choices = '[{"label":"A","text":"Ignore complaint"},{"label":"B","text":"SSRI-Induced Sexual Dysfunction (50-70% on SSRI experience; decreased libido, anorgasmia, delayed ejaculation, ED)"},{"label":"C","text":"Stop antidepressant abruptly"},{"label":"D","text":"Surgery"},{"label":"E","text":"No discussion"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** SSRI-Induced Sexual Dysfunction (50-70% on SSRI experience; decreased libido, anorgasmia, delayed ejaculation, ED): (1) **Risk-benefit discussion** — depression remission essential, sexual SE common; (2) **Strategies (in order of preference)**: - **Wait** — some tolerance develops (limited); - **Dose reduction** if possible; - **Switch antidepressant** to lower sexual SE: - **Bupropion** (no sexual SE; can replace SSRI if depression history without anxiety); - **Mirtazapine** (less sexual SE); - **Vortioxetine** (less than other SSRI); - **Vilazodone** (less); - **Augmentation/Antidote**: - **Bupropion 150 mg add to SSRI** — moderate evidence reduces sexual SE; - **Sildenafil/PDE5 inhibitor** — effective for ED + female sexual response (limited evidence women); - Buspirone — limited evidence; - Cyproheptadine, mirtazapine — historical; (3) **Drug holiday**: weekend off for short half-life SSRI (sertraline, paroxetine) — controversial, relapse risk; (4) **For women**: flibanserin (FDA approved HSDD — limited efficacy, side effects, alcohol interaction); bremelanotide (subcutaneous PRN); (5) **Behavioral**: couples therapy, sex therapy, communication, alternative intimate behaviors; (6) **Address relationship strain**: couples counseling; (7) **Address other contributors**: relationship dynamics, body image, hormonal (perimenopause), other medical, alcohol, fatigue from depression itself; (8) **Sertraline dose reduction** also reasonable strategy (lowest effective); (9) **Patient priorities** — shared decision; (10) **Multidisciplinary**: psychiatry, primary care, gynecology, urology, sex therapy

---

SSRI Sexual Dysfunction: common (50-70%). Strategies: wait, dose reduce, switch (bupropion, mirtazapine, vortioxetine, vilazodone), augment (bupropion adjunct, PDE5i), drug holiday (controversial). Women: flibanserin/bremelanotide. Address relationship + other contributors. Shared decision.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'psychiatry'
  and scenario = 'หญิงไทยอายุ 38 ปี on sertraline 100mg × 1 ปี for MDD (in remission) — new complaint: anorgasmia + decreased libido + marital strain; mood stable, otherwise functioning well

No other medications, no medical illness, healthy relationship pre-medication';

update public.mcq_questions
set choices = '[{"label":"A","text":"Conversion therapy"},{"label":"B","text":"Gender Dysphoria in Adolescent (DSM-5: marked incongruence between expressed/experienced gender + assigned gender + distress/impairment + ≥ 6 mo; adolescent criteria)"},{"label":"C","text":"Force assigned sex roles"},{"label":"D","text":"Surgery in childhood"},{"label":"E","text":"Ignore identity"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Gender Dysphoria in Adolescent (DSM-5: marked incongruence between expressed/experienced gender + assigned gender + distress/impairment + ≥ 6 mo; adolescent criteria): (1) **Gender-affirming care evidence-based** (WPATH SOC 8th, AAP, Endocrine Society): - **Psychosocial assessment** by experienced clinician — gender identity development, mental health (high comorbidity from minority stress), family support, school environment, persistent + consistent + insistent gender identity; - **NOT ''conversion therapy''** (illegal in many jurisdictions, harmful); (2) **Stepwise**: - **Social transition** (name, pronouns, clothing, presentation) — reversible; - **Puberty suppression** (GnRH agonists — leuprolide, histrelin) at Tanner 2-3 — pauses puberty to allow exploration; reversible; - **Gender-affirming hormones** (testosterone for transmen, estrogen + antiandrogen for transwomen) — partial reversibility; usually 16+; - **Gender-affirming surgery** — typically adult (top surgery may be considered earlier in some); (3) **Mental health**: address minority stress, depression, anxiety, suicide risk (very elevated — × 4-9 cisgender peers; reduced with affirming care); (4) **Family therapy + support**: PFLAG, gender-affirming family support; (5) **School/legal**: name change, school accommodations, sports policies, ID documents; (6) **Long-term follow-up**: bone health (puberty suppression), CV risk (estrogen), fertility preservation discussion, cancer screening; (7) **Multidisciplinary**: pediatric endocrinology, child psychiatry/psychology, primary care, surgery (later), social work, family; (8) **Modern**: depathologize identity itself (DSM-5-TR softened language); gender dysphoria — distress, NOT gender identity itself, is what is treated; (9) **Address minority stress** + societal stigma + advocacy

---

Gender Dysphoria adolescent: evidence-based gender-affirming care (WPATH SOC 8). Stepwise: social → puberty suppression → hormones → surgery (adult). Address minority stress + suicide risk. Family + school support. AVOID conversion therapy. Long-term follow-up. Multidisciplinary.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'psychiatry'
  and scenario = 'วัยรุ่นทรานส์อายุ 14 ปี assigned female at birth — long-standing dysphoria with assigned sex, identifies as male × 5 ปี consistently, marked distress + functional impairment, supportive family seeking gender-affirming care evaluation

DSM-5 GD criteria met
No psychotic features
Consistent identity over time + across settings';

update public.mcq_questions
set choices = '[{"label":"A","text":"High-dose benzodiazepine long-term"},{"label":"B","text":"Isolated Sleep Paralysis + History of NREM Parasomnia (sleep paralysis = REM atonia persisting into wake briefly; common — 30% lifetime; benign usually)"},{"label":"C","text":"No discussion"},{"label":"D","text":"Surgery"},{"label":"E","text":"Antibiotic"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Isolated Sleep Paralysis + History of NREM Parasomnia (sleep paralysis = REM atonia persisting into wake briefly; common — 30% lifetime; benign usually): (1) **Education + reassurance** — sleep paralysis common, brief, harmless; episodes self-limited; (2) **Sleep hygiene**: adequate sleep duration, regular schedule, avoid sleep deprivation (triggers), avoid supine sleep (triggers), reduce stress + alcohol + caffeine; (3) **Medication if severe + frequent**: REM-suppressing agents — SSRI (fluoxetine), TCA (clomipramine) — moderate evidence; (4) **NREM parasomnia** (sleepwalking, night terrors, sleep eating, sexsomnia) — different syndrome (first half of night, no recall, no atonia loss): - Sleep hygiene + adequate sleep (reduces); - Safety measures (lock doors, alarms, removing weapons, ground floor); - Address triggers (sleep deprivation, alcohol, fever, stress, medications — zolpidem famous trigger); - Medication if severe + injury risk: clonazepam HS, antidepressant; (5) **Distinguish**: REM parasomnia (RBD — late life, synucleinopathy prodrome) vs NREM parasomnia (childhood + young adult, benign usually); (6) **Sleep study (PSG)** if atypical features, injury, suspected RBD or OSA, possible nocturnal seizure (video EEG); (7) **Comorbidity assessment**: anxiety, depression (high comorbid sleep paralysis), narcolepsy (sleep paralysis component); (8) **Long-term**: usually benign + decreases with age; (9) **Multidisciplinary**: sleep medicine, psychiatry if comorbid anxiety

---

Isolated Sleep Paralysis: common, benign. Education + sleep hygiene first. REM-suppressant (SSRI/TCA) if severe. NREM parasomnia: safety measures + sleep hygiene + clonazepam if injury risk. Distinguish RBD (synucleinopathy prodrome) vs NREM (childhood/young, benign).'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'psychiatry'
  and scenario = 'ชายไทยอายุ 25 ปี — recurrent isolated sleep paralysis (cannot move at sleep onset/offset) + vivid hypnagogic hallucinations + family hx of sleepwalking + sleep-related eating in adolescence (no longer); functional but anxious about episodes

PSG normal sleep architecture
No narcolepsy (MSLT normal, no cataplexy)
No OSA';

update public.mcq_questions
set choices = '[{"label":"A","text":"Proceed with trial regardless"},{"label":"B","text":"Two Dusky prongs"},{"label":"C","text":"Auto-NGRI defense"},{"label":"D","text":"Surgery"},{"label":"E","text":"Ignore mental illness"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Competency to Stand Trial Evaluation (Dusky standard — sufficient present ability to consult with attorney with reasonable degree of rational understanding + rational + factual understanding of proceedings against him): (1) **Two Dusky prongs**: - **Factual understanding** of court (charges, roles, plea options, possible outcomes); - **Rational understanding** + ability to consult attorney; (2) **This patient**: factual understanding partial; rational understanding + attorney consultation impaired by paranoid delusions → likely INCOMPETENT; (3) **Recommendation to court**: incompetent to stand trial → restoration treatment; (4) **Restoration**: - Inpatient or outpatient depending on jurisdiction + severity; - Treat underlying disorder (antipsychotic for psychosis); - Education about legal proceedings; - Reassess periodically; - **Sell v United States** ruling — involuntary medication for restoration possible under specific criteria (important government interest, treatment medically appropriate, less intrusive alternatives considered, substantially likely to render competent); (5) **If unrestorable** — civil commitment, charges may be dropped (Jackson v Indiana — cannot indefinitely commit for restoration); (6) **Distinguish competency from**: - **NGRI** (insanity at time of offense — different question); - **Mens rea** (specific intent); - **General psychiatric assessment**; (7) **Forensic evaluator** — specially trained psychiatrist/psychologist; not the treating clinician (boundary); (8) **Report to court** — clear, specific, opinion; (9) **Documentation careful**; (10) **Multidisciplinary**: forensic psychiatry, treating team, attorneys, court

---

Competency to Stand Trial (Dusky): factual + rational understanding + consult attorney. Distinguished from NGRI (time of offense). Restoration treatment (antipsychotic). Sell ruling — involuntary medication for restoration possible. Jackson — cannot indefinitely commit for restoration. Forensic evaluator separate from treating.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'psychiatry'
  and scenario = 'ชายไทยอายุ 32 ปี facing criminal charges (assault) — defense requests competency to stand trial evaluation; patient has schizophrenia, paranoid sx, partially treated; can describe basic court procedure but cannot identify roles of defense vs prosecution + believes attorney working against him + cannot rationally consult with attorney

MSE: alert, oriented x3, but paranoid + delusional content interfering with reality testing';

update public.mcq_questions
set choices = '[{"label":"A","text":"Discharge without admission"},{"label":"B","text":"Civil Commitment / Involuntary Hospitalization (criteria vary by jurisdiction; in Thailand — Mental Health Act 2008; general principles)"},{"label":"C","text":"Indefinite commitment without review"},{"label":"D","text":"Surgery"},{"label":"E","text":"Refuse evaluation"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Civil Commitment / Involuntary Hospitalization (criteria vary by jurisdiction; in Thailand — Mental Health Act 2008; general principles): (1) **Standard criteria** (vary by state/country): - **Mental illness** (severe); - **Imminent danger to self or others** OR **grave disability** (unable to care for basic needs); - **Treatment available** that would benefit; - **Least restrictive alternative** considered; (2) **This patient meets criteria** — danger to others, mental illness, treatment available; (3) **Procedure**: - Initial emergency hold (typically 72h US; varies); - Court hearing for extended commitment; - Patient rights: notice, hearing, attorney, appeal; - Due process protections; (4) **Treatment during commitment**: - Antipsychotic + supportive care; - Right to refuse treatment varies: many jurisdictions require additional court order for involuntary medication; - **Less restrictive alternatives** — assertive community treatment, outpatient commitment, partial hospitalization; (5) **Outpatient commitment** (Kendra''s Law in NY, Laura''s Law in CA, AOT — assisted outpatient treatment): involuntary outpatient treatment as alternative or post-discharge; (6) **Discharge planning**: medication adherence, follow-up, family + community supports; (7) **Documentation** — court testimony, certification; (8) **Ethics**: paternalism vs autonomy balance; (9) **Cultural considerations**: stigma, family involvement varies; (10) **Modern**: emphasis on least restrictive + recovery-oriented + supported decision-making; **multidisciplinary**: psychiatry, social work, legal, family

---

Civil Commitment: mental illness + imminent danger or grave disability + treatment available + least restrictive. Emergency hold → court hearing. Due process. Right to refuse medication (may require separate order). Outpatient commitment alternative. Modern: recovery-oriented + least restrictive.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'psychiatry'
  and scenario = 'ชายไทยอายุ 28 ปี severe schizophrenia + active command auditory hallucinations to harm family + recent threat with knife; refuses voluntary admission + refuses medication; family + ED team requesting involuntary hospitalization

MSE: paranoid, delusional, hallucinations, threatening
Lacks insight, refuses treatment
In Thailand: Mental Health Act 2008 applies';

update public.mcq_questions
set choices = '[{"label":"A","text":"Restraints first-line without verbal de-escalation"},{"label":"B","text":"Acute Agitation Management — Stepwise"},{"label":"C","text":"High-dose multiple agents combination immediately"},{"label":"D","text":"Surgery"},{"label":"E","text":"Discharge without intervention"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Acute Agitation Management — Stepwise: (1) **Verbal de-escalation first** — Project BETA (Best practices in Evaluation + Treatment of Agitation): - Respect personal space; - Calm, low voice, non-threatening; - Active listening; - Brief, simple language; - Offer choices; - Identify needs + wants; (2) **Environmental**: reduce stimuli, remove weapons/objects, escape route preserved, others'' safety, calm setting if possible; (3) **Show of force** — security presence; (4) **Voluntary medication offered first**: - Oral options: lorazepam, haloperidol, olanzapine, risperidone; - Oral disintegrating tablets (asenapine, olanzapine ODT); - Inhaled loxapine (rapid); (5) **IM medication if necessary** + patient cannot accept oral: - **Lorazepam 1-2 mg IM** (no IV needed); - **Haloperidol 5 mg IM** (extrapyramidal risk; QTc); - **Combined Haldol + Ativan + Benadryl (''B-52'')** historical; - **Olanzapine 10 mg IM** (caution with concurrent BZD — hypotension); - **Ziprasidone 20 mg IM** (QTc); - **Droperidol** (faster, more sedating, QTc warning historically); (6) **AVOID IM in known causes when oral possible**; (7) **Restraint last resort** — least restrictive principle; if needed: appropriate technique, time-limited, frequent reassessment, debriefing afterwards; (8) **After acute**: investigate cause (delirium, intoxication, psychiatric, medical); cannot give appropriate treatment until cause known; (9) **Documentation**: behaviors, interventions, response; (10) **Trauma-informed**: many patients have trauma history — restraint can retraumatize; debrief afterward; (11) **Special populations**: pregnancy (lorazepam, haloperidol relatively safer; avoid valproate), pediatrics (lower doses, oral), elderly (avoid BZD if possible — lower antipsychotic dose, watch QTc, falls), known long QTc

---

Agitation Management (Project BETA): verbal de-escalation first → voluntary medication → IM if needed → restraint last resort. Lorazepam, haloperidol, olanzapine, ziprasidone IM options. Cause-specific treatment after acute control. Trauma-informed. Special populations (pregnancy, peds, elderly).'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'psychiatry'
  and scenario = 'ชายไทยอายุ 40 ปี acute psychiatric ED — severe agitation + threatening; patient hx unknown (no records); refuses cooperation; staff + patient safety at risk; verbal de-escalation attempted but failed

No IV access
Unknown medical history
No intoxication confirmed but possible';

update public.mcq_questions
set choices = '[{"label":"A","text":"Continue medications"},{"label":"B","text":"Discontinue serotonergic agents immediately"},{"label":"C","text":"Antipsychotic for agitation"},{"label":"D","text":"Bromocriptine"},{"label":"E","text":"Surgery"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Serotonin Syndrome (excess serotonergic activity; combinations of SSRIs + MAOI, tramadol, linezolid, methylene blue, triptans, dextromethorphan, lithium, St John''s wort, MDMA — high risk) — Hunter Criteria: serotonergic agent + clonus (spontaneous, inducible, ocular) ± agitation, sweating, tremor, hyperreflexia, hyperthermia; (1) **Discontinue serotonergic agents immediately** (fluoxetine + tramadol here); (2) **Supportive care**: - IV fluid resuscitation; - **Cooling** for hyperthermia (active cooling, intubation + paralysis if T > 41°C — neuromuscular blockade with non-depolarizing); - Cardiac monitoring; - Monitor for rhabdomyolysis, DIC, renal failure; (3) **Benzodiazepine** (lorazepam, diazepam) — sedation + reduce muscle activity + reduce CV sx + first-line agent; (4) **Cyproheptadine** (oral 5-HT2A antagonist) — antidote; initial 12 mg then 2 mg q2h until response; max 32 mg/d; (5) **AVOID**: physical restraint without paralysis (worsens hyperthermia + rhabdo); bromocriptine (worsens — dopamine, not serotonin); dantrolene controversial; antipyretics (centrally mediated, not effective); (6) **Distinguish from NMS** (similar features but: rigidity lead-pipe, hyporeflexia, slow onset, antipsychotic context vs serotonin syndrome: clonus, hyperreflexia, GI, rapid onset, serotonergic context); (7) **Most cases resolve 24h** with cessation + supportive; severe can be fatal; (8) **Education + medical alert** + careful future medication; (9) **Multidisciplinary**: emergency, ICU, psychiatry, pharmacy; (10) **Especially watch combinations**: SSRI + tramadol, SSRI + linezolid, SSRI + MAOI (washout period 14 d for irreversible MAOI; 5 wk fluoxetine)

---

Serotonin Syndrome: serotonergic agents + Hunter criteria (clonus, hyperreflexia, autonomic, GI). Discontinue → supportive + cooling + benzodiazepine + cyproheptadine antidote. Distinguish from NMS (rigidity, hyporeflexia, antipsychotic). SSRI + tramadol classic. Washout MAOI 14d (5wk fluoxetine).'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'psychiatry'
  and scenario = 'หญิงไทยอายุ 35 ปี on fluoxetine 40mg + recent addition of tramadol for pain — มาด้วย acute confusion, agitation, hyperreflexia, clonus (inducible + spontaneous, lower extremities), diaphoresis, hyperthermia 39.5°C, tachycardia 130, hypertension, dilated pupils, GI sx (nausea, diarrhea)

No recent muscle rigidity (no lead-pipe), no encephalopathy beyond confusion
CK mildly elevated
Hunter criteria met';

update public.mcq_questions
set choices = '[{"label":"A","text":"Haloperidol IM for agitation"},{"label":"B","text":"Anticholinergic Toxicity (diphenhydramine, antipsychotic, TCA, scopolamine, jimson weed, oxybutynin, benztropine, atropine — additive)"},{"label":"C","text":"Discharge home"},{"label":"D","text":"Surgery"},{"label":"E","text":"TCA-style sodium bicarbonate without TCA"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Anticholinergic Toxicity (diphenhydramine, antipsychotic, TCA, scopolamine, jimson weed, oxybutynin, benztropine, atropine — additive): (1) **Decontamination**: - Activated charcoal if within 1-2h ingestion + intact airway; - Gastric lavage rarely; - Cardiac monitoring; (2) **Supportive care**: - IV fluids; - **Cooling** for hyperthermia; - Foley if urinary retention; - Treat agitation with **benzodiazepine** (not haloperidol — anticholinergic + lowers seizure threshold); (3) **Physostigmine** (centrally acting acetylcholinesterase inhibitor) — antidote for severe anticholinergic delirium + agitation; - **Indications**: severe agitation + delirium + hallucinations + tachycardia not responsive to BZD; - **Dose**: 0.5-2 mg slow IV with cardiac monitoring; can repeat; - **Contraindications**: TCA overdose (wide QRS — risk asystole, seizure; sodium bicarbonate for TCA), bradycardia, conduction blocks, asthma/COPD, bowel obstruction; - **Side effects**: bradycardia, bronchospasm, seizures, cholinergic crisis (atropine antidote available); (4) **Watch for cardiac**: anticholinergic-induced arrhythmia, especially with TCA component; (5) **TCA overdose specifically** — wide QRS (Na channel blockade) — **sodium bicarbonate** to widen Na gradient, narrow QRS; serum alkalinization; (6) **Distinguish from**: sympathomimetic (sweating + bowel sounds + mydriasis — but moist not dry), sedative-hypnotic, serotonin syndrome, NMS, opioid withdrawal; (7) **Monitor**: cardiac, hyperthermia, rhabdomyolysis, mental status; (8) **Psychiatric eval after medical stabilization** — intentional overdose suicide risk vs accidental vs recreational; (9) **Multidisciplinary**: emergency, toxicology (poison control), psychiatry, ICU if severe; (10) **Disposition**: medical stabilization + psychiatric admission if suicidal + addiction if recreational pattern

---

Anticholinergic Toxicity: mad/hot/dry/red/blind/full. Supportive + benzodiazepine. Physostigmine for severe delirium + agitation (NOT in TCA overdose — wide QRS asystole risk). TCA overdose: sodium bicarbonate. Distinguish from sympathomimetic, serotonin syndrome. Psychiatric eval after stabilization.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'psychiatry'
  and scenario = 'วัยรุ่นชายอายุ 16 ปี — recreational ingestion ของ diphenhydramine 30 tablets — มา ED ด้วย delirium + visual hallucinations + flushed dry skin + dilated pupils + dry mucous membranes + urinary retention + tachycardia 130 + hyperthermia 38.5°C + bowel sounds absent

ECG: sinus tachycardia, QRS narrow
''Hot as a hare, dry as a bone, red as a beet, mad as a hatter, blind as a bat, full as a flask''';

update public.mcq_questions
set choices = '[{"label":"A","text":"Diagnose as depression relapse + increase dose"},{"label":"B","text":"FINISH mnemonic"},{"label":"C","text":"Continue cold-turkey"},{"label":"D","text":"Surgery"},{"label":"E","text":"Antibiotic"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** SSRI/SNRI Discontinuation Syndrome (esp short half-life agents — paroxetine, venlafaxine, fluvoxamine, duloxetine, sertraline — not fluoxetine due to long half-life; not addictive — physiologic adaptation): (1) **FINISH mnemonic**: **F**lu-like symptoms, **I**nsomnia/vivid dreams, **N**ausea, **I**mbalance/dizziness, **S**ensory disturbance (brain zaps, paresthesias), **H**yperarousal/anxiety; (2) **Onset**: 1-7 days after discontinuation; typically resolves 1-3 weeks; (3) **Treatment**: - **Restart at previous dose** then **taper gradually**; - Switch to long half-life agent (fluoxetine) then taper from there; - For severe — symptom-targeted (anti-nausea, dimenhydrinate for vertigo, short-term sleep aid); (4) **Prevention**: - Slow taper over weeks-months (especially long-term use, high dose, prior discontinuation issues); - Patient education at prescribing; - Hyperbolic tapering — smaller proportional reductions at lower doses (1mg + 0.5mg increments for paroxetine at end); - Avoid abrupt cessation; (5) **Distinguish from depression relapse**: - Discontinuation: physical sx (flu-like, dizziness, brain zaps), rapid onset days after stopping, resolves with restart; - Relapse: gradual reemergence of original depression sx, longer; (6) **Education**: not addiction, physiologic; importance of adherence + planned discontinuation; (7) **Risk factors**: short half-life agent, longer duration of treatment, higher dose, anxious sensitivity; (8) **Multidisciplinary**: prescriber + patient communication; (9) **Long-term discontinuation strategies** — increasing evidence base for very slow tapers (months-years) for some patients

---

SSRI Discontinuation Syndrome: FINISH (flu-like, insomnia, nausea, imbalance, sensory zaps, hyperarousal). Short half-life > long. Restart + taper gradually OR switch to fluoxetine. Hyperbolic tapering. Distinguish from relapse. NOT addiction.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'psychiatry'
  and scenario = 'หญิงไทยอายุ 40 ปี on paroxetine 40 mg × 2 ปี (depression in remission), self-discontinued 5 วันก่อนเพราะลืมยา — มาด้วย dizziness, electric shock sensations (brain zaps), nausea, vivid dreams, irritability, flu-like symptoms, anxiety; not depression relapse

No other medical cause';

update public.mcq_questions
set choices = '[{"label":"A","text":"Phenytoin for seizure"},{"label":"B","text":"Tricyclic Antidepressant Overdose — High Mortality (cardiac toxicity Na channel blockade, anticholinergic, alpha-blockade, serotonin/norepinephrine, GABA-A)"},{"label":"C","text":"Procainamide for arrhythmia"},{"label":"D","text":"Physostigmine"},{"label":"E","text":"Discharge home"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Tricyclic Antidepressant Overdose — High Mortality (cardiac toxicity Na channel blockade, anticholinergic, alpha-blockade, serotonin/norepinephrine, GABA-A): (1) **ABC + Cardiac monitoring** — intubation if obtunded; (2) **IV access, fluids**; (3) **Sodium bicarbonate** — backbone of treatment: - For QRS > 100 ms, ventricular arrhythmia, hypotension; - 1-2 mEq/kg bolus → infusion to maintain pH 7.45-7.55; - Mechanism: Na load + alkalosis displaces TCA from Na channels; - Monitor serum bicarbonate, K, Na, pH; (4) **Activated charcoal** if within 1-2h + intact airway (controversial benefit but consider); (5) **Seizure** — benzodiazepine; AVOID phenytoin (Na channel blocker — worsens); (6) **Hypotension** — IV fluid first, then norepinephrine (preferred — vs dopamine which is partially indirect — less effective when norepinephrine depleted); (7) **Arrhythmia**: - Wide QRS + ventricular arrhythmia → sodium bicarbonate; - AVOID class IA antiarrhythmics (procainamide, quinidine — Na channel — worsen); - **Lidocaine** acceptable for refractory; - Magnesium for torsades; - Lipid emulsion therapy considered for refractory; - **Intralipid** (lipid sink — moves TCA out of cardiac tissue); - ECMO last resort; (8) **Avoid**: physostigmine (asystole risk), flumazenil (seizure), class IA antiarrhythmic; (9) **Disposition**: ICU; minimum 6h observation if asymptomatic with normal QRS; longer if any signs; (10) **Psychiatric evaluation after stabilization** — suicide attempt; (11) **Long-term**: rethink TCA prescribing for suicidal patients (lethal overdose vs SSRI safer); limit dispensing; (12) **Multidisciplinary**: emergency, ICU, toxicology, psychiatry

---

TCA Overdose: cardiac toxicity (wide QRS, R in aVR). Sodium bicarbonate backbone. Benzodiazepine for seizure (NOT phenytoin — Na blocker). Norepinephrine for hypotension. AVOID class IA antiarrhythmic + physostigmine + flumazenil. Lipid emulsion for refractory. ICU. Psych eval after stabilization.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'psychiatry'
  and scenario = 'หญิงไทยอายุ 28 ปี intentional overdose amitriptyline 50 tablets 2 ชั่วโมงก่อน — มาด้วย CNS depression, seizure × 1, anticholinergic features, hypotension, tachycardia

ECG: sinus tachycardia, QRS 160 ms (wide), R wave in aVR > 3 mm
3 R''s: Rightward R wave aVR, Right axis deviation';

update public.mcq_questions
set choices = '[{"label":"A","text":"Confront alters directly"},{"label":"B","text":"Dissociative Identity Disorder (DID — DSM-5: ≥ 2 distinct personality states + recurrent gaps in recall + symptoms cause distress; not cultural/religious)"},{"label":"C","text":"Single-session treatment"},{"label":"D","text":"Surgery"},{"label":"E","text":"No treatment"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Dissociative Identity Disorder (DID — DSM-5: ≥ 2 distinct personality states + recurrent gaps in recall + symptoms cause distress; not cultural/religious): (1) **Trauma-focused phase-based treatment** (ISSTD Guidelines): - **Phase 1 — Safety + Stabilization**: skills (grounding, distress tolerance, emotion regulation), safety planning, address self-harm, build alliance, psychoeducation; - **Phase 2 — Trauma processing**: gradual exposure to trauma memories + integration; - **Phase 3 — Integration + Rehabilitation**: integration of identity states OR functional cooperation; reduce dissociation; daily life; (2) **Psychotherapy primary** — long-term (years); specialized training in DID; (3) **Address comorbidity**: PTSD (always present essentially), depression, self-harm, substance use, eating disorders; (4) **Medication symptomatic**: SSRI for depression/PTSD/anxiety; prazosin for nightmares; sleep agents; AVOID benzodiazepines long-term (worsen dissociation + dependence in trauma population); (5) **Safety planning** + self-harm + suicide risk (high); hospitalization for crisis (brief); (6) **AVOID**: - Iatrogenic creation of alters (controversial — high suggestibility); - Confronting alters; - Hypnosis without specialized training; (7) **Family/relationship**: education, support, sometimes couples therapy; (8) **DID controversial historically** — increasing acceptance + validity; under-diagnosis common (vs over-diagnosis controversy in 1990s); (9) **Distinguish from**: - Borderline PD (overlap exists but DID has distinct identity states + amnesia); - Schizophrenia (psychotic, no distinct identities); - Malingering (validity assessment); - Iatrogenic (avoid through careful technique); - Cultural possession states (different); (10) **Multidisciplinary**: trauma-specialized psychiatry + therapy

---

Dissociative Identity Disorder: trauma-focused phase-based treatment (ISSTD): safety/stabilization → trauma processing → integration. Long-term specialized therapy. SSRI for comorbidity. AVOID BZD + iatrogenic alter creation. Distinguish from BPD, psychosis, malingering. Trauma history universal.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'psychiatry'
  and scenario = 'หญิงไทยอายุ 30 ปี × longstanding (childhood) — distinct identity states (alters) recurrently take control of behavior, amnesia for events when alter present, severe childhood physical + sexual abuse documented; functional impairment + distress; comorbid PTSD, depression, self-harm

MSE: cooperative, dissociative episodes during sessions, alter introductions occur
Not due to substance/medical/cultural/religious practice (specific exclusions DSM-5)';

update public.mcq_questions
set choices = '[{"label":"A","text":"High-dose benzodiazepine long-term"},{"label":"B","text":"Depersonalization/Derealization Disorder (DSM-5: persistent or recurrent depersonalization + derealization + intact reality testing + distress/impairment + not substance/medical/other psychiatric)"},{"label":"C","text":"Cannabis to cope"},{"label":"D","text":"Surgery"},{"label":"E","text":"Antibiotic"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Depersonalization/Derealization Disorder (DSM-5: persistent or recurrent depersonalization + derealization + intact reality testing + distress/impairment + not substance/medical/other psychiatric): (1) **Limited evidence base** + chronic condition: (2) **Psychotherapy first-line**: - **CBT** — grounding techniques, cognitive restructuring, addressing catastrophic interpretation of sx, behavioral activation; - **Psychodynamic** for trauma history; - **Mindfulness-based** approaches; - Specialized DPD programs limited but emerging; (3) **Medication**: - **SSRI** (especially with comorbid depression/anxiety/OCD) — modest evidence; fluoxetine, fluvoxamine; - **Lamotrigine** (off-label, modest evidence — small trials); - **Naltrexone** (off-label, mechanism unclear, some evidence); - **AVOID**: benzodiazepines (worsen depersonalization); cannabis (often triggers/worsens — patient education); (4) **Address triggers/precipitants**: panic attacks, substance use (cannabis especially), trauma, stress, sleep deprivation; (5) **Address comorbidity**: depression (60%), anxiety, OCD, PTSD; (6) **Education**: depersonalization is a recognized condition; symptoms can wax + wane; reduce catastrophic interpretation; not psychosis; not ''going crazy''; (7) **Avoid**: substance use, cannabis, hyperventilation; (8) **Self-help groups + online resources**; (9) **Distinguish from**: - Panic attack (DPD episodes brief); - Psychosis (reality testing intact in DPD); - PTSD (dissociation in trauma context); - Schizophrenia (no hallucinations/delusions); - Substance-induced (especially cannabis); (10) **Long-term**: chronic but partial improvement common with treatment; (11) **Multidisciplinary**: psychiatry + psychotherapy

---

Depersonalization/Derealization Disorder: persistent + intact reality testing. CBT + grounding first-line. SSRI for comorbid. Lamotrigine modest evidence. AVOID benzodiazepines + cannabis (worsen). Address triggers. Education. Distinguish from psychosis, panic, PTSD, substance.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'psychiatry'
  and scenario = 'ชายไทยอายุ 22 ปี × 18 เดือน — persistent depersonalization (detached from own body, observing self from outside, emotional numbing, feeling unreal) + derealization (world feels foggy, dreamlike) — intact reality testing throughout; distress + functional impairment

No psychotic features, no substance use
No significant trauma history identified
PHQ-9: 12 (moderate depression — secondary)';

update public.mcq_questions
set choices = '[{"label":"A","text":"Single pathway"},{"label":"B","text":"Four Major Dopamine Pathways + Clinical Implications"},{"label":"C","text":"No clinical relevance"},{"label":"D","text":"Random"},{"label":"E","text":"Surgery"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Four Major Dopamine Pathways + Clinical Implications: (1) **Mesolimbic** (VTA → nucleus accumbens, limbic): - Positive symptoms of schizophrenia (hyperdopaminergic — hallucinations, delusions); - D2 blockade by antipsychotic → therapeutic effect on positive sx; - Reward circuit — addiction pathophysiology; substance use → DA release; (2) **Mesocortical** (VTA → prefrontal cortex): - Hypodopaminergic in schizophrenia → negative + cognitive sx (alogia, avolition, executive dysfunction); - Typical antipsychotics worsen mesocortical further (D2 blockade) → worsen negative + cognitive; - Atypical antipsychotics (5-HT2A antagonism) increase DA release in mesocortical → less worsening of negative; (3) **Nigrostriatal** (substantia nigra → striatum/basal ganglia): - Motor control; - D2 blockade → EPS (acute dystonia, akathisia, parkinsonism, tardive dyskinesia); - Parkinson''s disease — neurodegeneration → motor sx; - Typical antipsychotics > atypical for EPS risk; (4) **Tuberoinfundibular** (hypothalamus → pituitary): - Tonic dopamine inhibits prolactin release; - D2 blockade → hyperprolactinemia (amenorrhea, galactorrhea, sexual dysfunction, gynecomastia, bone loss); - Risperidone, paliperidone, haloperidol highest prolactin elevation; - Aripiprazole partial agonist often LOWERS prolactin; (5) **Clinical**: balance therapeutic mesolimbic D2 blockade with side effects in other pathways = challenge of antipsychotic treatment; atypicals + partial agonists (aripiprazole, brexpiprazole, cariprazine) try to selectively modulate

---

Dopamine pathways: mesolimbic (positive sx, D2 blockade therapeutic), mesocortical (negative/cognitive sx, hypodopaminergic), nigrostriatal (EPS), tuberoinfundibular (prolactin). Atypicals + partial agonists try selective modulation.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'psychiatry'
  and scenario = 'Resident ถามเรื่อง dopamine pathways + clinical relevance ใน schizophrenia treatment';

update public.mcq_questions
set choices = '[{"label":"A","text":"Single receptor"},{"label":"B","text":"Serotonin (5-HT) Receptors + Clinical Implications"},{"label":"C","text":"No relevance"},{"label":"D","text":"Random"},{"label":"E","text":"Surgery"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Serotonin (5-HT) Receptors + Clinical Implications: (1) **5-HT1A**: - Partial agonist anxiolytic (buspirone), antidepressant adjunct (aripiprazole, brexpiprazole partial agonist, vilazodone, vortioxetine partial agonist component); - Autoreceptor (somatodendritic) initially decreases serotonin → adaptation explains 4-6 wk delay of SSRI; (2) **5-HT1B/1D**: triptans for migraine (vasoconstriction, neuromodulation); (3) **5-HT2A**: - Antagonism → antipsychotic atypical effect (clozapine, risperidone, olanzapine, quetiapine etc.) — reduces EPS + improves negative sx (by increasing dopamine mesocortical); - Inverse agonist pimavanserin for PD psychosis (no D2 effect); - Hallucinogens (LSD, psilocybin, DMT) = 5-HT2A agonists → therapeutic potential research (depression, PTSD, addiction, end-of-life distress); - Sleep architecture (5-HT2A antagonist increases slow-wave sleep — trazodone, mirtazapine); (4) **5-HT2C**: - Antagonism → weight gain (olanzapine, clozapine, mirtazapine — significant metabolic SE); - Agonist lorcaserin (withdrawn — cancer signal) for weight loss historical; (5) **5-HT3**: - Antagonist antiemetic (ondansetron) — also mirtazapine 5-HT3 antagonist (anti-nausea + appetite increase); (6) **5-HT6**: cognition research target; (7) **5-HT7**: vortioxetine partial; circadian rhythms, mood; (8) **SSRI mechanism**: increased synaptic 5-HT → downstream effects on multiple receptors → adaptation over weeks → BDNF + neuroplasticity hypothesis of clinical effect; (9) **Serotonin syndrome**: excess from MULTIPLE serotonergic agents; (10) **Modern psychedelic research**: psilocybin (5-HT2A agonist) FDA breakthrough for TRD

---

Serotonin receptors: 5-HT1A (anxiolytic, autoreceptor SSRI delay), 5-HT2A (atypical antipsychotic, hallucinogen, sleep), 5-HT2C (weight), 5-HT3 (antiemetic), 5-HT6/7 (research). SSRI mechanism: increased 5-HT → BDNF + neuroplasticity. Psychedelic research expanding.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'psychiatry'
  and scenario = 'Resident ถามเรื่อง serotonin receptors + therapeutic relevance';

update public.mcq_questions
set choices = '[{"label":"A","text":"No HPA relevance"},{"label":"B","text":"HPA Axis Stress Response + Psychiatric Disorders"},{"label":"C","text":"Single hormone"},{"label":"D","text":"Random"},{"label":"E","text":"Surgery"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** HPA Axis Stress Response + Psychiatric Disorders: (1) **HPA axis**: hypothalamus → CRH → pituitary → ACTH → adrenal cortex → cortisol; negative feedback on hypothalamus + pituitary; circadian rhythm (peak AM, trough PM); (2) **Depression**: - HPA dysregulation common — elevated cortisol, blunted DST suppression, blunted CRH stimulation response; - Dexamethasone Suppression Test (DST) — historical research tool; not clinical diagnostic; - Chronic elevation contributes to hippocampal atrophy + neurodegenerative changes; - Mechanism partial — antidepressants normalize HPA over weeks (correlates with response); (3) **Anxiety disorders**: dysregulated HPA — both hyper- + hypo-cortisol patterns described; (4) **PTSD**: paradoxically LOW cortisol + enhanced feedback sensitivity (Yehuda); abnormal stress response; cortisol low pre-trauma may predispose to PTSD; (5) **Childhood trauma**: alters HPA axis development → lifelong dysregulation; epigenetic effects; (6) **Cushing''s syndrome** (hypercortisolism): - 50-80% develop psychiatric sx — depression most common, also mania/hypomania, psychosis, anxiety, cognitive; - Treat underlying Cushing''s; - Steroid-induced psychiatric sx — common with exogenous steroids (prednisone) — depression, mania, psychosis, especially > 40mg prednisone equivalent; (7) **Addison''s** (hypocortisolism): apathy, depression, fatigue, irritability; (8) **Premenstrual + postpartum hormonal**: estrogen + progesterone fluctuations affect mood (PMDD, postpartum mood disorders); (9) **Thyroid**: hyperthyroid — anxiety, mania; hypothyroid — depression, cognitive; (10) **Modern**: glucocorticoid receptor antagonism research (mifepristone for psychotic depression — limited evidence); (11) **Inflammation hypothesis**: HPA + inflammation interactions — cytokines, depression-inflammation link

---

HPA Axis: depression → hyper-cortisol, PTSD → low cortisol, childhood trauma → lifelong dysregulation. Cushing''s → 50-80% psychiatric sx. Steroid-induced. Hormonal psychiatry (PMDD, postpartum, thyroid). Inflammation hypothesis.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'psychiatry'
  and scenario = 'Resident ถามเรื่อง HPA axis + stress + psychiatric disorders';

update public.mcq_questions
set choices = '[{"label":"A","text":"No relevance"},{"label":"B","text":"Cytochrome P450 in Psychiatric Pharmacology"},{"label":"C","text":"Single enzyme"},{"label":"D","text":"Random"},{"label":"E","text":"Surgery"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Cytochrome P450 in Psychiatric Pharmacology: (1) **Key CYPs**: - **CYP2D6**: most psychotropic — TCA, many SSRI, antipsychotic (haloperidol, risperidone), opioids (codeine, tramadol activation); polymorphism — poor → ultra-rapid metabolizers; - **CYP3A4**: most drugs metabolized; many psychotropic; - **CYP1A2**: clozapine, olanzapine, fluvoxamine, caffeine; induced by smoking — clozapine levels drop when smoking, increase if quit; - **CYP2C19**: citalopram, escitalopram, sertraline, diazepam, omeprazole; - **CYP2B6**: bupropion, methadone; (2) **Strong inhibitors** (raise levels of substrates): - **Fluoxetine, paroxetine, bupropion** = strong CYP2D6 inhibitors — can elevate TCAs, antipsychotics; reduce tamoxifen activation (consider in breast cancer); - **Fluvoxamine** = strong CYP1A2 inhibitor — clozapine level increases; CYP2C19 inhibitor; - **Nefazodone** = CYP3A4 inhibitor; - **Grapefruit juice** = CYP3A4 inhibitor; (3) **Inducers** (reduce levels): - **Carbamazepine, phenytoin, phenobarbital, rifampin, St John''s wort, smoking (CYP1A2)** — induce; - Reduce OCP, antidepressants, antipsychotics; (4) **Clinical examples**: - **Fluoxetine + tamoxifen** → reduced endoxifen → reduced efficacy in breast cancer (avoid); - **Clozapine + smoking change** → unpredictable levels; - **Methadone + induce** → withdrawal; - **SSRI + tramadol** → serotonin syndrome + reduced analgesia (tramadol activation via 2D6); - **Carbamazepine OCP** → contraception failure; (5) **Pharmacogenomics**: - **CYP2D6 + CYP2C19** genotyping commercially available; - Useful in TRD, polypharmacy, treatment-resistant; - **GeneSight, others**; - Evidence mixed for clinical outcomes; (6) **Drug-drug interaction databases**: Liverpool HIV interactions; Lexi-Interact; Epocrates

---

P450 in psychiatry: 2D6 (many psychotropic, fluoxetine/paroxetine/bupropion inhibit), 3A4 (most drugs), 1A2 (clozapine, smoking induces), 2C19 (citalopram). Inducers (carbamazepine, smoking) → reduce levels. Pharmacogenomics emerging. Drug interactions critical.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'psychiatry'
  and scenario = 'Resident ถามเรื่อง CYP450 + psychiatric pharmacology + drug interactions';

update public.mcq_questions
set choices = '[{"label":"A","text":"No genetic basis"},{"label":"B","text":"Genetics of Psychiatric Disorders"},{"label":"C","text":"Single gene model"},{"label":"D","text":"Random"},{"label":"E","text":"Surgery"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Genetics of Psychiatric Disorders: (1) **Heritability** (twin studies): - Schizophrenia ~ 80%; - Bipolar ~ 70-80%; - Autism ~ 80%; - ADHD ~ 75%; - MDD ~ 35-40%; - Anxiety ~ 30-40%; - Substance use ~ 50%; - Pierce psychiatric disorders have substantial heritability; (2) **Polygenic architecture**: - Most psychiatric disorders polygenic — many genes of small effect; - No single ''depression gene'' or ''schizophrenia gene''; - Polygenic Risk Scores (PRS) — research utility; clinical utility limited; (3) **Rare highly penetrant variants**: - **22q11.2 deletion** (DiGeorge) — schizophrenia + intellectual disability + cardiac + immune; - **Fragile X** (FMR1 CGG repeats) — ID + autism features; - **CNVs** (copy number variants) — schizophrenia + autism + ID; (4) **Single gene Mendelian — neuropsychiatric**: - **Huntington''s** (HTT CAG repeats, AD); - **Wilson''s** (ATP7B, AR — copper, psychiatric sx); - **Inborn errors metabolism**; - **Alpha-synuclein, parkin, LRRK2** (familial PD); - **PSEN1/2, APP** (familial AD); - **C9orf72, GRN, MAPT** (FTD); (5) **Gene-environment interaction**: - Diathesis-stress model; - Examples: 5-HTTLPR + life stress + depression (Caspi — controversial); MAOA + childhood maltreatment + antisocial; - Epigenetic mechanisms — methylation, histone modification; childhood trauma → lasting epigenetic changes; (6) **GWAS findings**: - Schizophrenia >> 100 loci identified — including MHC region; - Cross-disorder shared genetics (schizophrenia + BP + depression overlap substantial); (7) **Clinical genetics**: - **Family history** essential; - **Genetic counseling** for: hereditary disorders (HD, AD familial), 22q11, family planning, pregnancy decisions; - Pharmacogenomic testing — CYP variants; - Whole exome sequencing — research + selected clinical (ID, autism + features); (8) **Modern**: precision psychiatry — individualized treatment based on genetics + biomarkers + clinical features — aspiration, evolving

---

Psychiatric genetics: high heritability (schizophrenia 80%, bipolar 70-80%). Polygenic — many genes small effect. Rare highly penetrant variants (22q11, Fragile X, CNVs). GxE + epigenetics (trauma). GWAS findings. Cross-disorder shared genetics. Pharmacogenomics + precision psychiatry emerging.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'psychiatry'
  and scenario = 'Resident ถามเรื่อง genetics of psychiatric disorders';

update public.mcq_questions
set choices = '[{"label":"A","text":"No plasticity adults"},{"label":"B","text":"Neuroplasticity + BDNF + Psychiatric Treatment"},{"label":"C","text":"Single mechanism"},{"label":"D","text":"Random"},{"label":"E","text":"Surgery"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Neuroplasticity + BDNF + Psychiatric Treatment: (1) **BDNF (Brain-Derived Neurotrophic Factor)**: - Promotes neuronal survival, synaptogenesis, dendritic growth, neurogenesis (limited adult — hippocampus, olfactory); - Hippocampal levels reduced in depression; - Stress + corticosteroids reduce BDNF; - Antidepressants (chronic) increase BDNF — partial mechanism + correlates with response; (2) **Ketamine + rapid antidepressants**: - NMDA receptor antagonism → glutamate burst → BDNF release → rapid synaptogenesis; - Hours-to-days antidepressant effect (vs weeks for SSRI); - Sustained effect 1-2 weeks; - Mechanism = rapid synaptic remodeling; (3) **Psychedelics + plasticity**: - Psilocybin, DMT, LSD = 5-HT2A agonists → rapid + lasting synaptogenesis + dendritic growth; - ''Psychoplastogens'' — Olson; - Single or few doses sustained effect (months); - Combine with psychotherapy critical for clinical benefit; (4) **ECT**: - Mechanism not fully understood; - Increases BDNF + neurogenesis; - Most effective antidepressant; (5) **Exercise**: - Aerobic exercise increases BDNF; - Antidepressant effect; (6) **Stress + depression**: - Chronic stress → hippocampal atrophy + dendritic retraction; - Reversible with treatment + recovery; (7) **Cognitive behavioral therapy**: - Functional brain changes — neuroplasticity in service of new learning; - Equivalent to medication for many disorders; (8) **CNS regeneration limited** vs PNS — most therapeutic neuroplasticity = synaptic remodeling not neurogenesis; (9) **Critical periods**: - Childhood + adolescence — neurodevelopment vulnerable; - Adolescent mental health crucial timing; (10) **Implications**: - Combine medication + psychotherapy + exercise + lifestyle for synergistic plasticity; - Sustained recovery requires sustained engagement with healthy patterns

---

Neuroplasticity + BDNF: depression ↓ BDNF; antidepressants ↑ BDNF (slow). Ketamine + psychedelics = rapid synaptogenesis (''psychoplastogens''). ECT + exercise + CBT also neuroplasticity. Adolescent critical period. Combine modalities for synergistic plasticity.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'psychiatry'
  and scenario = 'Resident ถามเรื่อง neuroplasticity + BDNF + relevance to psychiatric treatment';

update public.mcq_questions
set choices = '[{"label":"A","text":"No relevance"},{"label":"B","text":"Sleep Architecture + Psychiatric Disorders + Medication Effects"},{"label":"C","text":"Single stage"},{"label":"D","text":"Random"},{"label":"E","text":"Surgery"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Sleep Architecture + Psychiatric Disorders + Medication Effects: (1) **Normal sleep stages**: - **NREM 1** (light, sleep onset, 5%); - **NREM 2** (50%, K-complexes, sleep spindles, memory consolidation); - **NREM 3** (slow-wave sleep, 20%, growth hormone, restorative); - **REM** (25%, dreaming, atonia, memory consolidation emotional); - Cycles ~ 90 min; REM increases through night; (2) **Depression sleep**: - Decreased SWS (slow-wave sleep); - Decreased REM latency (REM onset earlier in night); - Increased REM density + duration; - REM rebound after SSRI discontinuation; - Early morning awakening (classic); - **REM suppression** — antidepressants suppress REM (SSRI, SNRI, TCA, MAOI) — therapeutic mechanism theory; (3) **Sleep deprivation** — paradoxical antidepressant effect (mostly relapses with sleep); REM deprivation specifically; (4) **Bipolar**: - Mania — decreased sleep need (not insomnia distress); - Depression — variable; - Sleep deprivation can trigger mania (sleep regulation IPSRT — Interpersonal + Social Rhythm Therapy); (5) **PTSD**: - Nightmares (REM-related); - Increased REM activity; - Prazosin reduces nightmares (alpha-1 antagonist, reduces noradrenergic in REM); (6) **Antipsychotic effects**: - Atypicals (quetiapine, olanzapine) increase SWS — sedation + sleep architecture changes; - Trazodone increases SWS; (7) **Substances**: - Alcohol — reduces REM + SWS rebound on withdrawal → vivid dreams + nightmares; - Cannabis withdrawal — vivid dreams (REM rebound); - Benzodiazepines — reduce SWS + REM (lighter sleep quality despite duration); - SSRI — reduce REM + may suppress dreams; (8) **Aging**: less SWS, more fragmentation, earlier sleep schedule; (9) **Sleep + cognition**: SWS critical for declarative memory consolidation; REM for emotional + procedural memory; sleep deprivation impairs both; (10) **Clinical implications**: assess sleep in all psychiatric presentations; primary sleep disorders mimic + worsen psychiatric

---

Sleep architecture: NREM stages + REM. Depression — decreased REM latency, ↓ SWS, REM rebound. Antidepressants suppress REM. Mania — decreased sleep need. PTSD — nightmares + prazosin. Alcohol + cannabis withdrawal — REM rebound. Aging — less SWS. Assess sleep in all psychiatric.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'psychiatry'
  and scenario = 'Resident ถามเรื่อง sleep architecture + medication effects + psychiatric';

update public.mcq_questions
set choices = '[{"label":"A","text":"All antipsychotics same"},{"label":"B","text":"Antipsychotic Classes + Mechanisms + Side Effects"},{"label":"C","text":"Only typical effective"},{"label":"D","text":"Random"},{"label":"E","text":"Surgery"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Antipsychotic Classes + Mechanisms + Side Effects: (1) **Typical (1st gen)**: - **High potency**: haloperidol, fluphenazine — strong D2 blockade; high EPS; less metabolic; less anticholinergic; less sedation; - **Low potency**: chlorpromazine, thioridazine — weaker D2; more anticholinergic, antihistaminic, alpha-1 — sedation + hypotension + weight gain; cardiac (QTc thioridazine); (2) **Atypical (2nd gen)**: D2 + 5-HT2A antagonism — lower EPS, may improve negative sx: - **Clozapine** — gold standard TRS, only with mortality + suicide reduction; mandatory monitoring (agranulocytosis); metabolic worst; sedation; sialorrhea; myocarditis; seizure; constipation/ileus; - **Olanzapine** — effective; severe metabolic (weight gain, lipids, glucose); sedation; IM short-acting + LAI; - **Risperidone** — effective; higher EPS than other atypicals at higher dose (more typical-like); hyperprolactinemia (highest); LAI; - **Paliperidone** — risperidone metabolite; primarily renal; LAI (Sustenna monthly, Trinza q3mo, Hafyera q6mo); only FDA approved for schizoaffective; - **Quetiapine** — sedating; less EPS + prolactin; metabolic moderate; FDA approved BP depression; - **Ziprasidone** — QTc warning (take with food for absorption); less metabolic; activating; - **Lurasidone** — less metabolic; FDA approved BP depression + schizophrenia; take with food (350 cal); - **Asenapine** — sublingual + transdermal; (3) **3rd generation — partial D2 agonists**: - **Aripiprazole** — partial agonist; less EPS + less prolactin (often lowers); akathisia common; minimal metabolic; LAI options; - **Brexpiprazole** — similar; FDA approved AD agitation 2023; - **Cariprazine** — partial D2 + D3; FDA approved mixed features + BP; (4) **LAI options**: - Risperidone, paliperidone, aripiprazole, olanzapine, haloperidol, fluphenazine; - Improve adherence; reduce relapse; consider early in schizophrenia; (5) **Side effect monitoring**: weight, lipids, glucose, BP, EPS, prolactin, QTc, cardiac, hematologic (clozapine); (6) **Black box**: increased mortality elderly with dementia + behavioral disturbance; (7) **Choice considerations**: prior response, comorbidity (metabolic, cardiac, cognitive), adherence, formulation needed, cost, side effect profile, patient preference

---

Antipsychotic classes: typical (high D2), atypical (D2 + 5-HT2A — less EPS), 3rd gen (partial D2 agonist — least metabolic). Clozapine TRS + mortality + suicide reduction. LAI for adherence. Metabolic monitoring + EPS + prolactin + QTc. Black box elderly with dementia.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'psychiatry'
  and scenario = 'Resident ถามเรื่อง antipsychotic classes + mechanisms + side effect profiles';

update public.mcq_questions
set choices = '[{"label":"A","text":"Only lithium effective"},{"label":"B","text":"Mood Stabilizers — Mechanisms + Clinical Use"},{"label":"C","text":"All same"},{"label":"D","text":"Random"},{"label":"E","text":"Surgery"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Mood Stabilizers — Mechanisms + Clinical Use: (1) **Lithium**: - Gold standard mood stabilizer; - Unique mortality + suicide reduction (BP + unipolar depression); - Mechanism complex — GSK-3 inhibition, IP3/PKC, neurotrophic (BDNF), neuroprotective; - Narrow therapeutic index — 0.6-1.2 mEq/L; monitor levels, renal, thyroid, parathyroid; - Side effects: tremor, polyuria/polydipsia (nephrogenic DI), hypothyroidism, hyperparathyroidism, cognitive blunting, weight gain, acne, EKG (T-wave flattening), Ebstein anomaly (small absolute risk pregnancy); - Drug interactions: NSAID, ACE-I, ARB, thiazide (↑ level — toxicity); - Toxicity emergency — hemodialysis if level > 4 or severe sx; - Acute mania, maintenance BP, BP depression (adjunct), unipolar augmentation, suicide reduction; (2) **Valproate (Divalproex)**: - GABA + sodium channel + Ca channel; - Acute mania (rapid loading); mixed features; - Side effects: weight gain, hair loss, liver, pancreatitis, thrombocytopenia, hyperammonemia, sedation, tremor; - **AVOID pregnancy** — NTD risk 1-2% + cognitive deficits in exposed (Major Congenital Malformations + IQ reduction — FDA black box); polycystic ovary syndrome; - Drug interactions: lamotrigine (doubles level — slow titration), warfarin; (3) **Lamotrigine**: - Voltage-gated sodium channel + glutamate; - BP depression + maintenance; - NOT effective acute mania; - **Stevens-Johnson syndrome / TEN** — slow titration essential (25 mg weeks); valproate doubles level (start lower); - Generally well-tolerated; (4) **Carbamazepine, Oxcarbazepine**: - Sodium channel; - Acute mania; - SJS/TEN especially HLA-B*1502 (Asian populations) — genetic testing; - Hyponatremia (oxcarbazepine especially); - Aplastic anemia, agranulocytosis (CBZ); - Strong CYP3A4 inducer — multiple drug interactions; - Acute mania; (5) **Atypical antipsychotics for BP**: olanzapine, risperidone, quetiapine (depression + mania), aripiprazole, asenapine, cariprazine, lurasidone (depression) — often used as mood stabilizers; (6) **Selection**: - Acute mania — lithium, valproate, atypical antipsychotic; - BP depression — lamotrigine, quetiapine, lurasidone, cariprazine, lithium adjunct; - Maintenance — lithium gold standard, lamotrigine (depression-prone), atypical LAI; - Mixed features — atypical (lurasidone, cariprazine); - Rapid cycling — avoid antidepressants, lithium less effective; valproate, lamotrigine, atypical

---

Mood stabilizers: lithium (gold standard, suicide reduction, narrow TI), valproate (acute mania, AVOID pregnancy NTD), lamotrigine (depression, SJS slow titration), carbamazepine (HLA-B*1502 SJS, CYP3A4 inducer). Atypicals for BP. Selection by phase + features.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'psychiatry'
  and scenario = 'Resident ถามเรื่อง mood stabilizers + mechanisms + clinical use';

update public.mcq_questions
set choices = '[{"label":"A","text":"Routine MRI all psychiatric"},{"label":"B","text":"Neuroimaging in Psychiatry"},{"label":"C","text":"No imaging useful"},{"label":"D","text":"Random"},{"label":"E","text":"Surgery"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Neuroimaging in Psychiatry: (1) **Clinical indications for imaging** in psychiatric presentation: - **Atypical features**: late onset, sudden onset, focal neurologic signs, altered mental status, head trauma, suspected stroke, suspected mass, suspected NPH, suspected dementia (workup), suspected encephalitis; - **First episode psychosis** — many guidelines recommend MRI to rule out organic; (2) **Structural imaging**: - **CT** — acute, blood, mass, hydrocephalus; - **MRI** — preferred; better tissue contrast, posterior fossa, white matter; (3) **Functional imaging**: - **fMRI** — research; - **PET** — clinical: amyloid PET (AD), tau PET, FDG-PET (FTD, AD differentiation), DAT scan (DLB, parkinsonism), 18F-DOPA, oncology; research: receptor occupancy, neurotransmitter; - **SPECT** — DAT scan; perfusion (limited clinical use); - **MEG, EEG** — seizure, sleep, functional; (4) **Specific applications**: - **Dementia workup**: MRI structural (atrophy, hippocampal volume, ischemic, NPH), FDG-PET (AD posterior, FTD frontal/temporal, DLB), amyloid PET (early AD), tau PET (research evolving), DAT scan (DLB vs AD); - **Pre-ECT**: not routine but if clinical concern; - **Stroke psychiatric sx**: CT/MRI; - **Anti-NMDA encephalitis**: MRI (often normal or mild), CSF, antibodies, FDG-PET sometimes; - **Suspected mass**: MRI with contrast; (5) **AD biomarkers** integrated diagnosis (NIA-AA): - Amyloid (CSF Aβ, amyloid PET, blood emerging); - Tau (CSF p-tau, tau PET, blood emerging); - Neurodegeneration (MRI atrophy, FDG-PET, blood NfL); (6) **Research applications**: - Polygenic + imaging genetics; - Treatment response prediction; - Network analyses; - Connectivity (default mode network, salience network); (7) **Limitations**: - **No imaging diagnostic for major psychiatric disorders** (depression, schizophrenia, BP) — research findings averaged across groups, not individual diagnostic; - Caution with claims of ''brain scan diagnosis''; (8) **Modern**: blood-based biomarkers emerging (plasma p-tau217, NfL, Aβ42/40) — may revolutionize AD diagnosis without need for PET/LP

---

Neuroimaging in psychiatry: clinical indications (atypical, focal neuro, FEP some, dementia workup). Structural MRI > CT. Functional: amyloid + tau PET (AD), DAT scan (DLB). NO imaging diagnostic for major psychiatric. Blood-based biomarkers emerging (p-tau217, NfL).'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'psychiatry'
  and scenario = 'Resident ถามเรื่อง neuroimaging in psychiatry + clinical use';

commit;
