-- ===============================================================
-- UPDATE chunk 7/8: anesthesiology (25 questions)
-- ===============================================================

begin;

update public.mcq_questions
set choices = '[{"label":"A","text":"Skip safety standards"},{"label":"B","text":"Non-Operating Room Anesthesia (NORA)"},{"label":"C","text":"No monitoring needed"},{"label":"D","text":"Different rules"},{"label":"E","text":"Refuse NORA"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Non-Operating Room Anesthesia (NORA): (1) Locations: - GI endoscopy (colonoscopy, ERCP, EUS); - Interventional radiology (embolization, biopsy, drain, EVAR); - Cardiac cath/EP lab (TAVR, ablation, ICD, PCI); - Radiation oncology (pediatric daily); - MRI/CT; - Bronchoscopy; - ECT (psychiatry); - Dental; - Office-based; (2) Challenges: - Unfamiliar environment; - Limited assistance; - Patient access limited (cath lab, MRI); - Equipment different/less; - Radiation exposure; - Magnetic field (MRI); - Distance from main OR/resources; (3) Anesthesia options: - MAC (moderate-deep sedation); - GA; - Regional + sedation; - Local + monitor; (4) Equipment requirements: - Same standards as OR (ASA monitoring); - Capnography mandatory moderate/deep; - Suction, O2, airway, drugs, defibrillator; - Reliable communication; - Emergency support plan; (5) MRI-specific: - MR-conditional equipment (ferromagnetic safety); - Long monitoring cables; - Pulse oximetry, capnography, ECG MR-safe; - Anesthesia machine MR-compatible or outside scan room; - Earplugs/protection (noise); - Patient screening (pacemaker, implants); - Heat concern (RF energy); (6) Radiation: - Lead shield + apron; - Distance + time minimization; - Pregnancy screening staff; - Eye protection; (7) Pediatric NORA — high volume (radiation therapy, MRI); requires expertise; (8) Sedation drugs: - Propofol, ketamine, dexmedetomidine, fentanyl, midazolam; - Risks: airway, hypotension, paradoxical reaction; (9) Pre-procedure assessment: - Standard pre-anesthesia evaluation; - NPO; - Difficult airway screening; - Comorbidities; (10) Safety: - Standard apply outside OR; - ASA Statement NORA

---

NORA: same ASA standards as OR, capnography mandatory moderate/deep sedation, MR-conditional equipment, radiation protection, pediatric NORA expertise. Reliable communication + emergency plan. ASA NORA Statement.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'anesthesiology'
  and scenario = 'EMS/Management: anesthesia for procedures outside OR (NORA — Non-Operating Room Anesthesia)';

update public.mcq_questions
set choices = '[{"label":"A","text":"Routine doses all drugs"},{"label":"B","text":"Cirrhosis perioperative anesthesia"},{"label":"C","text":"Morphine PCA only"},{"label":"D","text":"Mass IV crystalloid"},{"label":"E","text":"Skip TEG"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Cirrhosis perioperative anesthesia: (1) Severity assessment — Child-Pugh (A: 5-6, B: 7-9, C: 10-15), MELD (predicts mortality, > 15 high risk); (2) Pre-op optimization: - Treat ascites (diuretic, paracentesis large volume); - Correct coagulopathy (vitamin K, FFP, platelets if active bleeding or pre-procedure); - Optimize albumin + nutrition; - Hepatic encephalopathy (lactulose, rifaximin); - Hyponatremia correction slowly; - Renal function — hepatorenal syndrome screening; (3) Anesthetic considerations: - Altered drug metabolism — many drugs (benzodiazepines, opioids, propofol) accumulate; - Hypoalbuminemia → increased free drug; - Cisatracurium preferred NMB (Hofmann elimination); - Remifentanil preferred opioid (esterase metabolism); - Propofol OK (lower doses, slower infusion); - Avoid morphine (active metabolites); use fentanyl/hydromorphone reduced doses; - Avoid halothane (now rarely used); sevoflurane OK; (4) Hemodynamic: - Hyperdynamic circulation (low SVR, high CO); - Sensitive to fluid shifts; - Vasoplegia common; - Hemorrhagic risk + variceal bleeding; (5) Coagulation: - Rebalanced coagulation (both pro + anti-coagulant decreased); TEG more useful than INR; - Avoid unnecessary FFP (worsens portal pressure); (6) Special considerations TIPS, liver transplant, variceal bleeding; (7) Neuraxial considerations — coagulopathy concern; (8) Post-op: - Hepatic decompensation risk; - HRS; - Infection (SBP); - Coagulopathy; - Encephalopathy; (9) Multidisciplinary: hepatology + anesthesia + surgery + transplant team if applicable

---

Cirrhosis: Child-Pugh + MELD severity. Treat coagulopathy, ascites, encephalopathy. Cisatracurium, remifentanil, reduced doses. Hyperdynamic + vasoplegia. TEG > INR. Multidisciplinary.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'anesthesiology'
  and scenario = 'ผู้ป่วยชาย 50 ปี — elective hepatic resection
Lab: AST 80, ALT 60, ALK 120, bili 1.8, INR 1.3, plt 110k, albumin 3.2
Child-Pugh B, MELD 12, mild ascites';

update public.mcq_questions
set choices = '[{"label":"A","text":"Continue all unchanged"},{"label":"B","text":"Polypharmacy + elderly perioperative"},{"label":"C","text":"Stop everything"},{"label":"D","text":"Skip review"},{"label":"E","text":"Ignore interactions"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Polypharmacy + elderly perioperative: (1) Pre-op medication review (Beers Criteria, STOPP/START): - Identify potentially inappropriate medications (PIMs); - Drug interactions; - Cumulative anticholinergic burden; - Polypharmacy itself = risk factor adverse outcomes; (2) Common categories to review/adjust: - Anticoagulants — hold appropriate intervals (DOAC, warfarin); - Antiplatelets — selective hold; - Antihypertensives — hold ACE-I/ARB day surgery (hypotension); continue beta-blocker; - Diuretics — hold morning, resume; - Hypoglycemics — adjust insulin, hold metformin/SGLT2i; - Anticonvulsants — continue; - Psychiatric — continue most; SSRI (bleeding); MAOI (drug interactions); - Long-acting opioid — continue (avoid withdrawal); - Steroid — continue + stress dose; - Statin — continue (cardioprotective); - Antiarrhythmic — continue (amiodarone — pulmonary, hepatic, thyroid considerations); (3) Specific concerns: - Amiodarone — pulmonary fibrosis risk + intra-op bradycardia + corneal deposits + thyroid; - Furosemide — hypokalemia, hypomagnesemia, hypovolemia; replace K + Mg; - ACE-I — refractory intra-op hypotension; vasopressin may help; (4) Drug-drug interactions: - QTc prolongation cumulative; - Serotonin syndrome (multiple serotonergic); - Sedative additive; (5) Anticholinergic burden — falls, delirium, cognitive; (6) Renal/hepatic adjustment; (7) Cumulative bleeding risk multiple agents; (8) Withdrawal considerations — opioid, benzo, alcohol, nicotine, baclofen; (9) Multidisciplinary: - Pharmacist consultation; - Geriatric medicine; - Specialty consultations; (10) De-prescribing as appropriate long-term; (11) Modern: pre-op clinic medication reconciliation + optimization

---

Polypharmacy elderly: Beers Criteria + STOPP/START review, individualized hold/continue, address PIMs, anticholinergic burden, drug interactions, withdrawal considerations. Pharmacist + geriatric consult. Pre-op clinic.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'anesthesiology'
  and scenario = 'ผู้ป่วยหญิง 75 ปี — emergent surgery for SBO
Polypharmacy: 12 medications + DOAC + furosemide + amiodarone + warfarin + ACE-I + ASA
History: AFib, HFpEF, CKD, T2DM';

update public.mcq_questions
set choices = '[{"label":"A","text":"Refuse care"},{"label":"B","text":"Infective endocarditis + IVDU"},{"label":"C","text":"Single discipline"},{"label":"D","text":"Stigmatize patient"},{"label":"E","text":"Skip TEE"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Infective endocarditis + IVDU — cardiac anesthesia: (1) Multidisciplinary endocarditis team — cardiology + cardiac surgery + infectious disease + anesthesia + addiction medicine; (2) Pre-op optimization: - Antibiotics — appropriate based on organisms (MSSA, MRSA, Strep, enterococci, fungi); typically 4-6 weeks; surgery often before completion if indication; - Source control; - Echo (TTE + TEE) to characterize valve + vegetations + complications (abscess, fistula); - Cardiac assessment (heart failure, arrhythmia); - Embolic complications screen (CNS, splenic, renal); - Renal function (drug-induced, AKI from sepsis); - Substance use evaluation; (3) Surgical indications: - Heart failure refractory medical Mx; - Uncontrolled infection (large vegetation, abscess, embolic events); - Prosthetic valve endocarditis; - Specific organisms (fungal, MDR); (4) Anesthesia considerations: - Multivalvular disease — complex hemodynamics; - Anti-emboli precautions; - Possibly endocarditis prophylaxis sub-optimal; - Hemodynamic instability risk; - Cerebral vegetation/embolic stroke risk; - TEE crucial; - CPB considerations; (5) IVDU-specific: - Tolerance opioid + benzodiazepine — increased anesthetic + analgesic doses; - Risk withdrawal (heroin, methadone); coordinate with addiction medicine; - Blood-borne illness (HIV, hepatitis B + C) — universal precautions, antiretrovirals; - Vascular access difficult (sclerosed veins); central access; - Possible recurrence — discuss with patient + family; (6) Addiction medicine: - Methadone or buprenorphine bridge if appropriate; - Treatment plan post-op (residential, outpatient); - Naloxone education; (7) Stigma awareness — patient deserves equitable care; (8) Multidisciplinary post-op: - ICU; - Anticoagulation if mechanical valve; - Antibiotic continuation; - Addiction treatment; - Mental health; (9) Modern: combined cardiothoracic + addiction programs improve outcomes; ethical considerations regarding repeat surgery in active IVDU

---

Endocarditis + IVDU: multidisciplinary endocarditis team, antibiotics + source control + surgical indications, TEE essential, IVDU considerations (tolerance, withdrawal, vascular access), addiction medicine coordination, stigma-free care.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'anesthesiology'
  and scenario = 'ผู้ป่วยชาย 28 ปี healthy, IV drug user, presenting with infective endocarditis aortic + mitral valve
Vegetations large + new AR moderate-severe
Hemodynamically stable but planned valve surgery';

update public.mcq_questions
set choices = '[{"label":"A","text":"Crystalloid only"},{"label":"B","text":"Severe PPH + coagulopathy"},{"label":"C","text":"Single uterotonic"},{"label":"D","text":"Avoid TXA"},{"label":"E","text":"Stop transfusion"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Severe PPH + coagulopathy: (1) Activate MTP if not already; (2) Stop bleeding source: - Uterotonics maximal (oxytocin + methergine + carboprost + misoprostol); - Surgical interventions: balloon (Bakri), B-Lynch, uterine artery ligation, hysterectomy; - IR embolization if available + stable; (3) Balanced transfusion 1:1:1 PRBC:FFP:Plt; (4) Fibrinogen replacement aggressive: - Target > 2 g/L (PPH may need > 2.5); - Cryoprecipitate 10 units OR fibrinogen concentrate 4 g; - Critical for clot strength; (5) TXA 1g IV if not given (WOMAN trial — within 3h reduces death); (6) Calcium replacement (citrate); (7) Warm fluids + products + patient; (8) Avoid acidosis + hypothermia (lethal triad); (9) Monitoring: - Arterial line; - Continuous Hb (HemoCue); - TEG/ROTEM if available; - Lactate; - Urine output; (10) Anesthesia: - GA if instability requires; - Ketamine + opioid CV stable; - Vasopressors (norepinephrine first-line); - Inotropes if cardiogenic; (11) Cell salvage acceptable in OB now (post-2007 confirmation); (12) REBOA (Resuscitative Endovascular Balloon Occlusion of Aorta) — emerging for refractory; (13) Post-op: - ICU; - Continued bleeding monitoring; - Sheehan syndrome screening; - DIC; - AKI; - ARDS; - Renal replacement if needed; - Psychological support (PTSD, postpartum depression); (14) Multidisciplinary: OB + anesthesia + IR + ICU + hematology + blood bank

---

Severe PPH + coagulopathy: MTP 1:1:1, fibrinogen target > 2 (cryo/concentrate), TXA, Ca, warm, surgical control. TEG-guided. Norepi. Cell saver OB OK. REBOA emerging. ICU. Multidisciplinary.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'anesthesiology'
  and scenario = 'ผู้ป่วยหญิง 30 ปี G3P2 GA 36 wk — major obstetric hemorrhage after vaginal delivery 2L+ blood loss
Uterotonics escalated
Now shock with INR 1.8, fibrinogen 1.0 g/L, plt 80k';

update public.mcq_questions
set choices = '[{"label":"A","text":"Propofol bolus + hyperventilate"},{"label":"B","text":"Congenital heart disease neonatal anesthesia (Tet)"},{"label":"C","text":"Decrease SVR"},{"label":"D","text":"Allow dehydration"},{"label":"E","text":"Vasodilator first"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Congenital heart disease neonatal anesthesia (Tet): (1) Tetralogy of Fallot — VSD + RVOT obstruction + overriding aorta + RV hypertrophy; cyanosis from R-to-L shunt across VSD; (2) Tet spells (hypercyanotic episodes): - Triggered by — crying, dehydration, fever, induction; - Treatment: knee-chest position (increase SVR + reduce R-to-L shunt); 100% O2; morphine (sedation + reduces sympathetic + reduces infundibular spasm); phenylephrine (increases SVR); fluid bolus; propranolol (reduces infundibular spasm + tachycardia); bicarbonate if acidotic; ECMO if refractory; (3) Anesthetic considerations: - Avoid hypovolemia + tachycardia + decreased SVR — all worsen R-to-L shunt; - Maintain SVR (phenylephrine); - Maintain preload (fluid); - Avoid PVR increases (hypoxia, hypercapnia, acidosis, cold) — worsen R-to-L; - Adequate sedation pre-induction (cry → tet spell); - Smooth induction (ketamine preferred — maintains SVR + HR; etomidate alternative); avoid propofol bolus + high volatile (vasodilation); - Adequate depth before stimulation; - Antifibrinolytic for cardiac surgery; (4) Surgical options: - Modified Blalock-Taussig shunt (subclavian to PA) — palliation; - Complete repair (VSD closure + RVOT augmentation) — definitive; (5) Pre-op: - Echo (anatomy); - Hemoglobin (polycythemia from chronic hypoxia — phlebotomy if Hct > 65); - Bleeding considerations (coagulopathy from polycythemia); - Family preparation; (6) Anti-infective endocarditis prophylaxis; (7) Specific drug choices: - Ketamine 1-2 mg/kg (maintains SVR + HR); - Phenylephrine bolus 1-5 mcg/kg for SVR; - Fentanyl 5-10 mcg/kg; - Rocuronium; (8) Monitoring: - Arterial line; - SpO2 + EtCO2; - Cerebral oximetry useful; - TEE intraop; (9) Multidisciplinary pediatric cardiac team

---

Tet: maintain SVR + preload + adequate depth, avoid PVR increases. Tet spell: knee-chest + O2 + morphine + phenylephrine + propranolol. Ketamine induction. Modified BT shunt vs complete repair.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'anesthesiology'
  and scenario = 'ผู้ป่วยทารกแรกเกิด 36 wk GA 2.4 kg — congenital heart disease (tetralogy of Fallot) requires palliative shunt
Not ductal-dependent but cyanosis worsening, SpO2 78% on RA';

update public.mcq_questions
set choices = '[{"label":"A","text":"No antibiotics"},{"label":"B","text":"Ventilator-Associated Pneumonia (VAP) / Hospital-Acquired Pneumonia"},{"label":"C","text":"Continue support"},{"label":"D","text":"Ignore CXR"},{"label":"E","text":"Sedate more"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Ventilator-Associated Pneumonia (VAP) / Hospital-Acquired Pneumonia: (1) Definitions: - VAP: > 48h after intubation; - HAP: > 48h after hospital admission; - Post-extubation can blur with VAP for recently extubated; (2) Diagnosis: - Fever + leukocytosis + purulent secretions + hypoxia + new infiltrate; - Lower sensitivity in critically ill (other infiltrate causes — atelectasis, edema, ARDS, hemorrhage); - Bronchoalveolar lavage (BAL) or non-bronchoscopic mini-BAL; - Quantitative culture + threshold; - Procalcitonin (sensitivity moderate); (3) Empiric antibiotics — IDSA/ATS 2016 guidelines: - Cover S. aureus, Pseudomonas, gram-negative; - Vancomycin or linezolid (MRSA); - Cefepime, pip-tazobactam, or carbapenem (MDR risk); - Aminoglycoside or fluoroquinolone if high MDR risk; - De-escalate per culture (48-72h); - Duration 7 days standard (not 14); (4) Prevention bundle (VAP bundle): - HOB > 30° (semi-recumbent); - Oral care chlorhexidine; - SAT/SBT daily (extubate ASAP); - Stress ulcer prophylaxis; - DVT prophylaxis; - Subglottic suction ETT; - Cuff pressure 20-30; - Minimize sedation; - Hand hygiene; (5) Post-extubation considerations: - Aspiration risk; - Diaphragm dysfunction (ICU-acquired weakness); - Atelectasis; - Multimodal pulmonary toilet; (6) Risk factors VAP: - Prolonged ventilation; - Sedation/paralysis; - Reintubation; - Aspiration; - Supine position; - Comorbid (COPD, ARDS); (7) Outcomes: - Mortality 20-50% VAP; - Increased LOS + cost; (8) Modern: minimizing ventilation + aggressive prevention bundle

---

VAP/HAP: fever + WBC + secretions + infiltrate. Empiric MRSA + Pseudomonas coverage, de-escalate, 7 days. Bundle prevention (HOB, oral care, SAT/SBT, subglottic suction). Modern minimization.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'anesthesiology'
  and scenario = 'ผู้ป่วยหญิง 60 ปี — extubated ICU day 3 after major surgery
Develops fever 38.5°C, hypoxia SpO2 88% on 6L O2, productive cough, rhonchi RML
WBC 16k, CXR new RML infiltrate';

update public.mcq_questions
set choices = '[{"label":"A","text":"Continue surgery routine"},{"label":"B","text":"Perioperative myocardial infarction"},{"label":"C","text":"Ignore troponin"},{"label":"D","text":"Aggressive surgery"},{"label":"E","text":"Refuse cardiology"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Perioperative myocardial infarction: (1) Recognition — anginal symptoms may be masked (sedation, analgesia, post-op confusion); silent MI common (50%); ECG changes + troponin elevation key; (2) Classification: - Type 1 — plaque rupture, thrombosis; - Type 2 — supply-demand mismatch (most common perioperative — anemia, tachycardia, hypotension, hypoxia); (3) Management — depends on type + clinical: - Type 1 (STEMI or NSTEMI with high-risk features): - Cardiology consult urgent; - PCI consideration (timing depends on bleeding risk + surgical wound — often delayed primary PCI 24-72h); - Dual antiplatelet (DAPT) — ASA + clopidogrel — balance bleeding risk surgical; - Anticoagulation careful; - Beta-blocker, statin (continued/added); - Type 2: address underlying — transfuse, control HR/BP, oxygenate, treat pain; medical management; (4) Hemodynamic optimization: - HR < 80 (beta-blocker); - BP control (avoid extremes); - Adequate oxygenation; - Hb > 7-9 (debate); - Adequate analgesia (sympathetic surge); - Hemostatic control; (5) Imaging: - Echo (LV function, regional WMA); - Coronary angiography selective; (6) Cardiology consultation + multidisciplinary; (7) Risk stratification — RCRI, ACS-NSQIP, NSQIP-Gupta MICA, AUB-HAS2; (8) Prevention: - Continuation cardio-protective medications (statin, beta-blocker); - Optimize comorbidities; - Anemia avoidance; - Multimodal pain control; - Identification high-risk patients; (9) Outcomes — perioperative MI associated with high mortality (5-25%); (10) MINS (Myocardial Injury after Non-cardiac Surgery) — troponin elevation without classical MI criteria; increasingly recognized + treated as significant marker risk + therapeutic target

---

Perioperative MI: Type 1 (plaque) vs Type 2 (supply-demand). Cardiology consult, DAPT vs bleeding risk, hemodynamic optimization. MINS recognition. RCRI risk stratification. Multidisciplinary + prevention.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'anesthesiology'
  and scenario = 'ผู้ป่วยชาย 70 ปี post-major surgery day 1 — sudden chest pain + ST elevation V1-V4 + cardiac biomarkers rising
BP stable, no overt heart failure';

update public.mcq_questions
set choices = '[{"label":"A","text":"Wait + observe"},{"label":"B","text":"Post-bariatric surgical complication"},{"label":"C","text":"Discharge home"},{"label":"D","text":"Ignore tachycardia"},{"label":"E","text":"Routine post-op care"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Post-bariatric surgical complication: (1) DDx urgent: - Anastomotic leak (sleeve gastrectomy staple line leak — most feared); - Bleeding; - PE/DVT; - Sepsis (other source); - Cardiogenic; - Adrenal insufficiency; - Bowel obstruction; (2) Sleeve leak features: - Tachycardia + tachypnea early (often before pain or fever); - Fever; - Hypotension; - Leukocytosis; - Tachycardia > 120 = ominous sign; - Pain location variable (LUQ to L shoulder referred); - SOB; - Lactate elevation; (3) Diagnostic: - CT with PO + IV contrast (extravasation); - Upper GI series (water-soluble); - Endoscopy diagnostic + therapeutic; - Exploration if unstable; (4) Management: - NPO + NG decompression (controversial — endoscopic better); - IV fluids + electrolytes; - Broad-spectrum antibiotics (gram-negative + anaerobic); - Drain (percutaneous IR or surgical); - Endoscopic stent (sleeve leaks); - Surgical revision (massive leak, sepsis); - ICU monitoring; (5) PE/DVT — bariatric high risk: - Dyspnea, tachycardia, hypoxia; - CTPA; - Heparin anticoagulation; - Catheter-directed thrombolysis selected; - IVC filter selected; (6) Multidisciplinary: - Bariatric surgery; - General surgery; - IR; - Anesthesia (if OR); - ICU; - Nutrition; (7) Anesthesia for reoperation: - Difficult airway (obesity); - Aspiration risk; - Hemodynamic considerations sepsis; - Multimodal opioid-sparing (avoid NSAID after bariatric); - Regional techniques; (8) Outcomes — early recognition + intervention critical; (9) Modern: increased bariatric surgery, complications, standardized protocols

---

Post-bariatric crisis: think LEAK (tachy first sign), DDx PE/bleeding/sepsis. CT + endoscopy diagnostic. Antibiotics + drainage + stent or surgical. ICU. Multidisciplinary. Avoid NSAID post-bariatric.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'anesthesiology'
  and scenario = 'ผู้ป่วยหญิง 45 ปี post-bariatric sleeve gastrectomy POD 3 ICU — sudden tachycardia + hypotension + AKI + worsening confusion + abdominal pain
WBC 18k, lactate 4, fever 38.6';

update public.mcq_questions
set choices = '[{"label":"A","text":"Succinylcholine RSI"},{"label":"B","text":"Major burn anesthesia"},{"label":"C","text":"Routine doses"},{"label":"D","text":"No fluid"},{"label":"E","text":"Skip airway"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Major burn anesthesia: (1) Initial assessment ABCDE + burn-specific: - Airway — burns to face, neck, oropharynx → progressive edema → early intubation (within 4-6h); inhalational injury; - Breathing — circumferential chest burns may need escharotomy; - Circulation — fluid resuscitation Parkland: 4 mL × kg × %TBSA = 24h fluid; half in first 8h from time of burn; LR most common; modern reduces with adequate UO; - Disability — neuro; - Exposure — keep warm; (2) Inhalational injury: - Singed nasal hairs, soot, hoarse, stridor, carbonaceous sputum; - Carboxyhemoglobin (CO) + cyanide poisoning; treat with 100% O2 + hydroxocobalamin; - Early intubation (airway swelling progresses 24-48h); - Bronchoscopy diagnostic; (3) Fluid resuscitation: - Parkland formula starting point; - Titrate to UO 0.5 mL/kg/hr adult (1 mL/kg pediatric); - Avoid over-resuscitation (fluid creep, ACS, ARDS); - Albumin debated, often added 12-24h; - Vitamin C high-dose protocol (modern); (4) Anesthetic considerations: - Difficult airway anticipated (edema, distortion); - Hypermetabolism + increased MAC after 48h burn; - Hypercatabolism + nutrition needs; - Hemodynamic instability; - Hypothermia risk; - Vascular access difficult; - Renal + hepatic dysfunction; - Coagulopathy + DIC; (5) Drug pharmacology: - Succinylcholine — AVOID > 24h post-burn (hyperkalemic arrest); use rocuronium; - NMB resistance — increased doses non-depolarizing; - Opioid tolerance + increased requirements; - Volatile resistance; (6) Pain management: - Severe burn pain + procedural pain; - Multimodal — opioid PCA, ketamine, gabapentinoid, regional (limited by burn location), dexmedetomidine; - Procedural sedation for dressing changes; (7) Surgery — early excision + grafting; multiple surgeries; (8) Sepsis risk high — burn wound infection; antibiotics judicious; (9) Multidisciplinary burn center; (10) Long-term — physical + psychological rehabilitation

---

Major burn: ABCDE + early airway, Parkland fluid (titrate to UO), inhalational injury (CO + cyanide), AVOID sux > 24h, NMB resistance, opioid tolerance + multimodal, multidisciplinary burn center.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'anesthesiology'
  and scenario = 'ผู้ป่วยชาย 25 ปี — major burn 35% TBSA — emergency escharotomy + ongoing resuscitation
Burns chest, abdomen, both arms
Fluid resuscitation Parkland formula started';

update public.mcq_questions
set choices = '[{"label":"A","text":"Diuretic only"},{"label":"B","text":"Negative Pressure Pulmonary Edema (NPPE) post-laryngospasm/airway obstruction"},{"label":"C","text":"Discharge home"},{"label":"D","text":"Ignore symptoms"},{"label":"E","text":"Continue without intervention"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Negative Pressure Pulmonary Edema (NPPE) post-laryngospasm/airway obstruction: (1) Pathophysiology — forced inspiration against closed glottis → very negative intrapleural pressure → increased hydrostatic gradient → transudation alveoli; (2) Common settings: - Post-laryngospasm (most common in peds T+A); - Biting ETT (Type II NPPE); - Upper airway obstruction; - OSA; - Strangulation; (3) Clinical features: - Onset minutes after obstruction relieved; - Frothy/pink secretions; - Hypoxia; - Dyspnea, tachypnea; - Bilateral crackles; - Normal cardiac function (vs cardiogenic edema); (4) Diagnosis — clinical + CXR (bilateral pulmonary edema); echo to rule out cardiac (LV normal); (5) Management: - 100% O2; - Positive pressure ventilation (CPAP non-invasive or intubate + PEEP); - Furosemide selective (volume status concern in NPPE — usually euvolemic so questionable benefit); - Supportive — usually self-limited 12-24h; - Steroids questionable; (6) ICU/step-down monitoring; (7) Avoid: - Excessive fluid; - Repeat airway obstruction; (8) Prevention: - Laryngospasm prevention/treatment; - Pediatric airway expertise; - Magnesium adjunct; - Multimodal opioid-sparing; (9) Outcome — generally good with prompt recognition; (10) Pediatric considerations: - Smaller airway → more obstruction risk; - Rapid desaturation; - Cardiopulmonary reserve limited; - Family communication; - Observation 24h; (11) Modern: awareness + recognition; bedside ultrasound (B-lines)

---

NPPE: post-laryngospasm/airway obstruction → very negative pressure → pulmonary edema. Frothy/pink secretions, hypoxia. Mx: CPAP/PEEP, O2, supportive, usually 12-24h. Prevent: laryngospasm + multimodal anesthesia.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'anesthesiology'
  and scenario = 'ผู้ป่วยทารก 1 ปี 10 kg — post-op tonsillectomy + adenoidectomy, recovering in PACU
Develops progressive hypoxia, pink frothy secretions from airway, dyspnea
No bleeding evident';

update public.mcq_questions
set choices = '[{"label":"A","text":"Mass NMB doses"},{"label":"B","text":"Myasthenia gravis (MG) anesthesia"},{"label":"C","text":"Use sux high dose"},{"label":"D","text":"Magnesium routine"},{"label":"E","text":"Ignore TOF"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Myasthenia gravis (MG) anesthesia: (1) Pathophysiology — autoantibodies vs nicotinic acetylcholine receptors at NMJ → fluctuating weakness; (2) Pre-op: - Continue anticholinesterase (pyridostigmine) — debate timing of last dose pre-op (some hold to better assess intra-op NMB, others continue); - Assess severity (Osserman classification); - Pulmonary function (FVC) — predictor post-op ventilation; - Consider plasmapheresis or IVIG pre-op for severe; - Steroid stress dose if on chronic; - Multidisciplinary planning (neurology); (3) NMB considerations: - SENSITIVE to non-depolarizing NMB — reduce dose (rocuronium 0.3 mg/kg, 1/4 normal); titrate with TOF; - RESISTANT to succinylcholine (need higher dose 1.5-2 mg/kg); avoid generally; - Sugammadex 2-4 mg/kg for reversal — preferred over neostigmine (which paradoxically may worsen weakness in cholinergic crisis); - Quantitative TOF mandatory; (4) Volatile anesthetic potentiates weakness — be aware; (5) TIVA reasonable alternative — propofol + remifentanil; (6) Regional anesthesia useful adjunct (reduces opioid + NMB needs); (7) Drug interactions: - Avoid aminoglycosides (potentiate weakness); - Avoid certain antiarrhythmics (procainamide, quinidine); - Avoid magnesium (potentiates NMB); - Stress dose steroids if applicable; (8) Post-op concerns: - Myasthenic crisis vs cholinergic crisis (both cause weakness — differentiate); - Edrophonium test (rarely used now); - Plasmapheresis/IVIG; - Mechanical ventilation may be needed; (9) Risk factors post-op ventilation: - Duration MG > 6 years; - FVC < 2.9 L; - High pyridostigmine dose; - COPD; - Major intra-op blood loss; (10) Post-op monitoring ICU; multidisciplinary

---

MG: sensitive non-depolarizing NMB (1/4 dose), sugammadex reversal preferred, quantitative TOF, continue pyridostigmine, avoid aminoglycosides + magnesium. Post-op monitor for crisis. Plasmapheresis/IVIG. Multidisciplinary.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'anesthesiology'
  and scenario = 'ผู้ป่วยหญิง 55 ปี — myasthenia gravis chronic on pyridostigmine — elective thymectomy
Mild generalized weakness, no recent crisis
FVC 75% predicted';

update public.mcq_questions
set choices = '[{"label":"A","text":"Stop levodopa"},{"label":"B","text":"Parkinson disease + anesthesia"},{"label":"C","text":"Use metoclopramide"},{"label":"D","text":"Heavy sedation"},{"label":"E","text":"Ignore DBS"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Parkinson disease + anesthesia: (1) Pre-op: - Continue PD medications maximally (carbidopa-levodopa) — schedule around surgery; - Last dose pre-op timed; - Resume ASAP post-op via NG or PR (if PO not tolerated); - Withdrawal precipitates ''off'' periods + rigidity + risk neuroleptic malignant-like syndrome; - MAO-B inhibitor (selegiline) — typically continue; older non-selective MAOIs require drug interaction caution; (2) Drug interactions/avoidances: - Avoid antiemetics that block D2 (metoclopramide, droperidol, prochlorperazine, haloperidol) — worsen parkinsonism; - Ondansetron acceptable; - Avoid meperidine (serotonin syndrome with MAOI); - Cautious with sympathomimetic + MAOI (hypertensive crisis); - Avoid neuroleptic; (3) DBS considerations: - Verify with neurologist if DBS should remain on or be turned off intra-op; usually turned off if electrocautery (electromagnetic interference + heating); bipolar cautery preferred; - Pacemaker-like considerations; - Programming reassessment post-op; - MRI considerations (some DBS MRI-conditional); (4) Anesthetic technique: - Regional preferred when possible (avoid GA + reduces medication interaction); - GA: propofol OK, sevoflurane OK, fentanyl/remifentanil OK; - Avoid heavy sedation/long-acting opioid if PD with cognitive issues; - Aspiration risk (autonomic dysfunction, swallowing); - Postoperative confusion + delirium risk; (5) Autonomic dysfunction: - Orthostatic hypotension — careful position changes, IV fluid; - Tachycardia/bradycardia; - Constipation; - Urinary retention; (6) Aspiration risk — RSI considerations; (7) Post-op: - Resume PD meds urgently; - Multimodal opioid-sparing analgesia; - Early mobilization; - Aspiration precautions; - Delirium prevention bundle; (8) Multidisciplinary: anesthesia + surgery + neurology; (9) Modern: increasing PD population + DBS implants

---

PD: continue carbidopa-levodopa, AVOID D2 antagonists (metoclopramide, droperidol), DBS off for cautery + bipolar, regional preferred, aspiration + delirium prevention. Resume PD meds urgently post-op. Multidisciplinary.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'anesthesiology'
  and scenario = 'ผู้ป่วยชาย 60 ปี Parkinson disease 10 ปี + DBS implanted — elective surgery
Meds: carbidopa-levodopa, MAO-B inhibitor selegiline
Mild dyskinesia, tremor controlled';

update public.mcq_questions
set choices = '[{"label":"A","text":"Skip neuraxial"},{"label":"B","text":"Twin C-section + obesity + PEC + DM"},{"label":"C","text":"Routine anesthesia"},{"label":"D","text":"Heavy sedation"},{"label":"E","text":"Ignore comorbidities"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Twin C-section + obesity + PEC + DM — high-risk OB anesthesia: (1) Multiple risk factors compound complications; (2) Airway: - Obesity + pregnancy + PEC edema = anticipated difficult; - Pre-O2 thorough (rapid desaturation); - Ramped position; - Video laryngoscopy first; - Difficult airway equipment ready; (3) Anesthetic technique decision: - Neuraxial preferred if no contraindication; - Platelets (PEC) — generally OK > 70-80k; - Spinal vs epidural vs CSE; - Spinal may have profound hypotension in twins (higher uterine pressure, multiple); titrated dose lower; - CSE good balance — flexible duration + reduced dose; (4) Hemodynamic considerations: - Aortocaval compression worse in twins + obesity (left lateral tilt 30°); - Magnesium effects (mild vasodilation, NMB potentiation); - PEC — pulmonary edema risk (cautious fluids); - PEC — avoid HTN surge at intubation if GA; (5) Glucose management — gestational DM: - Insulin sliding scale or infusion; - Target intra-op 100-180; - Avoid hypoglycemia (fetal effects); (6) Multiple babies — neonatal team ready, separate teams ideal; (7) Post-partum considerations: - Atony risk increased (twins, magnesium); aggressive uterotonic; - PEC — continue magnesium 24h, BP control, fluid balance, pulmonary edema risk, eclampsia, AKI; - Thromboembolic prophylaxis (obese + PEC + post-op); - Pain control — multimodal, neuraxial morphine, intrathecal hydromorphone, TAP block, acetaminophen + NSAID (post-delivery OK); (8) ICU/HDU monitoring; (9) Glycemic management transition postpartum; (10) Multidisciplinary: OB + anesthesia + neonatology + MFM + ICU + nursing

---

High-risk OB: difficult airway, neuraxial preferred (platelets > 80k), aortocaval compression worse twins/obesity, magnesium + PEC + DM + atony management. Multidisciplinary. ICU postpartum. Multimodal analgesia.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'anesthesiology'
  and scenario = 'ผู้ป่วยหญิง 28 ปี G2P1 GA 30 wk — twin pregnancy, severe pre-eclampsia
Magnesium running, BP controlled
Weight 95 kg, BMI 38, gestational diabetes
C-section planned';

update public.mcq_questions
set choices = '[{"label":"A","text":"No anesthesia needed"},{"label":"B","text":"ECT anesthesia"},{"label":"C","text":"Heavy sedation continuous"},{"label":"D","text":"Skip NMB"},{"label":"E","text":"Avoid ECT all patients"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** ECT anesthesia: (1) Goals — induce brief generalized seizure (> 25 seconds) under anesthesia with NMB; (2) Pre-procedure: - Medical clearance (cardiac, neuro); - NPO; - IV access; - Standard ASA monitoring + EEG/EMG; - Mouthguard (protect teeth from masseter contraction); (3) Anesthetic technique: - Induction: methohexital (traditional) 1-1.5 mg/kg OR propofol 0.5-1 mg/kg (less seizure duration); etomidate alternative (longer seizure); ketamine 0.5-1 mg/kg (longer + better quality seizures, used for refractory); - Pre-oxygenate; - NMB: succinylcholine 0.5-1 mg/kg (lower dose than RSI — purpose is to attenuate convulsion not full paralysis); rocuronium + sugammadex alternative; - Mask ventilation during seizure (no intubation typically); - Glycopyrrolate pre-treatment (secretions + bradycardia); (4) Cardiovascular: - Initial parasympathetic surge (bradycardia, asystole) — atropine if severe; - Then sympathetic surge (tachycardia, hypertension) — beta-blocker (esmolol or labetalol) or labetalol pre-treatment for cardiac patients; - Monitor closely; (5) Cerebral: - Increased CBF, ICP, IOP, intragastric pressure transient; - Caution in space-occupying lesion, recent stroke, increased ICP; (6) Seizure parameters: - Target 25-60 seconds; - Inadequate: increase stimulus, change anesthetic (ketamine), reduce anesthetic if too deep, hyperventilate, withhold benzo, caffeine 500 mg pre-treatment; (7) Drug considerations: - SSRI continue (no contraindication); - MAOI (caution sympathomimetic interaction); - Lithium — neurotoxicity risk increased — debate continue vs hold; - Benzodiazepines decrease seizure (hold if possible); - Anticonvulsants for non-ECT reasons — debate; (8) Recovery: - Headache, confusion, myalgia common; - Anterograde amnesia (treatment + side effect); - Multimodal post-ECT (acetaminophen, ondansetron); (9) Series of treatments; (10) Multidisciplinary: psychiatry + anesthesia + nursing

---

ECT anesthesia: methohexital/propofol/ketamine + sux + mask ventilation. Glycopyrrolate. Treat parasympathetic then sympathetic surge. Seizure 25-60 sec target. Hold benzo. Multidisciplinary.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'anesthesiology'
  and scenario = 'ผู้ป่วยชาย 70 ปี — anesthesia for ECT (Electroconvulsive Therapy) for severe depression refractory
5 sessions weekly
On citalopram, mirtazapine';

update public.mcq_questions
set choices = '[{"label":"A","text":"Stop ART"},{"label":"B","text":"HIV/AIDS perioperative care"},{"label":"C","text":"Refuse care"},{"label":"D","text":"Treat as terminal"},{"label":"E","text":"Hide diagnosis"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** HIV/AIDS perioperative care: (1) Effective ART has transformed HIV from terminal to chronic — perioperative care similar to non-HIV in well-controlled patients; (2) Pre-op assessment: - CD4 count + viral load; well-controlled (CD4 > 200, undetectable VL) — comparable outcomes; - Comorbidities: cardiovascular (accelerated atherosclerosis), renal (HIV-associated nephropathy + tenofovir), bone (osteoporosis), neuropathy, depression; - Opportunistic infections screen; - Drug interactions; (3) Continue ART perioperatively: - Avoid interruption (resistance, viral rebound); - Coordinate with HIV specialist if NPO prolonged; - Some IV formulations available; (4) Drug interactions: - Protease inhibitors + integrase inhibitors — CYP3A4 effects; - Boosted regimens (ritonavir, cobicistat) — many interactions: midazolam, fentanyl (increased levels), opioids; - Anesthetic implications variable; - Methadone interactions; (5) Universal precautions — standard for all patients (HIV status often unknown); (6) Anesthetic technique — no specific contraindications; regional anesthesia OK; (7) Wound healing — comparable to non-HIV in well-controlled; AIDS (CD4 < 200) may have impaired healing; (8) Infection risk: - Comparable in well-controlled; - Antibiotic prophylaxis standard; - Opportunistic infection screen (CMV, PCP, TB) — selective; (9) Healthcare worker considerations: - Standard precautions; - Post-exposure prophylaxis (PEP) if exposure; - Hepatitis B + C considerations; (10) Stigma awareness — confidentiality + equitable care; (11) Psychiatric — depression, substance use, social factors; (12) Modern: HIV similar to other chronic illness, integrated care

---

HIV well-controlled: similar outcomes, continue ART, drug interactions (PI, integrase, boosted), universal precautions, no special anesthetic contraindications. Confidentiality + equitable care. Modern: chronic illness paradigm.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'anesthesiology'
  and scenario = 'ผู้ป่วยชาย 50 ปี HIV+ controlled on ART, CD4 450, undetectable VL — elective ortho surgery
Meds: dolutegravir/abacavir/lamivudine, statins
No opportunistic infections';

update public.mcq_questions
set choices = '[{"label":"A","text":"Maximum FGF always"},{"label":"B","text":"Sustainable anesthesia practice"},{"label":"C","text":"Use desflurane preferentially"},{"label":"D","text":"Ignore sustainability"},{"label":"E","text":"Single-use only"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Sustainable anesthesia practice: (1) Healthcare contributes 4-5% global greenhouse gases; anesthesia significant contributor; (2) Volatile anesthetics carbon footprint: - Desflurane WORST (2540× CO2 equivalent per kg, 14-year atmospheric lifetime); - Sevoflurane modest (130×, 1.1 year); - Isoflurane intermediate (510×, 3.2 year); - N2O significant (265×, 114 years); also ozone depleter; - 1 hour desflurane = driving 100 km; (3) Reduce volatile impact: - Lower FGF (fresh gas flow) 1-2 L/min — major reduction; - Avoid desflurane when alternatives appropriate; - Avoid N2O when alternatives; - TIVA reduces volatile entirely (but propofol packaging waste); - Charcoal-based volatile capture systems (Centurio, Deltasorb) emerging; (4) Other sustainability: - Reduce single-use plastic; - Reusable when safe + cost-effective; - Pharmaceutical waste reduction (right-sizing doses); - Equipment lifecycle assessment; - LED lighting + HVAC efficiency; - Local + sustainable supply chain; (5) Specific practices: - Open circuit avoid; - LMA reusable available; - Drug syringe sizing (avoid waste); - Procedure-appropriate equipment; (6) Patient + organizational benefits: - Cost savings (lower FGF, less waste); - Improved care continuity (greener operations); - Healthier workforce + community; (7) ASA Committee on Equipment + Facilities + Environmental Stewardship; (8) Code Green NHS UK + similar initiatives; (9) Personal + institutional advocacy: - Education + awareness; - Practice changes; - Procurement decisions; - Research; (10) Modern: regulatory pressure (EU desflurane ban 2026), accreditation incentives, anesthesia leadership in sustainability

---

Sustainability: anesthesia significant GHG. Desflurane WORST, N2O ozone depleter. Reduce FGF, avoid desflurane + N2O, TIVA option, charcoal capture. Plastic reduction. Cost savings + patient benefit. ASA + Code Green advocacy.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'anesthesiology'
  and scenario = 'EMS/Management: anesthesia for environmentally sustainable practice';

update public.mcq_questions
set choices = '[{"label":"A","text":"Avoid leadership"},{"label":"B","text":"Anesthesia leadership + administration"},{"label":"C","text":"Single-handed decisions"},{"label":"D","text":"Ignore finances"},{"label":"E","text":"Skip quality"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Anesthesia leadership + administration: (1) Roles: - Chief of Anesthesia; - Department chair; - Medical director OR/PACU; - Quality + safety officer; - Educational director; - Research director; - Wellness officer; - Equity, Diversity, Inclusion (EDI) officer; (2) Skills required: - Clinical credibility; - Vision + strategic planning; - Communication + interpersonal; - Conflict resolution; - Financial management; - Quality improvement; - Operations + workflow; - Personnel management; - Mentorship; (3) Operating room management: - Block scheduling; - Add-on management; - First case on-time start; - Turnover; - Utilization metrics; - Surgeon + nurse coordination; (4) Financial: - Reimbursement (insurance, value-based); - Coding (CPT, ASA, modifiers, time-based, units); - Productivity (RVU); - Cost management; - Investment decisions (equipment, technology); (5) Quality + safety: - Adverse event review; - Quality improvement projects (PDSA); - Benchmarking (NACOR, MIPS); - Risk management; - Credentialing + privileging; (6) Educational: - Resident program; - CME; - Simulation; - Faculty development; (7) Research: - IRB; - Funding; - Mentorship; - Collaboration; (8) Workforce: - Recruitment; - Retention; - Mentorship; - Wellness; - Burnout; - Succession planning; (9) Patient experience: - Satisfaction surveys; - HCAHPS; - Communication training; (10) Interdisciplinary collaboration: - Surgical specialties; - Nursing; - Hospital administration; - Insurance + payers; - Community; (11) Modern: data-driven, value-based care, telemedicine, AI integration; (12) Professional organizations: - ASA, ASAM, ARAS — engagement + advocacy

---

Anesthesia leadership: vision + strategic + operations + financial + quality + workforce + education + research. Multidisciplinary. Modern: data-driven, value-based. Professional engagement. EDI + wellness focus.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'anesthesiology'
  and scenario = 'EMS/Management: anesthesia leadership + administration';

update public.mcq_questions
set choices = '[{"label":"A","text":"Skip oximetry"},{"label":"B","text":"Pulse oximetry + capnography physics"},{"label":"C","text":"100% accurate always"},{"label":"D","text":"Ignore limitations"},{"label":"E","text":"Single wavelength"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Pulse oximetry + capnography physics: (1) Pulse oximetry: - Principle: Beer-Lambert law — absorption of red (660 nm) + infrared (940 nm) light by oxy- vs deoxyhemoglobin; - Pulsatile flow = arterial signal (ratio of pulsatile absorption red:IR converted to SpO2); - Accuracy ± 2% above SpO2 90%; (2) Limitations: - Motion artifact; - Poor perfusion (hypothermia, shock, vasoconstrictor); - Nail polish, henna; - Dyshemoglobinemia: - Carboxyhemoglobin (CO poisoning) — falsely HIGH (co-ox needed); - Methemoglobinemia — reads ~85% regardless of true; - Sulfhemoglobin; - Anemia — accuracy maintained until severe; - Ambient light interference; - Dye (methylene blue, indigo carmine — temporary drop); - Skin pigmentation — recent concerns of bias in dark skin (FDA review); (3) Pulse co-oximetry (Masimo) — measures additional wavelengths for SpCO, SpMet, SpHb (continuous Hb); (4) Capnography: - Infrared absorption (CO2 absorbs specific IR); - Mainstream (heated, in airway) vs sidestream (sample drawn out); - Time-based waveform — 4 phases; - Volumetric capnography emerging; (5) Limitations: - Delay sidestream; - Water + secretions; - Disconnection misread as zero; - High RR/short breaths may underestimate; (6) Clinical applications (covered separately); (7) Other monitoring: - Cerebral oximetry (NIRS) — regional brain O2 (rSO2); useful cardiac, beach chair, complex; - SedLine + BIS — processed EEG depth; - Esophageal Doppler — CO; - Pulse contour CO analysis (FloTrac, LiDCO); (8) Standards — continuous SpO2 + capnography for anesthesia + moderate/deep sedation; (9) Modern: integrated multi-parameter monitors, wearable continuous monitoring

---

Pulse ox: Beer-Lambert, R+IR ratio. Limitations: motion, perfusion, CO/MetHb, anemia, pigmentation. Capnography: IR absorption. Limitations: water, RR. NIRS/BIS/Doppler/pulse contour. Standards continuous.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'anesthesiology'
  and scenario = 'Basic science: physics of monitoring — pulse oximetry + capnography';

update public.mcq_questions
set choices = '[{"label":"A","text":"Use sux + volatile"},{"label":"B","text":"Muscular dystrophies + anesthesia"},{"label":"C","text":"Adult routine doses"},{"label":"D","text":"Ignore cardiac"},{"label":"E","text":"Refuse care"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Muscular dystrophies + anesthesia: (1) Categories: - Duchenne (DMD) + Becker (BMD) — X-linked; - Myotonic dystrophy — autosomal dominant; - Limb-girdle; - Facioscapulohumeral; (2) DMD: - Progressive proximal weakness, cardiomyopathy, scoliosis, respiratory failure; - AVOID succinylcholine (hyperkalemic arrest, rhabdomyolysis); - AVOID volatile anesthetics (MH-like reactions — anesthesia-induced rhabdomyolysis); - Use TIVA (propofol + opioid); - Cardiac assessment (cardiomyopathy); - Pulmonary assessment (restrictive); - NMB cautious (non-depolarizing OK at reduced dose with TOF); - Spinal anesthesia OK if scoliosis allows; (3) Myotonic dystrophy: - Sustained muscle contraction (myotonia); - Multisystem involvement (cardiac conduction, GI, endocrine, CNS); - AVOID succinylcholine (sustained myotonic contraction); - Caution all NMB; - Sensitive to opioids, sedatives, volatile (respiratory depression); - Cardiac conduction abnormalities — pacing readiness; - Temperature regulation; - Multimodal opioid-sparing; - Regional anesthesia helpful; - Avoid neostigmine (may worsen myotonia); use sugammadex if rocuronium; (4) Anesthesia-Induced Rhabdomyolysis (AIR): - Similar to MH but distinct mechanism — sarcolemmal damage; - Volatile triggers; - Treatment: stop volatile, supportive, IVF + alkalinization for myoglobinuria, monitor K + CK; - NO dantrolene (different mechanism); (5) Cardiac considerations: - Cardiomyopathy → consider as such for management; - Conduction abnormalities → ECG, electrophysiology consult; (6) Respiratory: - Restrictive disease; - Cough impaired; - Risk post-op ventilatory failure; - Avoid long-acting opioid; (7) Multidisciplinary: anesthesia + neurology + cardiology + pulmonology + physical therapy

---

Muscular dystrophies: DMD/BMD avoid sux + volatile (AIR), TIVA. Myotonic: avoid sux (sustained contraction), conduction abnormalities, NMB caution. Cardiomyopathy + respiratory assessment. Multidisciplinary.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'anesthesiology'
  and scenario = 'Basic science: muscular dystrophies + anesthesia';

update public.mcq_questions
set choices = '[{"label":"A","text":"Single opioid only"},{"label":"B","text":"Anesthesia adjuvants"},{"label":"C","text":"Skip multimodal"},{"label":"D","text":"Adult only"},{"label":"E","text":"Avoid all adjuvants"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Anesthesia adjuvants — opioid-sparing: (1) Ketamine: - NMDA antagonist; - Sub-anesthetic dose 0.1-0.5 mg/kg bolus + 0.1-0.3 mg/kg/hr infusion; - Anti-hyperalgesic + analgesic + opioid-sparing; - Useful: chronic opioid users, opioid-induced hyperalgesia, complex regional pain syndrome, depression (intranasal esketamine FDA-approved); - Side effects: sympathomimetic (HTN, tachy), psychomimetic (hallucinations — combine with low-dose benzo), salivation; (2) Magnesium: - NMDA antagonist + Ca channel blockade + smooth muscle relaxation; - Loading 30-50 mg/kg + infusion 8-15 mg/kg/hr; - Reduces opioid requirement, post-op pain, PONV, shivering, asthma; - Side effects: hypotension, flushing, sedation, NMB potentiation, respiratory depression at high levels; - Monitor reflexes + RR + serum Mg; (3) Lidocaine infusion: - Na channel block; - Bolus 1.5 mg/kg + infusion 1-3 mg/kg/hr; - Anti-inflammatory + analgesic; - Reduces opioid + ileus + PONV; - Useful: abdominal surgery, spine, breast; - Side effects: LAST (CNS, CV) — monitor signs + symptoms; - Avoid in heart block, severe hepatic dysfunction; (4) Dexmedetomidine (covered separately): alpha-2 agonist, sedation + analgesia + sympatholysis, no respiratory depression; (5) Dexamethasone: - Steroid; 4-10 mg single dose; - Anti-inflammatory + antiemetic + analgesic + airway swelling; - Hyperglycemia concern minimal single dose; (6) Gabapentinoids (gabapentin, pregabalin): - Voltage-gated Ca channel modulation; - Pre-op 300-1200 mg gabapentin or 75-300 mg pregabalin; - Reduces opioid + acute pain + chronic pain prevention; - Side effects: sedation, dizziness, especially elderly; recent guidelines suggest selective use rather than routine; (7) Acetaminophen IV: 1g; consistent multimodal; (8) NSAID (ketorolac 15-30 mg, celecoxib 200-400 mg); (9) Modern: multimodal opioid-sparing routine for major surgery; ERAS protocols

---

Adjuvants: ketamine (NMDA, anti-hyperalgesic), magnesium (NMDA + Ca), lidocaine infusion (Na channel, anti-inflammatory), dex (anti-inflammatory + analgesic), gabapentinoid (selective use), acetaminophen + NSAID. ERAS multimodal opioid-sparing standard.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'anesthesiology'
  and scenario = 'Basic science: pharmacology of common anesthesia adjuvants — ketamine, magnesium, lidocaine infusion';

update public.mcq_questions
set choices = '[{"label":"A","text":"Ignore ethics"},{"label":"B","text":"Anesthesia ethics"},{"label":"C","text":"Single principle only"},{"label":"D","text":"Hide errors"},{"label":"E","text":"Discriminate"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Anesthesia ethics: (1) Core principles: - Autonomy — patient self-determination, informed consent; - Beneficence — act in patient''s best interest; - Non-maleficence — first, do no harm; - Justice — fair distribution + access; (2) Common ethical dilemmas: - DNR in OR (covered); - Jehovah''s Witness blood refusal; - Capacity + surrogate decisions; - Disclosure of error; - End-of-life care + withdrawal; - Resource allocation (mass casualty, transplant); - Conflict of interest; - Confidentiality + privacy; - Pediatric assent + adolescent autonomy; - Pregnancy + fetal interests; - Substance use + impairment colleagues; - Caring for difficult patients; - Treatment of incarcerated patients; (3) Decision-making frameworks: - Four boxes (Jonsen): medical indications, patient preferences, quality of life, contextual features; - Multidisciplinary ethics consult; - Ethics committees; (4) Informed consent process: - Voluntary; - Capacity assessment; - Information disclosure; - Documentation; (5) Truth-telling: - Honest communication; - Cultural sensitivity; - Bad news delivery skills; (6) Confidentiality: - HIPAA; - Limits (mandatory reporting, public health, immediate safety); (7) Resource allocation: - ICU bed; - Transplant organ; - Crisis standards of care (pandemic); - Triage (mass casualty); (8) Professional ethics: - Maintain competence (MOC); - Avoid impairment; - Report colleague impairment/error; - Conflict of interest disclosure; - Industry relationships; (9) Research ethics: - Belmont Report (respect, beneficence, justice); - IRB; - Informed consent; - Vulnerable populations; - Data integrity; (10) Modern: precision medicine, AI ethics, digital health, genetic information, environmental ethics; (11) Resources: - ASA Statement on Ethical Practice; - AMA Code of Medical Ethics; - WMA Declaration of Geneva; - Bioethics literature

---

Anesthesia ethics: autonomy + beneficence + non-maleficence + justice. Common dilemmas: DNR, Jehovah''s Witness, capacity, disclosure, end-of-life. Four boxes framework. Ethics consult. Modern: AI, digital, environmental ethics.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'anesthesiology'
  and scenario = 'Integrative: ethics in anesthesia practice';

update public.mcq_questions
set choices = '[{"label":"A","text":"Avoid difficult conversations"},{"label":"B","text":"Difficult conversations + bad news"},{"label":"C","text":"Single quick statement"},{"label":"D","text":"Skip empathy"},{"label":"E","text":"Hide info"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Difficult conversations + bad news: (1) SPIKES protocol — bad news: - Setting (privacy, sit down, no distraction); - Perception (what patient knows); - Invitation (how much info wanted); - Knowledge (clear language, no jargon, pause for comprehension); - Emotion (acknowledge, empathize, support); - Strategy + summary (plan, follow-up); (2) Other models — NURSE (Name, Understand, Respect, Support, Explore emotions), Ask-Tell-Ask; (3) Anesthesia-specific scenarios: - Pre-op consent risk disclosure; - Adverse event disclosure (intraop awareness, dental injury, nerve injury, mortality); - Death notification; - End-of-life discussions; - Substance use disorder; - Chronic pain — realistic expectations; - Difficult family interactions; (4) Disclosure of adverse events: - Honest + timely; - Express empathy + apology (sorry vs admit fault — vary by jurisdiction; many states have apology laws); - Factual + non-defensive; - Documentation; - Institutional support; - Multidisciplinary; - Follow-up; (5) Family meetings: - Multidisciplinary; - Prepared agenda; - Patient/family-centered; - Cultural + spiritual considerations; - Decision aid + clarify; - Document discussion + outcomes; (6) Specific situations: - Pediatric — developmentally appropriate, parents, child life; - Cognitive impairment — surrogate; - LEP — interpreter; - Cultural differences — humility; (7) Communication skills training: - Simulation; - Real-time feedback; - Mentorship; (8) Self-care for provider: - Vicarious trauma; - Second victim phenomenon; - Debriefing; - Support resources; (9) Cognitive biases — anchoring, availability, confirmation; awareness; (10) Modern: cultural humility, structural humility, narrative medicine, patient-centered care, family-witnessed resuscitation

---

Difficult conversations: SPIKES (Setting, Perception, Invitation, Knowledge, Emotion, Strategy), NURSE. Disclosure (honest + empathic + apology). Multidisciplinary family meetings. Cultural + spiritual considerations. Self-care. Modern: patient-centered + humility.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'anesthesiology'
  and scenario = 'Integrative: communication with patients + family — bad news + difficult conversations';

update public.mcq_questions
set choices = '[{"label":"A","text":"Ignore evidence"},{"label":"B","text":"Translational research + evidence-based practice"},{"label":"C","text":"Rapid adoption all"},{"label":"D","text":"Single discipline"},{"label":"E","text":"Skip improvement"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Translational research + evidence-based practice: (1) Research to practice gap — 17 years average; addressing: - Implementation science: - Diffusion of innovation; - Knowledge translation; - Quality improvement; (2) Levels of translation: - T1: bench to bedside (drug development); - T2: clinical research to clinical practice; - T3: practice to community/population; - T4: policy + health outcomes; (3) Implementation science frameworks: - CFIR (Consolidated Framework Implementation Research); - PARIHS (Promoting Action Research Implementation); - RE-AIM (Reach, Effectiveness, Adoption, Implementation, Maintenance); (4) Quality improvement methodology: - PDSA (Plan, Do, Study, Act); - Six Sigma; - Lean; - Audit + feedback; - Clinical practice guidelines; - Pathways + protocols; (5) Barriers to adoption: - Time + workload; - Knowledge gaps; - Habit; - Patient + colleague resistance; - System constraints; - Resource limitations; (6) Facilitators: - Leadership champion; - Education; - Aligned incentives; - System redesign; - Feedback; - Patient + family engagement; (7) Anesthesia examples: - ERAS adoption; - Multimodal opioid-sparing; - Lung-protective ventilation; - Goal-directed fluid therapy; - Quality programs (NACOR, MIPS); (8) Maintenance + sustainability: - Continuous improvement; - Avoid drift; - Update guidelines; - Re-train; (9) Patient engagement: - Co-design; - Patient-reported outcomes; - Shared decision-making; - Lived experience; (10) Modern: big data, AI/ML, learning health systems, registries (NACOR), comparative effectiveness research, real-world evidence; (11) Resources: - Cochrane; - ASA practice advisories; - Evidence-Based Anesthesia; - Anesthesia & Analgesia Translational Research

---

Translational research: gap 17 years. Levels T1-T4. Implementation science (CFIR, RE-AIM). QI methodology (PDSA). Barriers + facilitators. Anesthesia examples (ERAS, multimodal). Modern: big data + AI/ML + learning health systems.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'anesthesiology'
  and scenario = 'Integrative: research + clinical practice — translating evidence';

update public.mcq_questions
set choices = '[{"label":"A","text":"Avoid telemedicine"},{"label":"B","text":"Telemedicine in anesthesia"},{"label":"C","text":"Same as in-person all"},{"label":"D","text":"Skip security"},{"label":"E","text":"No documentation"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Telemedicine in anesthesia: (1) Pre-op telemedicine: - Pre-anesthesia evaluation virtual; - Especially useful for ambulatory + remote patients; - Time + cost savings; - High satisfaction; - Limitations: airway exam, physical exam; - Hybrid (virtual + in-person) common; (2) Tele-ICU: - Centralized ICU monitoring + consultation; - 24/7 intensivist coverage rural/community; - Quality + mortality improvements; - Care plans + medication review; - Family communication; (3) Tele-anesthesia OR: - Mentorship + supervision remote; - Difficult case consultation; - Mass casualty + disaster; - Global health applications; (4) Tele-PACU + tele-rounding; (5) Mobile apps + wearables: - Patient monitoring (BP, SpO2, glucose, sleep); - Medication adherence; - Pain tracking; - Recovery monitoring; (6) Patient education: - Videos; - Apps; - Tele-consultation; - Cultural translation; (7) Limitations + challenges: - Technology access (digital divide); - Privacy + security; - Reimbursement (evolving); - Licensing + jurisdiction; - Liability + standard of care; - Cultural + language; - Physical exam limitations; - Procedure-specific (cannot do all in person); (8) COVID-19 pandemic accelerated adoption; (9) Quality + safety: - Same standards apply; - Documentation requirements; - Technical reliability; (10) Specific anesthesia applications: - Pre-anesthesia clinic; - Pain medicine consultation; - Critical care; - Disaster response; - Global health partnerships; - Education + simulation; (11) Modern: telemedicine integral to healthcare; ASA guidance + advocacy; ongoing reimbursement + regulation evolution

---

Telemedicine anesthesia: pre-op evaluation + tele-ICU + tele-PACU + mentorship + global health. Limitations: physical exam, technology access, reimbursement. COVID accelerated. Same standards + documentation. ASA guidance.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'anesthesiology'
  and scenario = 'Integrative: telemedicine + anesthesia (pre-op, post-op, ICU)';

commit;
