-- ===============================================================
-- UPDATE chunk 4/8: radiology (25 questions)
-- ===============================================================

begin;

update public.mcq_questions
set choices = '[{"label":"A","text":"Discharge"},{"label":"B","text":"Acute decompensated heart failure (ADHF) — imaging + workup"},{"label":"C","text":"Single specialty"},{"label":"D","text":"X-ray only sufficient"},{"label":"E","text":"Refuse care"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Acute decompensated heart failure (ADHF) — imaging + workup: (1) **CXR features**: cardiomegaly (cardiothoracic ratio > 0.5), upper lobe pulmonary venous diversion (cephalization — chronic), interstitial edema (Kerley B lines — peripheral horizontal lines in lower lobes, peribronchial cuffing, prominent interstitial markings — bat-wing distribution central), alveolar edema (perihilar ''bat wing''), pleural effusions (often right > left), valve calcifications; (2) **POCUS** (lung + cardiac): - **Lung**: B-lines (multiple — pulmonary edema, > 3 per intercostal space + bilateral diffuse), pleural effusions; - **Cardiac**: LV function (visual estimate of EF), wall motion abnormalities, RV size, pericardial effusion, IVC size + collapsibility (volume status — large + non-collapsing = high pressure); (3) **Echocardiogram** — comprehensive: LVEF, regional WMA, valves, diastolic function, RV, PA pressure estimation; classify HFrEF vs HFpEF (preserved EF ≥ 50%); (4) **CMR** for cardiomyopathy etiology (above question); (5) **Workup acute**: BNP/NT-proBNP, troponin (concurrent ischemia), CBC, BMP, TFTs, iron studies (cardiac iron overload), HIV, drug screen if appropriate; (6) **Treatment ADHF**: IV diuretics (loop — furosemide, doses titrated; DOSE trial), vasodilators (nitroglycerin for pulmonary edema + hypertension), inotropes (dobutamine, milrinone — for cardiogenic shock low EF), positive pressure ventilation (BiPAP — reduces preload + afterload + work of breathing); (7) **HFrEF chronic**: GDMT — ARNI (sacubitril/valsartan), beta-blocker (carvedilol, metoprolol succinate, bisoprolol), MRA (spironolactone, eplerenone), SGLT2 inhibitor (dapagliflozin, empagliflozin — improves outcomes regardless of DM); device — ICD, CRT for selected; advanced — LVAD, transplant; (8) **HFpEF** — empagliflozin/dapagliflozin (EMPEROR-Preserved, DELIVER); diuretics for symptoms; comorbidity management; (9) **Multidisciplinary HF clinic**: cardiology + HF specialist + PCP + nursing + nutrition + pharmacy + palliative care

---

ADHF: CXR cardiomegaly + Kerley B + bilateral edema. POCUS B-lines + cardiac. Echo for HFrEF/HFpEF + etiology. GDMT — ARNI + BB + MRA + SGLT2i (4 pillars). Multidisciplinary HF clinic.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'radiology'
  and scenario = 'ผู้ป่วยอายุ 75 ปี acute SOB + bilateral leg edema + S3 + JVD — CXR พบ cardiomegaly + cephalization + Kerley B lines + bilateral interstitial edema';

update public.mcq_questions
set choices = '[{"label":"A","text":"Single specialty discharge"},{"label":"B","text":"Pericardial tamponade — imaging + management"},{"label":"C","text":"Wait for elective workup"},{"label":"D","text":"Refuse care"},{"label":"E","text":"X-ray only"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Pericardial tamponade — imaging + management: (1) **POCUS / echocardiogram** — first-line emergent: large pericardial effusion (anechoic space around heart > 1 cm typically), tamponade signs — RV diastolic collapse, RA systolic collapse (more sensitive), septal bounce, IVC plethora (dilated, non-collapsing with respiration), respiratory variation in transvalvular flows (> 25% mitral, > 60% tricuspid — flow paradoxus); (2) **CXR**: ''water bottle'' cardiac silhouette (large globular heart) — slow accumulation; small effusions don''t change CXR; (3) **CT/MRI**: pericardial effusion characterization (hemorrhagic high attenuation, malignant masses, fibrin strands suggesting hemorrhagic/purulent); pericardial thickening (constrictive pericarditis differential); (4) **Etiology**: - Malignancy (most common cause large effusion + tamponade in adults — lung, breast, lymphoma, leukemia); - Infectious (TB endemic regions, viral, purulent); - Uremia (advanced renal failure); - Post-pericardiotomy syndrome; - Post-MI (Dressler, free wall rupture - small effusion can tamponade in acute); - Aortic dissection (extension into pericardium); - Hemorrhagic (anticoagulants, trauma, post-procedure); - Autoimmune (lupus, RA); - Hypothyroidism; (5) **Management emergent tamponade**: - **Pericardiocentesis** — subxiphoid + echo-guided; pigtail catheter for ongoing drainage (~24-48 hours); send fluid for cytology, gram + AFB stain + culture, protein, LDH, glucose, triglycerides; - **Surgical pericardiotomy / pericardial window** for malignant recurrent (subxiphoid window vs VATS — long-term drainage to pleural space); - Treat underlying cause; (6) **Constrictive pericarditis** (chronic): pericardial thickening + calcification + septal bounce + ventricular interdependence (D-shaped LV in inspiration) — distinguish from restrictive cardiomyopathy (CT/CMR critical) — pericardiectomy curative; (7) **Multidisciplinary**: cardiology + cardiac surgery + IR + oncology if malignant

---

Tamponade: echo first-line — large effusion + RV/RA collapse + IVC plethora + flow paradoxus. Emergent pericardiocentesis. Etiology workup. Surgical window for recurrent malignant. CT/CMR differentiate constrictive vs restrictive. Multidisciplinary.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'radiology'
  and scenario = 'ผู้ป่วยอายุ 65 ปี acute SOB + hypotension + JVD + muffled heart sounds (Beck''s triad) — pericardial effusion + tamponade physiology';

update public.mcq_questions
set choices = '[{"label":"A","text":"Single specialty discharge"},{"label":"B","text":"Infective endocarditis (IE) imaging"},{"label":"C","text":"X-ray only"},{"label":"D","text":"Refuse care"},{"label":"E","text":"Discharge"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Infective endocarditis (IE) imaging: (1) **Duke Criteria 2023 modified** (Major + minor): need 2 major OR 1 major + 3 minor OR 5 minor for definite IE; (2) **Major criteria — imaging-based**: - **Echocardiogram**: vegetation, abscess, prosthetic valve dehiscence/regurgitation, new valvular regurgitation; - **18F-FDG PET/CT or radiolabeled WBC SPECT/CT**: abnormal activity on prosthetic valve (≥ 3 months post-implant) — added in 2023 update; - **Cardiac CT**: definite paravalvular lesions; (3) **Echocardiogram approach**: - **TTE first** — sensitivity ~ 60% native valve, lower for prosthetic; - **TEE if negative TTE + clinical suspicion** OR initial in high-risk (prosthetic valve, IVDU with high suspicion, complications suspected) — sensitivity > 90%; - **Repeat TEE in 5-7 days** if initial negative + persistent suspicion; - Surveillance TEE for complications (abscess, dehiscence, perforation) + response monitoring; (4) **Other imaging**: - **Brain MRI** — embolic strokes + mycotic aneurysms (rupture risk — high in unruptured); routinely indicated even if asymptomatic per recent guidelines; - **CTA brain** — mycotic aneurysm screening; - **Whole-body imaging** — FDG PET/CT or labeled WBC for prosthetic valve + cardiac implantable device IE — sensitivity for prosthetic IE; (5) **Embolic phenomena imaging**: splenic infarcts, mycotic aneurysms (brain, mesenteric, splenic), Janeway lesions, Osler nodes, Roth spots, septic pulmonary emboli (right-sided IE — IVDU); (6) **Microbiology**: blood cultures × 3 from different sites BEFORE antibiotics, then empiric therapy modified by sensitivities; culture-negative IE (Coxiella, Bartonella, HACEK, Brucella — serology); (7) **Treatment**: prolonged IV antibiotics (4-6 weeks); surgery indications — CHF from valve destruction, persistent bacteremia, large vegetation > 10 mm with embolic events, paravalvular abscess, prosthetic valve IE, fungal IE; (8) **Multidisciplinary ''Endocarditis Team''**: cardiology + ID + cardiothoracic surgery + radiology + microbiology — improves outcomes per ESC + AHA

---

IE: Duke criteria 2023. TTE → TEE if negative + suspicion. Brain MRI for emboli. FDG-PET/CT or WBC SPECT for prosthetic valve. Multidisciplinary Endocarditis Team. Surgery for selected. Prolonged antibiotics.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'radiology'
  and scenario = 'ผู้ป่วยอายุ 50 ปี IVDU + fever + new murmur + embolic phenomena — infective endocarditis workup';

update public.mcq_questions
set choices = '[{"label":"A","text":"Discharge"},{"label":"B","text":"Coronary artery calcium (CAC) scoring (Agatston)"},{"label":"C","text":"X-ray sufficient"},{"label":"D","text":"Always treat with statin"},{"label":"E","text":"Bone scan"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Coronary artery calcium (CAC) scoring (Agatston): (1) **Method**: non-contrast prospectively ECG-gated CT chest, low radiation (~ 1 mSv), no contrast needed; calculates Agatston score based on calcified plaque area + density; (2) **Score categories**: - **CAC = 0** — very low risk (~ 1% MACE 10-year — ''power of zero'') — defer statin in low-intermediate risk; - **CAC 1-99** — mild; - **CAC 100-399** — moderate elevated risk; - **CAC ≥ 400** — severely elevated, equivalent to known CAD risk; (3) **Indications per ACC/AHA 2018 Cholesterol Guidelines** (Class IIa): asymptomatic intermediate ASCVD risk (10-year risk 5-20%, especially 7.5-20%) with uncertainty about statin benefit — CAC for risk reclassification + shared decision-making; also reasonable in selected low-borderline (5-7.5%) with risk enhancers (family history, etc.); (4) **NOT recommended** for: very low risk (< 5%), high risk already (already statin indicated), known CAD, symptomatic (use CCTA or stress test); (5) **Pitfalls**: detects calcified plaque only — does NOT detect non-calcified vulnerable plaque (younger patients), so ''zero'' less reliable in symptomatic; race/sex differences (lower in women, certain ethnicities); (6) **MESA Risk Score** integrates CAC with traditional risk factors — better prediction than risk calculators alone; (7) **Management based on CAC**: lifestyle (DASH/Mediterranean diet, exercise, weight, smoking cessation) for all; statin (moderate-high intensity) for CAC ≥ 100 (or per MESA estimate); aspirin individualized (ASCVD risk vs bleeding); BP + DM control; (8) **Patient education**: visual representation of risk often motivates lifestyle change; (9) **Multidisciplinary**: cardiology + primary care + radiology

---

CAC scoring: non-contrast CT for asymptomatic intermediate risk reclassification (ACC/AHA 2018 IIa). ''Power of zero'' very low risk. CAC ≥ 100 → statin. Not for symptomatic (use CCTA). MESA Risk Score integrates. Multidisciplinary preventive cardiology.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'radiology'
  and scenario = 'ผู้ป่วยอายุ 50 ปี asymptomatic — preventive cardiology — coronary artery calcium (CAC) scoring';

update public.mcq_questions
set choices = '[{"label":"A","text":"Always TRO for all chest pain"},{"label":"B","text":"Triple rule-out CT (TRO) — comprehensive"},{"label":"C","text":"MRI"},{"label":"D","text":"X-ray sufficient"},{"label":"E","text":"Discharge"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Triple rule-out CT (TRO) — comprehensive: (1) **Indication**: ED chest pain with unclear etiology — possible PE, ACS, aortic dissection — when clinical picture is mixed; controversial — most ED workups use targeted imaging based on clinical pre-test probabilities + biomarkers; (2) **Protocol**: ECG-gated CT chest with optimized IV contrast bolus timing to opacify pulmonary arteries + coronary arteries + thoracic aorta simultaneously (typically biphasic injection); higher radiation + contrast vs single-purpose CT; (3) **Strengths**: rapid (< 30 min imaging + reading), one-stop; (4) **Limitations**: higher radiation + contrast, complex protocols, requires expertise, may not be best for any single indication individually; not validated in highest-risk patients; (5) **Modern alternative**: high-sensitivity troponin pathways (rapid rule-out — 0/1 h algorithms per ESC) + risk-stratified imaging based on clinical scores; (6) **When TRO useful**: equivocal presentations with mixed differentials + need to expedite; (7) **Single-purpose CT preferred for most**: - **CTPA** for PE — Wells + D-dimer first; - **CCTA** for stable chest pain + intermediate PTP CAD; - **CTA aorta** for high clinical suspicion dissection; (8) **Modern imaging diagnostics**: AI-assisted detection (PE, LVO, calcium scoring) + structured reporting + closed-loop communication; (9) **Multidisciplinary**: ED + cardiology + radiology + critical care

---

Triple rule-out CT: combined PE/ACS/dissection — useful selected; ECG-gated; higher radiation + contrast. Modern practice — targeted imaging based on clinical PTP + hs-troponin pathways. AI-assisted detection. Multidisciplinary.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'radiology'
  and scenario = 'ผู้ป่วยอายุ 65 ปี acute chest pain + shock + ECG พบ ST elevation anterior + RV strain — pulmonary embolism vs MI vs aortic dissection — triple rule-out CT';

update public.mcq_questions
set choices = '[{"label":"A","text":"Discharge"},{"label":"B","text":"TAVR pre-procedural imaging"},{"label":"C","text":"Single specialty"},{"label":"D","text":"X-ray only"},{"label":"E","text":"Refuse care"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** TAVR pre-procedural imaging: (1) **Comprehensive multimodality imaging**: - **TTE (echo)** — confirm severe AS (mean gradient ≥ 40 mmHg, peak velocity ≥ 4 m/s, AVA ≤ 1 cm² or AVAi ≤ 0.6 cm²/m²), LV function, other valves, RV function; - **TEE** if poor TTE windows or low-flow low-gradient AS (dobutamine stress echo to assess true vs pseudo-severe); - **Cardiac CT (multiphase ECG-gated)** — STANDARD for TAVR planning: annulus sizing (3D circumference + area + perimeter for valve size selection — undersizing → paravalvular leak, oversizing → annular rupture), aortic root + sinotubular junction geometry, coronary ostial heights (low ostia < 10-12 mm risk coronary occlusion), aortic + iliofemoral access vessel evaluation (caliber > 5-6 mm typically needed for transfemoral, tortuosity, calcification), aortic valve calcification distribution (asymmetric — paravalvular leak risk); - **Coronary angiography** — pre-TAVR for revascularization decisions in significant CAD (PCI before TAVR for proximal/large vessel disease, especially LM/LAD); - **Carotid imaging** for stroke risk; - **PFTs + renal function** + frailty assessment; (2) **Heart team evaluation** — multidisciplinary: cardiology, interventional cardiology, cardiothoracic surgery, anesthesia, imaging, nursing — assess STS-PROM, frailty (essential frailty toolset), patient preference; (3) **TAVR vs SAVR decision** (PARTNER + EVOLUT trials): - **Low risk** (STS < 4%) — TAVR non-inferior to SAVR (PARTNER 3, EVOLUT Low Risk) — increasingly TAVR preferred; - **Intermediate risk** — TAVR equivalent or better; - **High/extreme risk** — TAVR superior to medical (no SAVR option); - Younger patients (< 65) — SAVR still preferred (limited TAVR durability data > 10 years); valve-in-valve TAVR option for failed bioprosthetic SAVR; (4) **Procedural imaging**: fluoroscopy + TEE intra-op for positioning + paravalvular leak assessment; (5) **Post-TAVR follow-up**: echo at discharge, 30 days, 1 year, then annual; (6) **Modern**: increasing TAVR indications; bicuspid AV — anatomic challenges; mitral + tricuspid transcatheter therapies

---

TAVR pre-procedural imaging: TTE/TEE for severity, cardiac CT for annulus + access + coronary heights, coronary angio for CAD. Heart team evaluation. TAVR vs SAVR by risk + age. PARTNER + EVOLUT trials. Multidisciplinary.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'radiology'
  and scenario = 'ผู้ป่วยอายุ 70 ปี severe AS + planning for TAVR — pre-procedural imaging';

update public.mcq_questions
set choices = '[{"label":"A","text":"No imaging"},{"label":"B","text":"Acute STEMI — imaging + treatment"},{"label":"C","text":"Discharge"},{"label":"D","text":"X-ray sufficient"},{"label":"E","text":"Single specialty"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Acute STEMI — imaging + treatment: (1) **STEMI diagnosis**: clinical + ECG (ST elevation in 2 contiguous leads or new LBBB) + troponin elevation; (2) **Primary PCI is gold standard** (vs fibrinolytics): - **Door-to-balloon (D2B) ≤ 90 minutes** (PCI-capable hospital); - **Door-to-needle ≤ 30 minutes** for fibrinolytics if no PCI available + transfer time > 120 minutes; - **Pre-hospital fibrinolytics** in some systems; - Door-in-door-out ≤ 30 minutes for transfer; (3) **Coronary angiography findings**: culprit vessel occlusion (typical patterns — LAD → anterior STEMI, RCA → inferior, LCx → lateral/posterior); other lesions (multi-vessel disease); (4) **Complete revascularization** — multi-vessel disease (non-culprit lesions): - **COMPLETE trial** + meta-analyses — staged complete revasc improves outcomes vs culprit-only; - Timing — during index admission or shortly after; - Cardiogenic shock — culprit-only first (CULPRIT-SHOCK); (5) **Adjuncts**: aspirin + P2Y12 (ticagrelor or prasugrel — DAPT 12 months), heparin (UFH or bivalirudin), high-intensity statin; (6) **Cardiogenic shock — mechanical support**: IABP (controversial — IABP-SHOCK II showed no mortality benefit), Impella (ongoing trials — RECOVER IV), ECMO for refractory; (7) **Post-STEMI imaging**: echo at 24-48h (LVEF, complications — VSD, free wall rupture, papillary muscle rupture with MR, LV thrombus); repeat echo at discharge + outpatient; cardiac MRI for tissue characterization (microvascular obstruction — MVO, intramyocardial hemorrhage, infarct size — prognostic); (8) **Mechanical complications of MI**: free wall rupture (cardiac tamponade), VSD (loud holosystolic murmur), papillary muscle rupture (severe MR + pulmonary edema), LV aneurysm (delayed), LV thrombus (anterior MI — anticoagulate); (9) **Multidisciplinary**: cardiology + interventional cardiology + critical care + cardiac surgery + ED

---

STEMI: primary PCI D2B ≤ 90 minutes. Coronary angio + culprit vessel identification. COMPLETE revasc improves outcomes (vs culprit only — except CULPRIT-SHOCK). Echo + CMR for prognosis + complications. Multidisciplinary.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'radiology'
  and scenario = 'ผู้ป่วยอายุ 55 ปี acute STEMI + cardiogenic shock — coronary angiography + PCI';

update public.mcq_questions
set choices = '[{"label":"A","text":"Radiation safe regardless of dose"},{"label":"B","text":"CT radiation dose — concepts"},{"label":"C","text":"Always avoid CT"},{"label":"D","text":"X-ray always preferred"},{"label":"E","text":"Discharge"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** CT radiation dose — concepts: (1) **Dose metrics**: - **CTDIvol** (CT dose index volume — mGy) — dose to phantom, indicator of scanner output; - **DLP** (dose-length product — mGy·cm) = CTDIvol × scan length; - **Effective dose** (mSv) — biological effect, weighted by tissue radiosensitivity (k-factor varies by body region — chest ~ 0.014, abdomen ~ 0.015); (2) **Typical effective doses**: CXR 0.02 mSv, mammogram 0.4 mSv, CT head 2 mSv, CT chest 7 mSv, CT abdomen-pelvis 10 mSv, coronary CT 3-5 mSv (prospective gating), nuclear cardiac stress 10-20 mSv, PET/CT 10-25 mSv; cumulative annual background ~ 3 mSv; (3) **Radiation risks (LNT model — linear no-threshold)**: - Stochastic — cancer (lifetime attributable risk: estimated 0.1% per 10 mSv) — pediatric, young adults higher; - Deterministic — skin injuries, cataracts (high dose); (4) **Dose reduction strategies (ALARA)**: - **Automatic tube current modulation (ATCM)** — based on patient size; - **Tube voltage reduction** (kVp — lower for smaller patients, vascular studies); - **Iterative reconstruction** (vs filtered back projection) — reduces noise at lower dose; - **AI/deep learning reconstruction** — emerging; - **Prospective ECG-gating** for cardiac CT (vs retrospective); - **Limiting scan length** to area of interest; - **Avoiding multiphase** when not needed; - **Bismuth shielding** for breast, thyroid, gonads — controversial recently, may worsen image quality + dose; (5) **Image Gently** (pediatric) + **Image Wisely** (adult) campaigns — promote appropriate use; (6) **Pediatric considerations**: 3-4× more radiosensitive than adults — child-sized protocols mandatory; (7) **Pregnancy**: ACR — diagnostic imaging rarely contraindicated in pregnancy when needed; cumulative fetal dose typically < 50 mGy threshold; informed discussion; (8) **Documentation + dose monitoring**: real-time + cumulative tracking; (9) **Multidisciplinary**: radiology + medical physics + ordering providers + patient education

---

CT radiation: CTDIvol, DLP, effective dose (mSv). Risks — stochastic cancer. ALARA strategies: tube current/voltage modulation, iterative reconstruction, AI, prospective gating, limiting scan length. Image Gently/Wisely. Pediatric particularly sensitive.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'radiology'
  and scenario = 'CT radiation dose — concepts + ALARA principle';

update public.mcq_questions
set choices = '[{"label":"A","text":"No safety concerns"},{"label":"B","text":"Iodinated CT contrast safety"},{"label":"C","text":"X-ray equivalent radiation"},{"label":"D","text":"Always contraindicated"},{"label":"E","text":"Discharge"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Iodinated CT contrast safety: (1) **Types**: low-osmolar non-ionic (iohexol, iopamidol, iopromide) — current standard; iso-osmolar (iodixanol — selected high-risk renal); high-osmolar replaced; (2) **Adverse reactions**: - **Allergic/anaphylactoid** (NOT true allergy in most cases — not IgE-mediated, but presents similarly): mild (urticaria, mild bronchospasm) 0.6%, moderate-severe 0.04-0.04%, fatal 1-3 per million; - **Premedication for prior reaction**: prednisone 50 mg PO 13h, 7h, 1h pre + diphenhydramine 50 mg 1h pre (Lasser/Greenberger regimen); methylprednisolone IV alternative; emergency protocols faster; - **Cross-reactivity** with gadolinium minimal; shellfish allergy NOT predictive (despite myth); (3) **Contrast-Induced Nephropathy (CIN) / Post-Contrast AKI (PC-AKI)**: - **Definition**: ≥ 25% or 0.3-0.5 mg/dL rise in creatinine within 48-72h; - **Risk factors**: pre-existing CKD (eGFR < 30 highest risk, 30-44 moderate), diabetes, dehydration, advanced age, CHF, large contrast volume, recent contrast within 48-72h, concurrent nephrotoxins; - **Recent evidence**: incidence overestimated in observational studies (confounded by underlying disease); RCTs (PRESERVE) showed no benefit of N-acetylcysteine; mostly avoided in emergencies if clinically needed; - **Prevention**: hydration with IV normal saline 1 mL/kg/h × 6-12h pre + post (best evidence intervention); minimize contrast volume; iso-osmolar in highest-risk; assess eGFR; discontinue nephrotoxins; - **Metformin**: stop before contrast in CKD (eGFR < 30) — risk lactic acidosis; resume 48h after if renal function preserved; (4) **Extravasation**: monitor for swelling at injection site — small extravasations conservative; large or compartment-syndrome risk — surgical evaluation; (5) **Pregnancy**: iodinated contrast crosses placenta — fetal thyroid concerns minimal with single exposure; use if clinically essential; (6) **Breastfeeding**: continue (minimal transfer); (7) **Multidisciplinary**: radiology + ED + pharmacy + nursing + nephrology

---

Iodinated contrast: low-osmolar non-ionic standard. Anaphylactoid reactions (NOT true allergy) — premedication if prior. CIN risk in CKD/DM — IV hydration prevention. Metformin hold in CKD. Pregnancy/breastfeeding generally OK.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'radiology'
  and scenario = 'Iodinated CT contrast — safety + contrast-induced nephropathy (CIN)';

update public.mcq_questions
set choices = '[{"label":"A","text":"No systematic approach needed"},{"label":"B","text":"Systematic CXR interpretation"},{"label":"C","text":"Read in 5 seconds"},{"label":"D","text":"Discharge"},{"label":"E","text":"Single area only"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Systematic CXR interpretation: (1) **Quality assessment first**: - **Rotation** — clavicles equidistant from spinous processes; - **Inspiration** — diaphragm at 10th posterior rib / 8th anterior rib; - **Penetration** — vertebrae visible behind heart; - **Angulation** — clavicles project below 4th rib (PA); - **Patient demographics + side markers + technique** (PA preferred to AP — AP magnifies heart); (2) **Systematic ''ABCDEFGHI'' or similar approach**: - **A — Airway**: trachea midline, carina, mainstem bronchi; - **B — Bones**: ribs (fractures), clavicles, spine, scapulae; - **C — Cardiac**: cardiothoracic ratio (< 0.5 PA), borders distinct; - **D — Diaphragm**: contour, free air below, costophrenic angles sharp; - **E — Edges + Effusions**: lateral, costophrenic angles, paravertebral; - **F — Fields (lung)**: zones (upper/middle/lower), compared bilaterally — opacities (consolidation, atelectasis, mass), lucencies (pneumothorax, bullae, emphysema), interstitial (Kerley B, reticulation, septal thickening), vascular markings; - **G — Gastric bubble** + bowel loops; - **H — Hila**: size, density (vascular vs lymphadenopathy), symmetry; - **I — Implants + tubes + lines + iatrogenic**: ETT (3-5 cm above carina), NG/OG tube position (subdiaphragmatic, NOT in lung), CVC (SVC-RA junction, not in heart, no PTX), Foley/PICC, pacemaker leads, surgical clips, chest tubes; (3) **Common pitfalls + tricks**: - **Silhouette sign**: loss of border = pathology adjacent (RML pneumonia obscures right heart border, lingula obscures left); - **Air bronchograms**: consolidation around patent airways; - **Deep sulcus sign**: pneumothorax on supine; - **Hampton hump + Westermark sign**: PE (rare but specific); - **Three Bs**: bones, breasts, base of lung — check edges; (4) **Comparison with priors** — essential; (5) **Documentation + structured reporting**: standardized helps consistency; (6) **Modern**: AI-assisted detection (PTX, nodules, consolidation) — adjunct to radiologist read

---

CXR interpretation: quality first (rotation, inspiration, penetration). Systematic ABCDEFGHI. Silhouette sign + air bronchograms. Compare with priors. AI-assisted detection adjunctive. Structured reporting.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'radiology'
  and scenario = 'Chest X-ray interpretation — systematic approach';

update public.mcq_questions
set choices = '[{"label":"A","text":"Anatomy unimportant"},{"label":"B","text":"Bronchopulmonary anatomy — CT"},{"label":"C","text":"Single lobe per lung"},{"label":"D","text":"X-ray only sufficient"},{"label":"E","text":"Discharge"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Bronchopulmonary anatomy — CT: (1) **Lobar anatomy**: - **Right lung**: 3 lobes (RUL, RML, RLL) separated by oblique (major) + horizontal (minor — only on right) fissures; - **Left lung**: 2 lobes (LUL with lingula functionally analogous to RML, LLL) separated by oblique fissure; (2) **Segmental anatomy (10 segments per lung — except left often 8 due to combined apicoposterior + anteromedial basal)**: - **RUL**: apical (S1), posterior (S2), anterior (S3); - **RML**: lateral (S4), medial (S5); - **RLL**: superior (S6), medial basal (S7), anterior basal (S8), lateral basal (S9), posterior basal (S10); - **LUL**: apicoposterior (S1+2), anterior (S3); - **Lingula**: superior (S4), inferior (S5); - **LLL**: superior (S6), anteromedial basal (S7+8), lateral basal (S9), posterior basal (S10); (3) **Vascular anatomy**: pulmonary arteries (deoxygenated, follow bronchi — bronchovascular bundle), pulmonary veins (oxygenated, drain interlobular septa, return to LA — anatomy important for pulmonary vein isolation in AFib ablation); bronchial arteries (systemic from aorta — bronchial circulation); (4) **Secondary pulmonary lobule** — anatomic-functional unit (1-2.5 cm, polyhedral, with terminal bronchiole + arteriole centrally, lymphatics + veins in interlobular septa) — basis for HRCT pattern interpretation: - **Centrilobular** distribution (small airway disease — RB-ILD, HP, infection); - **Perilymphatic** (along bronchovascular bundles + interlobular septa + subpleural — sarcoid, lymphangitic carcinomatosis); - **Random** (miliary TB, hematogenous mets); (5) **Mediastinal compartments** (IASLC 2014): superior (above thoracic inlet), prevascular (anterior), visceral (middle), paravertebral (posterior); (6) **Lymph node stations** (IASLC) — important for lung cancer staging — N stations 1-14 with subgroups; (7) **CT planes + windows**: axial standard, MPR (coronal, sagittal) for orientation, MIP for vessels + nodules, MinIP for airways/lucent lesions; lung window (level -600, width 1500), mediastinal (level 50, width 350), bone (level 400, width 1500)

---

Pulmonary anatomy: 3 lobes right, 2 left; 10 segments each side. Secondary pulmonary lobule = HRCT pattern unit (centrilobular, perilymphatic, random). Bronchovascular bundle. IASLC mediastinal + lymph node stations for lung cancer staging.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'radiology'
  and scenario = 'Pulmonary anatomy on CT — segmental bronchopulmonary anatomy';

update public.mcq_questions
set choices = '[{"label":"A","text":"No standardization needed"},{"label":"B","text":"Structured reporting + RADS systems"},{"label":"C","text":"Free text always preferred"},{"label":"D","text":"Discharge"},{"label":"E","text":"Single specialty"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Structured reporting + RADS systems: (1) **Benefits**: standardized communication, reduced ambiguity, comparable across institutions + readers, integration with EHR, quality improvement (compliance, outcomes), patient + referrer education; (2) **Major RADS systems**: - **BI-RADS** (Breast Imaging) — categories 0-6, longest established + most validated; - **Lung-RADS** — lung cancer screening LDCT (1-4X + S); - **LI-RADS** — liver imaging hepatocellular carcinoma (LR-1 definitely benign to LR-5 definitely HCC + LR-M malignant non-HCC); - **PI-RADS** — prostate MRI (1-5); - **TI-RADS** — thyroid nodule US (TR1-5); - **O-RADS** — ovarian/adnexal (1-5 US, with separate MRI version); - **C-RADS** — CT colonography colon polyps; - **CAD-RADS** — coronary CTA (0-5); - **NI-RADS** — head + neck post-treatment surveillance; - **Bone-RADS, ACR Lex-RADS, etc.** emerging; (3) **Components of structured report**: - Indication; - Technique; - Comparison; - Findings (organ-by-organ template); - Impression with management recommendations; - RADS classification + follow-up; - Critical findings communication documented; (4) **Implementation**: report templates in PACS / RIS; ACR Assist or similar embedded; (5) **Limitations**: rigid templates may miss nuances; require ongoing training + updates; (6) **Quality improvement**: peer review, RADPEER, dashboards, MIPS reporting, audits; (7) **Modern**: AI-augmented structured reporting + natural language processing + auto-population of fields; (8) **Patient-centered**: standardized impressions + plain-language summaries (Open Notes, patient portals) — increasingly common; (9) **Multidisciplinary**: radiology + ordering providers + EHR + IT + administration + quality + research

---

Structured reporting + RADS: BI-RADS, Lung-RADS, LI-RADS, PI-RADS, TI-RADS, O-RADS, CAD-RADS, C-RADS. Standardized communication + categories + follow-up. Quality improvement + EHR integration. AI augmentation emerging.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'radiology'
  and scenario = 'Structured reporting in radiology — RADS classifications + benefits';

update public.mcq_questions
set choices = '[{"label":"A","text":"No quality programs needed"},{"label":"B","text":"Radiology peer review + QA"},{"label":"C","text":"Single individual responsibility"},{"label":"D","text":"Discharge"},{"label":"E","text":"Refuse"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Radiology peer review + QA: (1) **Peer review programs**: - **RADPEER (ACR)** — anonymized random peer review of prior reports during current interpretation; categorize concordance (1-4) — agree, minor disagreement, clinically important disagreement, major; - **Discrepancy / error tracking** — root cause analysis, system + individual learning; - **Just culture** — distinguish system errors from individual negligence; (2) **Quality metrics**: - **Process measures**: turnaround time, critical findings communication, addendum/amendment rates, recommendation for follow-up adherence; - **Outcomes measures**: missed diagnoses, complications of procedures, patient satisfaction; - **Continuous quality improvement (CQI)**: PDSA cycles, lean methodology; (3) **Patient safety initiatives**: - **Wrong-side / wrong-patient prevention** — time-out before procedure, two patient identifiers; - **Contrast reaction management** — protocols, simulation; - **Radiation dose monitoring** — DICOM tags, ACR DIR (Dose Index Registry); - **Critical findings communication** — closed-loop systems with documentation; (4) **Accreditation**: ACR accreditation programs (CT, MR, US, mammography — MQSA, etc.) — facility + equipment + personnel + protocols + QC; (5) **Mammography Quality Standards Act (MQSA, FDA)** — federal regulation for mammography facilities; (6) **MIPS / Value-based reporting**: CMS quality reporting in US; (7) **Continuous Certification (ABR MOC)**: ongoing learning + assessment; (8) **Tumor boards + multidisciplinary conferences**: peer learning, quality, patient outcomes; (9) **Modern**: AI-assisted error detection, structured reporting, dashboards, transparency, patient-reported outcomes; (10) **Reporting near-misses + adverse events**: voluntary, blame-free, focused on systems improvement; (11) **Multidisciplinary**: radiology + administration + IT + risk management + patient safety + quality + medical physics + technologists

---

Radiology QA: RADPEER + discrepancy review + just culture. Process + outcome metrics. ACR accreditation + MQSA + MIPS. AI-assisted error detection. Multidisciplinary tumor boards + safety culture + near-miss reporting.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'radiology'
  and scenario = 'Peer review + radiology quality assurance programs';

update public.mcq_questions
set choices = '[{"label":"A","text":"Single specialty discharge"},{"label":"B","text":"Advanced lung cancer integrative care"},{"label":"C","text":"Avoid palliative care"},{"label":"D","text":"Refuse treatment"},{"label":"E","text":"No multidisciplinary"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Advanced lung cancer integrative care: (1) **Multidisciplinary tumor board**: thoracic medical oncology, radiation oncology, thoracic surgery, pulmonology, radiology, pathology, palliative care, social work, nutrition, pharmacy, nursing, interventional radiology/pulmonology; (2) **Imaging staging + restaging**: PET/CT + brain MRI initial; ongoing CT for response (RECIST 1.1), brain MRI for surveillance; (3) **Molecular characterization**: comprehensive genomic profiling (NGS) for all advanced NSCLC — EGFR, ALK, ROS1, BRAF, MET, RET, KRAS G12C, HER2, NTRK; tumor mutational burden (TMB), PD-L1 IHC; liquid biopsy (ctDNA) for monitoring; (4) **Targeted therapy** for driver mutations — superior to chemotherapy: osimertinib for EGFR, alectinib/lorlatinib for ALK, etc.; CNS-active for brain mets; (5) **Immunotherapy** — pembrolizumab, nivolumab, atezolizumab (anti-PD-1/L1) for PD-L1 high or in combination with chemo; durvalumab consolidation after chemoradiation in stage III; (6) **Local therapies**: - **SBRT** for early-stage NSCLC inoperable, oligometastatic disease, brain mets (SRS); - **Surgery** for early stage; - **RFA / cryoablation / microwave** for selected; - **Bronchoscopic interventions** — stenting for airway obstruction, brachytherapy, photodynamic therapy; (7) **Symptom management**: - Pain (multimodal — opioids, adjuvants, IR procedures — celiac plexus block for chest wall pain, vertebroplasty for spine mets); - Dyspnea (opioids, oxygen, fan, treat reversible causes — effusion drainage, malignant airway obstruction); - Cough; - Hemoptysis (bronchoscopic intervention, IR embolization); - Pleural effusion — drainage + indwelling pleural catheter (IPC) or pleurodesis; (8) **Palliative care integration** — concurrent from diagnosis, not ''end of life only'' — improves QOL + may improve survival (Temel 2010); (9) **Advance care planning** — early discussions, repeat conversations; (10) **Survivorship + support**: smoking cessation (even at diagnosis improves outcomes), nutrition, exercise, mental health, financial counseling, support groups; (11) **Family communication**: realistic prognosis + values + goals + grief support; (12) **Hospice when appropriate** (prognosis < 6 mo + comfort focus)

---

Advanced lung cancer: multidisciplinary tumor board. Molecular profiling drives therapy. Targeted + immunotherapy + chemo + local therapy (SBRT, ablation, bronchoscopic). Symptom management + IR procedures. EARLY palliative care integration. Family communication.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'radiology'
  and scenario = 'ผู้ป่วยอายุ 70 ปี advanced NSCLC + multiple complications + family — comprehensive multidisciplinary care';

update public.mcq_questions
set choices = '[{"label":"A","text":"Single specialty"},{"label":"B","text":"Comprehensive heart failure care"},{"label":"C","text":"No team needed"},{"label":"D","text":"Discharge"},{"label":"E","text":"Refuse treatment"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Comprehensive heart failure care: (1) **Multidisciplinary HF clinic / team**: HF cardiologist, primary care, advanced practice nurses, pharmacists, dietitians, social work, palliative care, exercise physiology, mental health, cardiac surgery (when transplant/LVAD), electrophysiology (ICD/CRT), nephrology (cardiorenal); (2) **Imaging**: serial echo (LVEF, dimensions, valves, RV); CMR for etiology + viability; cardiac PET for sarcoid + viability; coronary imaging (ischemic evaluation when appropriate); (3) **GDMT (Guideline-Directed Medical Therapy) — 4 pillars (HFrEF)**: - **ARNI** (sacubitril/valsartan) — preferred over ACEi/ARB (PARADIGM-HF); - **Beta-blocker** — carvedilol, metoprolol succinate, bisoprolol; - **MRA** — spironolactone or eplerenone; - **SGLT2 inhibitor** — dapagliflozin or empagliflozin (DAPA-HF, EMPEROR — benefit even without DM); titrate to target doses; (4) **Additional therapies in selected**: ivabradine (SR + HR > 70 on max BB), hydralazine + nitrates (African Americans or ACEi/ARB intolerance), digoxin (symptoms despite GDMT), vericiguat (worsening HF), omecamtiv mecarbil (severe LV dysfunction); (5) **Device therapy**: - **ICD** primary prevention for LVEF ≤ 35% NYHA II-III on optimal GDMT ≥ 3 months (or LVEF ≤ 30% NYHA I post-MI ≥ 40 days), expected survival > 1 year; - **CRT** for LVEF ≤ 35% + LBBB QRS ≥ 150 ms (or non-LBBB ≥ 150 ms); - **CRT-D** combines both; (6) **Advanced therapies**: - **LVAD** (HeartMate 3) — bridge to transplant or destination therapy in NYHA IIIB-IV refractory; - **Heart transplant** for selected younger patients; - **MitraClip / TEER** for secondary MR (COAPT — selected); (7) **Comorbidity management**: AFib, sleep apnea (CPAP), CKD, anemia + iron deficiency (IV iron — FAIR-HF, AFFIRM-AHF), diabetes (SGLT2i), COPD, depression; (8) **Lifestyle**: low sodium, fluid restriction (cautious), exercise (cardiac rehab — HF-ACTION), weight monitoring (daily weights), avoid NSAIDs; (9) **Patient education + self-management**: medication adherence, symptom recognition, action plans; (10) **Telemedicine + remote monitoring**: implantable hemodynamic monitors (CardioMEMS — CHAMPION trial), weight scales, BP cuffs; (11) **Palliative care + advance care planning** integrated; (12) **Hospice** for end-stage when curative options exhausted

---

HFrEF comprehensive care: multidisciplinary HF clinic. 4 GDMT pillars (ARNI + BB + MRA + SGLT2i). ICD/CRT for selected. LVAD + transplant for refractory. Comorbidity management. Remote monitoring. Palliative care integrated.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'radiology'
  and scenario = 'ผู้ป่วยอายุ 60 ปี chronic HFrEF + multimorbidity — team-based HF care';

update public.mcq_questions
set choices = '[{"label":"A","text":"Discharge"},{"label":"B","text":"Hollow viscus perforation — pneumoperitoneum"},{"label":"C","text":"X-ray sufficient diagnosis alone"},{"label":"D","text":"Observation always"},{"label":"E","text":"Single specialty"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Hollow viscus perforation — pneumoperitoneum: (1) **Imaging features**: - **Upright CXR**: free air under right hemidiaphragm (most sensitive view — left obscured by gastric bubble); detects as little as 1-2 mL; - **Left lateral decubitus** alternative for unable-to-stand patient; - **CT abdomen-pelvis with IV contrast**: most sensitive — tiny pneumoperitoneum (extraluminal gas adjacent to perforation), focal bowel wall thickening + discontinuity, focal fat stranding, fluid collections, contrast extravasation; (2) **Etiology**: peptic ulcer perforation (anterior duodenal — most common; gastric), diverticulitis perforation, malignancy perforation, ischemic bowel, foreign body, post-procedure (post-endoscopy/colonoscopy, post-laparoscopy retained air normal up to several days), trauma, iatrogenic; (3) **Localizing signs CT**: - Foregut perforation — air anterior/around stomach/duodenum; - Mid/hindgut — pericolic abscess + free air; - Retroperitoneal perforation — retroperitoneal air (duodenal D2-3, sigmoid posterior); (4) **Sealed vs free perforation**: contained (small focal collection — may manage conservatively in selected — peptic ulcer, diverticulitis), gross peritonitis → emergent surgery; (5) **Management**: - **Resuscitation** — IV fluids, broad-spectrum antibiotics (piperacillin-tazobactam, meropenem for severe; cover Gram-negative + anaerobes), NG decompression, NPO; - **Emergent surgical consultation** — laparotomy / laparoscopy for definitive repair; - **Selective non-operative** — contained perforation (sealed) + clinically stable + appropriate antibiotic coverage + close monitoring (e.g., contained diverticulitis Hinchey I-II, contained peptic perforation with no peritonitis); - **Image-guided drainage** for abscess (Hinchey II); (6) **Multidisciplinary**: ED + general surgery + radiology + IR + critical care

---

Hollow viscus perforation: upright CXR free air under right hemidiaphragm. CT for source + extent. Surgical + IR + IDD management. Selective non-operative for contained. Resuscitate + broad-spectrum antibiotics. Multidisciplinary.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'radiology'
  and scenario = 'ผู้ป่วยอายุ 65 ปี acute severe abdominal pain + peritoneal signs + sepsis — CXR upright พบ subdiaphragmatic free air';

update public.mcq_questions
set choices = '[{"label":"A","text":"Always CT every patient"},{"label":"B","text":"Acute appendicitis imaging — ACR Appropriateness"},{"label":"C","text":"X-ray sufficient"},{"label":"D","text":"Discharge"},{"label":"E","text":"Bone scan"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Acute appendicitis imaging — ACR Appropriateness: (1) **Adult**: - **CT abdomen-pelvis with IV contrast** — first-line, sensitivity + specificity > 95%; findings: dilated appendix > 6 mm, wall thickening + enhancement, fat stranding, appendicolith, abscess, free air (perforation); - **US** alternative in young/thin/pregnant — operator-dependent, sensitivity ~ 80% (less sensitive than CT); positive findings: non-compressible blind-ending tubular structure > 6-7 mm, target sign on cross-section, periappendiceal fat echogenic; (2) **Pregnant women**: **US first** (no radiation); if non-diagnostic → **MRI without gadolinium** (sensitive + no radiation); CT only if MRI not available + clinical concern high; (3) **Pediatric**: **US first** (no radiation, often diagnostic in thin patients); MRI alternative; CT reserved for non-diagnostic US + persistent clinical concern; (4) **Alvarado score** (clinical decision tool) — pre-test probability; high (≥ 7) — surgery without imaging may be appropriate, intermediate — image, low — observe / alternative diagnosis; (5) **Complications imaging**: perforation, abscess (image-guided drainage), peritonitis; (6) **Management**: - **Appendectomy** — laparoscopic preferred (lower wound infection, shorter LOS); - **Antibiotics-first strategy** — controversial but supported by recent trials (CODA, APPAC) for uncomplicated appendicitis — selected patients, with awareness of higher recurrence + appendectomy at 1 year ~ 25-40%; informed shared decision-making; - **Interval appendectomy** after percutaneous drainage of large abscess (Hinchey-like — phlegmon/abscess > 3-4 cm) — usual practice though increasingly questioned by recent data; (7) **Multidisciplinary**: ED + surgery + radiology + pediatrics if children

---

Appendicitis: ACR — adult CT first-line; pregnant US first then MRI; pediatric US first. Surgery laparoscopic standard. Antibiotics-first emerging for uncomplicated (CODA trial). Multidisciplinary.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'radiology'
  and scenario = 'ผู้ป่วยอายุ 25 ปี RLQ pain + fever + N/V + leukocytosis — acute appendicitis suspected

คำถาม: imaging modality choice';

update public.mcq_questions
set choices = '[{"label":"A","text":"X-ray sufficient"},{"label":"B","text":"Small bowel obstruction (SBO) imaging + management"},{"label":"C","text":"Discharge"},{"label":"D","text":"Always surgery first"},{"label":"E","text":"Single specialty"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Small bowel obstruction (SBO) imaging + management: (1) **Imaging findings CT**: dilated proximal small bowel (> 2.5-3 cm) with collapsed distal — transition point identification critical; etiology — adhesions (most common, no mass — bands), hernia (always check ventral + groin), tumor (intussusception in adults often pathologic — mass at lead point), gallstone ileus (pneumobilia + ectopic gallstone — Rigler triad), volvulus (whirl sign — twisted mesentery), foreign body, internal hernia (post-gastric bypass — important DDx); (2) **Severity findings (closed-loop, strangulation, perforation)**: - **Closed-loop obstruction** — radial distribution of dilated loops + whirl sign + mesenteric edema; - **Strangulation** (compromised blood supply) — bowel wall thickening + wall enhancement decreased or absent (key — compare to non-affected loops), pneumatosis intestinalis, portal venous gas, mesenteric edema/haziness, ascites; - **Perforation** — extraluminal gas, focal contrast leak; (3) **CT vs other modalities**: CT IV contrast — gold standard; oral contrast not necessary (delays + may not be tolerated); plain X-ray screen only (limited); US selective; (4) **Management**: - **Stable + uncomplicated (adhesions)** — initial conservative: NG decompression, IV fluids, NPO, electrolyte correction, monitor; ~ 60-80% resolve with conservative care in 24-72 h; **Gastrografin challenge** (water-soluble contrast) — both diagnostic + therapeutic (may resolve adhesive SBO); - **Closed-loop / strangulation / perforation / failure of conservative ≥ 72 h** → emergent surgery; - **Hernia** with incarceration → reduction + repair; - **Tumor / cancer-related** — depends on stage (palliative bypass, stenting in colon, resection); (5) **Large bowel obstruction differs**: most often colon cancer (left-sided) — imaging often CT + colonic decompression via tube/stent often bridge to surgery; sigmoid volvulus (coffee bean sign on X-ray) — decompression via endoscopy + elective surgery; cecal volvulus — surgical (no endoscopic option); (6) **Multidisciplinary**: ED + surgery + radiology + critical care

---

SBO: CT shows transition point + etiology + complications (closed-loop, strangulation). Conservative for stable adhesive (NG, fluids, gastrografin). Surgery for closed-loop/strangulation/failed conservative. LBO often cancer — stent then surgery. Multidisciplinary.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'radiology'
  and scenario = 'ผู้ป่วยอายุ 70 ปี abdominal distension + bilious vomiting + obstipation — CT พบ dilated small bowel loops with transition point + decompressed distal bowel + adhesive band';

update public.mcq_questions
set choices = '[{"label":"A","text":"Discharge"},{"label":"B","text":"Acute cholecystitis — imaging + management"},{"label":"C","text":"X-ray sufficient"},{"label":"D","text":"Delayed surgery weeks later"},{"label":"E","text":"Single specialty"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Acute cholecystitis — imaging + management: (1) **US (first-line per ACR + Tokyo Guidelines)**: gallstones, gallbladder wall thickening > 3 mm, pericholecystic fluid, sonographic Murphy sign (focal tenderness over GB on probe — specific), GB distension, sometimes wall hyperemia on Doppler; sensitivity ~ 88%, specificity ~ 80%; (2) **HIDA scan (cholescintigraphy)**: non-visualization of GB at 4 hours = acute cholecystitis (cystic duct obstruction blocks tracer); sensitivity > 95%; useful when US equivocal or acalculous cholecystitis suspected; (3) **CT** — less sensitive than US but identifies complications + alternative diagnoses (perforation, abscess, gangrenous, emphysematous, mass causing obstruction, Mirizzi syndrome — stone in cystic duct compressing CHD); (4) **MRI/MRCP** — high resolution + non-invasive evaluation of biliary tree; for complications or alternative diagnoses; (5) **Tokyo Guidelines 2018 (TG18)** severity grading: - Grade I (mild) — uncomplicated, healthy patient — early laparoscopic cholecystectomy preferred; - Grade II (moderate) — local complications (gangrene, abscess, peritonitis, > 72h symptoms, marked leukocytosis); - Grade III (severe) — organ dysfunction — antibiotics + drainage (percutaneous cholecystostomy by IR if poor surgical candidate), delayed cholecystectomy; (6) **Management**: NPO + IV fluids + antibiotics (ceftriaxone + metronidazole or piperacillin-tazobactam); early laparoscopic cholecystectomy (within 72 hours — ChoCo, ACDC trials); percutaneous cholecystostomy alternative for high-risk surgical candidates; (7) **Complications**: gangrene, perforation, emphysematous cholecystitis (diabetes — clostridial), Mirizzi syndrome, cholecystoenteric fistula → gallstone ileus; (8) **Acalculous cholecystitis** — critically ill, elderly, post-op, fasting — HIDA helpful; high mortality — percutaneous cholecystostomy often initial; (9) **Multidisciplinary**: ED + surgery + radiology + IR + GI

---

Acute cholecystitis: US first-line. HIDA when equivocal/acalculous. CT for complications. Tokyo Guidelines severity grading. Early laparoscopic cholecystectomy (< 72h). Percutaneous cholecystostomy by IR for high-risk. Multidisciplinary.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'radiology'
  and scenario = 'ผู้ป่วยอายุ 55 ปี F + obese + acute RUQ pain + fever + Murphy sign + leukocytosis — acute cholecystitis suspected';

update public.mcq_questions
set choices = '[{"label":"A","text":"X-ray sufficient"},{"label":"B","text":"Choledocholithiasis + biliary obstruction imaging"},{"label":"C","text":"Discharge"},{"label":"D","text":"Surgery always before ERCP"},{"label":"E","text":"Single specialty"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Choledocholithiasis + biliary obstruction imaging: (1) **Imaging algorithm per ASGE risk stratification**: - **High probability** (CBD stone visualized on US, cholangitis, bilirubin > 4 mg/dL with CBD > 6 mm) — ERCP directly for diagnosis + therapy; - **Intermediate probability** — MRCP or EUS first → ERCP if positive; - **Low probability** — imaging or operative cholangiography during cholecystectomy; (2) **Modalities**: - **US** — initial: gallstones, CBD dilation (> 6 mm post-cholecystectomy normal, > 8 mm elderly, > 4-6 mm typical reference); stones may not be visible in CBD (overlying bowel gas); - **MRCP (magnetic resonance cholangiopancreatography)** — non-invasive: T2-weighted thick-slab images of biliary + pancreatic ducts; high sensitivity for stones (~ 90%); excellent anatomic detail; - **EUS (endoscopic ultrasound)** — sensitive for distal CBD stones, ampullary lesions, small stones (< 5 mm); - **ERCP** — diagnostic + therapeutic (stone extraction via sphincterotomy + balloon/basket); risks — pancreatitis (5-10%, mitigated by rectal indomethacin), bleeding, perforation, cholangitis; (3) **Cholangitis** (Charcot triad — fever + jaundice + RUQ pain; Reynolds pentad adds hypotension + AMS) — surgical emergency: emergent ERCP for biliary decompression (within 24h, sooner if Reynolds pentad); broad-spectrum antibiotics; resuscitation; (4) **Cholecystocholedocholithiasis** — stones in both GB + CBD: ERCP first to clear CBD + sphincterotomy, then laparoscopic cholecystectomy (preferably same admission per Lancet Cholgate trial); alternative: laparoscopic cholecystectomy + intraoperative cholangiogram + CBD exploration; (5) **Mirizzi syndrome** — stone impacted in cystic duct/Hartmann pouch compressing CHD — variable management (open conversion may be needed); (6) **Multidisciplinary**: GI + surgery + radiology + IR (when ERCP fails — percutaneous transhepatic cholangiography PTC drainage)

---

Choledocholithiasis: US first; MRCP or EUS for intermediate risk; ERCP for high risk (Dx + therapy). Cholangitis = emergency — ERCP < 24h + antibiotics. Cholecystocholedocholithiasis = ERCP + cholecystectomy same admission. PTC if ERCP fails.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'radiology'
  and scenario = 'ผู้ป่วยอายุ 60 ปี jaundice + RUQ pain + dilated CBD on US + elevated bilirubin — choledocholithiasis suspected — MRCP confirms';

update public.mcq_questions
set choices = '[{"label":"A","text":"Always CT on admission"},{"label":"B","text":"Acute pancreatitis — Atlanta 2012 + imaging"},{"label":"C","text":"Discharge"},{"label":"D","text":"Antibiotics for all"},{"label":"E","text":"Single specialty"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Acute pancreatitis — Atlanta 2012 + imaging: (1) **Atlanta 2012 classification**: - **Interstitial edematous pancreatitis (80%)**: parenchymal enhancement preserved, peripancreatic edema/fat stranding, no necrosis; - **Necrotizing pancreatitis (20%)**: non-enhancing pancreatic tissue ± peripancreatic necrosis; **higher complication + mortality**; - **Complications**: acute peripancreatic fluid collection (APFC < 4 weeks, no wall), pseudocyst (> 4 weeks, defined wall, no solid debris), acute necrotic collection (ANC < 4 wks, heterogeneous), walled-off necrosis (WON > 4 wks, encapsulated necrosis); (2) **CT timing**: - **NOT routine on admission** — diagnosis is clinical + lab (lipase > 3× ULN); CT on day 1 may underestimate necrosis; - **CT abdomen-pelvis with IV contrast at 72 hours (or earlier if clinical deterioration)** — accurate necrosis assessment, complications, CTSI (CT severity index — Balthazar), Modified CTSI; - **Earlier CT if alternative diagnosis suspected** or unclear; - **MRCP** in selected (biliary pancreatitis with persistent obstruction); (3) **US** — initial workup for **etiology** — gallstones (most common cause acute pancreatitis worldwide), CBD dilation; (4) **Etiology workup**: gallstones (US — most common), alcohol (history), hypertriglyceridemia (> 1000 mg/dL — TGs trigger), hypercalcemia, post-ERCP, drugs (azathioprine, valproate, GLP-1 agonists controversial), trauma, autoimmune (AIP — IgG4), genetic (PRSS1, SPINK1), idiopathic; (5) **Severity assessment**: BISAP, APACHE II, Atlanta severity (mild, moderate, severe with persistent organ failure > 48h); (6) **Management**: - **Aggressive fluid resuscitation** initially (recent evidence — moderate not aggressive may be better per WATERFALL trial 2022 — Ringer lactate 1.5 mL/kg/h after bolus); - **Pain control**, antiemetics, early enteral feeding (within 72h — no NPO unless severe ileus); - **Gallstone pancreatitis** — ERCP for cholangitis or persistent obstruction within 24-72h; cholecystectomy same admission for mild gallstone pancreatitis; - **Antibiotics ONLY for infected necrosis** (NOT prophylactic — no benefit); diagnosis by FNA culture or clinical deterioration; - **Infected necrosis** — step-up approach (percutaneous drainage → minimally invasive necrosectomy → open) — PANTER trial; endoscopic transluminal drainage emerging; - **Pseudocyst** — drain if symptomatic, infected, > 5-6 cm persistent — endoscopic (EUS-guided) preferred; (7) **Multidisciplinary**: GI + general surgery + IR + radiology + critical care + nutrition + endocrinology (post-pancreatitis DM)

---

Acute pancreatitis: clinical + lab Dx. CT at 72h for necrosis (not admission). MRCP for biliary. Aggressive (moderate) fluids. ERCP for gallstone + cholangitis. Antibiotics ONLY infected necrosis. Step-up approach for necrosis. Multidisciplinary.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'radiology'
  and scenario = 'ผู้ป่วยอายุ 50 ปี severe epigastric pain radiating to back + N/V + elevated lipase 5× ULN — acute pancreatitis confirmed clinically + lab

คำถาม: role of imaging';

update public.mcq_questions
set choices = '[{"label":"A","text":"X-ray sufficient"},{"label":"B","text":"Acute diverticulitis — Hinchey classification + imaging"},{"label":"C","text":"Discharge no follow-up"},{"label":"D","text":"Always surgery"},{"label":"E","text":"Single specialty"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Acute diverticulitis — Hinchey classification + imaging: (1) **CT** — gold standard: sigmoid wall thickening, pericolic fat stranding, diverticula, abscess, free air, free fluid, distant complications; (2) **Hinchey classification**: - **I**: pericolic abscess (Ia phlegmon, Ib < 4 cm); - **II**: pelvic/distant abscess (≥ 4 cm); - **III**: purulent peritonitis; - **IV**: feculent peritonitis; (3) **Modified Hinchey + radiologic classification (Wasvary)**: more granular for treatment decisions; (4) **Management by severity**: - **Uncomplicated (Hinchey 0/Ia phlegmon)** — outpatient management trial in selected (per AGA 2015) — antibiotics may not be required (DIABOLO + AVOD trials in Europe showed no benefit of antibiotics for uncomplicated — paradigm shift); - **Complicated**: - Ib (abscess < 4 cm) — IV antibiotics, often resolves; - II (abscess ≥ 4 cm) — IV antibiotics + percutaneous drainage by IR; - III-IV — emergency surgery (Hartmann''s procedure or laparoscopic lavage in selected, primary anastomosis with diverting ileostomy increasingly); (5) **Antibiotics** when used: cover gram-negative + anaerobes (ciprofloxacin + metronidazole outpatient; piperacillin-tazobactam inpatient); (6) **Follow-up colonoscopy** — 6-8 weeks after acute episode in selected (rule out cancer — incidence ~ 1-2%) — recent evidence — selective (not all patients per ASCRS); (7) **Elective surgery** for: recurrent (≥ 2 episodes traditionally, now individualized — quality of life, complications, immunocompromised), complicated (fistula, stenosis, persistent abscess); (8) **Complications**: fistulae (colovesical — pneumaturia, fecaluria; colovaginal — vaginal discharge), stricture, perforation, bleeding; (9) **Right-sided diverticulitis** more common in Asian populations — often Mecillinam-treated; (10) **Multidisciplinary**: ED + surgery + radiology + IR + GI

---

Diverticulitis: CT + Hinchey classification. Uncomplicated — antibiotics may not be needed (DIABOLO/AVOD). Abscess > 4 cm — IR drainage. Peritonitis — surgery. Colonoscopy 6-8 wks selectively. Elective surgery individualized. Multidisciplinary.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'radiology'
  and scenario = 'ผู้ป่วยอายุ 65 ปี LLQ pain + fever + leukocytosis — CT พบ sigmoid wall thickening + pericolic fat stranding + small pericolic abscess 2 cm — diverticulitis with abscess (Hinchey Ib)';

update public.mcq_questions
set choices = '[{"label":"A","text":"Discharge"},{"label":"B","text":"Acute mesenteric ischemia (AMI) — high mortality + delayed diagnosis common"},{"label":"C","text":"X-ray sufficient"},{"label":"D","text":"Observation only"},{"label":"E","text":"Single specialty"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Acute mesenteric ischemia (AMI) — high mortality + delayed diagnosis common: (1) **Etiologies** (Brunt classification): - **Arterial embolic (50%)**: AFib, recent MI (mural thrombus), endocarditis — typically SMA mid-segment; sudden onset, severe pain out of proportion; - **Arterial thrombotic (15-25%)**: atherosclerotic plaque rupture, usually history of chronic mesenteric ischemia symptoms (postprandial pain, weight loss, food fear); - **Non-occlusive mesenteric ischemia (NOMI) (20-30%)**: low-flow state (shock, sepsis, cardiac failure, vasoconstrictors); - **Venous thrombosis (5-15%)**: hypercoagulable, portal HTN, malignancy, pancreatitis, inflammatory; (2) **Imaging**: - **CT angiography (CTA) — first-line**: arterial occlusion / thrombus, bowel wall changes (early — thickening with hyperemia; late — pneumatosis intestinalis, portal venous gas, lack of mucosal enhancement, hypoperfusion, bowel dilation), mesenteric edema, ascites, infarction signs; - **MR angiography** alternative; - **DSA** for selected — diagnostic + therapeutic; - Lab — lactic acidosis (late), D-dimer elevated (non-specific); (3) **Management — time-critical**: - **Resuscitation** — aggressive fluids, correct acidosis, hemodynamic support; - **Heparin anticoagulation**; - **Broad-spectrum antibiotics**; - **Emergent surgery** for peritonitis, infarction, perforation — explore + resect non-viable bowel, second-look laparotomy if borderline; - **Endovascular therapy** for arterial occlusions: catheter thrombolysis, mechanical thrombectomy, stenting (SMA); selected — early without peritonitis; - **NOMI** — improve hemodynamics + intra-arterial papaverine infusion (vasodilator); - **Venous thrombosis** — anticoagulation primary; surgery if peritonitis; (4) **Outcomes** — early diagnosis + revascularization (< 6 hours from onset) critical; mortality 50-80% historically, improved with endovascular era; (5) **Chronic mesenteric ischemia (CMI)** — chronic atherosclerosis of mesenteric arteries — postprandial pain, weight loss; CTA + DSA; revascularization (stenting preferred over open bypass for most); (6) **Multidisciplinary**: vascular surgery + IR + general surgery + GI + critical care + radiology

---

AMI: pain out of proportion + lactic acidosis + AFib. CTA first-line. Heparin + resuscitation + emergent surgery for peritonitis; endovascular for selected without peritonitis. Time-critical (< 6h). NOMI — improve hemodynamics. Multidisciplinary.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'radiology'
  and scenario = 'ผู้ป่วยอายุ 75 ปี AFib not on anticoagulant + acute severe abdominal pain out of proportion to exam + lactic acidosis — acute mesenteric ischemia (AMI) suspected';

update public.mcq_questions
set choices = '[{"label":"A","text":"Biopsy mandatory before treatment"},{"label":"B","text":"HCC — LI-RADS classification + management"},{"label":"C","text":"Discharge"},{"label":"D","text":"Single specialty"},{"label":"E","text":"X-ray sufficient"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** HCC — LI-RADS classification + management: (1) **LI-RADS** standardized reporting for HCC: - **LR-1**: definitely benign; - **LR-2**: probably benign; - **LR-3**: intermediate probability; - **LR-4**: probably HCC; - **LR-5**: **DEFINITELY HCC** (≥ 10 mm, arterial-phase hyperenhancement + ≥ 1 of: washout, capsule, threshold growth) — pathognomonic in cirrhotic context, biopsy NOT required; - **LR-M**: malignant non-HCC (e.g., cholangiocarcinoma); - **LR-TIV**: tumor in vein; (2) **Major imaging features for HCC**: - Arterial-phase hyperenhancement (APHE) — non-rim hyperenhancement; - Washout — relative hypoenhancement compared to liver in portal venous or delayed phase; - Capsule — peripheral rim of enhancement; - Threshold growth — ≥ 50% increase in 6 months or new ≥ 10 mm; (3) **Surveillance**: cirrhotic + high-risk chronic HBV (Asian males > 40, Asian females > 50, African > 20, family history HCC) — US ± AFP q6 months; CT/MRI if US inadequate (obese, fatty liver); (4) **Staging**: BCLC (Barcelona Clinic Liver Cancer): - 0/A — early — curative options (resection, transplant, ablation); - B — intermediate — TACE; - C — advanced (vascular invasion or extrahepatic spread) — systemic; - D — terminal — best supportive care; (5) **Treatment options**: - **Resection** — well-compensated cirrhosis (Child-Pugh A), no portal HTN, single tumor; - **Transplant** — within Milan criteria (single < 5 cm or up to 3 lesions all < 3 cm, no vascular invasion) — only definitive cure for cirrhosis + HCC; UCSF + downstaging expanding criteria; - **Locoregional therapies**: ablation (RFA, MWA) for ≤ 3 cm; **TACE** (transarterial chemoembolization) for intermediate stage; **TARE** (Y-90 radioembolization) — also for selected; - **Systemic**: atezolizumab + bevacizumab (IMbrave150 — improved OS vs sorafenib first-line); pembrolizumab + lenvatinib; lenvatinib; sorafenib; tremelimumab + durvalumab (HIMALAYA); (6) **Multidisciplinary HCC tumor board**: hepatology + transplant surgery + medical oncology + IR + radiation oncology + radiology + pathology + nursing + palliative care

---

HCC: LI-RADS LR-5 in cirrhotic context = HCC, no biopsy needed. Arterial enhancement + washout + capsule + threshold growth. BCLC staging guides treatment (resection, transplant Milan, ablation, TACE, systemic). Atezo + bev first-line systemic. Multidisciplinary tumor board.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'radiology'
  and scenario = 'ผู้ป่วยอายุ 55 ปี cirrhosis HCV + AFP rising — surveillance MRI พบ 3 cm hyperenhancing arterial-phase nodule with washout in portal venous + capsule — LI-RADS classification';

update public.mcq_questions
set choices = '[{"label":"A","text":"Hospice immediately"},{"label":"B","text":"Colorectal liver metastases (CRLM) — multimodal"},{"label":"C","text":"Single specialty"},{"label":"D","text":"Discharge"},{"label":"E","text":"Refuse"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Colorectal liver metastases (CRLM) — multimodal: (1) **Imaging**: - **CT chest-abdomen-pelvis with IV contrast (portal venous phase)** — staging modality of choice for CRC; - **MRI liver with hepatocyte-specific contrast (Eovist/Primovist, gadoxetate)** — superior for detecting + characterizing liver lesions, distinguishing FNH/adenoma/HCC/mets, in steatotic liver; recommended for surgical planning of liver mets resection (changes management ~ 20-30%); - **PET/CT** — when extra-hepatic disease changes management (pre-resection of CRLM); not sensitive for small or mucinous mets; (2) **Resectability assessment**: - Sufficient future liver remnant (FLR) > 25-30% normal liver, > 30-40% chemo-injured, > 40% cirrhotic; - Adequate vascular inflow + outflow; - Negative margins achievable; - Acceptable performance status; - Synchronous primary — concurrent vs staged resection (multidisciplinary decision); (3) **Multidisciplinary tumor board** essential — paradigm change with effective systemic therapy + advanced techniques; many initially ''unresectable'' downstaged to resectable; (4) **Resectability conversion strategies**: - **Chemotherapy** (FOLFOX/FOLFIRI ± biologics) — convert ~ 15-20% to resectable; - **Portal vein embolization (PVE) by IR** — induces FLR hypertrophy ~ 30% in 4-6 weeks before extended resection; - **ALPPS** (associating liver partition + portal vein ligation for staged hepatectomy) — selected; - **Ablation** for unresectable small lesions; - **Hepatic arterial infusion chemotherapy (HAIC)** — pump-based, selected centers; (5) **Locoregional therapies for unresectable CRLM**: ablation (RFA, MWA) for small (< 3 cm); TARE (Y-90 radioembolization); HAIC; (6) **Systemic therapy**: - First-line FOLFOX or FOLFIRI; biologics — bevacizumab (anti-VEGF — for all) vs anti-EGFR (cetuximab, panitumumab — only RAS/BRAF wild-type left-sided); - Second-line crossover; immunotherapy for MSI-H (pembrolizumab, ipi-nivo); KRAS G12C inhibitors emerging; (7) **Survival in resected CRLM** — 5-year ~ 40-50% (~ 25-30% cured); vs 20% with chemotherapy alone — multimodal critical; (8) **Multidisciplinary**: hepatobiliary surgery + medical oncology + IR + radiation oncology + radiology + pathology + nursing + palliative care

---

CRLM: CT staging + MRI liver hepatocyte-specific contrast for surgical planning. PET/CT selectively. Resectability assessment FLR. PVE/ALPPS to enlarge FLR. Convert with chemo. Ablation + TARE for selected. 5-yr survival 40-50% in resected. Multidisciplinary tumor board.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'radiology'
  and scenario = 'ผู้ป่วยอายุ 65 ปี colorectal cancer + liver mets on staging CT — workup + management';

commit;
