-- ===============================================================
-- UPDATE chunk 3/8: radiology (25 questions)
-- ===============================================================

begin;

update public.mcq_questions
set choices = '[{"label":"A","text":"AVM — embolize"},{"label":"B","text":"Cerebral cavernous malformation (cavernoma)"},{"label":"C","text":"Tumor — biopsy"},{"label":"D","text":"Stroke"},{"label":"E","text":"Discharge"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Cerebral cavernous malformation (cavernoma): (1) **Imaging characteristic**: ''popcorn'' appearance — heterogeneous mixed-signal core (different ages of blood products on T1 + T2 — methemoglobin, deoxyhemoglobin), surrounding rim of hemosiderin (low signal on T2 + GRE/SWI — ''blooming''); **GRE / SWI ESSENTIAL** — most sensitive for hemosiderin + multiple lesions detection; (2) **Differential**: cavernoma (popcorn + hemosiderin rim, NO early enhancement), AVM (high flow, contrast enhancement, vascular nidus), hemorrhagic neoplasm (mass effect, edema), developmental venous anomaly (DVA — caput medusae, often co-exists with cavernoma), micro-hemorrhages of CAA (elderly, lobar, no popcorn appearance); (3) **DSA — typically negative** (low flow lesion) — distinguishes from AVM; (4) **Familial CCM** (KRIT1, CCM2, CCM3 mutations) — multiple lesions, autosomal dominant — genetic counseling; (5) **Hemorrhage risk**: 0.5-2% per year (untreated, supratentorial), higher in brainstem, prior hemorrhage, infratentorial location, deep venous drainage; (6) **Management**: - Asymptomatic incidental → observation + serial MRI; - **Seizures controlled with AED** + observation if surgically inaccessible; - **Surgical resection** for: recurrent symptomatic hemorrhage, drug-resistant epilepsy attributable to cavernoma, severe progressive neuro deficit, accessible location (avoid eloquent cortex/brainstem unless absolutely needed); - **SRS** controversial — not first-line, some role for inaccessible recurrent bleeders; (7) **Multidisciplinary**: neurology + neurosurgery + radiology + genetics if familial

---

Cavernoma: ''popcorn'' + hemosiderin rim on GRE/SWI. DSA negative (vs AVM). Familial CCM (multiple). Surgery for symptomatic accessible; SRS controversial. Multidisciplinary.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'radiology'
  and scenario = 'ผู้ป่วยอายุ 50 ปี new-onset seizure — MRI พบ popcorn-appearance lesion with mixed signal (T2 hyperintense center, T2 hypointense rim — hemosiderin) without surrounding edema';

update public.mcq_questions
set choices = '[{"label":"A","text":"Likely migraine"},{"label":"B","text":"Primary CNS vasculitis (PACNS) — imaging + workup"},{"label":"C","text":"Stroke - aspirin"},{"label":"D","text":"Discharge"},{"label":"E","text":"Single specialty"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Primary CNS vasculitis (PACNS) — imaging + workup: (1) **Imaging features**: multiple infarcts in different vascular territories (suggests systemic embolic source vs vasculitis if no cardiac source), segmental narrowing + dilatation (''beading'') on MRA/CTA/DSA — vessel caliber irregularity, gadolinium enhancement of vessel wall on high-resolution vessel wall MRI (modern technique — distinguishes from RCVS, atherosclerosis), parenchymal contrast enhancement (granulomatous form), microhemorrhages on SWI; (2) **DSA** gold standard for angiographic findings — but limited sensitivity (< 60%) for small-vessel PACNS, low specificity (atherosclerosis, RCVS, infectious vasculitis, vasospasm look similar); high-resolution vessel wall MRI helps differentiate (PACNS — concentric thickening + enhancement; RCVS — minimal/no wall enhancement; atherosclerosis — eccentric); (3) **Workup to exclude mimics**: - CSF — lymphocytic pleocytosis, elevated protein common in PACNS (helps distinguish from RCVS, atherosclerosis); - Serology — ANA, ANCA, RF, CCP, dsDNA, complement, cryoglobulins, HIV, syphilis (RPR), hepatitis serologies, ESR, CRP (PACNS — systemic markers usually normal!); - Echo + telemetry — exclude embolic source; - **Brain biopsy** — gold standard for PACNS diagnosis (granulomatous, lymphocytic, or necrotizing) but invasive; reserved for atypical / severe / progressive cases with negative workup; (4) **Differential**: RCVS (reversible cerebral vasoconstriction — thunderclap HA, postpartum, vasoactive substances, resolves in 1-3 months), systemic vasculitis with CNS involvement (GPA, EGPA, PAN, Behcet), infectious vasculitis (VZV, syphilis, TB), atherosclerosis, Moyamoya, lymphoma; (5) **Treatment** (if PACNS confirmed): high-dose steroids + cyclophosphamide induction (rituximab alternative), maintenance with MTX/azathioprine/MMF; (6) **Multidisciplinary**: rheumatology + neurology + neuroradiology

---

PACNS: multiple infarcts + beading on angiogram. High-res vessel wall MRI helps differentiate from RCVS. Brain biopsy gold standard. Steroids + cyclophosphamide. Exclude mimics. Multidisciplinary.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'radiology'
  and scenario = 'ผู้ป่วยอายุ 40 ปี recurrent stroke + headache + cognitive decline — MRI พบ multiple infarcts in different vascular territories + segmental beading on MRA + CSF lymphocytic pleocytosis';

update public.mcq_questions
set choices = '[{"label":"A","text":"Single sequence sufficient"},{"label":"B","text":"MRI brain sequences — clinical applications"},{"label":"C","text":"X-ray only"},{"label":"D","text":"CT only"},{"label":"E","text":"No imaging"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** MRI brain sequences — clinical applications: (1) **T1-weighted**: anatomy, fat bright, fluid (CSF) dark, gray matter darker than white matter; post-contrast (gadolinium) — enhancement reflects BBB breakdown (tumor, infection, demyelination active, vascular); (2) **T2-weighted**: pathology bright (edema, gliosis, demyelination, tumor); CSF bright; differentiate gray/white matter; (3) **FLAIR (Fluid Attenuated Inversion Recovery)**: suppresses CSF — periventricular + cortical lesions seen better than T2 (MS plaques, subarachnoid blood, infection); (4) **DWI (diffusion-weighted imaging)** + ADC map: restricted diffusion — bright DWI + dark ADC — acute ischemia (within minutes — hyperacute marker), abscess (pus restricts), hypercellular tumor (lymphoma, GBM, epidermoid — bright on DWI), early stroke; (5) **GRE (gradient echo) / SWI (susceptibility-weighted)**: blood products (hemosiderin, deoxyhemoglobin), calcification, iron — micro-hemorrhages (CAA, hypertensive, DAI), cavernoma, hemorrhagic stroke; SWI more sensitive than GRE; (6) **MR angiography (MRA)**: TOF (no contrast) — flow imaging; contrast-enhanced MRA (gadolinium); MR venography (MRV) for venous; (7) **MR perfusion (PWI)**: CBV, CBF, MTT — penumbra in stroke, tumor grading (high rCBV = high-grade glioma); (8) **MR spectroscopy (MRS)**: metabolites — NAA (neuronal), choline (cell turnover — increased in tumors), creatine (energy), lactate (anaerobic), lipid (necrosis); (9) **DTI (diffusion tensor)**: white matter tracts for surgical planning; (10) **Functional MRI (fMRI)**: BOLD signal — language + motor mapping pre-op

---

MRI sequences: T1 (anatomy + contrast), T2 (edema), FLAIR (CSF-suppressed), DWI (stroke + abscess + cellular tumor), GRE/SWI (hemorrhage), MRA (vessels), perfusion, spectroscopy, DTI, fMRI. Tailor sequences to question.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'radiology'
  and scenario = 'MRI brain sequences — แต่ละ sequence เหมาะกับ pathology ใด

คำถาม: characteristics + indications';

update public.mcq_questions
set choices = '[{"label":"A","text":"No standard values"},{"label":"B","text":"Hounsfield Units (HU) — CT density values calibrated water = 0, air = -1000, dense bone = +1000+"},{"label":"C","text":"All tissues same HU"},{"label":"D","text":"Bone is negative HU"},{"label":"E","text":"Air positive HU"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Hounsfield Units (HU) — CT density values calibrated water = 0, air = -1000, dense bone = +1000+: (1) **Brain CT typical HU values**: - Air: -1000; - Fat: -100 to -50; - Water/CSF: 0; - White matter: 22-32 HU (slightly lower than gray); - Gray matter: 32-44 HU; - Acute blood: 50-80 HU (hyperdense); - Subacute blood: 30-40 HU (isodense, easier to miss); - Chronic blood/old hemorrhage: 0-30 HU (hypodense); - Calcification: > 100-200+ HU; - Cortical bone: > 1000 HU; (2) **Clinical pearls**: - Hyperdense MCA sign — thrombus 70-90 HU vs normal vessel 35-50 HU; - Loss of gray-white differentiation in acute ischemia (gray matter HU drops toward white matter); - Acute ICH is hyperdense (clot retraction) — fresh blood; over days becomes isodense then hypodense (rim); - Subdural hematoma: acute hyperdense → subacute isodense (~ 1-3 weeks — easy to miss, look for mass effect) → chronic hypodense; mixed-density suggests acute on chronic or active bleeding; - Contrast extravasation in trauma — 80-200 HU dependent on phase; (3) **CT brain window**: brain window (level 35, width 80) for parenchyma; bone window for skull fractures; subdural window (level 75, width 200) for thin hyperdense SDH along skull

---

HU: water 0, air -1000, bone +1000. Brain parenchyma 20-40, acute blood 50-80, calcification > 100, fat negative. Subacute SDH isodense — easy to miss. Use windows appropriately.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'radiology'
  and scenario = 'Hounsfield units (HU) on CT — typical values for brain pathology

คำถาม: HU value differences across tissues';

update public.mcq_questions
set choices = '[{"label":"A","text":"Plain X-ray sufficient"},{"label":"B","text":"Advanced MRI for neurosurgical planning"},{"label":"C","text":"No advanced imaging"},{"label":"D","text":"CT alone"},{"label":"E","text":"Bone scan"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Advanced MRI for neurosurgical planning: (1) **fMRI (BOLD signal — Blood Oxygen Level Dependent)**: detects changes in deoxyhemoglobin during neuronal activity; - **Task-based fMRI**: patient performs task (finger tapping, language) during scan — localizes motor cortex, language (Broca, Wernicke), visual areas; - **Resting-state fMRI**: networks (default mode, salience, attention) identified without task — useful when patient can''t cooperate; (2) **Clinical applications**: - Pre-op localization of eloquent cortex for tumor resection planning — maximizes safe resection extent while preserving function; - Pre-op for epilepsy surgery — language lateralization (alternative to Wada test), seizure focus characterization; - Stroke recovery monitoring; (3) **DTI (Diffusion Tensor Imaging)** + tractography: directionality of water diffusion along white matter tracts (anisotropic) — visualizes white matter pathways (corticospinal tract, arcuate fasciculus, optic radiations); (4) **Clinical applications DTI**: - Pre-op tract mapping — tumor relationship to corticospinal tract, language tracts, visual pathways; - Stroke/TBI — Wallerian degeneration assessment; - Connectome research; (5) **Integration with intraoperative**: fMRI/DTI fused with stereotactic neuronavigation + intraoperative awake mapping (direct cortical stimulation) = modern brain tumor surgery; (6) **Limitations**: BOLD signal altered near tumors (neurovascular uncoupling), patient cooperation needed for task-based, motion artifacts; (7) **Multidisciplinary**: neurosurgery + neuroradiology + neuropsychology + speech therapy

---

fMRI (BOLD) + DTI (tractography) for pre-op brain tumor planning — eloquent cortex + white matter tracts. Maximizes safe resection. Integrated with intraoperative awake mapping + neuronavigation.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'radiology'
  and scenario = 'Functional MRI (fMRI) + diffusion tensor imaging (DTI) — applications in brain tumor pre-op planning';

update public.mcq_questions
set choices = '[{"label":"A","text":"Always safe — no precautions"},{"label":"B","text":"Gadolinium-based contrast agents (GBCAs) — safety"},{"label":"C","text":"Discharge without screening"},{"label":"D","text":"Contraindicated in everyone"},{"label":"E","text":"Same as iodinated contrast"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Gadolinium-based contrast agents (GBCAs) — safety: (1) **NSF (nephrogenic systemic fibrosis)** — rare but severe fibrosing disorder of skin + organs in patients with severe renal impairment (eGFR < 30) exposed to GBCAs, especially older linear (non-ionic) agents (gadodiamide — Omniscan, gadoversetamide); (2) **Risk stratification by group**: - **Group I (high-risk linear)** — restricted in CKD; - **Group II (macrocyclic — stable)** — gadobutrol (Gadavist), gadoteridol (ProHance), gadoterate (Dotarem) — very low NSF risk, used preferentially; - **Group III (linear stable)**: gadoxetate (Eovist — liver-specific); (3) **ACR + Manufacturer recommendations**: screening for renal function (eGFR or GFR estimate) before GBCA in at-risk patients (CKD, dialysis, AKI, > 60 years, DM, HTN); macrocyclic agents (Group II) preferred — many institutions use only Group II; in dialysis patients on Group II → dialysis after exam may help clear contrast (does not eliminate NSF risk per recent guidelines but commonly practiced); (4) **Gadolinium retention in brain (dentate nucleus, globus pallidus)** — linear > macrocyclic; clinical significance uncertain but FDA warning 2017; preference for macrocyclic; (5) **Allergic reactions**: less common than iodinated CT contrast; treat similarly (epinephrine, antihistamine, steroids); premedication for known prior reaction; (6) **Pregnancy**: GBCAs cross placenta — only if essential, no alternative, benefits outweigh risk (ACR not contraindicated absolutely); (7) **Breastfeeding**: ACR — continue breastfeeding (minimal transfer); (8) **Pediatric**: lower doses, weight-based; macrocyclic preferred

---

GBCAs: NSF risk in CKD eGFR < 30 — linear agents higher risk; macrocyclic Group II preferred. Renal screening before. Brain retention noted (clinical significance uncertain). Allergic reactions less common than iodinated.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'radiology'
  and scenario = 'Gadolinium contrast — safety considerations + nephrogenic systemic fibrosis (NSF)';

update public.mcq_questions
set choices = '[{"label":"A","text":"Email only"},{"label":"B","text":"Critical findings communication — ACR + IOM standards"},{"label":"C","text":"Defer to next day"},{"label":"D","text":"No direct contact needed"},{"label":"E","text":"Discharge"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Critical findings communication — ACR + IOM standards: (1) **Critical / actionable findings** require direct communication beyond report: imminent life-threatening (pneumothorax under tension, free air, pulmonary embolism, AAA leak, ICH, stroke, acute aortic dissection, fracture risking instability, ectopic pregnancy), urgent (new mass, fracture, abscess); (2) **ACR Practice Parameter for Communication of Diagnostic Imaging Findings (2020)**: - **Level 1 (Red — within minutes)**: directly threatens patient survival or limb — call referring provider; document time, person spoken to, content; - **Level 2 (Orange — within hours)**: requires medical attention to avoid significant morbidity — phone/secure messaging; - **Level 3 (Yellow — within days)**: requires follow-up but not emergent — automated alerts, secure portals, follow-up systems; (3) **Methods**: phone call (most reliable for Level 1), secure messaging, EHR alerts, closed-loop communication confirming receipt; (4) **Documentation in report + audit trail**: when, how, who, content; (5) **Closing the loop**: tracking + follow-up systems for incidental findings (lung nodules — Fleischner, adnexal cysts, etc.) — avoid ''fall through cracks''; (6) **Safety culture**: blame-free reporting of near misses; (7) **Modern tools**: AI-assisted prioritization of worklists (flag PE/pneumothorax/ICH to top), automated alerts, dashboards, structured reporting; (8) **Multidisciplinary**: radiology + ordering provider + IT + quality + administration; (9) **Standards bodies**: ACR, Joint Commission, ABR; (10) **Continuous improvement**: case reviews, root cause analysis when communication failures lead to harm

---

Critical findings: direct communication required (phone for Level 1). ACR levels Red/Orange/Yellow + timing. Document method + person + content + closed loop. Modern AI-prioritization. Multidisciplinary safety culture.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'radiology'
  and scenario = 'Critical findings communication — radiology workflow + safety

คำถาม: communicating life-threatening findings';

update public.mcq_questions
set choices = '[{"label":"A","text":"No time pressure"},{"label":"B","text":"Stroke imaging quality metrics + DTN"},{"label":"C","text":"Discharge"},{"label":"D","text":"Wait next day"},{"label":"E","text":"Single specialty"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Stroke imaging quality metrics + DTN: (1) **AHA Get With The Guidelines-Stroke (GWTG)** + Joint Commission standards: - **Door-to-CT initiation** ≤ 25 minutes (ideal < 20); - **Door-to-CT interpretation** ≤ 45 minutes; - **Door-to-needle (DTN)** ≤ 60 minutes (target ≤ 45 minutes for highest tier); - **Door-to-groin puncture** for thrombectomy ≤ 90 minutes (≤ 60 minutes ideal); - **Door-in-door-out** for transfers ≤ 120 minutes; (2) **Process improvements proven to reduce DTN** (Target: Stroke campaign): pre-notification by EMS, single-call activation, parallel processes (registration concurrent with imaging), tPA mixing during CT, CT to ED bed reverse flow, point-of-care testing (INR), team meeting at scanner, premixed weight-based tPA dosing; (3) **Comprehensive Stroke Center criteria** vs Primary Stroke Center; (4) **Tele-stroke** expands access — vRobot consultation; (5) **Imaging protocols**: integrated CT + CTA + CTP rapid scan (''one-stop'' acquisition < 5 minutes); standardized post-processing automated (RAPID, Viz.ai, AI-assisted LVO detection); (6) **Multidisciplinary stroke team**: ED + neurology + radiology + IR + neurocritical care + pharmacy + nursing; (7) **Quality reporting**: GWTG, internal dashboards, AHA Stroke Honor Roll; (8) **Outcomes tied to time**: every 15 minutes saved = improved functional outcome (mRS shift); time is brain (1.9 million neurons lost per minute LVO); (9) **Continuous improvement**: monthly stroke team meetings + case review; (10) **Modern**: AI-driven LVO detection, mobile stroke units in some cities, ambulance bypass protocols

---

Stroke imaging metrics: DTN ≤ 60 (target 45), door-to-CT ≤ 25, door-to-groin ≤ 90 minutes. Target: Stroke processes (pre-notification, single-call, parallel processes). AI-assisted LVO detection. Multidisciplinary.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'radiology'
  and scenario = 'Door-to-needle (DTN) + door-to-imaging time for acute stroke — quality metrics';

update public.mcq_questions
set choices = '[{"label":"A","text":"Single specialty discharge"},{"label":"B","text":"Post-stroke integrative care"},{"label":"C","text":"No follow-up"},{"label":"D","text":"Refuse care"},{"label":"E","text":"Hospice immediately"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Post-stroke integrative care: (1) **Acute (24-48 hours)**: ICU/stroke unit monitoring — BP control (post-thrombectomy 140-180 SBP typically — avoid hypoperfusion + hemorrhage), neuro checks, repeat imaging 24h (assess hemorrhagic transformation), dysphagia screen before PO (NPO until cleared — aspiration prevention), DVT prophylaxis; (2) **Sub-acute (days-weeks)**: comprehensive workup for etiology — ECG/Holter for AFib (cryptogenic — extended monitoring 30 days, implantable loop recorder consideration), echo (TTE then TEE if cryptogenic — PFO, LV thrombus, valve, ASD), vessel imaging (carotid + intracranial), labs (lipids, HbA1c, hypercoagulable if young/atypical), CHA2DS2-VASc; (3) **Secondary prevention based on etiology**: - Atherosclerotic — antiplatelet (aspirin/clopidogrel; DAPT × 21-90 days for high-risk minor stroke per CHANCE/POINT/SOCRATES), high-intensity statin (target LDL < 70), BP control (< 130/80), DM, smoking cessation; - Cardioembolic (AFib) — anticoagulation (DOAC preferred or warfarin); - Other (PFO, dissection, hypercoagulable) — individualized; (4) **Rehabilitation** early + intensive: PT (gait, balance), OT (ADLs), speech therapy (aphasia, dysphagia), neuropsychology (cognitive deficits, depression), recreational therapy; inpatient rehab vs SNF vs home with services; (5) **Post-stroke depression** (~ 30%) — screen + treat (SSRI); cognitive impairment screening; (6) **Modifiable risk factor management** lifelong: BP, lipids, DM, weight, exercise, diet, smoking, alcohol; (7) **Family + caregiver support + education**: stroke warning signs, medication adherence, fall prevention, transportation, equipment; (8) **Multidisciplinary stroke clinic** follow-up: neurology + PCP + cardiology if AFib + PT/OT + speech + social work + nutrition + nursing; (9) **Advance care planning** if severe deficit; (10) **Return to work + driving + community reintegration**

---

Post-stroke care: acute monitoring + etiology workup + secondary prevention by mechanism + intensive rehab + depression/cognitive screening + risk factor management + multidisciplinary stroke clinic + family support.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'radiology'
  and scenario = 'ผู้ป่วยอายุ 60 ปี acute LVO stroke + successful thrombectomy — comprehensive post-stroke care';

update public.mcq_questions
set choices = '[{"label":"A","text":"Always image"},{"label":"B","text":"Goals of care + imaging in advanced dementia"},{"label":"C","text":"Single specialty"},{"label":"D","text":"Discharge without discussion"},{"label":"E","text":"Refuse care"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Goals of care + imaging in advanced dementia: (1) **First step — goals of care discussion BEFORE imaging**: imaging guided by what will change management consistent with patient values + prognosis; ALWAYS ask: ''Will this scan change what we do? Is what we''d do aligned with patient values?''; (2) **Comprehensive geriatric assessment**: medical (comorbidities), functional (ADLs/IADLs), cognitive (severity of dementia — Global Deterioration Scale, FAST), psychosocial, advance directives review; (3) **Family conflict navigation**: - Identify legal surrogate decision-maker (HCPOA, next of kin per state law); - Substituted judgment standard (what would patient want, not what family wants); - Family meeting with palliative care if available — explore values, concerns, fears, misunderstandings; - Time-limited trial of treatment with predetermined goals + reassessment may help; - Mediation, ethics committee if persistent conflict; (4) **Considerations against extensive imaging in severe dementia**: - Patient may not tolerate (cooperation, claustrophobia, anxiety); - Transport risk (falls, delirium worsening, exposure to noise/stress); - Sedation risks (delirium, aspiration); - Findings may not change management (e.g., new cancer found but patient too frail for treatment); - Avoid ''imaging cascade'' — incidental findings → more tests → more interventions → potential harm; (5) **Considerations FOR imaging when changes management**: - Acute pain — fracture (would impact pain control + positioning); - Suspected reversible cause of decline (UTI, infection, treatable mass causing pain); - Comfort interventions (palliative XRT for bone mets pain — yes, would need imaging for planning); (6) **Palliative imaging philosophy**: limited but purposeful imaging consistent with comfort + dignity goals; concurrent palliative care services; (7) **Hospice consideration** when prognosis < 6 months + focus on comfort; (8) **Documentation**: detailed shared decision-making conversation, surrogate involvement, rationale; (9) **Multidisciplinary**: PCP + geriatrics + palliative care + radiology + nursing + social work + ethics + chaplaincy + family

---

Goals of care drive imaging decisions in advanced dementia. Substituted judgment for surrogate decision. Will imaging change management? Family meeting, palliative care involvement, ethics if needed. Limited purposeful imaging.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'radiology'
  and scenario = 'ผู้ป่วยอายุ 85 ปี severe dementia + new acute symptoms + family disagreement — goals of imaging discussion';

update public.mcq_questions
set choices = '[{"label":"A","text":"X-ray first then decompress"},{"label":"B","text":"Tension pneumothorax — CLINICAL diagnosis + immediate decompression BEFORE imaging"},{"label":"C","text":"MRI"},{"label":"D","text":"Observation only"},{"label":"E","text":"CT prior to any intervention"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Tension pneumothorax — CLINICAL diagnosis + immediate decompression BEFORE imaging: (1) **Clinical diagnosis** — do NOT wait for imaging: respiratory distress + tracheal deviation away from affected side + absent breath sounds + hyperresonance + hypotension + JVD + hypoxia; (2) **Immediate intervention**: needle decompression (14-gauge, 2nd intercostal space midclavicular line OR 5th ICS anterior axillary line per recent ATLS — depends on body habitus, larger studies show better) → tube thoracostomy (chest tube) — definitive; (3) **Imaging AFTER initial stabilization**: - **CXR (upright when stable)**: deep sulcus sign on supine (lateral costophrenic angle deepened), visceral pleural line + absence of lung markings peripheral, mediastinal shift away, depressed hemidiaphragm; - **CT chest** — most sensitive for small/occult pneumothorax (eFAST may detect ~ 50%); - **eFAST/POCUS** at bedside — absence of lung sliding + absence of B-lines + lung point (specific) — high sensitivity in trained hands, faster than imaging transport; (4) **Simple pneumothorax management** (no tension): - Small (< 2 cm rim) + asymptomatic → observation + repeat CXR + supplemental oxygen (accelerates resorption); - Larger or symptomatic → catheter aspiration or chest tube; - Persistent air leak > 5-7 days or recurrent → surgical (VATS bleb resection + pleurodesis); (5) **Pneumothorax risk factors**: trauma, iatrogenic (CVC, biopsy, mechanical ventilation barotrauma), spontaneous (tall thin males — primary; COPD/cystic lung disease — secondary), procedures

---

Tension pneumothorax = CLINICAL diagnosis — needle decompression THEN chest tube, then imaging. eFAST at bedside (lung sliding + lung point). CT for occult/small. Simple PTX — small + asymptomatic observation; larger needs aspiration/chest tube.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'radiology'
  and scenario = 'ผู้ป่วยอายุ 30 ปี post-MVC + acute SOB + tracheal deviation + decreased breath sounds R + hypotension — clinical tension pneumothorax suspected';

update public.mcq_questions
set choices = '[{"label":"A","text":"Discharge"},{"label":"B","text":"Hemothorax — clinical + imaging + management"},{"label":"C","text":"Observation no chest tube"},{"label":"D","text":"MRI emergent"},{"label":"E","text":"Single specialty"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Hemothorax — clinical + imaging + management: (1) **Imaging**: - **eFAST at bedside** — first: free fluid in pleural space (FAST views), pneumothorax screen; - **CXR upright** — blunting of costophrenic angle (~ 200 mL needed for blunting on PA upright; less on lateral decubitus — as little as 50 mL); supine CXR — diffuse haziness over hemithorax; large hemothorax — opacification, mediastinal shift away (significant volume); - **CT chest** — most sensitive + identifies source + associated injuries (lung, vascular, diaphragm, esophagus); (2) **Initial management**: - Hemodynamically stable + small (< 300 mL) → observation; - Larger / symptomatic → **tube thoracostomy** (28-32 Fr large bore for hemothorax — drainage + monitoring of ongoing bleeding); - **Indications for thoracotomy/VATS**: > 1500 mL immediate drainage OR ongoing bleeding > 200 mL/hr × 3-4 hours; persistent hemothorax (retained) → VATS evacuation within 3-7 days to prevent empyema + fibrothorax; (3) **Retained hemothorax** complications: empyema, fibrothorax, restrictive ventilatory defect, chronic pain; (4) **Coagulopathy correction**: transfusion (1:1:1 ratio in massive — MTP), TXA in trauma (CRASH-2/3); (5) **Penetrating chest trauma decision tree**: ABCDE + eFAST + CXR + decision for OR (massive hemothorax, persistent hemodynamic instability, cardiac tamponade) vs CT (stable, comprehensive evaluation); (6) **Multidisciplinary**: trauma surgery + ED + radiology + critical care + anesthesia

---

Hemothorax: eFAST + CXR + CT. Large-bore chest tube. Thoracotomy if > 1500 mL initial or > 200 mL/hr × 3-4h. Retained hemothorax → VATS evacuation. MTP + TXA. Multidisciplinary trauma.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'radiology'
  and scenario = 'ผู้ป่วยอายุ 45 ปี post-stab wound to chest + hemodynamically unstable + decreased breath sounds L — clinical hemothorax suspected';

update public.mcq_questions
set choices = '[{"label":"A","text":"Biopsy immediately"},{"label":"B","text":"Fleischner Society 2017 Guidelines — incidental pulmonary nodules ≥ 35 years"},{"label":"C","text":"Discharge no follow-up"},{"label":"D","text":"Surgery for all nodules"},{"label":"E","text":"X-ray annual"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Fleischner Society 2017 Guidelines — incidental pulmonary nodules ≥ 35 years: (1) **For solid nodules**: - **< 6 mm**: low-risk (non-smoker, no other risk) → no routine follow-up; high-risk (smoker, occupational exposure, family hx) → optional CT at 12 months; - **6-8 mm**: low-risk → CT at 6-12 months, then 18-24 months; high-risk → CT at 6-12 months + 18-24 months; - **> 8 mm**: CT at 3 months + PET/CT + biopsy/resection — individualized; (2) **Multiple solid nodules**: < 6 mm — no follow-up (low) / 12 mo (high); ≥ 6 mm — CT 3-6 mo + consider follow-up at 18-24 mo; (3) **Subsolid nodules**: - Pure ground glass: < 6 mm — no follow-up; ≥ 6 mm — CT at 6-12 mo to confirm persistence, then q2y × 5 years; - Part-solid: solid component < 6 mm — same as ground glass; solid component ≥ 6 mm — CT at 3-6 mo, then management of solid component drives decisions (suspicious — biopsy/resect); (4) **Application**: incidentally found nodules in routine imaging (NOT lung cancer screening — those follow Lung-RADS); (5) **Considerations**: nodule growth (volume doubling time — solid < 400 days suspicious), morphology (spiculation, lobulation, pleural retraction suspicious), location (upper lobe suspicious), patient factors (age, smoking, occupational, family hx); (6) **Modern**: AI-assisted nodule detection + volumetry + characterization emerging; standardized reporting; (7) **Documentation + tracking** of incidental findings — closed-loop systems to avoid lost follow-up

---

Fleischner 2017: solid nodule < 6 mm low-risk → no follow-up; 6-8 mm → CT 6-12 mo; > 8 mm → CT 3 mo + PET + biopsy. Subsolid nodules longer follow-up (q2y × 5 yrs). Track + close loop. Differentiate from Lung-RADS (screening).'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'radiology'
  and scenario = 'ผู้ป่วยอายุ 55 ปี incidental finding 6 mm solid pulmonary nodule on chest CT done for other reason — non-smoker, no malignancy history

คำถาม: Fleischner Society 2017 management';

update public.mcq_questions
set choices = '[{"label":"A","text":"No staging needed"},{"label":"B","text":"NSCLC staging — TNM 8th edition (effective 2017)"},{"label":"C","text":"Single specialty"},{"label":"D","text":"Discharge"},{"label":"E","text":"Always surgery without staging"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** NSCLC staging — TNM 8th edition (effective 2017): (1) **Imaging staging algorithm**: - **CT chest/abdomen (through adrenals)** with IV contrast: primary tumor (T — size, invasion of mediastinum/pleura/diaphragm/chest wall), N1-3 lymph nodes (hilar, mediastinal — short axis ≥ 1 cm by CT, but CT not specific — biopsy needed), liver + adrenal mets (M); - **PET/CT FDG** — mediastinal nodes + distant mets (extracranial); upstages 15% of patients vs CT alone; - **MRI brain** with contrast — exclude brain mets in all stage II+ (high incidence even asymptomatic); CT brain alternative; - **MRI Pancoast tumor** — superior sulcus, brachial plexus + subclavian vessels invasion; - **Bone scan** — if PET not done; (2) **Tissue diagnosis + molecular**: image-guided biopsy (transthoracic CT-guided, EBUS-TBNA for mediastinal nodes, navigational bronchoscopy); molecular markers — EGFR, ALK, ROS1, BRAF, MET, RET, KRAS G12C, NTRK, HER2 (targeted therapies), PD-L1 (immunotherapy); (3) **Mediastinal staging**: EBUS-TBNA (preferred — minimally invasive, samples lymph nodes), mediastinoscopy for selected (sensitivity for paratracheal stations); (4) **PFTs** for surgical planning (predicted post-op FEV1, DLCO); cardiac evaluation if surgery; (5) **Multidisciplinary tumor board** — radiology, pulmonology, thoracic surgery, medical oncology, radiation oncology, pathology, palliative care; (6) **Stage-based treatment**: I-II — surgery (lobectomy + LN dissection) + adjuvant chemo for selected (osimertinib for EGFR adjuvant ADAURA); III — concurrent chemoradiation + durvalumab consolidation (PACIFIC); IV — systemic (targeted, immunotherapy, chemo)

---

NSCLC staging: TNM 8th ed. CT chest/abd + PET/CT + brain MRI + EBUS-TBNA. Molecular markers (EGFR, ALK, ROS1, KRAS G12C, PD-L1). Multidisciplinary tumor board. Stage-based therapy with osimertinib/durvalumab.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'radiology'
  and scenario = 'ผู้ป่วยอายุ 65 ปี smoker + new lung mass — pathology confirmed NSCLC adenocarcinoma

คำถาม: staging workup';

update public.mcq_questions
set choices = '[{"label":"A","text":"Always negative is benign"},{"label":"B","text":"FDG-PET/CT for pulmonary nodules"},{"label":"C","text":"Discharge"},{"label":"D","text":"X-ray more sensitive"},{"label":"E","text":"Bone scan"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** FDG-PET/CT for pulmonary nodules: (1) **Mechanism**: FDG (fluorodeoxyglucose) — glucose analog uptake reflects metabolic activity; malignant tumors typically hypermetabolic; (2) **Standardized uptake value (SUV)** — semi-quantitative; SUVmax > 2.5 suggests malignancy (cut-off variable; high-grade tumors > 4-5 common); SUV affected by blood glucose, time of imaging, body composition; (3) **Sensitivity for nodules**: - Solid > 8-10 mm — sensitivity 90-95%, specificity 80%; - **Small nodules (< 8 mm) — UNRELIABLE** (false negatives due to partial volume effect); - Ground glass / subsolid nodules — FALSE NEGATIVES — adenocarcinoma in situ + minimally invasive adenocarcinoma often FDG-low; (4) **False positives**: granulomatous infections (TB, fungal — endemic regions), sarcoidosis, infection, inflammation, post-radiation; (5) **False negatives**: subsolid nodules, low-grade tumors (carcinoid — neuroendocrine, mucinous adenocarcinoma in situ), small lesions; (6) **Clinical use**: - Characterize indeterminate solid nodule ≥ 8 mm (Fleischner); - **Staging** NSCLC (T, N, M) — upstages 15-25%, prevents futile surgery; - **Re-staging** post-treatment (PERCIST criteria); - **Recurrence detection**; (7) **Limitations**: brain mets — PET poor (high background brain glucose uptake) — need MRI brain; bone marrow background; (8) **Combined PET/CT** standard — anatomic + functional fused; (9) **Newer tracers**: FDG most common, but specialized — DOTATATE for neuroendocrine, F-DOPA, FAPI emerging

---

PET/CT for nodules: SUVmax > 2.5 suggests malignancy. UNRELIABLE for < 8 mm + subsolid/GGN (false negatives). False positives — granulomatous infection in endemic regions. Useful for staging + recurrence. PET/CT standard combined.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'radiology'
  and scenario = 'ผู้ป่วยอายุ 60 ปี 8 mm solitary pulmonary nodule + non-smoker — PET/CT for characterization

คำถาม: interpretation';

update public.mcq_questions
set choices = '[{"label":"A","text":"NSIP"},{"label":"B","text":"UIP pattern (Usual Interstitial Pneumonia) on HRCT — diagnostic for IPF in clinical context"},{"label":"C","text":"Lung cancer"},{"label":"D","text":"Acute pneumonia"},{"label":"E","text":"Single specialty"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** UIP pattern (Usual Interstitial Pneumonia) on HRCT — diagnostic for IPF in clinical context: (1) **UIP pattern criteria (ATS/ERS/JRS/ALAT 2018)**: - **Definite UIP** (all 4): subpleural + basal predominance, honeycombing (clustered cystic airspaces 3-10 mm with thick walls), reticulation + traction bronchiectasis, absence of features suggesting alternative diagnosis; - **Probable UIP**: subpleural basal + reticulation + traction bronchiectasis WITHOUT definite honeycombing; - **Indeterminate**: features not clearly UIP or alternative; - **Alternative diagnosis**: features suggesting other ILD (extensive ground glass, micronodules, peribronchovascular, upper/midzonal); (2) **Confidence for IPF diagnosis**: definite UIP on HRCT + appropriate clinical context (age > 60, no exposure/CTD/drug) — diagnostic for IPF, lung biopsy NOT needed; probable UIP — multidisciplinary discussion + may need surgical lung biopsy or transbronchial cryobiopsy; (3) **Differential diagnosis of UIP pattern**: IPF (most common), chronic hypersensitivity pneumonitis (upper-mid lobe predominance, mosaic attenuation), CTD-ILD (especially RA, scleroderma — autoantibodies, esophageal dilation), asbestosis (exposure history, pleural plaques), drug-induced (amiodarone, methotrexate, nitrofurantoin), familial IPF (telomere, surfactant gene mutations); (4) **NSIP pattern** (different — more responsive to immunosuppression): ground glass + reticulation, peripheral + basal, subpleural sparing, no honeycombing (usually) — younger, female, CTD common; (5) **Workup IPF**: HRCT + clinical + serologies (ANA, RF, anti-CCP, myositis panel — exclude CTD), serum precipitins for HP, occupational/environmental history; (6) **Treatment IPF**: **antifibrotics — pirfenidone, nintedanib** (slow FVC decline + reduce mortality — ASCEND, INPULSIS); lung transplant for selected; clinical trials; multidisciplinary; (7) **Multidisciplinary ILD clinic** — pulmonology + radiology + rheumatology + pathology + thoracic surgery

---

UIP pattern: subpleural + basal + honeycombing + traction bronchiectasis = IPF in appropriate clinical context (no biopsy needed). NSIP — different (ground glass, peripheral basal, no honeycombing). Antifibrotics (pirfenidone, nintedanib). Multidisciplinary ILD.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'radiology'
  and scenario = 'ผู้ป่วยอายุ 60 ปี progressive dyspnea + dry cough × 6 เดือน — HRCT พบ subpleural reticulation + honeycombing + traction bronchiectasis + basal posterior predominance ไม่มี ground glass

คำถาม: ILD diagnosis';

update public.mcq_questions
set choices = '[{"label":"A","text":"Lung cancer"},{"label":"B","text":"Sarcoidosis — Lofgren syndrome variant"},{"label":"C","text":"TB"},{"label":"D","text":"Pneumonia"},{"label":"E","text":"CHF"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Sarcoidosis — Lofgren syndrome variant: (1) **Imaging features**: - **CXR Scadding staging**: Stage 0 normal; Stage I bilateral hilar lymphadenopathy alone; Stage II BHL + parenchymal infiltrates; Stage III parenchymal only; Stage IV pulmonary fibrosis; - **HRCT**: bilateral symmetric hilar + mediastinal lymphadenopathy (HALLMARK), perilymphatic nodules along bronchovascular bundles + fissures + subpleural, upper-mid lobe predominance, eventual fibrosis, calcified nodes (eggshell pattern); (2) **PET-CT**: hypermetabolic nodes + lesions — extrapulmonary disease assessment (cardiac, neuro, eye, skin); (3) **Tissue diagnosis** (usually needed): EBUS-TBNA of mediastinal nodes (high yield) > skin biopsy (cutaneous lesions); shows **non-caseating granulomas**; exclude TB (AFB, PPD/IGRA), fungal, lymphoma; (4) **Lofgren syndrome** = BHL + erythema nodosum + arthralgias + uveitis — often resolves spontaneously (90% remission); good prognosis; biopsy not always needed; (5) **Heerfordt syndrome** = uveoparotid fever + fever + facial nerve palsy + parotid enlargement; (6) **Extrapulmonary involvement** — eye (uveitis), heart (conduction blocks, cardiomyopathy — cardiac MRI + PET for diagnosis), CNS (meningitis, neurosarcoidosis), skin (lupus pernio, plaques), kidney (hypercalcemia + nephrolithiasis), liver, spleen, bone marrow; (7) **Workup**: ACE level (limited utility — not for diagnosis), serum + 24h urine calcium (hypercalcemia from extrarenal calcitriol), eye exam, ECG + echo + cardiac MRI (50% subclinical cardiac involvement), neurologic exam; (8) **Treatment**: observation for asymptomatic limited disease; **corticosteroids** for symptomatic / organ-threatening (lung, eye, cardiac, neuro, skin) + steroid-sparing (MTX, azathioprine, mycophenolate, biologics — TNF inhibitors); (9) **Multidisciplinary** — pulmonology + cardiology + ophthalmology + dermatology + neurology

---

Sarcoidosis: bilateral symmetric hilar adenopathy. Scadding stages I-IV. Lofgren syndrome (BHL + EN + uveitis) — often spontaneous remission. Non-caseating granulomas. ACE not diagnostic. Steroids for symptomatic/organ-threatening. Multidisciplinary.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'radiology'
  and scenario = 'ผู้ป่วยอายุ 35 ปี dry cough + dyspnea + hilar adenopathy bilateral symmetric on CXR + erythema nodosum + uveitis';

update public.mcq_questions
set choices = '[{"label":"A","text":"IPF"},{"label":"B","text":"Hypersensitivity pneumonitis (HP) — chronic farmer''s lung"},{"label":"C","text":"Asthma"},{"label":"D","text":"Bronchitis"},{"label":"E","text":"Pneumonia"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Hypersensitivity pneumonitis (HP) — chronic farmer''s lung: (1) **Imaging features**: - **Acute/subacute HP**: ground glass opacities + centrilobular nodules (poorly defined), upper-mid lobe + central distribution; - **Chronic HP**: superimposed fibrosis (reticulation, traction bronchiectasis, honeycombing — may mimic IPF/UIP — distinguishing features below), mosaic attenuation on expiration (small airway disease + air trapping), ''three-density sign'' (normal lung + ground glass + lobular air trapping) characteristic; (2) **Distinguishing chronic HP from IPF**: - HP — upper-mid lobe predominance, mosaic attenuation, air trapping on expiration, ground glass abundant; - IPF — lower lobe + basal + subpleural predominance, honeycombing, no significant ground glass; sparing of basal areas in HP vs IPF where they are heavily involved; (3) **History essential**: exposure history (birds, mold, hot tubs, occupation — farming, lumber mill, metal working fluids, etc.); identifying antigen sometimes difficult; (4) **Workup**: HRCT + clinical exposure history + bronchoalveolar lavage (lymphocytosis > 30%, low CD4/CD8 ratio typical), serum precipitins for known antigens (limited test characteristics — exposure marker not diagnosis), transbronchial cryobiopsy or surgical lung biopsy in selected cases; (5) **Treatment**: - **Antigen avoidance** — most important — without it, treatment fails; - Corticosteroids for symptomatic acute/subacute; - Chronic fibrotic HP — antifibrotics (nintedanib — INBUILD trial for progressive pulmonary fibrosis including HP); MMF + azathioprine alternatives; - Lung transplant for advanced; (6) **Prevention**: occupational hygiene, ventilation, avoiding exposure; (7) **Multidisciplinary**: pulmonology + allergy/immunology + occupational medicine + radiology + pathology

---

HP: centrilobular GGNs + mosaic attenuation + air trapping + upper-mid lobe in chronic. Exposure history essential. BAL lymphocytosis. Antigen avoidance MOST important. Nintedanib for progressive fibrotic. Multidisciplinary.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'radiology'
  and scenario = 'ผู้ป่วยอายุ 50 ปี farmer + chronic cough + progressive dyspnea + weight loss — HRCT พบ centrilobular ground glass nodules + mosaic attenuation + air trapping + mid-upper lobe predominance';

update public.mcq_questions
set choices = '[{"label":"A","text":"Benign — discharge"},{"label":"B","text":"Mesothelioma — workup + management"},{"label":"C","text":"X-ray only sufficient"},{"label":"D","text":"Single specialty"},{"label":"E","text":"Refuse care"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Mesothelioma — workup + management: (1) **Imaging features**: - **CXR/CT**: unilateral pleural effusion (often large, recurrent), nodular pleural thickening (> 1 cm), pleural masses, encasement of lung (''rind-like''), volume loss of hemithorax, pleural calcifications + plaques (asbestos exposure marker, NOT mesothelioma itself), chest wall invasion, mediastinal involvement; - **MRI** — extent of chest wall + diaphragm + mediastinal invasion (better than CT for soft tissue resectability); - **PET/CT** — distant metastases + nodal staging + biopsy target; (2) **Tissue diagnosis** REQUIRED: thoracoscopic (VATS) pleural biopsy preferred (high yield); image-guided pleural biopsy with closed needle technique (Abrams or Cope) — lower yield; cytology of pleural fluid alone insensitive; immunohistochemistry essential (calretinin+, WT1+, cytokeratin 5/6+, CK7+, negative TTF-1 — distinguishes from adenocarcinoma); histologic subtypes — epithelioid (best prognosis), sarcomatoid (worst), biphasic; (3) **Staging**: TNM 8th ed for mesothelioma; (4) **Treatment**: - **Multimodal — multidisciplinary tumor board**: thoracic surgery + medical oncology + radiation oncology + radiology + pathology + palliative care; - **Selected resectable epithelioid** — surgery (extrapleural pneumonectomy EPP or pleurectomy/decortication — less morbid) + chemotherapy + RT; - **Immunotherapy** — nivolumab + ipilimumab (CheckMate 743 — improved OS first-line); - **Chemotherapy** — cisplatin/carboplatin + pemetrexed; bevacizumab; - **Palliative** — pleural drainage (indwelling pleural catheter — IPC), talc pleurodesis; (5) **Asbestos exposure documentation** — compensation, prevention, screening of other exposed workers; (6) **Prognosis** poor — median OS 12-18 months without treatment, ~ 24+ months with multimodal in selected; (7) **Prevention**: ban asbestos use, surveillance of exposed workers, awareness

---

Mesothelioma: asbestos exposure + unilateral pleural effusion + nodular pleural thickening. VATS biopsy + IHC essential. Multimodal multidisciplinary. Nivolumab + ipilimumab first-line (CheckMate 743). Palliative IPC.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'radiology'
  and scenario = 'ผู้ป่วยอายุ 70 ปี occupational asbestos exposure 30 ปีก่อน + worsening chest pain + dyspnea + unilateral pleural effusion — CT พบ nodular pleural thickening + pleural masses';

update public.mcq_questions
set choices = '[{"label":"A","text":"Repeat CXR daily"},{"label":"B","text":"CT findings + DDx"},{"label":"C","text":"MRI immediately"},{"label":"D","text":"Discharge without imaging"},{"label":"E","text":"X-ray monthly"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Pneumonia imaging: (1) **Diagnosis**: clinical + CXR (lobar consolidation, infiltrates) usually sufficient for CAP; CT not routine but indicated if: - Complications suspected (effusion, empyema, abscess, necrotizing PNA); - Immunocompromised + unusual organisms; - Treatment failure; - Underlying lung disease (e.g., COPD with infiltrate); - Recurrent or non-resolving (suspect underlying mass — endobronchial obstruction); (2) **CT findings + DDx**: - Lobar consolidation (bacterial — pneumococcus, Klebsiella); - Bronchopneumonia/lobular (staph, gram-negatives); - Cavity (anaerobic, TB, fungal, septic emboli, lung cancer); - Tree-in-bud (small airway disease — endobronchial spread, TB, bronchiolitis); - Ground glass + organizing patterns (viral — COVID, influenza, PCP — perihilar in HIV); - Halo + reverse halo signs (angioinvasive aspergillosis — neutropenic); (3) **Follow-up CXR**: - Resolution often slow — clinical recovery precedes radiographic by weeks (full clearance 6-8 weeks for some); - **Repeat CXR at 6-8 weeks** for patients > 50 or smokers — exclude occult underlying lung cancer; recent ATS/IDSA — selective based on risk; (4) **Complications imaging**: - **Parapneumonic effusion** (US-guided thoracentesis — pH < 7.2, glucose < 60, LDH > 1000, presence of bacteria/pus = complicated → chest tube drainage); - **Empyema** — thick-walled, septated; VATS evacuation; - **Lung abscess** — cavity with air-fluid level; - **Necrotizing pneumonia** — multiple small cavities within consolidation (PVL-Staph, Klebsiella); (5) **Treatment per IDSA/ATS CAP 2019**: outpatient (amoxicillin or doxycycline or macrolide); inpatient non-ICU (beta-lactam + macrolide or respiratory fluoroquinolone); inpatient ICU (beta-lactam + macrolide or fluoroquinolone); MRSA + Pseudomonas coverage selectively

---

Pneumonia: CXR usually sufficient for CAP; CT for complications/failure/immunocompromised/non-resolving. Repeat CXR 6-8 wks selective (smokers, > 50). Complications: parapneumonic effusion (tap), empyema, abscess, necrotizing. IDSA/ATS treatment.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'radiology'
  and scenario = 'ผู้ป่วยอายุ 65 ปี fever + productive cough + lobar consolidation R lower lobe on CXR — community-acquired pneumonia

คำถาม: imaging role + when to repeat';

update public.mcq_questions
set choices = '[{"label":"A","text":"Bacterial pneumonia"},{"label":"B","text":"Pulmonary TB — imaging features"},{"label":"C","text":"Lung cancer alone"},{"label":"D","text":"Sarcoidosis"},{"label":"E","text":"Discharge"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Pulmonary TB — imaging features: (1) **Primary TB**: lower/middle lobe consolidation + ipsilateral hilar/mediastinal lymphadenopathy (Ghon complex if calcified); often resolves spontaneously in immunocompetent; may calcify; (2) **Post-primary (reactivation) TB**: upper lobe cavitary disease (apical-posterior segments of upper lobes + superior segments of lower lobes — well-aerated favors mycobacteria), tree-in-bud (endobronchial spread — small airway involvement with mucus + inflammation), centrilobular nodules, consolidation, pleural effusion, miliary (tiny 1-3 mm nodules diffusely — disseminated, hematogenous spread); (3) **Differential of cavitary lung lesion**: TB (most common chronic infectious cause worldwide), bacterial abscess (anaerobic, Klebsiella, Staph), fungal (Aspergillus — mycetoma in pre-existing cavity, endemic mycoses), septic emboli, lung cancer (squamous most often), Wegener (now GPA — multiple cavities), rheumatoid nodule, sarcoidosis (rare), pneumocystis (uncommon); (4) **Active vs latent TB on imaging** — not reliable distinction; active disease may have minimal findings; sputum + clinical + epidemiologic correlation needed; (5) **Workup**: AFB smear (low sensitivity), culture (gold standard, 6-8 weeks), Xpert MTB/RIF (rapid, detects rifampin resistance — preferred initial test now), IGRA / PPD (exposure marker — does not distinguish active vs latent); (6) **Sequelae imaging**: post-TB fibrosis, bronchiectasis (especially upper lobes), tracheobronchial stenosis, calcified granulomas + lymph nodes, aspergilloma in old cavities, broncholiths; (7) **Treatment** (drug-susceptible): 2 months HRZE + 4 months HR (RIPE), DOT recommended; MDR-TB longer regimens; (8) **Infection control + public health** — isolation airborne precautions, contact tracing, reporting; (9) **Multidisciplinary**: ID + pulmonology + public health + radiology

---

Reactivation TB: upper lobe cavity + tree-in-bud + apical-posterior. Differential cavitary lung lesion. Xpert MTB/RIF rapid Dx. RIPE 6-month treatment + DOT. Airborne isolation. Multidisciplinary.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'radiology'
  and scenario = 'ผู้ป่วยอายุ 40 ปี chronic cough + weight loss + night sweats + hemoptysis — CXR พบ upper lobe cavitary lesion with tree-in-bud opacities — TB suspected';

update public.mcq_questions
set choices = '[{"label":"A","text":"Discharge"},{"label":"B","text":"Acute aortic dissection — imaging + management"},{"label":"C","text":"Medical only for all dissection"},{"label":"D","text":"Wait for next day surgery"},{"label":"E","text":"Single specialty"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Acute aortic dissection — imaging + management: (1) **Imaging modality choice**: - **CT angiography aorta (CTA) — first-line in hemodynamically stable** — fast, widely available, comprehensive (extent, branch vessels, complications); ECG-gated CTA reduces motion artifact in ascending aorta; - **TEE** (transesophageal echo) — alternative for unstable patients (bedside), excellent for ascending aorta + valve; limited descending visualization, requires sedation; - **MRA** — selected stable patients, follow-up; (2) **Classification**: - **Stanford A** — involves ascending aorta (with or without descending) — SURGICAL EMERGENCY (high mortality from rupture into pericardium, tamponade, AI, stroke, MI from coronary involvement); - **Stanford B** — descending only (distal to left subclavian) — usually medical management with antihypertensives unless complications (malperfusion, rupture, refractory pain, expansion — TEVAR endovascular preferred); - **DeBakey** I-III — anatomic; (3) **Imaging features**: intimal flap separating true (typically smaller, faster flow) + false lumens, intramural hematoma variant (no flap — crescent of high attenuation in vessel wall), penetrating atherosclerotic ulcer (focal contrast outpouching), aortic root involvement → coronary involvement + AI + tamponade, branch vessel involvement → malperfusion (carotid, mesenteric, renal, iliac); (4) **Management Stanford A**: - **Emergency cardiothoracic surgery** — replace ascending aorta + aortic valve (Bentall procedure) ± hemiarch / total arch; - BP control while preparing (esmolol → SBP 100-120, HR < 60) — beta-blocker first (reduce shear stress); (5) **Management Stanford B**: - Uncomplicated — anti-impulse therapy (BP + HR control); - Complicated (malperfusion, expansion, refractory pain, rupture) — **TEVAR** (thoracic endovascular aortic repair) preferred over open; (6) **Multidisciplinary**: cardiothoracic surgery + vascular surgery + cardiology + IR + critical care + anesthesia + radiology

---

Aortic dissection: CTA first-line. Stanford A (ascending) = EMERGENCY surgery (Bentall). Stanford B (descending) = medical (HR + BP control) unless complications → TEVAR. Multidisciplinary.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'radiology'
  and scenario = 'ผู้ป่วยอายุ 50 ปี severe chest pain radiating to back + hypertension — CT angiography aorta พบ intimal flap extending from ascending aorta to descending — Stanford A dissection';

update public.mcq_questions
set choices = '[{"label":"A","text":"Annual CT all adults"},{"label":"B","text":"AAA screening"},{"label":"C","text":"No screening ever"},{"label":"D","text":"Discharge"},{"label":"E","text":"MRI screening"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** AAA screening: (1) **USPSTF Grade B recommendation**: one-time abdominal US screening for AAA in men aged 65-75 who have ever smoked; (2) **For men 65-75 never smoked**: USPSTF grade C — selective screening based on risk (family history of AAA, vascular disease); (3) **For women**: USPSTF — **insufficient evidence** for screening; consider in selected (smokers, family history); some guidelines (SVS) recommend screening women 65-75 who have smoked or have family history; (4) **Modality**: **abdominal ultrasound** — first-line: no radiation, no contrast, accurate for diameter, low cost; CT for definitive sizing + surgical planning + complications; MRA alternative; (5) **AAA threshold definitions**: > 3.0 cm aortic diameter = aneurysm; treatment threshold > 5.5 cm men, > 5.0 cm women (smaller diameter to wall ratio); rapid expansion > 0.5 cm/6 months also indication; (6) **Surveillance based on size**: 3.0-3.9 cm — US q3 years; 4.0-4.9 cm — q1 year; 5.0-5.4 cm — q6 months; (7) **Treatment options**: - **Endovascular aneurysm repair (EVAR)** — preferred for most anatomically suitable AAAs (lower 30-day mortality vs open, similar long-term, requires lifelong surveillance for endoleaks); - **Open surgical repair** — for complex anatomy, young patients with longer life expectancy, infected AAA, EVAR failure; - Medical — BP control + smoking cessation + statin + antiplatelet; (8) **Ruptured AAA** — emergent — surgical or EVAR (depending on stability + anatomy); high mortality; (9) **Multidisciplinary**: vascular surgery + radiology + cardiology + primary care

---

AAA screening: one-time abdominal US for men 65-75 ever smoked (USPSTF B). Surveillance interval by size. Treat > 5.5 cm men, > 5.0 cm women, or rapid expansion. EVAR preferred for most. Multidisciplinary.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'radiology'
  and scenario = 'ชายอายุ 70 ปี USPSTF screening + smoker — abdominal aortic aneurysm screening';

update public.mcq_questions
set choices = '[{"label":"A","text":"Discharge"},{"label":"B","text":"Coronary CT angiography (CCTA) — stable chest pain"},{"label":"C","text":"Always invasive cath"},{"label":"D","text":"X-ray sufficient"},{"label":"E","text":"Stress test only"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Coronary CT angiography (CCTA) — stable chest pain: (1) **Indications per AHA/ACC 2021 Chest Pain Guidelines + ESC 2019**: stable chest pain + intermediate pre-test probability of CAD (15-65% per ESC, 15-50% intermediate per ACC) — CCTA Class I; alternative to stress testing; **ISCHEMIA** + **SCOT-HEART** + **PROMISE** trials support CCTA-first strategy; (2) **Strengths**: high negative predictive value (> 95%) — excludes obstructive CAD reliably; detects non-obstructive plaque (prognostic), high-risk plaque features (positive remodeling, low attenuation < 30 HU = lipid core, spotty calcification, napkin-ring sign — vulnerable plaque); anatomic information; (3) **Limitations**: severely calcified coronaries (overestimate stenosis), arrhythmia (motion — though modern scanners handle), high heart rates (beta-blocker to HR < 65), pregnancy/young women (radiation — risk-benefit), prior stent (artifact), CABG patients (graft assessment OK but limited native vessel); (4) **FFR-CT** (fractional flow reserve from CCTA) — physiologic significance of anatomic stenosis from same dataset using computational fluid dynamics — reduces unnecessary cath; (5) **Reporting standards** — CAD-RADS classification (0-5) for systematic assessment; (6) **Coronary calcium scoring (CAC, Agatston)** — separate non-contrast scan, prognostic for asymptomatic risk stratification (CAC = 0 very low risk; CAC > 100 elevated risk — consider statin per ACC 2018 cholesterol guidelines); (7) **Acute chest pain CCTA** — selective in low-intermediate risk in some EDs (rapid rule-out — ROMICAT, ACRIN), but high-sensitivity troponin pathways often preferred now; (8) **Radiation dose**: prospective ECG-triggering, iterative reconstruction reduce to 1-3 mSv (modern); (9) **Multidisciplinary**: cardiology + radiology + ED

---

CCTA: stable chest pain intermediate PTP CAD. High NPV. CAD-RADS reporting. FFR-CT for physiology. CAC scoring separate for asymptomatic risk. ISCHEMIA/SCOT-HEART/PROMISE support. Multidisciplinary.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'radiology'
  and scenario = 'ผู้ป่วยอายุ 60 ปี atypical chest pain + intermediate pre-test probability for CAD — CCTA performed

คำถาม: CCTA strengths + interpretation';

update public.mcq_questions
set choices = '[{"label":"A","text":"No tissue characterization possible"},{"label":"B","text":"Cardiac MRI (CMR) — comprehensive characterization"},{"label":"C","text":"X-ray sufficient"},{"label":"D","text":"Discharge"},{"label":"E","text":"PET only"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Cardiac MRI (CMR) — comprehensive characterization: (1) **Strengths**: gold standard for ventricular volumes + EF (reproducible), tissue characterization (myocardial fibrosis, edema, iron, fat infiltration), flow quantification, perfusion + viability; no radiation; (2) **Late gadolinium enhancement (LGE)**: extracellular gadolinium accumulates in expanded extracellular space (fibrosis, infarct) — appears bright on inversion-recovery imaging; patterns differentiate etiologies: - **Subendocardial/transmural** = infarct (vascular distribution); - **Mid-wall / patchy** = non-ischemic cardiomyopathy (DCM, sarcoid, myocarditis); - **Subepicardial/lateral wall** = myocarditis; - **Diffuse global** = amyloid (also characteristic — difficult to null myocardium); - **Septal/mid-wall stripe** = hypertrophic cardiomyopathy + DCM; (3) **T1 mapping + ECV (extracellular volume)**: quantitative measure of diffuse fibrosis (without need for LGE which detects only focal); native T1 elevated in fibrosis, amyloid, edema; (4) **T2 mapping + STIR**: edema (myocarditis, acute MI, sarcoidosis, takotsubo); (5) **T2*** for iron quantification (thalassemia, hemochromatosis); (6) **Stress CMR** (vasodilator — adenosine, regadenoson): perfusion + viability — alternative to nuclear stress test; (7) **Viability assessment**: hibernating myocardium (akinetic but viable — < 50% wall thickness LGE typically recovers post-revascularization); STICH trial — viability didn''t predict CABG benefit, but CMR remains useful clinically; (8) **Specific conditions**: - **Hypertrophic cardiomyopathy** — LV mass, LGE pattern, apical involvement; - **Cardiac amyloid** — characteristic LGE pattern + difficulty nulling + diffuse ECV elevation; transthyretin (TTR) PYP scan for ATTR; - **Sarcoidosis** — patchy LGE + FDG-PET correlation; - **Myocarditis** — Lake Louise criteria (edema + early gad + LGE); - **ARVC** — fatty infiltration RV + dyskinesia + fibrosis; (9) **Multidisciplinary**: cardiology + cardiac imaging + electrophysiology + cardiothoracic surgery

---

CMR: gold standard volumes/EF + tissue characterization. LGE pattern differentiates ischemic (subendo/transmural) vs non-ischemic (mid-wall, subepi) cardiomyopathy. T1/T2/T2* mapping. Viability + stress perfusion. Lake Louise myocarditis.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'radiology'
  and scenario = 'ผู้ป่วยอายุ 50 ปี non-ischemic cardiomyopathy + LVEF 25% — CMR for tissue characterization + viability';

commit;
