-- ===============================================================
-- UPDATE chunk 3/8: family_medicine (25 questions)
-- ===============================================================

begin;

update public.mcq_questions
set choices = '[{"label":"A","text":"Universal PSA screening for all men"},{"label":"B","text":"Prostate Cancer Screening Shared Decision-Making (USPSTF + AUA + ACS)"},{"label":"C","text":"Never screen — too harmful"},{"label":"D","text":"Force decision without information"},{"label":"E","text":"DRE alone — sufficient screening"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Prostate Cancer Screening Shared Decision-Making (USPSTF + AUA + ACS): (1) **USPSTF 2018**: ages 55-69 — **individual shared decision**; > 70 — recommend against routine; (2) **Race + family history**: Black, family history early/lethal, BRCA1/2, Lynch — discuss earlier (45-50); (3) **Shared decision-making components**: - **Benefits**: ~ 1 in 1000 men aged 55-69 screened with PSA may avoid death from PC over 13 yr (ERSPC); - **Harms**: false positives (~ 75% of biopsies negative); overdiagnosis (~ 30-50%) → overtreatment (incontinence ~ 5-15%, ED ~ 30-70%, urinary/bowel from radiation/surgery); biopsy complications (bleeding, infection, sepsis 1-2%); anxiety; - Patient values + life expectancy ≥ 10 yr; (4) **PSA testing approach if chosen**: baseline + interval based on PSA (lower risk longer interval, 2-4 yr); free PSA, PSA density, PSA velocity, PHI, 4Kscore for ambiguous; (5) **Multi-parametric MRI prostate** before biopsy increasingly preferred (PRECISION trial); reduces unnecessary biopsy; (6) **Active surveillance** for low-risk PC (Gleason 6, low volume) — preferred over immediate treatment in most; avoids overtreatment harms; (7) **DRE** — independent value low; sometimes performed; (8) **Documentation** of shared decision; (9) **Multidisciplinary**: PCP + urology + radiation oncology + medical oncology + patient

---

Prostate screening: USPSTF — shared decision 55-69 yo. Discuss benefits + harms + values + life expectancy. Black + family history earlier. MRI before biopsy increasingly preferred. Active surveillance for low-risk. Multidisciplinary.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'family_medicine'
  and scenario = 'ผู้ป่วยชาย อายุ 60 ปี healthy, no family history, no LUTS; มาถามเรื่อง PSA screening';

update public.mcq_questions
set choices = '[{"label":"A","text":"Routine screening only"},{"label":"B","text":"Hereditary Breast Cancer Risk + Management (NCCN + USPSTF)"},{"label":"C","text":"Avoid genetic testing"},{"label":"D","text":"Wait until cancer develops"},{"label":"E","text":"Single mastectomy only — no genetic eval"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Hereditary Breast Cancer Risk + Management (NCCN + USPSTF): (1) **Genetic counseling + testing** — refer all with family history suggestive (USPSTF 2019): - 1st-degree relatives with BC ≤ 50, ovarian, male BC, bilateral, multiple in family, Ashkenazi Jewish; - Risk assessment tools (Tyrer-Cuzick, BRCAPRO); - Pre-test counseling on implications; (2) **BRCA1/2 carriers — lifetime risk**: breast ~ 60-70%, ovarian 40-60% (BRCA1) or 15-30% (BRCA2); also pancreatic, prostate, melanoma; (3) **High-risk surveillance**: - **Breast MRI annually** + mammogram annually starting **age 25-30** (alternate 6 mo apart); clinical breast exam q 6-12 mo; - **Ovarian** — transvaginal US + CA-125 q 6 mo from age 30 (suboptimal — RRSO preferred); (4) **Risk-reducing strategies**: - **Risk-reducing salpingo-oophorectomy (RRSO)** age 35-40 (BRCA1) or 40-45 (BRCA2) after childbearing — reduces ovarian + breast risk; - **Risk-reducing mastectomy** — 90%+ risk reduction; bilateral with/without reconstruction; - **Chemoprevention** (tamoxifen, raloxifene, aromatase inhibitor) — 50% risk reduction; (5) **Lifestyle**: physical activity, weight, alcohol limit, breastfeeding; (6) **Family cascade testing**: at-risk relatives; (7) **Lynch syndrome consideration** + other hereditary syndromes; (8) **Psychosocial support**: high anxiety; counseling, support groups; (9) **Insurance coverage** for genetic + screening (GINA prohibits discrimination); (10) **Multidisciplinary**: PCP + genetic counselor + breast surgery + gyn oncology + medical oncology + plastic surgery + mental health

---

BRCA family history: genetic counseling + testing. Carriers — MRI + mammo annually from 25-30; RRSO 35-45; risk-reducing mastectomy; chemoprevention. Cascade testing. Multidisciplinary high-risk clinic.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'family_medicine'
  and scenario = 'ผู้หญิงอายุ 40 ปี — mother + sister with breast cancer (age 45, 50); แม่ + ป้าได้รับ BRCA1 mutation';

update public.mcq_questions
set choices = '[{"label":"A","text":"Colonoscopy only or no screening"},{"label":"B","text":"CRC Screening Modality Choice (USPSTF + ACS)"},{"label":"C","text":"MRI as primary screen"},{"label":"D","text":"Abdominal X-ray screening"},{"label":"E","text":"No screening if family history negative"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** CRC Screening Modality Choice (USPSTF + ACS): (1) **Start age 45** (USPSTF + ACS 2021 — lowered from 50 due to young-onset CRC rise) through age 75; ages 76-85 individualized; > 85 not recommended; (2) **Multiple effective modalities** — best test = one patient will do consistently: - **Colonoscopy q 10 yr** — gold standard, can remove polyps, longest interval, requires prep + sedation + day off + small perforation risk; - **FIT (fecal immunochemical test)** annual — stool antigen, no prep, mail-in, low cost; abnormal → colonoscopy; - **gFOBT (guaiac)** annual — older, less sensitive than FIT, dietary restrictions; - **FIT-DNA (Cologuard)** q 3 yr — combined FIT + DNA mutations; higher sensitivity, higher cost + false positives; abnormal → colonoscopy; - **CT colonography** q 5 yr — non-invasive imaging, prep, incidental findings, radiation; abnormal → colonoscopy; - **Flexible sigmoidoscopy** q 5 yr (or q 10 + FIT annual) — limited to distal colon; (3) **Programmatic approach** — annual FIT in many primary care; high participation = best outcomes; (4) **Shared decision** — discuss options, preferences; (5) **High-risk (family history, IBD, polyposis, Lynch)** — earlier + more frequent + colonoscopy preferred; (6) **Reminders + outreach** in EHR + population health; (7) **Multidisciplinary**: PCP + GI + pathology + surgery + cancer center

---

CRC screening: start 45 (USPSTF 2021). Multiple options — best = one patient does. FIT annual common primary care; colonoscopy q 10 yr gold standard; FIT-DNA, CT colonography, sigmoidoscopy alternatives. Shared decision. Programmatic approach.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'family_medicine'
  and scenario = 'ผู้ป่วยอายุ 50 ปี average risk, ไม่อยากทำ colonoscopy; ถามทางเลือก';

update public.mcq_questions
set choices = '[{"label":"A","text":"Start vaccines from birth"},{"label":"B","text":"Pediatric Catch-Up Vaccination (CDC + ACIP)"},{"label":"C","text":"Skip vaccines — child too old"},{"label":"D","text":"One vaccine at a time over years"},{"label":"E","text":"Wait for school requirement"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Pediatric Catch-Up Vaccination (CDC + ACIP): (1) **General principles**: vaccinate immediately + complete catch-up; minimum intervals between doses; live vaccines together or 4 wk apart; documented vaccines accepted even from other countries (if written + dates match schedule); (2) **Approach to no records**: assume unvaccinated; CDC catch-up schedule; serologic testing limited role (controversial — extra cost, not for all); (3) **At age 5 — catch-up to give**: - **DTaP** — 4 doses (4-6 wk apart × 3, then 6 mo); 5th dose age 4-6; - **IPV (polio)** — 4 doses; - **MMR** — 2 doses 28 d apart; - **Varicella** — 2 doses 3 mo apart; - **HepB** — 3-dose series (0, 1, 6 mo); - **HepA** — 2 doses 6 mo apart; - **Hib** — usually not needed > 59 mo unless immunocompromised/asplenic; - **PCV (pneumococcal conjugate)** — usually not > 59 mo unless high-risk; - **Influenza** annually (first time: 2 doses 4 wk apart); - **COVID-19** per current recommendations; (4) **Future per schedule**: HPV starting 9-11, Tdap age 11, meningococcal 11 + 16, COVID, flu; (5) **Address parental concerns + vaccine hesitancy**: presumptive approach, motivational interviewing, evidence-based information, share own decisions, school requirements; (6) **Multiple vaccines same visit OK + recommended**; (7) **Document** in state immunization registry; (8) **Insurance + VFC (Vaccines for Children)** — free for eligible; (9) **Multidisciplinary**: PCP + pharmacy + public health + school nurse

---

Pediatric catch-up: CDC schedule, assume unvaccinated, start immediately. Multiple vaccines safe + recommended. Document + state registry. Address hesitancy. VFC free for eligible. Multidisciplinary.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'family_medicine'
  and scenario = 'เด็กชาย 5 ปี ย้ายมาจากต่างประเทศ — ไม่มีบันทึกวัคซีน, healthy';

update public.mcq_questions
set choices = '[{"label":"A","text":"No pneumococcal vaccine needed"},{"label":"B","text":"Adult Pneumococcal Vaccination (ACIP 2024 Update)"},{"label":"C","text":"PPSV23 alone only"},{"label":"D","text":"Wait until acute pneumonia"},{"label":"E","text":"Repeat every year"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Adult Pneumococcal Vaccination (ACIP 2024 Update): (1) **2 vaccines available**: - **PCV (pneumococcal conjugate)**: PCV15, PCV20 (now preferred over older PCV13); - **PPSV23 (polysaccharide)**: 23 serotypes; (2) **2022-2024 ACIP simplification**: - **Adults ≥ 65 yo** (or 19-64 + high-risk condition) who have not received pneumococcal vaccine: - **Option 1 (preferred — simpler)**: **PCV20 alone (single dose)**; - **Option 2**: **PCV15 followed by PPSV23** ≥ 1 yr later (8 wk if immunocompromised, CSF leak, cochlear implant); - Patient นี้: COPD + DM + age 66 → PCV20 single dose preferred; (3) **Previously vaccinated complex algorithms** — refer CDC chart; PCV20 single dose often appropriate to update; (4) **High-risk 19-64 yo indications**: chronic heart/lung/liver disease, DM, smokers, alcoholism, asplenia, CSF leak, cochlear implant, immunocompromised, CKD/dialysis, HIV, malignancy; (5) **Co-administration**: can give with flu, COVID, RSV, Tdap, shingles — different sites; (6) **Documentation** + state registry; (7) **Address hesitancy + concerns**: efficacy data, safety profile (mild local reaction common, serious AE rare); (8) **Cost coverage**: Medicare Part B + most insurance; (9) **Pharmacist role** — significant in adult vaccinations; (10) **Multidisciplinary**: PCP + pharmacy + public health

---

Pneumococcal vaccine adult ACIP 2024 simplified: PCV20 single dose preferred for vaccine-naive ≥ 65 or 19-64 high-risk. Alternative PCV15 + PPSV23. Co-admin with other vaccines OK. Pharmacist role.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'family_medicine'
  and scenario = 'ผู้ป่วยอายุ 66 ปี COPD + DM, ยังไม่เคยฉีด pneumococcal vaccine';

update public.mcq_questions
set choices = '[{"label":"A","text":"Broad-spectrum antibiotic for all URIs"},{"label":"B","text":"Acute Viral URI — Antibiotic Stewardship (CDC + ACP + IDSA)"},{"label":"C","text":"Steroid taper for cold symptoms"},{"label":"D","text":"Refer to ED for any URI"},{"label":"E","text":"Antiviral for all viral URIs regardless"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Acute Viral URI — Antibiotic Stewardship (CDC + ACP + IDSA): (1) **Most acute URI = viral** (rhinovirus, coronavirus, RSV, influenza, parainfluenza) — antibiotic NOT effective + harmful; common cold typically 7-10 d, cough may last 3 wk; (2) **No antibiotic for**: acute bronchitis, common cold, viral pharyngitis, sinusitis < 10 d without severe/worsening symptoms, viral conjunctivitis; (3) **Bacterial considerations**: - **Strep pharyngitis**: Centor/McIsaac score (fever, tonsillar exudate, anterior cervical LN, no cough, age 3-14) — RADT/throat culture if ≥ 2-3; treat penicillin/amoxicillin × 10 d; - **Acute bacterial sinusitis**: > 10 d, severe (fever > 39, purulent + facial pain ≥ 3 d), worsening after improving; amoxicillin-clavulanate first-line; - **Acute otitis media**: amox high-dose; - **Influenza**: oseltamivir if within 48 h + high-risk; - **COVID**: Paxlovid + Pediatric considerations; (4) **Symptomatic treatment**: rest, fluids, humidified air, saline nasal, OTC decongestant/antihistamine/NSAIDs (use with caution in elderly + HT), throat lozenge, honey for cough (> 1 yr); (5) **Patient counseling**: viral nature, expected duration, when to return (worsening, high fever, severe symptoms, > 10 d no improvement); (6) **Antibiotic stewardship**: shared decision aids, communication training, delayed prescription strategy (give script but try without first); (7) **Public health**: hand hygiene, mask in vulnerable, stay home, vaccination (flu, COVID); (8) **Multidisciplinary**: PCP + pharmacy + public health

---

Acute URI: mostly viral — NO antibiotic. Treat symptoms. Distinguish bacterial (strep, sinusitis ≥ 10d/severe, AOM) — specific abx. Antibiotic stewardship. Patient counseling on expected course + return criteria.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'family_medicine'
  and scenario = 'ผู้ป่วยอายุ 35 ปี ไอ + เจ็บคอ + คัดจมูก × 4 วัน, no fever, no purulent sputum; ขอ antibiotic';

update public.mcq_questions
set choices = '[{"label":"A","text":"Fluoroquinolone first-line for simple cystitis"},{"label":"B","text":"Uncomplicated Acute Cystitis (IDSA 2010 + Updates)"},{"label":"C","text":"Long-course IV antibiotic"},{"label":"D","text":"No antibiotic — observe"},{"label":"E","text":"Cystoscopy for first UTI"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Uncomplicated Acute Cystitis (IDSA 2010 + Updates): (1) **Diagnosis clinical** for classic symptoms (dysuria, frequency, urgency) in healthy non-pregnant women; urine dipstick (nitrite + leukocyte esterase) supports; routine culture not needed for uncomplicated first episode; (2) **First-line antibiotic** (consider local resistance): - **Nitrofurantoin** 100 mg BID × 5 d (avoid eGFR < 30, late pregnancy near term); - **TMP-SMX** DS BID × 3 d (avoid if local resistance > 20%, sulfa allergy, pregnancy 1st trimester + near term); - **Fosfomycin** 3 g single dose (less effective but convenient, expensive); - **Pivmecillinam** (where available); (3) **Avoid** for uncomplicated cystitis: - **Fluoroquinolones** (collateral damage, resistance, FDA warning — tendinopathy, AAA, peripheral neuropathy, mental health, hypoglycemia); - Beta-lactams (less effective than above) — only if alternatives unavailable; (4) **Phenazopyridine** symptomatic relief × 2-3 d (orange urine); (5) **Hydration + voiding**; (6) **Recurrent UTI** (≥ 2 in 6 mo or ≥ 3 in 12 mo): - Lifestyle (post-coital voiding, wiping, hydration, avoid spermicide); - Vaginal estrogen postmenopausal; - **Cranberry products** — modest evidence; - Methenamine hippurate alternative non-antibiotic; - Prophylactic antibiotic continuous or post-coital (select patients); (7) **Complicated UTI considerations**: pregnancy, male, structural/functional abnormality, immunocompromised, recent instrumentation, indwelling catheter → culture + longer course; (8) **Pyelonephritis features**: fever, flank pain, NV → admit or outpatient FQ/cipro × 7-14 d; (9) **Multidisciplinary**: PCP + urology if recurrent/complicated

---

Uncomplicated cystitis: clinical diagnosis. First-line nitrofurantoin / TMP-SMX (if local resist < 20%) / fosfomycin. Avoid FQ (collateral). Recurrent UTI: behavioral + vaginal estrogen + cranberry + non-abx options. Pyelo + complicated different.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'family_medicine'
  and scenario = 'ผู้หญิงอายุ 28 ปี healthy non-pregnant — dysuria + frequency × 2 d; no flank pain, no fever; first episode';

update public.mcq_questions
set choices = '[{"label":"A","text":"Outpatient management with NSAIDs"},{"label":"B","text":"Headache Red Flags + Acute Workup (AHS + AAN — SNOOP4 mnemonic)"},{"label":"C","text":"Migraine treatment without workup"},{"label":"D","text":"Discharge home — follow up 1 wk"},{"label":"E","text":"Treat as tension headache"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Headache Red Flags + Acute Workup (AHS + AAN — SNOOP4 mnemonic): (1) **Red flags (SNOOP4)**: - **S**ystemic: fever, weight loss, immunocompromised, malignancy → infection, vasculitis, malignancy; - **N**eurological: focal deficit, papilledema, AMS, seizure → stroke, mass, hemorrhage; - **O**nset sudden (thunderclap < 1 min to max) → SAH, RCVS, dissection; - **O**lder > 50 new → temporal arteritis, malignancy; - **P**ositional / **P**recipitated by Valsalva → ICP changes; - **P**apilledema; - **P**rogressive worsening; - **P**regnancy / postpartum → eclampsia, CVT, PRES; ผู้ป่วยนี้: fever + neck stiffness + photophobia = **meningitis** (bacterial, viral, fungal); (2) **Acute workup**: - **LP** (after CT if focal/AMS/papilledema) — CSF for cells, glucose, protein, culture, PCR (HSV, enterovirus, meningococcal), cryptococcal Ag (immunocompromised); - **CT head non-contrast** to rule out mass effect/herniation pre-LP; CT angiography if SAH suspected; - **MRI/MRA** more sensitive, esp meningitis complications, CVT, mass; - **Labs**: CBC, CMP, blood cultures × 2, coag; (3) **Empiric treatment IMMEDIATELY** if bacterial meningitis suspected (don''t delay for LP): - **Ceftriaxone 2 g IV + Vancomycin** for typical adult; - **Add ampicillin** if > 50 yo or immunocompromised (Listeria); - **Dexamethasone 10 mg IV** before/with first abx — reduces neuro sequelae (esp pneumococcal); - **Acyclovir IV** if HSV suspected; (4) **Isolation** until bacterial cause excluded; (5) **Post-exposure prophylaxis** for close contacts (meningococcal — rifampin, ciprofloxacin, ceftriaxone); (6) **Public health notification** for reportable meningitis (meningococcal, others); (7) **ICU admission** for severe; (8) **Multidisciplinary**: PCP/ER + neurology + ID + ICU + public health

---

Headache SNOOP4 red flags → emergent workup. Fever + neck stiffness + photophobia = meningitis. Empiric ceftriaxone + vanco + dex IMMEDIATELY (+ ampi > 50 yo); LP after CT if focal. Post-exposure prophylaxis. Public health.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'family_medicine'
  and scenario = 'ผู้ป่วยอายุ 45 ปี — headache ใหม่ × 1 wk + worst ever; fever 38.5, neck stiffness, photophobia';

update public.mcq_questions
set choices = '[{"label":"A","text":"Daily opioid for chronic headache"},{"label":"B","text":"Tension-Type Headache Management (AHS + IHS)"},{"label":"C","text":"Triptan for tension headache"},{"label":"D","text":"MRI for all headaches"},{"label":"E","text":"Long-term daily NSAIDs without monitoring"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Tension-Type Headache Management (AHS + IHS): (1) **Diagnosis**: bilateral, pressing/tightening, mild-moderate, not aggravated by activity; ≥ 10 episodes; no NV (mild possible); photophobia OR phonophobia possible (not both); not better explained by other; (2) **Subtypes**: infrequent episodic (< 1/mo), frequent episodic (1-14/mo), chronic (≥ 15/mo); (3) **Rule out red flags**: SNOOP4; this patient features classic; (4) **Acute treatment**: - **NSAIDs** (ibuprofen 400-800, naproxen 500) first-line; - **Acetaminophen** alternative; - **Combination analgesics with caffeine** — limit due to medication overuse headache risk; - **Avoid**: opioids, butalbital, frequent over-the-counter (> 10-15 d/mo → medication overuse headache); (5) **Preventive if frequent/chronic**: - **Amitriptyline** 10-100 mg HS first-line (TCA); - Mirtazapine, venlafaxine alternatives; - **Behavioral therapy**: CBT, biofeedback, relaxation; - **Physical therapy** — neck/shoulder + posture; - **Acupuncture, massage**; - **Mindfulness, yoga**; (6) **Address triggers**: stress (CBT, mindfulness), sleep (regular), caffeine, dehydration, posture, eye strain (vision check), TMJ; (7) **Comorbidity**: depression, anxiety, insomnia, chronic neck pain; (8) **Medication overuse headache** workup + management — withdraw overused, transitional therapy; (9) **Multidisciplinary**: PCP + behavioral health + PT + neurology if refractory

---

Tension headache: bilateral pressing, mild-mod. Acute NSAIDs/acetaminophen; avoid opioids. Preventive amitriptyline + behavioral (CBT, biofeedback, relaxation) + PT + acupuncture. Address triggers + comorbidity. MOH important. Multidisciplinary.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'family_medicine'
  and scenario = 'ผู้ป่วยอายุ 35 ปี — bilateral pressing headache × 2-3 ครั้ง/wk × หลายเดือน, mild-moderate, no nausea, no aura; stress at work';

update public.mcq_questions
set choices = '[{"label":"A","text":"NSAIDs and outpatient PT"},{"label":"B","text":"Cauda Equina Syndrome — Emergency (ACP + AANS)"},{"label":"C","text":"MRI in 2 weeks routine"},{"label":"D","text":"Discharge with bedrest"},{"label":"E","text":"Chiropractic adjustment"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Cauda Equina Syndrome — Emergency (ACP + AANS): (1) **Red flag emergency**: cauda equina syndrome (CES) — surgical emergency to prevent permanent dysfunction; (2) **Classic features**: - Saddle anesthesia (perineum, perianal, genitals); - Bladder dysfunction (urinary retention with overflow, or incontinence); - Bowel dysfunction (incontinence, decreased tone); - Bilateral lower extremity radiculopathy + weakness; - Sexual dysfunction; - Reduced anal tone, decreased rectal sensation; (3) **Other LBP red flags** beyond mechanical: - Trauma (this patient — fall); - Malignancy (history, weight loss, > 50 yo, refractory pain); - Infection (fever, IV drugs, immunocompromised); - Fracture (osteoporosis, steroid, trauma); - AAA (pulsatile mass, > 60 yo, vascular risk); - Ankylosing spondylitis (young, morning stiffness, improves with exercise); (4) **Emergency workup**: - **Urgent MRI lumbar spine** — emergent; CT myelography if MRI CI; - Post-void residual; - Neurologic exam — sensory (perineal), motor, reflexes, anal tone, anal wink; - Labs as indicated; (5) **Emergent neurosurgery consult**: surgical decompression within 24-48 h for best outcomes (some advocate < 24 h); (6) **Bladder catheterization** for retention; (7) **Avoid sending home** — admit; (8) **Documentation** of exam + timing; (9) **Multidisciplinary**: PCP/ED + neurosurgery/ortho spine + radiology + urology + rehab

---

Cauda equina syndrome = surgical emergency. Saddle anesthesia + bladder/bowel + bilateral leg deficit. URGENT MRI + neurosurgery within 24-48 h for decompression. Catheterize. Admit. Don''t miss in primary care.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'family_medicine'
  and scenario = 'ผู้ป่วยอายุ 55 ปี — LBP + saddle anesthesia + new urinary retention × 2 d; recent fall';

update public.mcq_questions
set choices = '[{"label":"A","text":"Empiric antibiotic for all sore throats"},{"label":"B","text":"Acute Pharyngitis — Strep Workup + Treatment (IDSA + AAP)"},{"label":"C","text":"Skip test — clinical alone"},{"label":"D","text":"Fluoroquinolone first-line"},{"label":"E","text":"No treatment if positive"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Acute Pharyngitis — Strep Workup + Treatment (IDSA + AAP): (1) **Centor/McIsaac score**: fever > 38, no cough, anterior cervical LN, tonsillar exudate, age (3-14 +1, > 45 -1); score ≥ 2-3 → test; (2) **Testing**: **RADT (rapid antigen detection test)** first; if negative + Centor ≥ 3 in adolescents/children → throat culture; ในผู้ใหญ่ negative RADT มัก reliable; PCR available; (3) **Don''t treat empirically without test** unless contraindications testing; (4) **Treatment if positive GAS**: - **Penicillin V 500 mg BID/TID × 10 d** first-line (gold standard); - **Amoxicillin 1g daily × 10 d** alternative (better taste pediatric); - **PCN allergy**: cephalexin (low cross-reactivity if no anaphylaxis), azithromycin × 5 d, clindamycin; resistance increasing; (5) **Goals of treatment**: reduce duration symptoms 1-2 d, reduce transmission, prevent acute rheumatic fever (rare in resourced settings), prevent suppurative complications (PTA, lymphadenitis), reduce post-strep GN (limited); (6) **Symptomatic**: NSAIDs/acetaminophen, hydration, throat lozenge, saltwater gargle; (7) **Return to school/work**: 24 h after antibiotic + afebrile; (8) **Recurrent pharyngitis**: consider carrier vs true infection; tonsillectomy criteria (Paradise — ≥ 7 episodes in 1 yr, ≥ 5/yr × 2 yr, ≥ 3/yr × 3 yr); (9) **Complications watch**: PTA (peritonsillar abscess) — needs drainage; scarlet fever, post-strep GN, rheumatic fever; (10) **Multidisciplinary**: PCP + ENT if recurrent

---

Pharyngitis: Centor + RADT (culture if negative children). Positive GAS → penicillin V × 10 d (amox alternative). Pen allergy: cephalosporin/macrolide. Reduces sx duration + transmission + complications. Symptomatic care. Recurrent: tonsillectomy criteria.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'family_medicine'
  and scenario = 'ผู้ป่วยอายุ 25 ปี — เจ็บคอ × 2 d, fever 38.8, tonsillar exudate, anterior cervical LN tenderness, no cough, no coryza; Centor 4';

update public.mcq_questions
set choices = '[{"label":"A","text":"No treatment ever"},{"label":"B","text":"Acute Otitis Media Pediatric (AAP 2013 + 2022 Update)"},{"label":"C","text":"Topical drops only for AOM"},{"label":"D","text":"Long-term prophylactic antibiotic routine"},{"label":"E","text":"Immediate tympanostomy for first episode"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Acute Otitis Media Pediatric (AAP 2013 + 2022 Update): (1) **Diagnostic criteria**: middle ear effusion + signs of inflammation (bulging TM, otorrhea not from external) + moderate-severe symptoms; (2) **Severe AOM**: T > 39, severe otalgia ≥ 48 h, otorrhea, bilateral (< 2 yo); (3) **Treatment decision**: - **< 6 mo**: always treat; - **6 mo - 2 yo**: treat if certain diagnosis + bilateral or severe; observation option if non-severe + unilateral + reliable follow-up; - **≥ 2 yo**: observation option × 48-72 h with rescue Rx prescription (SNAP — Safety Net Antibiotic Prescription) if non-severe; treat if severe; - ผู้ป่วยนี้: 2 yo + severe → **treat**; (4) **Antibiotic of choice**: - **Amoxicillin high-dose 80-90 mg/kg/d divided BID × 10 d** first-line; (≤ 5 yo or severe — 10 d; > 6 yo non-severe — 5-7 d); - **Amoxicillin-clavulanate** if recent abx (90 d), concurrent purulent conjunctivitis (likely H. influenzae), treatment failure 48-72 h; - **PCN allergy**: cefdinir, cefuroxime, cefpodoxime (low cross-reactivity); macrolide (azithromycin × 5 d) — increasing resistance; ceftriaxone IM × 1-3 d severe; (5) **Symptomatic**: ibuprofen/acetaminophen for pain; **avoid topical analgesics in unperforated TM** (controversial); (6) **Follow-up**: improvement 48-72 h; if not → reassess + change abx; (7) **Recurrent AOM** (≥ 3 in 6 mo or ≥ 4 in 12 mo): consider tympanostomy tubes; (8) **Prevention**: pneumococcal + flu vaccine, breastfeeding, avoid tobacco smoke, daycare considerations, no bottle while supine; (9) **Multidisciplinary**: PCP + ENT if recurrent/persistent effusion

---

Pediatric AOM: criteria (effusion + inflammation + sx). Treat < 6 mo, severe, bilateral young. Observation option non-severe + reliable F/U. **Amoxicillin high-dose** first-line × 10 d; amox-clav if treatment failure/recent abx. Vaccines for prevention.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'family_medicine'
  and scenario = 'เด็กชาย 2 ปี — fever 39.0 + ear pain + bulging TM with effusion; severe symptoms';

update public.mcq_questions
set choices = '[{"label":"A","text":"Antibiotic for any sinusitis < 10 days"},{"label":"B","text":"Acute Sinusitis (IDSA + AAFP 2012 + ICAR 2021)"},{"label":"C","text":"No antibiotic ever — always viral"},{"label":"D","text":"CT imaging for every case"},{"label":"E","text":"Steroid burst alone"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Acute Sinusitis (IDSA + AAFP 2012 + ICAR 2021): (1) **Acute bacterial rhinosinusitis (ABRS) criteria** — any 1 of: - **Persistent** symptoms ≥ 10 d without improvement; - **Severe** symptoms (T > 39, purulent + facial pain ≥ 3-4 d at onset); - **Worsening** after initial improvement (double-sickening — this patient); (2) **No imaging** for uncomplicated; CT only for complications, surgical, or recurrent/chronic; (3) **Common pathogens**: S. pneumoniae, H. influenzae, M. catarrhalis; (4) **Antibiotic first-line**: - **Amoxicillin-clavulanate** standard adult dose 875/125 BID × 5-7 d (or 5-10 d kids); IDSA prefers amox-clav over amox alone for better H. flu coverage + beta-lactamase; - **PCN allergy**: doxycycline (adult), respiratory fluoroquinolone (levofloxacin) — reserve; pediatric — cefuroxime, cefpodoxime, cefdinir, clindamycin + cefixime combo; - Macrolides + TMP-SMX — high resistance, NOT recommended empirically; (5) **High-dose amox-clav (2g/125 BID)** if: severe, > 65 yo, recent hospitalization, recent antibiotics, immunocompromised, daycare; (6) **Symptomatic adjuncts**: saline irrigation (good evidence), intranasal steroid (modest), decongestants (limit < 3 d, rebound), analgesics; (7) **Reassess 48-72 h**: if no improvement → change abx (amox-clav high-dose, FQ); (8) **Complications watch** (rare but serious): orbital cellulitis, cavernous sinus thrombosis, meningitis, brain abscess, Pott''s puffy tumor — urgent CT + ENT/neurosurgery + IV abx; (9) **Chronic sinusitis (> 12 wk)**: different management, ENT referral, intranasal steroids, irrigation, possibly endoscopic surgery; (10) **Multidisciplinary**: PCP + ENT chronic/complications

---

ABRS criteria: persistent ≥ 10 d, severe ≥ 3-4 d at onset, or worsening (double-sickening). Amox-clav first-line. Saline irrigation + intranasal steroid. Reassess 48-72 h. Watch complications. Chronic sinusitis — ENT.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'family_medicine'
  and scenario = 'ผู้ป่วยอายุ 40 ปี — nasal congestion + facial pain × 12 d, ไม่ดีขึ้น, purulent rhinorrhea เพิ่ม + fever กลับมา; no severe sx initially';

update public.mcq_questions
set choices = '[{"label":"A","text":"Topical antibiotic for all conjunctivitis"},{"label":"B","text":"Conjunctivitis Differential + Management (AAO + AAFP)"},{"label":"C","text":"Topical steroid first-line"},{"label":"D","text":"Patch eye for treatment"},{"label":"E","text":"Ignore vision change"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Conjunctivitis Differential + Management (AAO + AAFP): (1) **Differentiate by features**: - **Viral** (most common — adenovirus): watery discharge, often URI + preauricular LN, bilateral progression, highly contagious; - **Bacterial**: purulent thick discharge, usually unilateral start, sticky lids; - **Allergic**: itching prominent, bilateral, watery, often other atopy; - **Gonococcal/chlamydial**: severe purulent, sexually active, neonatal; - **Herpes simplex/zoster**: vesicles, dendritic ulcer, severe — refer urgent; (2) **Red flags requiring ophthalmology**: severe pain, vision loss, photophobia (vs comfort), contact lens use (Pseudomonas, Acanthamoeba), corneal involvement, herpes suspected, hyperacute purulent (gonococcal), failure to improve; (3) **Viral conjunctivitis**: - Supportive: cool compress, artificial tears, hand hygiene, separate towels, no shared items; - Contagious 10-14 d; school/work return when discharge resolved (controversial); - No antibiotic effective; (4) **Bacterial conjunctivitis**: - Most self-limited; abx shortens duration; - **Topical**: erythromycin ointment, polymyxin-trimethoprim, gentamicin, fluoroquinolone (moxifloxacin, ofloxacin) — reserve for contact lens or severe; - Avoid neomycin (allergy), gentamicin can be corneal-toxic; - Pediatric concurrent otitis (H. flu) → systemic abx; (5) **Allergic**: topical antihistamine-mast cell stabilizer (olopatadine, ketotifen), cold compress, allergen avoidance; oral antihistamine; severe — topical steroid by ophthalmology; (6) **STI-related** (gonococcal/chlamydial): adult + sexual exposure → IM ceftriaxone + oral azithromycin/doxy + ophthalmology; neonatal → admit + IV abx; (7) **Multidisciplinary**: PCP + ophthalmology referral red flags; STI + public health if relevant

---

Conjunctivitis: differentiate viral (watery, URI, preauricular LN) vs bacterial (purulent) vs allergic (itchy) vs HSV/gonococcal (urgent). Red flags → ophthalmology. Viral — supportive. Bacterial — topical abx selective. Allergic — topical antihistamine.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'family_medicine'
  and scenario = 'ผู้ป่วยอายุ 8 ปี — bilateral red eye + watery discharge × 2 d, no pain, no vision change; URI symptoms; ไม่มี contact lens';

update public.mcq_questions
set choices = '[{"label":"A","text":"Broad-spectrum antibiotic empirically"},{"label":"B","text":"Acute Infectious Gastroenteritis (IDSA 2017 + WHO)"},{"label":"C","text":"IV fluids only — no oral"},{"label":"D","text":"Strict BRAT diet × 1 week"},{"label":"E","text":"Anti-motility for bloody diarrhea"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Acute Infectious Gastroenteritis (IDSA 2017 + WHO): (1) **Most acute diarrhea = viral self-limited** (norovirus, rotavirus, adenovirus); no abx needed; (2) **Severity assessment**: dehydration (vital signs, mucous membranes, skin turgor, urine output, mental status, weight loss); (3) **Oral rehydration therapy (ORT) first-line** — WHO ORS or commercial; preferred over IV for mild-moderate; small frequent sips; (4) **Diet**: resume regular diet ASAP (BRAT diet outdated); avoid lactose if intolerance, sugary drinks alone, alcohol; (5) **Anti-motility (loperamide)** — OK for non-bloody, non-febrile adult diarrhea; reduce duration + frequency; avoid in suspected invasive (fever, bloody) — risk megacolon, HUS extension (e.g., EHEC, C. diff); (6) **Antiemetic**: ondansetron for nausea; (7) **Antibiotic indications limited**: - Severe/persistent symptoms; - Immunocompromised; - Suspected/confirmed specific pathogens (Shigella, Salmonella severe, Campylobacter severe, traveler''s, cholera, C. diff); - Sepsis features; - **Empiric** ciprofloxacin/azithromycin not routinely recommended without specific indication; - **Avoid in suspected EHEC** (Shiga toxin) — increases HUS risk; (8) **Workup**: usually not needed if mild; stool studies (culture, O&P, C. diff PCR, viral PCR) for severe, prolonged > 7 d, bloody, immunocompromised, recent abx (C. diff), hospitalized, travel, outbreak; (9) **C. diff considerations**: recent abx, hospitalization, age > 65 — PCR/EIA stool toxin; treat oral vanco or fidaxomicin; (10) **Public health**: report outbreaks; food-handler exclusions; (11) **Prevention**: hand hygiene, food safety, water safety, vaccines (rotavirus pediatric, cholera selected, typhoid travel); (12) **Multidisciplinary**: PCP + ID + public health

---

Acute GE: mostly viral self-limited. ORT first. Resume diet ASAP. Loperamide for non-bloody adult OK; avoid invasive/EHEC. Antibiotic targeted not empiric. Workup for severe/prolonged/bloody/immunocompromised. C. diff considerations.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'family_medicine'
  and scenario = 'ผู้ป่วยอายุ 30 ปี — acute watery diarrhea 6-8 ครั้ง/d + cramping × 2 d, no fever, no blood, no recent travel/abx, mild dehydration';

update public.mcq_questions
set choices = '[{"label":"A","text":"Long-term benzodiazepine daily"},{"label":"B","text":"Chronic Insomnia Management (AASM 2017 + ACP)"},{"label":"C","text":"Diphenhydramine nightly"},{"label":"D","text":"Ignore — just need sleep"},{"label":"E","text":"Increase caffeine to function"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Chronic Insomnia Management (AASM 2017 + ACP): (1) **Diagnosis chronic insomnia disorder**: difficulty initiating/maintaining sleep ≥ 3x/wk × ≥ 3 mo + daytime impairment + not better explained by other; (2) **Comprehensive evaluation**: - Sleep diary 1-2 wk; - Comorbidity screen: depression, anxiety, OSA (STOP-BANG), RLS, chronic pain, medications (caffeine, alcohol, decongestant, BB, steroid), substances; - Medical: thyroid, menopause, prostate, CV; - Lifestyle: screen time, shift work, naps; (3) **First-line: CBT-I (Cognitive Behavioral Therapy for Insomnia)** — gold standard (ACP strong recommendation): - Stimulus control, sleep restriction, cognitive restructuring, sleep hygiene, relaxation; - In-person, group, digital (CBT-I apps — SHUTi, Sleepio, Somryst FDA-approved); - More effective than meds long-term + no SE; (4) **Sleep hygiene** important adjunct: regular schedule, dark cool bedroom, limit caffeine/alcohol/screens before bed, exercise (not late), bed for sleep + sex only; (5) **Pharmacotherapy if CBT-I unavailable/inadequate** — short-term + targeted: - **Newer agents preferred**: ramelteon (melatonin agonist), doxepin low-dose (sleep maintenance), suvorexant + lemborexant (DORAs — dual orexin receptor antagonists — newer + safer); - **Z-drugs** (zolpidem, eszopiclone) — short-term; risks: complex sleep behavior, falls elderly, dependence; - **Benzodiazepines AVOID** in chronic insomnia: addiction, falls, cognition, MV accidents, mortality (Beers criteria PIM); (6) **Avoid** OTC antihistamines (diphenhydramine — anticholinergic, tolerance, Beers); (7) **Address comorbidity**: depression (SSRI), pain, OSA (CPAP); (8) **Mindfulness, exercise, light therapy** evidence-based adjuncts; (9) **Patient education + non-stigmatizing**; (10) **Multidisciplinary**: PCP + behavioral health/sleep psychology + sleep medicine if refractory

---

Chronic insomnia: CBT-I first-line (ACP). Sleep hygiene. Pharmacotherapy short-term — DORAs/ramelteon/doxepin preferred; avoid benzo + diphenhydramine (Beers). Address comorbidity. Digital CBT-I accessible. Multidisciplinary.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'family_medicine'
  and scenario = 'ผู้ป่วยอายุ 45 ปี — insomnia × 6 mo, difficulty initiating sleep + frequent awakenings + daytime fatigue; ขอ benzodiazepine';

update public.mcq_questions
set choices = '[{"label":"A","text":"Long-term benzodiazepine daily"},{"label":"B","text":"Panic Disorder Management (APA + AAFP)"},{"label":"C","text":"Ignore — panic harmless"},{"label":"D","text":"Cardiac workup repeated indefinitely"},{"label":"E","text":"Avoidance behavior — stay home"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Panic Disorder Management (APA + AAFP): (1) **Diagnosis DSM-5**: recurrent unexpected panic attacks + ≥ 1 mo of persistent worry about attacks or maladaptive behavior change + not attributable to other; (2) **Medical workup**: TSH, EKG, electrolytes, CBC; ECG for chest sx; rule out cardiac, thyroid, pheochromocytoma (selected), substance use; (3) **First-line treatment** — combination preferred: - **SSRI** (sertraline, escitalopram, paroxetine FDA-approved) or SNRI (venlafaxine) — start LOW (e.g., sertraline 12.5-25 mg) to avoid initial activation; titrate weekly; full effect 4-6 wk; continue 1-2 yr after remission; - **CBT** for panic disorder — interoceptive exposure, cognitive restructuring, breathing retraining; equally effective as SSRI, more durable; - Combination CBT + SSRI most effective severe; (4) **Avoid long-term benzodiazepines**: short-term bridge OK (alprazolam, clonazepam) for severe acute, but addiction + tolerance + rebound; preferred short-acting low-dose; (5) **Lifestyle**: exercise, sleep, caffeine reduction, alcohol avoidance, mindfulness; (6) **Acute panic attack**: breathing techniques, grounding (5-4-3-2-1), reassurance, safe place; do not avoid; (7) **Comorbidity**: depression (high), other anxiety, substance use — screen + treat; (8) **Patient education**: panic not dangerous, sensations explained, avoidance maintains anxiety; (9) **Telehealth + apps** options for CBT (Woebot, Calm, Headspace, NICE-recommended digital CBT); (10) **Multidisciplinary**: PCP + behavioral health/psychiatry if complex + Collaborative Care

---

Panic disorder: SSRI/SNRI + CBT first-line. Avoid long-term benzo (bridge only). Lifestyle (caffeine, exercise). Education + breathing. Comorbidity. Digital CBT + Collaborative Care. Effective treatment widely available.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'family_medicine'
  and scenario = 'ผู้ป่วยอายุ 28 ปี — recurrent unexpected panic attacks (chest tightness, palpitation, choking, fear of dying) + persistent worry; medical workup negative';

update public.mcq_questions
set choices = '[{"label":"A","text":"Ignore — childhood condition only"},{"label":"B","text":"Adult ADHD Diagnosis + Treatment (DIVA + ACEM + APA)"},{"label":"C","text":"Long-term opioid for focus"},{"label":"D","text":"Random antidepressant without workup"},{"label":"E","text":"Avoid all medications"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Adult ADHD Diagnosis + Treatment (DIVA + ACEM + APA): (1) **DSM-5 criteria adult**: ≥ 5 of 9 inattention or hyperactivity-impulsivity symptoms persistent ≥ 6 mo + onset before age 12 + multiple settings + functional impairment + not better explained by other; (2) **Diagnostic workup**: clinical interview (DIVA-5 structured), self-report scales (ASRS), collateral history (parent, partner), school records if available; rule out mood, anxiety, sleep, substance use, hearing, thyroid; (3) **Comorbidity common** (~ 70%): depression, anxiety, substance use, learning disability, sleep disorder, autism spectrum; treat concurrently; (4) **Pharmacotherapy first-line**: - **Stimulants** (most effective) — methylphenidate (Ritalin, Concerta — long-acting preferred adult), amphetamine (Adderall, Vyvanse); start low + titrate; side effects (appetite, sleep, BP, HR, anxiety, rebound, abuse potential — Schedule II); BP/HR monitoring; - **Non-stimulants**: **atomoxetine** (Strattera — SNRI, non-controlled), **viloxazine** (Qelbree — newer), alpha-2 agonists (guanfacine, clonidine); useful if stimulant contraindicated, substance use risk, comorbidity (anxiety); - **Bupropion** off-label option; (5) **Behavioral interventions**: CBT for ADHD (specialized), coaching, executive function strategies, environmental modifications, mindfulness; (6) **Workplace/educational accommodations**: ADA; quiet space, breaks, written instructions; (7) **Cardiovascular evaluation** before stimulants: HR, BP, family/personal cardiac history; ECG if concerns; (8) **Substance use** screen + monitor (extended-release stimulants + non-stimulants if risk); (9) **Driving safety** counseling; (10) **Adult ADHD undertreated** — significant functional + QOL impact; (11) **Multidisciplinary**: PCP + psychiatry/psychology + ADHD coach + workplace/school + family + Collaborative Care

---

Adult ADHD: DSM-5 + structured interview + collateral. Stimulants first-line (long-acting preferred); non-stimulants (atomoxetine, viloxazine, alpha-2) alternatives. CBT + accommodations. Comorbidity. CV evaluation. Underdiagnosed adult.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'family_medicine'
  and scenario = 'ผู้ป่วยอายุ 30 ปี — chronic inattention + disorganization + impulsivity ตั้งแต่เด็ก + ส่งผลต่อ work + relationships';

update public.mcq_questions
set choices = '[{"label":"A","text":"Ignore alcohol use"},{"label":"B","text":"Alcohol Use Disorder (AUD) Primary Care Management (USPSTF + APA + SAMHSA)"},{"label":"C","text":"Long-term benzodiazepine maintenance"},{"label":"D","text":"Single intervention — no follow-up"},{"label":"E","text":"Cold-turkey withdrawal at home for severe AUD"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Alcohol Use Disorder (AUD) Primary Care Management (USPSTF + APA + SAMHSA): (1) **Screening**: USPSTF — all adults; AUDIT-C (3-item, ≥ 4 men, ≥ 3 women positive) or AUDIT (10-item, ≥ 8 risky); single-item NIAAA (heavy drinking day in past year); (2) **Brief intervention** (SBIRT framework) effective in primary care: - Personalized feedback, motivational interviewing, goal-setting, follow-up; - Even brief counseling reduces consumption; (3) **AUD diagnosis DSM-5**: ≥ 2 of 11 criteria over 12 mo; mild (2-3), moderate (4-5), severe (≥ 6); (4) **Pharmacotherapy (underused — only ~ 2% AUD treated with meds)**: - **Naltrexone** (oral 50 mg daily or **monthly injection Vivitrol**) — reduces cravings + heavy drinking; first-line; CI in opioid use; - **Acamprosate** — for abstinence maintenance; CI severe renal; - **Disulfiram** — aversion (vomiting with alcohol); requires motivation + supervision; - **Off-label**: topiramate, gabapentin, baclofen; (5) **Behavioral therapy**: CBT, motivational enhancement, 12-step facilitation (AA), group therapy, contingency management; combination meds + therapy best; (6) **Withdrawal management**: CIWA assessment; mild-moderate outpatient with benzodiazepine taper (e.g., chlordiazepoxide, lorazepam) + thiamine + folate + magnesium; severe / risk DTs / seizure history / pregnancy → inpatient; (7) **Address comorbidity**: depression (high), anxiety, PTSD, other substance use, chronic pain; (8) **Medical complications screen**: LFTs, hepatitis (HCV common), peripheral neuropathy, thiamine deficiency (Wernicke prevention), pancreatitis, cardiomyopathy, cancers, falls; (9) **Vaccinations**: HAV, HBV, pneumococcal; (10) **Recovery support**: AA, SMART Recovery, recovery housing, peer support specialists; (11) **Multidisciplinary**: PCP + behavioral health + addiction medicine + hepatology + social work

---

AUD: USPSTF screening (AUDIT-C). SBIRT brief intervention. **Naltrexone** first-line pharmacotherapy (underused). Acamprosate, disulfiram options. Behavioral therapy combo best. Withdrawal management. Comorbidity + complications. Multidisciplinary.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'family_medicine'
  and scenario = 'ผู้ป่วยอายุ 50 ปี — drinks 6-8 drinks/d × 10 yr, wants to cut down; AUDIT-C 8; LFT mild elevation';

update public.mcq_questions
set choices = '[{"label":"A","text":"Detoxification alone — no medication"},{"label":"B","text":"Opioid Use Disorder (OUD) Treatment (SAMHSA + ASAM)"},{"label":"C","text":"Long taper without MOUD"},{"label":"D","text":"Refuse to treat — moral failing"},{"label":"E","text":"Single-modality detox"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Opioid Use Disorder (OUD) Treatment (SAMHSA + ASAM): (1) **Diagnosis DSM-5**: ≥ 2 of 11 criteria over 12 mo; severity mild/moderate/severe; (2) **Medications for OUD (MOUD)** — gold standard, life-saving; > 50% reduction in mortality vs no medication: - **Buprenorphine** (sublingual, mono or with naloxone — Suboxone) — partial mu agonist; ceiling effect (safer); X-waiver REMOVED 2023 — any DEA-licensed prescriber can prescribe (MAJOR access expansion); start when in withdrawal (avoid precipitated); - **Methadone** — full mu agonist; opioid treatment programs (OTPs) only currently in US; effective; - **Naltrexone** (Vivitrol monthly injection) — opioid antagonist; requires 7-14 d abstinence first; less effective adherence-dependent; (3) **Choose based on**: patient preference, prior treatment, severity, comorbidity, access, pregnancy (methadone or buprenorphine preferred); (4) **Behavioral therapy adjunct**: CBT, contingency management, MI; but MOUD alone reduces mortality — don''t withhold for lack of therapy access; (5) **Harm reduction**: - **Naloxone** prescription/distribution — universal for opioid users + close contacts; intranasal Narcan, IM; OTC approved 2023; - Syringe service programs; - Drug checking (fentanyl test strips); - Safe consumption sites (limited US); (6) **Address comorbidity**: HIV, HCV (treat as Tx as P!), pain, mental health (depression, anxiety, PTSD), social (housing, employment); (7) **Pregnancy**: MOUD preferred (buprenorphine, methadone) over abstinence (relapse risk); manage neonatal opioid withdrawal; (8) **Avoid**: detoxification alone without MOUD (high relapse + mortality), shaming, stigma; (9) **Stigma reduction**: language matters (person-first, ''person with OUD'' not ''addict''); (10) **Multidisciplinary**: PCP + addiction medicine + behavioral health + ID + OB if pregnant + social work + recovery community

---

OUD: MOUD = buprenorphine (X-waiver removed 2023 — major access expansion), methadone (OTP), naltrexone — life-saving. Naloxone universal harm reduction. Behavioral adjunct. Pregnancy MOUD preferred. Address comorbidity + stigma. Multidisciplinary.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'family_medicine'
  and scenario = 'ผู้ป่วยอายุ 35 ปี — chronic opioid use, wants to stop; tolerance + withdrawal; +urine drug screen positive opioids';

update public.mcq_questions
set choices = '[{"label":"A","text":"Wait — should resolve naturally"},{"label":"B","text":"Postpartum Depression (PPD) (ACOG + AAP + USPSTF)"},{"label":"C","text":"Stop SSRI — unsafe for breastfeeding"},{"label":"D","text":"Single visit — no follow-up"},{"label":"E","text":"Ignore screening — too sensitive"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Postpartum Depression (PPD) (ACOG + AAP + USPSTF): (1) **Universal screening** — pregnancy + postpartum + well-child visits (mother) — USPSTF recommendation; **EPDS (Edinburgh Postnatal Depression Scale)** ≥ 10 positive screen, ≥ 13 likely depression; PHQ-9 alternative; (2) **Assess safety**: suicidal ideation (especially passive; suicide leading cause of postpartum mortality), thoughts of harming baby (postpartum psychosis emergency — different from PPD); (3) **Differential**: postpartum blues (transient < 2 wk), PPD, postpartum anxiety, postpartum OCD, postpartum PTSD, postpartum psychosis (rare 0.1% — emergency, psychiatric admission), bipolar (mood disorder may present postpartum); rule out medical (thyroid, anemia, sleep deprivation); (4) **Treatment**: - **Mild-moderate**: psychotherapy first-line (CBT, IPT); group, telehealth options; - **Moderate-severe**: SSRI + therapy combination: - **Sertraline first-line** in lactation (minimal breast milk transfer); - Other options: escitalopram, paroxetine; - **Brexanolone** (Zulresso) IV infusion — FDA-approved for PPD severe; - **Zuranolone** (Zurzuvae) — oral; FDA-approved 2023; faster onset; - Continue medications already taking effective (don''t stop SSRI for breastfeeding — risks of untreated depression > minimal medication effects); (5) **Lifestyle support**: sleep (challenging), exercise, social support, baby care help; (6) **Address SDOH**: childcare, financial, partner support, IPV; (7) **Lactation support** + breastfeeding continuation (safe with most SSRIs); (8) **Father postpartum depression** also common — screen; (9) **Postpartum visit comprehensive** — ACOG 2018 — ongoing care for 12 wk + transition; (10) **Multidisciplinary**: family medicine + OB + pediatrics + behavioral health + lactation + social work + family + peer support

---

PPD: universal screening (EPDS). Assess safety + rule out psychosis. Mild-mod — psychotherapy; mod-severe — SSRI (sertraline first-line lactation) + therapy; brexanolone/zuranolone severe new options. SDOH + lactation + father screening. Multidisciplinary.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'family_medicine'
  and scenario = 'ผู้ป่วยอายุ 30 ปี G1P1 postpartum 4 wk — sadness + tearfulness + insomnia + difficulty bonding with baby; EPDS 16; ไม่มี thoughts harming baby';

update public.mcq_questions
set choices = '[{"label":"A","text":"Combined OCP first-line postpartum < 21 days"},{"label":"B","text":"Postpartum Contraception (CDC US MEC + ACOG)"},{"label":"C","text":"No contraception until breastfeeding stops"},{"label":"D","text":"Surgery only option"},{"label":"E","text":"Same as pre-pregnancy regardless"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Postpartum Contraception (CDC US MEC + ACOG): (1) **Counseling**: discuss prenatal + postpartum + at first postpartum visit; LARC (long-acting reversible contraception) most effective; interpregnancy spacing 18-24 mo for best outcomes; (2) **Lactational Amenorrhea Method (LAM)** — exclusively breastfeeding + amenorrhea + < 6 mo postpartum → ~ 98% effective; but limited applicability; (3) **CDC US MEC categories**: 1 (no restriction), 2 (advantages > risks), 3 (risks > advantages — usually avoid), 4 (unacceptable risk); breastfeeding + postpartum + medical conditions affect choice; (4) **Options by timing**: - **Immediate postpartum (post-placental — within 10 min)**: IUD (Cu or LNG) — OK (slight ↑ expulsion); permanent (BTL); - **0-21 days postpartum**: avoid combined hormonal (estrogen) — VTE risk; **progestin-only OK** (POPs, DMPA, implant, LNG-IUD); (5) **3-6 wk postpartum**: combined hormonal contraception OK if no VTE risk + breastfeeding OK (concern milk supply less now); (6) **Permanent contraception**: BTL postpartum, salpingectomy, vasectomy partner; (7) **For this patient (HTN + DM history, breastfeeding)**: - **LARC preferred**: LNG-IUD (Mirena, Liletta, Kyleena, Skyla) or Cu-IUD or etonogestrel implant (Nexplanon); - Avoid combined hormonal (HTN US MEC 3-4 depending severity); - POPs OK; DMPA OK but consider DM (variable glucose effect); - Discuss permanent if family complete; (8) **Address barriers**: cost (most covered Medicaid + ACA), access, partner involvement; (9) **STI screening + condom use** for prevention; (10) **Future fertility planning**; (11) **Multidisciplinary**: family medicine + OB + pediatrics + nursing + family planning specialist if complex

---

Postpartum contraception: LARC preferred. CDC US MEC. Immediate postpartum IUD OK. 0-21 d avoid combined hormonal (VTE); progestin OK. HTN history → avoid combined; LARC, POPs OK. Counseling prenatal + postpartum.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'family_medicine'
  and scenario = 'ผู้ป่วยอายุ 30 ปี G2P2 — 4 wk postpartum, breastfeeding, ต้องการคุมกำเนิด; HTN + DM history';

update public.mcq_questions
set choices = '[{"label":"A","text":"Skip vaccines at 2 mo"},{"label":"B","text":"Month Well-Baby Visit (AAP Bright Futures)"},{"label":"C","text":"No anticipatory guidance"},{"label":"D","text":"Discharge — return age 1"},{"label":"E","text":"Solid food starting 2 mo"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** 2-Month Well-Baby Visit (AAP Bright Futures): (1) **Growth + nutrition**: weight, length, HC plotted; breastfeeding adequacy (8-12 feeds/d, wet diapers, weight gain); supplementation: vitamin D 400 IU/d breastfed (or partially), iron consider 4 mo; (2) **Vaccinations 2 mo (CDC schedule)**: - DTaP, IPV, Hib, PCV15/20, RV (rotavirus), HepB #2; - 4-6 simultaneous injections OK + recommended; combination vaccines available; - Pre-vaccination counseling: side effects (low-grade fever, irritability, local), benefit, schedule; acetaminophen pre-medication not recommended (may blunt immune response); (3) **Developmental surveillance**: social smile, cooing, head control improving, tracks; (4) **Anticipatory guidance**: - Sleep (back to sleep — SIDS prevention, no co-sleeping in same bed, safe sleep environment), - Feeding (continue breast or formula), - Safety (car seat rear-facing, smoke-free home, water temperature, hand hygiene), - Tummy time, - Reading + interaction, - Maternal mental health screening (PPD); (5) **Screen for**: maternal depression (EPDS/PHQ-9), domestic violence, smoking household, food/housing insecurity (SDOH); (6) **Newborn screen results** review (hearing, metabolic, CCHD); (7) **Bilirubin** post-discharge if not done; (8) **Dental + oral health** education early; first dental visit by age 1; (9) **Address concerns**: colic, reflux, sleep, behavior; reassurance + guidance; (10) **Schedule next**: 4 mo visit; sick visit education + when to call; (11) **Multidisciplinary**: PCP + lactation + maternal mental health + early intervention + social work as needed

---

2-mo WCV: growth + nutrition (vit D supplementation breastfed). Vaccines per CDC (DTaP, IPV, Hib, PCV, RV, HepB). Developmental surveillance. Anticipatory guidance (safe sleep, car seat). Maternal mental health + SDOH screening.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'family_medicine'
  and scenario = 'ทารกอายุ 2 mo — first well-baby visit หลังคลอด, breastfed + thriving';

update public.mcq_questions
set choices = '[{"label":"A","text":"Wait and see — boys talk later"},{"label":"B","text":"Developmental Delay + Autism Screening (AAP + AAFP)"},{"label":"C","text":"MRI brain immediately for all"},{"label":"D","text":"No intervention until school age"},{"label":"E","text":"Single workup test only"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Developmental Delay + Autism Screening (AAP + AAFP): (1) **Surveillance + screening**: developmental surveillance every WCV; **formal screening** at 9, 18, 30 mo (ASQ, PEDS); **autism-specific M-CHAT-R/F** at 18 + 24 mo; (2) **Red flags this child**: language delay (< 50 words age 2 + no 2-word phrases) + social communication concerns (joint attention, eye contact) — high autism concern; (3) **Workup approach**: - **Refer simultaneously** (don''t wait for evaluation to complete): - **Early Intervention (EI — Part C of IDEA)** — free under age 3, comprehensive evaluation, therapies (speech, OT, PT, ABA, family training); - **Audiology** — rule out hearing loss; - **Developmental-behavioral pediatrics or autism specialist** — formal evaluation with ADOS-2, ADI-R; - **Vision** evaluation if concerns; (4) **Medical workup**: comprehensive history + exam (dysmorphic features, neurological); selectively: - **Genetic**: chromosomal microarray (CMA — first-line), Fragile X testing; whole exome if specific features; - **Metabolic**: targeted if regression, dysmorphic, family history; - **Lead level** if exposure risk; - **TSH**; - **EEG** if seizures or regression; - **MRI brain** selected (microcephaly, neuro deficits); (5) **Family support**: education, resources, advocacy (CDC Learn the Signs); (6) **Address comorbidities**: GI, sleep, feeding issues, behavior (sensory, self-injury), anxiety; (7) **Don''t say wait-and-see** for delays at this age — early intervention has best evidence for outcomes; (8) **School transition** age 3 → Part B (IDEA) school services + IEP; (9) **Multidisciplinary**: PCP + EI team + DBP + speech-language pathologist + OT + audiology + genetics + family + community resources

---

Developmental delay + autism concern: don''t wait. Refer EI + audiology + DBP simultaneously. Workup: CMA + Fragile X + targeted. M-CHAT-R/F screening 18 + 24 mo. Family support + comorbidity. Early intervention critical. Multidisciplinary.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'family_medicine'
  and scenario = 'เด็กชายอายุ 24 mo — ยังไม่พูด 2-word phrase, vocab < 20 คำ, no joint attention, limited eye contact';

update public.mcq_questions
set choices = '[{"label":"A","text":"Medication alone — no behavior therapy"},{"label":"B","text":"Pediatric ADHD Diagnosis + Treatment (AAP 2019 + AACAP)"},{"label":"C","text":"Avoid all medication"},{"label":"D","text":"Single visit without school input"},{"label":"E","text":"Send to special school only"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Pediatric ADHD Diagnosis + Treatment (AAP 2019 + AACAP): (1) **DSM-5 criteria pediatric (< 17 yo)**: ≥ 6 of 9 inattention or hyperactivity-impulsivity symptoms × ≥ 6 mo + onset < age 12 + ≥ 2 settings + functional impairment; (2) **Diagnostic process**: clinical interview + standardized scales from multiple settings (Vanderbilt, Conners — parent + teacher); medical + developmental + behavioral history; observation; (3) **Rule out / co-occurring**: hearing, vision, sleep (OSA — adenoidectomy may help), iron deficiency, thyroid, lead, learning disability, anxiety, depression, trauma, autism spectrum, oppositional defiant, conduct, tic disorder; (4) **Age-based treatment AAP 2019**: - **4-5 yo**: **Behavioral therapy FIRST-LINE** (parent training in behavior management); methylphenidate only if behavioral inadequate + significant impairment; - **6-11 yo (this patient)**: **FDA-approved medication + behavioral therapy** + school accommodations; - **≥ 12 yo**: medication + behavioral + school; (5) **Medications**: - **Stimulants first-line** (methylphenidate or amphetamine) — extended-release preferred for adherence + diversion reduction; titrate to optimal; - **Non-stimulants**: atomoxetine, viloxazine, alpha-2 agonists (guanfacine ER, clonidine ER); for non-responders, side effects, comorbidity; (6) **Behavioral therapy**: parent training (Triple P, Incredible Years, PCIT), CBT older children, social skills, school-based; (7) **School**: 504 plan or IEP; accommodations (preferred seating, breaks, extended time, modified assignments); (8) **Monitor**: response, side effects, growth (height + weight every visit on stimulants), BP/HR, sleep, mood; (9) **Family support + education**: psychoeducation, parent training, family therapy as needed; (10) **Vision/hearing** evaluation; (11) **Multidisciplinary**: PCP + pediatric psychiatry/psychology + school (teachers, counselors) + family + community resources

---

Pediatric ADHD: DSM-5 + multi-setting scales (Vanderbilt, Conners). 4-5 yo behavioral first; 6+ yo medication + behavioral + school. Stimulants first-line (ER preferred). Monitor growth, BP, mood. School accommodations. Family training. Multidisciplinary.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'family_medicine'
  and scenario = 'เด็กชาย 8 ปี — ครูสังเกตเห็น inattention + impulsivity + hyperactivity at school + home; school performance ลดลง; symptoms ≥ 6 mo';

commit;
