-- ===============================================================
-- UPDATE chunk 4/8: family_medicine (25 questions)
-- ===============================================================

begin;

update public.mcq_questions
set choices = '[{"label":"A","text":"Ignore — pregnancy resolves it"},{"label":"B","text":"Hyperemesis Gravidarum vs Common NV in Pregnancy (ACOG)"},{"label":"C","text":"Anti-anxiety only"},{"label":"D","text":"Termination of pregnancy"},{"label":"E","text":"Long-term corticosteroid in 1st trimester"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Hyperemesis Gravidarum vs Common NV in Pregnancy (ACOG): (1) **NV of pregnancy (NVP)**: ~ 70-80% pregnancies, peak 6-12 wk, usually self-limited; (2) **Hyperemesis gravidarum (HG)**: severe NV + weight loss > 5% pregravid + dehydration + electrolyte/acid-base/ketones; affects 0.5-3%; (3) **PUQE score** (Pregnancy-Unique Quantification of Emesis) — assess severity, guide treatment; (4) **Workup**: vital signs, urine ketones, electrolytes, LFT, TSH (HCG cross-reactivity → hyperthyroid mimic), pregnancy US (rule out molar, multifetal); (5) **Stepwise treatment ACOG**: - **Lifestyle**: small frequent meals, bland/cold foods, ginger (effective), avoid triggers, hydration; - **Pyridoxine (B6) 10-25 mg q 6-8 h** first-line; - **+ doxylamine (combination Diclegis/Bonjesta)** FDA-approved pregnancy; - **Antihistamine**: dimenhydrinate, diphenhydramine; - **Dopamine antagonist**: promethazine, metoclopramide (Reglan — caution prolonged use); - **5HT3 antagonist**: ondansetron — effective but small ↑ risk birth defects (CHD, oral cleft) data mixed; use after others, after 10 wk preferred; - **Corticosteroid** (methylprednisolone) — severe refractory; avoid 1st trimester (oral cleft); - **IV hydration + electrolyte correction** + thiamine (Wernicke prevention) when dehydrated; - **Inpatient** if dehydration, electrolyte imbalance, weight loss not responding; (6) **Nutrition**: enteral tube feeding or TPN rarely needed; (7) **Comorbidity**: depression, anxiety screening; (8) **Antiemetics avoid**: ergot derivatives; phenothiazines selective; (9) **Multidisciplinary**: family medicine + OB + nutrition + behavioral health if needed

---

Pregnancy NV: stepwise. B6 + doxylamine first-line. Antihistamine + promethazine/metoclopramide. Ondansetron after others. IV hydration + thiamine if dehydrated. HG (> 5% weight loss) admit if needed. Multidisciplinary.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'family_medicine'
  and scenario = 'ผู้ป่วยอายุ 28 ปี G1P0 GA 10 wk — severe nausea + vomiting × 3 wk, weight loss 4 kg, dehydration';

update public.mcq_questions
set choices = '[{"label":"A","text":"Switch to formula immediately"},{"label":"B","text":"Breastfeeding Support + Common Issues (USBC + AAP + ABM)"},{"label":"C","text":"No lactation support — figure it out"},{"label":"D","text":"Stop all medications"},{"label":"E","text":"Single visit advice — no follow-up"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Breastfeeding Support + Common Issues (USBC + AAP + ABM): (1) **Universal counseling pregnancy + postpartum**: exclusive breastfeeding 6 mo + continued through 1-2 yr + complementary foods (WHO + AAP); benefits maternal + infant (decrease infection, allergy, obesity, SIDS, BC + ovarian CA); (2) **Common early issues**: - **Latch problems** — most common cause of nipple pain + low supply; lactation consultant urgent referral; correct latch + positioning; - **Engorgement** — frequent feeding, warm before, cold after, massage, no tight bra; - **Sore/cracked nipples** — latch correction (root cause), lanolin, expressed milk on nipples, brief drying, hydrogel pads; - **Tongue tie (ankyloglossia)** — assessment, frenotomy if functional; - **Mastitis** — pain + redness + warmth + fever; continue feeding (won''t harm baby), warm compress, anti-inflammatories, abx (dicloxacillin/cephalexin) if no improvement 12-24 h or systemic; rule out abscess; - **Plugged duct** — massage, warm, feed/pump; - **Low supply** — increase frequency, hydration, address latch + emptying, galactagogues (fenugreek limited evidence, domperidone outside US); rule out: insufficient glandular tissue, retained placenta, thyroid; (3) **Lactation consultant (IBCLC)** referral early; (4) **Workplace support**: pumping breaks, refrigeration, ACA workplace protections; (5) **Family education**: partner support, household help, realistic expectations; (6) **Maternal medications**: most safe (LactMed reference); avoid pseudoephedrine (decreases supply), some psych meds need consideration (sertraline preferred), chemotherapy CI; (7) **Special situations**: relactation, induced lactation (adoption), milk donation/banks; (8) **Maternal mental health**: postpartum depression affects breastfeeding + vice versa; treat both; (9) **Avoid early supplementation** unless medically indicated (decreases supply, nipple confusion); (10) **Multidisciplinary**: family medicine + OB + pediatrics + IBCLC + WIC + peer support (La Leche)

---

Lactation: latch + positioning most common cause of pain/low supply. IBCLC early. Mastitis: continue feeding + abx if needed. Workplace support. Most meds safe (LactMed). Avoid early supplementation. Address PPD. Multidisciplinary.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'family_medicine'
  and scenario = 'ผู้ป่วย G1P1 — 5 d postpartum — sore cracked nipples + low milk supply concerns + considering formula';

update public.mcq_questions
set choices = '[{"label":"A","text":"Bed rest to prevent falls"},{"label":"B","text":"Geriatric Falls Assessment + Prevention (CDC STEADI + AGS)"},{"label":"C","text":"Single intervention only"},{"label":"D","text":"Restrict all activity"},{"label":"E","text":"Ignore — falls expected age"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Geriatric Falls Assessment + Prevention (CDC STEADI + AGS): (1) **Falls leading cause of injury death** > 65 yo + significant morbidity; (2) **Screening** annually all ≥ 65 yo: fall in past year, fear of falling, gait/balance problem; (3) **Assessment if positive**: - **Gait + balance**: Timed Up and Go (TUG) > 12 sec, 30-sec chair stand, 4-stage balance; - **Medications** (FRIDs — Fall Risk-Increasing Drugs): benzodiazepines, opioids, anticholinergics, antihypertensives, antidepressants, antipsychotics, sleep aids; deprescribe (Beers, STOPP); - **Vision** (cataract, refractive, glaucoma); - **Feet + footwear**; - **Postural BP** (orthostatic hypotension); - **Cognitive** screen (MoCA, Mini-Cog); - **Comorbidity**: cardiac (arrhythmia, syncope), Parkinson''s, peripheral neuropathy, anemia, alcohol, depression; - **Home safety** assessment (lighting, rugs, stairs, bathroom — grab bars, raised seat); - **Vitamin D** (deficiency contributes); (4) **Multifactorial intervention** — most effective: - **Exercise** (strength, balance — tai chi, Otago, multifactorial PT programs); - Medication review + deprescribe; - Vision correction; - Home modification (OT home assessment); - Vitamin D supplementation if deficient; - Treat underlying conditions; (5) **Bone health**: DXA + osteoporosis treatment to prevent fracture from falls (fracture risk = falls × bone fragility); (6) **Assistive devices** appropriately (cane, walker — PT fit); avoid premature wheelchair (decreases mobility); (7) **Fear of falling** addressed (CBT, exercise programs); (8) **Post-fall syndrome** prevention; (9) **Caregiver education** + family involvement; (10) **Documentation in EHR + community resources** (senior centers, SilverSneakers); (11) **Multidisciplinary**: PCP + PT + OT + pharmacy + ophthalmology + community fall prevention programs (CDC STEADI implementation)

---

Geriatric falls: STEADI screening. Multifactorial assessment (gait, meds, vision, BP, cognition, home, vit D). Multifactorial intervention (exercise — tai chi, deprescribe, vision, home mods). Bone health. Multidisciplinary.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'family_medicine'
  and scenario = 'ผู้ป่วยอายุ 80 ปี — fall × 2 in past 6 mo, gait unsteady, on multiple medications, vision changes';

update public.mcq_questions
set choices = '[{"label":"A","text":"No workup — old age"},{"label":"B","text":"Dementia Workup Primary Care (AAN + Alzheimer''s Association)"},{"label":"C","text":"MMSE alone — sufficient"},{"label":"D","text":"Single visit referral to nursing home"},{"label":"E","text":"Antipsychotic first-line for BPSD"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Dementia Workup Primary Care (AAN + Alzheimer''s Association): (1) **Cognitive assessment**: - **Brief screening**: Mini-Cog (3-word recall + clock draw, ~ 3 min), MoCA (Montreal Cognitive Assessment, 30-pt, more sensitive than MMSE for MCI), MMSE; - **Formal neuropsychology** for unclear or specific subtype; (2) **Functional assessment**: ADL (Katz), IADL (Lawton) — IADL impaired before ADL; (3) **History from collateral source** essential (family, friend); insight often impaired; (4) **Diagnostic workup** rule out reversible causes (~10% — actually contributing more often, less commonly fully reversible): - **Labs**: TSH, B12, CBC, CMP, RPR (selected), HIV (selected); - **Imaging**: MRI brain (or CT) — rule out NPH (normal pressure hydrocephalus — gait, urinary, cognition triad), tumor, stroke, hematoma; structural; - **Depression screening** (pseudodementia mimics); - **Medication review** — anticholinergics, sedatives, opioids worsen cognition; - **Sleep apnea** screen; alcohol/substance; (5) **Subtype evaluation**: Alzheimer''s most common (insidious, memory predominant), vascular (stepwise, vascular risk), Lewy body (visual hallucinations, parkinsonism, REM behavior, fluctuations), frontotemporal (younger, behavior/language), mixed common; (6) **Newer biomarkers** (specialist): - CSF Aβ42, p-tau, t-tau; - Amyloid PET (rarely covered); - **Blood-based biomarkers** emerging (p-tau217 — very promising) — primary care use coming; (7) **Disclosure of diagnosis** to patient + family + planning; (8) **Treatment**: - **Cholinesterase inhibitors** (donepezil, rivastigmine, galantamine) — modest symptomatic benefit AD/Lewy; - **NMDA antagonist** memantine — moderate-severe AD; - **Anti-amyloid antibodies** (lecanemab Leqembi, donanemab) — disease-modifying for early AD with confirmed amyloid; specialist + monitoring (ARIA — amyloid-related imaging abnormalities); access + cost barriers; - **Non-pharmacologic**: cognitive engagement, exercise, social, music, environment, sleep, caregiver education; - **BPSD (behavioral + psychological symptoms)**: address triggers + non-pharm first; antipsychotic LAST resort (Black Box mortality); SSRI for depression; (9) **Caregiver support** essential — counseling, support groups, respite, education (REACH, Savvy Caregiver); (10) **Advance care planning + legal**: POA, advance directive, driving safety, financial planning; (11) **Safety**: driving evaluation, home safety, wandering (MedicAlert + Safe Return), medication safety; (12) **Multidisciplinary**: PCP + neurology/geriatrics + neuropsychology + social work + occupational therapy + caregiver + community (Alzheimer''s Association)

---

Dementia workup: cognitive (Mini-Cog/MoCA) + functional (ADL/IADL) + collateral. Rule out reversible (TSH, B12, MRI, depression, meds). Subtype matters. Treatment: ChEI/memantine; new anti-amyloid early AD. Non-pharm + caregiver support + advance care planning. Multidisciplinary.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'family_medicine'
  and scenario = 'ผู้ป่วยอายุ 78 ปี — family concerns about memory + repetition × 1 yr, missed appointments, gets lost in familiar areas; ADL ลดลง';

update public.mcq_questions
set choices = '[{"label":"A","text":"Benzodiazepine first-line for agitation"},{"label":"B","text":"Delirium Recognition + Management (American Geriatrics Society + CAM)"},{"label":"C","text":"Restrain patient"},{"label":"D","text":"No workup — confusion expected"},{"label":"E","text":"Antipsychotic monotherapy long-term"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Delirium Recognition + Management (American Geriatrics Society + CAM): (1) **CAM (Confusion Assessment Method)** for diagnosis: - 1. Acute onset + fluctuating course (required); - 2. Inattention (required); - 3. Disorganized thinking OR 4. Altered LOC; - 1+2 + (3 or 4) = delirium; (2) **Subtypes**: hyperactive (agitated — easier to recognize), hypoactive (lethargic — often missed, worse prognosis), mixed; (3) **Identify cause(s) — usually multifactorial**: - **DELIRIUMS mnemonic** / common: - **Drugs** (anticholinergic, sedatives, opioids, polypharmacy, withdrawal — alcohol, benzo); - **Electrolyte** (Na, Ca, glucose); - **Lack of drugs** (withdrawal); - **Infection** (UTI, pneumonia, sepsis — most common in elderly!); - **Reduced sensory input** (vision, hearing — provide aids); - **Intracranial** (stroke, hemorrhage, mass, meningitis); - **Urinary retention / fecal impaction**; - **Myocardial / metabolic** (MI, hypoxia, CO2 retention, thyroid); - **Sleep deprivation**; (4) **Workup** (targeted): vital signs + O2 + glucose, CBC, CMP, urinalysis + culture, CXR, EKG, TSH, B12; selected (CT head, LP, blood culture, drug levels); (5) **Non-pharmacologic FIRST + ALWAYS**: - **HELP (Hospital Elder Life Program)** + ABCDEF bundle; - Reorientation (clock, calendar, family); - Sensory aids (glasses, hearing aids); - Mobility + PT; - Sleep hygiene (minimize nighttime disruptions); - Hydration + nutrition; - Familiar caregivers + family at bedside; - Avoid restraints (worsen delirium); - Minimize tubes/lines; (6) **Pharmacologic LAST resort** for severe agitation + safety: - **Low-dose antipsychotic** (haloperidol 0.25-0.5 mg, risperidone, quetiapine) — short-term only; Black Box dementia mortality; QTc monitoring; - **Avoid benzodiazepines** (worsen delirium) EXCEPT alcohol/benzo withdrawal; (7) **Treat underlying cause**; (8) **Prognosis**: ~ 50% mortality 1 yr; functional decline; persistent cognitive impairment; (9) **Prevention** more important than treatment — multicomponent (HELP); (10) **Family education + caregiver support**; (11) **Multidisciplinary**: PCP + geriatrics + nursing + PT/OT + pharmacy + behavioral health + family

---

Delirium: CAM diagnosis. Hyperactive vs hypoactive (often missed). Multifactorial — identify causes (UTI, drugs, electrolyte, sensory). Non-pharm FIRST (HELP, ABCDEF, reorient, mobility, sleep). Antipsychotic LAST resort. Avoid benzo (except withdrawal). Prognosis serious. Multidisciplinary.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'family_medicine'
  and scenario = 'ผู้ป่วยอายุ 82 ปี — acute change in mental status × 3 d, fluctuating, inattention, disorganized thinking; baseline mild MCI';

update public.mcq_questions
set choices = '[{"label":"A","text":"Annual screening only"},{"label":"B","text":"MSM STI Screening + Prevention (CDC STI Treatment Guidelines 2021 + USPHS)"},{"label":"C","text":"Refuse to discuss sexual practices"},{"label":"D","text":"PrEP not needed for MSM"},{"label":"E","text":"Urethral only NAAT"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** MSM STI Screening + Prevention (CDC STI Treatment Guidelines 2021 + USPHS): (1) **Screening interval q 3-6 mo** if multiple/anonymous partners + condomless sex: - **HIV**: + 4th gen Ag/Ab; q 3-6 mo high-risk; - **Syphilis**: serology q 3-6 mo; - **Chlamydia + gonorrhea**: NAAT all anatomical sites where sex occurs (oropharyngeal, rectal, urethral); ~ 80% of asymptomatic infection at non-urethral sites; - **Hepatitis A + B + C**: HCV q 6-12 mo if HIV+ or PrEP user; vaccinate HAV/HBV if not immune; HCV more frequent if HIV +; - **HPV**: anal pap selective; (2) **PrEP (Pre-Exposure Prophylaxis)** for HIV — strongly recommend high-risk MSM: - **Daily oral** tenofovir-emtricitabine (Truvada or Descovy); - **On-demand** 2-1-1 dosing (PROUD/IPERGAY) — alternative for MSM; - **LAI cabotegravir** (Apretude) — bimonthly injection — FDA-approved 2021; better adherence; - 99% effective if adherent; - Screening before + during (HIV, renal, HBV, STI); - Counseling, condoms, partner services; (3) **DoxyPEP (doxycycline post-exposure prophylaxis)** — 200 mg within 72 h of condomless sex — reduces syphilis + chlamydia + gonorrhea ~ 60-80% (DoxyPEP, IPERGAY studies); CDC guideline 2024 — recommend selected MSM/TGW; (4) **HPV vaccination** through age 26 (catch-up 27-45 shared decision); (5) **Mpox (monkeypox) vaccination** — Jynneos for high-risk; (6) **Behavioral interventions**: condom use, partner notification + EPT where legal, harm reduction; (7) **Hepatitis A/B vaccination** if not immune; (8) **Substance use screening** + connect care; (9) **Mental health screen** + connect care; (10) **Stigma-free environment + competent care**: training, intake forms (sexual orientation, gender identity, partners, practices), confidentiality; (11) **Multidisciplinary**: PCP + ID/HIV + sexual health clinic + behavioral health + community + public health

---

MSM STI screening: q 3-6 mo HIV + syphilis + GC/CT NAAT all sites + HCV q 6-12. PrEP strongly recommended (daily, 2-1-1, LAI cabotegravir). DoxyPEP. HPV, HepA/B, Mpox vaccination. Stigma-free competent care. Multidisciplinary.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'family_medicine'
  and scenario = 'ผู้ป่วยอายุ 28 ปี MSM — multiple partners + condomless anal sex × 6 mo; ขอ STI screening';

update public.mcq_questions
set choices = '[{"label":"A","text":"Oral antibiotic alone long-term"},{"label":"B","text":"Acne Vulgaris Stepwise Management (AAD 2024)"},{"label":"C","text":"Topical antibiotic monotherapy long-term"},{"label":"D","text":"Aggressive scrub + drying agents"},{"label":"E","text":"No treatment — will outgrow"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Acne Vulgaris Stepwise Management (AAD 2024): (1) **Severity assessment**: mild (comedonal, few inflammatory), moderate (extensive comedonal + inflammatory papulopustules), severe (nodulocystic, scarring); psychosocial impact assessment important; (2) **Stepwise approach AAD**: - **Mild**: topical retinoid (adapalene OTC, tretinoin Rx, tazarotene) ± benzoyl peroxide (BP); topical antibiotic (clindamycin, erythromycin — always combine with BP to reduce resistance); azelaic acid; - **Moderate (this patient)**: combination topical retinoid + BP + topical antibiotic; or add **oral antibiotic** (doxycycline 100 mg BID or minocycline) × 3-4 mo + topical regimen; combined oral contraceptive (women) — estrogen-containing approved for acne; spironolactone (women — anti-androgen, off-label common); - **Severe / nodulocystic / scarring / refractory**: refer dermatology for **isotretinoin (Accutane)**; iPLEDGE program (US); pregnancy test + 2 forms contraception (severe teratogen); monitor LFT, lipids, mood; (3) **Cycle through topicals**: 3-month trial each combination before escalating; (4) **Avoid**: topical antibiotic monotherapy (resistance), oral antibiotic monotherapy long-term (resistance), aggressive scrubbing, picking, excessive sun exposure with retinoid; (5) **Adjuncts**: gentle skincare, non-comedogenic cosmetics, mineral SPF (sun protection — many acne meds photosensitize); (6) **Procedural**: comedone extraction, chemical peels, light therapy (limited evidence); (7) **Psychosocial impact**: anxiety, depression, body image — screen + address; (8) **Scarring management**: prevention primary, treatment after acne controlled (laser, microneedling, fillers, surgery — dermatology); (9) **Hormonal evaluation** if signs androgen excess (irregular menses, hirsutism, alopecia) — PCOS workup; (10) **Pregnancy considerations** if applicable; (11) **Multidisciplinary**: PCP + dermatology (especially isotretinoin) + mental health if affected

---

Acne: stepwise. Mild — topical retinoid ± BP ± topical abx (combined w/ BP). Moderate — combination + oral doxycycline + OCP/spironolactone (women). Severe — isotretinoin (dermatology + iPLEDGE). Avoid abx monotherapy. Psychosocial + adjuncts. Multidisciplinary.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'family_medicine'
  and scenario = 'วัยรุ่นอายุ 16 ปี — moderate inflammatory acne + comedones บนหน้า + chest + back × 1 yr, fail OTC benzoyl peroxide';

update public.mcq_questions
set choices = '[{"label":"A","text":"No biopsy — observe"},{"label":"B","text":"Suspicious Skin Lesion + Melanoma Approach (AAD + NCCN)"},{"label":"C","text":"Shave biopsy only"},{"label":"D","text":"Refer in 3 months"},{"label":"E","text":"Topical steroid trial"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Suspicious Skin Lesion + Melanoma Approach (AAD + NCCN): (1) **ABCDE criteria** for melanoma: - **A**symmetry; - **B**order irregular; - **C**olor variegated; - **D**iameter > 6 mm; - **E**volving (changes); - This patient: multiple criteria present + risk factors → **biopsy**; (2) **High-risk features**: fair skin, sunburns, family history (CDKN2A, BRCA, BAP1), personal history melanoma/NMSC, atypical nevi, > 50 nevi, immunosuppression, age, occupational/recreational UV; (3) **Biopsy approach**: - **Excisional biopsy with narrow margin (1-3 mm)** preferred for suspicious pigmented lesions — accurate staging; - **Punch biopsy through deepest part** if large; - Avoid shave (may miss depth/Breslow); - Avoid partial sampling if possible; - Document location, photo; (4) **Histopathology features**: Breslow depth (most important prognostic), ulceration, mitotic rate, regression, lymphovascular invasion, margins; (5) **Staging if melanoma confirmed**: dermatology + onc — wide local excision (margins depend on Breslow), SLNB (sentinel lymph node biopsy) if T1b+ (Breslow > 0.8 mm or ulceration); imaging (CT, PET, brain MRI) for stage III+; LDH; (6) **Treatment**: - Local: wide excision; - Adjuvant systemic stage III: immunotherapy (anti-PD-1 nivolumab/pembrolizumab), targeted (BRAF + MEK if BRAF V600 mutant); - Metastatic: immunotherapy (combo nivo + ipilimumab), BRAF/MEK inhibitors, novel; - LAG-3 inhibitor (relatlimab); (7) **NMSC (BCC, SCC)**: more common, less deadly; biopsy + excision/Mohs + topicals selected; (8) **Sun protection counseling**: SPF 30+, broad-spectrum, reapply, shade, protective clothing, sunglasses, avoid tanning beds; (9) **Self-skin exam** monthly; **professional full skin exam** annually for high-risk; (10) **Genetic counseling** if hereditary risk; (11) **Multidisciplinary**: PCP + dermatology + dermatopathology + surgical oncology + medical oncology + radiation oncology + cancer center

---

Suspicious pigmented lesion: ABCDE + risk factors → biopsy. Excisional with narrow margin preferred (not shave). Breslow depth key. Staging + treatment if melanoma (WLE + SLNB + adjuvant). Sun protection + screening. Multidisciplinary.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'family_medicine'
  and scenario = 'ผู้ป่วยอายุ 55 ปี fair skin + history sunburns + family history melanoma; new asymmetric, irregular, dark pigmented lesion 8 mm';

update public.mcq_questions
set choices = '[{"label":"A","text":"Long-term opioid"},{"label":"B","text":"Rotator Cuff Tendinopathy / Subacromial Impingement (AAOS + Cochrane)"},{"label":"C","text":"Immediate surgery for all"},{"label":"D","text":"Bed rest with sling × 6 weeks"},{"label":"E","text":"MRI for all initial cases"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Rotator Cuff Tendinopathy / Subacromial Impingement (AAOS + Cochrane): (1) **Diagnosis clinical**: pain with overhead activity, lateral arm pain, night pain; Neer + Hawkins-Kennedy + Empty Can + Drop Arm tests; (2) **Imaging**: not routine for initial; X-ray if no improvement (rule out arthritis, calcific tendonitis, AC joint); **MRI or US** for: persistent symptoms > 4-6 wk, suspected tear (sudden weakness, trauma, age), pre-surgical planning; US increasingly used in primary care; (3) **Conservative management first-line (4-6 wk)**: - **Activity modification** (avoid overhead aggravators); - **Physical therapy** — gold standard: rotator cuff strengthening, scapular stabilization, posture, manual therapy, stretching; - **NSAIDs** short-course; - **Acetaminophen**; - **Topical analgesics**; - **Ice/heat**; - **Home exercise program** + education; (4) **Subacromial corticosteroid injection** if persistent: - Modest short-term benefit, repeated injections cumulative risk (tendon weakening, rupture); maximum 2-3/year; - US-guided improves accuracy; (5) **Refractory cases**: orthopedic referral for further imaging, possible arthroscopic decompression or rotator cuff repair (full-thickness tear, especially acute traumatic younger; degenerative ≥ 60 yo conservative often successful); (6) **Adjuncts (variable evidence)**: PRP (platelet-rich plasma), prolotherapy, dry needling, acupuncture; (7) **Workplace considerations**: ergonomics, work hardening, return-to-work planning; (8) **Risk factor modification**: smoking (impairs tendon healing), DM (worse outcomes), obesity; (9) **Bilateral / refractory** — consider systemic: spondyloarthritis, polymyalgia rheumatica, diabetes-related; (10) **Multidisciplinary**: PCP + PT + orthopedics + occupational/sports medicine + workplace

---

Shoulder impingement / RC tendinopathy: clinical diagnosis. Conservative first (4-6 wk) — PT gold standard + NSAIDs + activity mod. Subacromial steroid if persistent. Surgery for refractory or specific tears. Workplace + risk factors. Multidisciplinary.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'family_medicine'
  and scenario = 'ผู้ป่วยอายุ 45 ปี — overhead worker — shoulder pain + weakness × 2 mo; positive impingement signs; no trauma';

update public.mcq_questions
set choices = '[{"label":"A","text":"Surgery first-line"},{"label":"B","text":"Plantar Fasciitis (APTA + AAOS)"},{"label":"C","text":"Long-term opioid"},{"label":"D","text":"Immobilization in cast × 6 wks"},{"label":"E","text":"No treatment — ignore"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Plantar Fasciitis (APTA + AAOS): (1) **Clinical diagnosis**: heel pain medial calcaneal, worst first steps morning + after rest (post-static dyskinesia), insertion of plantar fascia; (2) **Differential**: heel pad atrophy, tarsal tunnel, calcaneal stress fracture (point tender, swelling), nerve entrapment (Baxter''s), seronegative arthropathy, infection; (3) **Imaging usually not needed** initial; X-ray if persistent (rule out fracture, heel spur — spur common in normal, not cause); MRI/US for refractory; (4) **Risk factors**: overuse, weight (obesity), tight Achilles/calf, pes planus or cavus, occupation standing, inappropriate footwear, sudden activity increase, age 40-60; (5) **Conservative management first-line (90%+ resolve within 1 yr)**: - **Stretching**: plantar fascia-specific (toe extension) + Achilles + calf — most evidence; - **Activity modification**: reduce impact, cross-train, return gradually; - **Footwear**: supportive with cushioning, avoid going barefoot/flat; - **OTC arch support / orthotic** (custom usually not needed); - **NSAIDs** short-term; - **Ice massage** after activity; - **Night splints** for refractory (dorsiflexion to maintain stretch); - **PT** — manual therapy, taping, exercise; (6) **Weight loss** if BMI elevated; (7) **Second-line if persistent ≥ 6-12 mo**: - **Corticosteroid injection** US-guided (modest short-term, risk fascia rupture + heel pad atrophy — limit); - **PRP** (platelet-rich plasma) — modest evidence, increasing use; - **ESWT (extracorporeal shock wave)** — moderate evidence; - **Botulinum toxin** — emerging; (8) **Surgery rare** (< 5%): plantar fascia release (open or endoscopic) — only after exhaustive conservative; (9) **Address contributors**: ergonomics, training schedule (runner), shoes; (10) **Patient education + expectations**: 6-18 months recovery common; (11) **Multidisciplinary**: PCP + PT + sports medicine + podiatry + orthopedics if refractory

---

Plantar fasciitis: clinical diagnosis. Conservative first (90%+ resolve): stretching + footwear + activity mod + NSAIDs + PT. Refractory — steroid injection (limit), ESWT, PRP. Surgery rare. Weight, training, ergonomics. Multidisciplinary.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'family_medicine'
  and scenario = 'ผู้ป่วยอายุ 50 ปี runner — heel pain (medial calcaneal) worst with first steps morning + after rest × 3 mo';

update public.mcq_questions
set choices = '[{"label":"A","text":"Long-term opioid"},{"label":"B","text":"Knee OA Management Primary Care (AAOS 2021 + ACR/AF 2019 + OARSI)"},{"label":"C","text":"Arthroscopic debridement for all OA"},{"label":"D","text":"Rest only — avoid exercise"},{"label":"E","text":"Single intervention"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Knee OA Management Primary Care (AAOS 2021 + ACR/AF 2019 + OARSI): (1) **Diagnosis**: clinical + X-ray (joint space narrowing, osteophytes, subchondral sclerosis); MRI usually not needed; rule out inflammatory (RA — symmetric, prolonged morning stiffness, systemic); (2) **Non-pharmacologic FOUNDATION (essential for all)**: - **Weight loss** ≥ 5-10% — each pound reduces 4 lb knee load; most impactful intervention; - **Exercise** (aerobic + strengthening — quadriceps especially) — strong evidence; supervised PT > home alone; aquatic for severe; Tai chi; - **Education** + self-management programs (ACPA, Arthritis Foundation); - **Cane/walking aid** opposite hand; - **Bracing** (medial unloader); - **Footwear** modifications; (3) **Pharmacologic stepwise**: - **Topical NSAIDs** (diclofenac gel) — first-line (less systemic SE, especially elderly + comorbidity); - **Oral NSAIDs** — short course; cautious renal, GI (PPI co-Rx high-risk), CV; consider celecoxib if needed; - **Acetaminophen** — limited efficacy (NEJM, BMJ), but safe adjunct; - **Duloxetine** — chronic OA pain (evidence in chronic MSK pain); - **Capsaicin topical**; - **Avoid opioids** for chronic OA (CDC + ACR/AF 2019 strong against — minimal benefit, significant harm); - **Glucosamine + chondroitin** — controversial, ACR/AF strongly against; - **Hyaluronate intra-articular** — controversial, AAOS recommends against, ACR/AF conditional against; (4) **Intra-articular corticosteroid injection** — modest short-term benefit; ACR/AF strong support; conflicting (small meta-analysis cartilage concern); maximum 3-4/yr; avoid if planning surgery soon; (5) **Surgery** (refractory + significant impairment): - **Total knee arthroplasty (TKA)** — highly effective; eligibility based on symptoms + function not just imaging; bilateral simultaneous vs staged; - Arthroscopic debridement / partial meniscectomy NOT recommended for OA without mechanical symptoms (multiple RCTs negative); (6) **Multimodal**: PT, weight, lifestyle, medication; (7) **Mental health screening** — chronic pain comorbidity; (8) **Multidisciplinary**: PCP + PT/OT + orthopedics + behavioral health + nutritional + community exercise programs

---

Knee OA: weight loss + exercise FOUNDATION. Topical NSAIDs first-line; oral NSAIDs caution; duloxetine + capsaicin; AVOID opioids. Intra-articular steroid short-term. TKA for refractory + impairment. Arthroscopy for OA NOT recommended. Multidisciplinary.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'family_medicine'
  and scenario = 'ผู้ป่วยอายุ 65 ปี BMI 33 — bilateral knee pain + crepitus + morning stiffness < 30 min × 1 yr, X-ray joint space narrowing';

update public.mcq_questions
set choices = '[{"label":"A","text":"Long-term high-potency steroid daily"},{"label":"B","text":"Atopic Dermatitis Stepwise (AAD 2014 + AAAAI 2023)"},{"label":"C","text":"Oral steroid burst chronic"},{"label":"D","text":"No moisturizer needed"},{"label":"E","text":"Avoid bathing entirely"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Atopic Dermatitis Stepwise (AAD 2014 + AAAAI 2023): (1) **Diagnosis clinical**: chronic relapsing, pruritus, typical distribution (flexural older), personal/family atopy, age-related distribution; (2) **Severity assessment**: EASI, SCORAD; impact (sleep, school, mental health); (3) **Stepwise approach**: - **Foundation for all**: - **Emollients** — apply liberally + frequently (within 3 min after bath); thick creams/ointments preferred over lotions; - **Bathing**: daily warm short, mild non-soap cleanser, moisturize immediately; bleach baths for recurrent infections (¼ cup bleach in tub); - **Trigger avoidance**: irritants (wool, fragrance, harsh soap), allergens (dust mite, pet, food selective), stress, sweat, climate; - **Education**: chronic condition, flares, written action plan; - **Mild**: low-potency topical steroid (hydrocortisone 1-2.5% face/groin/young children); topical calcineurin inhibitor (tacrolimus, pimecrolimus) — steroid-sparing; - **Moderate (this patient)**: mid-potency topical steroid (triamcinolone 0.1%) extremities + low-potency face; topical calcineurin alternate or maintenance; **proactive therapy** (intermittent 2x/wk steroid/calcineurin to prevent flare); - **Severe / refractory**: - **Topical PDE-4 inhibitor** (crisaborole, roflumilast); - **Topical JAK inhibitor** (ruxolitinib); - **Phototherapy** (NBUVB); - **Systemic** (refer dermatology): - **Dupilumab** (IL-4/13 antibody) — FDA approved ≥ 6 mo; highly effective + safety profile; - Other biologics: tralokinumab (IL-13); nemolizumab (IL-31); - **Oral JAK inhibitors**: abrocitinib, upadacitinib (≥ 12 yo); monitoring; - Cyclosporine, methotrexate, mycophenolate (less used now with biologics); (4) **Treat secondary infection**: bacterial (Staph — topical mupirocin, oral cephalexin), viral (HSV eczema herpeticum — emergency, IV acyclovir), fungal; (5) **Address comorbidity**: asthma, allergic rhinitis, food allergy (referral if severe), mental health (sleep, anxiety, depression), school impact; (6) **Avoid**: chronic high-potency steroid (atrophy, striae), systemic steroid for chronic (rebound), oral antihistamine routinely (limited efficacy beyond sedation); (7) **Allergy testing** selective for moderate-severe; (8) **Multidisciplinary**: PCP + dermatology + allergy + mental health + school nurse

---

Atopic dermatitis: emollient foundation + bathing routine + trigger avoidance. Stepwise topical (low/mid/high potency steroid + calcineurin inhibitor proactive). Severe: dupilumab + JAK + phototherapy. Treat secondary infection. Multidisciplinary.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'family_medicine'
  and scenario = 'เด็กอายุ 4 ปี — chronic itchy + dry rash + flexural surfaces + family history atopy; failing OTC moisturizers';

update public.mcq_questions
set choices = '[{"label":"A","text":"No preparation needed — wing it"},{"label":"B","text":"Travel Medicine Pre-Travel Visit (CDC Yellow Book + ISTM)"},{"label":"C","text":"Single vaccine for all destinations"},{"label":"D","text":"Antibiotic prophylaxis prevent malaria"},{"label":"E","text":"Avoid all vaccines abroad"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Travel Medicine Pre-Travel Visit (CDC Yellow Book + ISTM): (1) **Pre-travel assessment ideally 4-6 wk prior**: itinerary (countries, regions, urban/rural, duration, season, accommodations, activities), traveler factors (age, comorbidity, pregnancy, immunosuppression, medications, prior travel, vaccines); (2) **Vaccines** (CDC destination-specific): - **Routine update**: Tdap, MMR, polio booster, flu, COVID; - **Required (entry conditions)**: yellow fever (sub-Saharan + S America — single dose lifelong, ICVP certificate; 10-d wait); meningococcal (ACWY for Hajj/Umrah, meningitis belt during dry season); polio (some countries); - **Recommended**: typhoid (oral or injectable, areas with poor sanitation), hepatitis A + B (most travelers), rabies (high-risk activity rural), Japanese encephalitis (rural Asia), cholera (selected — newer Vaxchora oral); (3) **Malaria prevention** (chemoprophylaxis + bite avoidance critical): - Region-specific resistance pattern; CDC malaria map; - **Atovaquone-proguanil** (Malarone) — daily, 1-2 d before + 1 wk after; - **Doxycycline** — daily, cheap, also tick-borne prophylaxis; - **Mefloquine** — weekly; neuropsychiatric SE; - **Chloroquine** (only chloroquine-sensitive areas, increasingly rare); - **Tafenoquine** (Krintafel/Arakoda) — single-dose presumptive therapy + radical cure; - **Primaquine + tafenoquine** — radical cure P. vivax/ovale (G6PD test required first); - **Bite avoidance**: DEET 20-30% / picaridin / IR3535 (apply skin) + permethrin (clothing) + bed nets (permethrin-treated) + air-conditioned/screened rooms; (4) **Traveler''s diarrhea**: food + water safety education (Boil it, cook it, peel it, or forget it); self-treatment kit with antibiotic (azithromycin 500 mg × 1-3 d) + loperamide (mild); avoid FQ in many regions (resistance); ORT; (5) **Other infections**: schistosomiasis (avoid fresh water in Africa), Zika/dengue/chikungunya (mosquito-borne, daytime + nighttime), STIs (condoms), HIV PrEP/PEP, leishmaniasis, tick-borne; (6) **Altitude sickness** (acetazolamide if high altitude travel); (7) **DVT prevention** long flights (mobilization, hydration); (8) **Insurance** travel + medical evacuation; (9) **Personal medications** — letter from physician, original containers, sufficient supply; (10) **Mental health, sun, road safety**; (11) **Post-travel evaluation** if symptoms (fever, diarrhea, rash); (12) **Multidisciplinary**: PCP + travel medicine specialist + pharmacy + CDC Travel website

---

Travel medicine: pre-travel 4-6 wk. Routine + required (yellow fever, meningococcal) + recommended (typhoid, HepA/B, rabies, JE) vaccines. Malaria chemoprophylaxis + bite avoidance. Traveler''s diarrhea self-Rx + food safety. Other risks. Multidisciplinary.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'family_medicine'
  and scenario = 'ผู้ป่วยอายุ 35 ปี planning trip ไป sub-Saharan Africa × 4 wk — safari, urban, rural; ไม่ได้ฉีดวัคซีน travel มาก่อน';

update public.mcq_questions
set choices = '[{"label":"A","text":"Total disability — no return to work"},{"label":"B","text":"Workplace Injury + Occupational Medicine"},{"label":"C","text":"Long-term opioid for pain"},{"label":"D","text":"Imaging immediately for all"},{"label":"E","text":"Ignore workers'' comp"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Workplace Injury + Occupational Medicine: (1) **Initial assessment**: thorough history (mechanism, prior injuries, work demands), full exam, red flags (cauda equina, fracture); X-ray only if red flags or significant trauma; (2) **Workers'' Compensation system understanding**: - Documentation: mechanism + work-relatedness + functional impact + impairment; - Maximum medical improvement (MMI), impairment rating, return-to-work status; - State-specific regulations + insurance carriers; - Communication with employer + insurer; (3) **Treatment LBP** per ACP (similar to non-occupational): - Activity modification (modified duty better than total off); - NSAIDs; - Heat; - Exercise + PT (early); - Education (favorable prognosis); - Avoid opioids (CDC + ACOEM); - Avoid prolonged bed rest; - Acupuncture, manipulation acceptable; (4) **Return-to-work (RTW) approach**: - **Modified duty / restricted work** preferred over total disability (faster recovery + return); - Specific restrictions (lifting limit, posture, frequency); - Graded RTW progression; - Functional capacity evaluation (FCE) if persistent; - Vocational rehab if cannot return to original job; (5) **Workplace assessment**: ergonomic evaluation, training, prevention of recurrence; OSHA + employer responsibility; (6) **Psychosocial assessment** — Yellow Flags for chronicity: belief work harmful, fear-avoidance, depression, distress, job dissatisfaction, secondary gain, system distrust, prolonged disability; CBT for chronic; (7) **Workers'' comp + disability** specific considerations + advocacy; (8) **Coordination with employer**: confidentiality (limited in WC), education, accommodations, return-to-work planning; (9) **Prevention**: ergonomics, training, lifting techniques, equipment, regular health surveillance; (10) **Other occupational considerations**: hearing conservation, respiratory protection, ergonomics, mental health, shift work, toxic exposures, infection control (healthcare); (11) **Multidisciplinary**: PCP + occupational medicine + PT + ergonomist + employer + insurance + behavioral health (if yellow flags) + vocational rehab

---

Workplace LBP: same evidence-based treatment as non-occupational — early activity + PT + NSAIDs, avoid opioids. **Modified duty + RTW** preferred. Functional restrictions. Address yellow flags (chronicity). Workers'' comp documentation. Ergonomic prevention. Multidisciplinary.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'family_medicine'
  and scenario = 'ผู้ป่วยอายุ 40 ปี construction worker — acute LBP after lifting at work; ขอใบลา + workers'' compensation';

update public.mcq_questions
set choices = '[{"label":"A","text":"NRT patch alone — same as before"},{"label":"B","text":"Smoking Cessation Pharmacotherapy Selection (USPSTF + AAFP + EAGLES)"},{"label":"C","text":"Long-term opioid for cravings"},{"label":"D","text":"Single counseling session"},{"label":"E","text":"No medication ever"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Smoking Cessation Pharmacotherapy Selection (USPSTF + AAFP + EAGLES): (1) **Combination most effective**: pharmacotherapy + behavioral; both individually ↑ cessation but combination doubles; (2) **First-line pharmacotherapy options**: - **Varenicline (Chantix)** — most effective single agent + (a4b2 nicotinic partial agonist); start 1 wk before quit date; titrate up over 1 wk; continue 12-24 wk; **EAGLES trial** — cardiovascular + neuropsychiatric safety reaffirmed (Black Box warning removed); FDA reapproved 2016; recently temporarily off market (nitrosamine impurity 2021) — now available again; - **NRT (Nicotine Replacement Therapy)**: combination patch (long-acting baseline) + short-acting (gum, lozenge, inhaler, spray for cravings) — more effective than single; OTC; safer than smoking; - **Bupropion (Zyban/Wellbutrin SR)** 150 mg BID; start 1-2 wk before quit; dual benefit if depression; CI seizure disorder, eating disorder; - **Combination varenicline + NRT** — emerging evidence; - **Combination bupropion + NRT** — also effective; (3) **Second-line / alternatives**: nortriptyline, clonidine (off-label); (4) **Cytisine** — partial agonist (like varenicline); cheaper; available in some countries; (5) **E-cigarettes**: mixed evidence; UK NICE supports as cessation aid; US position more cautious (FDA not approved as cessation); some evidence (~ 18% vs 9.9% NRT cessation in Cochrane review); youth concerns, EVALI risk; (6) **Behavioral support critical**: brief counseling at every visit (5As); quitline 1-800-QUIT-NOW; text-based (SmokefreeTXT); apps; in-person counseling; group programs; (7) **Address triggers**: stress (mindfulness, CBT), alcohol, social, mental health (depression high comorbidity); (8) **Relapse common — multiple attempts typical**; don''t discourage; (9) **Special populations**: pregnant (behavioral first; NRT if needed; varenicline + bupropion limited data), cardiovascular (varenicline + NRT safe per EAGLES + meta-analyses), mental health (varenicline + bupropion safety reaffirmed EAGLES), opioid/methadone, adolescents (limited pharm — behavioral + NRT cautious); (10) **Cost**: many insurance covers; generic; manufacturer assistance; (11) **Multidisciplinary**: PCP + pharmacy + tobacco treatment specialist + quitline + behavioral health

---

Smoking cessation: combination > monotherapy. Varenicline most effective single (EAGLES safe). Combination NRT (patch + short-acting). Bupropion + NRT also effective. Behavioral critical. Address triggers + comorbidity. Multiple attempts common.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'family_medicine'
  and scenario = 'ผู้ป่วยอายุ 50 ปี smoker 30 pack-years — past failed attempts NRT patch + cold turkey; ขอ med ที่ effective ที่สุด';

update public.mcq_questions
set choices = '[{"label":"A","text":"Start T3 alone — no levothyroxine"},{"label":"B","text":"Hypothyroidism Management (ATA + AACE 2014 + 2022)"},{"label":"C","text":"Treat all subclinical with TSH 6"},{"label":"D","text":"No treatment — wait"},{"label":"E","text":"Long-term steroid for thyroid"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Hypothyroidism Management (ATA + AACE 2014 + 2022): (1) **Diagnosis**: overt — TSH ↑ + free T4 ↓; subclinical — TSH ↑ + free T4 normal; (2) **Etiology workup**: anti-TPO antibody (Hashimoto''s = most common in iodine-sufficient areas); other causes: post-radioactive iodine, post-thyroidectomy, central (rare — TSH normal/low + T4 low), drugs (amiodarone, lithium, immune checkpoint inhibitors), congenital, iodine deficiency; (3) **Treatment overt hypothyroidism**: - **Levothyroxine** weight-based 1.6 mcg/kg/d in healthy; lower in elderly, CAD, frail (start 25-50 mcg, titrate); - Take fasting, 30-60 min before breakfast OR bedtime ≥ 3 h after last meal; consistent timing; - Separate from Ca, iron, PPI, soy, fiber (absorption); separate from levothyroxine 4 h; - Recheck TSH 6-8 wk after initiation/dose change; target TSH 0.5-2.5 most (slightly higher in elderly); - Brand vs generic: bioequivalence variable — stick to same; (4) **Subclinical hypothyroidism**: - Treat if TSH > 10, symptoms, positive antibodies + planning pregnancy, infertility; - Observation reasonable < 10 + asymptomatic; (5) **Pregnancy**: - Pre-pregnancy optimize TSH < 2.5; - During pregnancy ↑ dose ~ 30% (more thyroid demand); - Trimester-specific TSH ranges; (6) **Older adults**: less aggressive — TSH 4-6 acceptable; avoid overtreatment (AFib, osteoporosis, mortality); (7) **Treatment failure / persistent symptoms despite normalized TSH**: assess adherence, absorption (celiac, atrophic gastritis, PPI), other causes (depression, sleep apnea, anemia, polycystic); T3 addition controversial — most evidence shows no benefit (selected may try liothyronine combination); (8) **Myxedema coma** rare emergency — IV levothyroxine + T3 + steroid; (9) **Monitor**: TSH q 6-12 mo when stable; (10) **Multidisciplinary**: PCP + endocrine if complex / pregnancy / refractory

---

Hypothyroidism: TSH ↑ + T4 ↓ overt; levothyroxine weight-based fasting consistent timing. Recheck 6-8 wk. Subclinical — treat if TSH > 10 / sx / pregnancy. Elderly less aggressive. Pregnancy ↑ dose. Multidisciplinary.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'family_medicine'
  and scenario = 'ผู้ป่วยอายุ 55 ปี — fatigue + weight gain + constipation + cold intolerance; TSH 12.8, free T4 0.7 (low)';

update public.mcq_questions
set choices = '[{"label":"A","text":"No treatment — self-resolves"},{"label":"B","text":"Graves Disease Management (ATA 2016)"},{"label":"C","text":"Levothyroxine for hyperthyroid"},{"label":"D","text":"Beta-blocker alone long-term"},{"label":"E","text":"Surgery first-line for all"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Graves Disease Management (ATA 2016): (1) **Diagnosis**: clinical + TSH suppressed + T4/T3 ↑ + TRAb (TSI) positive; thyroid US — diffuse vascular goiter; RAIU if uncertain (↑ uniform); (2) **3 main treatment options — patient preference + factors**: - **Antithyroid drugs (ATDs)** — first-line many, especially mild + young + small goiter + planning pregnancy: - **Methimazole (MMI)** preferred — 5-30 mg daily; LFT + CBC baseline + as needed; ~ 50% remission after 12-18 mo (continue ≥ 12 mo before considering taper); - **PTU** for 1st trimester pregnancy (MMI teratogen 1st trim — aplasia cutis), thyroid storm; hepatotoxicity higher; - SE: rash, hepatitis (PTU), agranulocytosis (RARE — STOP for fever/sore throat → CBC), arthralgia; - **Radioactive iodine (RAI)** — definitive, simple outpatient; CI in pregnancy + lactation + young children + severe orbitopathy (may worsen); usually leads to hypothyroidism → lifelong levothyroxine; - **Thyroidectomy** — definitive, for large goiter, suspicious nodules, severe orbitopathy, pregnancy 2nd trim if needed, patient preference; risk recurrent laryngeal nerve + hypoparathyroidism; experienced surgeon; (3) **Symptom management**: **beta-blocker (propranolol, atenolol)** for tachycardia, tremor, anxiety; (4) **Graves orbitopathy management**: refer ophthalmology; smoking cessation critical (worsens); IV steroids for moderate-severe active; **teprotumumab** (Tepezza — IGF-1R antibody) FDA-approved 2020 — game changer; orbital radiation, decompression surgery selected; (5) **Pregnancy**: PTU 1st trimester, MMI 2nd-3rd; close monitoring; (6) **Thyroid storm**: emergency — ICU; beta-blocker, PTU, iodine, steroid, supportive; (7) **Monitor**: TFT q 4-6 wk during titration, q 3-6 mo stable; TRAb if considering ATD withdrawal; (8) **Multidisciplinary**: PCP + endocrine + nuclear medicine + ENT/surgery + ophthalmology + smoking cessation

---

Graves: TSH ↓ + T4/T3 ↑ + TRAb +. 3 options: ATD (MMI; PTU 1st trim) / RAI / surgery — based on factors. Beta-blocker for sx. Orbitopathy — smoking cessation + steroid + teprotumumab. Pregnancy considerations. Multidisciplinary.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'family_medicine'
  and scenario = 'ผู้ป่วยหญิงอายุ 35 ปี — palpitations + weight loss + heat intolerance + tremor + diffuse goiter + mild ophthalmopathy; TSH < 0.01, T4 ↑, T3 ↑; TRAb positive';

update public.mcq_questions
set choices = '[{"label":"A","text":"Long-term PPI without lifestyle"},{"label":"B","text":"GERD Management (ACG 2022)"},{"label":"C","text":"Surgery first-line for typical GERD"},{"label":"D","text":"Antacid PRN only for chronic"},{"label":"E","text":"No treatment for moderate symptoms"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** GERD Management (ACG 2022): (1) **Diagnosis**: clinical with typical symptoms (heartburn, regurgitation); rule out alarm symptoms (dysphagia, odynophagia, weight loss, anemia, hematemesis, melena, vomiting) → EGD; (2) **EGD indications**: alarm symptoms, refractory PPI, > 50 yo first onset, Barrett''s surveillance, screening high-risk (chronic GERD + 2 risk factors — white male > 50, obese, smoker, family history); (3) **Lifestyle modification (foundation)**: - Weight loss (most impactful in obese — strong evidence); - Elevate head of bed 6-8 inches (gravity); - Avoid late meals (< 3 h before bed); - Smaller meals; - Avoid trigger foods individually (spicy, fatty, citrus, mint, chocolate, caffeine, alcohol — variable); - Smoking cessation; - Loose clothing; (4) **Pharmacotherapy stepwise**: - **PPI standard dose × 8 wk** — first-line (omeprazole 20-40, esomeprazole, pantoprazole, lansoprazole); take 30-60 min before breakfast; - **H2RA** (famotidine) — alternative; less effective; tachyphylaxis; useful for nocturnal breakthrough or maintenance; - **Antacid** symptomatic only; - **Step-down approach** — once controlled, reduce to lowest effective dose, PRN, or discontinue; - **Refractory** (despite optimized PPI): - Compliance + timing check; - Switch PPI brand; - BID dosing; - Add H2RA at bedtime; - Refer GI — pH-impedance testing, manometry, consider P-CAB (potassium-competitive acid blocker — vonoprazan FDA-approved 2022); (5) **Long-term PPI considerations**: - Generally safe; - Possible associations (low quality): CKD, fracture, dementia, infections (C diff, pneumonia), hypomagnesemia, B12 deficiency, gastric polyps — discuss but don''t deprive when indicated; - Minimum effective dose; (6) **Anti-reflux surgery** (Nissen fundoplication, magnetic sphincter augmentation — LINX) for: refractory + objective reflux + non-acid reflux predominant + young, regurgitation predominant; less common with effective PPIs; (7) **Barrett''s surveillance**: q 3-5 yr based on dysplasia; (8) **Multidisciplinary**: PCP + GI + nutritionist + surgery selected

---

GERD: lifestyle (weight, HOB, late meals) + PPI 8 wk first-line. EGD for alarms / refractory / Barrett''s screen. H2RA + antacid roles. Refractory — GI eval. Long-term PPI generally safe. Surgery selective. Multidisciplinary.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'family_medicine'
  and scenario = 'ผู้ป่วยอายุ 50 ปี — heartburn + regurgitation × 3 wk, no alarm symptoms; BMI 32';

update public.mcq_questions
set choices = '[{"label":"A","text":"No treatment — bacteria normal"},{"label":"B","text":"H. pylori Eradication (ACG 2017 + Maastricht VI 2022)"},{"label":"C","text":"Short 3-day course"},{"label":"D","text":"Single antibiotic alone"},{"label":"E","text":"Surgery for ulcer first"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** H. pylori Eradication (ACG 2017 + Maastricht VI 2022): (1) **Testing indications**: PUD, MALT lymphoma, atrophic gastritis, gastric cancer family history, post-gastric cancer resection, uninvestigated dyspepsia in low-risk, before long-term NSAID/aspirin (selected), iron-deficiency anemia unexplained, ITP, vitamin B12 deficiency unexplained; (2) **Testing methods**: - **Non-invasive**: urea breath test, stool antigen — first choice non-EGD; serology — has been used but cannot distinguish current vs past; - **Invasive (EGD)**: rapid urease test, histology, culture; - Hold PPI ≥ 1-2 wk + antibiotic ≥ 4 wk before testing (false neg); (3) **Treatment** — empiric based on local resistance: - **Bismuth quadruple × 14 d** (preferred first-line per ACG 2017 + Maastricht VI in areas with clarithromycin resistance > 15%): PPI BID + bismuth + tetracycline + metronidazole; - **Clarithromycin-based triple** × 14 d (PPI + amox + clarithro) — only if local clarithro resistance < 15% AND no prior macrolide exposure; - **Levofloxacin triple** × 10-14 d (PPI + amox + levo) — alternative; - **Concomitant** quadruple (PPI + amox + clarithro + metronidazole) × 10-14 d; - **Rifabutin triple** (rifabutin + amox + omeprazole — Talicia) salvage; - Vonoprazan-amox dual / triple emerging; (4) **Test of cure** ≥ 4 wk after completing therapy + ≥ 1-2 wk off PPI — urea breath test or stool antigen (NOT serology); (5) **Treatment failure** ~ 20-30%: use different regimen (avoid prior abx); resistance testing if available; (6) **Counseling**: complete full course; SE warning (taste, GI); confirm cure (PUD risk reduction); (7) **Family considerations**: gastric cancer family history — discuss screening; (8) **Multidisciplinary**: PCP + GI

---

H. pylori PUD: bismuth quadruple × 14 d first-line (or clarithro triple if local resist < 15%). Hold PPI/abx before testing. Test of cure 4 wk post-tx (UBT or stool Ag, not serology). Treatment failure — different regimen.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'family_medicine'
  and scenario = 'ผู้ป่วยอายุ 55 ปี — dyspepsia + EGD พบ gastric ulcer + biopsy positive H. pylori';

update public.mcq_questions
set choices = '[{"label":"A","text":"Repeat colonoscopy q 6 mo"},{"label":"B","text":"IBS Management (ACG 2021 + Rome IV)"},{"label":"C","text":"Single antibiotic course indefinitely"},{"label":"D","text":"Ignore — psychological only"},{"label":"E","text":"Long-term opioid"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** IBS Management (ACG 2021 + Rome IV): (1) **Diagnosis Rome IV**: recurrent abdominal pain ≥ 1 d/wk in past 3 mo + ≥ 2 of: related to defecation, change in frequency, change in form; (2) **Subtypes by Bristol stool**: IBS-D (diarrhea), IBS-C (constipation), IBS-M (mixed), IBS-U (unsubtyped); (3) **Workup limited if no alarms**: - CBC, CRP/ESR; - Celiac serology (tTG-IgA); - Stool studies if diarrhea (Giardia, infection); - **Calprotectin** — to rule out IBD; - **No routine colonoscopy** if no alarms + age < 45 (or 50); - Lactose breath test if suspected; (4) **Patient education** — chronic relapsing, gut-brain disorder, not progressive, not life-threatening; therapeutic relationship key; (5) **Dietary**: - **Low FODMAP diet** (with dietitian) — strong evidence for symptom improvement, especially IBS-D; structured elimination + reintroduction; - Soluble fiber (psyllium) — IBS-C and some IBS-D; - Avoid trigger foods individual; - Gluten-free trial selected (non-celiac gluten sensitivity overlap); (6) **Pharmacotherapy by subtype**: - **IBS-D**: - Loperamide for diarrhea; - **Rifaximin** 550 mg TID × 14 d (TARGET trials); can repeat 2 more cycles if symptomatic recurrence; - **Eluxadoline** (Viberzi) — mixed mu/kappa; CI no gallbladder or alcohol; - **Alosetron** (5HT3 antagonist) — restricted; - TCA low-dose (amitriptyline, nortriptyline) — visceral pain modulation + sleep; - **IBS-C**: - PEG; - **Linaclotide, plecanatide** (guanylate cyclase agonists); - **Lubiprostone** (chloride channel activator); - **Tenapanor** (NHE3 inhibitor) — newer; - SSRI; - Prucalopride (5HT4 agonist) selected; (7) **Behavioral therapy**: CBT, gut-directed hypnotherapy — strong evidence; mindfulness; (8) **Probiotics** — limited evidence overall; specific strains may help; (9) **Address psychosocial**: stress, anxiety, depression, trauma, FODMAP triggers; (10) **Mental health screening + collaborative care**; (11) **Multidisciplinary**: PCP + GI + dietitian + behavioral health

---

IBS: Rome IV diagnosis + limited workup (no alarms). Education + dietary (low FODMAP, fiber). Subtype-specific pharm (IBS-D — rifaximin/loperamide/TCA; IBS-C — PEG/linaclotide). Behavioral therapy strong evidence. Address psychosocial. Multidisciplinary.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'family_medicine'
  and scenario = 'ผู้ป่วยอายุ 30 ปี — recurrent abdominal pain + altered bowel habits (diarrhea predominant) × 6 mo, no alarm features, normal physical exam, normal labs';

update public.mcq_questions
set choices = '[{"label":"A","text":"Empiric IV vancomycin for all cellulitis"},{"label":"B","text":"Cellulitis Outpatient Management (IDSA SSTI 2014)"},{"label":"C","text":"MRI all cellulitis"},{"label":"D","text":"No antibiotic — observe"},{"label":"E","text":"Hospitalize all cellulitis"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Cellulitis Outpatient Management (IDSA SSTI 2014): (1) **Diagnosis clinical**: erythema + warmth + edema + tenderness; mark borders; demarcate; (2) **Differentiate**: - **Non-purulent cellulitis** (this patient) — typically beta-hemolytic strep (GAS, GBS) and MSSA; - **Purulent cellulitis / abscess** — typically MRSA; I&D first; abx if larger; - **Mimics**: DVT, stasis dermatitis, contact dermatitis, gout, erysipelas (more raised + sharp border — strep), necrotizing fasciitis (severe pain out of proportion, crepitus, hemorrhagic bullae — surgical emergency); (3) **Severity classification**: - **Mild** (this patient — afebrile, stable, no comorbidity) — outpatient oral; - **Moderate** — systemic signs, more extensive — outpatient IV or hospitalization; - **Severe** — sepsis, deep infection, fail outpatient — admit IV; (4) **Outpatient antibiotic for non-purulent cellulitis** (cover strep ± MSSA): - **Cephalexin 500 mg QID × 5-10 d** (5 days often sufficient — DICTATES study); or - **Dicloxacillin** 500 mg QID; or - **Penicillin V** 500 mg QID if clear strep; - **PCN allergy**: clindamycin 300-450 mg QID, doxycycline; - **MRSA coverage** (purulent or risk factors): TMP-SMX, doxycycline, clindamycin; (5) **Adjuncts**: - Elevation of affected limb; - Mark borders + reassess 24-48 h; - Cool compresses; - Treat tinea pedis (common entry); skin care; - Address venous insufficiency, lymphedema (recurrence prevention); (6) **Hospital admission indications**: severe systemic signs, immunocompromised, rapid progression, failed outpatient, suspect necrotizing fasciitis (URGENT surgery + IV abx), facial cellulitis (esp orbital), special hosts; (7) **Follow-up 24-72 h**: expect improvement; worsening → re-evaluate (abscess, resistant, alternative diagnosis); (8) **Recurrence prevention**: treat predisposing (tinea, venous, lymphedema); long-term prophylaxis (penicillin) for frequent recurrences; (9) **Multidisciplinary**: PCP + ID/dermatology + vascular if venous + surgery if necrotizing

---

Non-purulent cellulitis: clinical diagnosis, mark borders. Cephalexin (strep ± MSSA) 5-10 d outpatient if mild. Cover MRSA only if purulent / risk factors. Address entry (tinea), elevation. Watch necrotizing fasciitis. Follow-up 24-72 h.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'family_medicine'
  and scenario = 'ผู้ป่วยอายุ 40 ปี — leg redness + warmth + swelling × 2 d after minor scratch, no purulent drainage, no abscess, no fever; stable vitals';

update public.mcq_questions
set choices = '[{"label":"A","text":"Allopurinol during acute attack alone"},{"label":"B","text":"Acute Gout + Long-term Management (ACR 2020)"},{"label":"C","text":"Long-term opioid for gout pain"},{"label":"D","text":"No treatment — self-resolves"},{"label":"E","text":"Surgery for tophi only"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Acute Gout + Long-term Management (ACR 2020): (1) **Acute attack diagnosis**: classic (1st MTP — podagra), monoarthritis, rapid onset, red/hot/tender; gold standard = joint aspiration + monosodium urate crystals (negatively birefringent needles) under polarized light; uric acid often elevated but may be normal during attack; rule out septic arthritis (always consider with monoarthritis — culture); (2) **Acute treatment** (start ASAP, within 24 h best): - **NSAIDs** (naproxen 500 BID, indomethacin, ibuprofen) — first-line if no CI; consider PPI; - **Colchicine** (1.2 mg → 0.6 mg in 1 h → 0.6 mg BID-TID until resolved; max ~ 5-7 d) — best within 24 h of onset; less effective if delayed; dose-reduce in CKD; - **Corticosteroid** (prednisone 30-40 mg taper over 7-10 d) — first-line if NSAID/colchicine CI (CKD, GI bleed, anticoagulation, HF); intra-articular for single joint; IM as alternative; - **IL-1 inhibitor** (anakinra, canakinumab) for refractory or contraindications to others; - Combination therapy for severe (NSAID + colchicine or steroid + colchicine); - Don''t start/stop urate-lowering during acute (but continue if already on); (3) **Long-term urate-lowering therapy (ULT)** indications (ACR 2020): - ≥ 2 attacks/yr; - Tophi; - Radiographic damage; - Stage 3 CKD; - Uric acid > 9; - Discuss with first attack + risk factors; (4) **ULT options**: - **Allopurinol first-line** — start 100 mg/d (50 if CKD), titrate q 2-5 wk to uric acid < 6 (< 5 if tophi); HLA-B*5801 testing in Asian (esp Han Chinese, Korean, Thai) + African — severe hypersensitivity (SJS/TEN) risk; - **Febuxostat** alternative; CV warning (FDA 2019 — black box vs allopurinol — CARES trial); - **Probenecid** uricosuric (CI overproducers, kidney stones, CKD); - **Pegloticase** (uricase IV) — refractory + tophaceous; - **ULT initiation during acute attack OK** (modern recommendation, with anti-inflammatory bridge — colchicine 0.6 mg daily or low-dose NSAID/steroid × 3-6 mo while titrating ULT — prevents paradoxical flares); (5) **Lifestyle**: weight loss, alcohol limit (especially beer, spirits), purine moderation (red meat, organ, shellfish), low-fructose, dairy + cherries beneficial, hydration; (6) **Address comorbidities** (high CV risk): HTN — losartan + amlodipine preferred (uric acid neutral), DM, lipid, CKD, NAFLD; AVOID — thiazide, loop diuretic, low-dose aspirin (raise uric acid); (7) **Patient education**: chronic disease, attack action plan, ULT adherence; (8) **Multidisciplinary**: PCP + rheumatology if refractory + nutrition

---

Gout: acute — NSAID/colchicine/steroid (start < 24 h). Joint aspiration if uncertain. Long-term ULT (allopurinol — HLA-B*5801 high-risk pop; febuxostat alt) — start during attack OK with anti-inflam bridge. Target uric acid < 6. Lifestyle + CV risk + meds.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'family_medicine'
  and scenario = 'ผู้ป่วยอายุ 55 ปี HTN — acute monoarthritis of 1st MTP joint, red + hot + extremely tender × 1 d; serum uric acid 9.8; first episode';

update public.mcq_questions
set choices = '[{"label":"A","text":"Long-term NSAIDs alone"},{"label":"B","text":"Rheumatoid Arthritis Initial Management (ACR 2021)"},{"label":"C","text":"Steroid monotherapy long-term"},{"label":"D","text":"Wait 1 yr before DMARD"},{"label":"E","text":"No treatment until severe deformity"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Rheumatoid Arthritis Initial Management (ACR 2021): (1) **Diagnosis** — ACR/EULAR 2010 criteria; clinical + serology (RF, anti-CCP) + acute phase + duration; (2) **Workup**: CBC, LFT, Cr, hepatitis B+C, TB screen, CXR; pregnancy if applicable; (3) **Refer rheumatology urgently** — early initiation of DMARD (within 3 mo) — improves outcomes, prevents joint damage (window of opportunity); (4) **Treatment principle: treat-to-target** (remission or low disease activity); monitor disease activity (CDAI, DAS28) regularly + escalate as needed; (5) **DMARDs**: - **Methotrexate first-line** (csDMARD) — start 7.5-15 mg/wk + folate 1 mg/d (or 5 mg/wk); titrate to 20-25 mg/wk; SC if oral GI intolerance or insufficient; baseline + monitoring CBC, LFT, Cr; avoid alcohol; - **Hydroxychloroquine** mild disease or combination; baseline + annual eye exam (retinopathy); - **Sulfasalazine** alternative; - **Leflunomide** alternative; - **Triple therapy** (MTX + HCQ + SSZ) for inadequate MTX response; (6) **Biologics + JAK inhibitors (b/tsDMARDs)** for MTX-inadequate response: - **TNF inhibitors** (adalimumab, etanercept, infliximab, golimumab, certolizumab) — first-line biologic; - **Non-TNF biologics**: IL-6 (tocilizumab, sarilumab), B-cell (rituximab), T-cell (abatacept); - **JAK inhibitors** (tofacitinib, baricitinib, upadacitinib) — Boxed warning for CV + cancer (ORAL Surveillance) — secondary now in many; - Screen + treat latent TB before biologics; - Hepatitis B screening + prophylaxis; - Live vaccines avoid on biologics; (7) **Bridging therapy**: low-dose corticosteroid (prednisone 5-10 mg or intra-articular) for symptom control during DMARD onset; taper ASAP; avoid chronic; (8) **NSAIDs** for symptoms — adjunct; cautious CV + GI + renal; (9) **Comorbidities**: CV risk ↑ (treat aggressively), depression, osteoporosis (steroid + disease), interstitial lung disease screen; (10) **Vaccinations**: pneumococcal, flu, COVID, shingles (Shingrix recombinant OK), HPV — update before immunosuppression ideally; (11) **Lifestyle**: exercise, smoking cessation (worsens RA + decreases response), Mediterranean diet, weight; (12) **Patient education**: chronic disease, adherence, infection signs; (13) **Multidisciplinary**: PCP + rheumatology + PT/OT + orthopedic + ophthalmology (HCQ) + behavioral health + cardiac

---

RA: early DMARD critical (window of opportunity). MTX first-line + folate. Hydroxychloroquine + SSZ + leflunomide alternatives. Biologics/JAK for refractory. Treat-to-target. Steroid bridge. CV/osteoporosis/lung screening. Vaccines. Multidisciplinary.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'family_medicine'
  and scenario = 'ผู้ป่วยอายุ 45 ปี — bilateral symmetric MCP + PIP joint pain + morning stiffness > 1 h × 6 wk; positive RF + anti-CCP; ESR 55';

update public.mcq_questions
set choices = '[{"label":"A","text":"Surgery first-line for moderate BPH"},{"label":"B","text":"BPH Management (AUA + Canadian Urological Association)"},{"label":"C","text":"Long-term Foley catheter"},{"label":"D","text":"Anticholinergic for retention"},{"label":"E","text":"No treatment ever"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** BPH Management (AUA + Canadian Urological Association): (1) **Evaluation**: AUA-SI (Symptom Index) score (mild < 8, moderate 8-19, severe 20-35); history including red flags (hematuria, retention, recurrent UTI, stones, CKD), digital rectal exam (size + nodularity), urinalysis, PSA (with shared decision discussion), Cr; uroflowmetry, post-void residual (PVR), US optional; (2) **Rule out**: prostate cancer (PSA + DRE — shared decision), bladder cancer, overactive bladder, stricture, urinary tract infection, medication causes (anticholinergic, sympathomimetic), neuro causes, polyuria; (3) **Behavioral / lifestyle (mild + moderate)**: - Limit fluids before bed; - Avoid caffeine + alcohol (especially evening); - Double voiding; - Avoid anticholinergics, decongestants; - Bladder training (timed voiding); - Pelvic floor exercises; - Weight loss; (4) **Pharmacotherapy moderate-severe**: - **Alpha-1 blockers** (tamsulosin, alfuzosin, silodosin, doxazosin, terazosin) — first-line; relax smooth muscle; rapid effect; SE: orthostatic hypotension, ejaculatory dysfunction; non-selective (doxazosin) — BP-lowering; floppy iris syndrome (alert ophthalmology before cataract surgery); - **5-alpha reductase inhibitors (5-ARI)** (finasteride, dutasteride) — shrink prostate; for larger prostates (> 40 g); slow effect (6+ mo); SE: sexual dysfunction (libido, ED, ejaculatory), depression rare; lowers PSA ~ 50% (multiply x 2 for interpretation); - **Combination** (alpha + 5-ARI) — CombAT trial; for moderate-severe + large prostate; better than monotherapy; - **Anticholinergic / beta-3 agonist** (mirabegron) — for irritative symptoms + low PVR; - **PDE5 inhibitor** (tadalafil 5 mg daily) — for BPH + ED — dual benefit; (5) **Surgical / procedural** for refractory + complications: - **TURP** (transurethral resection) — gold standard; - **HoLEP** (Holmium laser enucleation), **GreenLight laser** — alternatives; - **Minimally invasive**: UroLift (prostatic urethral lift), Rezum (water vapor), iTind, Aquablation, prostatic artery embolization; - Open / robotic simple prostatectomy for very large; (6) **Complications watch**: urinary retention, recurrent UTI, hematuria, bladder stones, hydronephrosis, AKI; (7) **Multidisciplinary**: PCP + urology referral for refractory / complications / surgical candidate

---

BPH: AUA-SI severity. Behavioral + medical first. Alpha-blocker first-line moderate-severe. 5-ARI for large prostate. Combination for both. PDE5 if also ED. Mirabegron irritative. Surgical for refractory. Multidisciplinary.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'family_medicine'
  and scenario = 'ผู้ป่วยชายอายุ 65 ปี — LUTS (urgency + frequency + nocturia 3x + weak stream) × 1 yr; AUA-SI 18 (moderate-severe); no hematuria; PSA 3.2';

update public.mcq_questions
set choices = '[{"label":"A","text":"Ignore — not important"},{"label":"B","text":"Erectile Dysfunction (ED) Evaluation + Management (AUA + ISSM)"},{"label":"C","text":"Testosterone for all ED"},{"label":"D","text":"Surgery first-line for all"},{"label":"E","text":"Long-term opioid for relationship issues"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Erectile Dysfunction (ED) Evaluation + Management (AUA + ISSM): (1) **ED as window to systemic disease** — strong marker of CV disease, often precedes by 3-5 yr; comprehensive CV evaluation + risk modification; (2) **History + exam**: onset, progression, situational (psychogenic) vs all settings (organic), morning erections (preserved suggests psychogenic), medications, comorbidities, partner factors, mental health, sexual orientation/identity, substance use; testicular + genital exam; (3) **Workup**: testosterone (total + free if low; AM); fasting glucose / A1c; lipids; TSH if indicated; prolactin if low T; (4) **Comprehensive CV risk evaluation + management** — HT, lipid, DM control, smoking cessation; ASCVD calculator; exercise; (5) **First-line: PDE5 inhibitors** (highly effective ~ 70%): - **Sildenafil** (Viagra) — 25-100 mg PRN 1 h before; with empty stomach better; - **Tadalafil** (Cialis) — 5-20 mg PRN or **5 mg daily** (also BPH dual benefit); long half-life 36 h; food-independent; - **Vardenafil**, avanafil alternatives; - **Absolute CI**: concurrent nitrates (life-threatening hypotension), severe hypotension; - Caution: alpha-blockers (lower dose), CYP3A4 interactions, retinitis pigmentosa; - Side effects: headache, flushing, dyspepsia, blue vision (sildenafil), rare priapism > 4 h emergency; (6) **Address medications causing ED**: SSRI (bupropion alternative), beta-blocker (except nebivolol/carvedilol), thiazide, finasteride, opioids; (7) **Testosterone replacement** only if confirmed hypogonadism (low + symptoms); not for normal T; risks: erythrocytosis, prostate growth, possible CV (current data more reassuring per TRAVERSE); (8) **Second-line**: - **Intraurethral alprostadil** (MUSE); - **Intracavernosal injection** (alprostadil, papaverine, phentolamine combo) — urology training; - **Vacuum erection device**; - **Penile prosthesis** — surgical, very effective, satisfaction high; (9) **Psychosexual counseling / sex therapy** — alone or combined with medical; address partner; (10) **Lifestyle**: exercise (significant ED improvement), weight loss, Mediterranean diet, sleep, stress; (11) **Multidisciplinary**: PCP + urology + endocrinology + cardiology + behavioral health + sex therapy

---

ED: marker of CVD — comprehensive risk eval. PDE5 inhibitors first-line (avoid w/ nitrates). Address meds + low T (only if confirmed). Lifestyle + CV risk. Second-line: alprostadil, vacuum, prosthesis. Psychosexual counseling. Multidisciplinary.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'family_medicine'
  and scenario = 'ผู้ป่วยชายอายุ 55 ปี HTN + DM + smoker — gradual decrease in erection × 1 yr; embarrassed';

commit;
