-- ===============================================================
-- UPDATE chunk 2/8: family_medicine (25 questions)
-- ===============================================================

begin;

update public.mcq_questions
set choices = '[{"label":"A","text":"In-person only"},{"label":"B","text":"Telemedicine + Digital Health in Primary Care"},{"label":"C","text":"Refuse"},{"label":"D","text":"Random"},{"label":"E","text":"Avoid technology"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Telemedicine + Digital Health in Primary Care: (1) **Types**: synchronous (video, audio), asynchronous (secure messaging, eConsult), remote monitoring (BP, glucose, weight, sleep, fall detection, wearables); (2) **Use cases**: routine follow-up, chronic disease management, behavioral health, urgent care, specialist consultation, second opinion, school + work absences; (3) **Advantages**: access (rural, transportation, disabilities), efficiency, time, cost, convenience, infectious disease prevention; (4) **Limitations**: physical exam limited, technology barriers (elderly, low SES, language), digital divide, reimbursement, licensure (interstate); (5) **Best practices**: appropriate visit selection (some conditions need in-person), backup for failure, patient + provider training, privacy (HIPAA), documentation; (6) **Patient portal**: secure messaging, lab + test results, appointment scheduling, medication refills, patient education; (7) **EHR integration**: data exchange, decision support, structured reporting, interoperability; (8) **AI + digital tools**: symptom checker, triage, diagnosis aid, predictive analytics, patient self-management apps; (9) **Equity considerations**: digital divide — provide alternatives, community resources, language access, accessibility; (10) **Regulation + reimbursement evolving** post-COVID; (11) **Multidisciplinary**: provider + IT + nursing + administration + patient; (12) **Modern**: integrated care + technology + value-based; growing rapidly

---

Telemedicine + digital health: synchronous + asynchronous + remote monitoring. Multiple use cases. Advantages + limitations. Best practices. Patient portal + EHR + AI integration. Equity considerations. Modern: integrated care + technology + COVID-accelerated.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'family_medicine'
  and scenario = 'Hospital implements primary care telemedicine + digital health integration';

update public.mcq_questions
set choices = '[{"label":"A","text":"Fee-for-service only"},{"label":"B","text":"Population Health + Value-Based Care"},{"label":"C","text":"Random"},{"label":"D","text":"No data"},{"label":"E","text":"Refuse"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Population Health + Value-Based Care: (1) **Population health management**: focus on entire population, not individual visit; data analytics, registries, stratification; (2) **Triple Aim (now Quadruple/Quintuple)**: better population health + better patient experience + lower cost + clinician well-being + health equity; (3) **Value-Based Payment models**: - Fee-for-service (volume); - Pay-for-performance (P4P); - Bundled payments (episodes); - Shared savings (ACOs — Accountable Care Organizations); - Capitation + full risk; - Alternative Payment Models (APMs); (4) **Quality measures**: process + outcome; HEDIS, CMS Stars, MIPS; clinical quality, patient experience, cost, equity; (5) **Care management** for high-risk: identification + intervention + outcomes; (6) **Chronic disease registries**: DM, HTN, asthma, CHF — proactive panel management; (7) **Preventive care gaps**: outreach for screening + vaccination + chronic disease followup; (8) **SDOH integration**: address upstream determinants; (9) **Behavioral health integration**: Collaborative Care, integrated primary care; (10) **Transitions of care**: post-hospital, care transitions intervention; (11) **Multidisciplinary team**: physicians + APPs + nurses + care managers + social workers + pharmacists + community health workers + data analysts; (12) **Health IT**: EHR + analytics + registry + telehealth + decision support + interoperability; (13) **Patient engagement**: portal, education, advisory groups, surveys; (14) **Equity focus**: stratified outcomes, address disparities; (15) **Modern**: transformation from volume to value + population focus

---

Population health + value-based care: focus on population not individual visit. Quadruple/Quintuple Aim. Value-based payment models. Quality measures. Care management. SDOH + behavioral health integration. Equity focus. Modern: transformation + technology + multidisciplinary.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'family_medicine'
  and scenario = 'Hospital wants implement population health management + value-based care';

update public.mcq_questions
set choices = '[{"label":"A","text":"Single specialty"},{"label":"B","text":"Multimorbid Primary Care Integrative Management"},{"label":"C","text":"Single specialist"},{"label":"D","text":"Refuse"},{"label":"E","text":"Hospice"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Multimorbid Primary Care Integrative Management: (1) **Comprehensive assessment**: medical + functional + cognitive + nutritional + psychosocial + medications + advance care planning + values + goals; (2) **Care planning**: prioritize based on impact + patient values + interactions between conditions; (3) **Integrated chronic disease management**: - T2DM: ADA standards + SGLT2/GLP-1 RA for cardiorenal benefit + obesity + comorbidity; - HTN: target individualized + ACEi/ARB for CKD; - CKD: SGLT2i, RAAS, K-sparing diuretic, lipid; - Obesity: lifestyle + pharmacotherapy + bariatric for selected; - OSA: CPAP, weight loss, positional; - Depression: SSRI + therapy + Collaborative Care; - Chronic pain: multimodal opioid-sparing + PT + behavioral; (4) **Common medication overlaps**: SGLT2i + GLP-1 RA address DM + obesity + CV/renal; SSRI may help mood + pain; ACE/ARB renal + HT; (5) **Polypharmacy management**: Beers, STOPP/START; deprescribing; pharmacist consultation; (6) **Lifestyle medicine foundation**: nutrition + exercise + sleep + stress + social + avoid risky substances; (7) **Mental health integration**: collaborative care; (8) **SDOH assessment + intervention**: address food, housing, transportation, income; (9) **Multidisciplinary team**: PCP + endocrine + nephrology + cardiology + sleep + behavioral health + dietitian + PT + pharmacy + social work + nursing; (10) **Patient-centered**: shared decision-making + values + goals + quality of life; (11) **Care coordination**: medical home model; (12) **Long-term**: chronic disease lifelong + adjustment + transitions; (13) **Health equity + access** focus

---

Multimorbid primary care = quintessentially integrative. Comprehensive assessment + prioritize + integrated disease management + medication overlap leveraging. Polypharmacy + lifestyle + mental health + SDOH. Multidisciplinary + patient-centered. Modern: family medicine well-positioned for chronic disease integration.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'family_medicine'
  and scenario = 'ผู้ป่วยอายุ 55 ปี — multimorbid (T2DM + HTN + CKD + obesity + OSA + depression + chronic LBP) — comprehensive integrative primary care';

update public.mcq_questions
set choices = '[{"label":"A","text":"Single member"},{"label":"B","text":"Family-Centered Primary Care"},{"label":"C","text":"Random"},{"label":"D","text":"Refuse"},{"label":"E","text":"Discharge"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Family-Centered Primary Care: (1) **Family unit as focus**: family medicine unique among specialties — treats family + system; (2) **Family genogram**: 3 generations medical + psychosocial + relationships; identify patterns, risk factors, supports; (3) **Family systems theory**: family as interdependent unit; changes affect whole; (4) **Common family-level interventions**: - Family meeting for chronic illness, end-of-life, dementia; - Couples counseling for marital + sexual + communication; - Parenting support (PCIT, Triple P); - Family therapy for relationship + behavioral; - Caregiver support + respite; (5) **Life cycle considerations**: transitions (childbirth, adolescence, empty nest, retirement, aging, dying) — anticipatory guidance + support; (6) **Family-based screening + risk assessment**: hereditary cancers (BRCA, Lynch), CV risk, mental health (genetic + environmental); (7) **Multigenerational care**: continuity across lifespan; (8) **Domestic violence + abuse**: screen + safety + resources + multidisciplinary response; (9) **Family-based interventions chronic disease**: improves outcomes (DM, asthma, mental health); (10) **Adverse childhood experiences (ACEs)**: screening, trauma-informed care, address long-term health impact; (11) **Multidisciplinary**: PCP + family therapy + social work + behavioral health + pediatric + adult specialists + community resources; (12) **Cultural humility**: family + cultural + religious values + practices; (13) **Modern**: family medicine evolution + integrated behavioral health + multidisciplinary care + relationship-centered

---

Family-centered care: family medicine unique focus on family unit. Genogram + family systems theory + family-based interventions. Life cycle considerations + multigenerational. ACEs + trauma-informed. Multidisciplinary. Modern: relationship-centered + integrated.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'family_medicine'
  and scenario = 'ครอบครัว — Family unit + multiple family members medical + behavioral + social problems — family-centered care';

update public.mcq_questions
set choices = '[{"label":"A","text":"Single clinic only"},{"label":"B","text":"Community-Oriented Primary Care (COPC)"},{"label":"C","text":"Single specialty"},{"label":"D","text":"Random"},{"label":"E","text":"Refuse"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Community-Oriented Primary Care (COPC): (1) **COPC principles**: integrate community + clinical perspectives, address health needs of defined population, multidisciplinary; (2) **5 steps**: define community + identify problems + research + intervene + evaluate; (3) **Community Health Needs Assessment**: data analysis + community input + health priorities; (4) **Population health management** including SDOH; (5) **Community-based interventions**: - School health programs; - Workplace health promotion; - Faith-based health partnerships; - Community health worker programs; - Public health collaboration (vaccination, screening); - Environmental + policy advocacy; (6) **Common community priorities**: chronic disease, mental health, substance use, violence, maternal + child, infectious disease, equity; (7) **Multisector partnerships**: healthcare + schools + employers + government + community organizations + faith + housing + food + transportation; (8) **Health Promotion**: education, social marketing, behavior change at population level; (9) **Health equity focus**: address disparities, structural racism, social determinants, marginalized populations; (10) **Disaster + pandemic preparedness + response**: community resilience; (11) **Quality improvement at community level**: data, evaluation, ongoing improvement; (12) **Modern**: integrated with primary care + value-based + population health + equity-focused

---

Community-Oriented Primary Care: integration of community + clinical. CHNA. Community-based interventions. Multisector partnerships. Health equity focus. Disaster preparedness. Modern: integrated + value-based + equity-focused.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'family_medicine'
  and scenario = 'Community — health promotion + chronic disease prevention + reduce disparities through community-based + public health approach';

update public.mcq_questions
set choices = '[{"label":"A","text":"Increase HCTZ to 100 mg"},{"label":"B","text":"Resistant Hypertension (AHA 2018 + ACC 2017)"},{"label":"C","text":"Add second ACEi (dual RAAS)"},{"label":"D","text":"Stop all medications"},{"label":"E","text":"Refer immediately for renal denervation"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Resistant Hypertension (AHA 2018 + ACC 2017): (1) **นิยาม**: BP ≥ 130/80 (or ≥ 140/90 per old) แม้ใช้ 3 ยาขนาดเหมาะสม + 1 ตัวต้องเป็น thiazide; หรือ controlled แต่ต้องใช้ ≥ 4 ยา; (2) **ตรวจสอบ pseudoresistance**: white-coat (home BP/ABPM), adherence (pill count, urine drug levels), measurement technique; (3) **Secondary causes screen** (~ 20%): primary aldosteronism (aldo:renin ratio — most common, แนะนำใน all resistant), renal artery stenosis, OSA (STOP-BANG), CKD, pheochromocytoma, Cushing, drug-induced (NSAIDs, decongestants, OCP, licorice); (4) **Optimize regimen**: change HCTZ → chlorthalidone (more potent, longer half-life); maximize doses; (5) **Add 4th-line: spironolactone 25-50 mg** (PATHWAY-2 trial — most effective add-on); alternative eplerenone; ระวัง hyperkalemia + Cr; (6) **5th-line**: beta-blocker, alpha-blocker (doxazosin), centrally-acting (clonidine), hydralazine, minoxidil; (7) **Lifestyle reinforce**: Na < 1.5 g, weight, alcohol, exercise; (8) **Refer specialist** ถ้า refractory, suspected secondary, renal denervation candidate (newer evidence); (9) **Multidisciplinary**: PCP + nephrology + endocrine + sleep

---

Resistant HTN: confirm true vs pseudo (adherence, white-coat); workup secondary (esp primary aldo); switch HCTZ → chlorthalidone; spironolactone 4th-line (PATHWAY-2). Lifestyle. Specialist if refractory.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'family_medicine'
  and scenario = 'ผู้ป่วยอายุ 58 ปี HTN — BP 158/96 average แม้กิน amlodipine 10 + lisinopril 40 + HCTZ 25 mg ครบ 3 เดือน, adherent + home BP ยืนยัน';

update public.mcq_questions
set choices = '[{"label":"A","text":"Start triple antihypertensive immediately"},{"label":"B","text":"White-Coat Hypertension (ACC/AHA + ESC)"},{"label":"C","text":"Office BP only — ignore home readings"},{"label":"D","text":"Admit for IV BP control"},{"label":"E","text":"Diagnose secondary HTN — proceed to renal imaging"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** White-Coat Hypertension (ACC/AHA + ESC): (1) **นิยาม**: office BP สูง (≥ 130/80) + out-of-office BP ปกติ (< 130/80 home หรือ < 125/75 daytime ABPM); ~ 15-30% ของผู้ที่มี office HTN; (2) **ยืนยันด้วย**: 24-h ABPM (gold standard) หรือ home BP monitoring (HBPM) — 2 ครั้ง/วัน เช้า-เย็น × 7 วัน หาค่าเฉลี่ย; (3) **Prognosis**: CV risk น้อยกว่า sustained HTN แต่มากกว่า normotensive — ติดตามต่อ; (4) **Management**: ไม่ต้องเริ่มยา HTN routinely; lifestyle modification (DASH, exercise, weight, Na, alcohol); (5) **Follow-up**: recheck BP 6-12 mo with HBPM/ABPM — ~ 30-50% progress เป็น sustained HTN ภายใน 5 ปี; (6) **Screen + treat other CV risks**: lipid, DM, smoking; ASCVD risk; (7) **Mask HTN — opposite** (office ปกติ, home สูง — CV risk = sustained HTN) — ใช้ HBPM screen ถ้ามี risk factors; (8) **Patient education**: เทคนิควัด BP ที่บ้าน (พักนั่ง 5 นาที, แขนระดับหัวใจ, cuff ขนาดถูก, 2 ครั้งห่าง 1 นาที); (9) **Multidisciplinary**: PCP + cardiology if uncertain

---

White-coat HTN: office สูง + out-of-office ปกติ. ยืนยัน ABPM/HBPM. ไม่ต้องเริ่มยา. Lifestyle + monitor — risk progress sustained HTN. Mask HTN ตรงกันข้าม — สำคัญ screen ด้วย HBPM.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'family_medicine'
  and scenario = 'ผู้ป่วยอายุ 45 ปี — office BP 152/94 ซ้ำหลายครั้ง แต่ไม่มี end-organ damage; home BP 122/78 average × 2 สัปดาห์';

update public.mcq_questions
set choices = '[{"label":"A","text":"IV nitroprusside in clinic"},{"label":"B","text":"Asymptomatic Severe HTN (Hypertensive Urgency) Outpatient"},{"label":"C","text":"Sublingual short-acting nifedipine"},{"label":"D","text":"Send to ER for all severe BP"},{"label":"E","text":"Stop all antihypertensives"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Asymptomatic Severe HTN (Hypertensive Urgency) Outpatient: (1) **แยก urgency vs emergency**: urgency = BP ≥ 180/120 + NO acute end-organ damage; emergency = + acute end-organ damage (ACS, dissection, stroke, encephalopathy, AKI, papilledema, eclampsia, pulmonary edema); (2) **Urgency management**: NO rapid IV BP lowering (เสี่ยง ischemia); recheck BP after 30 min rest; address pain, anxiety, bladder distension; (3) **Workup point-of-care**: ECG (LVH, ischemia), urinalysis (protein, RBC), basic labs (Cr, K, glucose); (4) **Restart/intensify ORAL antihypertensive**: ถ้ามียาเดิม resume + adherence counseling; ถ้าไม่มี start oral (amlodipine, lisinopril, chlorthalidone); หลีกเลี่ยง short-acting nifedipine sublingual (ห้ามใช้ — เสี่ยง hypotension, stroke, MI); (5) **Goal**: ค่อย ๆ ลด BP ในช่วงหลายชั่วโมงถึงวัน (ไม่เกิน 25% ใน 24 h); (6) **Close follow-up 24-72 h**; (7) **ER referral** ถ้า new symptoms develop or evidence of end-organ damage; (8) **Address barriers**: cost, side effects, regimen complexity, mental health; (9) **Patient education + safety plan**; (10) **Multidisciplinary**: PCP + pharmacy + nursing + cardiology if needed

---

Asymptomatic severe HTN (urgency): NO rapid lowering, NO SL nifedipine. Recheck after rest, workup end-organ. Oral medication restart/intensify. Close follow-up. ER only if emergency criteria.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'family_medicine'
  and scenario = 'ผู้ป่วยอายุ 62 ปี HTN walk-in OPD — BP 198/118 asymptomatic, no chest pain, no neuro deficit, no visual change, no dyspnea';

update public.mcq_questions
set choices = '[{"label":"A","text":"Add more thiazide diuretic without workup"},{"label":"B","text":"Primary Aldosteronism (PA) Screening + Workup (Endocrine Society 2016)"},{"label":"C","text":"Refer for renal denervation immediately"},{"label":"D","text":"Ignore K — supplement only"},{"label":"E","text":"Continue current regimen — recheck 1 yr"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Primary Aldosteronism (PA) Screening + Workup (Endocrine Society 2016): (1) **Indications screen**: resistant HTN, HTN + hypokalemia (spontaneous or diuretic-induced), HTN + adrenal mass, HTN onset < 30 yo, severe HTN (> 150/100), HTN + family history early stroke/HTN, HTN + 1st-degree relative with PA, HTN + OSA; (2) **Screening test**: **aldosterone:renin ratio (ARR)**; aldosterone > 15 ng/dL + ARR > 20-30 = positive screen; (3) **Pre-test prep**: K+ normal (correct first), Na liberal, stop interfering meds (MRA 4-6 wk; ACEi/ARB, BB, diuretics for 2 wk if possible; doxazosin OK substitute); (4) **Confirmatory test**: oral salt loading + 24-h urine aldosterone; IV saline suppression; fludrocortisone suppression; captopril challenge; (5) **Subtype workup**: adrenal CT (มวล); adrenal venous sampling (AVS — gold standard for lateralization, esp ถ้าจะผ่าตัด); genetic testing in young (familial hyperaldosteronism); (6) **Treatment**: - Unilateral adenoma (Conn syndrome) → adrenalectomy (laparoscopic) — cure HTN ~ 50%, improve ~ 90%; - Bilateral hyperplasia → MRA (spironolactone หรือ eplerenone — less endocrine SE); - Lifelong K, BP monitoring; (7) **Multidisciplinary**: PCP + endocrine + surgery + radiology

---

Primary aldosteronism — most common secondary HTN (~10% resistant). Screen with ARR (correct K first). Confirm with suppression. CT + AVS for subtype. Adenoma → surgery; bilateral → MRA. Family medicine triggers referral.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'family_medicine'
  and scenario = 'ผู้ป่วยอายุ 42 ปี HTN ตั้งแต่อายุ 35, ใช้ 3 ยา BP ยังไม่ controlled + K+ 3.2 + adrenal incidentaloma';

update public.mcq_questions
set choices = '[{"label":"A","text":"Increase glargine to lower A1c more"},{"label":"B","text":"Hypoglycemia in Elderly T2DM — Reassess Targets + Regimen (ADA 2024 + AGS)"},{"label":"C","text":"Add another sulfonylurea"},{"label":"D","text":"Continue current regimen — A1c excellent"},{"label":"E","text":"Stop all DM medications"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Hypoglycemia in Elderly T2DM — Reassess Targets + Regimen (ADA 2024 + AGS): (1) **HbA1c 6.4% เข้มเกินไปสำหรับผู้สูงอายุ + recurrent hypoglycemia + severe episode**; ADA 2024 — relax target: HbA1c < 7.5-8.0% สำหรับ complex/multimorbid; < 8.5% สำหรับ very complex/frail; avoid < 7% if risk hypo; (2) **Hypoglycemia unawareness assessment**: severe hypoglycemia เพิ่ม mortality, dementia, falls, fracture, CV events; (3) **Deprescribe high-risk agents**: - หยุด **sulfonylurea (glipizide)** — high hypo risk in elderly + CKD; - ลด/หยุด basal insulin หรือเปลี่ยน schedule; - **เลือกใช้** metformin (CI ถ้า eGFR < 30), DPP-4 inhibitor (sitagliptin), GLP-1 RA (semaglutide — also weight loss + CV benefit), SGLT2 inhibitor (ระวัง dehydration, euglycemic DKA, AKI ใน elderly); (4) **Set new target HbA1c 7.5-8%**; (5) **Hypoglycemia management**: 15-15 rule (15g carb, recheck 15 min); glucagon kit (intranasal Baqsimi) + family training; CGM (continuous glucose monitor) — covered Medicare ถ้า insulin-using; (6) **Driving + safety counseling**; (7) **Address contributing factors**: CKD, malnutrition, dementia, polypharmacy, missed meals; (8) **Multidisciplinary**: PCP + endocrine + dietitian + pharmacy + family

---

Elderly T2DM + hypo: HbA1c 6.4% เข้มเกิน. Relax target 7.5-8%. Deprescribe sulfonylurea + reduce insulin. Use low-hypo agents (metformin, DPP-4, GLP-1, SGLT2 carefully). CGM + glucagon kit. Multidisciplinary.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'family_medicine'
  and scenario = 'ผู้ป่วยอายุ 72 ปี T2DM × 15 ปี — recurrent hypoglycemia (3 ครั้ง/เดือน, ครั้งล่าสุด unconscious) บน metformin + glipizide + glargine; HbA1c 6.4%';

update public.mcq_questions
set choices = '[{"label":"A","text":"Wait until T2DM develops"},{"label":"B","text":"Prediabetes Management (ADA 2024 + DPP Evidence)"},{"label":"C","text":"Start full DM medication regimen"},{"label":"D","text":"Refer for bariatric surgery immediately"},{"label":"E","text":"No intervention — just monitor"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Prediabetes Management (ADA 2024 + DPP Evidence): (1) **Diagnosis prediabetes**: FPG 100-125 (IFG), HbA1c 5.7-6.4%, OGTT 2-h 140-199 (IGT); (2) **Risk**: 5-10%/year progression to T2DM; CV risk เพิ่ม; (3) **First-line: Intensive Lifestyle Intervention (Diabetes Prevention Program)**: - Goal: 7% weight loss, 150 min/wk moderate activity; - Evidence: 58% reduction in T2DM progression (DPP trial); - CDC-recognized DPP programs (in-person, online, community); covered Medicare + many insurance; - Dietitian-led nutrition counseling (Mediterranean, DASH, low-carb); (4) **Metformin** ถ้า: BMI ≥ 35, age < 60, women with prior GDM, HbA1c ≥ 6.0% + เพิ่มขึ้น แม้ lifestyle; off-label แต่ ADA recommends; 31% T2DM reduction in DPP; (5) **GLP-1 RA (semaglutide)** — emerging role for weight + glycemic control ใน high-risk obese prediabetes (STEP trials); cost barrier; (6) **Address CV risk factors**: HTN, lipid (statin per ASCVD risk), smoking; (7) **Monitor**: HbA1c or FPG annually; OGTT แม่นยำกว่า; (8) **Vaccinations**: flu, COVID; (9) **Mental health screening**: depression common; (10) **Multidisciplinary**: PCP + DPP coach + dietitian + behavioral health

---

Prediabetes: DPP intensive lifestyle (7% weight, 150 min/wk) — 58% risk reduction. Metformin for high-risk subgroups (31% reduction). CV risk factor management. Multidisciplinary. Modern: DPP programs widely available, GLP-1 RA emerging.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'family_medicine'
  and scenario = 'ผู้ป่วยอายุ 45 ปี BMI 31 + family history DM — FPG 112, HbA1c 6.0% — preventive visit';

update public.mcq_questions
set choices = '[{"label":"A","text":"Wait until delivery — no intervention"},{"label":"B","text":"Gestational Diabetes (GDM) Management (ACOG + ADA 2024)"},{"label":"C","text":"Start metformin without monitoring"},{"label":"D","text":"Schedule immediate cesarean"},{"label":"E","text":"Recommend pregnancy termination"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Gestational Diabetes (GDM) Management (ACOG + ADA 2024): (1) **Diagnosis**: 75g OGTT 1-step (IADPSG/ADA): ≥ 1 abnormal — FPG ≥ 92, 1-h ≥ 180, 2-h ≥ 153 mg/dL; หรือ 2-step (50g screen → 100g 3-h); ผู้ป่วยนี้: positive (1-h สูง); (2) **First-line MNT (medical nutrition therapy)** + glucose monitoring (fasting + 1-h postprandial 4×/d): goals FPG < 95, 1-h PP < 140, 2-h PP < 120; (3) **Exercise**: 30 min moderate/d ถ้าไม่มี OB contraindication; (4) **Pharmacotherapy ถ้า lifestyle ไม่พอ** (~ 30% GDM): - **Insulin first-line** (ACOG + ADA preferred — ไม่ผ่าน placenta, ปรับยืดหยุ่นได้); basal + bolus; - **Metformin** acceptable alternative (ผ่าน placenta, long-term safety data จำกัด แต่ใช้ได้ — โดยเฉพาะถ้าผู้ป่วยปฏิเสธ insulin); - **Glyburide** ใช้น้อยลง (ผ่าน placenta + neonatal hypo); (5) **Fetal surveillance**: growth US, NST/BPP 3rd trimester; (6) **Delivery planning**: 39-40 wk ถ้า controlled, อาจ early ถ้า poorly controlled หรือ LGA; (7) **Postpartum**: หยุดยา DM; recheck 75g OGTT 4-12 wk postpartum (50% develop T2DM ภายใน 10 yr); ติดตามตลอดชีวิต — A1c q1-3 yr; (8) **Breastfeeding** safe + protective; (9) **Family planning + interpregnancy weight**; (10) **Multidisciplinary**: family medicine + OB + endocrine + dietitian + diabetes educator

---

GDM: 75g OGTT diagnosis. MNT + glucose monitoring first. Insulin first-line if lifestyle inadequate (metformin alternative). Fetal surveillance + delivery planning. Postpartum OGTT 4-12 wk + lifelong follow-up (50% develop T2DM). Multidisciplinary family + OB.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'family_medicine'
  and scenario = 'ผู้ป่วยอายุ 32 ปี G2P1 GA 26 wk — 75g OGTT: FPG 96, 1-h 188, 2-h 158';

update public.mcq_questions
set choices = '[{"label":"A","text":"Topical antibiotic alone — no offloading"},{"label":"B","text":"Diabetic Foot Ulcer Outpatient Management (IDSA + ADA + IWGDF)"},{"label":"C","text":"Immediate amputation"},{"label":"D","text":"Continue weight-bearing activity"},{"label":"E","text":"Oral steroid for healing"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Diabetic Foot Ulcer Outpatient Management (IDSA + ADA + IWGDF): (1) **Comprehensive assessment**: depth (Wagner/UT classification), size, infection signs (PEDIS), vascular (ABI, pulses, transcutaneous O2), neuropathy (10g monofilament, vibration), osteomyelitis (probe to bone, X-ray, MRI if suspected); (2) **Infection — clinical diagnosis** (not cultures alone): ≥ 2 of: erythema > 0.5 cm, warmth, tenderness, induration, purulent discharge; mild/moderate outpatient — empiric oral abx (cephalexin, dicloxacillin, TMP-SMX, or amox-clav); cover MRSA if risk; severe → IV + admission; (3) **Vascular**: ABI; refer vascular if PAD + non-healing; revascularization improves healing; (4) **Offloading critical** (often forgotten): total contact cast gold standard; removable knee-high walker; specialty footwear; reduce pressure; (5) **Wound care**: debridement (sharp preferred), moist dressings, NPWT for selected, biological dressings (advanced); (6) **Glycemic control**: HbA1c < 8% reasonable (not too tight); (7) **Smoking cessation critical**; (8) **Osteomyelitis evaluation**: probe to bone, X-ray (3-wk lag), MRI; if positive — 4-6 wk IV abx + surgical consult; (9) **Prevention recurrence**: daily inspection, professional foot care, footwear, podiatry follow-up; (10) **Multidisciplinary foot clinic**: PCP + podiatry + vascular + ID + wound care + endocrine — reduces amputation by 50-85%

---

DFU: comprehensive assessment (depth, infection, vascular, neuropathy, OM). Empiric oral abx if mild infection. **Offloading critical** (total contact cast). Vascular assessment. Wound care + glycemic + smoking. Multidisciplinary foot clinic reduces amputation 50-85%.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'family_medicine'
  and scenario = 'ผู้ป่วยอายุ 65 ปี T2DM 20 ปี + neuropathy — non-healing plantar ulcer 2 cm × 3 wk, no fever, no purulent discharge';

update public.mcq_questions
set choices = '[{"label":"A","text":"Permanently stop all lipid therapy"},{"label":"B","text":"Statin-Associated Muscle Symptoms (SAMS) Approach (ACC + NLA)"},{"label":"C","text":"Increase atorvastatin to 80"},{"label":"D","text":"Add fibrate immediately for muscle pain"},{"label":"E","text":"Add NSAIDs for muscle pain"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Statin-Associated Muscle Symptoms (SAMS) Approach (ACC + NLA): (1) **Assess + classify**: myalgia (pain, normal CK) — most common ~5-10%; myositis (CK 3-10× ULN); rhabdomyolysis (CK > 10× ULN — rare); ผู้ป่วยนี้: mild CK + myalgia; (2) **Rule out alternative causes**: hypothyroidism (TSH), vit D deficiency, exercise, infection, drug interactions (azoles, macrolides, fibrates, cyclosporine, amiodarone, grapefruit), rheumatologic; (3) **Stop statin × 2-4 wk → recheck symptoms + CK**: ถ้า resolve = likely SAMS; ถ้าไม่ = อาจไม่ใช่; (4) **Rechallenge strategies**: - Same statin lower dose; - Alternate statin (rosuvastatin or pravastatin — less SAMS in trials); - Intermittent dosing (e.g., rosuvastatin twice weekly); ~ 70-90% tolerate alternative statin (SAMSON, GAUSS trials); (5) **Vit D repletion** ถ้า deficient; CoQ10 — limited evidence; (6) **Non-statin LDL-lowering ถ้า truly intolerant**: - **Ezetimibe** 10 mg (IMPROVE-IT — 6% relative risk reduction); - **PCSK9 inhibitors** (alirocumab, evolocumab — FOURIER, ODYSSEY) for high-risk; - **Bempedoic acid** (CLEAR Outcomes) — non-muscle target; - **Inclisiran** siRNA q6 mo SC; (7) **Lifestyle reinforce**: Mediterranean, exercise, weight, smoking; (8) **Address ASCVD risk holistically**: BP, glucose, smoking, aspirin selective; (9) **SAMSON trial** — most SAMS is nocebo effect; reassurance + rechallenge important; (10) **Multidisciplinary**: PCP + cardiology + lipidology refractory

---

SAMS: rule out alternative causes; stop statin 2-4 wk; rechallenge with alternative or lower dose (70-90% tolerate). Non-statin: ezetimibe, PCSK9i, bempedoic, inclisiran for true intolerance. SAMSON — much is nocebo. Lifestyle + holistic ASCVD risk.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'family_medicine'
  and scenario = 'ผู้ป่วยอายุ 60 ปี ASCVD risk 18% — เริ่ม atorvastatin 40 → muscle pain ทั่วร่างกาย 3 wk; CK 280 (mild ↑); lipids LDL 142';

update public.mcq_questions
set choices = '[{"label":"A","text":"Ignore TG — focus only on LDL"},{"label":"B","text":"Severe Hypertriglyceridemia (HTG) Management (Endocrine Society + AHA)"},{"label":"C","text":"Surgery to remove pancreas"},{"label":"D","text":"Increase alcohol for HDL benefit"},{"label":"E","text":"High-dose fish oil OTC with no monitoring"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Severe Hypertriglyceridemia (HTG) Management (Endocrine Society + AHA): (1) **Risk stratification**: TG 150-499 (moderate), 500-1000 (severe), > 1000 (very severe — high pancreatitis risk); (2) **Pancreatitis risk** TG > 500-1000 — preventable cause; (3) **Identify + treat secondary causes**: - Uncontrolled DM (glycemic control); - **Alcohol** (cessation/major reduction critical here); - Obesity (weight loss); - Drugs (estrogen oral, tamoxifen, retinoids, steroids, BB, thiazides, atypical antipsychotics, protease inhibitors); - Hypothyroidism; - Nephrotic syndrome; - Pregnancy; (4) **Lifestyle (foundation)**: alcohol cessation (most impactful here), weight loss 5-10%, low-fat diet, refined carb + sugar limit, omega-3 from fish, exercise; (5) **Glycemic control optimization**; (6) **Pharmacotherapy**: - **TG > 500** + lifestyle inadequate → **fibrate (fenofibrate)** first-line — reduce pancreatitis risk; gemfibrozil ระวัง interact with statin (rhabdomyolysis); - **Omega-3 fatty acids (icosapent ethyl/Vascepa)** — REDUCE-IT trial: 25% CV event reduction in high-risk with elevated TG; - **Niacin** less used (SE, no proven benefit modern); - **Statin** สำหรับ LDL + ASCVD risk; (7) **Genetic** — familial chylomicronemia (LPL deficiency, ApoC-II) — refer lipidology; volanesorsen newer therapy; (8) **Monitor**: lipid panel q 6-12 wk, A1c, LFT, CK; (9) **Multidisciplinary**: PCP + dietitian + endocrine + lipidology

---

Severe HTG: pancreatitis risk if > 500-1000. Treat secondary (alcohol, DM, obesity, drugs). Lifestyle foundation (alcohol cessation here critical). Fibrate first-line + icosapent ethyl (REDUCE-IT). Statin for LDL/ASCVD. Genetic forms refer.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'family_medicine'
  and scenario = 'ผู้ป่วยอายุ 50 ปี TG 680 mg/dL (fasting), LDL 105, HDL 32; T2DM, obesity, alcohol use 4-5 drinks/d';

update public.mcq_questions
set choices = '[{"label":"A","text":"GDMT same as HFrEF — start all 4 pillars"},{"label":"B","text":"HFpEF Management (AHA/ACC/HFSA 2022 + ESC 2023 Update)"},{"label":"C","text":"No proven therapy — ignore"},{"label":"D","text":"Diuretics only"},{"label":"E","text":"Aggressive fluid loading"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** HFpEF Management (AHA/ACC/HFSA 2022 + ESC 2023 Update): (1) **Diagnosis**: clinical HF + EF ≥ 50% + structural/functional evidence diastolic dysfunction; H2FPEF + HFA-PEFF scores aid diagnosis; (2) **Identify + treat etiologies**: HTN (most common), CAD, AFib, obesity, CKD, OSA, infiltrative (amyloidosis — bone scan + free light chains screen), hypertrophic CM, valvular; (3) **GDMT — historically limited but expanding**: - **SGLT2 inhibitors** (empagliflozin EMPEROR-Preserved, dapagliflozin DELIVER) — first-line, only Class I in HFpEF — reduces HF hospitalization across full EF spectrum; - **MRA** (spironolactone — TOPCAT) — selected especially HFmrEF + lower-range HFpEF; - **ARNI** (sacubitril/valsartan — PARAGON-HF borderline) — consider lower EF range; - **Diuretics** for congestion symptoms; - **ACE/ARB + BB** less proven HFpEF, treat comorbidities; (4) **HTN target < 130/80**; (5) **AFib management**: rate, rhythm, anticoagulation; (6) **Weight loss** ถ้า obese; **exercise + cardiac rehab**; (7) **Comorbidity management**: DM (SGLT2 + GLP-1), CKD, OSA (CPAP), iron deficiency (IV iron — FAIR-HF, AFFIRM-AHF); (8) **Amyloid workup** ถ้า indications: bone scintigraphy (PYP), serum FLC + immunofixation, biopsy; tafamidis for ATTR-CM; (9) **Vaccinations**; (10) **Multidisciplinary**: PCP + cardiology + nephrology

---

HFpEF: confirm with H2FPEF/HFA-PEFF + workup etiology. **SGLT2i Class I** (EMPEROR-Preserved, DELIVER). MRA + ARNI selected. Diuretics for congestion. Treat comorbidities (HTN, AFib, obesity, CKD, OSA, iron). Amyloid workup. Multidisciplinary.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'family_medicine'
  and scenario = 'ผู้ป่วยอายุ 72 ปี — exertional dyspnea, leg edema; Echo EF 55%, septal e'' velocity ลดลง, E/e'' 16; H2FPEF score 7; BNP 480';

update public.mcq_questions
set choices = '[{"label":"A","text":"No follow-up — patient is stable"},{"label":"B","text":"Post-HF Hospitalization Transitions of Care (AHA + ACC + STS)"},{"label":"C","text":"Continue same as inpatient — no adjustment"},{"label":"D","text":"Stop GDMT after discharge"},{"label":"E","text":"Send to ER for any weight gain"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Post-HF Hospitalization Transitions of Care (AHA + ACC + STS): (1) **Vulnerable period**: 30 days post-discharge — high readmission (~ 25%) + mortality; transitions intervention reduces; (2) **Early post-discharge visit 7-14 days** (Class I recommendation); telemedicine acceptable for some; (3) **Medication reconciliation**: confirm GDMT (4 pillars) at appropriate doses, address discrepancies, simplify regimen, address cost barriers (generic, $4 plans, patient assistance); ARNI requires 36-h washout from ACEi; (4) **GDMT titration**: q 1-2 weeks initially; up-titrate to maximum tolerated; monitor BP, HR, K, Cr; (5) **Volume status**: daily weights, symptoms, diuretic adjustment (sliding scale); fluid + Na restriction; (6) **Comprehensive HF education**: low-Na diet (< 2g/d), fluid (< 1.5-2L/d), daily weight (call if > 2-3 lb in day, > 5 lb in week), medication adherence, recognize warning signs, when to call/go to ER; (7) **Cardiac rehabilitation** referral — Class I; underutilized (only ~ 30%); (8) **Address comorbidities**: AFib (anticoagulation), DM (SGLT2 + GLP-1), CKD, OSA, depression (high comorbidity — affects adherence), iron deficiency; (9) **Advance care planning** — appropriate for HF; (10) **Multidisciplinary team**: PCP + cardiology + HF nurse + pharmacist + dietitian + cardiac rehab + social work + behavioral health; (11) **Remote monitoring options**: CardioMEMS PA pressure (selected NYHA III), weight scales, BP cuffs; (12) **Population health**: identify high-risk for proactive intervention

---

Post-HF discharge: 30-day vulnerable period. Early visit 7-14 d. Medication reconciliation + GDMT titration. Volume monitoring + education. Cardiac rehab. Comorbidity + depression. Multidisciplinary care + remote monitoring. Reduces readmission.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'family_medicine'
  and scenario = 'ผู้ป่วย HFrEF อายุ 68 ปี — D/C จาก hospital หลัง ADHF — wt 78 kg → 74, weight loss with IV diuresis; เปลี่ยน Lasix PO 40 BID, started sacubitril/valsartan + carvedilol + dapa + spiro; F/U OPD ที่ family medicine';

update public.mcq_questions
set choices = '[{"label":"A","text":"No anticoagulation — asymptomatic"},{"label":"B","text":"New AFib Outpatient Management (ACC/AHA/HRS 2023)"},{"label":"C","text":"Aspirin alone — sufficient stroke prevention"},{"label":"D","text":"Aggressive rhythm control without anticoagulation"},{"label":"E","text":"Immediate cardioversion without preparation"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** New AFib Outpatient Management (ACC/AHA/HRS 2023): (1) **Workup**: history + ECG + TSH + electrolytes + CBC + Cr + echo (LVEF, valvular, LA size, structural); identify reversible (hyperthyroid, alcohol, sleep apnea, electrolyte); (2) **Stroke prevention — Anticoagulation per CHA2DS2-VASc**: - Men ≥ 2, women ≥ 3 → recommend OAC; ผู้ป่วยนี้ score 4 = clear indication; - **DOACs preferred over warfarin** (apixaban, rivaroxaban, dabigatran, edoxaban) — fewer bleeding, no INR; warfarin still for valvular AFib (mechanical valve, moderate-severe MS); - HAS-BLED for bleeding risk (informs but doesn''t preclude); - Address modifiable bleeding risks (BP, alcohol, NSAID, antiplatelet, PPI); (3) **Rate vs rhythm control**: - Rate first-line for most; goal HR < 110 (lenient — RACE II); - Beta-blocker (metoprolol) or non-DHP CCB (diltiazem, verapamil — avoid in HFrEF); digoxin add-on selected; - **Early rhythm control consideration (EAST-AFNET 4)**: within 1 year of diagnosis improves CV outcomes; ablation > antiarrhythmics for many; refer EP; (4) **Cardioversion**: anticoagulate ≥ 3 wk pre + 4 wk post; TEE-guided alternative; (5) **Catheter ablation**: improving outcomes; first-line PAF (CABANA, CASTLE-AF); HF + AFib benefit; (6) **Risk factor management**: HTN, DM, obesity (LEGACY trial — weight loss reduces AFib burden), OSA, alcohol, exercise; (7) **Patient education + decision aid**; (8) **Multidisciplinary**: PCP + cardiology + EP + anticoagulation clinic

---

New AFib: workup + reversible causes. CHA2DS2-VASc → DOAC for stroke prevention (preferred over warfarin). Rate first-line most; early rhythm control (EAST-AFNET 4) for selected. Risk factor management (LEGACY). Multidisciplinary.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'family_medicine'
  and scenario = 'ผู้ป่วยอายุ 68 ปี HTN + DM — new AFib detected on routine ECG, HR 88 (rate-controlled), asymptomatic; CHA2DS2-VASc 4';

update public.mcq_questions
set choices = '[{"label":"A","text":"Emergency PCI for all stable angina"},{"label":"B","text":"Stable Angina (CCS) Outpatient (AHA/ACC Chronic CAD 2023)"},{"label":"C","text":"Ignore — only treat if MI"},{"label":"D","text":"Long-term opioid for chest pain"},{"label":"E","text":"Aspirin only — no statin"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Stable Angina (CCS) Outpatient (AHA/ACC Chronic CAD 2023): (1) **Diagnostic workup**: pretest probability (typical anginal, age, sex, risk factors); resting ECG; (2) **Initial test if intermediate-high pretest**: stress test ± imaging — exercise ECG (low pretest), stress echo, nuclear, stress CMR; or **coronary CT angiography (CCTA)** — preferred in many (CONFIRM, SCOT-HEART, PROMISE); plaque + stenosis + risk assessment; (3) **Invasive coronary angiography**: high-risk noninvasive testing, refractory symptoms, suspected high-risk anatomy; (4) **Optimal Medical Therapy (OMT)**: - **Antiplatelet aspirin 81 mg** (clopidogrel if intolerant); - **Statin** high-intensity (atorvastatin 40-80, rosuvastatin 20-40); LDL goal < 70, < 55 high-risk; ezetimibe + PCSK9i add-on; - **Anti-anginal**: beta-blocker first-line (metoprolol, atenolol); CCB (amlodipine) + long-acting nitrate alternative or add; ranolazine add-on; - **ACEi/ARB** if HT, DM, CKD, HF, prior MI; - **SGLT2i + GLP-1 RA** if DM (cardiorenal benefit); (5) **Revascularization** (PCI vs CABG): for refractory symptoms, high-risk anatomy (left main, multivessel CAD + DM/LV dysfunction → CABG often better — SYNTAX, FREEDOM); ISCHEMIA trial — OMT vs early invasive equivalent for many stable CAD; (6) **Risk factor modification**: smoking cessation (most impactful), BP < 130/80, A1c individualized, lipid, exercise, diet (Mediterranean), weight, depression, stress; (7) **Cardiac rehab** Class I post-MI/PCI/CABG; (8) **Vaccinations**; (9) **Multidisciplinary**: PCP + cardiology + cardiothoracic surgery + cardiac rehab

---

Stable angina: pretest probability + stress test or CCTA. OMT (ASA + statin + anti-anginal + ACEi/ARB/SGLT2 selected). Revascularization for refractory or high-risk anatomy (ISCHEMIA — OMT often equivalent). Risk factor modification + cardiac rehab. Multidisciplinary.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'family_medicine'
  and scenario = 'ผู้ป่วยอายุ 65 ปี exertional chest pressure × 3 mo, predictable, relieved by rest; HT, DM, smoker; resting ECG ปกติ';

update public.mcq_questions
set choices = '[{"label":"A","text":"Send to ED for all exacerbations"},{"label":"B","text":"COPD Exacerbation Outpatient Management (GOLD 2024)"},{"label":"C","text":"Long-term prednisone × 30 days"},{"label":"D","text":"No antibiotic — never indicated"},{"label":"E","text":"Stop maintenance inhalers during exacerbation"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** COPD Exacerbation Outpatient Management (GOLD 2024): (1) **Severity assessment**: vital signs, oximetry, mental status, accessory muscle use, ability to speak; mild-moderate outpatient OK; severe (resp distress, hypercapnia, SpO2 < 90 despite O2, AMS, hemodynamic instability) → hospitalize; (2) **Bronchodilator intensify**: short-acting (SABA + SAMA — ipratropium-albuterol via inhaler with spacer or nebulizer); continue long-acting; (3) **Systemic corticosteroid**: prednisone 40 mg PO × 5 days (REDUCE trial — 5 days = 14 days no inferiority); reduces relapse + LOS; (4) **Antibiotics** for Anthonisen criteria (≥ 2 of): increased dyspnea, sputum volume, sputum purulence; or need mechanical ventilation; or change sputum color/purulence; - First-line outpatient: doxycycline, amoxicillin-clavulanate, or macrolide (azithromycin 500 mg × 3 d); - Pseudomonas risk (severe COPD, frequent abx, recent hospitalization) → fluoroquinolone (levofloxacin); duration 5-7 days; (5) **Oxygen** if SpO2 < 90% — target 88-92% (avoid over-oxygenation → CO2 retention); (6) **Close follow-up 1-2 weeks**; (7) **Address triggers**: infection, environmental (smoke, pollution), medication non-adherence; (8) **Reinforce inhaler technique + maintenance therapy**; (9) **Pulmonary rehab** post-exacerbation reduces readmission; (10) **Vaccinations** review; (11) **Smoking cessation** if applicable; (12) **Advance care planning** discussion for frequent exacerbators or end-stage; (13) **Multidisciplinary**: PCP + pulmonology + RT + smoking cessation

---

COPD exacerbation outpatient: severity assessment. Bronchodilator intensify + prednisone 40 mg × 5 d (REDUCE). Abx if Anthonisen ≥ 2. O2 target 88-92%. Close F/U + pulmonary rehab + triggers + adherence. Multidisciplinary.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'family_medicine'
  and scenario = 'ผู้ป่วย COPD GOLD III อายุ 70 ปี — increased dyspnea + change in sputum color + volume × 3 d; SpO2 91% room air, no fever, talking in full sentences';

update public.mcq_questions
set choices = '[{"label":"A","text":"Continue ICS-formoterol PRN only"},{"label":"B","text":"Pediatric Asthma Management (GINA 2024 Pediatric + EPR-4)"},{"label":"C","text":"Oral steroid daily long-term"},{"label":"D","text":"SABA monotherapy daily"},{"label":"E","text":"No treatment until severe attack"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Pediatric Asthma Management (GINA 2024 Pediatric + EPR-4): (1) **Severity classification**: this = uncontrolled / moderate persistent — needs step up; (2) **Stepwise approach (children 6-11 yo)**: - Step 1-2: low-dose ICS daily + SABA PRN; alternatively low-dose ICS-formoterol MART; - **Step 3 (this patient)**: low-dose ICS-LABA (fluticasone-salmeterol) daily + SABA PRN; or medium-dose ICS daily; - Step 4: medium-dose ICS-LABA + SABA PRN; - Step 5: refer specialist; high-dose ICS-LABA ± LAMA (tiotropium age ≥ 6); biologics for severe (omalizumab age ≥ 6; mepolizumab age ≥ 6; dupilumab age ≥ 6); (3) **Inhaler technique critical** — spacer + mask younger, mouthpiece older; observe + train every visit; (4) **Asthma action plan** written; review with family + school; (5) **Trigger avoidance**: tobacco smoke (parental), allergens (dust mite, pet, mold, cockroach), respiratory infections, exercise (don''t restrict — use SABA pre-exercise); (6) **Comorbidity**: allergic rhinitis (intranasal steroid), atopic dermatitis, GERD, OSA, obesity, mental health; (7) **Allergen immunotherapy** for selected; (8) **Vaccinations**: flu annually, pneumococcal, COVID; (9) **Education**: school plan, peak flow monitoring (older), recognize warning signs, when to seek care; (10) **Avoid LABA monotherapy** ever; (11) **Annual review + spirometry age ≥ 5**; (12) **Multidisciplinary**: family medicine + pediatric pulmonology/allergy + school nurse + behavioral health

---

Pediatric asthma uncontrolled: step up to low-dose ICS-LABA + SABA PRN. Inhaler technique. Action plan + trigger avoidance. Comorbidity. Vaccinations. Never LABA monotherapy. Multidisciplinary.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'family_medicine'
  and scenario = 'เด็กชาย 7 ปี asthma — recurrent symptoms 3 day/week + nighttime awakening 2 ครั้ง/เดือน + 1 ER visit ใน 6 เดือน; ใช้ ICS-formoterol PRN เท่านั้น';

update public.mcq_questions
set choices = '[{"label":"A","text":"No intervention until dialysis"},{"label":"B","text":"CKD Stage 3 (G3b A2) Management — Primary Care (KDIGO 2022 + ADA 2024)"},{"label":"C","text":"Stop ACEi for any Cr rise"},{"label":"D","text":"Avoid SGLT2 in CKD"},{"label":"E","text":"Refer to dialysis preparation immediately"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** CKD Stage 3 (G3b A2) Management — Primary Care (KDIGO 2022 + ADA 2024): (1) **Confirm + stage**: 2 eGFR < 60 over 3 mo + albuminuria; cause workup (DM most likely here + HTN); rule out reversible (NSAIDs, contrast, dehydration, obstruction); renal US ถ้า indicated; (2) **CV risk** in CKD = very high — leading cause of death; manage holistically; (3) **Slow progression**: - **BP target < 130/80** (or even < 120 if tolerated per SPRINT); - **ACEi or ARB** first-line for albuminuria — even normotensive (lisinopril, losartan, valsartan); monitor Cr (acceptable < 30% increase) + K; - **SGLT2 inhibitor (dapagliflozin, empagliflozin)** — DAPA-CKD, EMPA-KIDNEY — slows progression + CV benefit; indicated eGFR ≥ 20 with albuminuria; - **Finerenone** (nonsteroidal MRA) for DM + CKD + albuminuria — FIDELIO-DKD, FIGARO-DKD; - **GLP-1 RA** (semaglutide, dulaglutide) — emerging renal benefit (FLOW trial); - **Glycemic control** A1c target ~ 7% individualized; metformin OK eGFR > 30; (4) **CV risk reduction**: statin (moderate-high intensity all CKD ≥ 50 yo), aspirin selective, smoking cessation; (5) **Avoid nephrotoxins**: NSAIDs, contrast (limit when possible, hydration prevent), aminoglycosides, herbals; dose-adjust meds; (6) **CKD complications screening**: anemia (workup if Hb < 11 — iron studies, EPO if indicated), CKD-MBD (Ca, phos, PTH, vit D — PTH > stage 3), hyperkalemia (binders — patiromer, sodium zirconium), metabolic acidosis (bicarb supplement), nutrition; (7) **Vaccinations**: flu, pneumo, HepB (pre-dialysis), COVID; (8) **Refer nephrology** when eGFR < 30, rapid decline (> 5/yr), albuminuria > 300, refractory complications; (9) **Multidisciplinary**: PCP + nephrology + dietitian + diabetes educator + pharmacy

---

CKD stage 3: BP < 130/80 + ACEi/ARB + **SGLT2i (DAPA-CKD, EMPA-KIDNEY)** + finerenone (DM+CKD) + GLP-1. Glycemic. Statin. Avoid nephrotoxins. Screen complications. Refer nephrology < 30 or rapid decline. Multidisciplinary.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'family_medicine'
  and scenario = 'ผู้ป่วยอายุ 60 ปี T2DM + HTN — eGFR 42, UACR 320 mg/g (A2), Hb 11.2, BP 138/86';

update public.mcq_questions
set choices = '[{"label":"A","text":"Transfuse to Hb 13"},{"label":"B","text":"CKD Anemia Management (KDIGO Anemia 2012 + 2018 Update)"},{"label":"C","text":"Oral iron only — never IV in CKD"},{"label":"D","text":"Target Hb > 13 with ESA"},{"label":"E","text":"Ignore — anemia expected"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** CKD Anemia Management (KDIGO Anemia 2012 + 2018 Update): (1) **Workup**: CBC, retic, iron studies (ferritin, TSAT), B12, folate, TSH, occult blood, evaluate for blood loss; rule out other causes; ผู้ป่วยนี้: functional iron deficiency (low TSAT despite normal ferritin) — common CKD; (2) **Iron repletion first** — target ferritin > 100-500, TSAT > 20-30%: - Oral iron (ferrous sulfate, ferrous gluconate) — limited efficacy CKD due to hepcidin; new sucroferric oxyhydroxide; - **IV iron** preferred CKD stage 4-5 (iron sucrose, ferric gluconate, ferumoxytol, ferric carboxymaltose) — more effective + faster; (3) **ESA (erythropoiesis-stimulating agents)** — epoetin alfa, darbepoetin: - Initiate when Hb < 10 in non-dialysis CKD; target Hb 10-11.5 (NOT > 11.5 — TREAT, CHOIR, CREATE → increased CV/stroke risk at higher targets); - Address iron + other causes first; - SC vs IV; (4) **HIF-PHI (hypoxia-inducible factor prolyl hydroxylase inhibitors)** — daprodustat, roxadustat, vadadustat: oral, newer option; emerging role; (5) **Address inflammation**: chronic disease, infection; (6) **Monitor**: Hb q 2-4 wk initial, q 1-3 mo maintenance; iron studies q 3 mo; (7) **Transfusion** only for symptomatic acute anemia, not chronic management; (8) **Refer nephrology** if not already; (9) **Multidisciplinary**: PCP + nephrology + dialysis if applicable

---

CKD anemia: workup + iron first (IV preferred CKD 4-5). ESA when Hb < 10, target 10-11.5 (TREAT — avoid > 11.5). HIF-PHI emerging oral option. Transfusion only acute symptomatic. Multidisciplinary nephrology.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'family_medicine'
  and scenario = 'ผู้ป่วย CKD stage 4 (eGFR 22) — Hb 9.2, MCV 88, ferritin 95, TSAT 18%, no GI bleed';

update public.mcq_questions
set choices = '[{"label":"A","text":"Wait until adulthood — child will grow out"},{"label":"B","text":"Pediatric Obesity Management (AAP 2023 + Endocrine Society)"},{"label":"C","text":"Restrictive diet alone"},{"label":"D","text":"Single-visit advice — no follow-up"},{"label":"E","text":"Shame-based approach"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Pediatric Obesity Management (AAP 2023 + Endocrine Society): (1) **Diagnose**: BMI ≥ 95th percentile = obesity; ≥ 99th percentile หรือ ≥ 120% of 95th = severe (class 2); ≥ 140% = class 3; (2) **Comprehensive evaluation**: comorbidities (T2DM/prediabetes, dyslipidemia, NAFLD, HTN, OSA, PCOS, depression, ortho — Blount, SCFE), genetic + syndromic causes (Prader-Willi, MC4R, leptin), medications, family history; (3) **Labs ≥ 10 yo + obesity**: FPG ± A1c, lipid panel, ALT/AST, TSH selected; OSA + sleep study if symptoms; (4) **AAP 2023 major update — intensive treatment for ALL ages, no watchful waiting**: - **Intensive Health Behavior + Lifestyle Treatment (IHBLT)** ≥ 26 contact hours over 3-12 mo — gold standard ≥ 6 yo; - Family-based, behavioral, nutrition, activity, screen time; (5) **Pharmacotherapy** ≥ 12 yo: - **GLP-1 RA (liraglutide, semaglutide)** — FDA approved adolescents (Wegovy semaglutide STEP TEENS — 17% weight loss); - **Phentermine (≥ 16)**, orlistat (≥ 12), phentermine-topiramate; - Setmelanotide (rare genetic); (6) **Metabolic + bariatric surgery** ≥ 13 yo + severe obesity (BMI ≥ 35) + comorbidity, or BMI ≥ 40; Roux-en-Y, sleeve; multidisciplinary specialty programs; safe + effective adolescents (Teen-LABS); (7) **Treat comorbidities concurrently**: prediabetes/T2DM (metformin, lifestyle), dyslipidemia, HTN, OSA, mental health; (8) **Mental health screening**: depression, anxiety, eating disorder, bullying, body image; (9) **Family-centered + non-stigmatizing approach**; address SDOH (food security, neighborhood); (10) **Multidisciplinary**: PCP + pediatric obesity specialist + dietitian + behavioral health + bariatric surgery + endocrinology + sleep + school

---

Pediatric obesity AAP 2023: no watchful waiting. IHBLT ≥ 26 h. Pharmacotherapy ≥ 12 yo (GLP-1 RA effective). Bariatric ≥ 13 yo selected. Treat comorbidities. Family-centered + non-stigmatizing. Multidisciplinary.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'family_medicine'
  and scenario = 'เด็กชาย 10 ปี BMI 30 (> 99th percentile) + acanthosis nigricans + family history T2DM; ผู้ปกครองกังวลน้ำหนัก';

update public.mcq_questions
set choices = '[{"label":"A","text":"Annual CXR for screening"},{"label":"B","text":"Lung Cancer Screening (USPSTF 2021 + ACS)"},{"label":"C","text":"Sputum cytology screening"},{"label":"D","text":"No screening — too risky"},{"label":"E","text":"MRI chest for screening"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Lung Cancer Screening (USPSTF 2021 + ACS): (1) **USPSTF 2021 update**: annual **LDCT (low-dose CT)** for age **50-80** (was 55-80) + **≥ 20 pack-year** (was 30) + current smoker or quit < 15 yr; ผู้ป่วยนี้: eligible (age 62, 35 pack-year, quit 8 yr); (2) **Shared decision-making visit** required (Medicare): benefits (20% mortality reduction NLST), harms (false positives ~ 25%, incidental findings, radiation, overdiagnosis, complications from workup, anxiety), patient values; (3) **LDCT technique**: low-dose protocol, < 1.5 mSv; (4) **Lung-RADS classification** results: - Category 1-2 (negative/benign) → annual LDCT; - Category 3 (probably benign) → 6-mo follow-up LDCT; - Category 4A → 3-mo LDCT or PET; - Category 4B/4X → biopsy or specialist; (5) **Stop screening when**: develop health problem limiting life expectancy or ability/willingness for curative treatment; > 15 yr since quitting; > age 80; (6) **Smoking cessation integration** — most impactful + improves screening efficacy; offer at every visit; (7) **Coverage**: Medicare + most insurance per USPSTF; ICD codes; (8) **Quality framework**: registry (American College of Radiology), accredited program, multidisciplinary nodule clinic; (9) **Avoid CXR or sputum cytology** — not effective screening; (10) **Multidisciplinary**: PCP + radiology + pulmonology + thoracic surgery + tobacco treatment + cancer center

---

Lung CA screening: USPSTF 2021 — LDCT annual age 50-80, ≥ 20 pack-year, quit < 15 yr. Shared decision-making. Lung-RADS follow-up. Stop when life expectancy limited or quit > 15 yr. Smoking cessation integrated. Multidisciplinary.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'family_medicine'
  and scenario = 'ผู้ป่วยอายุ 62 ปี อดีตสูบบุหรี่ 35 pack-years, เลิก 8 ปีก่อน; ไม่มีอาการ; ถามเรื่อง screening มะเร็งปอด';

commit;
