-- ===============================================================
-- UPDATE chunk 4/8: pathology (25 questions)
-- ===============================================================

begin;

update public.mcq_questions
set choices = '[{"label":"A","text":"Random unit"},{"label":"B","text":"Transfusion Medicine — Compatibility + Reactions"},{"label":"C","text":"Skip ID"},{"label":"D","text":"Refuse"},{"label":"E","text":"Discard"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Transfusion Medicine — Compatibility + Reactions: (1) **Pre-transfusion testing**: - **ABO/Rh typing** (forward + reverse — confirm match); - **Antibody screen** (3-cell panel detects clinically significant alloantibodies); - **Crossmatch** (donor + recipient): immediate spin (ABO confirm), antiglobulin (full match if antibody+), electronic crossmatch (if validated); - **Type & screen** valid 72 hours post-transfusion/pregnancy (new antibodies); (2) **Component selection**: - **PRBC**: ABO compatible (not necessarily identical for ABO if no whole blood); Rh-matched for Rh-neg recipients (especially women childbearing); - **Platelets**: ABO ideally matched (plasma in unit), Rh-matched for Rh-neg women childbearing (small RBC contamination → anti-D); - **FFP**: ABO match (plasma — donor anti-A/B → recipient RBCs); - **Cryoprecipitate**: ABO match preferred; (3) **Indication-based use** + restrictive transfusion (Hb < 7 stable, < 8 cardiac/symptomatic); single-unit then reassess; (4) **Pre-transfusion patient identification — two patient identifiers** at issue + bedside (wrong patient = most common cause of fatal hemolytic reaction); (5) **Acute transfusion reactions**: - **Acute hemolytic (ABO mismatch)**: fever, hypotension, pain, hemoglobinuria, DIC, renal failure; STOP transfusion + maintain IV access + saline + monitor — workup + report blood bank; - **FNHTR** (febrile non-hemolytic): cytokines + recipient anti-leukocyte Abs; leukoreduced products reduce; antipyretic; - **Allergic/urticarial**: histamines (donor plasma); antihistamine ± slow + continue if mild; severe → epinephrine; - **TRALI** (transfusion-related acute lung injury): ARDS within 6 h, donor anti-HLA/HNA Abs to recipient leukocytes; leading cause transfusion mortality; supportive; male-predominant plasma policy reduced; - **TACO** (transfusion-associated circulatory overload): volume + cardiac; furosemide + slow rate; common in elderly; - **Bacterial sepsis** (platelet > RBC); - **Anaphylaxis** (IgA-deficient + anti-IgA — wash or use IgA-deficient donor); (6) **Delayed reactions**: delayed hemolytic (3-14 d, anamnestic), GvHD (irradiate for at-risk — immunocompromised, neonates, intrauterine, directed donors, HLA-matched units), iron overload (chronic — chelation), alloimmunization, post-transfusion purpura, infectious; (7) **Hemovigilance** + reporting + RCA

---

Transfusion: type/screen/crossmatch + ABO/Rh; two-identifier ID bedside (wrong pt → fatal hemolytic). Acute reactions: hemolytic, FNHTR, allergic, TRALI (leading mortality), TACO, sepsis. Delayed: hemolytic, GvHD (irradiate), iron overload. Hemovigilance.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'pathology'
  and scenario = 'ผู้ป่วยอายุ 65 ปี post-op day 1 hip replacement — Hb 6.8 → ordered 2 units PRBC; blood bank workflow + compatibility + acute hemolytic + non-hemolytic transfusion reactions';

update public.mcq_questions
set choices = '[{"label":"A","text":"PRBC only"},{"label":"B","text":"Massive Transfusion Protocol (MTP)"},{"label":"C","text":"FFP only"},{"label":"D","text":"Crystalloid only"},{"label":"E","text":"Refuse"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Massive Transfusion Protocol (MTP): (1) **Definition**: > 10 units PRBC/24 h OR > 4 units in 1 h OR replacement of patient''s blood volume; activate early; (2) **Ratio-based resuscitation**: **1:1:1 (PRBC : FFP : platelet apheresis units)** — based on PROPPR trial — improved hemostasis (vs 1:1:2); mimics whole blood; (3) **Whole blood (low-titer group O whole blood — LTOWB)** increasingly used in military + trauma centers — single-product simpler logistics; (4) **Adjuncts**: - **Tranexamic acid (TXA)** — 1 g IV bolus + 1 g over 8h within 3 h of trauma (CRASH-2/3); reduces mortality; - **Calcium replacement** — massive citrate (anticoagulant in blood products) chelates ionized Ca → hypocalcemia → contractility + coag impaired — monitor + replace with CaCl2 or Ca gluconate; - **Warm products + patient** — prevent hypothermia (coag impaired below 35°C); - **Bicarbonate / pH management** — acidosis impairs coag (lethal triad: acidosis + hypothermia + coagulopathy); (5) **Damage control resuscitation principles**: permissive hypotension (SBP 80-90 if no head injury) until surgical control; hemostatic resuscitation; limit crystalloid (worsens coagulopathy + edema); (6) **Lab role + monitoring**: - **Fast turnaround**: CBC, PT/PTT/INR, fibrinogen, blood gas, ionized Ca, lactate q15-30 min; - **TEG/ROTEM** viscoelastic — guides product use (fibrinogen, platelet, factor) more dynamically than conventional coag tests; - **Communication** with blood bank — anticipate need + prepare products; - **Universal donor** (O- for women + men with unknown, O+ for men) for emergency release before type/screen ready; (7) **Targeted fibrinogen replacement**: cryoprecipitate or fibrinogen concentrate if fibrinogen < 1.5-2 g/L; (8) **PCC (4-factor)** + vitamin K for anticoagulant reversal; (9) **Reassess + deactivate** when bleeding controlled; (10) **Multidisciplinary**: trauma surgery + anesthesia + blood bank + lab + ED + ICU

---

MTP: 1:1:1 PRBC:FFP:plt (PROPPR); LTOWB emerging. TXA within 3h (CRASH-2/3). Calcium replacement (citrate chelation). Warm + correct acidosis (lethal triad). TEG/ROTEM-guided. Damage control resuscitation; limit crystalloid. Universal O- emergency.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'pathology'
  and scenario = 'ผู้ป่วย trauma + hemorrhagic shock — activate massive transfusion protocol (MTP); ratio + monitoring + adjuncts + lab role';

update public.mcq_questions
set choices = '[{"label":"A","text":"Hemophilia A"},{"label":"B","text":"von Willebrand Disease (vWD) — Pathology + Diagnosis"},{"label":"C","text":"ITP"},{"label":"D","text":"TTP"},{"label":"E","text":"DIC"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** von Willebrand Disease (vWD) — Pathology + Diagnosis: (1) **Background**: most common inherited bleeding disorder (~ 1%); autosomal (dominant typically); mucocutaneous bleeding (nosebleed, menses, GI, post-procedure); (2) **vWF function**: - **Platelet adhesion** at vascular injury (binds collagen + GPIb on platelets); - **Factor VIII carrier** (protects from degradation) — explains low FVIII in severe vWD; (3) **Classification**: - **Type 1** (partial quantitative — ~ 75%): vWF Ag + activity low (parallel); mild; - **Type 2** (qualitative — abnormal vWF): subtypes 2A (loss of large multimers), 2B (gain-of-function platelet binding — thrombocytopenia), 2M (loss of platelet binding without multimer abnormality), 2N (defective FVIII binding — mimics hemophilia); - **Type 3** (severe quantitative — virtually absent): autosomal recessive; severe joint bleeding-like hemophilia A; (4) **Lab workup**: - vWF antigen (vWF:Ag); - vWF activity (vWF:RCo ristocetin cofactor — measures platelet binding function; alternatives GPIbM, GPIbR); - **vWF:Ag / vWF:RCo ratio** distinguishes types (< 0.7 = qualitative defect type 2); - Factor VIII level; - **Multimer analysis** for type 2 distinction; - **Platelet function** (PFA-100 — closure time prolonged but not specific); - **Bleeding score** (ISTH); (5) **Pitfalls**: vWF is acute-phase reactant — false-normal in stress/pregnancy/OCP; blood type O ~ 25% lower baseline vWF; repeat testing; (6) **Acquired vWS**: aortic stenosis (shear), LVAD, MGUS, hypothyroidism, autoimmune; (7) **Treatment**: - **DDAVP (desmopressin)** — type 1 mild + selected type 2; releases endothelial vWF stores; test dose response; tachyphylaxis with repeat doses; - **vWF concentrate** (with or without FVIII — Humate-P, Wilate; recombinant vWF Vonvendi) for type 3, severe, surgical prophylaxis, type 2 unresponsive to DDAVP; - **Antifibrinolytic** (TXA) adjunct; - **OCP** for menorrhagia; - **Emicizumab** in development for vWD/hemophilia overlap; (8) **Multidisciplinary**: hematology + dental + OB-GYN + nurse coordinator

---

vWD: most common inherited bleeding. Types 1 (quantitative partial), 2 (qualitative — 2A/B/M/N), 3 (severe quant). vWF:Ag + RCo + FVIII + multimers + ratio. DDAVP for type 1; vWF concentrate for type 3/severe. TXA adjunct. Acquired vWS exists. Multidisciplinary.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'pathology'
  and scenario = 'ผู้ป่วยอายุ 35 ปี — recurrent nosebleeds + heavy menses + family history of bleeding → coagulation workup: PT normal, aPTT mildly prolonged, platelet count normal, BT prolonged, vWF antigen low, vWF activity (RCo) low, factor VIII low; การวินิจฉัย';

update public.mcq_questions
set choices = '[{"label":"A","text":"Diabetic nephropathy"},{"label":"B","text":"Lupus Nephritis (Class IV — Diffuse Proliferative) ISN/RPS Classification"},{"label":"C","text":"FSGS"},{"label":"D","text":"IgA nephropathy"},{"label":"E","text":"ATN"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Lupus Nephritis (Class IV — Diffuse Proliferative) ISN/RPS Classification: (1) **ISN/RPS 2003 (updated 2018) classification**: - **Class I**: minimal mesangial — normal LM, mesangial deposits IF/EM; - **Class II**: mesangial proliferative; - **Class III**: focal (< 50% glomeruli) proliferative; - **Class IV**: **diffuse (≥ 50%) proliferative** (this case) — endocapillary proliferation, wire loops, subendothelial deposits, fibrinoid necrosis, crescents — most aggressive; - **Class V**: membranous (subepithelial deposits like idiopathic MN but immune complex); - **Class VI**: advanced sclerosis (≥ 90%); - **Class III + V** and **IV + V** combinations; (2) **Activity + chronicity scores** (NIH) — guides treatment + prognosis; (3) **Immunofluorescence**: **''full-house''** (IgG + IgA + IgM + C3 + C1q) classic for lupus — distinguishes from idiopathic MN/MPGN; subendothelial in proliferative, subepithelial in membranous; (4) **EM**: subendothelial + mesangial deposits (proliferative); subepithelial (membranous); **tubuloreticular inclusions** in endothelial cells (interferon signature — lupus + viral); ''fingerprint'' deposits; (5) **Workup**: ANA, dsDNA (specific lupus), C3/C4 (low in active), Smith Ab, anti-phospholipid, urine sediment + UPCR, kidney biopsy when proteinuria > 0.5 g/d or active sediment with eGFR change; (6) **Treatment** (KDIGO 2021): - **Class III/IV induction**: mycophenolate (preferred) OR low-dose IV cyclophosphamide (Euro-Lupus) + steroids; ± **belimumab** (BLISS-LN) + standard; **voclosporin** (AURORA) + MMF + steroid — recent additions improve renal response; - **Class V**: MMF + RAS blockade ± steroids; - **Maintenance**: MMF or azathioprine + low-dose steroid; - **Refractory**: rituximab consideration (LUNAR negative but used); calcineurin inhibitors; (7) **Adjuncts**: HCQ all SLE (improves renal + extrarenal outcomes), RAS blockade, SGLT2 inhibitors (DAPA-CKD/EMPA-KIDNEY — proteinuria reduction), BP control; (8) **Pregnancy planning** + APS screening + LMWH if positive

---

Lupus nephritis: ISN/RPS Class I-VI; class IV diffuse proliferative most aggressive. Full-house IF + TR inclusions hallmark. Activity + chronicity scores. Induction: MMF or low-dose CYC + steroids ± belimumab or voclosporin (new). HCQ + RAS blockade + SGLT2.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'pathology'
  and scenario = 'ผู้ป่วยอายุ 30 ปี SLE — proteinuria + active sediment → kidney biopsy: glomeruli with endocapillary proliferation + wire loops + subendothelial deposits + ''full-house'' immunofluorescence (IgG, IgA, IgM, C3, C1q); EM: subendothelial deposits + tubuloreticular inclusions; classification';

update public.mcq_questions
set choices = '[{"label":"A","text":"Lupus"},{"label":"B","text":"IgA Nephropathy (Berger''s)"},{"label":"C","text":"Minimal change"},{"label":"D","text":"ATN"},{"label":"E","text":"FSGS"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** IgA Nephropathy (Berger''s): (1) **Most common primary glomerulonephritis worldwide**; (2) **Clinical**: gross hematuria post-URI (synpharyngitic — within days vs PSGN 1-2 wk after); microscopic hematuria + proteinuria + variable BP + Cr; can present as nephrotic + crescentic RPGN + AKI; (3) **Histology**: - **LM**: mesangial hypercellularity + matrix expansion; segmental sclerosis; crescents in severe; - **IF**: dominant or codominant **IgA** in mesangium (must be dominant); ± IgG, IgM, C3; C1q usually absent (vs lupus); - **EM**: electron-dense deposits mesangial (predominant) ± subendothelial in active disease; (4) **Pathogenesis**: galactose-deficient IgA1 + IgG autoantibodies → mesangial deposition + injury; (5) **Oxford classification (MEST-C)** scoring: Mesangial hypercellularity, Endocapillary hypercellularity, Segmental sclerosis, Tubular atrophy/interstitial fibrosis, Crescents — guides prognosis + treatment; (6) **Spectrum**: includes IgA vasculitis (formerly HSP) — same pathology with extrarenal (palpable purpura, arthralgia, GI) — more common children; (7) **Workup**: rule out secondary (cirrhosis, HIV, celiac), complement (C3/C4 usually normal), serologies; (8) **Treatment** (KDIGO 2021/2024 update): - **Supportive (foundation)**: RAS blockade (ACE/ARB) maximally tolerated to lower proteinuria + BP; salt restriction; BMI; smoking cessation; - **SGLT2 inhibitors** (dapagliflozin DAPA-CKD, empagliflozin EMPA-KIDNEY) — recommended for proteinuric CKD; reduce progression; - **Endothelin antagonists** (sparsentan PROTECT) — newer, approved; - **Targeted-release budesonide (Nefecon TARGET-A)** — gut-targeted, approved for high-risk progressive — addresses mucosal IgA; - **Systemic immunosuppression** controversial — for crescentic/rapidly progressive only typically (steroids; ± rituximab/MMF); - **Anti-complement** (iptacopan — for IgAN, MN under study) emerging; (9) **Renal transplant** for ESRD — recurs in graft ~ 30%; (10) **Multidisciplinary** nephrology + pathology + dietitian

---

IgA nephropathy: most common 1° GN; synpharyngitic hematuria. Mesangial IgA-dominant IF + mesangial deposits. Oxford MEST-C scoring. Tx: RAS blockade + SGLT2 + sparsentan + Nefecon (gut-targeted budesonide). Anti-complement emerging. Transplant recurs ~30%.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'pathology'
  and scenario = 'ผู้ป่วยอายุ 28 ปี — gross hematuria 2 d after URI → kidney biopsy: mesangial proliferation + dominant IgA deposits on IF + electron-dense deposits in mesangium; การวินิจฉัยและการรักษา';

update public.mcq_questions
set choices = '[{"label":"A","text":"Meningioma"},{"label":"B","text":"Glioblastoma, IDH-wildtype (WHO grade 4) — CNS5 Classification 2021"},{"label":"C","text":"Lymphoma"},{"label":"D","text":"Mets"},{"label":"E","text":"Refuse"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Glioblastoma, IDH-wildtype (WHO grade 4) — CNS5 Classification 2021: (1) **WHO CNS5 (2021) integrates molecular + histology**: layered diagnosis (histopathological + CNS WHO grade + molecular); (2) **Adult-type diffuse gliomas (3 types)**: - **Astrocytoma, IDH-mutant** (grade 2, 3, or 4); - **Oligodendroglioma, IDH-mutant, 1p/19q-codeleted** (grade 2 or 3); - **Glioblastoma, IDH-wildtype** (grade 4) — most common, worst prognosis; (3) **Glioblastoma criteria** (IDH-WT adult): histologic — microvascular proliferation OR necrosis OR molecular features even in lower-grade morphology — **TERT promoter mutation, EGFR amplification, +7/-10** = grade 4 / glioblastoma regardless of morphology; (4) **IHC + molecular workup**: - **IDH1 R132H IHC** (most common, ~ 90% IDH-mutant); negative needs sequencing to rule out non-canonical; - **ATRX** loss (in IDH-mutant astrocytoma); - **GFAP, OLIG2, SOX2** (glial markers); - **MGMT promoter methylation** (predictive of TMZ response, prognostic); - **p53** (often mutated IDH-mutant astrocytoma); - **TERT promoter, EGFR, +7/-10** (GBM); - **1p/19q codeletion** (oligo); - **H3 K27M** for diffuse midline glioma; H3 G34 for diffuse hemispheric glioma; **CDKN2A/B homozygous deletion** (worsens grade in IDH-mutant astrocytoma to grade 4); (5) **Treatment GBM** (newly diagnosed): - **Maximal safe resection** (5-ALA fluorescence guided improves); - **Adjuvant radiotherapy + concurrent + adjuvant temozolomide** (Stupp protocol); - **Tumor treating fields (TTFields, Optune)** added — EF-14 trial — survival benefit; - **MGMT methylation** predicts TMZ benefit; (6) **Recurrent**: bevacizumab, lomustine, regorafenib, re-resection/RT; clinical trials; (7) **IDH-mutant gliomas**: now **vorasidenib** (INDIGO trial) — IDH1/2 inhibitor — significant PFS improvement grade 2 IDH-mutant — emerging standard pre-RT/chemo selection; (8) **Multidisciplinary**: neurosurgery + neuro-onc + RT + neuropath + neuro-radiology

---

GBM IDH-WT WHO CNS5 grade 4: TERT/EGFR/+7-10 = GBM even without classic histology. IDH/ATRX/MGMT/1p19q workup. Stupp (RT+TMZ) + TTFields. MGMT methylation predicts TMZ. Vorasidenib INDIGO for IDH-mutant. Multidisciplinary.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'pathology'
  and scenario = 'ผู้ป่วยอายุ 60 ปี — frontal mass + altered mental status; biopsy: glial tumor + nuclear atypia + microvascular proliferation + necrosis with palisading; IHC: GFAP+, ATRX retained, IDH-1 R132H NEGATIVE; molecular: TERT promoter mutated, EGFR amplified, +7/-10';

update public.mcq_questions
set choices = '[{"label":"A","text":"Skip"},{"label":"B","text":"Medical Examiner Forensic Autopsy Workflow"},{"label":"C","text":"Random"},{"label":"D","text":"Refuse"},{"label":"E","text":"No exam"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Medical Examiner Forensic Autopsy Workflow: (1) **Jurisdiction**: cases requiring ME — sudden, unexpected, unattended, traumatic (accident, suicide, homicide), in-custody, suspicious, occupational, public health concern, no recent attending physician; varies by state/country; (2) **Scene investigation + history**: scene visit if possible (death scene context, position, ligatures, evidence, drugs), interview family/witnesses, medical history review, social history, medications, prior incidents; (3) **External examination**: identification (visual, fingerprint, dental, DNA), photographs, livor + rigor + algor (postmortem changes — estimate PMI), injuries documented (location, type, age — antemortem vs postmortem distinction), tattoos + scars; (4) **Internal examination**: full autopsy — gross + histology all organs; brain (after fixation 2-3 wk if neuropathology); cardiac (weight, valve circumferences, coronaries, conduction); pulmonary; abdominal; (5) **Specimen collection (toxicology)**: blood (peripheral femoral preferred, central caval less ideal), urine, vitreous (most stable PMI changes, alcohol), bile, liver, hair (chronic), gastric contents; preserved + sealed; (6) **Toxicology** (essential many cases): comprehensive screen + targeted (opioids, fentanyl analogs critical given opioid epidemic; stimulants; ethanol; sedatives; psychotropic), confirmatory mass spec; (7) **Ancillary**: microbiology (sudden infant death, sepsis), microbiology + viral (sudden), histology, neuropathology, cardiac pathology (channelopathy/CM molecular autopsy — saved blood for genetic), ophthalmology (retinal hemorrhage — pediatric abusive head trauma); (8) **Cause of death** (immediate, contributing) + **Manner** (natural, accident, suicide, homicide, undetermined); (9) **Report + death certificate**; (10) **Communication**: family, law enforcement, courts (expert testimony); (11) **Molecular autopsy**: sudden cardiac death — genetic testing for LQTS, CPVT, HCM, ARVC; sudden unexplained infant death; collaboration with cardiology genetic; (12) **Education + quality**: institutional QI, NAME accreditation

---

ME autopsy: jurisdiction + scene + external + internal exam. Tox specimens (peripheral blood, vitreous, urine, liver). COD (immediate/contrib) + manner (natural/accident/suicide/homicide/undetermined). Molecular autopsy for sudden cardiac. NAME standards.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'pathology'
  and scenario = 'Medical examiner — sudden death 35 yo male found in apartment; postmortem exam + cause of death + manner determination workflow + toxicology + scene investigation';

update public.mcq_questions
set choices = '[{"label":"A","text":"Random"},{"label":"B","text":"Platelet Function + Primary Hemostasis"},{"label":"C","text":"No tests"},{"label":"D","text":"Skip"},{"label":"E","text":"Refuse"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Platelet Function + Primary Hemostasis: (1) **Primary hemostasis steps**: - **Adhesion**: vWF binds exposed collagen at injury → platelet GPIb/IX/V binds vWF → tethering; - **Activation**: ADP, thrombin, TxA2, collagen activate platelets → shape change (pseudopods), granule release, phospholipid exposure (PS); - **Aggregation**: GPIIb/IIIa activates + binds fibrinogen + vWF → platelet-platelet bridges; (2) **Granules**: alpha (P-selectin, fibrinogen, vWF, factor V, PDGF), dense (ADP, ATP, serotonin, calcium, polyphosphate); (3) **Receptors**: GPIb-IX-V (vWF), GPIIb/IIIa (fibrinogen — αIIbβ3 integrin), GPVI (collagen), P2Y12 (ADP — clopidogrel target), TxA2 receptor (aspirin target via COX-1); (4) **Primary hemostasis disorders**: - **Quantitative**: thrombocytopenia (production — BM failure, suppression; destruction — ITP, TTP, DIC; sequestration — splenomegaly); thrombocytosis (reactive vs MPN — ET, PV); - **Qualitative**: inherited — **Bernard-Soulier** (GPIb deficiency — large platelets, mild thrombocytopenia, vWF doesn''t bind), **Glanzmann thrombasthenia** (GPIIb/IIIa deficiency — aggregation absent), storage pool diseases (dense granule), Wiskott-Aldrich, MYH9-related; acquired — uremia, drugs (aspirin, clopidogrel/P2Y12i, NSAIDs, anti-GPIIb/IIIa); (5) **Tests**: - **Platelet count** (CBC); - **PFA-100/200** (closure time — adhesion-aggregation under shear — screen for vWD + qualitative defects); - **Light transmission aggregometry (LTA)** — gold standard agonist-induced aggregation (ADP, epi, collagen, ristocetin, arachidonic acid); - **Whole blood impedance aggregometry**; - **Flow cytometry** for receptors (GPIb, IIb/IIIa); - **Bleeding time** — obsolete; - **TEG/ROTEM** platelet contribution; - **VerifyNow** P2Y12 inhibition monitoring; (6) **Treatment for platelet disorders**: ITP (steroids, IVIG, TPO mimetics, splenectomy, rituximab), TTP (PLEX, caplacizumab, rituximab), inherited Glanzmann/Bernard-Soulier (DDAVP, antifibrinolytic, recombinant factor VIIa, platelet transfusion); (7) **Antiplatelet therapy review** + holding for procedures; spacious area

---

Primary hemostasis: adhesion (GPIb-vWF) → activation (granules) → aggregation (GPIIb/IIIa-fibrinogen). Tests: count, PFA, LTA, flow, TEG, VerifyNow. Disorders: thrombocytopenia (qty), Bernard-Soulier/Glanzmann/storage (qual), acquired (drugs/uremia). Tx by disorder.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'pathology'
  and scenario = 'Resident question — fundamentals of platelet function + primary hemostasis pathway + clinical platelet function tests + clinical applications';

update public.mcq_questions
set choices = '[{"label":"A","text":"Random"},{"label":"B","text":"Coagulation Cascade + Cell-Based Model"},{"label":"C","text":"Random"},{"label":"D","text":"Skip"},{"label":"E","text":"Refuse"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Coagulation Cascade + Cell-Based Model: (1) **Classical waterfall (pedagogical)**: - **Intrinsic** (contact): XII → XIIa → XI → XIa → IX → IXa + VIIIa → X activation; - **Extrinsic** (tissue factor): TF + VIIa → X activation; - **Common**: X → Xa + Va → prothrombin (II) → thrombin (IIa) → fibrinogen (I) → fibrin → cross-linked by XIIIa; (2) **Cell-based model (modern — Hoffman + Monroe 2001)** — physiologically accurate: - **Initiation**: TF-bearing cells (subendothelial) bind VIIa → small amount Xa → thrombin (priming); - **Amplification**: thrombin activates platelets + V + VIII + XI on platelet surface; - **Propagation**: massive thrombin burst on platelet surface → fibrin formation; - Highlights platelet-coag interaction + integration with primary hemostasis; (3) **Anticoagulant systems** (natural balance): - **Antithrombin** (inhibits IIa, Xa, IXa — heparin enhances); - **Protein C + S** (cleave Va + VIIIa); - **TFPI** (tissue factor pathway inhibitor); (4) **Fibrinolysis**: plasminogen → plasmin (by tPA, urokinase) → degrades fibrin → D-dimer; antagonized by PAI-1 + alpha-2 antiplasmin + TAFI; (5) **Clinical tests**: - **PT/INR**: extrinsic + common (factors VII, X, V, II, fibrinogen); standardized INR via ISI for warfarin monitoring; - **aPTT**: intrinsic + common (factors XII, XI, IX, VIII, X, V, II, fibrinogen); heparin monitoring; - **Thrombin time** (TT): fibrinogen step, prolonged in dysfibrinogenemia, heparin, DTIs; - **Fibrinogen** (Clauss); - **Mixing study** (1:1 with normal plasma): corrects = factor deficiency; doesn''t correct = inhibitor (factor inhibitor, lupus anticoagulant, DOAC, heparin); - **Specific factor levels**; - **Anti-Xa** for LMWH + DOAC (calibrated assays); - **TEG/ROTEM** viscoelastic — global function + real-time; - **D-dimer**: VTE rule-out, DIC; (6) **Disorders**: factor deficiencies (hemophilia A/B, factor VII, XI, fibrinogen), DIC, liver disease, vitamin K deficiency, anticoagulant drugs; (7) **Reversal**: vitamin K + 4F-PCC (warfarin), andexanet alfa (anti-Xa DOAC), idarucizumab (dabigatran), protamine (heparin); (8) **DOAC monitoring**: not routine; specialized assays when needed

---

Coag: classical waterfall (intrinsic/extrinsic/common) → cell-based model (initiation/amplification/propagation on platelet surface). PT (extrinsic) + aPTT (intrinsic) + TT + mixing study + fibrinogen + anti-Xa + TEG. Anti-thrombin/Protein C-S/TFPI natural. Reversal agents.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'pathology'
  and scenario = 'Resident question — fundamentals of coagulation cascade (extrinsic + intrinsic + common pathway) + clinical lab tests + new perspective (cell-based model)';

update public.mcq_questions
set choices = '[{"label":"A","text":"Skip"},{"label":"B","text":"Body Fluid Cytology Workflow + Processing"},{"label":"C","text":"Random"},{"label":"D","text":"Refuse"},{"label":"E","text":"Skip"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Body Fluid Cytology Workflow + Processing: (1) **Specimen types**: pleural, peritoneal/ascitic, pericardial, CSF, urine, washings (bronchial, peritoneal, biliary, brush), FNA (thyroid, breast, lymph node, salivary, abdominal organs, pancreas EUS-FNA), bronchoalveolar lavage, fine needle washings; (2) **Pre-analytical**: prompt to lab (delay → cell degradation, lysis); refrigerate if delay; volume guides processing approach; (3) **Processing methods**: - **Conventional smear** (Pap + Diff-Quik) — fast, basic; - **Cytospin** — small volumes/CSF — concentrates cells; - **Liquid-based cytology** (ThinPrep, SurePath) — better preservation, less obscuring blood/mucus, allows ancillary studies; - **Cell block** (formalin-fixed, paraffin-embedded centrifuged sediment) — essential — provides histologic-quality sections for IHC + molecular; - **Direct smears for FNA** + needle rinse for cell block (best of both); (4) **Stains**: - **Papanicolaou** (transparent, nuclear detail) — primary; - **Diff-Quik** (rapid romanowsky) — rapid bedside, cytoplasm/mucin; - **Special stains** (PAS, mucicarmine, Alcian blue, Ziehl-Neelsen, GMS); - **IHC on cell block**; (5) **Diagnostic categories**: - Adequate specimen documented; - Benign vs atypical vs suspicious vs malignant; - Primary vs metastatic — IHC essential (e.g., CK7/CK20, TTF-1, GATA3, PAX8, etc.); (6) **Common challenges**: reactive vs malignant mesothelial (BAP1 loss, MTAP IHC + p16/CDKN2A FISH for mesothelioma vs reactive); adenocarcinoma vs mesothelioma panel; lymphoma assessment (flow cytometry on fresh fluid); (7) **Ancillary studies** on cell block + supernatant: IHC, FISH (e.g., HER2 in breast cancer effusion, MET in lung), molecular (EGFR/ALK/PD-L1 lung, KRAS pancreas, MSI), flow cytometry (lymphoproliferative); (8) **Reporting systems**: - Bethesda (cervical, thyroid); - Milan (salivary FNA); - Paris (urine cytology) — for urothelial; - International Pancreatic; - International FNA Breast; (9) **Quality assurance**: adequacy criteria, correlation with surgical, rapid on-site evaluation (ROSE) for FNA increases yield

---

Body fluid cyto: prompt to lab; conventional smear + cell block + liquid-based + cytospin. Pap + Diff-Quik. Cell block enables IHC + molecular. Reporting systems: Bethesda/Milan/Paris/Pancreatic/Breast. ROSE for FNA. QA + correlation with surgical.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'pathology'
  and scenario = 'Resident — pathology + role of cytopathology of body fluids — workflow + processing + diagnostic challenges; cell block vs liquid-based vs conventional smear';

update public.mcq_questions
set choices = '[{"label":"A","text":"No governance"},{"label":"B","text":"POCT Management Framework"},{"label":"C","text":"Random"},{"label":"D","text":"Skip"},{"label":"E","text":"Refuse"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** POCT Management Framework: (1) **POCT definition**: laboratory testing performed near the patient — bedside, clinic, ED, OR, ICU — by non-laboratory personnel; (2) **Common POCT**: blood glucose, blood gases, urine dipstick + hCG, INR, ACT (cath lab), influenza/SARS-CoV-2, strep, troponin, BNP, lactate, hemoglobin/hematocrit; (3) **Advantages**: rapid TAT, immediate clinical action; (4) **Risks**: variable operator competency, less rigorous QC, devices vary in accuracy, documentation challenges, errors in patient ID + result entry; (5) **Governance**: - **POCT coordinator** — laboratory-trained, oversight; - **Multidisciplinary POCT committee** (lab + nursing + physician + risk + IT); - **Policies + procedures** standardized; - **Accreditation oversight (CAP, TJC, ISO 15189, CLIA)** — POCT held to same standards as central lab; (6) **Operator training + competency**: - Initial training + documented; - **Annual competency assessment** (CLIA 6 elements: direct observation, monitoring, blind sample analysis, problem-solving, procedure review); - Pediatric, surgical, dialysis special considerations; (7) **Quality control**: - QC frequency per manufacturer + regulatory; - Daily QC for many; - QC documentation + review; - Linearity, calibration verification; - Internal proficiency testing (PT) + external (CAP surveys, AAFP); - Comparison studies POCT vs central lab; (8) **Connectivity**: middleware connects POCT to LIS + EHR — eliminates manual entry errors, ensures documentation, QC compliance; (9) **Lot-to-lot verification**, reagent storage monitoring, expiration tracking; (10) **Incident reporting + RCAs** for errors; (11) **Cost-effectiveness analysis** vs central testing; (12) **Continuous review** with clinical input + outcomes; (13) **Examples of governance failures**: bedside glucose mismatches → wrong insulin → hypoglycemia events

---

POCT: rapid testing near patient. Governance: coordinator + multidisciplinary committee + accreditation (CAP/TJC/CLIA/ISO). Training + annual competency (6 CLIA elements). QC + PT + comparison. Middleware connectivity. Incident reporting.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'pathology'
  and scenario = 'Pathology lab — point-of-care testing (POCT) implementation + quality + accreditation + governance';

update public.mcq_questions
set choices = '[{"label":"A","text":"Single specialty"},{"label":"B","text":"AML Integrative Multidisciplinary Care"},{"label":"C","text":"Random"},{"label":"D","text":"Refuse"},{"label":"E","text":"Skip"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** AML Integrative Multidisciplinary Care: (1) **Diagnosis phase**: pathology (morphology + cytochemistry + flow + cytogenetics + molecular FLT3, NPM1, CEBPA, IDH1/2, TP53, KMT2A, RUNX1, ASXL1, comprehensive NGS panel) + hematology + risk stratification (ELN 2022 favorable/intermediate/adverse); (2) **Treatment selection**: - Fit for intensive: 7+3 (cytarabine + anthracycline) ± midostaurin (FLT3) or gemtuzumab (CD33+ core-binding); - APL: ATRA + arsenic — > 90% cure; - Unfit for intensive: **venetoclax + azacitidine/decitabine** (VIALE-A) — transformed outcomes; - Targeted: ivosidenib + aza (IDH1), enasidenib (IDH2), olutasidenib, gilteritinib (FLT3 R/R), revumenib (KMT2A/NPM1); (3) **Multidisciplinary team**: hematology + transplant + pathology + transfusion + ID + ICU + pharmacy + nursing + nutrition + social work + mental health + chaplaincy + research/trials + cardio-onc (anthracycline) + supportive care; (4) **Supportive**: transfusion (PRBC + platelets — irradiated for those moving to HCT, CMV-safe), antifungal/antibacterial prophylaxis, growth factors (selected), TLS prophylaxis (rasburicase, hydration), nutrition, central line care, oral care, exercise, mental health; (5) **Patient + family education + decision-making**: shared decisions on intensity, goals, palliative integration; advance care planning; (6) **HCT evaluation** for adverse-risk and intermediate-risk if available + appropriate fitness — early HLA typing + donor search; complications (GVHD, infection, late effects); (7) **MRD monitoring** (multiparameter flow + molecular — NPM1, CBF, FLT3) — guides post-remission, transplant timing; (8) **Survivorship + late effects** (cardiotoxicity, secondary malignancy, fertility, psychosocial, post-HCT issues); (9) **Clinical trials integration**; (10) **Equity**: access, financial toxicity, geographic disparities; (11) **Palliative integration early** improves outcomes

---

AML integrative care: pathology + molecular (ELN 2022) → fitness-based treatment (7+3 + midostaurin vs ven-aza vs targeted). Multidisciplinary + supportive (TLS, infection prophy, transfusion). HCT for adverse. MRD-guided. Survivorship + palliative early.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'pathology'
  and scenario = 'Patient with newly diagnosed acute myeloid leukemia — multidisciplinary integrative care from diagnosis through treatment + survivorship';

update public.mcq_questions
set choices = '[{"label":"A","text":"Single specialty"},{"label":"B","text":"Kidney Transplant Pathology Integrative Care"},{"label":"C","text":"Random"},{"label":"D","text":"Refuse"},{"label":"E","text":"Skip"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Kidney Transplant Pathology Integrative Care: (1) **Pre-transplant**: - Donor evaluation (living/deceased) — pathology + clinical; donor kidney biopsy (deceased — frozen for chronic changes, glomerulosclerosis, IFTA); - Recipient: HLA typing + crossmatch (complement-dependent cytotoxicity, flow, single-antigen bead — virtual crossmatch), DSA assessment; ABO compatibility (or desensitization for incompatible); - Cause of ESRD review + treatable disease (avoid recurrence); (2) **Surgical pathology of explant** (for native kidney removed if applicable) + transplant kidney; (3) **Post-transplant pathology — biopsy crucial**: - **Banff classification 2022** standardized: - **T cell-mediated rejection (TCMR)**: tubulitis (t1-3) + interstitial inflammation (i1-3) + vasculitis (v1-3); - **Antibody-mediated rejection (ABMR)**: peritubular capillaritis + glomerulitis + C4d deposition + DSA + molecular signatures (Molecular Microscope, B-HOT panel emerging); - **Chronic**: IFTA (interstitial fibrosis + tubular atrophy), chronic TCMR, chronic active ABMR, transplant glomerulopathy; - **Recurrent disease** (FSGS, IgA, MN, lupus, oxalate); - **De novo disease** (de novo MN, GBM); - **BK virus nephropathy** (SV40 IHC), CMV, EBV-PTLD; - **Drug toxicity** (CNI — striped fibrosis, isometric vacuolization); - **Polyomavirus + adenovirus**; (4) **Immunosuppression management**: - Induction (basiliximab IL-2R blocker or ATG); - Maintenance (tacrolimus + MMF + steroid taper typical); - **Belatacept** (CTLA4-Ig) — costimulation blockade alternative; - Adjustments based on biopsy + DSA + infections; (5) **Multidisciplinary**: transplant nephrology + surgery + transplant pathology + ID + pharmacy + immunology + tissue typing + nursing + nutrition + mental health + social work; (6) **Surveillance protocols** (serum creatinine + DSA + protocol biopsies in some centers); (7) **Long-term complications**: rejection, infection (opportunistic), malignancy (skin, PTLD, others — sirolimus may reduce), cardiovascular (leading cause death), metabolic, recurrent disease; (8) **Equity** + access + financial; (9) **Living donor** outcomes monitoring

---

Kidney transplant pathology integrative: HLA + DSA pre. Banff 2022: TCMR (tubulitis + interstitial) + ABMR (capillaritis + C4d + DSA). BK virus, CMV, recurrent disease, CNI tox. Immunosuppression tailored (tac + MMF; belatacept alt). Multidisciplinary long-term care.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'pathology'
  and scenario = 'Patient kidney transplant recipient — pathology + integrative care from donor evaluation to post-transplant management';

update public.mcq_questions
set choices = '[{"label":"A","text":"AML"},{"label":"B","text":"Chronic Lymphocytic Leukemia (CLL) / Small Lymphocytic Lymphoma (SLL)"},{"label":"C","text":"DLBCL"},{"label":"D","text":"MCL"},{"label":"E","text":"ALL"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Chronic Lymphocytic Leukemia (CLL) / Small Lymphocytic Lymphoma (SLL): (1) **Diagnostic criteria (iwCLL 2018)**: monoclonal B-lymphocyte count > 5 × 10⁹/L in peripheral blood; clonality + immunophenotype confirmed; SLL = same disease, tissue-based (lymph nodes), low lymphocyte count; (2) **Immunophenotype** (essential — distinguishes from other CD5+ lymphomas): - **CD5+** (T-cell antigen aberrantly expressed); - **CD19+**, CD20 dim, CD79b dim; - **CD23+** (CLL key — vs MCL CD23-); - **CD200+** (CLL — vs MCL); - **FMC7 dim/negative** (vs MCL strong); - Light chain restricted (kappa or lambda) dim; cyclin D1 negative (vs MCL); LEF1 + (CLL marker); (3) **Workup at diagnosis** (essential — risk stratification): - **IGHV mutation status**: **unmutated IGHV** (poor prognosis, more aggressive) vs **mutated** (better); - **FISH (CLL panel)**: del(13q) — best prognosis; +12; del(11q) ATM; **del(17p) TP53** — worst; - **TP53 mutation** (next-gen sequencing — important even without del(17p)); - **NOTCH1, SF3B1, BIRC3** — adverse; - **CD49d** flow — adverse; - Beta-2 microglobulin; (4) **MBL** (monoclonal B-cell lymphocytosis) — < 5 × 10⁹/L, immunophenotype like CLL — precursor, surveillance; (5) **Treatment** — only when indicated (active disease per iwCLL — progressive cytopenia, symptomatic LAD/splenomegaly, B symptoms, lymphocyte doubling < 6 mo, autoimmune cytopenia): - **Targeted therapy frontline (no chemo)**: - **BTK inhibitor** (acalabrutinib, zanubrutinib preferred over ibrutinib due to cardiac SE) ± obinutuzumab — continuous; - **Venetoclax (BCL2 inhibitor) + obinutuzumab** — fixed duration 12 mo (CLL14); - **Ibrutinib + venetoclax** fixed-duration combinations (GLOW, CAPTIVATE) emerging; - Chemo-IO (FCR, BR, R-Bendamustine) historical — limited current use; (6) **TP53/del(17p) high-risk**: avoid chemo; BTKi + venetoclax preferred; (7) **Relapsed/refractory**: switch class (BTKi → BCL2i or vice versa); pirtobrutinib (non-covalent BTKi) — BRUIN; CAR-T (lisocabtagene — TRANSCEND CLL); allo-HCT select; (8) **Complications**: hypogammaglobulinemia (infections, IVIG selected), autoimmune cytopenia (AIHA, ITP), Richter transformation (DLBCL or Hodgkin), second malignancies; (9) **Vaccinations** + infection prophylaxis (PJP, antifungal, antiviral on BTKi/BCL2i)

---

CLL/SLL: CD5+/CD19+/CD23+/CD200+/dim Ig; FMC7-/cyclin D1-/LEF1+. IGHV + FISH (del17p/TP53 high-risk) + NGS. Treat when iwCLL active. Targeted frontline: BTKi (acala/zanu) or ven-obi (CLL14). Pirtobrutinib + CAR-T R/R. Richter transformation, infections.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'pathology'
  and scenario = 'ผู้ป่วยอายุ 70 ปี — incidental lymphocytosis 25,000; smear: small mature lymphocytes + smudge cells; flow cytometry: CD5+, CD19+, CD20 dim, CD23+, CD200+, kappa-restricted dim, FMC7-, CD79b dim; การวินิจฉัย + workup + treatment';

update public.mcq_questions
set choices = '[{"label":"A","text":"Reactive"},{"label":"B","text":"Extranodal Marginal Zone Lymphoma (MALT lymphoma)"},{"label":"C","text":"DLBCL"},{"label":"D","text":"MCL"},{"label":"E","text":"Sjögren only"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Extranodal Marginal Zone Lymphoma (MALT lymphoma): (1) **Origin**: arises from chronic antigenic stimulation in mucosa-associated lymphoid tissue (MALT) — acquired or normal; (2) **Common sites + associations**: - **Gastric** — H. pylori (most studied); - **Salivary gland** — Sjögren syndrome; - **Thyroid** — Hashimoto thyroiditis; - **Ocular adnexa** — Chlamydia psittaci (some regions); - **Skin** — Borrelia (Europe); - **Lung (BALT)**, GI other sites, breast; (3) **Histology**: small B-cells (centrocyte-like, monocytoid, plasmacytic differentiation), reactive follicles colonized + ''lymphoepithelial lesions'' (B-cells infiltrating epithelium) — diagnostic; (4) **Immunophenotype**: CD20+, CD79a+; **CD5-, CD10-, CD23-, cyclin D1- (rules out other small B-cell lymphomas)**; light chain restricted (kappa or lambda); CD43 sometimes aberrant+; (5) **Genetics**: - **t(11;18)(q21;q21) BIRC3-MALT1** — most common; **predicts H. pylori eradication resistance** (gastric — choose alternate Tx if positive); - t(14;18) MALT1/IGH; t(1;14) BCL10/IGH; t(3;14) FOXP1/IGH; - Trisomy 3, 18; (6) **Workup**: identify + treat underlying chronic stimulus when possible; staging PET-CT, BM (selectively), EGD/site-specific endoscopy; (7) **Treatment** (depends on site + stage + risk + t(11;18)): - **Gastric MALT**: H. pylori eradication — induces regression in low-grade, t(11;18) negative; persistent disease or t(11;18) positive → RT (low-dose) or rituximab ± chemo; - **Non-gastric**: RT (very radiosensitive), rituximab, observation in indolent low-burden, immunochemotherapy in advanced; - **Antibiotic-responsive** in other sites (ocular — doxycycline for C. psittaci); (8) **Indolent course typically**; **transformation to DLBCL** ~ 10%; (9) **Multidisciplinary**: heme-onc + GI/specialty + ID + rheumatology

---

MALT lymphoma: chronic antigen stimulation (H. pylori/Sjögren/Hashimoto/C. psittaci). Lymphoepithelial lesions + monocytoid B-cells; CD20+/CD5-/CD10-/CD23-. t(11;18) most common — predicts H. pylori eradication resistance. Antibiotic-responsive when feasible.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'pathology'
  and scenario = 'ผู้ป่วยหญิงอายุ 65 ปี — bilateral parotid swelling chronic; biopsy: lymphoepithelial lesions + reactive germinal centers + monocytoid B-cells expanding into epithelium; flow: monoclonal kappa; IHC: CD20+, CD5-, CD10-, CD23-, cyclin D1-; การวินิจฉัย';

update public.mcq_questions
set choices = '[{"label":"A","text":"AML"},{"label":"B","text":"B-cell Acute Lymphoblastic Leukemia/Lymphoblastic Lymphoma (B-ALL/LBL)"},{"label":"C","text":"Reactive lymphocytosis"},{"label":"D","text":"Refuse"},{"label":"E","text":"Hospice"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** B-cell Acute Lymphoblastic Leukemia/Lymphoblastic Lymphoma (B-ALL/LBL): (1) **Diagnostic criteria**: ≥ 20% lymphoblasts in BM/PB (or tissue-based LBL); immunophenotyping essential; (2) **B-ALL immunophenotype**: CD19+ (pan-B), CD22+, CD79a+, **CD10+ (common ALL)**, **TdT+**, CD34+ in many, **MPO negative** (vs AML); pro-B (CD10-), common B (CD10+, surface Ig-), pre-B (cIgM+), mature B = Burkitt (sIg+); (3) **T-ALL**: cytoplasmic CD3+, CD7+, CD1a+ (cortical), CD4/CD8 variable; T-cell receptor rearrangements; (4) **Cytogenetics/molecular (essential — risk stratification, WHO HAEM5)**: - **Good risk pediatric**: hyperdiploidy (51-65), **t(12;21) ETV6-RUNX1** (cryptic — needs FISH); - **High risk**: hypodiploidy < 44, **t(9;22) BCR-ABL (Ph+)** — add TKI, **KMT2A (MLL) rearrangements** (especially infants), iAMP21, **Ph-like ALL** (CRLF2, JAK2, ABL-class — adult > pediatric, kinase fusions); - **B-other**, ETP-T-ALL (T-cell aggressive), **TCF3-PBX1**, **TCF3-HLF**, ZNF384, DUX4 (favorable); - **IKZF1 deletion** — adverse independently; (5) **MRD monitoring** (flow MRD + molecular) — strongest prognostic factor; (6) **Treatment**: - **Multi-agent chemo**: induction (corticosteroid + vincristine + anthracycline + asparaginase ± rituximab) → consolidation → CNS-directed (IT MTX/cytarabine) → maintenance (~ 2-3 yr total in pediatric); - **Ph+ ALL**: add TKI (imatinib, dasatinib, ponatinib) — survival > 80% pediatric, much improved adult; - **Pediatric > adult outcomes**; pediatric-inspired protocols extended to AYA + adult; - **Relapsed/refractory**: - **Blinatumomab** (CD19/CD3 bispecific) — pre/post-MRD-positive role; - **Inotuzumab ozogamicin** (anti-CD22 ADC); - **CAR-T (tisagenlecleucel, brexucabtagene)** — pediatric ALL revolutionary cure rates; - allo-HCT consolidation; (7) **Pediatric outcomes excellent**: > 90% cure in good-risk; (8) **Multidisciplinary** + supportive + survivorship

---

B-ALL: ≥20% blasts; CD19/CD22/CD10/TdT+, MPO-. Risk strat by genetics: hyperdiploid + t(12;21) good; hypodiploid + Ph+ + KMT2A + Ph-like + iAMP21 high. MRD-guided. Pediatric chemo + CNS prophylaxis; +TKI for Ph+. R/R: blinatumomab, inotuzumab, CAR-T.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'pathology'
  and scenario = 'ผู้ป่วยเด็กอายุ 5 ปี — fatigue + bruising + LAD; CBC: WBC 60,000 with blasts; flow: CD19+, CD10+, CD20-, CD22+, TdT+, MPO-; cytogenetics: t(12;21) ETV6-RUNX1; การวินิจฉัยและการรักษา';

update public.mcq_questions
set choices = '[{"label":"A","text":"AML"},{"label":"B","text":"Myelodysplastic Syndromes (MDS) — Classification + Management"},{"label":"C","text":"Refuse"},{"label":"D","text":"Iron deficiency"},{"label":"E","text":"B12 deficiency"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Myelodysplastic Syndromes (MDS) — Classification + Management: (1) **WHO HAEM5 (2022) / ICC**: classified by dysplasia lineage count, blast %, genetics, ring sideroblasts: - MDS with low blasts (< 5% BM, < 2% PB); - MDS with low blasts and SF3B1 mutation; - MDS with low blasts and isolated del(5q); - MDS with biallelic TP53 inactivation (poor); - MDS with increased blasts (MDS-IB1 5-9%, MDS-IB2 10-19%); - MDS, hypoplastic; - MDS, fibrotic; - MDS/MPN overlap; - (2) **IPSS-R / IPSS-M** prognostic — IPSS-M integrates 31 mutations (TP53 multi-hit worst; SF3B1, SRSF2, U2AF1, ASXL1, RUNX1, EZH2, ETV6, others); (3) **Diagnostic workup**: BM biopsy + aspirate + iron stain (ring sideroblasts) + cytogenetics + FISH + NGS panel (myeloid); flow cytometry + Ogata score; rule out copper/B12/HIV/recent chemo; (4) **MDS with del(5q) — 5q minus syndrome**: middle-aged women, macrocytic anemia, normal/elevated platelet, megakaryocyte hypolobulation; **lenalidomide highly effective**; (5) **Treatment by risk**: - **Lower-risk MDS**: ESA (erythropoietin) for symptomatic anemia + low EPO; **luspatercept (RBC)** especially SF3B1+/ring sideroblasts (COMMANDS, MEDALIST); lenalidomide for del(5q); transfusion + iron chelation; immunosuppression (ATG/cyclosporine) for hypoplastic MDS; - **Higher-risk MDS**: **hypomethylating agents (azacitidine, decitabine, oral cedazuridine-decitabine)** — backbone; **allo-HCT only curative** (eligibility based on age/comorbidities); - **AML transformation** (MDS-IB2 already AML-like — venetoclax + aza emerging in ''AML with myelodysplasia-related changes''); - **TP53-mutated MDS/AML**: very poor — magrolimab/eprenetapopt under study, mostly trials; (6) **Supportive**: transfusion + chelation; growth factors; vaccinations; (7) **Multidisciplinary**: heme + transplant + transfusion + supportive care; (8) **Symptom-focused** in older unfit patients; palliative integration

---

MDS WHO HAEM5: by lineage dysplasia + blast % + genetics (SF3B1, del(5q), TP53). IPSS-M with mutations. Tx by risk: ESA/luspatercept/lenalidomide for low-risk; HMA + allo-HCT for high-risk. TP53 multi-hit worst. Supportive + multidisciplinary.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'pathology'
  and scenario = 'ผู้ป่วยอายุ 75 ปี — pancytopenia + dysplastic features in marrow: ringed sideroblasts > 15%, blasts 6%; cytogenetics: del(5q); molecular: SF3B1 mutation + TP53 wildtype; การจำแนกและการรักษา';

update public.mcq_questions
set choices = '[{"label":"A","text":"AML"},{"label":"B","text":"Chronic Myeloid Leukemia (CML) — BCR-ABL1+"},{"label":"C","text":"Reactive leukocytosis"},{"label":"D","text":"Refuse"},{"label":"E","text":"MDS"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Chronic Myeloid Leukemia (CML) — BCR-ABL1+: (1) **Diagnostic criteria (WHO HAEM5)**: **BCR-ABL1 fusion** (t(9;22)(q34;q11.2) Philadelphia chromosome) — pathognomonic; myeloproliferation; left-shifted granulocytes + basophilia (specific) + variable eosinophilia + thrombocytosis; splenomegaly; (2) **Phases**: - **Chronic phase (CP)** — < 5% blasts in BM/PB, control of WBC achievable; - **Accelerated phase (AP)** — 10-19% blasts OR ≥ 20% basophils OR persistent thrombocytosis/penia OR new clonal evolution; - **Blast phase (BP)** — ≥ 20% blasts (myeloid 70% or lymphoid 30%) — behaves like acute leukemia; (3) **Workup**: PB + BM + cytogenetics + FISH + RT-PCR for BCR-ABL1 (p210 major, p190 minor, p230 — typing); baseline before TKI; (4) **Risk scores**: Sokal, Hasford, ELTS — guides TKI choice + monitoring; (5) **Treatment** (CP): - **TKI revolution** transformed CML survival ~ normal lifespan: - **First-gen**: **imatinib** (Gleevec); - **Second-gen**: **dasatinib, nilotinib, bosutinib** — frontline in higher-risk; - **Third-gen + asciminib (STAMP — allosteric BCR-ABL inhibitor)** approved 1L (ASC4FIRST 2024); - **Ponatinib** for T315I-mutated (resistance to other TKIs); - Choice considers comorbidities (cardiovascular — ponatinib + nilotinib caution; pleural effusion — dasatinib caution; pulmonary HTN); (6) **Monitoring**: - **BCR-ABL1 RT-qPCR (IS — international scale)** every 3 mo until MMR; milestones: BCR-ABL1 ≤ 10% at 3 mo, ≤ 1% at 6 mo, ≤ 0.1% (MMR) at 12 mo; - **Deep molecular response (MR4, MR4.5)** allows **treatment-free remission (TFR)** trial in eligible patients (sustained DMR > 2 yr) — ~ 50% maintain; - **Failure**: switch TKI, check BCR-ABL kinase domain mutations (T315I, F359, etc.); (7) **AP/BP**: more intensive — TKI + chemo ± allo-HCT; (8) **Multidisciplinary**: heme + transplant + adherence (TKI adherence critical) + pharmacy + cardiovascular + supportive; (9) **Compliance > 90% essential** for optimal response

---

CML: BCR-ABL1 t(9;22) pathognomonic; CP/AP/BP. TKI revolution: imatinib → dasatinib/nilotinib/bosutinib → ponatinib (T315I) → asciminib (STAMP). Molecular monitoring (IS); MMR at 12 mo; TFR for sustained DMR. Switch TKI + kinase mutation testing for failure.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'pathology'
  and scenario = 'ผู้ป่วยอายุ 55 ปี — high WBC 80,000 + immature myeloid cells + basophilia; BM hypercellular with granulocytic hyperplasia + blasts < 5%; FISH/PCR: **BCR-ABL1 t(9;22)** positive; การวินิจฉัยและการรักษา';

update public.mcq_questions
set choices = '[{"label":"A","text":"Secondary polycythemia"},{"label":"B","text":"Polycythemia Vera (PV) — WHO 2022"},{"label":"C","text":"MDS"},{"label":"D","text":"AML"},{"label":"E","text":"Refuse"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Polycythemia Vera (PV) — WHO 2022: (1) **Diagnostic criteria** (3 major or first 2 + minor): - Major 1: Hb > 16.5 (M) / 16.0 (F) OR Hct > 49% (M) / 48% (F) OR red cell mass > 25% mean predicted; - Major 2: BM biopsy showing hypercellular for age with trilineage growth (panmyelosis) with pleomorphic mature megakaryocytes; - Major 3: **JAK2 V617F or JAK2 exon 12 mutation**; - Minor: subnormal serum EPO level; (2) **Other Philadelphia-negative MPNs**: - **Essential thrombocythemia (ET)** — sustained Plt > 450 × 10⁹/L; JAK2 V617F (~ 50%), **CALR exon 9** (~ 25%), **MPL** (~ 3%), ''triple negative'' (~ 10-15%); BM proliferation of large mature megakaryocytes; - **Primary myelofibrosis (PMF)** — prefibrotic and overt; same drivers; cytopenia + fibrosis + leukoerythroblastic + dacrocytes/teardrops + splenomegaly; - **MDS/MPN overlap**: CMML, aCML, JMML, MDS/MPN-RS-T, MDS/MPN-NOS; (3) **MPN complications**: thrombosis (arterial + venous — splanchnic — important PV/ET; HCT control), bleeding (acquired vWS in ET high platelet), transformation to MF then AML (acquired drivers ASXL1, EZH2, SRSF2, IDH; TP53); (4) **Risk stratification PV**: - **Low risk**: age < 60 + no thrombosis history → phlebotomy + low-dose aspirin; - **High risk**: age ≥ 60 OR thrombosis history → add cytoreduction; (5) **Treatment**: - **PV cytoreduction**: hydroxyurea (1st-line typically), interferon-α / pegylated IFN (**ropeginterferon alfa-2b** FDA-approved PV — PROUD-PV) — preferred for young/pregnancy; **ruxolitinib** (JAK1/2 inhibitor) — for HU-intolerant/resistant (RESPONSE/RESPONSE-2); - **ET**: low-risk — aspirin; high-risk — hydroxyurea, anagrelide, IFN; - **MF**: ruxolitinib, fedratinib, momelotinib (anemia + ↓ spleen, MOMENTUM), pacritinib (severe thrombocytopenia, PERSIST-2); navitoclax + ruxo combos under trial; allo-HCT only curative; (6) **Thrombosis prevention** central; control Hct < 45 PV (CYTO-PV); aspirin; risk-adapted cytoreduction; (7) **Multidisciplinary**

---

PV: WHO 2022 — Hb/Hct↑ + panmyelosis + JAK2 mutation + low EPO. MPN drivers JAK2/CALR/MPL. Tx: phlebotomy + ASA all; cytoreduction (HU or ropeg-IFN) for high-risk PV. Ruxolitinib for HU-intol/resistant (RESPONSE) + MF. Hct < 45 (CYTO-PV).'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'pathology'
  and scenario = 'ผู้ป่วยอายุ 60 ปี — erythrocytosis Hb 19 + splenomegaly + pruritus; EPO low; molecular: **JAK2 V617F mutation** positive; BM: hypercellular trilineage hyperplasia; การวินิจฉัยและการรักษา';

update public.mcq_questions
set choices = '[{"label":"A","text":"Adenocarcinoma"},{"label":"B","text":"HPV-associated Oropharyngeal Squamous Cell Carcinoma (HPV-OPSCC)"},{"label":"C","text":"Lymphoma"},{"label":"D","text":"Melanoma"},{"label":"E","text":"Cyst"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** HPV-associated Oropharyngeal Squamous Cell Carcinoma (HPV-OPSCC): (1) **Epidemiology**: rising incidence, predominantly white middle-aged men, sexual transmission, oral HPV exposure; better prognosis than HPV-negative; (2) **Histology**: typically non-keratinizing, basaloid, with comedo-type necrosis; lymphoepithelial pattern; tonsil + base of tongue most common; high-risk HPV types — predominantly HPV-16 (90% of HPV+ OPSCC), HPV-18, 33, 35; (3) **HPV testing — required** for OPSCC (CAP/ASCO/CAP-WHO): - **p16 IHC** — strong + diffuse (≥ 70% nuclear + cytoplasmic) — surrogate marker, high sensitivity, lower specificity especially outside oropharynx; - **HPV DNA ISH** or **HPV E6/E7 mRNA ISH** — directly detects HPV; - **HPV PCR** including high-risk genotype; - **HPV-associated head/neck cancers limited mostly to OROPHARYNX** — non-oropharyngeal p16+ less reliable HPV-driven; (4) **Staging**: **AJCC 8th edition (2017) — DIFFERENT for HPV-related OPSCC** (cN/cM categories simpler — reflects better prognosis): - p16+ T1-T2 N1 = stage I; - cf. p16- OPSCC traditional staging; (5) **HPV+ OPSCC excellent prognosis** — 5-yr OS > 80%; (6) **Treatment**: - **De-escalation trials ongoing** (lower dose RT, less intensive chemo) — not yet standard outside trial; - **Standard**: surgery (transoral robotic — TORS) for select + neck dissection + risk-adapted adjuvant; OR primary RT + concurrent platinum chemo; - **HPV-negative**: stage-based intensive multimodal; (7) **EBV-associated nasopharyngeal carcinoma** distinct — common SE Asia + Mediterranean: EBER ISH + (testing essential), non-keratinizing undifferentiated, treat with concurrent chemoRT; nivolumab + chemo in advanced (KEYNOTE-122); (8) **HPV vaccination** primary prevention; (9) **Multidisciplinary**: H&N surgery + RT + medical onc + speech + nutrition + dental + psychology + survivorship

---

HPV+ OPSCC: non-keratinizing, p16 block+ (CAP), HPV ISH/PCR confirmatory. AJCC 8th separate staging (better prognosis). 5-yr OS > 80%. Treatment: surgery (TORS) + risk-adapted adjuvant or chemoRT. EBV NPC distinct (EBER ISH). HPV vaccination prevention.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'pathology'
  and scenario = 'ผู้ป่วยอายุ 55 ปี — heavy smoker + drinker; HPV testing positive; oropharyngeal tonsil mass biopsy: non-keratinizing squamous + basaloid cells + central necrosis; IHC: **p16 strong + diffuse block-positive**; HPV ISH or HPV PCR positive (high-risk type 16); การวินิจฉัยและการ stage';

update public.mcq_questions
set choices = '[{"label":"A","text":"Leiomyoma"},{"label":"B","text":"Gastrointestinal Stromal Tumor (GIST)"},{"label":"C","text":"Lipoma"},{"label":"D","text":"Carcinoma"},{"label":"E","text":"Refuse"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Gastrointestinal Stromal Tumor (GIST): (1) **Origin**: interstitial cells of Cajal (pacemaker cells of GI tract); (2) **Common sites**: stomach (~ 60%), small intestine (~ 30%), colon, rectum, esophagus, extraintestinal (omentum); (3) **Histology**: spindle (70%), epithelioid (20%), mixed; nuclear atypia + mitoses variable; necrosis; (4) **IHC**: **CD117 (KIT)+ ~ 95%** (most specific), **DOG1+ ~ 98%** (more sensitive — useful in KIT-negative), CD34+ (~ 70%), variable SMA; S100-, desmin- (distinguishes from leiomyoma/sarcoma/schwannoma); succinate dehydrogenase (SDHB) IHC — loss in pediatric/SDH-deficient GIST; (5) **Molecular** (essential — guides treatment): - **KIT mutation** ~ 75-80% (exon 11 most common — best response to imatinib; exon 9 — partial response, higher dose 800 mg; exon 13, 17 less common); - **PDGFRA mutation** ~ 5-10% (exon 18 D842V — **imatinib resistant** — needs avapritinib; other exon 18 sensitive); - **KIT/PDGFRA wild-type GIST**: SDH-deficient (pediatric, Carney triad, Carney-Stratakis), NF1 (small bowel multifocal), BRAF V600E, KIT exon 11 internal duplication; (6) **Risk stratification (Miettinen + Lasota)**: size + mitotic count + site + tumor rupture → very low/low/intermediate/high — guides surveillance + adjuvant; (7) **Treatment**: - **Surgical resection** primary if resectable — R0 without lymph node dissection (rare nodal mets except SDH-deficient pediatric); - **Adjuvant imatinib** 3 yr for high-risk (PERSIST-5, SSGXVIII); - **Neoadjuvant imatinib** for unresectable/borderline → downsize; - **Metastatic/unresectable**: **imatinib** (400 mg, 800 mg for KIT exon 9) → **sunitinib** (2nd line) → **regorafenib** (3rd line) → **ripretinib** (4th line, INVICTUS); - **PDGFRA D842V**: **avapritinib**; - SDH-deficient + WT: targeted by mutation; immunotherapy investigational; (8) **Multidisciplinary**: surgery + medical onc + GI + pathology + radiology + genetics (SDH/NF1/Carney)

---

GIST: CD117+/DOG1+/CD34+ (interstitial cells of Cajal). KIT mutation 75-80% (exon 11 best imatinib response); PDGFRA D842V → avapritinib. SDH-deficient + WT subset. Surgery + adjuvant imatinib for high-risk. Sequential TKIs metastatic (imatinib → sunitinib → regorafenib → ripretinib).'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'pathology'
  and scenario = 'ผู้ป่วยอายุ 60 ปี — gastric mass → biopsy: spindle cell tumor with mild atypia + low mitoses; IHC: **CD117 (KIT) +, DOG1+, CD34 + variable**, S100-, desmin-, SMA-; molecular: KIT exon 11 mutation; การวินิจฉัยและการรักษา';

update public.mcq_questions
set choices = '[{"label":"A","text":"Osteomyelitis"},{"label":"B","text":"Osteosarcoma (Conventional)"},{"label":"C","text":"Refuse"},{"label":"D","text":"Hospice"},{"label":"E","text":"Benign cyst"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Osteosarcoma (Conventional): (1) **Epidemiology**: most common primary malignant bone tumor in adolescents + young adults; bimodal — second peak in elderly (Paget-associated, post-radiation); metaphysis of long bones (distal femur > proximal tibia > proximal humerus); (2) **Histology**: **osteoid production by malignant cells** — defining feature; spindle/polygonal cells with marked pleomorphism + atypical mitoses + necrosis; lace-like + sheet-like + filigree osteoid patterns; (3) **Subtypes**: - **Conventional** (most common — osteoblastic, chondroblastic, fibroblastic); - **Telangiectatic** (cystic, mimics ABC); - **Small cell** (mimics Ewing); - **Low-grade central** (mimics fibrous dysplasia, MDM2/CDK4 amp); - **Parosteal** (low-grade, posterior distal femur, MDM2/CDK4 amp — same as well-diff/dediff liposarcoma); - **Periosteal** (intermediate-grade, chondroblastic); - **Surface high-grade**; - **Secondary** (Paget, radiation); (4) **IHC**: SATB2+ (osteoblastic), variable osteonectin, osteocalcin; non-specific largely; **MDM2/CDK4** IHC + FISH for low-grade central + parosteal; (5) **Imaging**: aggressive periosteal reaction (Codman triangle, sunburst), poorly defined, soft-tissue mass; staging — CT chest (lung mets common), MRI primary, bone scan / PET; (6) **Genetics**: complex karyotype typically; hereditary predisposition (**Li-Fraumeni — TP53**, **Hereditary retinoblastoma — RB1**, **Rothmund-Thomson, Werner, Bloom**); MDM2 amp in low-grade subtypes; (7) **Differential**: Ewing sarcoma (small round blue cell — CD99+, EWSR1-FLI1 t(11;22)), chondrosarcoma, osteomyelitis (clinical), fibrous dysplasia, GCT; (8) **Treatment**: - **Neoadjuvant chemo** (MAP — methotrexate + adriamycin + cisplatin) → wide resection → adjuvant chemo; - **Necrosis ≥ 90% (Huvos)** predicts better outcome; EURAMOS-1 showed switching post-op chemo for poor response didn''t improve; - **Limb salvage** vs amputation per anatomy + response; - **Lung mets** resection (curative possible); - **Relapsed/refractory**: regorafenib, cabozantinib, sorafenib, mifamurtide (selected); trials; (9) **Multidisciplinary**: ortho onc + medical onc + RT (limited role) + pediatric onc + pathology + radiology + rehab; (10) **Genetic counseling** when hereditary suspected

---

Osteosarcoma: osteoid by malignant cells; metaphysis adolescent. Subtypes: conventional + telangiectatic + small cell + low-grade (MDM2/CDK4 amp) + parosteal. TP53/RB1 hereditary. MAP chemo neoadj + adjuvant + wide resection; Huvos necrosis prognostic. Limb salvage. Pulmonary met resection.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'pathology'
  and scenario = 'ผู้ป่วยอายุ 15 ปี — knee pain + radiograph: aggressive bone lesion + Codman triangle + sunburst periosteal reaction; biopsy: malignant cells producing osteoid matrix + marked atypia + high mitoses; การวินิจฉัยและการรักษา';

update public.mcq_questions
set choices = '[{"label":"A","text":"Osteosarcoma"},{"label":"B","text":"CD99 (MIC2)+ membranous diffuse"},{"label":"C","text":"Lymphoma"},{"label":"D","text":"Refuse"},{"label":"E","text":"Benign"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Ewing Sarcoma: (1) **Epidemiology**: bone or soft tissue, children + young adults, diaphysis of long bones / pelvis / chest wall (Askin tumor) / paraspinal; (2) **Histology**: small round blue cell tumor — monotonous small cells with scant cytoplasm + round nuclei + finely dispersed chromatin + PAS-positive glycogen; Homer-Wright rosettes occasional; (3) **IHC**: **CD99 (MIC2)+ membranous diffuse** — characteristic (also positive in lymphoblastic lymphoma, synovial sarcoma, others — not specific alone); **NKX2.2+** (more specific), FLI1+, ERG+ (variant fusions); often vimentin+; (4) **Molecular (essential for diagnosis)** — **''Ewing sarcoma family'' genetic definition**: - **EWSR1-FLI1** ~ 85% (t(11;22)(q24;q12)); - **EWSR1-ERG** ~ 10% (t(21;22)); - Less common: EWSR1-ETV1, EWSR1-ETV4, EWSR1-FEV; - **FUS-ERG, FUS-FEV** rare; - These are ''fusions involving FET family RNA-binding protein with ETS transcription factor''; - **''Ewing-like sarcomas'' / round cell sarcomas — distinct entities** (WHO 2020): - **CIC-rearranged sarcoma** (CIC-DUX4 most common) — aggressive; - **BCOR-rearranged sarcoma** (BCOR-CCNB3) — children, distinct biology; - **Round cell sarcoma with EWSR1-non-ETS fusion**; - Different biology + treatment than classical Ewing; (5) **Differential**: osteosarcoma small cell, neuroblastoma (HVA, VMA, MIBG+; PHOX2B+), rhabdomyosarcoma alveolar (myogenin+, PAX-FOXO1), lymphoblastic lymphoma (TdT+), small cell carcinoma (cytokeratin, synaptophysin); (6) **Imaging**: diaphyseal, onion-skin or hair-on-end periosteal, large soft-tissue mass; staging CT chest, bone scan, MRI primary, PET; **BM biopsy** (high involvement frequency); (7) **Treatment**: - **Multimodal — chemo + local control + chemo**; - **VDC/IE (vincristine + doxorubicin + cyclophosphamide alternating with ifosfamide + etoposide)** — backbone; - **Interval compression** every 2 wk (Children''s Oncology Group) better outcomes pediatric; - **Local control**: surgery preferred when feasible; RT alternative or addition; - **Mets at diagnosis** ~ 25% (lung > bone > BM); lung-only better prognosis; - **Relapsed**: cyclophosphamide + topotecan, irinotecan + temozolomide, high-dose chemo + auto-SCT (controversial); trials with EZH2 inhibitor, others; (8) **Multidisciplinary**: ortho/surg + pediatric onc + RT + pathology + molecular + rehab; (9) **5-yr OS** ~ 70% localized, ~ 30% metastatic

---

Ewing: small round blue cell + glycogen; CD99 membranous + NKX2.2 + FLI1; EWSR1-FLI1 ~85%. ''Ewing-like'' (CIC-DUX4, BCOR) distinct entities. Multimodal VDC/IE chemo + surgery/RT. Interval compression pediatric. Lung-only mets better prognosis.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'pathology'
  and scenario = 'ผู้ป่วยอายุ 14 ปี — diaphysis of femur + onion-skin periosteal reaction; biopsy: small round blue cells with scant cytoplasm; IHC: CD99+ membranous (diffuse), FLI1+, NKX2.2+; molecular: EWSR1-FLI1 fusion t(11;22)';

update public.mcq_questions
set choices = '[{"label":"A","text":"Lipoma"},{"label":"B","text":"Liposarcoma — Well-Differentiated / Dedifferentiated (WHO 2020)"},{"label":"C","text":"Cyst"},{"label":"D","text":"Carcinoma"},{"label":"E","text":"Refuse"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Liposarcoma — Well-Differentiated / Dedifferentiated (WHO 2020): (1) **Categories**: - **Well-differentiated liposarcoma (WDLPS)** / **atypical lipomatous tumor (ALT)** — same biology, different name based on location (extremity = ALT, retroperitoneum/mediastinum/spermatic cord = WDLPS — implies worse prognosis due to inability to resect with margins); - **Dedifferentiated liposarcoma (DDLPS)** — abrupt transition from WD areas to high-grade non-lipogenic sarcoma; - **Myxoid liposarcoma** — round to spindle cells in myxoid stroma with delicate vasculature + lipoblasts (signet-ring); ''low-grade'' (< 5% round cell) vs ''high-grade'' (≥ 5% round cell — worse); - **Pleomorphic liposarcoma** — high-grade pleomorphic sarcoma with lipoblasts; (2) **Histology WDLPS**: mature adipocytes with size variation + scattered atypical hyperchromatic spindle cells in fibrous septa + atypical adipocytes/lipoblasts (latter not required); (3) **Molecular**: - **WDLPS/DDLPS**: **MDM2 + CDK4 amplification on 12q14-15** — diagnostic; IHC + FISH; - **Myxoid liposarcoma**: **FUS-DDIT3** (CHOP) t(12;16) ~ 95%, or rare EWSR1-DDIT3; - **Pleomorphic**: complex karyotype; (4) **Differential**: lipoma (no atypia, no MDM2 amp), spindle cell lipoma (CD34+, monosomy 13/16, no MDM2), atypical spindle cell/pleomorphic lipomatous tumor (RB1 loss); (5) **Treatment**: - **Surgical resection** mainstay — wide excision; - **WDLPS retroperitoneal**: recurrence common (multifocal in 30%) — long-term surveillance; - **DDLPS**: more aggressive, distant mets possible; - **Myxoid LPS**: highly radiosensitive — RT may be useful pre-op or post-op; characteristic dissemination to soft tissue + extrapulmonary (vs other sarcoma lung-pattern); - **Pleomorphic**: doxorubicin-based chemo for metastatic; - **Investigational**: MDM2 inhibitors (milademetan, navtemadlin) for WD/DD LPS (trials, mixed results); trabectedin myxoid LPS especially active (ET-743 binds DNA + affects FUS-DDIT3 transcription); (6) **Soft tissue sarcoma general**: sarcoma multidisciplinary centers improve outcomes; (7) **Multidisciplinary**: surgical onc + sarcoma medical onc + pathology + RT + radiology

---

Liposarcoma WHO 2020: WDLPS/ALT (MDM2/CDK4 amp 12q), DDLPS (high-grade transition), myxoid (FUS-DDIT3; round cell % matters), pleomorphic. Surgery mainstay; myxoid radiosensitive + trabectedin active. MDM2 IHC/FISH key. Sarcoma multidisciplinary centers.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'pathology'
  and scenario = 'ผู้ป่วยอายุ 50 ปี — large retroperitoneal mass → biopsy: well-differentiated lipomatous areas + spindle cells in fibrous bands; IHC: MDM2+, CDK4+; FISH: MDM2 amplification on 12q15; การวินิจฉัย';

update public.mcq_questions
set choices = '[{"label":"A","text":"Glioma"},{"label":"B","text":"Meningioma — CNS WHO 2021"},{"label":"C","text":"Lymphoma"},{"label":"D","text":"Pituitary"},{"label":"E","text":"Refuse"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Meningioma — CNS WHO 2021: (1) **Origin**: arachnoid cap cells (meningothelial); most common primary CNS tumor adult (~ 1/3); dural-based; majority benign (grade 1); women > men (2:1); progesterone receptor positive — increased growth with pregnancy/hormones; (2) **Histology**: meningothelial whorls + syncytial nests + psammoma bodies + intranuclear pseudoinclusions; many subtypes histologically (transitional, fibrous, psammomatous, secretory, microcystic, etc.); (3) **IHC**: **EMA+ (variable), SSTR2A+ (somatostatin receptor)**, vimentin+, **PR+** (better in lower grade), Ki-67 grade marker; CD34+ + STAT6+ rule out solitary fibrous tumor (different entity); (4) **CNS WHO 2021 grading**: - **Grade 1 (benign — ~ 80%)**: usual subtypes, < 4 mitoses/10 HPF; - **Grade 2 (atypical — ~ 15%)**: ≥ 4 mitoses OR ≥ 3 of (necrosis spontaneous, sheeting, small cell, prominent nucleoli, hypercellularity); brain invasion alone now grade 2 (CNS5); chordoid + clear cell subtypes; - **Grade 3 (malignant)**: ≥ 20 mitoses, frank malignancy histology, rhabdoid or papillary subtypes; (5) **Molecular criteria (CNS5)**: - **TERT promoter mutation** OR **homozygous CDKN2A/B deletion** → upgrade to **grade 3** (CNS5 — integrated grading); - **NF2** loss common (sporadic + NF2-associated multiple meningiomas); - **AKT1, TRAF7, KLF4, SMO, POLR2A** mutations in subsets — some location-correlated; - **SMARCE1** (clear cell), **BAP1** (rhabdoid), **DMD** loss (subset); - **Methylation profiling** increasingly used for accurate grading + prognosis (DKFZ classifier); (6) **Imaging**: dural-based + enhancing + dural tail; (7) **Treatment**: - **Asymptomatic small grade 1**: observation; - **Symptomatic / growing / accessible**: surgical resection — **Simpson grade** of resection (0-V) — predicts recurrence; - **Subtotal resection or higher grade**: adjuvant or salvage RT (stereotactic for small, fractionated for larger); - **Recurrent/refractory**: trials with bevacizumab, sunitinib, octreotide-derivatives, mTOR inhibitors; - **NF2 multiple meningiomas**: complex management, observation when possible, bevacizumab in some; (8) **Multidisciplinary**: neurosurgery + RT + neuropath + neuro-onc; genetic eval (NF2) if multiple/young

---

Meningioma: arachnoid cap; EMA+/SSTR2A+/PR+. CNS WHO 2021: grade 1-3 by histology + molecular (TERT or CDKN2A/B homozygous deletion → grade 3). NF2 sporadic + germline. Methylation classification emerging. Simpson resection grade; RT for residual/recurrent.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'pathology'
  and scenario = 'ผู้ป่วยอายุ 50 ปี — adult — convexity dural-based brain mass → resection: meningothelial cells forming whorls + psammoma bodies; IHC: EMA+, SSTR2A+, progesterone receptor+; การวินิจฉัยและการ grade';

commit;
