-- ===============================================================
-- UPDATE chunk 3/8: pathology (25 questions)
-- ===============================================================

begin;

update public.mcq_questions
set choices = '[{"label":"A","text":"ไม่ต้อง control"},{"label":"B","text":"IHC Principles + Pitfalls"},{"label":"C","text":"Random Ab"},{"label":"D","text":"No retrieval"},{"label":"E","text":"Skip"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** IHC Principles + Pitfalls: (1) **Concept**: antibody-based detection of specific antigens in tissue — primary Ab → secondary Ab/polymer with enzyme (HRP/AP) → chromogen (DAB brown, AEC red) → visualized in tissue context; (2) **Antigen retrieval** (essential for FFPE — formalin masks epitopes): - **Heat-induced epitope retrieval (HIER)**: most common, citrate buffer pH 6 OR EDTA-Tris pH 9 (high pH); pressure cooker / steamer / microwave; - **Enzymatic** (proteinase K, trypsin) for some antibodies (e.g., kappa/lambda); - Mismatched retrieval common cause of false-negative; (3) **Detection systems**: avidin-biotin (legacy), polymer-based (HRP-conjugated polymer — sensitive, no endogenous biotin issue), tyramide amplification (very sensitive); (4) **Controls (essential)**: - **Positive control**: tissue known to express antigen on same slide or batch — confirms procedure worked; - **Negative control**: tissue lacking antigen or omit primary Ab — confirms specificity; - **Internal control**: cells within patient tissue (e.g., normal duct for ER, blood vessels for vimentin) — best validation; - **Each run** must have controls + documented; (5) **Pitfalls** (interpretation): - **Fixation issues** → false-negative (over/under); - **Edge artifact** — tissue edge stains non-specifically; - **Necrosis** — non-specific staining; - **Endogenous peroxidase** (RBCs, granulocytes) — block; - **Endogenous biotin** (liver, kidney) — block; - **Tonsil/tumor heterogeneity**; - **Antibody cross-reactivity**; (6) **Quantification**: percentage + intensity (e.g., ER, PR, HER2 with H-score, Allred, TPS PD-L1); standardized scoring critical; (7) **Validation**: CLIA-validated against gold standard; CAP accreditation requirements

---

IHC: Ab-Ag detection in tissue. HIER (citrate pH6 / EDTA pH9) essential FFPE. Polymer detection sensitive. Controls (positive/negative/internal) every run. Pitfalls: fixation, edge, endogenous biotin/perox, heterogeneity. Quantification standardized (Allred/TPS).'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'pathology'
  and scenario = 'Resident pathology — ขอเข้าใจหลักการของ immunohistochemistry (IHC) — antigen retrieval + detection systems + controls + interpretation pitfalls';

update public.mcq_questions
set choices = '[{"label":"A","text":"FISH = same as IHC"},{"label":"B","text":"FISH Principles + Applications"},{"label":"C","text":"Same as NGS"},{"label":"D","text":"Useless"},{"label":"E","text":"Random"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** FISH Principles + Applications: (1) **Concept**: fluorescently labeled DNA probes hybridize to specific chromosomal regions in interphase cells (FFPE tissue) or metaphase (cytogenetics) — detects gene amplifications, deletions, translocations/fusions; (2) **Probe types**: - **Locus-specific** (e.g., HER2 amplification — HER2/CEP17 ratio); - **Centromeric** (chromosome enumeration); - **Break-apart** (rearrangement detection — e.g., ALK, ROS1, MYC, IGH — red/green flanking → separation = rearrangement); - **Dual fusion** (specific fusion partners, e.g., BCR-ABL); - **Whole chromosome painting** (metaphase); (3) **Major applications**: - **HER2 amplification** breast/gastric (ratio HER2/CEP17 ≥ 2.0 or HER2 copies ≥ 6.0); - **ALK, ROS1, RET, NTRK** rearrangements lung; - **MYC** translocations lymphoma (Burkitt, double-hit DLBCL); - **EWSR1** Ewing sarcoma, **SS18** synovial sarcoma; - **MDM2** amplification well-differentiated/dedifferentiated liposarcoma; - **1p/19q codeletion** oligodendroglioma; - **Urovysion** urine for urothelial; - **Prenatal/oncology cytogenetics**; (4) **Advantages**: single-cell resolution, works on FFPE, can detect subclones, visual + spatial; (5) **Limitations**: targeted (need to know what to look for), labor-intensive, requires fluorescence microscope, fading; (6) **vs IHC**: IHC = protein, FISH = DNA; complementary — IHC screen + FISH confirm (HER2 2+ → FISH); (7) **vs NGS**: NGS = sequence-level, more comprehensive, lower turnaround, can miss some fusions if intronic; (8) **Quality**: validated probes, signal counting standards (cells counted, scoring rules), inter-observer concordance

---

FISH: fluorescent DNA probes detect amplifications/deletions/translocations on FFPE. HER2/ALK/MYC/1p19q/MDM2/EWSR1 key applications. Break-apart for rearrangements. Single-cell + spatial. Complements IHC + NGS.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'pathology'
  and scenario = 'หลักการของ FISH (fluorescence in situ hybridization) ใน pathology — applications + interpretation + advantages vs limitations เมื่อเทียบกับ IHC และ NGS';

update public.mcq_questions
set choices = '[{"label":"A","text":"NGS = Sanger"},{"label":"B","text":"Clinical NGS Principles"},{"label":"C","text":"No QC"},{"label":"D","text":"Skip"},{"label":"E","text":"Random"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Clinical NGS Principles: (1) **Concept**: massively parallel sequencing — millions of short reads per run vs Sanger one read; (2) **Workflow**: DNA/RNA extraction → library preparation (fragmentation + adapter ligation + barcode) → enrichment (capture or amplicon) → sequencing on platform (Illumina short read, ONT/PacBio long read) → bioinformatics (alignment to reference, variant calling, annotation, filtering) → clinical interpretation + reporting; (3) **Panel types**: - **Targeted hotspot panels** (e.g., 50-gene cancer panel) — fast, deep coverage, limited scope; - **Comprehensive genomic profiling (CGP)** ~ 300-700+ genes — TMB, MSI, signatures (FoundationOne, MSK-IMPACT); - **Whole exome (WES)** — all coding ~ 1.5% genome; - **Whole genome (WGS)** — comprehensive but expensive; - **RNA seq** — fusions, expression, splicing (better fusion detection vs DNA); - **Liquid biopsy** (ctDNA) — non-invasive, monitoring, resistance — limited sensitivity early-stage; (4) **Applications**: - Solid tumor profiling (matched therapy + clinical trials); - Heme malignancies (myeloid + lymphoid panels — AML risk stratification, MDS, MPN); - Germline cancer predisposition (hereditary panels); - Inherited disease (WES diagnostic); - Microbiology (metagenomic); - Transplant; - Pharmacogenomics; (5) **Variant classification**: - **Somatic** (AMP/ASCO/CAP 2017 Tier I-IV — actionable, potential, unknown, benign); - **Germline** (ACMG 5-tier P/LP/VUS/LB/B); - VAF (variant allele frequency) interpretation — germline ~ 50% (het) / 100% (hom); somatic variable; (6) **QC**: depth (≥ 100x typical tumor), uniformity, coverage; validation; CLIA/CAP requirements; (7) **Limitations**: detection of large structural variants challenging (long-read helps); RNA needed for many fusions; tumor purity essential for VAF; turnaround time

---

NGS: massively parallel; library prep → seq → bioinfo → interpretation. Panels (hotspot/CGP/WES/WGS/RNA/ctDNA). Variant tiers — somatic (AMP/ASCO/CAP 2017) + germline (ACMG). Depth + tumor purity essential. RNA needed for fusion detection.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'pathology'
  and scenario = 'หลักการของ next-generation sequencing (NGS) ใน clinical molecular pathology — workflow + applications + tumor + germline + variant interpretation + limitations';

update public.mcq_questions
set choices = '[{"label":"A","text":"Report ก็ได้"},{"label":"B","text":"Pre-analytical Specimen Handling Errors + Mitigation"},{"label":"C","text":"Discard silently"},{"label":"D","text":"Use anyway"},{"label":"E","text":"Refuse case"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Pre-analytical Specimen Handling Errors + Mitigation: (1) **CAP/ASCO Guidelines for breast biomarkers (ER, PR, HER2)**: - **Cold ischemia time ≤ 1 hour** (time from removal to fixation); refrigeration acceptable short delay but documented; - **Fixation time 6-72 hours** in 10% NBF; - **Documented** on requisition + report (cold ischemia, fixation time); (2) **This case violates both**: 3-h cold ischemia + 4-h fixation → invalid for biomarker testing per guidelines; (3) **Consequences**: false-negative ER/PR (loss of antigenicity), false-negative HER2 IHC + invalid FISH, impacts treatment decisions (deny targeted therapy); (4) **Mitigation**: - Document deviation explicitly on report; - Note ''biomarker results may be unreliable due to pre-analytic deviation''; - Recommend repeat sampling if results affect management; - Consider testing surgical specimen if core invalid; - Discuss with treating clinician; (5) **Quality improvement (system level)**: - Specimen transport workflow with time stamps; - Education of OR + transport + lab; - Tracking software for cold ischemia + fixation timestamps; - Periodic audits + feedback; - Root cause analysis; - CAP accreditation requirements monitored; (6) **Other pre-analytical critical issues**: hemolysis (chemistry), clot in EDTA (CBC), wrong tube/anticoagulant, mislabeling (most common — ''never event'' if causes wrong patient treatment), inadequate volume; (7) **Two-identifier rule**: specimens labeled with ≥ 2 patient identifiers; (8) **Specimen rejection criteria** standardized + tracked; (9) **TJC + ISO 15189 + CAP**: pre-analytical phase 60-70% of lab errors — focus area

---

Breast biomarker preanalytics: cold ischemia ≤1h, fixation 6-72h. Deviation → unreliable ER/HER2. Mitigation: document, comment on report, possibly repeat. QI: workflow + tracking + RCA. Pre-analytic = 60-70% lab errors. Two-identifier rule.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'pathology'
  and scenario = 'Lab manager — มี breast biopsy specimen ที่ refrigerated และ formalin fixation เริ่มหลังจาก 3 ชม cold ischemia + ระยะ fixation เพียง 4 ชม ก่อนนำไป processing; ส่ง ER + HER2 — ปัญหา + management';

update public.mcq_questions
set choices = '[{"label":"A","text":"ไม่ทำ"},{"label":"B","text":"Frozen Section Operations"},{"label":"C","text":"Refuse"},{"label":"D","text":"Random sections"},{"label":"E","text":"No QA"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Frozen Section Operations: (1) **Purpose**: intraoperative consultation — diagnosis (benign vs malignant), margin assessment, identification of unknown tissue, evaluation of lymph nodes; guide immediate surgical decisions; (2) **Workflow**: surgeon submits fresh specimen → pathologist examines gross → selects sections → cryostat freezes (-25 to -30°C OCT compound) → microtome sections (5-10 μm) → rapid H&E (or toluidine blue) → microscopic interpretation → communicate to OR; (3) **Standards (CAP)**: - **Turnaround time** target: 20 min per block (single specimen) — track + report; - **Concordance with permanent**: ≥ 97% target; - Documented results, time stamps; (4) **Limitations**: - **Artifacts**: ice crystals (slow freeze), folding, freeze artifact → harder interpretation; - **Some lesions hard frozen**: fatty tissue (lipoma, fatty breast), small foci; - **No IHC** (some specialty IHC possible but routinely none); - **Permanent sections needed for definitive diagnosis** — always note ''pending permanent''; (5) **Common scenarios**: - **Breast margin**: ''cavity shave'' margins assessed; ink + sections; report distance to margin; - **Sentinel lymph node**: per-protocol slicing (2 mm slices), levels examined; cytokeratin IHC on permanents (micromets); - **Brain tumor**: smear preparation often added; - **Thyroid**: limited utility (papillary nuclear features lost in frozen, follicular vs follicular ca needs capsular invasion on permanent); (6) **Quality assurance**: monitor TAT, concordance, deferred rate; periodic case review; (7) **Communication**: clear verbal + written; surgeon repeats back; documented in OR + path system; (8) **Multidisciplinary**: surgeon + pathologist + OR staff collaboration; team-based

---

Frozen section: cryostat-cut H&E for intraop diagnosis/margin/LN. TAT target 20 min/block; concordance ≥97%. Limitations: artifacts, thyroid follicular, no IHC. Always ''pending permanent''. QA + clear communication + documentation essential.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'pathology'
  and scenario = 'Intra-operative frozen section — surgeon ขอ frozen section จาก breast lumpectomy margin + sentinel lymph node 3 nodes; lab manager จัด workflow + turnaround time + accuracy expectations';

update public.mcq_questions
set choices = '[{"label":"A","text":"Email"},{"label":"B","text":"Critical Value Reporting (CAP/CLSI/TJC)"},{"label":"C","text":"No documentation"},{"label":"D","text":"Tell student"},{"label":"E","text":"Skip"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Critical Value Reporting (CAP/CLSI/TJC): (1) **Definition**: laboratory result that requires immediate notification because it may represent life-threatening condition; (2) **Each lab establishes own list** based on clinical input — example panic values: - **CBC**: WBC < 1.0 or > 30; Hb < 6 or > 20; platelet < 20 or > 1000; absolute neutrophil < 0.5; - **Chemistry**: glucose < 40 or > 500; Na < 120 or > 160; K < 2.8 or > 6.2; Ca < 6 or > 13; - **Coagulation**: INR > 5 (anticoag); fibrinogen < 100; - **Microbiology**: positive blood culture, CSF culture, gram stain; - **Toxicology**: acetaminophen toxic level; - **Histopathology**: unexpected critical diagnoses (e.g., mucormycosis); (3) **Process** (closed-loop): - **Confirmation**: verify result (delta check, repeat if quality concern); - **Notification** to **licensed caregiver who can act** — physician, nurse, NP, PA — NOT clerk/student; - **Read-back / repeat-back**: caregiver repeats result back to lab; - **Time-stamped documentation** in LIS: result, who notified, who notified (name + role), time, read-back confirmation; - **Escalation pathway** if unable to reach (chain of command, attending, supervisor, hospitalist); - **Maximum time target** (e.g., < 30 min) per policy; (4) **Quality monitoring**: % critical values reported within target time, missed/delayed events, RCAs for failures; TJC NPSG 02.03.01; (5) **System support**: automated alerts, escalation systems, on-call rosters, pager/secure messaging; (6) **Training + competency**: lab staff + clinicians on process; (7) **Continuous review** of critical value list with clinical input + outcomes

---

Critical value: established list + closed-loop reporting. Confirm → notify licensed actionable provider → read-back → time-stamp documentation → escalation if unreachable. < 30 min target. TJC NPSG 02.03.01. Monitor + RCA for misses.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'pathology'
  and scenario = 'Lab director — มี critical value (panic value) ใน CBC: WBC 0.4 ที่ AM rounds รออยู่ + plt 8; ระบบรายงาน critical values + accountability + กระบวนการ closed-loop communication';

update public.mcq_questions
set choices = '[{"label":"A","text":"Single specialist decides"},{"label":"B","text":"Multidisciplinary Tumor Board (MTB) Integrative Care"},{"label":"C","text":"No discussion"},{"label":"D","text":"Skip"},{"label":"E","text":"Refuse"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Multidisciplinary Tumor Board (MTB) Integrative Care: (1) **Composition**: pathology + radiology + medical oncology + surgical oncology (thoracic) + radiation oncology + pulmonology + palliative + nursing + social work + research/clinical trials + pharmacy + nutrition + supportive care + patient advocacy/navigator; (2) **Case preparation**: structured templates — clinical hx, imaging review, pathology (histology + IHC + molecular complete profile), staging summary, prior treatment, performance status, patient priorities; (3) **Standard outputs**: consensus diagnosis, stage, treatment recommendation with rationale, clinical trial options, supportive care; documented in chart for team + patient; (4) **Modern features**: - **Molecular tumor board**: dedicated team for complex genomic findings — interpret VUS, off-label targeted therapy, trial matching; - **Virtual MTB**: telemedicine extends to community partners; - **Patient navigator** ensures plan execution + access; - **Survivorship + late effects** planning; (5) **Quality + outcomes**: MTB attendance documented; track concordance with NCCN/guidelines, time to treatment, clinical trial enrollment, equity in access, patient experience; (6) **Equity considerations**: language services, cultural competence, transportation, financial counseling, community outreach; (7) **Clinical trial integration**: matched targeted trials (NTRK, RET, MET, HER2), IO trials, neoadjuvant trials; (8) **Patient + family included** when appropriate; (9) **Documentation** in EHR + shared with primary care; (10) **Continuous improvement**: outcomes review, case audits, education; (11) **Integrative + supportive**: smoking cessation, nutrition, pulmonary rehab, mental health, palliative early-integration (Temel)

---

MTB integrative care: multidisciplinary team-based decisions. Composition wide. Modern: molecular tumor board, virtual MTB, navigator. QI tracking. Trial integration. Equity + supportive + palliative integration. Patient-centered.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'pathology'
  and scenario = 'ผู้ป่วยอายุ 55 ปี — newly diagnosed lung adenocarcinoma — case discussion ที่ multidisciplinary tumor board: pathology + biomarkers + imaging + treatment planning + clinical trials + multidisciplinary integrative care';

update public.mcq_questions
set choices = '[{"label":"A","text":"Ignore VUS"},{"label":"B","text":"Molecular Tumor Board (MTB) Integrative"},{"label":"C","text":"Skip board"},{"label":"D","text":"Refuse"},{"label":"E","text":"Single specialty"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Molecular Tumor Board (MTB) Integrative: (1) **Purpose**: interpret complex genomic results, match to targeted therapies/trials, classify variants, recommend additional testing; bridge between pathology + treating team; (2) **Composition**: molecular pathologist + genomic counselor + medical oncology (rare cancers + specific tumor types) + clinical pharmacist + bioinformatics + research + pathology + radiology + germline genetics + ethics consult (selected); (3) **Variant interpretation**: - **Tier I** (strong clinical significance) — FDA-approved drug; - **Tier II** (potential) — off-label or trial evidence; - **Tier III** (VUS) — additional curation; - **Tier IV** (benign/likely benign); - Functional studies, public databases (ClinVar, COSMIC, OncoKB, CIViC), literature; (4) **Germline implications**: distinguish somatic vs germline (paired testing or VAF); recommend genetic counseling + family testing; secondary findings (ACMG-recommended actionable list); (5) **Clinical trial matching**: basket/umbrella trials, MATCH/NCI-MATCH, ASCO TAPUR, industry trials; navigator-supported enrollment; (6) **Off-label + access**: insurance prior auth + appeals; patient assistance programs; compassionate use; expanded access; (7) **Equity**: rare tumor + biomarker access barriers; financial toxicity; (8) **Patient engagement**: shared decision-making + understanding of evidence quality; informed consent; (9) **Documentation + follow-up**: structured EHR templates; outcome tracking + database; (10) **Continuous learning**: update knowledge with rapidly evolving evidence; (11) **Integration**: molecular + clinical + imaging + multidisciplinary main tumor board; comprehensive treatment plan including palliative + supportive

---

Molecular tumor board: dedicated team for genomic interpretation + trial matching. Variant tiers I-IV (AMP/ASCO/CAP). Germline implications + counseling. Trial matching (MATCH, TAPUR). Access + equity considerations. Integrated with main MTB.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'pathology'
  and scenario = 'Patient with rare cancer + VUS (variant of uncertain significance) ใน NGS — molecular tumor board for interpretation + integrative care + clinical trial matching';

update public.mcq_questions
set choices = '[{"label":"A","text":"No autopsy"},{"label":"B","text":"Hospital Autopsy Integrative Value"},{"label":"C","text":"Skip"},{"label":"D","text":"Single specialty"},{"label":"E","text":"Refuse"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Hospital Autopsy Integrative Value: (1) **Purposes**: - **Diagnostic accuracy**: identify missed/incorrect diagnoses (~ 10-30% major discrepancies historically — even in modern era ~ 8-25%); - **Cause of death determination**; - **Quality + safety**: M&M, root cause analysis input, complications identified; - **Education**: medical students, residents, fellows, attendings learning; - **Research**: tissue collection (with consent), disease characterization; - **Family closure**: explanation, grief processing, hereditary implications; - **Public health**: surveillance of disease, COVID/emerging pathogens (e.g., COVID autopsy programs key to understanding disease); (2) **Process**: - **Consent**: from legal next of kin; specifics (full autopsy, restricted, organs retention); medical examiner cases (homicide, suicide, accident, suspicious, unattended, in-custody) → separate jurisdiction, no family consent needed; - **External exam** + photo documentation; - **Internal exam**: thoracic, abdominal, cranial as consented; - **Gross + histology**; - **Special**: microbiology, toxicology, genetic, molecular as indicated; - **Provisional anatomical diagnosis** within ~ 24 hours; - **Final autopsy report** ~ 6-8 weeks with histology + ancillary; (3) **Communication with family**: empathetic, clear, structured meeting; bereavement support; (4) **Communication with clinical team**: M&M conference, learning; (5) **Quality**: track autopsy rate, discrepancies (Goldman class I-IV), reporting timeliness; (6) **Multidisciplinary**: pathology + clinical service + bereavement + chaplaincy + risk management + legal as needed; (7) **Modern decline + revival**: rate dropped historically but renewed importance with COVID + complex deaths + AI; consent process improvement essential

---

Hospital autopsy: diagnostic accuracy + quality + education + family closure + research + public health. Goldman class discrepancies. Consent + ME jurisdiction. Provisional ~24h, final ~6-8w. Communication with family + clinical team. COVID renewed importance.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'pathology'
  and scenario = 'Hospital autopsy program — sudden unexpected adult death in hospital + family consent given; pathology + multidisciplinary autopsy integrative role in quality + education + family closure';

update public.mcq_questions
set choices = '[{"label":"A","text":"Reactive hyperplasia"},{"label":"B","text":"Diffuse Large B-cell Lymphoma (DLBCL)"},{"label":"C","text":"CLL"},{"label":"D","text":"Hodgkin"},{"label":"E","text":"Refuse"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Diffuse Large B-cell Lymphoma (DLBCL): (1) **Histology**: diffuse effacement by sheets of large transformed B-cells (centroblasts, immunoblasts); ≥ 2 × normal lymphocyte size; high mitoses + apoptosis; (2) **IHC** (mandatory panel): CD20, CD79a, PAX5 (B-cell); BCL6, CD10, MUM1 (cell-of-origin); BCL2, MYC (double-expressor); Ki-67; (3) **Hans algorithm (cell of origin from IHC)**: GCB (germinal-center B — CD10+ OR (CD10- BCL6+ MUM1-)) vs **non-GCB** (rest); GCB better prognosis; (4) **Molecular subtypes** (gene-expression): GCB, ABC, unclassified; new genomic clusters (LymphGen — MCD, BN2, N1, EZB, ST2, A53); (5) **Essential FISH** (rule out high-grade): **MYC** + **BCL2** + **BCL6** rearrangements → if MYC + (BCL2 and/or BCL6) = **''double-hit'' / ''triple-hit'' high-grade B-cell lymphoma (HGBL)** — aggressive, separate WHO entity; (6) **Double expressor** (BCL2 + MYC by IHC, no rearrangement) = worse prognosis but not HGBL; (7) **Staging**: PET-CT (Lugano 2014 criteria), BM biopsy (selective — replaced by PET in many), CNS risk assessment (CNS-IPI); (8) **Treatment**: - **R-CHOP × 6** standard; - **Pola-R-CHP** (polatuzumab vedotin replacing vincristine — POLARIX) ≥ IPI 2 — new standard for many; - HGBL: DA-EPOCH-R; - CNS prophylaxis high-risk (CNS-IPI ≥ 4, testicular, breast, double-hit, kidney/adrenal); - Relapsed/refractory: **CAR-T** (axi-cel, liso-cel — ZUMA-7, TRANSFORM moved CAR-T to 2nd line) > auto-HCT; - Other: tafasitamab + lenalidomide, lonca-T, glofitamab/epcoritamab (bispecific), pola; (9) **IPI / NCCN-IPI** risk; (10) **PMBCL** distinct entity; (11) **Cures > 60% with R-CHOP**

---

DLBCL: large B-cell sheets; Hans algorithm GCB vs non-GCB; FISH for MYC/BCL2/BCL6 to rule out HGBL. R-CHOP standard; Pola-R-CHP new (POLARIX). CAR-T 2nd line (ZUMA-7). Bispecifics + ADCs for R/R. Cure > 60%.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'pathology'
  and scenario = 'ผู้ป่วยอายุ 65 ปี — lymph node biopsy: diffuse sheet-like proliferation of large lymphoid cells with vesicular nuclei + prominent nucleoli, high mitoses; IHC: CD20+, CD79a+, BCL6+, MUM1+, CD10-, Ki-67 ~80%, MYC 30%, BCL2 50%; FISH: no MYC/BCL2/BCL6 rearrangements; การวินิจฉัยและการรักษา';

update public.mcq_questions
set choices = '[{"label":"A","text":"Reactive follicular hyperplasia"},{"label":"B","text":"Follicular Lymphoma (FL)"},{"label":"C","text":"MCL"},{"label":"D","text":"Burkitt"},{"label":"E","text":"Hodgkin"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Follicular Lymphoma (FL): (1) **Histology**: nodular/follicular pattern with monotonous small cleaved (centrocytes) + variable large (centroblasts) cells; loss of polarization + tingible-body macrophages; (2) **IHC**: CD20+, CD10+, BCL6+, **BCL2+ within follicles (aberrant — vs reactive germinal centers BCL2 negative)**, CD5-, CD23-; Ki-67 typically low in low-grade; (3) **Cytogenetics**: **t(14;18)(q32;q21) IGH/BCL2** in ~ 85% — leads to BCL2 overexpression + apoptosis evasion; (4) **Grading (WHO)**: based on centroblast count per HPF — grade 1-2 (0-15), grade 3A (> 15 but with centrocytes), 3B (sheets of centroblasts — treated like DLBCL); FL grading recently simplified; (5) **Variants/related**: pediatric-type FL (different biology), duodenal-type FL (indolent), in situ follicular B-cell neoplasm; FL with predominantly diffuse pattern, FL with unusual cytologic features; (6) **Staging**: PET-CT, BM biopsy (~ 70% involvement at diagnosis); (7) **FLIPI/FLIPI2** prognostic; (8) **Treatment**: - **Asymptomatic low burden**: watch + wait (no survival benefit from immediate Tx in low-grade); - **Symptomatic/high tumor burden (GELF criteria)**: bendamustine + rituximab (BR) OR R-CHOP OR R² (rituximab + lenalidomide — AUGMENT relapsed); rituximab maintenance debated; obinutuzumab + chemo alternative; - **Localized stage I**: RT alone potentially curative; - **Transformation to DLBCL** ~ 2-3%/yr — re-biopsy if discordant behavior; - **Relapsed/refractory**: PI3K inhibitors (limited), tazemetostat (EZH2 mutant), CAR-T (axi-cel — ZUMA-5), bispecifics (mosunetuzumab); (9) **Indolent but currently incurable** with chemo (except localized)

---

FL: follicular pattern, CD10+/BCL6+/BCL2+ (aberrant in follicles); t(14;18) IGH/BCL2 ~85%. Grading by centroblast count. Asymptomatic → W&W; symptomatic → BR/R-CHOP/R². Tazemetostat (EZH2), CAR-T, bispecifics for R/R. Incurable but indolent.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'pathology'
  and scenario = 'ผู้ป่วยอายุ 55 ปี — generalized lymphadenopathy + slow growing → excisional biopsy: nodular/follicular pattern; IHC: CD20+, CD10+, BCL6+, BCL2+ (aberrant in follicles), CD5-, CD23-, Ki-67 low (~10%); FISH: t(14;18) IGH/BCL2 positive; grade 1-2';

update public.mcq_questions
set choices = '[{"label":"A","text":"CLL"},{"label":"B","text":"Mantle Cell Lymphoma (MCL)"},{"label":"C","text":"FL"},{"label":"D","text":"Hodgkin"},{"label":"E","text":"Reactive"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Mantle Cell Lymphoma (MCL): (1) **Histology**: monotonous medium-sized cells with irregular cleaved nuclei; mantle zone, nodular, diffuse, or blastoid (aggressive variant) patterns; pleomorphic variant; (2) **IHC**: CD20+, CD5+, **CD23 negative** (vs CLL CD23+), **cyclin D1+ (nuclear)**, SOX11+ (specific; positive even in CCND1-negative MCL), CD10-, BCL6-; (3) **Cytogenetics**: **t(11;14)(q13;q32) CCND1/IGH** — pathognomonic, dysregulates cyclin D1 → cell cycle drive; (4) **Variants**: - **Classic** — node-based, aggressive; - **Leukemic non-nodal** (indolent, SOX11- subset) — watch + wait; - **Blastoid + pleomorphic** — aggressive; - **In situ mantle cell neoplasia**; (5) **Molecular**: TP53 mutation (poor prognosis — affects treatment selection — avoid intensive chemo); CDKN2A; ATM; NOTCH1/2; (6) **MIPI** prognostic; Ki-67 important (> 30% adverse); (7) **Staging**: PET-CT, BM biopsy, often advanced stage at diagnosis; GI involvement common (lymphomatous polyposis); (8) **Treatment**: - **Indolent (non-nodal, SOX11-)**: watch + wait; - **Younger fit**: intensive induction (R-DHAP or R-CHOP/R-DHAP alternating + cytarabine) + auto-HCT consolidation; rituximab maintenance; - **Older/less fit**: BR or R-CHOP + rituximab maintenance; - **TP53 mutated**: standard chemo poor — consider novel/trials (ibrutinib + venetoclax, BTKi-based, CAR-T); - **Relapsed**: BTK inhibitors (ibrutinib, acalabrutinib, zanubrutinib, pirtobrutinib non-covalent); venetoclax; lenalidomide; **CAR-T (brexucabtagene — ZUMA-2)** for R/R; bispecifics emerging

---

MCL: CD5+/CD23-/cyclin D1+/SOX11+; t(11;14) CCND1/IGH pathognomonic. Variants: classic, leukemic non-nodal (indolent), blastoid (aggressive). TP53 mutated worse; novel/CAR-T. BTKi (incl. pirtobrutinib) + venetoclax for R/R. ZUMA-2 CAR-T.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'pathology'
  and scenario = 'ผู้ป่วยชายอายุ 68 ปี — lymphadenopathy + splenomegaly + B symptoms; lymph node biopsy: monotonous medium-sized lymphoid cells with irregular nuclei; IHC: CD20+, CD5+, CD23-, **cyclin D1+**, SOX11+, CD10-; FISH: t(11;14) CCND1/IGH; การวินิจฉัย';

update public.mcq_questions
set choices = '[{"label":"A","text":"Hodgkin"},{"label":"B","text":"BCL2 negative or weak"},{"label":"C","text":"ALL"},{"label":"D","text":"Neuroblastoma"},{"label":"E","text":"FL"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Burkitt Lymphoma: (1) **Histology**: monomorphic medium-sized cells with basophilic cytoplasm + lipid vacuoles; ''starry sky'' pattern from tingible body macrophages engulfing apoptotic cells (extremely high cell turnover); high mitoses + apoptosis; (2) **IHC**: CD20+, CD10+, BCL6+, **BCL2 negative or weak** (essential — distinguish from DLBCL/HGBL), **Ki-67 ~100%**, MYC + (translocation product); TdT negative; (3) **Cytogenetics**: **MYC rearrangement** — t(8;14)(q24;q32) IGH/MYC (most common); variants t(2;8) IGK/MYC, t(8;22) IGL/MYC; (4) **Variants (WHO)**: - Endemic (African) — EBV-associated, mandibular/abdominal; - Sporadic — abdominal, head/neck; - Immunodeficiency-associated (HIV, post-transplant); - **Burkitt-like lymphoma with 11q aberration** (newer entity, no MYC rearr, different biology); (5) **HGBL-NOS** + **HGBL with MYC + BCL2 +/- BCL6 (double/triple-hit)** distinct from Burkitt — important differential; (6) **Highly aggressive but curable** with intensive multi-agent chemo; (7) **Treatment**: - **Tumor lysis prophylaxis essential** (rasburicase, aggressive hydration, monitor electrolytes) — TLS often present at diagnosis; - **DA-EPOCH-R** with CNS prophylaxis (acceptable + tolerable in adults — Roschewski); - **CODOX-M/IVAC** (Magrath regimen) — historical/pediatric; - **R-Hyper-CVAD** alternative; - **CNS prophylaxis essential** (IT MTX/cytarabine ± high-dose systemic MTX); - Pediatric ANHL1131 regimen; (8) **Outcomes**: cure > 90% pediatric/young + low-stage, > 70% adult advanced

---

Burkitt: ''starry sky'', CD20+/CD10+/BCL6+/BCL2-, Ki-67 ~100%, MYC translocation (t(8;14)). Distinct from HGBL double-hit (BCL2+). TLS prophylaxis essential. DA-EPOCH-R or CODOX-M/IVAC; CNS prophylaxis. Curable.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'pathology'
  and scenario = 'ผู้ป่วยชายอายุ 12 ปี — abdominal mass + tumor lysis on presentation; biopsy: monomorphic medium-sized cells with basophilic cytoplasm + vacuoles + ''starry sky'' (tingible body macrophages); IHC: CD20+, CD10+, BCL6+, BCL2-, Ki-67 ~100%, MYC+; FISH: t(8;14) MYC/IGH';

update public.mcq_questions
set choices = '[{"label":"A","text":"Reactive"},{"label":"B","text":"Classical Hodgkin Lymphoma (CHL)"},{"label":"C","text":"DLBCL"},{"label":"D","text":"TB"},{"label":"E","text":"CLL"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Classical Hodgkin Lymphoma (CHL): (1) **Histology**: Reed-Sternberg (RS) cells — large, multinucleated/bilobed with prominent eosinophilic ''owl-eye'' nucleoli; mononuclear variants (Hodgkin cells); lacunar variant (nodular sclerosis); inflammatory background — small lymphocytes, eosinophils, plasma cells, histiocytes, fibrosis; (2) **Subtypes (CHL)**: - **Nodular sclerosis** (NSCHL) — most common in West, young adults, mediastinum, lacunar RS cells, fibrous bands; - **Mixed cellularity** (MCCHL) — older, EBV-associated; - **Lymphocyte-rich** (LRCHL); - **Lymphocyte-depleted** (LDCHL) — rarest, aggressive, HIV-associated; (3) **IHC (CHL)**: **CD30+ (strong)**, **CD15+** (~ 75%), PAX5 dim+, MUM1+, **CD20 usually negative or weak/heterogeneous**, **CD45 negative**, BCL6-, OCT2/BOB1 weak/absent (B-cell program down-regulated); EBV (EBER ISH) variable; (4) **Nodular Lymphocyte Predominant Hodgkin/NLP B-cell Lymphoma** (NLPHL — reclassified in WHO HAEM5 as NLPBL) — distinct: LP (''popcorn'') cells, CD20+, CD45+, CD15-, CD30-, BCL6+ — treated more like indolent B-cell lymphoma; (5) **Staging**: PET-CT (Lugano) — replaces routine BM biopsy in CHL; (6) **Treatment**: - **Early stage favorable**: ABVD × 2 + ISRT (RAPID, H10) or ABVD × 4 alone (RATHL — PET-adapted); - **Early unfavorable**: ABVD × 4 + RT; - **Advanced**: ABVD × 6 (RATHL PET-adapted reducing bleo) OR **A+AVD (brentuximab vedotin + AVD)** (ECHELON-1 — A+AVD superior + PFS); recent ABVD/A+AVD + nivolumab data; - **Relapsed**: salvage + auto-HCT; brentuximab + nivolumab/pembrolizumab; allo-HCT for select; (7) **Cures > 80%**

---

Classical Hodgkin: RS cells (CD30+/CD15+/CD20-/CD45-), ''owl-eye'' nucleoli + inflammatory background. Subtypes NS/MC/LR/LD. NLPHL (NLPBL) distinct (CD20+). PET-adapted ABVD or A+AVD (ECHELON-1). Brentuximab + IO for R/R. Cure > 80%.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'pathology'
  and scenario = 'ผู้ป่วยอายุ 25 ปี — cervical lymphadenopathy + B symptoms → biopsy: scattered large cells with bilobed nuclei + prominent eosinophilic nucleoli (''owl eyes'') in background of small lymphocytes + eosinophils + plasma cells + fibrosis; IHC: CD30+, CD15+, PAX5 dim+, CD20-, CD45-';

update public.mcq_questions
set choices = '[{"label":"A","text":"MGUS"},{"label":"B","text":"Multiple Myeloma (MM)"},{"label":"C","text":"Refuse"},{"label":"D","text":"Hospice"},{"label":"E","text":"Lymphoma"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Multiple Myeloma (MM): (1) **Diagnostic criteria (IMWG 2014, updated)**: clonal BM plasma cells ≥ 10% (or biopsy-proven plasmacytoma) + one of CRAB (hypercalcemia, renal insufficiency, anemia, bone lesions) OR myeloma-defining events (clonal BM PC ≥ 60%, FLC ratio ≥ 100, > 1 focal MRI lesion ≥ 5 mm) — SLiM-CRAB; (2) **vs MGUS** (M-protein < 3, BM PC < 10%, no CRAB) and **smoldering MM** (intermediate, no CRAB); (3) **Workup**: SPEP + UPEP + immunofixation, serum free light chains, IgG/A/M quantitative, beta-2 microglobulin, albumin (R-ISS); skeletal survey (low-dose whole-body CT or MRI/PET preferred — more sensitive than plain films); BM biopsy + aspirate with FISH; (4) **FISH/cytogenetics (essential — risk stratification)**: - **High risk**: t(4;14), t(14;16), t(14;20), del(17p)/TP53, gain/amp 1q21, +/- t(14;20); - **Standard**: t(11;14), hyperdiploidy; (5) **R-ISS / R2-ISS**: stage I-III using albumin + β2m + LDH + cytogenetics; (6) **Treatment** (transplant-eligible — newly diagnosed): - **Quadruplet induction**: **Dara-VRd (daratumumab + bortezomib + lenalidomide + dexamethasone)** (PERSEUS, GRIFFIN) — new standard; alt isa-KRd; - Auto-HCT consolidation; - Maintenance lenalidomide; daratumumab maintenance trials; - **Transplant-ineligible**: Dara-Rd or Dara-VRd; (7) **Relapsed/refractory**: - **CAR-T (BCMA — ide-cel KarMMa, cilta-cel CARTITUDE)** — earlier lines now (CARTITUDE-4, KarMMa-3); - Bispecifics: **teclistamab, elranatamab (BCMA), talquetamab (GPRC5D), cevostamab (FcRH5)**; - Other PI (carfilzomib, ixazomib), IMiD (pomalidomide), anti-CD38 (isatuximab), selinexor, venetoclax (t(11;14)); (8) **Supportive**: bisphosphonate/denosumab, infection prophylaxis, anticoagulation IMiD

---

MM: SLiM-CRAB criteria; SPEP/SFLC/IFE + BM + FISH. High-risk t(4;14)/del(17p)/t(14;16)/+1q. Quadruplet Dara-VRd + auto-HCT + maintenance new standard. R/R: BCMA CAR-T (ide-cel/cilta-cel), bispecifics (teclistamab, talquetamab). Supportive bisphos.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'pathology'
  and scenario = 'ผู้ป่วยอายุ 70 ปี — fatigue + bone pain + Cr 2.3 + Hb 8.5 + Ca 11.5 + serum protein electrophoresis: M-spike 4.5 g/dL IgG kappa; BM biopsy: 60% plasma cells, sheets + atypical; FISH: t(4;14) FGFR3/MMSET, del(17p); การวินิจฉัยและการรักษา';

update public.mcq_questions
set choices = '[{"label":"A","text":"Thalassemia"},{"label":"B","text":"Iron Deficiency Anemia (IDA) — Pathology + Workup"},{"label":"C","text":"Sickle cell"},{"label":"D","text":"G6PD"},{"label":"E","text":"AIHA"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Iron Deficiency Anemia (IDA) — Pathology + Workup: (1) **Pattern**: microcytic (MCV < 80) + hypochromic (MCH ↓) + elevated RDW (heterogeneous); reticulocyte count low; (2) **Iron studies**: **ferritin LOW (most specific — < 15-30 ng/mL = iron deficient; < 100 in chronic disease + ''iron deficient'')**, serum Fe low, TIBC high (transferrin produced to compensate), transferrin saturation < 16%, sTfR elevated; (3) **Smear**: microcytic + hypochromic + anisocytosis + poikilocytosis (pencil/cigar cells, target cells); (4) **Differential of microcytic anemia (mnemonic TAILS)**: Thalassemia, Anemia of chronic disease, Iron deficiency, Lead poisoning, Sideroblastic; (5) **vs Thalassemia**: thal — MCV very low for Hb level, RDW NORMAL, normal/elevated Fe + ferritin, basophilic stippling, target cells; Hb electrophoresis abnormal (Hb F, A2); (6) **vs ACD**: ACD — ferritin normal/high, Fe low, TIBC LOW, hepcidin high (iron sequestration); (7) **Cause investigation essential** — IDA = bleeding until proven otherwise: - Menstrual loss; - GI bleed (occult — workup EGD + colonoscopy in adult men + postmenopausal women OR persistent IDA); - Pregnancy + lactation; - Malabsorption (celiac, atrophic gastritis, post-bariatric); - Diet (rare in developed countries except infants); - H. pylori; (8) **Treatment**: - Oral iron — ferrous sulfate 325 mg every other day (better absorption than daily — Stoffel data) until ferritin > 100 + 3-6 mo more for stores; - IV iron (ferric carboxymaltose, iron sucrose, ferumoxytol) — intolerance, severe deficit, IBD, CKD, pregnancy 2nd-3rd tri, post-bariatric, ongoing loss; - Transfusion only severe symptomatic; (9) **Follow-up**: Hb 4 wk + ferritin 3 mo

---

IDA: microcytic hypochromic + high RDW + low ferritin + low Fe + high TIBC + low sat. vs thal (normal RDW, normal Fe), ACD (low TIBC). Mandatory cause workup (GI in adults). Oral Fe alt-day (Stoffel); IV Fe selected. Monitor ferritin to replete stores.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'pathology'
  and scenario = 'ผู้ป่วยหญิงอายุ 35 ปี — fatigue + heavy menses; CBC: Hb 8.2, MCV 68, MCH 22, RDW elevated; serum ferritin < 10, Fe low, TIBC high, transferrin saturation 5%; การวินิจฉัยและการรักษา';

update public.mcq_questions
set choices = '[{"label":"A","text":"Iron deficiency"},{"label":"B","text":"Vitamin B12 Deficiency Anemia — Pathology + Workup"},{"label":"C","text":"MDS"},{"label":"D","text":"Aplastic anemia"},{"label":"E","text":"Refuse"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Vitamin B12 Deficiency Anemia — Pathology + Workup: (1) **Pattern**: macrocytic (MCV > 100), megaloblastic (oval macrocytes + hypersegmented neutrophils ≥ 5 lobes + 5%); pancytopenia possible severe cases; (2) **Megaloblastic = impaired DNA synthesis** — folate or B12 deficiency → ineffective erythropoiesis → high LDH + indirect bili (intramedullary hemolysis); (3) **B12 vs folate**: serum B12 + folate; **MMA (methylmalonic acid) elevated only in B12 def** (B12 cofactor for methylmalonyl-CoA mutase); homocysteine elevated in both; (4) **Causes B12 def**: - **Pernicious anemia** (autoimmune anti-IF, anti-parietal cell — atrophic gastritis) — most common adult; check anti-IF Ab (specific) + anti-parietal (sensitive); - **Dietary** (vegan, infants of vegan mothers); - **Malabsorption**: post-gastrectomy/bariatric, ileal resection/Crohn''s, pancreatic insufficiency, fish tapeworm (rare), bacterial overgrowth; - **PPI/H2RA chronic use**, **metformin** (mild); - **Inherited**: TC-II deficiency, IF deficiency (juvenile); (5) **Neurologic features** (B12 specific — folate doesn''t cause): subacute combined degeneration (posterior + lateral columns), peripheral neuropathy, paresthesias, ataxia, dementia, psych symptoms — can occur **without anemia** — neuro irreversible if untreated long; (6) **Treatment**: - Pernicious anemia or malabsorption: IM cyanocobalamin/hydroxocobalamin 1000 μg daily × 1 wk → weekly × 1 mo → monthly lifelong; high-dose oral 1000-2000 μg/d acceptable; - Dietary: oral; - Initial replenishment may unmask hypokalemia (sudden cell production); - **Don''t give folate alone if B12 deficient** — corrects anemia but neuro worsens; (7) **Investigate underlying** + monitor; (8) **Folate deficiency**: alcoholism, malabsorption, pregnancy, methotrexate, phenytoin, dialysis

---

B12 deficiency: macrocytic + megaloblastic (oval macros + hyperseg neutros); MMA + homocysteine elevated (B12 specific MMA). Pernicious anemia main cause adult. Neuro features irreversible if delayed. Treat IM/high-dose oral; don''t give folate alone if B12 low.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'pathology'
  and scenario = 'ผู้ป่วยอายุ 75 ปี vegan — Hb 9.0, MCV 115 (macrocytic), oval macrocytes + hypersegmented neutrophils, LDH high + indirect bili high, B12 100 (low), homocysteine + MMA elevated; การวินิจฉัยและการ workup + Tx';

update public.mcq_questions
set choices = '[{"label":"A","text":"Iron deficiency"},{"label":"B","text":"Sickle Cell Disease (HbSS) — Pathology + Management"},{"label":"C","text":"Refuse"},{"label":"D","text":"Skip"},{"label":"E","text":"Same as trait"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Sickle Cell Disease (HbSS) — Pathology + Management: (1) **Pathophysiology**: point mutation HBB gene (Glu6Val) → HbS polymerizes in deoxygenated state → sickle RBCs → vaso-occlusion + chronic hemolysis + endothelial dysfunction + chronic inflammation; (2) **Smear**: sickle cells, target cells, Howell-Jolly bodies (functional asplenia), nucleated RBCs, polychromasia (reticulocytosis); (3) **Hb electrophoresis**: HbSS (homozygous), HbSC (compound heterozygous), HbS/β-thal; sickle cell trait (HbAS — usually asymptomatic, rare hypoxic complications); (4) **Newborn screening** universal (HbF predominant → screen with HPLC); (5) **Acute complications**: - **Vaso-occlusive crisis (VOC)**: pain — opioid + hydration + warmth; - **Acute chest syndrome (ACS)** — leading cause of mortality: hypoxia + infiltrate + chest pain → exchange transfusion + ABX (incl atypical) + bronchodilator + incentive spirometry; - **Splenic sequestration** (children); - **Aplastic crisis** (parvovirus B19); - **Stroke** — TCD screen children + transfuse if elevated velocity; - **Priapism**; - **Sepsis** (encapsulated organisms — functional asplenia → daily prophylactic PCN < 5 yo, full immunizations incl pneumo, Hib, meningo); (6) **Chronic**: chronic hemolytic anemia, gallstones, pulmonary HTN, renal disease, retinopathy, leg ulcers, avascular necrosis, growth failure, mental health; (7) **Disease-modifying therapy**: - **Hydroxyurea** (induces HbF) — foundation; - **L-glutamine** (Endari); - **Crizanlizumab** (anti-P-selectin) — re-evaluated; - **Voxelotor** (HbS polymerization inhibitor) — withdrawn 2024 globally due to mortality signal; - **Chronic transfusion** (stroke prevention/secondary, recurrent ACS); - **Curative**: **HLA-matched allo-HCT** (children + selected adults); **gene therapy** — Lyfgenia (lovotibeglogene autotemcel) + Casgevy (exa-cel — CRISPR BCL11A — first FDA-approved CRISPR therapy 2023); (8) **Multidisciplinary lifelong care**

---

SCD: sickle RBCs + Howell-Jolly + Hb S on electrophoresis. VOC + ACS major acute. Stroke (TCD screen), sepsis (prophylactic PCN, vaccines). Hydroxyurea foundation; chronic txn for select; allo-HCT + gene therapy (Casgevy CRISPR, Lyfgenia) curative. Voxelotor withdrawn.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'pathology'
  and scenario = 'ผู้ป่วยอายุ 25 ปี African descent — peripheral smear: sickle-shaped RBCs + Howell-Jolly bodies + target cells; Hb electrophoresis: HbS 88%, HbF 8%, HbA2 3.5%, HbA 0%; current VOC + acute chest syndrome; การวินิจฉัยและการรักษา comprehensive';

update public.mcq_questions
set choices = '[{"label":"A","text":"IDA"},{"label":"B","text":"Thalassemia (Compound) — Pathology + Management"},{"label":"C","text":"AIHA"},{"label":"D","text":"G6PD"},{"label":"E","text":"Refuse"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Thalassemia (Compound) — Pathology + Management: (1) **Background — common in Southeast Asia + Mediterranean + Africa**; (2) **α-thalassemia (HBA1/HBA2 deletions)**: - Silent carrier (-α/αα); - α-thal trait (--/αα or -α/-α) — microcytic + mild; - **HbH disease** (--/-α) — 3 α genes deleted → HbH (β4 tetramers) — moderate-severe; - **Hb Bart''s hydrops** (--/--) — incompatible with life (without intrauterine intervention); (3) **β-thalassemia (HBB mutations)**: - β-thal minor (heterozygous) — microcytic + mild; - β-thal intermedia — transfusion-independent or intermittent; - **β-thal major (Cooley''s anemia)** — homozygous null β-globin → severe; transfusion-dependent from infancy; (4) **β-thal/HbE** (compound — common Thailand/Cambodia) — variable severity from intermedia → major; (5) **Smear**: severe microcytic + hypochromic + target cells + nucleated RBCs + tear drops + basophilic stippling; (6) **Hb typing (HPLC)**: elevated HbA2 (β-thal trait/minor), HbF (β-thal major/intermedia, HbE), HbE peak, HbH peak (HbH disease), Bart''s (newborn); (7) **Iron studies**: normal/elevated Fe + ferritin (vs IDA which Fe + ferritin low); (8) **Complications**: ineffective erythropoiesis → marrow expansion (skull bossing, chipmunk facies), extramedullary hematopoiesis, hypersplenism; iron overload from transfusions + GI absorption — endocrine + cardiac + liver dysfunction; (9) **Treatment**: - **Transfusion** to suppress endogenous erythropoiesis (target Hb 9-10 pre-tx); - **Iron chelation** — deferoxamine SC, deferasirox PO, deferiprone PO — based on ferritin + MRI T2* (cardiac + liver iron); - **Splenectomy** for hypersplenism (vaccines + prophylactic ABX); - **Luspatercept** (β-thal — BELIEVE trial); - **Curative**: allo-HCT (children matched donor); **gene therapy** Casgevy + Zynteglo (betibeglogene); (10) **Prenatal screening + counseling** essential — Thailand national policy

---

Thalassemia: severe microcytic + target/teardrop + nRBCs; Hb typing diagnostic; normal/high Fe+ferritin (vs IDA). β-thal major Cooley''s, β-thal/HbE common Thai. Tx: transfusion + chelation + luspatercept; allo-HCT + gene therapy (Zynteglo, Casgevy) curative. Prenatal screening Thai policy.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'pathology'
  and scenario = 'ผู้ป่วยเด็กไทยอายุ 6 ปี — pallor + jaundice + splenomegaly; CBC: Hb 6, MCV 60, MCH 18; smear: severe microcytic + target cells + tear drops + nucleated RBCs; Hb typing: HbE 25%, HbF 60%, HbA2 5%, HbA 0%, HbH small amount; molecular: β-thal mutation + α-thal deletion';

update public.mcq_questions
set choices = '[{"label":"A","text":"Iron deficiency"},{"label":"B","text":"Autoimmune Hemolytic Anemia (AIHA)"},{"label":"C","text":"Refuse"},{"label":"D","text":"Thrombosis"},{"label":"E","text":"MDS"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Autoimmune Hemolytic Anemia (AIHA): (1) **Hemolysis markers**: anemia + reticulocytosis (compensatory) + LDH up + indirect bili up + haptoglobin low + urine hemosiderin (intravascular); (2) **DAT (direct Coombs)**: positive for IgG ± C3 (warm); C3 alone (cold); negative possible in some AIHA (DAT-neg); (3) **Smear**: spherocytes (warm AIHA) — Fc-mediated splenic clearance partial → loss of membrane; agglutination (cold); schistocytes if microangiopathic (different — TTP, HUS, DIC, mechanical valve); (4) **Types**: - **Warm AIHA** (~ 60-70%): IgG, optimal 37°C, extravascular hemolysis (spleen); idiopathic, lymphoproliferative (CLL, lymphoma — must rule out), SLE, drugs (alpha-methyldopa, penicillin, cephalosporin); - **Cold agglutinin disease** (CAD): IgM, optimal 4°C, intravascular hemolysis via complement; CAD primary (clonal lymphoproliferative — IGHV4-34 monoclonal IgM); secondary (Mycoplasma, EBV, lymphoma); - **Paroxysmal cold hemoglobinuria** (Donath-Landsteiner) — rare children post-viral; - **Mixed**, **drug-induced**; (5) **DAT-negative AIHA** ~ 5-10% — use enhanced techniques (gel column, flow); (6) **Workup for secondary**: CBC + smear, immunoglobulins, ANA, lymphadenopathy/splenomegaly assess (LDH, CT), HIV/hepatitis, drug review; PNH (flow CD55/CD59) consider if DAT-negative; (7) **Treatment**: - **Warm AIHA**: prednisone first-line; rituximab second-line (effective); IVIG less reliable; splenectomy (vaccines + prophy); thrombosis prophylaxis (high risk); transfusion if severe with best-match unit; - **CAD**: avoid cold + treat underlying; **sutimlimab** (anti-C1s, complement inhibitor — CARDINAL/CADENZA trials) approved 2022 + targets intravascular; rituximab ± bendamustine for clonal disease; steroids LESS effective in CAD vs warm; (8) **Multidisciplinary** including hematology + rheum/onc if secondary

---

AIHA: hemolysis markers + DAT positive. Warm (IgG, spleen, spherocytes) vs cold (IgM, complement, intravascular). Rule out secondary (lymphoproliferative). Warm: pred → rituximab. CAD: sutimlimab (anti-C1s) + rituximab. Thrombosis prophylaxis.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'pathology'
  and scenario = 'ผู้ป่วยหญิงอายุ 30 ปี — สงสัย AIHA → DAT (direct antiglobulin test) positive IgG + C3; warm autoantibody; CBC: Hb 7, retic 12%, smear: spherocytes + polychromasia; LDH high, haptoglobin low, indirect bili high';

update public.mcq_questions
set choices = '[{"label":"A","text":"ไม่ส่ง"},{"label":"B","text":"Pleural Effusion Cytology + Workup"},{"label":"C","text":"Random Tx"},{"label":"D","text":"Refuse"},{"label":"E","text":"Hospice"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Pleural Effusion Cytology + Workup: (1) **Light''s criteria for exudate vs transudate** (any 1 of 3): - Pleural/serum protein > 0.5; - Pleural/serum LDH > 0.6; - Pleural LDH > 2/3 upper limit of normal serum LDH; (2) **Transudates**: CHF, cirrhosis, nephrotic, hypoalbuminemia; (3) **Exudates**: infection (parapneumonic, empyema, TB), malignancy, PE, autoimmune (RA, lupus), pancreatitis, chylothorax, hemothorax; (4) **Tests on pleural fluid**: protein + LDH + glucose + pH; cell count + differential; cytology + cell block; gram stain + bacterial culture; AFB smear + culture (TB); fungal; adenosine deaminase (TB suggestive); triglyceride (chyle); amylase (esophageal/pancreatic); flow cytometry (lymphoproliferative); biomarkers — selected; (5) **Cytology yield malignant**: ~ 60-80% with adequate sample (≥ 1 sample; high volume aspirated 60-100 mL); cell block essential — better morphology + IHC opportunity; (6) **Common malignancies metastatic to pleura**: lung > breast > GI > GU > lymphoma > others; mesothelioma primary; (7) **Mesothelioma workup**: thoracoscopic biopsy preferred (cytology limited); IHC mesothelial (calretinin+, WT1+, D2-40+, CK5/6+, mesothelin+) vs adenocarcinoma (CEA+, BerEP4+, MOC31+, TTF-1+, claudin-4+); (8) **PD-L1 + biomarker** testing on cell block adequate samples — increasingly important; (9) **Flow cytometry for lymphocyte-predominant** rule out lymphoma; (10) **TB pleuritis** in Thailand consideration — high ADA, lymphocyte-predominant, low glucose, AFB low yield in fluid — pleural biopsy higher yield; (11) **Multidisciplinary**: pulm + path + onc + ID; (12) **Indwelling pleural catheter** for recurrent malignant effusion

---

Pleural fluid: Light''s criteria (exudate vs transudate). Tests: protein/LDH/cyto/culture/ADA/flow. Cell block for IHC. Malignancy panel: meso markers vs adenoca markers. TB: ADA + lymphocytic + biopsy higher yield. PD-L1 on cell block. Multidisciplinary.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'pathology'
  and scenario = 'ผู้ป่วยอายุ 50 ปี — pleural effusion → thoracentesis 1.5 L → fluid sent: cytology + cell count + chemistry + culture + flow cytometry; results: lymphocyte-predominant + protein 5.2 + LDH 450 + cytology malignant cells; Light''s criteria + cytology workflow';

update public.mcq_questions
set choices = '[{"label":"A","text":"All FNA = surgery"},{"label":"B","text":"Bethesda System for Thyroid Cytopathology (2023)"},{"label":"C","text":"All FNA = nothing"},{"label":"D","text":"Skip"},{"label":"E","text":"Random"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Bethesda System for Thyroid Cytopathology (2023): (1) **6 Categories with malignancy risk + management**: - **I — Non-diagnostic** (5-10%); ROM 13% (5-20%); → repeat FNA with US guidance; - **II — Benign** (60-70%); ROM < 4%; → clinical/US surveillance; - **III — Atypia of undetermined significance (AUS)** (~ 10%); ROM 22% (13-30% — wide); → **molecular testing** (Afirma GSC, ThyroSeq, ThyGeNEXT/ThyraMIR) preferred OR repeat FNA OR lobectomy; - **IV — Follicular neoplasm/SFN** (5-10%); ROM 30% (23-34%); → **molecular testing** preferred OR lobectomy; - **V — Suspicious for malignancy** (~ 5%); ROM 74% (67-83%); → lobectomy or near-total thyroidectomy; - **VI — Malignant** (~ 5%); ROM 97% (97-99%); → thyroidectomy ± central neck dissection; (2) **NIFTP carve-out** affects malignancy risks; (3) **Molecular testing for III + IV** (refines management): - **High-risk mutations** (BRAF V600E, TERT promoter, TP53, fusions ALK/RET/NTRK) → surgery + extent guided; - **RAS-like, intermediate**, **benign signature** — lobectomy or surveillance; - Negative predictive value high — rule out malignancy + reduce unnecessary surgery; (4) **US risk stratification** (TI-RADS, ATA) determines FNA threshold and adds info; (5) **Special considerations**: pediatric (lower thresholds), pregnancy (defer if safe), graves; (6) **Multidisciplinary**: endocrinology + endo surgery + cytopathology + radiology; (7) **Active surveillance** for low-risk papillary microcarcinoma emerging

---

Bethesda 2023 thyroid: 6 categories (I non-diag, II benign, III AUS, IV FN/SFN, V susp, VI malignant) with ROM + mgmt. III + IV → molecular testing (Afirma/ThyroSeq) refines decisions. US risk strat (TI-RADS/ATA). Multidisciplinary.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'pathology'
  and scenario = 'ผู้ป่วยอายุ 40 ปี — thyroid nodule 2 cm → FNA → Bethesda categories interpretation + recommendations + reflex molecular testing';

update public.mcq_questions
set choices = '[{"label":"A","text":"Skip lab"},{"label":"B","text":"Blood Culture + Identification Workflow"},{"label":"C","text":"Discard"},{"label":"D","text":"No reporting"},{"label":"E","text":"Refuse"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Blood Culture + Identification Workflow: (1) **Gram stain on positive blood culture** — preliminary report ASAP (clusters → Staph; chains → Strep/Enterococcus; pairs → Strep pneumo; tetrads; rods); critical-value notification; (2) **Identification methods**: - **MALDI-TOF MS** (rapid, minutes from colonies — revolutionized clinical micro); - **Rapid molecular** (PCR — BioFire BCID2, Verigene, GeneXpert) directly from positive bottle — 1-2 hr ID + select resistance markers (mecA for MRSA, vanA/B for VRE, KPC, NDM, OXA, CTX-M for ESBL/CRE); - **Conventional biochemical + culture** still backup; (3) **Susceptibility testing (AST)**: - **Phenotypic** (MIC by broth microdilution, gradient/Etest, automated systems Vitek/Phoenix); reference standard; - **Rapid AST** emerging (Accelerate Pheno, MicroScan rapid panels) — faster than 18-24h; - **Disk diffusion (Kirby-Bauer)** still used; - **CLSI / EUCAST breakpoints** updated annually; (4) **MRSA**: mecA/mecC encoded PBP2a → cefoxitin/oxacillin resistant; treat with vancomycin (target trough 15-20 or AUC/MIC 400-600), daptomycin (not pulmonary — surfactant inactivates), linezolid, ceftaroline, dalbavancin, oritavancin; (5) **Communication + stewardship**: - Critical-value calls for blood culture positive — rapid impact; - **Antimicrobial stewardship** consult/intervention — narrow when susceptibilities back; de-escalation; - **Source control** essential (line, abscess, endocarditis workup); (6) **TAT goals**: blood culture detection within hours (continuous monitoring systems — BacT/Alert, BACTEC); gram stain reported same day; preliminary ID + AST same day with rapid methods; (7) **Contamination vs true positive**: skin flora (CoNS, diphtheroids, Cutibacterium) — single bottle, late time-to-positivity → consider contamination + clinical context; (8) **Quality**: contamination rates < 3% target; volume adequate (≥ 10 mL/bottle adults); two sets

---

Blood culture: gram stain immediate, MALDI-TOF + rapid molecular (BCID2 detects mecA MRSA). Phenotypic AST CLSI/EUCAST. MRSA → vancomycin (not dapto for pulm). Critical-value + stewardship + source control. Contamination < 3% target.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'pathology'
  and scenario = 'ผู้ป่วยอายุ 45 ปี — septic shock — blood cultures growing gram-positive cocci in clusters; → identification + susceptibility — MRSA suspected; lab workflow + reporting + antimicrobial stewardship';

update public.mcq_questions
set choices = '[{"label":"A","text":"Viral meningitis"},{"label":"B","text":"Bacterial Meningitis — Lab + Treatment"},{"label":"C","text":"Refuse"},{"label":"D","text":"Tumor"},{"label":"E","text":"Skip"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Bacterial Meningitis — Lab + Treatment: (1) **CSF profile**: - **Bacterial**: cloudy, WBC > 1000 PMN-predominant, protein > 100, glucose < 40 (CSF/serum < 0.4); - **Viral**: clear, WBC 10-1000 lymphocyte-predominant, protein normal-mildly elevated, glucose normal; - **TB**: lymphocytic, protein very high, glucose low, ADA elevated; - **Fungal**: lymphocytic, similar to TB; cryptococcal — India ink, antigen, culture; (2) **Gram stain CSF morphology** clues: - GPC pairs lancet — Strep pneumoniae; - **GNDC — Neisseria meningitidis** (this case); - GNCB — Haemophilus influenzae (rare post-Hib vaccine); - GPB short — Listeria (elderly, pregnant, immunosup); - Pleomorphic GNB — others; (3) **N. meningitidis (meningococcal) — critical management**: - **Treatment**: ceftriaxone + vancomycin + dexamethasone (decreases neuro outcomes Strep pneumo; less benefit meningococcal but typically given empirically); - **Penicillin G** susceptible historically but resistance emerging; - **Chemoprophylaxis** close contacts: rifampin / ciprofloxacin / ceftriaxone (single dose); - **Reportable** to public health; vaccine recommendations to outbreak community; (4) **Empiric meningitis Tx by age/risk**: - Adult: ceftriaxone + vancomycin (± ampicillin if Listeria risk — > 50, immunosup, pregnant) + dexamethasone; - Steroid-responsive: pneumococcal; - Post-neurosurgical/trauma: add anti-pseudomonal (cefepime/meropenem); vancomycin; (5) **Workup**: blood cultures × 2; CT before LP if focal deficits, papilledema, immunocompromised, recent seizure, altered LOC; (6) **Molecular**: BioFire ME panel — rapid multiplex PCR; (7) **PCR + cultures + sensitivities**; (8) **Severe complications**: cerebritis, abscess, hydrocephalus, sequelae (hearing loss); (9) **Vaccination**: pneumococcal, Hib, meningococcal (MCV4 + Men B); (10) **Multidisciplinary**: ID + neurology + IM + public health

---

Bacterial meningitis: cloudy CSF, PMN, low glucose, high protein. GNDC = N. meningitidis. Empiric ceftriaxone + vanco ± amp (Listeria) + dexamethasone. Meningococcal: reportable, chemoprophylaxis contacts. BioFire ME panel rapid. CT before LP if focal/immunosup.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'pathology'
  and scenario = 'ผู้ป่วยอายุ 55 ปี — fever + headache + neck stiffness → LP: CSF cloudy, WBC 2500/µL (90% PMN), protein 250, glucose 20 (serum 90); gram stain: gram-negative diplococci; การวินิจฉัยและการรักษา + lab workflow';

update public.mcq_questions
set choices = '[{"label":"A","text":"ไม่ต้องวิเคราะห์"},{"label":"B","text":"Liver Function Test (LFT) Interpretation"},{"label":"C","text":"Refuse"},{"label":"D","text":"Skip"},{"label":"E","text":"Random"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Liver Function Test (LFT) Interpretation: (1) **Hepatocellular pattern**: AST + ALT markedly elevated (> 3-5× ULN); R ratio = (ALT/ULN) / (ALP/ULN) > 5; causes — viral, drug (acetaminophen acute, isoniazid), ischemic, autoimmune, Wilson''s, alpha-1 AT; (2) **Cholestatic pattern**: ALP + GGT elevated > AST/ALT (R < 2); causes — extrahepatic (CBD stone, stricture, malignancy) vs intrahepatic (PBC, PSC, drug, infiltrative, sepsis); GGT confirms ALP hepatic vs bone origin; (3) **Mixed pattern**: R 2-5; (4) **AST/ALT ratio**: - > 2 — alcoholic liver disease (AST > ALT due to pyridoxal deficit + mitochondrial); - > 1 + low absolute — cirrhosis; - < 1 typical for NAFLD/MASLD + viral hepatitis (acute); (5) **Bilirubin**: - **Unconjugated** (indirect) — hemolysis, Gilbert''s, Crigler-Najjar; - **Conjugated** (direct) — hepatocellular dysfunction, cholestasis, Dubin-Johnson, Rotor; (6) **Synthetic function**: albumin, INR/PT (vitamin K-dependent factors — half-life 6h for factor VII, sensitive); platelets (hypersplenism, thrombopoietin decreased); (7) **Cirrhosis labs**: low albumin + elevated INR + thrombocytopenia + low Na (advanced); MELD (bili + Cr + INR + Na) for prognosis + transplant priority; Child-Pugh A/B/C; (8) **Etiology workup**: - **Viral**: HBV (HBsAg, anti-HBc, HBV DNA), HCV (Ab + RNA), HAV/HEV; - **Alcohol** history + AUDIT; - **Metabolic**: NAFLD/MASLD (US + transient elastography), Wilson''s (ceruloplasmin + 24h urine Cu < 40 yo), hemochromatosis (ferritin + sat + HFE), alpha-1 AT phenotype; - **Autoimmune**: ANA, ASMA, anti-LKM, IgG, AMA (PBC), p-ANCA (PSC); MRCP for PSC; - **Drug-induced** review (LiverTox); (9) **Imaging**: US + Doppler; MRI/MRCP; transient elastography; (10) **Cirrhosis surveillance**: HCC US ± AFP q6 mo, varices EGD, encephalopathy + ascites screening

---

LFT: hepatocellular (AST/ALT↑, R>5) vs cholestatic (ALP/GGT↑, R<2) vs mixed. AST/ALT ratio >2 alcohol. Bili direct vs indirect. Synthetic (albumin, INR). Cirrhosis: MELD, Child-Pugh. Etiology workup: viral/metabolic/autoimmune/drug + imaging. Surveillance HCC/varices.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'pathology'
  and scenario = 'ผู้ป่วยอายุ 50 ปี hepatitis + cirrhosis → labs: total bili 12, direct 9, AST 145, ALT 95, ALP 280, GGT 350, albumin 2.8, INR 1.8, plt 80; interpretation + cause workup';

commit;
