-- ===============================================================
-- UPDATE chunk 5/8: pathology (25 questions)
-- ===============================================================

begin;

update public.mcq_questions
set choices = '[{"label":"A","text":"Random"},{"label":"B","text":"Gunshot Wound Forensic Examination"},{"label":"C","text":"Skip"},{"label":"D","text":"Refuse"},{"label":"E","text":"Random"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Gunshot Wound Forensic Examination: (1) **Entrance vs exit features**: - **Entrance**: usually round/oval; abrasion collar (skin scraped by spinning bullet); marginal abrasion irregular if angled; bullet wipe (dirt/lubricant); inverted edges; - **Exit**: usually larger, irregular/stellate; no abrasion collar (unless shored = pressed against surface); everted edges; (2) **Range of fire (entrance characteristics)**: - **Contact**: muzzle imprint, soot in wound track, seared edges, stellate tearing (gas under skin — head especially); - **Close-range (intermediate)**: < ~ 1 m — **stippling/tattooing** = embedded burnt+unburnt powder grains (in skin, not wipeable); soot if very close; - **Distant**: no stippling; (3) **Documentation**: - Photographs (with scale, ruler); - Diagrams; - Trajectory: external + internal — entrance to exit or terminal location; can suggest assailant position; - Wound dimensions, location anatomically + clothing + body landmarks; (4) **Bullet recovery + chain of custody**: - Recovered carefully without metal forceps (preserve striae for ballistics); - Labeled + sealed bag with documentation; - Chain of custody maintained for forensic ballistics + court; (5) **Tox + alcohol**: standard; (6) **Manner determination — homicide, suicide, accident, undetermined**: - Suicide indicators: contact wound, anatomically accessible site (temple ipsilateral to handedness, mouth, sub-mandibular), single shot, weapon present, no defensive wounds, fingerprints/DNA; - Multiple shots, atypical site, defensive wounds, weapon away → homicide more likely; - Scene investigation essential; (7) **Special — shotgun**: pellet pattern (close range tight, distance spreads); choke effect; wadding identified; (8) **Other forensic ballistics**: rifling pattern (lands + grooves), caliber estimation, NIBIN database; (9) **Communication**: testimony in court, evidence-based, neutral; quality + peer review for testimony; (10) **NAME standards + Wood + DiMaio textbook + RCFL coordination**

---

GSW: entrance (abrasion collar, contact may have soot/imprint/stellate; close range has stippling) vs exit (larger, no collar). Range: contact/close/distant. Manner determination needs scene + wounds + tox + history. Bullet recovery + chain of custody. Photograph + diagram + measurements.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'pathology'
  and scenario = 'ME case — found man with gunshot wound to head; postmortem exam — distinguishing entrance vs exit wounds, range determination, trajectory, and forensic ballistics workflow';

update public.mcq_questions
set choices = '[{"label":"A","text":"ไม่ทำอะไร"},{"label":"B","text":"Rh Alloimmunization Prevention"},{"label":"C","text":"Refuse"},{"label":"D","text":"Surgery"},{"label":"E","text":"Random"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Rh Alloimmunization Prevention: (1) **Pathophysiology**: Rh-negative mother exposed to Rh-positive fetal blood (delivery, miscarriage, trauma, procedures, transfusion) → anti-D Ab → next Rh-positive pregnancy → fetal hemolysis (HDFN — hemolytic disease of fetus + newborn); severe → hydrops fetalis, in utero death; (2) **Prevention with RhoIG (RhoGAM, anti-D immunoglobulin)**: - **Antenatal**: 300 μg IM at 28 wk gestation (covers usual fetomaternal hemorrhage to delivery); - **Postpartum**: 300 μg IM within 72 hr of delivery if baby Rh+ (cord blood typing); - **Sensitizing events**: 300 μg after miscarriage > 12 wk, ectopic, amniocentesis, CVS, abdominal trauma, ECV, antepartum hemorrhage; smaller doses (50-120 μg) for early pregnancy events per protocol; (3) **Workup**: - **Antibody screen** maternal at first prenatal + 28 wk (and after sensitizing event); - **Cord blood typing** (ABO, Rh, DAT) on baby of Rh-negative mother; - **Kleihauer-Betke test** if large fetomaternal hemorrhage suspected (placental abruption, trauma, abdominal injury) — quantifies fetal RBCs in maternal circulation → dose RhoIG (1 vial 300 μg covers ~ 30 mL fetal whole blood); alternative flow cytometry; (4) **Mechanism RhoIG**: passive Ab coats fetal RBCs → cleared by maternal RES before maternal immune sensitization; (5) **Mother already sensitized (anti-D present)**: RhoIG doesn''t help — monitor anti-D titers + middle cerebral artery Doppler peak systolic velocity (MCA-PSV) in fetus → predicts fetal anemia; intrauterine transfusion if severe; deliver early; (6) **Other relevant alloantibodies**: Kell (transfuse Kell-negative blood to Rh-D negative women of childbearing age — Kell can cause severe HDFN with low titers + suppress erythropoiesis), Duffy, Kidd, c, E, S; routine antibody screen covers; (7) **ABO incompatibility HDFN**: mostly mild — group O mother + A/B baby; jaundice manageable with phototherapy; (8) **Postpartum management**: newborn DAT + bilirubin monitoring; phototherapy + exchange transfusion if severe; (9) **Counseling for future pregnancy**

---

Rh prevention: RhoIG antenatal (28 wk) + postpartum (if baby Rh+) within 72 h + after sensitizing events. Kleihauer-Betke quantifies FMH for dosing. Already sensitized → MCA-PSV + IUT. Kell-negative blood for Rh-D-neg women childbearing. Other alloantibodies relevant.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'pathology'
  and scenario = 'Pregnant woman Rh-negative with Rh-positive fetus — postpartum maternal serology + antibody screen + cord blood + Kleihauer-Betke + RhoGAM administration + management of subsequent pregnancy';

update public.mcq_questions
set choices = '[{"label":"A","text":"Random"},{"label":"B","text":"Cardiac Biomarkers — Troponin (hs-cTn) + Use"},{"label":"C","text":"Skip"},{"label":"D","text":"Random"},{"label":"E","text":"Refuse"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Cardiac Biomarkers — Troponin (hs-cTn) + Use: (1) **High-sensitivity troponin (hs-cTnI or hs-cTnT)** — replaces conventional troponin; detects much lower levels reliably + rapid rule-in/rule-out protocols (0/1-h or 0/2-h); (2) **Pathophysiology**: cTnI + cTnT — cardiac-specific structural proteins released from injured cardiomyocytes; rise within 1-3 hr injury, peak 24-48 hr, persist 7-14 d; (3) **Interpretation**: - **Sex-specific 99th percentile URL (upper reference limit)** — male/female different — apply correct; - **Delta change** essential — rule-in for MI requires both elevated AND dynamic change (rise/fall); - 0/1-h algorithm ESC: hs-cTn very low + no chest pain ≥ 3 hr → rule-out; high + delta → rule-in; - Type 1 MI (atherothrombotic) vs **Type 2 MI** (supply-demand mismatch — anemia, hypotension, tachyarrhythmia); cardiac troponin elevation also in many non-MI conditions; (4) **Differential of elevated troponin (NOT all MI)**: - Demand ischemia (anemia, sepsis, tachyarrhythmia, HF, hypotension, hypoxia); - Myocarditis (incl post-COVID, immune checkpoint inhibitor); - Cardiomyopathy (HCM, takotsubo, peripartum, infiltrative); - Aortic dissection, PE (RV strain), severe HTN, stroke (neurogenic stunning); - Renal disease (chronic elevation — interpret with delta + clinical), tachyarrhythmia, blunt trauma, cardioversion, ablation, cardiac surgery; - Sepsis, critical illness; (5) **Universal definition of MI (4th)**: troponin rise/fall + ≥ 1 of (symptoms ischemia, ECG changes, imaging evidence wall motion/loss, coronary thrombus identified); (6) **In pregnancy**: differential includes peripartum cardiomyopathy, preeclampsia-related, dissection (SCAD — spontaneous coronary artery dissection — increased pregnancy), PE, amniotic fluid embolism, takotsubo; pregnancy slightly alters reference; (7) **Other biomarkers**: BNP/NT-proBNP (HF — pregnancy slightly elevated baseline), D-dimer (PE — pregnancy elevated baseline — adjust by trimester or use age/preg-adjusted cutoff or YEARS), CK-MB (obsolete except specific scenarios); (8) **Pre-analytics**: hemolysis affects assays; tube types; same assay for serial; (9) **Critical value reporting** + ED-cardiology coordination + standardized protocols

---

hs-cTn: sex-specific 99th URL + delta change rule-in MI. 0/1-h algorithm ESC. DDx many non-MI causes (demand, myocarditis, PE, dissection, sepsis, renal, infiltrative). Universal MI definition (4th). Pregnancy: SCAD, peripartum CM, preeclampsia, PE.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'pathology'
  and scenario = 'ผู้ป่วยอายุ 35 ปี ผู้หญิงตั้งครรภ์ — chest pain + dyspnea + troponin elevated; cardiac biomarkers + interpretation + reference intervals + DDx';

update public.mcq_questions
set choices = '[{"label":"A","text":"Hyperthyroidism"},{"label":"B","text":"Hypothyroidism — Diagnosis + Lab Interpretation"},{"label":"C","text":"Refuse"},{"label":"D","text":"Random"},{"label":"E","text":"Adrenal crisis"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Hypothyroidism — Diagnosis + Lab Interpretation: (1) **Primary hypothyroidism**: TSH ↑ + free T4 ↓ (overt) or normal (subclinical); most common etiology — **Hashimoto thyroiditis** (autoimmune — anti-TPO + anti-Tg positive); other — post-radioactive iodine, post-thyroidectomy, iodine deficiency, drugs (lithium, amiodarone, IFN, IO checkpoint inhibitors, ATG, TKI); (2) **Secondary (central) hypothyroidism**: TSH low/inappropriately normal + free T4 ↓ — pituitary or hypothalamic disease (mass, surgery, RT, infiltrative — sarcoid, hemochromatosis, lymphocytic hypophysitis); (3) **Sick euthyroid (NTIS — non-thyroidal illness syndrome)**: TSH normal/low, T3 low, reverse T3 high, T4 variable — defer routine hypothyroid screening in critically ill unless strong clinical suspicion; (4) **TSH assays — interpretation pitfalls**: - Reference range narrows ages + adjusted for pregnancy (trimester-specific cutoffs — lower upper limit early pregnancy); - **Biotin interference** (high-dose biotin supplements interfere with streptavidin-biotin immunoassays → falsely low TSH + falsely high free T4 mimicking hyperthyroidism — pause biotin 48 h before draw); - **Macro-TSH** (autoantibody-bound TSH cleared slowly — falsely high TSH); - **Heterophile antibodies, HAMA** — false elevations; (5) **Treatment**: - **Levothyroxine (T4)** — once-daily oral, empty stomach, 30-60 min before food/coffee/other meds; weight-based starting dose ~ 1.6 μg/kg/d in healthy; lower starting dose (12.5-25 μg) in elderly, CAD; - Recheck TSH 6-8 wk after dose change; - Target TSH normal range (mid-low for young, slightly higher for elderly); - **Subclinical hypothyroidism**: treat if TSH > 10, symptomatic, infertility/pregnancy planning, goiter, dyslipidemia; pregnant — treat to TSH < 2.5; - **Pregnancy**: increase levothyroxine ~ 30% empirically + monitor q4 wk first half; (6) **T3 add-on**: largely unsupported routinely; some persistent symptoms patient subgroups discussed; (7) **Drug interactions**: PPI, calcium, iron, soy reduce absorption — separate timing; (8) **Multidisciplinary**: endocrinology + primary care + pregnancy + cardiology if older with CAD

---

Hypothyroidism: primary (TSH↑, T4↓) — Hashimoto most common. Central (low/inappropriate TSH). Sick euthyroid distinct. Biotin/macro-TSH/heterophile interfere. Levothyroxine 1.6 μg/kg empty stomach; recheck q6-8 wk; pregnancy ↑30%. Subclinical Tx criteria.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'pathology'
  and scenario = 'ผู้ป่วยอายุ 60 ปี — fatigue + bradycardia + cold intolerance; labs TSH 25, free T4 0.4 (low), anti-TPO + anti-thyroglobulin antibodies elevated; การวินิจฉัยและการรักษา + interpretation';

update public.mcq_questions
set choices = '[{"label":"A","text":"Diuretic"},{"label":"B","text":"Hyponatremia — Workup + Treatment"},{"label":"C","text":"Skip"},{"label":"D","text":"Refuse"},{"label":"E","text":"Furosemide alone"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Hyponatremia — Workup + Treatment: (1) **First step — confirm true hyponatremia + identify acute vs chronic**: rule out pseudohyponatremia (hyperlipidemia/hyperproteinemia — older methods; hyperglycemia — corrected Na = measured + 1.6 mEq/L per 100 mg/dL glucose above 100); (2) **Classification by tonicity + volume**: - **Hypotonic** (true): - **Hypovolemic**: GI loss, renal loss (diuretics — thiazide), adrenal insufficiency, third-spacing, cerebral salt wasting; - **Euvolemic**: SIADH (this case profile — urine osm > 100 + serum osm < 275 + euvolemic + normal renal/adrenal/thyroid + urine Na > 20); hypothyroidism; adrenal insufficiency; reset osmostat; primary polydipsia (low urine osm < 100); - **Hypervolemic**: HF, cirrhosis, nephrotic syndrome, AKI/CKD; (3) **SIADH causes**: - **CNS**: stroke, hemorrhage, infection (meningitis, encephalitis), trauma, mass, surgery, pain, nausea; - **Pulmonary**: SCLC ectopic ADH, pneumonia, TB, ARDS; - **Drugs**: SSRIs, carbamazepine + oxcarbazepine, MDMA, antipsychotics, NSAIDs, vincristine, cyclophosphamide; - **Postoperative** (especially neuro); - **HIV, idiopathic in elderly** (~ 10% of community-dwelling elderly); (4) **Workup essentials**: - **Serum + urine osmolality + urine Na simultaneously**; - **Volume status assessment**; - **TSH, cortisol** rule out endocrine; - **History + medication review**; - **Imaging** for SIADH cause if cancer/CNS suspected; (5) **Treatment**: - **Acute severe symptomatic (seizure, severe altered LOC, brainstem herniation)**: **3% hypertonic saline 100 mL bolus q10 min × 1-3** until symptoms improve; target rise ~ 4-6 mEq/L initial; - **Chronic asymptomatic/mild**: cause-directed — restrict fluid, treat underlying; - **SIADH chronic**: fluid restriction (< 800-1000 mL/d), salt + protein intake, **tolvaptan (V2 receptor antagonist)** carefully (limit 30 days liver concern); urea oral; loop diuretic + salt tablets adjunct; - **CRITICAL — rate of correction**: ≤ 10-12 mEq/L in 24 hr (some say 8); too rapid → **osmotic demyelination syndrome (ODS — central pontine + extrapontine myelinolysis)** — devastating, irreversible; - **Risk factors ODS**: chronic hyponatremia, alcoholism, malnutrition, liver disease, hypokalemia; - **Re-lower** with hypotonic fluid + DDAVP if overcorrected to slow back; (6) **Recheck Na q2-4 hr during correction**

---

Hyponatremia: confirm hypotonic + classify by volume → cause. SIADH if euvolemic + urine osm>100 + urine Na>20 + normal endocrine. Acute symptomatic: 3% saline bolus. Chronic: fluid restriction, tolvaptan, urea. Rate ≤10-12 mEq/L/24h (ODS risk). Re-lower if overcorrected.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'pathology'
  and scenario = 'ผู้ป่วยอายุ 70 ปี — confusion + dilute urine; serum Na 118; clinical euvolemic; urine osm 450, serum osm 250; การวินิจฉัยและการ workup + management';

update public.mcq_questions
set choices = '[{"label":"A","text":"Random"},{"label":"B","text":"Mycobacterial Infection Pathology + Workflow"},{"label":"C","text":"Skip"},{"label":"D","text":"Random"},{"label":"E","text":"Refuse"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Mycobacterial Infection Pathology + Workflow: (1) **Histology features**: - **Granulomatous inflammation** — collections of epithelioid macrophages + Langhans giant cells + lymphocytes; - **Caseating necrosis** classic of TB (vs sarcoid non-necrotizing); - Acid-fast bacilli (slender, beaded rods) — usually scant in tuberculoid form, abundant in immunocompromised; - **Spectrum**: tuberculoid (well-organized granuloma, paucibacillary) → lepromatous-like in HIV severe (poorly formed, multibacillary, foamy macrophages); (2) **Stains for AFB**: - **Ziehl-Neelsen** (carbol-fuchsin) — gold standard; - **Kinyoni** (cold modification); - **Auramine-rhodamine fluorescence** — more sensitive than Z-N for screening; - **Fite stain** for M. leprae + Nocardia (less acid-fast); (3) **Differential of granulomatous infection**: - Mycobacteria — TB, NTM (MAC, kansasii), leprosy; - **Fungal** — histoplasmosis (small yeast in macrophages), coccidioidomycosis (large spherules with endospores), blastomycosis (broad-based budding), cryptococcosis (capsule with India ink/mucicarmine, narrow-based budding), aspergillosis (septate hyphae 45° branching), mucormycosis (broad ribbon-like aseptate hyphae 90° branching); - **Bacterial** — brucellosis, listeriosis, syphilis, cat-scratch (Bartonella); - **Parasitic** — schistosomiasis, leishmaniasis; - **Sarcoidosis** (non-caseating); - **GPA + Crohn''s** non-infectious; (4) **Special stains adjunct**: GMS, PAS (fungi); Warthin-Starry (spirochetes, Bartonella); Giemsa (Leishmania, Histoplasma); (5) **Molecular diagnostics (rapid + sensitive)**: - **GeneXpert MTB/RIF** (now MTB/RIF Ultra) — 2-hr PCR direct from specimen — detects MTB + rifampin resistance — revolutionary; - **Line probe assays** (LPA) — first-line + second-line drug resistance; - **NAAT** for other organisms; (6) **Culture + susceptibility** still gold standard for definitive ID + full susceptibility — Mycobacteria growth slow weeks (MGIT broth, LJ solid); MALDI-TOF mass spec for species ID; (7) **HIV + TB co-infection**: common SE Asia + sub-Saharan; impacts presentation + Tx; IRIS risk on ART; (8) **Reporting + public health**: TB reportable; isolate; contact tracing; (9) **Multidisciplinary**: pathology + microbiology + ID + pulmonology + public health

---

Granuloma: caseating (TB), non-caseating (sarcoid); Z-N/auramine for AFB; Fite for leprosy. Differential: fungi (GMS/PAS), bacterial, parasitic, autoimmune. GeneXpert MTB/RIF rapid + RIF resistance. Culture gold-standard + slow. HIV + TB common, IRIS risk.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'pathology'
  and scenario = 'ผู้ป่วยอายุ 30 ปี HIV positive — high fever + lymphadenopathy; biopsy: necrotizing granulomas with acid-fast bacilli; AFB+, GeneXpert MTB/RIF positive — rifampin susceptible; การ pathology workflow + integration';

update public.mcq_questions
set choices = '[{"label":"A","text":"TB"},{"label":"B","text":"Cryptococcosis — Pathology + Treatment"},{"label":"C","text":"Bacterial"},{"label":"D","text":"Refuse"},{"label":"E","text":"Skip"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Cryptococcosis — Pathology + Treatment: (1) **Organism**: Cryptococcus neoformans (immunocompromised — HIV/AIDS, organ transplant, steroid use) + C. gattii (immunocompetent + Pacific Northwest); encapsulated yeast — polysaccharide capsule (GXM antigen detected); (2) **Histology**: round to oval yeast 4-10 μm with thick polysaccharide capsule appearing as clear halo (mucicarmine + Alcian blue + Fontana-Masson + positive for capsule/melanin); narrow-based budding; (3) **Stains**: - **India ink** (CSF — wet mount) — capsule excludes dye; - **Mucicarmine** + **Alcian blue** — stain capsule pink/blue; - **Fontana-Masson** — stains melanin in cell wall (helpful capsule-deficient variant); - GMS + PAS — fungal wall; (4) **Cryptococcal antigen (CrAg) detection**: - Lateral flow assay (LFA) — fast, accurate, low cost — in serum + CSF; - Latex agglutination historical; - **Sensitive + specific** for screening — used for HIV+ patients with CD4 < 100 in high-burden settings (preempt with fluconazole); (5) **Clinical syndromes**: cryptococcal meningitis (most common AIDS, classic), pulmonary cryptococcosis (variable from asymptomatic to severe), cutaneous, prostate, disseminated; (6) **CSF in cryptococcal meningitis**: lymphocytic, elevated protein, low glucose, **markedly elevated opening pressure** (often > 25 cm H2O — critical to manage with repeated LPs to reduce → reduces blindness + mortality); (7) **Treatment** (cryptococcal meningitis HIV — WHO + IDSA): - **Induction (2 wk)**: amphotericin B (liposomal preferred — toxicity less) + flucytosine; - **AMBITION-cm trial** — **single-dose liposomal amphotericin B 10 mg/kg + 14 days flucytosine + fluconazole** non-inferior to standard, less toxic — emerging standard especially LMIC settings; - **Consolidation (8 wk)**: fluconazole 400-800 mg; - **Maintenance**: fluconazole 200 mg until CD4 > 100-200 sustained on ART; - **Opening pressure management**: serial LPs reducing 50% to < 20 cm; lumbar drain or shunt selected cases; - **IRIS risk** when ART started — delay ART 4-6 wk after antifungal initiation; (8) **Other organ transplant + non-HIV**: tailored; (9) **Pulmonary cryptococcosis** mild — fluconazole; severe — amphotericin + flucytosine then fluconazole; (10) **Multidisciplinary**: ID + neurology + ICU + pharmacy

---

Cryptococcus: encapsulated yeast (India ink, mucicarmine+); CrAg LFA sensitive. Meningitis AIDS classic. CSF: lymphocytic + ↑OP critical to manage. Tx: ampho + flucytosine induction → fluconazole consolidation + maintenance; AMBITION-cm single-dose lipo ampho emerging. IRIS risk.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'pathology'
  and scenario = 'ผู้ป่วย HIV/AIDS — sputum + BAL: large yeast cells with broad-based budding + capsule; cryptococcal antigen positive in serum + CSF; การวินิจฉัยและการรักษา';

update public.mcq_questions
set choices = '[{"label":"A","text":"Random"},{"label":"B","text":"Hematoxylin + Eosin (H&E) Stain Chemistry + Interpretation"},{"label":"C","text":"Skip"},{"label":"D","text":"Random"},{"label":"E","text":"Refuse"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Hematoxylin + Eosin (H&E) Stain Chemistry + Interpretation: (1) **Hematoxylin**: natural dye from logwood tree; oxidized to **hematein** (active form); requires **mordant** (aluminum, iron — Harris uses aluminum potassium sulfate) to bind tissue; basic — stains **acidic structures (nucleic acids, ribosomes, calcium-rich, mucin)** blue/purple → **''basophilic''**; (2) **Eosin**: acidic synthetic dye; stains **basic structures (proteins, cytoplasm, collagen, red blood cells, keratin)** pink/red → **''eosinophilic''**; (3) **Typical workflow**: deparaffinize (xylene) → rehydrate (graded ethanol) → hematoxylin → blueing (Scott''s tap water or lithium carbonate) — turns red precipitate blue + sharpens → differentiate (acid alcohol — remove excess) → dehydrate → eosin → dehydrate → clear → coverslip with mounting medium; (4) **Variations**: progressive (no differentiation, e.g., Mayer''s) vs regressive (over-stain then differentiate, e.g., Harris); H&E variations (gill''s, mayer''s, harris''s) — pathologists/labs prefer different; (5) **Common H&E artifacts + their causes**: - **''Cornflake'' (air bubbles)** — incomplete coverslip wetting → ghosts of cells; - **Knife scratches** — dull microtome; - **Tissue folding** — section too thick + cold block; - **''Chatter'' / lines** — microtome vibration or blocked block; - **Pale staining** — over-differentiation, weak dye, old; - **Over-purple/blue** — over-stain, inadequate differentiation; - **Floaters** — tissue contamination between cases; serious QC issue → CAP requirement to address; - **Pen/charcoal artifacts** from ink margins; - **Lipid washout artifact** — clear vacuoles from fat dissolved by xylene/ethanol; - **Freezing artifact** — ice crystal vacuolation (frozen sections); - **Mercury pigment** (B5 fixed) — small brown granules; - **Formalin pigment** (acid hematin — pH issue) — brown/black extracellular granules in bloody tissue; - **Heat artifact** (electrocautery) — nuclei elongated + smudged at edges; (6) **Other key routine stains**: PAS (carbohydrates, BM, fungi), GMS (fungi, PCP), Gram (bacteria), Z-N/auramine (AFB), Congo red (amyloid — apple-green birefringence under polarized), Prussian blue (iron), reticulin, trichrome (collagen), oil red O (frozen for lipid), Alcian blue (mucin); (7) **QA standards**: CAP histology checklist — stain quality monitoring + control slides + tissue handling

---

H&E: hematoxylin (basic, stains acidic structures blue — nucleic acids) + eosin (acidic, stains basic structures pink — cytoplasm/collagen). Progressive vs regressive. Artifacts: cornflake, scratches, chatter, floaters, lipid wash, formalin pigment. Special stains complement.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'pathology'
  and scenario = 'Resident — fundamentals of routine H&E stain — chemistry of hematoxylin and eosin staining + common artifacts + interpretation';

update public.mcq_questions
set choices = '[{"label":"A","text":"Random"},{"label":"B","text":"Flow Cytometry Principles"},{"label":"C","text":"Skip"},{"label":"D","text":"Random"},{"label":"E","text":"Refuse"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Flow Cytometry Principles: (1) **Concept**: cells in suspension pass through laser → detect forward scatter (FSC — size), side scatter (SSC — granularity/complexity), + fluorescence at multiple wavelengths from labeled antibodies binding cellular antigens (surface, intracellular); (2) **Workflow**: - Cell suspension preparation (blood, BM, lymph node, body fluid, FNA); - Lysis of RBCs (cell-specific protocols); - **Cocktail** of fluorochrome-conjugated antibodies (different fluorochromes — FITC, PE, APC, PerCP, BV421, etc. — many channels); - Acquire (typically 100,000+ events/tube); - **Compensation** for spectral overlap between fluorochromes; - **Gating** strategy (sequential gates): FSC/SSC → exclude debris + doublets → identify lymphocytes, monocytes, granulocytes, blasts → subset analysis; (3) **Modern instruments**: 8-12 colors routine; spectral flow cytometry + mass cytometry (CyTOF) > 30 parameters; (4) **Applications hemato**: - **Leukemia/lymphoma diagnosis + classification** — phenotype B/T/NK + lineage (CD19, CD20, CD3, CD56, CD13/33 myeloid, CD41/61 megakaryocyte, CD235a erythroid); abnormal antigen expression patterns vs normal; - **MRD (minimal residual disease)** — high-sensitivity (10⁻⁴ to 10⁻⁶) in ALL, CLL, AML, MM (8-color + next-generation flow per EuroFlow); - **PNH** — CD55 + CD59 absence on granulocytes/RBCs, FLAER (more sensitive); - **Lymphocyte subsets** — CD4/CD8 in HIV monitoring; - **CD34 stem cell enumeration** for HCT; - **DNA content/ploidy** (less common now); - **Platelet disorders** — GPIb (Bernard-Soulier), GPIIb/IIIa (Glanzmann); - **Reticulocyte enumeration** automated; (5) **Light chain restriction**: monoclonal B-cell — kappa or lambda only; vs polyclonal reactive — mixed; (6) **CD45 vs SSC plot**: standard gating — blasts CD45 dim/low SSC, lymphocytes CD45 bright/low SSC, granulocytes CD45 dim/high SSC; (7) **Limitations**: - Loss of architecture (cell context lost — biopsy still essential); - Cell viability sensitive (older samples); - Sample heterogeneity + subsampling; - Operator + interpretation expertise required; - Cost + technology investment; (8) **QC**: instrument standardization (CS&T beads), control samples, compensation, panel validation; (9) **Reporting**: standardized terminology; integrate with cytology/histology + cytogenetics + molecular

---

Flow cytometry: laser detection of size/granularity/fluorochrome-labeled antibodies. Multi-color cocktail + gating (CD45 vs SSC + lineage). Applications: heme malignancy classification, MRD (EuroFlow), PNH (CD55/59/FLAER), CD34, light chain restriction. Compensation + QC.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'pathology'
  and scenario = 'หลักการของ flow cytometry ใน hematopathology — workflow + gating + immunophenotyping + interpretation + applications + limitations';

update public.mcq_questions
set choices = '[{"label":"A","text":"Random"},{"label":"B","text":"Laboratory Biosafety Program"},{"label":"C","text":"Skip"},{"label":"D","text":"Random"},{"label":"E","text":"Refuse"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Laboratory Biosafety Program: (1) **Biosafety Levels (BSL — WHO/CDC)**: - **BSL-1**: agents not known to cause disease in healthy adults (e.g., E. coli K-12, B. subtilis); basic lab practices; - **BSL-2**: moderate-risk agents (most clinical specimens, HIV, HBV, HCV, S. aureus, Salmonella); BSC class II + PPE + sharps + autoclave; - **BSL-3**: serious/lethal disease + airborne route (M. tuberculosis, SARS-CoV-2 — initial phases, certain influenzas); sealed lab + directional airflow + respirator + autoclave; - **BSL-4**: high-risk + no treatment (Ebola, Marburg, smallpox); positive-pressure suit + dedicated facility; (2) **Animal BSL (ABSL)** parallel framework; (3) **Risk assessment** essential: - Agent characteristics (route, infectious dose, stability, treatment, vaccine); - Procedures (aerosol-generating — sonication, centrifuge open, vortex, pipetting, autopsy); - Personnel (training, immunocompromised, pregnant); - Equipment + facility; - Likelihood + consequence; (4) **Engineering controls** (most effective): biosafety cabinet (BSC class I/II/III — II most common clinical), HEPA filtration, autoclave, sealed centrifuges, biosafety hood; (5) **Administrative controls**: training, competency, SOPs, occupational health, vaccination (HBV, MMR, varicella, influenza, COVID, others per role); (6) **PPE**: gloves, lab coat, eye protection, face shield, respiratory (N95, PAPR); appropriate to task; donning/doffing trained; (7) **Sharps + waste**: sharps containers, no recapping, dedicated biohazard waste, segregation, disposal per regulations; chemical + radiation waste separate; (8) **Specimen handling**: tube tops carefully, prevent spills, contained transport, decontamination protocols (bleach 1:10, 70% EtOH, glutaraldehyde, etc. — agent-specific); (9) **Exposure response**: - Bloodborne — wash + report + occupational health + serology + PEP per algorithm (HIV PEP within hours, HBV vaccine/HBIG, HCV monitoring); - Aerosol — leave room + report; - Documentation + RCA; (10) **Reporting + surveillance**: needlestick injuries, near-misses; trend analysis; quality improvement; (11) **Regulations**: OSHA bloodborne pathogen standard, CDC/NIH BMBL 6th ed, CAP, ISO 15189, country-specific (e.g., Thailand DMSc); (12) **Culture of safety**: leadership commitment, non-punitive reporting, continuous improvement, training, drills

---

Biosafety: BSL 1-4 by agent risk; engineering (BSC, HEPA) > admin (training, vaccines) > PPE. Risk assessment + agent-specific. Exposure response — bloodborne PEP. Reporting non-punitive. OSHA BBP, BMBL 6th ed, ISO 15189. Culture of safety.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'pathology'
  and scenario = 'Lab director — implementing laboratory biosafety program + risk assessment + BSL levels + PPE + safety culture + reporting';

update public.mcq_questions
set choices = '[{"label":"A","text":"Random"},{"label":"B","text":"Lab Quality Management System (QMS)"},{"label":"C","text":"Random"},{"label":"D","text":"Skip"},{"label":"E","text":"Refuse"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Lab Quality Management System (QMS): (1) **Standards/accreditation frameworks**: - **ISO 15189**: international standard for medical labs — quality + competence; - **CAP (College of American Pathologists)** accreditation — checklists by discipline + on-site inspection; - **CLIA (US — Clinical Laboratory Improvement Amendments)** regulatory; - **The Joint Commission (TJC)** lab accreditation; - **WHO LQSI / Stepwise Lab Quality Improvement Process** for resource-limited; - **Country-specific**: Thailand LA (Laboratory Accreditation), BLQS; (2) **QMS pillars (12 ''Quality System Essentials'' per CLSI HS01)**: organization, personnel, equipment, purchasing/inventory, process control, information management, documents/records, occurrence management, assessments, process improvement, customer service, facilities/safety; (3) **Total testing process — 3 phases**: - **Pre-analytical** (60-70% of errors): order entry, patient ID, collection, transport, accessioning — STAT recognition, mislabels, tube errors, hemolysis; - **Analytical**: test performance, calibration, QC, validation, proficiency testing — failure modes traceable; - **Post-analytical**: result reporting, critical value, interpretation, distribution — wrong report linked to wrong patient; (4) **Quality control + proficiency testing**: - Daily internal QC (Westgard rules for SPC), CUSUM; - **External PT** required (CAP surveys, CDC, etc.) regular — proficiency testing failure → corrective action; - **Interlaboratory comparison**; (5) **Continuous improvement frameworks**: - **PDCA (Plan-Do-Check-Act)** Deming; - **Six Sigma DMAIC** (define-measure-analyze-improve-control) — DPMO < 3.4/million; - **Lean** — eliminate waste (TIM WOODS — transport, inventory, motion, waiting, overprocessing, overproduction, defects, skills); 5S; value stream mapping; - **A3 problem solving**, **kaizen**; (6) **Patient safety events**: - Sentinel events + close calls reported; - **Root cause analysis (RCA)** systematic; - **Failure modes + effects analysis (FMEA)** proactive; - **TJC NPSGs** patient safety goals (correct patient + sample, critical value, medication safety); (7) **KPIs/dashboards**: TAT (turnaround time), critical value compliance, rejection rate, customer satisfaction, mislabeling rate, error rates by phase; (8) **Personnel competency**: hire + train + assess (CLIA 6 elements); continuing ed; (9) **Document control**: SOPs, versions, training records, traceability; (10) **Risk-based quality (CLSI QMS, IVD-R)** modernizing — designed for individual lab + tests

---

Lab QMS: ISO 15189 / CAP / CLIA / TJC standards; CLSI HS01 12 essentials. Phases: pre-analytical (60-70% errors) + analytical + post-analytical. QC + PT mandatory. Improvement: PDCA/Six Sigma/Lean. RCA + FMEA. KPIs (TAT, critical values, rejections).'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'pathology'
  and scenario = 'Lab management — implementing comprehensive quality management system (QMS) with accreditation + continuous improvement + ISO 15189 + CAP + Six Sigma + lean';

update public.mcq_questions
set choices = '[{"label":"A","text":"Wilms"},{"label":"B","text":"Neuroblastoma — Pediatric"},{"label":"C","text":"Refuse"},{"label":"D","text":"Hodgkin"},{"label":"E","text":"Skip"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Neuroblastoma — Pediatric: (1) **Origin**: neural crest cells (sympathoadrenal) — adrenal medulla, paraspinal sympathetic ganglia; (2) **Most common extracranial solid tumor in children**; median age ~ 17 mo; (3) **Histology**: small round blue cell tumor; Homer-Wright rosettes (neuroblasts around fibrillary core); neuropil (fine eosinophilic matrix); spectrum — neuroblastoma (undifferentiated, poorly differentiated, differentiating), ganglioneuroblastoma (intermixed, nodular), ganglioneuroma (mature, benign); (4) **IHC**: synaptophysin+, chromogranin+, neuron-specific enolase+, CD56+, **PHOX2B+** (specific transcription factor), GD2 (target for therapy); CK negative (vs small cell carcinoma), CD99 negative (vs Ewing), TdT negative (vs lymphoblastic); (5) **Urinary catecholamines (HVA + VMA)** elevated in > 90% — diagnostic + monitoring; (6) **Imaging**: **MIBG (I-123 metaiodobenzylguanidine)** — concentrated in neuroblastoma — staging + response assessment; PET/CT alternative; (7) **Staging**: INRGSS (image-defined risk factors) — international consensus; INSS (older surgical staging); (8) **Risk stratification (Children''s Oncology Group)**: - Age (< 18 mo better), stage, MYCN amplification (poor), ploidy (hyperdiploid better in infant), histology (Shimada/INPC favorable vs unfavorable), 1p/11q LOH; - **MYCN amplification — strongest adverse molecular marker**; - **ALK mutations** (germline + somatic — actionable with crizotinib/lorlatinib); - **ATRX, ARID1A, TERT** alterations; (9) **Treatment by risk**: - **Low-risk**: surgery alone often curative; observation for stage MS infants; - **Intermediate-risk**: surgery + moderate chemo (carbo + etop + cyclo + dox); - **High-risk** (~ 50%, with worse outcomes): - **Induction**: 5-6 cycles intensive chemo (BuMel-based); - **Consolidation**: high-dose chemo + auto-HCT (often tandem) + radiation to primary; - **Maintenance**: **anti-GD2 immunotherapy (dinutuximab)** + IL-2 + GM-CSF + cis-RA (isotretinoin) — major survival improvement; - **Refractory/relapsed**: MIBG therapy (I-131), ALK inhibitors (if mutated), naxitamab, eflornithine new addition; (10) **Multidisciplinary**: pediatric onc + surgery + RT + nuclear medicine + pathology + genetics + supportive + survivorship

---

Neuroblastoma: neural crest; Homer-Wright + neuropil; synaptophysin/chromogranin/PHOX2B+; HVA/VMA + MIBG. INRGSS staging + COG risk (age, MYCN amp, ploidy, histology, 1p/11q). High-risk: induction + auto-HCT + anti-GD2 (dinutuximab) maintenance. ALK actionable.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'pathology'
  and scenario = 'ผู้ป่วยอายุ 5 ปี — abdominal mass + LDH high + catecholamine metabolites (HVA + VMA) elevated; biopsy: small round blue cells with Homer-Wright rosettes + neuropil-like background; IHC: synaptophysin+, chromogranin+, PHOX2B+; molecular: MYCN amplification';

update public.mcq_questions
set choices = '[{"label":"A","text":"Neuroblastoma"},{"label":"B","text":"Wilms Tumor (Nephroblastoma)"},{"label":"C","text":"Refuse"},{"label":"D","text":"Lymphoma"},{"label":"E","text":"Skip"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Wilms Tumor (Nephroblastoma): (1) **Most common renal tumor pediatric**; peak 2-5 yr; ~ 5% bilateral; (2) **Histology**: classic **triphasic** — **blastemal** (small round blue cells), **epithelial** (primitive tubules, glomeruloid structures), **stromal** (loose mesenchymal); proportions variable; (3) **Favorable vs unfavorable histology**: - **Favorable** ~ 90%; - **Unfavorable** — diffuse anaplasia (extreme nuclear enlargement + hyperchromasia + atypical mitoses); focal anaplasia better than diffuse; - **Other renal tumors pediatric** distinct entities (per WHO): **clear cell sarcoma of kidney (CCSK)**, **rhabdoid tumor of kidney (SMARCB1/INI1 loss — extremely aggressive)**, **congenital mesoblastic nephroma** (infant, ETV6-NTRK3 in cellular type); (4) **IHC**: WT1+ in blastemal/epithelial; PAX2/PAX8 epithelial; vimentin stromal; (5) **Molecular**: WT1, WT2 (11p15), CTNNB1, FBXW7, TP53 (anaplasia association); (6) **Hereditary predisposition syndromes (~ 10-15% Wilms)**: - **WAGR** (Wilms, Aniridia, GU anomaly, Range of intellectual disability — 11p13 deletion); - **Denys-Drash** (WT1 mutation — early onset nephropathy + pseudohermaphroditism + Wilms); - **Beckwith-Wiedemann** (11p15 — overgrowth, omphalocele, macroglossia, hemihypertrophy — Wilms + other tumors); - **Perlman, Sotos, Bloom, Li-Fraumeni**; — surveillance with renal US for at-risk children; (7) **Staging (COG NWTS)**: I (limited to kidney, resected) → V (bilateral); (8) **Treatment (combined approaches — COG North American + SIOP European)**: - **COG**: surgery first → adjuvant chemo based on stage + histology + biology; - **SIOP**: pre-operative chemo → surgery → adjuvant; - **Chemo agents**: vincristine + actinomycin D (low-stage), + doxorubicin (higher-stage); - **RT** for unfavorable + advanced; - **High-risk relapsed**: high-dose chemo + auto-HCT, etoposide-based, novel agents; (9) **Outcomes**: > 90% cure favorable; (10) **Multidisciplinary**: peds onc + urology + RT + pathology + genetics; (11) **Long-term survivorship** — cardiotoxicity, renal function, secondary malignancy, reproductive

---

Wilms tumor: triphasic (blastemal + epithelial + stromal); favorable vs unfavorable (anaplasia). WT1+/PAX8. Hereditary syndromes: WAGR, Denys-Drash, BWS — surveillance. COG vs SIOP approach (surgery first vs neoadjuvant). Cure > 90% favorable.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'pathology'
  and scenario = 'ผู้ป่วยเด็กอายุ 4 ปี — abdominal mass kidney → resection: triphasic tumor with blastemal + epithelial (tubules) + stromal components; favorable histology; WT1 mutation';

update public.mcq_questions
set choices = '[{"label":"A","text":"Random"},{"label":"B","text":"Pregnancy-Associated Breast Cancer (PABC) Integrative Care"},{"label":"C","text":"Random"},{"label":"D","text":"Skip"},{"label":"E","text":"Refuse"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Pregnancy-Associated Breast Cancer (PABC) Integrative Care: (1) **Definition**: diagnosed during pregnancy, lactation, or 1 year postpartum; ~ 1 in 3000 pregnancies; often delayed diagnosis (changes in breast); (2) **Pathology + workup**: - Core biopsy safe during pregnancy; pathology unchanged — IHC (ER/PR/HER2/Ki-67) standard; - More often ER-, HER2+, TNBC, higher grade in young; - Genetic counseling — BRCA testing recommended (young + family history); (3) **Staging**: US, MRI breast (no gadolinium contrast in pregnancy), CXR (with abdominal shielding), liver US; avoid CT + PET if avoidable; bone scan post-delivery; (4) **Multidisciplinary team**: medical oncology + breast surgery + radiation oncology + maternal-fetal medicine + OB-GYN + pathology + radiology + neonatology + psychology + lactation; (5) **Treatment by trimester**: - **1st trimester**: - **Surgery** safe (mastectomy or BCS — adapt anesthesia, avoid SLN with isosulfan blue, radiotracer alone OK); - **Chemotherapy CONTRAINDICATED** in 1st trimester (organogenesis); - **Endocrine therapy + tamoxifen CONTRAINDICATED** entire pregnancy (teratogenic); - **HER2 targeted (trastuzumab) CONTRAINDICATED** entire pregnancy (oligohydramnios); - **Radiation deferred to post-delivery**; - **2nd + 3rd trimester**: - Anthracycline + cyclophosphamide (AC) chemotherapy can be given (data show safe for fetus); - Taxanes (paclitaxel) OK 2nd-3rd; - **Avoid chemo within 3-4 wk of delivery** (neonatal cytopenia); - **6) Termination consideration**: rarely needed unless very early Ist trimester + need for immediate teratogenic Tx, no longer routinely recommended given good outcomes with adapted Tx; (7) **Delivery**: full-term preferred; (8) **Post-delivery**: complete standard treatment — endocrine, HER2 targeted, RT; (9) **Lactation**: usually safe to feed from unaffected side; avoid lactation during chemo; (10) **Fetal monitoring**: growth scans, NST, anomaly scan timing; (11) **Mental health**, support; (12) **Genetic counseling + future planning**; (13) **Fertility consult**: many young patients want options preserved; (14) **Survivorship including ongoing breast surveillance + late effects + psychosocial**; (15) **Outcomes**: comparable to non-PABC stage-for-stage when treated appropriately

---

PABC integrative care: multidisciplinary inc. MFM. Trimester-based Tx — surgery anytime; chemo 2nd/3rd OK (anthracycline + taxane), CONTRA in 1st; tamoxifen + trastuzumab CONTRA entire pregnancy; RT post-delivery. Delivery full-term preferred. Outcomes comparable.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'pathology'
  and scenario = 'Multidisciplinary integrative pathology — patient with breast cancer + pregnancy + complex management; multidisciplinary tumor board including OB-GYN + medical onc + breast + pathology + maternal-fetal medicine';

update public.mcq_questions
set choices = '[{"label":"A","text":"Random"},{"label":"B","text":"Cancer of Unknown Primary (CUP) Integrative Care"},{"label":"C","text":"Random"},{"label":"D","text":"Skip"},{"label":"E","text":"Refuse"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Cancer of Unknown Primary (CUP) Integrative Care: (1) **Definition**: histologically confirmed metastatic cancer without identifiable primary site after appropriate workup; ~ 2-5% of cancers; (2) **Pathology workup** (most important step — increasingly identifies primary or actionable target): - **Histology**: well-differentiated adenocarcinoma, poorly differentiated, squamous, neuroendocrine, undifferentiated → broad categories; - **IHC** algorithm (extensive, site-tailored): - CK7 + CK20 + (lung, breast, pancreas, biliary, urothelial, gastric); - CK7 + CK20 - (lung, breast, biliary, thyroid, salivary); - CK7 - CK20 + (colorectal); - CK7 - CK20 - (HCC, RCC, prostate, squamous, neuroendocrine); - Site-specific: TTF-1 (lung, thyroid), GATA3 (breast, urothelial), PAX8 (Müllerian, thyroid, RCC), CDX2 (GI), p40 (squamous), synapto/chromo (neuroendocrine), SALL4 (germ cell), HepPar1 (HCC), arginase (HCC), RCC marker, NKX3.1 (prostate), MUC1, MUC2, others; - **Molecular**: comprehensive NGS for actionable mutations + tissue-of-origin classifier (CancerType ID, CUP-AI-Dx); MSI/dMMR + TMB + PD-L1; (3) **Imaging**: CT chest/abdomen/pelvis; mammogram (women); upper + lower endoscopy if GI suspicion; specific imaging by histology + IHC; PET-CT useful selected; (4) **Favorable CUP subsets (treat like primary)**: - Women with adenocarcinoma in axillary nodes → treat as breast; - Women with peritoneal carcinomatosis (papillary serous + psammoma + PAX8+/WT1+) → ovarian/Müllerian; - Men with squamous in cervical nodes → treat as head/neck; - Inguinal nodes squamous → genital/anal; - Single site → consider primary; - Neuroendocrine — well-diff treat like NET, poorly diff like SCLC; - Germ cell features (midline mass young male) — test/treat like germ cell; (5) **Treatment**: - **Site-specific** when subset identifies; - **Empiric chemo** (platinum + taxane historical) — limited benefit; - **Targeted therapy if actionable mutations** — increasingly important — agnostic FDA approvals: **larotrectinib/entrectinib (NTRK fusions), pembrolizumab (MSI-H/dMMR or TMB ≥ 10), dabrafenib + trametinib (BRAF V600E), selpercatinib (RET), etc.**; - **Immunotherapy + chemo** — CUPISCO trial — molecular-guided improved outcomes; (6) **Multidisciplinary**: medical onc + pathology + radiology + molecular tumor board + palliative + supportive; (7) **Palliative integration early** — symptom management + goals of care + advance care planning; (8) **Patient + family**: communication of uncertainty, emotional support, second opinions, clinical trial discussion; (9) **Equity**: access to comprehensive molecular workup + targeted therapy + trials

---

CUP integrative care: pathology IHC algorithm + molecular (NGS + tissue-of-origin classifier) → identify favorable subset or actionable target. Treat per primary when identified. Tissue-agnostic targeted therapy (NTRK/MSI-H/BRAF/RET). CUPISCO molecular-guided. Palliative early.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'pathology'
  and scenario = 'Integrative palliative care + pathology — patient with advanced metastatic cancer of unknown primary (CUP) — workflow + multidisciplinary + targeted therapy + supportive care + goals of care';

update public.mcq_questions
set choices = '[{"label":"A","text":"Random"},{"label":"B","text":"Clinical Lab Role in Public Health Surveillance"},{"label":"C","text":"Random"},{"label":"D","text":"Skip"},{"label":"E","text":"Refuse"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Clinical Lab Role in Public Health Surveillance: (1) **Outbreak detection + response**: - **Real-time reporting** of reportable diseases (TB, measles, meningococcal disease, HIV, hepatitis, foodborne, STDs, novel emergencies) — automated electronic laboratory reporting (ELR) to public health; - **Cluster detection** algorithms (CDC + state systems) on lab data; - **Whole-genome sequencing** (WGS) for foodborne outbreaks (PulseNet) — supplements/replaces PFGE; (2) **Antimicrobial resistance (AMR) surveillance** (One Health priority): - **WHO GLASS** global; - National systems track key resistance (MRSA, VRE, CRE/carbapenem-resistant Enterobacterales, MDR/XDR-TB, MDR Gonorrhea, candida auris, drug-resistant malaria); - **Clinical microbiology labs essential** — submit isolates, AST data; (3) **Emerging + re-emerging pathogen detection**: - **COVID-19 pandemic** demonstrated critical lab role — high-throughput PCR, variant tracking (WGS — GISAID), serology, antigen testing; - **Mpox, Marburg, Ebola** preparedness; - **Avian influenza H5N1** — One Health (animal + human + environment); - **Antimicrobial-resistant Candida auris** monitoring; (4) **Public health labs** (state + reference) — confirmatory + outbreak + characterization + capacity-building; (5) **Population health** initiatives: - Cancer registries (population incidence + outcomes); - Newborn screening (PKU, sickle cell, etc.); - HIV testing (universal); - Cervical cancer (HPV + cytology); - Hepatitis C screening universal adult; - LDL/A1C/BP population-level chronic disease; (6) **Equity considerations**: - Disparities in screening access, diagnosis, treatment — health equity goals; - Reduce disparities through accessible testing + culturally competent outreach; (7) **Epidemic preparedness**: - **Laboratory Response Network (LRN)** US — tiered lab capability for biosafety + bioterror; - Stockpile reagents; - Surge capacity testing; - Workforce training; - Specimen submission protocols + transport (Cat A/B); (8) **Data integration**: - **Electronic lab reporting (ELR)** + HL7/FHIR standards; - **Public health informatics** infrastructure; - Privacy + ethics + data sharing; (9) **International collaboration**: WHO, ECDC, CDC, IHR (International Health Regulations) — outbreak coordination; (10) **Lessons from COVID + Ebola + Zika**: investment in lab capacity + workforce + surveillance + equity essential

---

Clinical labs public health: ELR + outbreak detection + WGS (PulseNet); AMR surveillance (WHO GLASS); emerging pathogens (COVID/mpox/H5N1); newborn screening + cancer registries; equity. LRN preparedness. International collaboration (WHO, IHR). Workforce + capacity investment.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'pathology'
  and scenario = 'Integrative pathology — public health surveillance: lab data role in identifying outbreaks + emerging pathogens + antimicrobial resistance + population health + epidemic preparedness';

update public.mcq_questions
set choices = '[{"label":"A","text":"Minimal change"},{"label":"B","text":"Focal Segmental Glomerulosclerosis (FSGS)"},{"label":"C","text":"Membranous"},{"label":"D","text":"IgA"},{"label":"E","text":"Lupus"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Focal Segmental Glomerulosclerosis (FSGS): (1) **Histology**: segmental (affecting only portion of glomerulus) + focal (involves only some glomeruli) sclerosis; podocyte injury; (2) **Subtypes (Columbia classification)**: - **Tip lesion** (best prognosis); - **Perihilar** (often secondary, hyperfiltration); - **Cellular**; - **Collapsing** (worst — HIVAN, APOL1, SARS-CoV-2, drug); - **NOS** (not otherwise specified); (3) **Primary vs secondary** (critical distinction): - **Primary (idiopathic)**: circulating permeability factor (suPAR? others under research); diffuse foot process effacement on EM; nephrotic syndrome; often steroid-responsive; - **Secondary**: maladaptive (obesity, reduced nephron number, reflux, HTN), drug (heroin, lithium, anabolic steroids, bisphosphonate, IFN), infection (HIV, parvovirus, SARS-CoV-2), genetic; subnephrotic proteinuria; focal foot process effacement; (4) **Genetic FSGS**: NPHS1 (nephrin), NPHS2 (podocin), WT1 (Denys-Drash), TRPC6, INF2, ACTN4 (autosomal dominant), COL4A3/4/5 (Alport — overlap), MYO1E; **APOL1** high-risk variants — African ancestry — increased FSGS, HIVAN, lupus nephritis collapsing, CKD progression risk; (5) **IF**: nonspecific IgM + C3 entrapment in sclerotic segments; full house argues for lupus; (6) **EM**: diffuse foot process effacement in primary; less in secondary; (7) **Treatment**: - **Primary FSGS**: corticosteroids first-line (high-dose prednisone ≥ 4 mo); steroid-resistant — calcineurin inhibitors (cyclosporine, tacrolimus); rituximab considered; **MMF, ACTH, abatacept** in refractory; **plasmapheresis** for recurrent FSGS post-transplant; - **Secondary FSGS**: address underlying (weight loss, RAS blockade, treat HIV — TAF/PrEP, drugs); - **SGLT2 inhibitors** added for proteinuric CKD (DAPA-CKD); - **Sparsentan** (dual endothelin + AT1R antagonist — DUPLEX trial) approved 2023 FSGS; (8) **Genetic testing** in pediatric + adult selected — guides treatment (genetic forms don''t respond to immunosuppression typically); (9) **Recurrence** in transplant ~ 30% primary — plasmapheresis ± rituximab; (10) **Multidisciplinary**

---

FSGS: segmental sclerosis + podocyte injury. Columbia subtypes (tip, perihilar, cellular, collapsing, NOS). Primary (steroid-responsive, diffuse FPE) vs secondary (maladaptive, focal FPE) vs genetic. APOL1 high-risk variants. Sparsentan + SGLT2 added. Genetic testing selected.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'pathology'
  and scenario = 'ผู้ป่วยอายุ 35 ปี — nephrotic syndrome (proteinuria 6 g/d + edema + hypoalbuminemia + hyperlipidemia) → kidney biopsy: segmental sclerosis affecting < 50% glomeruli with podocyte foot process effacement on EM; IF: nonspecific IgM/C3 entrapment; APOL1 high-risk variants';

update public.mcq_questions
set choices = '[{"label":"A","text":"Minimal change"},{"label":"B","text":"Membranous Nephropathy (MN)"},{"label":"C","text":"FSGS"},{"label":"D","text":"IgA"},{"label":"E","text":"ATN"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Membranous Nephropathy (MN): (1) **Histology**: thickened GBM, ''spikes'' on Jones methenamine silver (basement membrane reaction around subepithelial deposits — represents new BM forming around immune deposits); (2) **IF**: diffuse granular IgG + C3 along GBM (IgG4 subclass dominant in primary); (3) **EM (staging — Ehrenreich-Churg)**: stage I — subepithelial deposits; II — spikes; III — incorporation; IV — resorption + irregular GBM; (4) **Primary (idiopathic) MN — ~ 80%**: autoimmune to podocyte antigens: - **PLA2R (M-type phospholipase A2 receptor) — ~ 70-80%** — serum + tissue IHC; biomarker for diagnosis + monitoring response; - **THSD7A** ~ 3% — second target; - **Newer antigens**: NELL1 (~ 5-10% — malignancy-associated MN), exostosin 1/2 (autoimmune), semaphorin 3B (pediatric), neural EGFL-like 1, protocadherin 7, HTRA1, others — actively discovered; (5) **Secondary MN — ~ 20%** — workup essential: - **Infection**: hepatitis B (children especially), syphilis, hepatitis C, schistosomiasis, malaria; - **Malignancy** (10% adult > 60 — especially NELL1+ — lung, colorectal, prostate); - **Drugs**: NSAIDs, gold, mercury, penicillamine, captopril, anti-TNF; - **Autoimmune**: lupus (Class V), RA, Sjögren — IgG1+2+3 mixed (not pure IgG4), C1q present (vs primary); - **Allograft**: de novo or recurrent; (6) **Workup**: - Serum anti-PLA2R + anti-THSD7A; - Hepatitis B + C, HIV, syphilis, ANA, complement; - Age-appropriate cancer screening; - Renal biopsy with IF + EM (immunoperoxidase for antigens); (7) **Treatment**: - **Conservative**: RAS blockade + statin + sodium restriction + DVT prophylaxis (high VTE risk — nephrotic + albumin < 2.5; nephrotic-range proteinuria); SGLT2 inhibitors; - **Immunosuppression** if high-risk (persistent nephrotic, declining eGFR): - **Rituximab** — first-line per KDIGO 2021 (MENTOR trial — superior to cyclosporine); - **Cyclophosphamide + steroids** (Ponticelli regimen) alternative; - **Calcineurin inhibitors** option but more relapse; - **Combination** for high-risk; - **Anti-PLA2R titer-guided** response monitoring; - **B-cell depletion antigen-specific therapies** emerging; (8) **Remission**: 30% spontaneous remission in primary — observation high-risk patients

---

MN: subepithelial deposits + spikes on silver; granular IgG/C3 IF. Primary ~80% — PLA2R, THSD7A, NELL1 (cancer-assoc), exostosins (autoimmune). Secondary: HBV/syphilis/malignancy/drugs/lupus class V. Rituximab first-line (MENTOR); anti-PLA2R titer-guided.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'pathology'
  and scenario = 'ผู้ป่วยอายุ 60 ปี — nephrotic syndrome → biopsy: thickened GBM with subepithelial deposits ''spike'' on silver stain; IF: granular IgG + C3 along GBM; IHC: PLA2R+ on glomeruli; serum anti-PLA2R antibody positive';

update public.mcq_questions
set choices = '[{"label":"A","text":"GN"},{"label":"B","text":"Acute Tubular Necrosis (ATN) — Pathology + Management"},{"label":"C","text":"Vasculitis"},{"label":"D","text":"Refuse"},{"label":"E","text":"Skip"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Acute Tubular Necrosis (ATN) — Pathology + Management: (1) **Causes**: - **Ischemic**: sepsis, hypovolemia, hypotension, cardiac arrest, cardiogenic shock; - **Nephrotoxic**: aminoglycosides, vancomycin, contrast (less common now with iso-osmolar), chemo (cisplatin), pigment (rhabdomyolysis — myoglobin; hemolysis — hemoglobin), light chains (myeloma cast nephropathy distinct), heavy metals, ethylene glycol; (2) **Histology**: tubular epithelial cell injury, flattening, loss of brush border, sloughing into lumen, apoptosis/necrosis, denuded basement membrane, regenerative epithelium (mitoses), intratubular debris, no significant inflammation; preservation of glomeruli (early); (3) **Urinary findings**: muddy brown (epithelial cell) granular casts, isosthenuria (urine osm ~ serum osm — concentrating defect), FENa > 2% (lost concentrating ability vs pre-renal < 1%); FEUrea > 50%; (4) **AKI staging (KDIGO)** by Cr rise + urine output; (5) **Differential**: pre-renal (FENa < 1%, hyaline casts, responds to fluid), post-renal (obstruction — hydro on US), other intrinsic (GN, AIN, vascular); (6) **Acute Interstitial Nephritis (AIN) — distinct entity**: - Drug (PPIs, NSAIDs, antibiotics — beta-lactams, sulfa, vancomycin, fluoroquinolones, **immune checkpoint inhibitors major emerging cause**), infection, autoimmune; - Histology — interstitial inflammation + edema + eosinophils + tubulitis; - Urinalysis WBC + WBC casts + eosinophiluria (insensitive); rash + fever (less common now); - Treatment: stop offending drug + steroids if persistent + checkpoint AIN; (7) **Treatment ATN**: - **Address cause**: optimize hemodynamics, withdraw nephrotoxins, treat infection; - **Supportive**: AKI complications — volume management, hyperkalemia, acidosis, uremic complications; - **No specific therapy** to reverse ATN; recovery via tubular regeneration; - **Renal replacement therapy (RRT)** indications: refractory hyperK, acidosis, volume, uremic complications, certain intoxications (AEIOU); modalities CRRT vs IHD in unstable ICU; - **Pharmacology adjustment** for renal clearance; (8) **Recovery**: oliguria → diuresis phase → recovery — most regain function; some progress to CKD; AKI is independent risk for future CKD; (9) **Prevention**: hydration, avoiding nephrotoxins, sepsis bundles, smart-pump CT contrast protocols, drug monitoring (vancomycin AUC, aminoglycoside)

---

ATN: ischemic or nephrotoxic; muddy brown casts + FENa>2% + isosthenuria. Histology: tubular sloughing + regen. KDIGO AKI staging. AIN distinct (eos, ICI emerging cause). Tx: address cause + supportive + RRT for AEIOU; no specific reversal. Prevention key.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'pathology'
  and scenario = 'ผู้ป่วย ICU + AKI; urine: muddy brown granular casts; FENa > 2%; biopsy if obtained: tubular epithelial sloughing + flattened cells + apoptosis + regenerative changes; การวินิจฉัยและการรักษา';

update public.mcq_questions
set choices = '[{"label":"A","text":"Pseudocyst"},{"label":"B","text":"Intraductal Papillary Mucinous Neoplasm (IPMN) — Pancreatic Cyst Workup"},{"label":"C","text":"Cancer"},{"label":"D","text":"Skip"},{"label":"E","text":"Refuse"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Intraductal Papillary Mucinous Neoplasm (IPMN) — Pancreatic Cyst Workup: (1) **Pancreatic cystic lesions (PCLs) — major categories**: - **Pseudocyst** (post-pancreatitis, no epithelium); - **Serous cystadenoma (SCA)** — benign, microcystic + central scar; - **Mucinous Cystic Neoplasm (MCN)** — pre-malignant, women, ovarian-type stroma; - **IPMN** (this case) — pre-malignant, main-duct + branch-duct + mixed; - **Solid pseudopapillary neoplasm** (young women); - **PNET cystic**; (2) **IPMN subtypes**: - **Main-duct IPMN (MD-IPMN)**: high malignant potential — usually surgical; - **Branch-duct IPMN (BD-IPMN)**: lower risk; - **Mixed**; - Pathology subtypes: gastric (most common BD-IPMN, low risk), intestinal (main duct, MUC2+, colloid carcinoma association), pancreatobiliary (high-grade, MUC1+), oncocytic (separate entity now); (3) **Workup (revised Kyoto 2024 + Fukuoka guidelines)**: - **High-risk stigmata** → resect: enhancing mural nodule ≥ 5 mm, MPD ≥ 10 mm, jaundice; - **Worrisome features** → consider EUS + biopsy: cyst ≥ 3 cm, thickened wall, MPD 5-9 mm, mural nodule < 5 mm, abrupt MPD change, lymphadenopathy, CA19-9 elevated, growth ≥ 5 mm/2 yr, new diabetes; - Surveillance per size + features; (4) **Cyst fluid analysis (EUS-FNA)**: - **CEA**: > 192 ng/mL suggests mucinous; very high (> 500) more likely mucinous neoplasm but not pre-malignant grading; - **Amylase**: high in pseudocyst + IPMN (connect to duct); low in MCN/SCA (don''t communicate); - **Glucose**: low (< 50 mg/dL) in mucinous; normal in non-mucinous (better than CEA in some studies); - **Cytology**: mucinous epithelium, atypia (limited sensitivity); - **Molecular**: KRAS + GNAS mutations highly suggestive IPMN (GNAS specific); KRAS + mucinous in MCN; VHL in SCA; CTNNB1 + solid pseudopapillary; - **String sign** of mucin; (5) **Management**: surgical resection for high-risk features; surveillance for low-risk (MRI/EUS); (6) **Resected pathology**: assess grade — low-grade dysplasia → high-grade → invasive carcinoma; invasive component changes prognosis substantially — surgical staging; (7) **Multidisciplinary**: GI + pancreatic surgery + radiology + pathology + medical onc; (8) **Hereditary**: PJS (STK11), familial pancreatic cancer — surveillance protocols

---

IPMN: cyst fluid CEA + amylase + glucose + cytology + KRAS/GNAS molecular. MD vs BD subtypes + histologic types. Fukuoka/Kyoto: high-risk stigmata → resect; worrisome → EUS+biopsy. Grade matters (LGD → HGD → invasive). Multidisciplinary; hereditary considerations.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'pathology'
  and scenario = 'ผู้ป่วยอายุ 60 ปี — pancreatic cyst → EUS-FNA + cyst fluid analysis: CEA 600 ng/mL + amylase low + cytology: mucinous epithelial cells with mild atypia; imaging: branch-duct dilatation + mural nodule; molecular cyst fluid: KRAS + GNAS mutations; การวินิจฉัย';

update public.mcq_questions
set choices = '[{"label":"A","text":"Hepatitis"},{"label":"B","text":"Primary Biliary Cholangitis (PBC, formerly PBC = primary biliary cirrhosis)"},{"label":"C","text":"PSC"},{"label":"D","text":"Refuse"},{"label":"E","text":"Hospice"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Primary Biliary Cholangitis (PBC, formerly PBC = primary biliary cirrhosis): (1) **Pathophysiology**: autoimmune destruction of small + medium intrahepatic bile ducts → chronic cholestasis → fibrosis → cirrhosis; women > men 10:1; middle-aged; (2) **Clinical**: fatigue + pruritus (mainstay symptoms — significant impact QoL); jaundice late; sicca symptoms (Sjögren overlap); osteoporosis; metabolic bone disease; hyperlipidemia (cholesterol) without increased CV; (3) **Diagnostic criteria** (2 of 3): - **ALP elevated ≥ 1.5× ULN ≥ 24 wk**; - **AMA (anti-mitochondrial Ab) positive** (M2 specific — anti-PDC-E2) ≥ 1:40 (95% PBC); - **Histologic features** typical of PBC (florid duct lesion); (4) **AMA-negative PBC** ~ 5% — anti-sp100 + anti-gp210 antinuclear Abs may help; (5) **Histology (Ludwig staging I-IV)**: - **Stage 1**: portal inflammation + florid duct lesion (CNSC + granulomas); - **Stage 2**: periportal + ductular proliferation; - **Stage 3**: bridging fibrosis; - **Stage 4**: cirrhosis; (6) **Differential**: - **Primary Sclerosing Cholangitis (PSC)**: men > women, IBD association, p-ANCA, large duct strictures (MRCP — beaded), ''onion-skin'' fibrosis; **no specific treatment** (UDCA not endorsed); cholangiocarcinoma + colorectal cancer surveillance; - **Autoimmune hepatitis** overlap (PBC-AIH overlap) — interface hepatitis + ALT high; - **IgG4-related disease** cholangiopathy — high IgG4 + storiform fibrosis; - **Drug-induced + others**; (7) **Treatment**: - **UDCA (ursodeoxycholic acid)** 13-15 mg/kg/d — first-line, improves biochemistry + survival + delays transplant — RESPONSE is critical (POISE/Toronto criteria); - **Obeticholic acid (OCA, Ocaliva)** — FXR agonist, second-line for UDCA-incomplete responders; - **Bezafibrate, fenofibrate** — fibrates — add-on UDCA-incomplete responders (BEZURSO trial); - **Seladelpar, elafibranor** — PPAR delta agonists — approved 2024-2025 for UDCA-inadequate response; - **Pruritus management**: cholestyramine, rifampin, naltrexone, sertraline, **ileal bile acid transporter (IBAT) inhibitor (linerixibat)** for chronic pruritus; - **Symptomatic**: fatigue (modafinil sometimes); osteoporosis (Ca, vit D, bisphosphonate); fat-soluble vitamins; (8) **Liver transplant** — end-stage cirrhosis or refractory pruritus; can recur post-transplant; (9) **Multidisciplinary**: hepatology + transplant + rheum + dietitian

---

PBC: autoimmune small bile duct destruction; women, AMA+ (PDC-E2), ↑ALP. Florid duct lesion + granulomas; Ludwig stages. UDCA 1st; OCA, bezafibrate, seladelpar/elafibranor (new) for incomplete responders. Pruritus management (rifampin, naltrexone, IBAT). Distinct from PSC.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'pathology'
  and scenario = 'ผู้ป่วยอายุ 50 ปี — fatigue + pruritus + jaundice; labs: ALP markedly elevated + GGT high + AMA positive (titer 1:160) + IgM elevated; biopsy: chronic non-suppurative cholangitis + bile duct destruction + lymphoplasmacytic + granulomas; การวินิจฉัย';

update public.mcq_questions
set choices = '[{"label":"A","text":"HCC"},{"label":"B","text":"Cholangiocarcinoma — Pathology + Molecular"},{"label":"C","text":"Pancreatic ca"},{"label":"D","text":"Refuse"},{"label":"E","text":"Skip"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Cholangiocarcinoma — Pathology + Molecular: (1) **Anatomic classification**: - **Intrahepatic cholangiocarcinoma (iCCA)** — small + large duct; - **Perihilar (Klatskin)** — most common, Bismuth-Corlette types I-IV; - **Distal extrahepatic** (distal bile duct); - **Gallbladder carcinoma** — separate entity but related; (2) **Histology**: glandular structures + abundant desmoplastic stroma + perineural + lymphovascular invasion; (3) **IHC**: CK7+, CK19+, CK20 variable (less in iCCA), CDX2 +/-, MUC1+; HepPar1-, glypican3- (distinguishes from HCC); CK20+/CDX2+ may suggest GI mets (differential); (4) **Molecular (key for targeted therapy)** — depends on subtype: - **iCCA**: - **IDH1/2 mutations** ~ 20% — **ivosidenib** (ClarIDHy IDH1 inhibitor) approved; enasidenib (IDH2) under study; - **FGFR2 fusions/rearrangements** ~ 10-15% — **pemigatinib (FIGHT-202), futibatinib (FOENIX-CCA2), infigratinib** approved; resistance via FGFR2 kinase mutations; - **BRAF V600E** ~ 5% — dab+tram; - **HER2 (ERBB2) amplification** — trastuzumab + pertuzumab, T-DXd; - **NTRK fusions** rare — larotrectinib/entrectinib; - **MSI-H/dMMR** — pembrolizumab; - **Perihilar/distal**: KRAS, TP53, SMAD4, ARID1A; less actionable; - **Gallbladder**: TP53, KRAS, HER2; (5) **Risk factors**: PSC, choledochal cysts, hepatolithiasis, **liver flukes Opisthorchis viverrini + Clonorchis sinensis** (endemic SE Asia — Thailand high incidence), chronic hepatitis B/C, NAFLD, biliary intraepithelial neoplasia; (6) **Workup**: CT/MRI MRCP/ERCP; tumor markers CA 19-9, CEA; tissue biopsy + brushings + molecular profiling; staging laparoscopy for advanced iCCA; (7) **Treatment**: - **Resectable**: surgical resection with R0 margin; adjuvant capecitabine (BILCAP); - **Locally advanced**: chemoRT or systemic; transplant for selected unresectable iCCA (UNOS criteria); - **Advanced/metastatic**: - **Frontline**: **durvalumab + gemcitabine + cisplatin** (TOPAZ-1) or **pembrolizumab + gem-cis** (KEYNOTE-966); - **Second-line**: matched targeted therapy if mutations + FOLFOX (ABC-06); - **Later lines**: targeted-specific (pemi, futi, ivosid, dab-tram, T-DXd, pembro MSI-H); (8) **Multidisciplinary**: GI/HPB surgery + hepatology + medical onc + RT + IR + pathology; (9) **Thailand context** — Opisthorchis-related cholangiocarcinoma — northeast region — public health programs

---

Cholangiocarcinoma: iCCA vs perihilar vs distal vs GB. CK7+/CK19+; HepPar-. iCCA molecular: IDH1 (ivosidenib), FGFR2 fusions (pemigatinib/futibatinib), BRAF, HER2, NTRK, MSI-H. Risk: PSC, choledochal cysts, liver flukes (Thailand). Frontline durva+gem-cis (TOPAZ-1).'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'pathology'
  and scenario = 'ผู้ป่วยอายุ 50 ปี post-cholecystectomy — biopsy bile duct mass: glandular structures with abundant desmoplastic stroma + perineural invasion; IHC: CK7+ CK19+ CK20- TTF1- CDX2- HepPar1- glypican3-; molecular: IDH1 + FGFR2 fusion analyzed';

update public.mcq_questions
set choices = '[{"label":"A","text":"Lung ca"},{"label":"B","text":"Malignant Pleural Mesothelioma (MPM)"},{"label":"C","text":"TB"},{"label":"D","text":"Hospice only"},{"label":"E","text":"Refuse"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Malignant Pleural Mesothelioma (MPM): (1) **Etiology**: **asbestos exposure** primary (long latency 20-50 yr); other — erionite (Turkey), radiation, SV40 (debated), BAP1 germline mutation (familial mesothelioma); pleural >> peritoneal > pericardial > tunica vaginalis; (2) **Histology subtypes** (matter prognostically + treatment): - **Epithelioid** ~ 70% (best prognosis); - **Sarcomatoid** ~ 15% (worst); - **Biphasic** (both); - **Desmoplastic** variant of sarcomatoid; - WHO 2021 includes **mesothelioma in situ** (early lesion concept); (3) **Histology**: tubulopapillary, solid, trabecular, deciduoid, lymphohistiocytoid, transitional; spindle sarcomatoid; (4) **IHC (panel essential — distinguish from adenocarcinoma metastatic to pleura — most important DDx)**: - **Mesothelial markers (positive in meso)**: calretinin (high sens + spec), WT1, **D2-40 (podoplanin)**, CK5/6, cytokeratin (CK7+/CK20- typical), mesothelin, HEG1, **claudin 15+**; - **Adenocarcinoma markers (negative in meso)**: CEA, BerEP4, MOC31, claudin-4, TTF-1 (lung), GATA3 (breast/urothelial), PAX8 (Müllerian/RCC); - Need ≥ 2 mesothelial + ≥ 2 negative adenoca to support meso (per IMIG); (5) **Distinguishing benign mesothelial reactive vs malignant (challenging on cytology + small biopsies)**: - **BAP1 IHC loss** + **MTAP loss** (CDKN2A/p16 surrogate) + **p16/CDKN2A homozygous deletion by FISH** — support malignancy; - **MTAP/BAP1 dual IHC reliable**; - **5-hmC loss**; - Definitive often requires invasion seen on biopsy; (6) **Molecular**: BAP1 loss/mutation ~ 60% (germline + somatic — Family BAP1 syndrome — meso + uveal melanoma + RCC + others); NF2, TP53, SETD2; (7) **Staging**: TNM 8th ed; CT + PET + diffusion MRI; surgical staging laparoscopy in select; (8) **Treatment**: - **Systemic frontline**: **nivolumab + ipilimumab** (CheckMate 743) — superior to chemo for non-epithelioid + comparable epithelioid; chemo (cisplatin + pemetrexed ± bevacizumab) historical; chemo + nivolumab combo; - **Surgical resection**: extended pleurectomy/decortication or extra-pleural pneumonectomy (less favored) — multimodal trimodal therapy (chemo + surgery + RT) for early-stage; - **Symptomatic**: pleurodesis, indwelling pleural catheter for recurrent effusion; (9) **Multidisciplinary**: thoracic surg + medical onc + RT + path; (10) **Compensation + occupational** — many countries support patients

---

MPM: asbestos; epithelioid/sarcomatoid/biphasic. IHC: calretinin/WT1/D2-40/CK5/6+; CEA/BerEP4/TTF1-. BAP1 loss + MTAP loss + p16/CDKN2A homozygous deletion distinguish from reactive. Nivo+ipi frontline (CheckMate 743). BAP1 germline syndrome.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'pathology'
  and scenario = 'ผู้ป่วยอายุ 70 ปี smoker + asbestos exposure 40 yr ago — pleural thickening + effusion; biopsy: epithelioid + spindle cells; IHC: calretinin+, WT1+, D2-40+, CK5/6+, BAP1 LOSS, MTAP loss; CEA- BerEP4- TTF1-; FISH: CDKN2A homozygous deletion; การวินิจฉัย';

update public.mcq_questions
set choices = '[{"label":"A","text":"Cortisol-secreting"},{"label":"B","text":"Pheochromocytoma + Paraganglioma (PPGL)"},{"label":"C","text":"Refuse"},{"label":"D","text":"Skip"},{"label":"E","text":"Random"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Pheochromocytoma + Paraganglioma (PPGL): (1) **Origin**: chromaffin cells of adrenal medulla (pheochromocytoma) or extra-adrenal sympathetic/parasympathetic paraganglia (paraganglioma); (2) **Clinical**: classic triad — episodic headache + palpitations + sweating; sustained or paroxysmal hypertension; pallor; orthostatic; metabolic; some asymptomatic incidentaloma; (3) **Histology**: ''Zellballen'' (cell balls) — nests of polygonal chromaffin cells surrounded by capillary network; cytoplasm fine granular (catecholamines); pleomorphism doesn''t predict malignancy; (4) **IHC**: chromogranin A+, synaptophysin+, GATA3+, tyrosine hydroxylase+; **sustentacular cells S100+ (surround the nests)**; (5) **Biochemistry (most important for diagnosis)**: - **Plasma free metanephrines + normetanephrines** OR **24-h urine fractionated metanephrines** — sensitivity > 95%; - Pre-analytics critical (supine, avoid stress, no medications interfering); - **Chromogranin A** elevated; - **Methoxytyramine** (dopamine metabolite) — head/neck paragangliomas + SDH-related; (6) **Localization**: CT/MRI for primary; **123I-MIBG scintigraphy + 68Ga-DOTATATE PET** for staging; (7) **All PPGL — consider malignant potential** (no benign — replaced by ''metastatic risk''): - **PASS** (Pheochromocytoma of Adrenal Scaled Score) + **GAPP** + **COPPS**; - Definition of malignancy = metastasis (lymph node, bone, lung, liver, brain); ~ 10-15% metastatic; (8) **Genetic — 40% PPGL have germline mutation — universal genetic testing recommended**: - **Cluster 1 (pseudohypoxia)**: SDHx (SDHA, SDHB — adverse, malignant risk, methoxytyramine; SDHC, SDHD, SDHAF2), VHL, EPAS1 (HIF2A), FH, PHD2; - **Cluster 2 (kinase signaling)**: RET (MEN2), NF1, TMEM127, MAX, HRAS; - **Cluster 3 (Wnt)**: CSDE1, MAML3 fusions; (9) **Pre-operative management critical** (avoid hypertensive crisis): - **Alpha-blockade FIRST** (phenoxybenzamine or doxazosin) 7-14 d; - **Volume expansion** + high salt diet; - Beta-blockade **only after** alpha-blockade (avoid unopposed alpha → hypertensive crisis); - Calcium channel blocker adjunct; (10) **Treatment**: - **Surgical resection** (laparoscopic for most adrenal); - **Metastatic**: **lutetium-177 DOTATATE (PRRT)** approved; sunitinib, mTOR inhibitors, CVD chemo (cyclophos-vincristine-DTIC), 131I-MIBG (Azedra) for MIBG-avid; HIF-2α inhibitor **belzutifan** approved for VHL-related; - **Surveillance**: lifelong — metanephrines, imaging; (11) **Family screening** for germline carriers

---

Pheo/PGL: Zellballen + chromog/synapto/GATA3+; sustentacular S100+. Plasma/urine metanephrines diagnostic. MIBG + DOTATATE imaging. 40% germline — universal genetic testing (SDHx/VHL/RET/NF1/MAX). Alpha-blockade FIRST pre-op. PRRT (177Lu-DOTATATE) metastatic. Belzutifan VHL.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'pathology'
  and scenario = 'ผู้ป่วยอายุ 40 ปี — episodic hypertension + headaches + sweating + palpitations; plasma metanephrines elevated; CT: adrenal mass; biopsy (rarely needed): nests of chromaffin cells ''Zellballen'' pattern; IHC: chromogranin+, synaptophysin+, S100+ (sustentacular); molecular: SDHB testing';

update public.mcq_questions
set choices = '[{"label":"A","text":"TTP"},{"label":"B","text":"Immune Thrombocytopenic Purpura (ITP) — Adult"},{"label":"C","text":"DIC"},{"label":"D","text":"MDS"},{"label":"E","text":"Refuse"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Immune Thrombocytopenic Purpura (ITP) — Adult: (1) **Diagnosis** — **diagnosis of exclusion**: isolated thrombocytopenia + no other cause + appropriate clinical (no hepatosplenomegaly, no LAD, no systemic illness); peripheral smear shows large platelets without schistocytes, normal RBCs/WBCs; (2) **Pathophysiology**: anti-platelet autoantibodies (often GPIIb/IIIa, Ib/IX) + T-cell dysregulation → enhanced platelet destruction + impaired production; (3) **Workup**: - CBC + smear + retic; - DAT (rule out Evans syndrome — AIHA + ITP); - HIV + HCV + H. pylori (treat if positive — can resolve ITP); - HBV before rituximab; - ANA (rule out lupus); - Quantitative immunoglobulins (CVID); - Thyroid (autoimmune common); - Anti-platelet Ab testing not routine (insensitive); - BM biopsy not required if classic presentation + atypical features (older, abnormal blood counts, persistent — selectively); (4) **Classification**: newly diagnosed (< 3 mo), persistent (3-12 mo), chronic (> 12 mo), refractory (failed splenectomy + others); (5) **Treatment** (ASH 2019, IWG 2020+): - **Asymptomatic with platelet ≥ 30K**: observation typically (no treatment threshold absolute); - **Platelet < 30K or bleeding**: - **First-line**: corticosteroids — dexamethasone 40 mg × 4 d (preferred — faster, less cumulative SE) vs prednisone 1 mg/kg taper; - **IVIG** (1-2 g/kg) — rapid rise, surgery, severe bleeding; - **Anti-D** (Rh-positive non-splenectomized — RhD+ adults — rare use now); - **Second-line**: - **TPO receptor agonists** (eltrombopag, romiplostim, **avatrombopag**) — increase production, durable, well-tolerated, growing first-line role in chronic; - **Rituximab** — anti-CD20; ~ 50-60% response; - **Splenectomy** — historically definitive, less common now due to thrombosis + infection risk; pre-op vaccines + lifelong consideration of vaccine adherence; - **Fostamatinib** (SYK inhibitor) — option chronic; - **Refractory**: combinations, rituximab, alemtuzumab; (6) **Bleeding management**: platelet transfusion (limited efficacy — antibodies still active), IVIG + steroids, antifibrinolytics, recombinant factor VIIa selected; (7) **Pregnancy ITP**: corticosteroids + IVIG (avoid splenectomy + rituximab + TPO unless essential — limited data); planning delivery; **neonatal alloimmune thrombocytopenia (NAIT)** distinct; (8) **Evans syndrome** (concurrent AIHA + ITP) consider; (9) **Hereditary thrombocytopenias** masquerade — MYH9, Bernard-Soulier — consider if unusual features; (10) **Multidisciplinary**: hematology + primary care + specialist for refractory

---

ITP: isolated low platelets, exclusion diagnosis; rule out HIV/HCV/H. pylori/lupus/Evans. Tx: observe if ≥30K + no bleed; otherwise dex 40 mg×4 d or pred + IVIG. 2nd line: TPO-R agonists (eltrombopag/avatrombopag), rituximab, splenectomy, fostamatinib. Pregnancy + Evans considerations.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'pathology'
  and scenario = 'ผู้ป่วยอายุ 30 ปี — incidental thrombocytopenia 25 + petechiae; CBC otherwise normal; smear: scant large platelets; BM normal megakaryocytes; การวินิจฉัยและการรักษา';

commit;
