-- ===============================================================
-- UPDATE chunk 2/8: pathology (25 questions)
-- ===============================================================

begin;

update public.mcq_questions
set choices = '[{"label":"A","text":"Single specialty"},{"label":"B","text":"Precision Medicine Program"},{"label":"C","text":"Random"},{"label":"D","text":"Refuse"},{"label":"E","text":"Single specialty"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Precision Medicine Program: (1) **Molecular tumor board (MTB)**: multidisciplinary — pathology + medical oncology + surgical oncology + radiation + radiology + clinical genetics + bioinformatics + pharmacy + research; (2) **Workflow**: tissue procurement + adequate quality + comprehensive molecular profiling (NGS panel, IHC, FISH) → interpretation → treatment recommendation → clinical trial matching; (3) **Cancer Genomics**: actionable mutations identification, targeted therapy selection, clinical trial eligibility, off-label use, expanded access; (4) **Hereditary cancer genetics**: germline testing + counseling + family screening; (5) **Liquid biopsy**: minimal residual disease (MRD), monitoring, recurrence detection, resistance evolution; (6) **Pharmacogenomics**: medication selection + dosing + safety; (7) **Specialized pathology**: synoptic reports, molecular sign-out, MDT participation; (8) **Quality + standards**: CAP, ASCO, NCCN guidelines; (9) **Data sharing + registries**: cBioPortal, OncoKB, AACR Project GENIE; (10) **Patient + family education**: complex information, shared decision-making; (11) **Equity considerations**: ensure access + reduce disparities; (12) **Research integration**: clinical trials, translational; (13) **Multidisciplinary infrastructure**: regular meetings, EMR integration, decision support; (14) **Modern**: precision medicine standard in oncology + expanding to other specialties (cardiology, neurology, immunology)

---

Precision medicine: molecular tumor board + multidisciplinary. Comprehensive profiling + interpretation + treatment selection. Hereditary + liquid biopsy + pharmacogenomics. Equity + research integration. Modern: standard in oncology + expanding.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'pathology'
  and scenario = 'Hospital implements precision medicine program + tumor board + multidisciplinary integration';

update public.mcq_questions
set choices = '[{"label":"A","text":"Random"},{"label":"B","text":"Pathology Workforce + Telepathology"},{"label":"C","text":"Random"},{"label":"D","text":"Refuse"},{"label":"E","text":"Avoid"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Pathology Workforce + Telepathology: (1) **Workforce shortage**: pathology + lab medicine global shortage; rural + developing country access challenges; aging workforce; (2) **Telepathology**: remote consultation, primary diagnosis (with validation), subspecialty consultation, education; reduces geographic disparity; (3) **Telepathology modes**: dynamic (real-time microscope), static (selected images), whole-slide image-based (most comprehensive); (4) **Subspecialty consultation**: rare or difficult cases referred to specialists globally; (5) **Global pathology**: capacity building in LMICs (low- middle-income countries); WHO + ASCP, etc.; (6) **Workforce expansion**: - More residency training positions; - Subspecialty fellowships; - Pathologist assistant + lab technologist; - Cytotechnologists + histotechnologists; (7) **Education + training**: simulation, online learning, webinars, virtual microscopy; (8) **Quality assurance** for telepathology: validation, consistency, lighting + color, network latency, security; (9) **Regulatory + licensing**: cross-state + cross-country; HIPAA + GDPR + local regulations; (10) **Equity + access**: ensure benefits reach underserved + LMIC; affordability; (11) **Multidisciplinary**: pathology + IT + administration + clinical + global health; (12) **Modern**: telepathology + global collaboration + AI + digital transformation expanding access

---

Pathology workforce + telepathology: shortage + access challenges. Telepathology expands access + subspecialty consultation. Global pathology capacity building. Workforce expansion + education. Quality + regulation. Equity. Modern: digital + collaboration transforming.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'pathology'
  and scenario = 'Hospital implements pathology workforce + telepathology + global pathology';

update public.mcq_questions
set choices = '[{"label":"A","text":"Single specialty"},{"label":"B","text":"Breast Cancer Pathology Integrative Care"},{"label":"C","text":"Random"},{"label":"D","text":"Single specialty"},{"label":"E","text":"Refuse"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Breast Cancer Pathology Integrative Care: (1) **Initial pathology**: core biopsy diagnosis + biomarkers (ER/PR/HER2/Ki-67) → molecular subtype + risk stratification; (2) **Multidisciplinary tumor board**: pathology + breast surgery + medical oncology + radiation oncology + radiology + plastic surgery + genetics + nurse navigator; (3) **Treatment planning**: neoadjuvant vs adjuvant; surgery (BCS vs mastectomy); axillary management; radiation; systemic therapy (chemo + targeted + endocrine); (4) **Post-treatment monitoring + surveillance**: annual mammography, clinical exam, symptoms, biomarkers (selected); (5) **Late effects + survivorship**: - Cardiotoxicity (trastuzumab, anthracycline) — cardio-oncology; - Lymphedema management; - Sexual + reproductive health; - Bone health (aromatase inhibitor — DEXA, bisphosphonate); - Cognitive (chemo brain); - Mental health + body image; - Fatigue + nutrition + exercise; (6) **Genetic counseling**: BRCA + others — family implications + risk-reducing strategies; (7) **Recurrence/metastatic disease**: re-biopsy when accessible — biomarker changes (ER/PR/HER2 conversion), new actionable mutations; (8) **New agents revolutionizing**: CDK4/6 inhibitors (palbociclib, ribociclib, abemaciclib) + endocrine; PARP inhibitors (BRCA); antibody-drug conjugates (T-DXd — HER2 + HER2-low); sacituzumab govitecan (TNBC); immunotherapy (TNBC + PD-L1+); (9) **Patient + family support**: education, peer support, financial counseling, integrative therapies; (10) **Equity considerations** + access

---

Breast cancer integrative pathology + care: multidisciplinary + comprehensive + long-term. Treatment phase + monitoring + survivorship + late effects + genetic counseling + recurrence management. Modern: revolutionary new agents + precision. Patient-centered.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'pathology'
  and scenario = 'Patient with breast cancer — pathology + multidisciplinary + survivorship integrative care';

update public.mcq_questions
set choices = '[{"label":"A","text":"Single specialty"},{"label":"B","text":"CKD Integrative Multidisciplinary Care"},{"label":"C","text":"Random"},{"label":"D","text":"Single specialty"},{"label":"E","text":"Refuse"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** CKD Integrative Multidisciplinary Care: (1) **Pathology role**: kidney biopsy for diagnosis of underlying disease (IgA, lupus nephritis, membranous, FSGS, diabetic nephropathy, etc.) → guides treatment; (2) **CKD staging**: by GFR + albuminuria (KDIGO); (3) **Treatment based on cause + stage**: - Diabetic nephropathy: SGLT2 + RAS blockade + finerenone + glycemic + BP control; - Immune-mediated: immunosuppression + KDIGO 2021; - Inherited (polycystic): tolvaptan for ADPKD; - Other secondary: treat underlying; (4) **Slowing progression** (universal): BP control + RAS blockade + glycemic + SGLT2 + finerenone + lipid + diet + smoking cessation; (5) **Comorbidity management**: CVD (greatest cause of death in CKD), bone-mineral disease (Ca, phos, PTH, vit D), anemia (EPO, iron, oral HIF-PHI roxadustat in some regions), acidosis (bicarbonate), uremia symptoms; (6) **Dialysis planning + transplant evaluation early** (Stage 4 → access, evaluation); (7) **Education + patient empowerment**: nutrition (K, phos, Na, protein, fluid), medication adherence, lifestyle, symptom recognition; (8) **Pharmacy review**: dose adjustment, nephrotoxin avoidance; (9) **Vaccinations**: special considerations (HBV — high doses, pre-dialysis); (10) **Mental health**: depression high in CKD; (11) **Palliative + advance care planning** for advanced; (12) **Multidisciplinary**: nephrology + pathology + primary care + dietitian + pharmacy + social work + transplant + dialysis + mental health; (13) **Modern**: novel agents (SGLT2, finerenone, HIF-PHI) + integrated chronic care

---

CKD integrative care: pathology diagnostic + comprehensive multidisciplinary management. Slowing progression + comorbidity + dialysis/transplant planning + education + palliative for advanced. Modern: SGLT2 + finerenone + HIF-PHI revolutionizing care.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'pathology'
  and scenario = 'Patient with chronic kidney disease — pathology + multidisciplinary integrative care';

update public.mcq_questions
set choices = '[{"label":"A","text":"Single specialty"},{"label":"B","text":"Hereditary Cancer Syndrome Integrative Care (Lynch Syndrome example)"},{"label":"C","text":"Random"},{"label":"D","text":"Refuse"},{"label":"E","text":"Single specialty"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Hereditary Cancer Syndrome Integrative Care (Lynch Syndrome example): (1) **Diagnostic confirmation**: germline MMR gene mutation (MLH1, MSH2, MSH6, PMS2, EPCAM); tumor testing (MSI, IHC for MMR) + Amsterdam/Bethesda criteria + family history; (2) **Surveillance + risk reduction**: - Colon: colonoscopy q1-2 yr starting age 20-25 (or 2-5 yr before youngest relative); - Endometrial + ovarian (women): annual TVS + endometrial sampling 30-35; risk-reducing hysterectomy + BSO 40-45; - Gastric/duodenal: EGD q3-5 yr from age 30-35 (especially Asian + family history); - Urothelial: annual urinalysis from 30-35; - Skin: annual skin exam; - Pancreatic: EUS/MRI in selected; (3) **Family screening**: cascade testing of first-degree relatives at appropriate age; counseling; (4) **Treatment of cancers**: standard but consider immunotherapy (pembrolizumab — MSI-H benefit); chemoprevention (aspirin — CAPP2 trial — reduces CRC + endometrial in Lynch); (5) **Genetic counseling**: complex testing + interpretation + family implications + psychosocial impact; (6) **Reproductive**: preimplantation genetic testing (PGT) consideration; (7) **Multidisciplinary**: medical genetics + GI + GYN + medical oncology + surgical oncology + pathology + primary care + psychology; (8) **Registry + research**: data + future understanding; (9) **Equity considerations**: testing access + cost + underrepresented populations; (10) **Patient + family education + advocacy**; (11) **Modern**: precision + family-centered + comprehensive lifelong care

---

Hereditary cancer syndrome integrative care: diagnosis + surveillance + risk reduction + family screening + treatment + counseling. Multidisciplinary genetics. Chemoprevention (aspirin Lynch). Modern: precision family-centered comprehensive lifelong care.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'pathology'
  and scenario = 'Patient with hereditary cancer syndrome (Lynch) + multidisciplinary genetics integrative care';

update public.mcq_questions
set choices = '[{"label":"A","text":"Invasive ductal carcinoma"},{"label":"B","text":"Ductal Carcinoma In Situ (DCIS)"},{"label":"C","text":"Atypical ductal hyperplasia"},{"label":"D","text":"Lobular carcinoma in situ"},{"label":"E","text":"Phyllodes tumor"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Ductal Carcinoma In Situ (DCIS): (1) **Definition**: malignant epithelial proliferation confined ใน ductal-lobular system โดย basement membrane intact; pre-invasive lesion; (2) **Histology**: solid, cribriform, papillary, micropapillary, comedo patterns; central necrosis + calcifications บ่อยใน high-grade comedo type; (3) **Grade (nuclear)**: low (1) — mild atypia + uniform; intermediate (2); high (3) — marked pleomorphism + comedonecrosis; (4) **IHC**: myoepithelial layer สำคัญที่สุด — p63, calponin, SMM-HC, CK5/6 intact = DCIS (vs invasive ที่ myoepithelium หายไป); ER/PR/HER2 routinely tested เพื่อ guide therapy + risk; (5) **Risk progression to invasive cancer**: untreated ~ 30-50% over 10 ปี; high grade + comedo + large size = higher risk; (6) **Treatment**: BCS + RT หรือ mastectomy; SLN biopsy ไม่จำเป็น routine (พิจารณาใน mastectomy หรือ large/high grade ที่อาจมี invasion occult); endocrine therapy (tamoxifen หรือ AI) สำหรับ ER+ DCIS หลัง BCS — reduces ipsilateral + contralateral risk; (7) **Margin**: ≥ 2 mm preferred per SSO/ASTRO/ASCO consensus; (8) **Surveillance**: annual mammogram + clinical exam; (9) **Multidisciplinary**: breast surgery + radiation + medical onc + pathology

---

DCIS — pre-invasive ductal neoplasia, myoepithelium intact (p63+/calponin+). BCS+RT or mastectomy; SLN เฉพาะ selected. Endocrine therapy ลด recurrence ใน ER+. Margin ≥ 2 mm.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'pathology'
  and scenario = 'ผู้ป่วยหญิงอายุ 48 ปี — screening mammogram พบ microcalcifications → stereotactic core biopsy; histology: cribriform + comedo pattern + central necrosis + atypical cells confined to ductal lumens, ไม่ทะลุ basement membrane; IHC: ER+ PR+ HER2 1+, p63 + myoepithelium intact; การวินิจฉัยและการจัดการที่เหมาะสม';

update public.mcq_questions
set choices = '[{"label":"A","text":"Ductal carcinoma"},{"label":"B","text":"Invasive Lobular Carcinoma (ILC)"},{"label":"C","text":"DCIS"},{"label":"D","text":"Inflammatory carcinoma"},{"label":"E","text":"Metaplastic carcinoma"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Invasive Lobular Carcinoma (ILC): (1) **Distinctive histology**: discohesive cells, single-file (Indian file) pattern, targetoid arrangement around ducts, signet ring cells, low-grade nuclei most cases; (2) **Hallmark molecular**: **loss of E-cadherin** (CDH1 gene mutation/deletion) → discohesive growth; p120 relocates จาก membrane → cytoplasm (E-cadherin loss); (3) **IHC pattern**: E-cadherin negative or fragmented + p120 cytoplasmic = lobular; vs ductal ที่ E-cadherin membrane+; (4) **Biology**: almost all ER+/PR+ HER2-; lower grade typically; (5) **Imaging**: often occult on mammography (no mass effect, no calcifications) → MRI สำคัญ in suspected ILC; (6) **Patterns of spread**: GI tract, ovary, peritoneum, leptomeninges (unique vs ductal); bone bilateral; (7) **Treatment** considerations: BCS challenging due to multifocality + extent; mastectomy more common; endocrine therapy mainstay (ER+); chemo less benefit historically; CDK4/6 + endocrine in advanced; (8) **Lobular Carcinoma In Situ (LCIS)**: marker of bilateral risk, not direct precursor; pleomorphic LCIS more aggressive; (9) **CDH1 germline**: hereditary diffuse gastric cancer syndrome — increased risk of ILC + diffuse gastric ca → consider genetic counseling

---

ILC: discohesive single-file, E-cadherin loss (CDH1), p120 cytoplasmic. Almost always ER+/HER2-. Imaging occult; MRI helpful. Unique metastasis pattern (GI, ovary, LM). Endocrine mainstay. CDH1 germline → HDGC syndrome.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'pathology'
  and scenario = 'ผู้ป่วยหญิงอายุ 62 ปี — palpable mass at breast → core biopsy: cells in single-file (Indian file) pattern infiltrating stroma + signet ring cells + lack of cohesion; IHC: ER+ PR+ HER2 0, **E-cadherin negative**, p120 cytoplasmic relocation; การวินิจฉัย';

update public.mcq_questions
set choices = '[{"label":"A","text":"Same prognosis"},{"label":"B","text":"Gastric Adenocarcinoma — Lauren Classification"},{"label":"C","text":"Skip biopsy"},{"label":"D","text":"Refuse"},{"label":"E","text":"Hospice immediately"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Gastric Adenocarcinoma — Lauren Classification: (1) **Intestinal type**: cohesive glands, intestinal metaplasia background, expansive growth, distal stomach, older men, environmental + H. pylori driven, stepwise progression (chronic gastritis → atrophy → intestinal metaplasia → dysplasia → carcinoma — Correa cascade); (2) **Diffuse type**: discohesive cells, signet ring, linitis plastica, younger, equal sex, **CDH1 (E-cadherin) loss** (sporadic + hereditary — HDGC); worse prognosis; (3) **WHO classification**: tubular, papillary, mucinous, poorly cohesive (incl signet ring), mixed, undifferentiated; (4) **Molecular subtypes (TCGA)**: EBV+ (PIK3CA, PD-L1, CIMP), MSI-high (hypermutated, MMR loss), genomically stable (CDH1, RHOA — diffuse type), chromosomal instability (TP53, intestinal type); (5) **Biomarker testing (essential for advanced)**: **HER2** (IHC + ISH per ToGA criteria — apical/lateral staining acceptable, ≥ 10% threshold) → trastuzumab; **PD-L1 CPS** → immunotherapy (nivolumab + chemo, pembrolizumab); **MSI/MMR** → immunotherapy + Lynch screen; **EBV** ISH → immunotherapy responsive; **Claudin 18.2** IHC → zolbetuximab (new); **FGFR2b**, **NTRK** in select; (6) **Staging**: TNM (AJCC 8th); EUS + CT/PET; staging laparoscopy + peritoneal cytology for advanced; (7) **Treatment**: perioperative chemo (FLOT) + D2 gastrectomy resectable; palliative chemo + targeted/IO for advanced; (8) **Multidisciplinary**

---

Gastric ca Lauren: intestinal (cohesive, H. pylori-driven, Correa cascade) vs diffuse (signet ring, CDH1 loss, worse). TCGA: EBV+/MSI/GS/CIN. Biomarkers: HER2, PD-L1 CPS, MSI, EBV, claudin 18.2. FLOT + D2 resectable.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'pathology'
  and scenario = 'ผู้ป่วยชายอายุ 65 ปี — endoscopic biopsy of gastric ulcer: glands with intestinal differentiation + goblet cells + cohesive nests, vs another patient with poorly cohesive cells + signet ring + diffuse infiltration; การจำแนกตาม Lauren classification และ implications';

update public.mcq_questions
set choices = '[{"label":"A","text":"No treatment needed"},{"label":"B","text":"H. pylori Gastritis Pathology + Management"},{"label":"C","text":"Surgery first"},{"label":"D","text":"Steroids"},{"label":"E","text":"Antifungal"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** H. pylori Gastritis Pathology + Management: (1) **Organism**: Helicobacter pylori — gram-negative curved/spiral rod, urease-producing (hydrolyzes urea → ammonia → neutralizes acid); (2) **Diagnostic methods**: histology (Giemsa, Warthin-Starry, IHC) — sensitive; rapid urease test (CLO) on biopsy; urea breath test (non-invasive); stool antigen; serology (cannot distinguish active vs past); culture (special media); (3) **Histology**: chronic active gastritis — lymphoplasmacytic + neutrophils + lymphoid aggregates; bacteria in mucus over surface epithelium; (4) **Associated conditions**: chronic gastritis → atrophic gastritis → intestinal metaplasia → dysplasia → gastric adenocarcinoma (Correa cascade); MALT lymphoma; peptic ulcer disease; iron deficiency; ITP; (5) **WHO Class 1 carcinogen** for gastric cancer + MALT lymphoma; (6) **Treatment**: eradication regimens (resistance-guided): - **Bismuth quadruple** (PPI + bismuth + tetracycline + metronidazole) 10-14 d — increasingly first-line due to clarithromycin resistance; - **Concomitant** (PPI + amox + clarithro + metro) where resistance < 15%; - **Triple** PPI + clarithro + amox phasing out in high-resistance areas; - **Vonoprazan-based** (potassium-competitive acid blocker) newer regimens — vonoprazan + amox dual + clarithro; (7) **Confirm eradication** ≥ 4 wk after Tx: urea breath test or stool antigen (off PPI 2 wk); (8) **MALT lymphoma**: eradication can induce regression of low-grade gastric MALT (depends on t(11;18))

---

H. pylori: gram-neg curved urease+ rod; histology + urease + UBT + stool Ag. Causes gastritis → cancer cascade + MALT. Eradication: bismuth quadruple or vonoprazan-based; confirm cure with UBT/stool Ag.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'pathology'
  and scenario = 'ผู้ป่วยอายุ 50 ปี — chronic dyspepsia + EGD biopsy from antrum: chronic active inflammation + lymphoid aggregates + curved gram-negative rods at mucus layer; rapid urease test positive';

update public.mcq_questions
set choices = '[{"label":"A","text":"Lynch syndrome confirmed"},{"label":"B","text":"Colorectal MSI/MMR Interpretation"},{"label":"C","text":"Ignore the IHC"},{"label":"D","text":"Repeat biopsy"},{"label":"E","text":"Refuse treatment"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Colorectal MSI/MMR Interpretation: (1) **MMR IHC pattern**: paired loss MLH1+PMS2 OR MSH2+MSH6 (heterodimer partners); isolated PMS2 loss = MLH1 hypomorph or PMS2 mutation; isolated MSH6 loss = MSH6 mutation; (2) **MLH1 loss with BRAF V600E + MLH1 hypermethylation** = sporadic, NOT Lynch — methylation silences MLH1, BRAF mutation associated with serrated pathway; (3) **MLH1 loss WITHOUT BRAF mutation/MLH1 methylation** → germline testing (Lynch); (4) **MSH2, MSH6, PMS2 loss** → germline testing directly (Lynch — BRAF/methylation reflex applies only to MLH1); (5) **MSI testing**: PCR-based (Bethesda panel, pentaplex BAT-25, BAT-26, NR-21, NR-24, MONO-27) — concordant with IHC; NGS-based MSI increasingly used; (6) **Clinical implications**: - **Prognosis**: stage II MSI-H better prognosis, may not benefit from adjuvant 5-FU monotherapy; - **Immunotherapy**: MSI-H/dMMR predicts response to checkpoint inhibitors (pembrolizumab, nivolumab/ipi) — frontline metastatic + neoadjuvant rectal (NICHE, PD-1 alone can yield clinical CR avoiding surgery); - **Lynch syndrome screen**: per universal CRC testing recommendations; (7) **WHO + CAP + NCCN**: universal MMR/MSI testing on all CRC + endometrial cancers; (8) **Multidisciplinary**: pathology + genetic counseling + oncology

---

MLH1 loss + BRAF V600E + MLH1 methylation = sporadic MSI-H, NOT Lynch. MSH2/MSH6/PMS2 loss → germline directly. MSI-H predicts IO response (frontline metastatic, neoadjuvant rectal). Universal CRC + EC testing.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'pathology'
  and scenario = 'ผู้ป่วยอายุ 58 ปี — right colon adenocarcinoma resection — IHC: **MLH1 loss + PMS2 loss**, MSH2/MSH6 intact; molecular: BRAF V600E mutation present, MLH1 promoter hypermethylation positive; การ interpret และ implications';

update public.mcq_questions
set choices = '[{"label":"A","text":"Cholangiocarcinoma"},{"label":"B","text":"Hepatocellular Carcinoma (HCC)"},{"label":"C","text":"Hemangioma"},{"label":"D","text":"FNH"},{"label":"E","text":"Metastasis"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Hepatocellular Carcinoma (HCC): (1) **Histology**: trabecular > 3 cells thick, pseudoglandular, solid, scirrhous patterns; polygonal cells with eosinophilic granular cytoplasm; bile production pathognomonic; sinusoidal capillarization (CD34 +); (2) **IHC panel**: HepPar-1 (hepatocyte specific Ag), arginase-1 (most sensitive + specific), glypican-3 (positive in HCC, negative in benign), AFP (variable); CD34 sinusoidal capillarization; reticulin loss; (3) **Differential**: hepatocellular adenoma (no atypia, reticulin retained, no glypican-3), focal nodular hyperplasia (central scar, map-like GS), cholangiocarcinoma (CK7/19+, mucin+), metastatic adenocarcinoma; (4) **Subtypes**: classic, fibrolamellar (young, no cirrhosis, DNAJB1-PRKACA fusion, lamellar fibrous bands), steatohepatitic, scirrhous, clear cell; (5) **Grading**: WHO/Edmondson-Steiner I-IV; (6) **Risk factors**: HBV, HCV, alcohol, NASH/MASLD increasingly important, aflatoxin, hemochromatosis, alpha-1 antitrypsin; (7) **Surveillance** in cirrhosis: US ± AFP q6 mo; LI-RADS for imaging interpretation; (8) **Treatment (BCLC)**: - 0/A: resection, transplant (Milan), ablation; - B: TACE; - C: systemic — atezolizumab + bevacizumab (IMbrave150) frontline; tremelimumab + durvalumab (HIMALAYA); lenvatinib, sorafenib; later lines regorafenib, cabozantinib, ramucirumab (AFP > 400), nivolumab + ipi; - D: BSC; (9) **Prevention**: HBV vaccination + treatment; HCV cure with DAAs

---

HCC: trabecular + bile production, IHC HepPar-1/arginase-1/GPC3/AFP. Subtypes (fibrolamellar DNAJB1-PRKACA). BCLC-based treatment; atezo-bev frontline systemic. HBV/HCV/MASLD risk; surveillance with US±AFP q6mo + LI-RADS.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'pathology'
  and scenario = 'ผู้ป่วยชายอายุ 60 ปี cirrhosis from HBV → liver mass biopsy: trabecular pattern of polygonal cells with eosinophilic cytoplasm, bile production within tumor; IHC: HepPar-1+, arginase-1+, glypican-3+, AFP+; การวินิจฉัย';

update public.mcq_questions
set choices = '[{"label":"A","text":"Acinar cell carcinoma"},{"label":"B","text":"Pancreatic Ductal Adenocarcinoma (PDAC)"},{"label":"C","text":"Neuroendocrine tumor"},{"label":"D","text":"Solid pseudopapillary"},{"label":"E","text":"Chronic pancreatitis"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Pancreatic Ductal Adenocarcinoma (PDAC): (1) **Histology**: malignant glandular structures, mucin production, desmoplastic stroma (fibrous reaction prominent), perineural + lymphovascular invasion common, infiltrative pattern; (2) **IHC**: CK7+, CK19+, CA19-9, MUC1, MUC5AC; loss of SMAD4 (DPC4) in ~ 55% (genomic deletion 18q21); CK20/CDX2 negative (helps distinguish from intestinal mets); (3) **Molecular landscape (TCGA)**: KRAS mutation > 90% (mainly G12D, G12V, G12R), TP53 ~ 70%, CDKN2A ~ 50%, SMAD4 ~ 55%; KRAS G12C minority but actionable (sotorasib, adagrasib); (4) **Actionable alterations (4-15%)**: BRCA1/2, PALB2 (HRD → platinum + PARP — olaparib maintenance POLO trial); MSI-H rare ~ 1% (immunotherapy); NTRK, NRG1 fusions; BRAF; HER2 amplification; (5) **Subtypes (molecular)**: classical, basal-like (squamous) — basal-like worse prognosis; (6) **Precursors**: PanIN, IPMN (intraductal papillary mucinous neoplasm), MCN (mucinous cystic); (7) **Staging + treatment**: resectable < 20% — Whipple/distal panc + adjuvant mFOLFIRINOX (preferred) or gem-cape; borderline/locally advanced — neoadjuvant FOLFIRINOX/gem-NabP; metastatic — FOLFIRINOX (NAPOLI-3 with NALIRIFOX now alternative), gem-NabP; second line nano-liposomal irinotecan + 5-FU; (8) **Germline testing recommended** all patients; (9) **Multidisciplinary** + palliative early + biliary stenting + nutrition

---

PDAC: glands + desmoplasia + perineural; CK7+/CK19+, SMAD4 loss ~55%. KRAS > 90% + TP53/CDKN2A/SMAD4. Actionable: BRCA/PALB2 (PARP), MSI rare, KRAS G12C. NALIRIFOX + FOLFIRINOX. Germline all patients.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'pathology'
  and scenario = 'ผู้ป่วยอายุ 65 ปี — pancreatic head mass + obstructive jaundice → EUS-FNA biopsy: malignant glands with mucin in desmoplastic stroma; IHC: CK7+ CK19+ CK20- CDX2-; molecular: KRAS mutation, TP53, CDKN2A, SMAD4 loss; การวินิจฉัย และ implications';

update public.mcq_questions
set choices = '[{"label":"A","text":"Reactive change"},{"label":"B","text":"Cervical HSIL/CIN3 — Pathology + Management"},{"label":"C","text":"Cervicitis"},{"label":"D","text":"Hysterectomy first"},{"label":"E","text":"Refuse"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Cervical HSIL/CIN3 — Pathology + Management: (1) **LAST terminology (2012, revised)**: LSIL (low-grade squamous intraepithelial lesion = CIN1, HPV cytopathic effect); HSIL (high-grade = CIN2-3); SCC; AIS (adenocarcinoma in situ); (2) **Histology HSIL**: atypia ≥ 2/3 epithelial thickness; mitoses upper layers; loss of maturation; (3) **IHC**: **p16 block-positive** (strong continuous nuclear + cytoplasmic ≥ 1/3 thickness) = high-risk HPV transcriptionally active → upgrade equivocal lesions; Ki-67 elevated upper levels; (4) **HPV**: high-risk types 16, 18 most common; 31, 33, 45, 52, 58 also; (5) **Screening (USPSTF/ASCCP 2019, updated)**: HPV primary 25-65 q5y preferred; co-testing q5y; cytology alone q3y 21-29; (6) **Risk-based management (ASCCP 2019)**: based on current + past results → estimate CIN3+ risk → treat, colpo, or surveillance; HSIL/CIN3 → excisional treatment (LEEP, cold knife cone) typically; (7) **AIS**: cold knife conization (LEEP can fragment), negative margins essential; hysterectomy after childbearing; (8) **Prevention**: HPV vaccination 9-valent recommended 9-26 (catch-up to 45 shared decision); (9) **Special**: pregnancy, immunocompromised (HIV), adolescents = different algorithms; (10) **Post-treatment surveillance**: HPV testing 6 mo, then per risk

---

HSIL (CIN2-3): full-thickness atypia + p16 block+ + HPV-HR. ASCCP 2019 risk-based mgmt; LEEP/cone treatment. AIS → CKC. HPV vaccine prevention. LAST terminology + p16 IHC standard.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'pathology'
  and scenario = 'ผู้ป่วยหญิงอายุ 42 ปี — abnormal cervical screening → colposcopy + biopsy: full-thickness atypia + koilocytes + mitotic figures throughout epithelium; p16 strong + diffuse block-positive, Ki-67 elevated full thickness; HPV testing: HPV-16 positive';

update public.mcq_questions
set choices = '[{"label":"A","text":"Benign hyperplasia"},{"label":"B","text":"Endometrial Carcinoma Pathology + Molecular Classification"},{"label":"C","text":"Polyp"},{"label":"D","text":"Refuse"},{"label":"E","text":"Cervicitis"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Endometrial Carcinoma Pathology + Molecular Classification: (1) **Histology**: endometrioid adenocarcinoma — confluent glands, cribriform, squamous differentiation common, low-grade nuclei (FIGO 1-2) vs serous + clear cell + carcinosarcoma (high grade); (2) **FIGO grade (endometrioid)**: based on architectural pattern + nuclear atypia; G1 ≤ 5% solid, G2 6-50%, G3 > 50% solid; nuclear atypia upgrades by 1; (3) **TCGA/ProMisE molecular classification (essential, integrated into FIGO 2023 staging)**: - **POLE ultramutated**: best prognosis, may de-escalate; - **MMR-deficient (MSI-H)** ~ 30%: intermediate, immunotherapy candidate, screen for Lynch; - **p53 abnormal (copy number high, serous-like)**: worst prognosis, often serous/G3 endometrioid, HER2 testing (trastuzumab benefit); - **NSMP (no specific molecular profile)**: variable; (4) **Endometrial hyperplasia/EIN** terminology: WHO — hyperplasia without atypia (benign) vs atypical hyperplasia/EIN (precursor) → high progression risk → hysterectomy or progestin; (5) **PTEN loss** common early in endometrioid; (6) **Workup**: TVS, EMB, hysteroscopy; staging surgical (TAH-BSO + LN/SLN); (7) **Treatment**: - Stage I low-risk: surgery alone; - Higher risk: ± adjuvant chemo/RT; - Advanced/metastatic: chemo (carbo-paclitaxel) + pembrolizumab + lenvatinib OR pembro alone if dMMR (KEYNOTE-868, RUBY); - Recurrent: same combos; HER2+ serous → trastuzumab/T-DXd; (8) **Lynch screen** universal

---

Endometrial endometrioid ca: confluent glands + atypia. FIGO 2023 integrates TCGA molecular (POLE/MMRd/p53abn/NSMP) → prognosis + Tx. Pembro + lenvatinib advanced; pembro alone dMMR. Universal Lynch screen; HER2 in serous.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'pathology'
  and scenario = 'ผู้ป่วยหญิงอายุ 67 ปี — postmenopausal bleeding + endometrial biopsy: confluent glands + cribriform + nuclear atypia + squamous differentiation; IHC: ER+ PR+ PTEN loss; MMR IHC retained; การจำแนกและการรักษา';

update public.mcq_questions
set choices = '[{"label":"A","text":"Endometrioid"},{"label":"B","text":"High-Grade Serous Carcinoma (HGSC) — Ovarian/Tubal"},{"label":"C","text":"Mucinous"},{"label":"D","text":"Granulosa cell"},{"label":"E","text":"Teratoma"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** High-Grade Serous Carcinoma (HGSC) — Ovarian/Tubal: (1) **Histology**: papillary, slit-like glandular, solid; marked nuclear atypia + high mitotic rate + psammoma bodies; (2) **IHC**: **WT1+** (Müllerian/serous), PAX8+ (Müllerian), p53 ''aberrant'' (diffuse strong overexpression OR complete null) reflecting TP53 mutation (~ 96% HGSC), p16 block, Ki-67 high, ER variable; (3) **Origin**: most HGSCs arise from fallopian tube fimbriae (STIC — serous tubal intraepithelial carcinoma) — basis for opportunistic salpingectomy + RRSO in BRCA; (4) **Molecular**: TP53 ubiquitous; **homologous recombination deficiency (HRD)** ~ 50% — BRCA1/2 (germline + somatic) ~ 20-25%, other HR genes (RAD51, PALB2, BRIP1, CHEK2, ATM, BARD1); CCNE1 amplification mutually exclusive with HR loss; (5) **Tumor + germline testing** all HGSC (NCCN); (6) **Staging**: FIGO surgical — TAH-BSO + omentectomy + LN + cytoreduction; (7) **Treatment**: - Primary cytoreductive surgery + IV/IP platinum-taxane; - Neoadjuvant chemo + interval debulking acceptable; - Bevacizumab in select; - **PARP inhibitors** (olaparib, niraparib, rucaparib) maintenance — biggest impact in BRCA/HRD+ (SOLO-1, PRIMA, PAOLA-1); - Recurrent platinum-sensitive vs resistant; (8) **Grading**: 2-tier (low vs high grade) per WHO/MD Anderson; LGSC distinct entity (BRAF/KRAS, MAPK pathway, MEK inhibitor); (9) **Multidisciplinary** GYN-onc + medical onc + genetics + path

---

HGSC: papillary + psammoma + p53 aberrant + WT1+/PAX8+. TP53 ~96%; HRD ~50% (BRCA/HR genes). Origin: tubal fimbria (STIC). Treatment: cytoreduction + plat-tax + PARP maintenance (HRD biggest benefit). Universal germline.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'pathology'
  and scenario = 'ผู้ป่วยหญิงอายุ 58 ปี — pelvic mass + ascites + CA-125 markedly elevated → omental biopsy: papillary architecture + slit-like spaces + marked nuclear atypia + psammoma bodies; IHC: WT1+, PAX8+, p53 diffuse aberrant overexpression, p16 block-positive; การวินิจฉัย';

update public.mcq_questions
set choices = '[{"label":"A","text":"Benign"},{"label":"B","text":"Prostate Adenocarcinoma — Grading + Management"},{"label":"C","text":"BPH"},{"label":"D","text":"Refuse"},{"label":"E","text":"Prostatitis only"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Prostate Adenocarcinoma — Grading + Management: (1) **Histology**: infiltrative small glands lacking basal cells; nucleoli prominent; (2) **IHC for diagnostic challenge**: AMACR (P504S)+ in cancer; basal cell markers (p63, HMWCK 34βE12, CK5/6) negative in cancer, positive in benign basal cells; (3) **Grading**: **ISUP Grade Groups (2014, integrated 2019)** — replaced sole Gleason reporting; GG1 = 3+3, GG2 = 3+4, GG3 = 4+3, GG4 = 8 (4+4, 3+5, 5+3), GG5 = 9-10; cribriform/intraductal carcinoma adverse features (report explicitly); (4) **Intraductal carcinoma of prostate (IDC-P)**: aggressive feature within ducts/acini; report separately — associated with adverse outcomes + germline DDR mutations; (5) **Staging**: TNM + risk groups (NCCN: very low, low, favorable intermediate, unfavorable intermediate, high, very high, regional, metastatic); PSMA-PET (Ga-68/F-18 piflufolastat) revolutionized staging + biochemical recurrence localization; (6) **Molecular biomarkers**: AR-V7 (resistance), BRCA1/2 + other HRR (germline + somatic — olaparib, rucaparib, talazoparib in mCRPC), MSI-H (rare → pembro), genomic classifiers (Decipher, Prolaris, Oncotype DX Prostate); (7) **Treatment by risk**: - Active surveillance for very low + selected low; - Localized: prostatectomy or RT ± ADT; - Metastatic hormone-sensitive: ADT + ARSI (apa/enza/abi) + chemo (TITAN, LATITUDE, ENZAMET, ARASENS, PEACE-1); - mCRPC: ARSI, docetaxel, cabazitaxel, radium-223 (bone), 177Lu-PSMA (VISION), PARP if HRR+; (8) **Germline testing** for metastatic + high-risk + family history

---

Prostate ca: small glands, no basal, AMACR+/p63-. ISUP grade groups GG1-5. Cribriform/IDC-P adverse. PSMA-PET staging; HRR germline (PARP). Risk-based: AS → RP/RT → ADT+ARSI±chemo → mCRPC ARSI/177Lu-PSMA/PARP.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'pathology'
  and scenario = 'ผู้ป่วยชายอายุ 68 ปี — elevated PSA → prostate biopsy: small infiltrative glands lacking basal cells, nucleoli prominent; ISUP/Gleason score 4+3=7 (Grade group 3); IHC: AMACR (P504S)+, basal markers (p63, HMWCK) negative; PTEN loss; การ stage และ rxtreatment';

update public.mcq_questions
set choices = '[{"label":"A","text":"Papillary RCC"},{"label":"B","text":"Clear Cell Renal Cell Carcinoma (ccRCC)"},{"label":"C","text":"Chromophobe"},{"label":"D","text":"Oncocytoma"},{"label":"E","text":"Angiomyolipoma"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Clear Cell Renal Cell Carcinoma (ccRCC): (1) **Histology**: clear cytoplasm (glycogen + lipid dissolved during processing), delicate vascular network ''chicken wire'', solid/alveolar/cystic; (2) **IHC**: CAIX (membranous, hypoxia marker)+, PAX8+, CD10+, vimentin+, RCC marker+; CK7 patchy (helpful vs papillary which CK7+); (3) **Grading**: **WHO/ISUP grade 1-4** (replaced Fuhrman) based on nucleoli prominence + rhabdoid/sarcomatoid features; (4) **Molecular**: **VHL gene inactivation** (3p deletion + somatic mutation/methylation) → HIF accumulation → pro-angiogenic (VEGF, PDGF); other 3p genes PBRM1, BAP1, SETD2; (5) **Hereditary**: VHL syndrome (germline VHL → bilateral multifocal ccRCC + hemangioblastoma + pheo); (6) **Other RCC subtypes (WHO 5th ed)**: papillary RCC (TFE3 — MiTF family translocation, FH-deficient — HLRCC, SDH-deficient, ELOC, SMARCB1-deficient renal medullary carcinoma); papillary type 1 (MET-driven) + type 2; chromophobe (KIT/EGFR, mitochondria-rich); collecting duct; medullary (sickle trait, very aggressive); (7) **Staging**: TNM + size; (8) **Treatment**: - Localized: partial vs radical nephrectomy; small renal masses (≤ 4 cm) — active surveillance considered, ablation, partial; - Metastatic frontline: IO doublet (nivolumab + ipi for intermediate/poor risk) OR IO + TKI (pembro + axitinib, nivo + cabo, pembro + lenvatinib, ave + axitinib) — based on IMDC risk; - Single-agent TKI (sunitinib, cabozantinib, pazopanib) historical; - HIF-2α inhibitor **belzutifan** approved (VHL-associated RCC + advanced RCC after IO/TKI)

---

ccRCC: clear cytoplasm + chicken-wire vessels; CAIX+/PAX8+/CD10+; VHL inactivation + 3p loss. WHO/ISUP grading. Hereditary: VHL syndrome. Treatment: IO doublet or IO+TKI metastatic; belzutifan HIF-2α inhibitor.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'pathology'
  and scenario = 'ผู้ป่วยอายุ 60 ปี — renal mass nephrectomy: tumor with clear cytoplasm + delicate vasculature ''chicken wire'' pattern + Fuhrman/WHO-ISUP grade 3; IHC: CAIX+, PAX8+, CD10+, vimentin+, CK7 patchy; molecular: VHL inactivation, 3p loss; การวินิจฉัย';

update public.mcq_questions
set choices = '[{"label":"A","text":"Carcinoma in situ only"},{"label":"B","text":"Urothelial Carcinoma — Classification + Management"},{"label":"C","text":"Refuse"},{"label":"D","text":"Hospice"},{"label":"E","text":"Routine f/u no Tx"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Urothelial Carcinoma — Classification + Management: (1) **WHO 2022 (5th ed) classification**: - Urothelial papilloma (rare); - **PUNLMP** (papillary urothelial neoplasm of low malignant potential); - **Non-invasive low-grade papillary urothelial carcinoma**; - **Non-invasive high-grade papillary urothelial carcinoma**; - **Urothelial CIS** (flat high-grade); - **Invasive urothelial carcinoma** (Ta — non-invasive, T1 lamina propria, T2+ muscularis propria); (2) **Histologic features**: variants — squamous, glandular, micropapillary (aggressive — early radical), plasmacytoid (aggressive, CDH1 loss), sarcomatoid, nested, lymphoepithelioma-like, lipid-cell; (3) **IHC**: GATA3, p40/p63, CK7+/CK20+ uroplakin+ helpful for site of origin in mets; (4) **Molecular subtypes** (TCGA, Lund — luminal, basal/squamous, neuroendocrine) — increasingly therapy-relevant; (5) **FGFR3 alterations** in ~ 20% (more in NMIBC) → erdafitinib (THOR trial) in metastatic; (6) **Treatment**: - **NMIBC** (Ta, T1, CIS): TURBT + intravesical therapy (BCG for high-risk; mitomycin) + surveillance; BCG-unresponsive — pembrolizumab, nadofaragene firadenovec, oportuzumab monatox; - **MIBC** (T2+): neoadjuvant cisplatin chemo (MVAC/gem-cis) + radical cystectomy + PLND; bladder preservation TMT in select; adjuvant nivolumab (CheckMate 274) ypT2+/N+; - **Metastatic**: now frontline **enfortumab vedotin + pembrolizumab** (EV-302) — superseded chemo; chemo alternative; later sacituzumab govitecan, erdafitinib (FGFR), avelumab maintenance after chemo response; (7) **Multidisciplinary**

---

Urothelial ca WHO 2022: PUNLMP/low-grade/high-grade/CIS/invasive. Variants matter (micropap/plasmacytoid aggressive). FGFR3 — erdafitinib. NMIBC: TURBT+BCG. MIBC: neoadj cis + cystectomy. Metastatic: EV+pembro frontline.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'pathology'
  and scenario = 'ผู้ป่วยชายอายุ 70 ปี — gross hematuria + bladder cystoscopy: papillary tumor → TURBT shows papillary urothelial neoplasm with mild atypia + low mitoses + > 7 cells thick; การจำแนกตาม WHO 2022 + ติดตาม';

update public.mcq_questions
set choices = '[{"label":"A","text":"Yolk sac"},{"label":"B","text":"Testicular Seminoma (Classic)"},{"label":"C","text":"Lymphoma"},{"label":"D","text":"Sertoli cell"},{"label":"E","text":"Refuse Tx"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Testicular Seminoma (Classic): (1) **Histology**: sheets/nests of uniform cells with clear cytoplasm (glycogen — ''fried egg''), prominent central nucleoli, fibrous septa with lymphocytic infiltrate ± granulomas; (2) **IHC**: **OCT3/4**+, PLAP+, **CD117 (KIT)**+, SALL4+, D2-40 (podoplanin)+, CK negative (vs embryonal CK+); CD30 negative (vs embryonal); (3) **Tumor markers**: AFP normal (elevated AFP rules out pure seminoma — indicates yolk sac or mixed); beta-hCG mildly elevated possible (syncytiotrophoblast cells); LDH non-specific; (4) **Differential**: embryonal (CD30+, OCT4+, CK+), yolk sac (AFP+, glypican-3+), choriocarcinoma (hCG markedly elevated), teratoma; spermatocytic tumor (older age, OCT4 negative); (5) **Precursor**: **germ cell neoplasia in situ (GCNIS)** — formerly ITGCN — atypical germ cells in seminiferous tubules; OCT4+, PLAP+; (6) **Staging**: TNM + serum tumor markers (S) + risk groups (IGCCCG); (7) **Treatment** (highly curable): - Stage I: orchiectomy + surveillance (preferred), single-dose carboplatin, or RT (less favored now); - Stage IIA/B: RT or chemo (BEP × 3 / EP × 4); - Stage IIC+/metastatic: BEP × 3 (good risk) or BEP × 4 (intermediate); - Salvage: high-dose chemo + autoSCT or TIP; (8) **Survivorship**: cardiovascular + second malignancy + fertility — sperm banking pre-treatment essential; (9) **Genetic**: isochromosome 12p (i(12p)) characteristic

---

Seminoma: fried-egg + lymphocytic infiltrate; OCT3/4+/CD117+/SALL4+, CK-/CD30-. AFP normal (if AFP↑ → mixed/yolk sac). Precursor GCNIS. Stage I surveillance preferred. BEP chemo highly curative. i(12p) characteristic.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'pathology'
  and scenario = 'ผู้ป่วยชายอายุ 28 ปี — testicular mass orchiectomy: tumor cells with fried-egg cytoplasm + clear glycogen + lymphocytic infiltrate; IHC: OCT3/4+, PLAP+, CD117+, SALL4+, CK negative; serum: AFP normal, beta-hCG mildly elevated, LDH elevated';

update public.mcq_questions
set choices = '[{"label":"A","text":"Anaplastic thyroid ca"},{"label":"B","text":"Papillary Thyroid Carcinoma (PTC)"},{"label":"C","text":"Medullary"},{"label":"D","text":"Hashimoto"},{"label":"E","text":"Adenoma"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Papillary Thyroid Carcinoma (PTC): (1) **Bethesda system for thyroid cytopathology** I-VI; III (AUS/FLUS) + IV (FN/SFN) — molecular testing (Afirma GSC, ThyroSeq, ThyGeNEXT-ThyraMIR) refines risk; V suspicious; VI malignant; (2) **PTC histology**: papillary fronds with fibrovascular cores; **nuclear features** diagnostic — chromatin clearing (''Orphan Annie eyes''), nuclear grooves, intranuclear pseudoinclusions, irregular contours, overlapping; psammoma bodies; (3) **IHC**: TTF1+, thyroglobulin+, CK19+, HBME-1+, galectin-3+; cyclin D1+; (4) **Variants** (some renamed in 2017 reclassification): - **NIFTP** (non-invasive follicular thyroid neoplasm with papillary-like nuclear features) — formerly noninvasive encapsulated FV-PTC — indolent, lobectomy alone; - Classical, follicular variant, tall cell, columnar, hobnail (aggressive), diffuse sclerosing, solid; (5) **Molecular**: **BRAF V600E** ~ 60% (more aggressive, more recurrence); RAS-mutated (more follicular-pattern, less aggressive); RET/PTC rearrangements (radiation-associated, pediatric); TERT promoter (adverse); (6) **Treatment**: lobectomy vs total thyroidectomy based on size + features + risk; selective central neck dissection; RAI for selected (intermediate/high-risk); levothyroxine TSH suppression for higher risk; (7) **Targeted therapy**: dabrafenib + trametinib (BRAF+ advanced); selpercatinib/pralsetinib (RET fusions); larotrectinib/entrectinib (NTRK fusions); cabozantinib, lenvatinib, sorafenib (RAI-refractory); (8) **Active surveillance** for low-risk papillary microcarcinoma (< 1 cm, no concerning features) emerging

---

PTC: papillary + diagnostic nuclear features (clearing, grooves, pseudoinclusions) + psammoma. Bethesda → molecular refines risk. NIFTP carved out. BRAF V600E ~60%; targeted Tx for advanced (BRAF/RET/NTRK). RAI selected.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'pathology'
  and scenario = 'ผู้ป่วยอายุ 35 ปี — thyroid nodule FNA → cytology Bethesda VI (malignant); thyroidectomy: papillary architecture + nuclear features (clearing, grooves, intranuclear pseudoinclusions) + psammoma bodies; molecular: BRAF V600E mutation';

update public.mcq_questions
set choices = '[{"label":"A","text":"SCLC"},{"label":"B","text":"Lung Adenocarcinoma — Pathology + Molecular"},{"label":"C","text":"Mesothelioma"},{"label":"D","text":"Carcinoid"},{"label":"E","text":"Pneumonia"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Lung Adenocarcinoma — Pathology + Molecular: (1) **Histology**: lepidic, acinar, papillary, micropapillary (aggressive), solid, mucinous, colloid; new IASLC grading (G1-3) by predominant + high-grade pattern; (2) **IHC**: TTF-1+ (most), napsin-A+, CK7+; mucinous adenoca may TTF-1 negative; vs squamous (p40+, CK5/6+); SCLC (synaptophysin, chromogranin, INSM1+, TTF-1+, CK dot-like); (3) **Essential biomarker panel (advanced NSCLC, NCCN/CAP)**: **EGFR, ALK, ROS1, BRAF V600E, KRAS (especially G12C), MET exon 14 + amplification, HER2 (ERBB2), RET, NTRK1/2/3, NRG1; PD-L1 TPS**; comprehensive NGS preferred; (4) **Targeted therapy (matched)**: - EGFR (exon 19 del, L858R): osimertinib (3rd-gen) frontline; FLAURA2 osimertinib + chemo; amivantamab + lazertinib (MARIPOSA); exon 20 ins — amivantamab; - ALK: alectinib, brigatinib, lorlatinib (CROWN); - ROS1: entrectinib, repotrectinib (newer), crizotinib; - BRAF V600E: dab + tram; encorafenib + binimetinib; - KRAS G12C: sotorasib, adagrasib; - MET ex14: capmatinib, tepotinib; - RET fusion: selpercatinib, pralsetinib; - NTRK: larotrectinib, entrectinib; - HER2: T-DXd; - NRG1: zenocutuzumab; (5) **No driver mutation**: IO ± chemo based on PD-L1; KEYNOTE-189/407; (6) **Adjuvant** for resected: osimertinib (EGFR — ADAURA), atezolizumab/pembro (PD-L1 ≥ 1%), alectinib (ALK — ALINA); (7) **Re-biopsy on progression** for resistance mechanisms (T790M, C797S, MET amp)

---

Lung adenoca: TTF-1+/napsin-A+. IASLC grading. Essential biomarkers (EGFR/ALK/ROS1/BRAF/KRAS/MET/HER2/RET/NTRK/NRG1/PD-L1). Matched targeted Tx (osimertinib EGFR; alectinib ALK; etc.). Re-biopsy at progression.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'pathology'
  and scenario = 'ผู้ป่วยหญิงอายุ 62 ปี non-smoker — lung mass → biopsy: glandular architecture with lepidic + acinar patterns; IHC: TTF-1+, napsin-A+, CK7+; molecular reflex: EGFR exon 19 deletion mutation positive, ALK negative, ROS1 negative, PD-L1 TPS 5%';

update public.mcq_questions
set choices = '[{"label":"A","text":"Adenocarcinoma"},{"label":"B","text":"Squamous Cell Carcinoma of Lung"},{"label":"C","text":"SCLC"},{"label":"D","text":"Carcinoid"},{"label":"E","text":"Tuberculosis"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Squamous Cell Carcinoma of Lung: (1) **Histology**: keratinization (keratin pearls), intercellular bridges, eosinophilic dense cytoplasm; central location classically (vs peripheral adenocarcinoma); (2) **IHC**: **p40+** (most specific), p63+, CK5/6+, CK7 variable, TTF-1 negative, napsin-A negative, desmoglein-3+; (3) **Molecular**: PIK3CA, PTEN, FGFR1 amplification, DDR2 — fewer actionable drivers vs adenocarcinoma; (4) **Smoking-related**; tumor mutational burden often high → IO response; (5) **Biomarker testing**: PD-L1 TPS essential; comprehensive NGS still warranted to find rare actionable (rare EGFR/ALK if non-smoker or never-smoker history); (6) **Treatment (advanced)**: - PD-L1 ≥ 50%: pembrolizumab monotherapy or chemo-IO; - PD-L1 < 50%: chemo + pembrolizumab (KEYNOTE-407 with carbo + paclitaxel/nab-paclitaxel); - Other combos: atezolizumab + chemo; cemiplimab; durva + treme + chemo; nivolumab + ipilimumab + chemo; - **Bevacizumab + erlotinib contraindicated** in squamous (cavitation/hemorrhage risk historically — pemetrexed and bevacizumab limited to non-squamous); (7) **Resectable**: surgery + adjuvant cisplatin chemo (+ adjuvant atezolizumab/pembro); neoadjuvant nivo + chemo (CheckMate 816); perioperative pembro/nivo (KEYNOTE-671, AEGEAN); (8) **Locally advanced**: concurrent chemoRT + durvalumab consolidation (PACIFIC); (9) **Distinguishing from adenoca essential** for treatment (pemetrexed/bevacizumab restrictions)

---

Squamous NSCLC: keratinization + bridges; p40+/p63+/CK5/6+, TTF-1-/napsin-. Smoking-related, few drivers. PD-L1 + NGS. Pembro ± chemo (KEYNOTE-407). No pemetrexed/bev (squamous). Perioperative IO + chemo (CheckMate 816).'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'pathology'
  and scenario = 'ผู้ป่วยอายุ 70 ปี heavy smoker — central lung mass → biopsy: keratin pearls + intercellular bridges + cells with abundant eosinophilic cytoplasm; IHC: p40+, p63+, CK5/6+, TTF-1 negative; การวินิจฉัย และ implications';

update public.mcq_questions
set choices = '[{"label":"A","text":"Benign nevus"},{"label":"B","text":"Cutaneous Melanoma — Pathology + Management"},{"label":"C","text":"BCC"},{"label":"D","text":"Seborrheic keratosis"},{"label":"E","text":"Dermatofibroma"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Cutaneous Melanoma — Pathology + Management: (1) **Histology**: atypical melanocytes in nests + single cells; pagetoid (upward) spread; lack of maturation; mitoses including deep; ulceration; lymphovascular/perineural invasion; (2) **IHC**: **SOX10** (most sensitive, nuclear), S100+, HMB-45+, Melan-A (MART-1)+, tyrosinase+, **PRAME** emerging (positive in melanoma, helps distinguish from nevus; high specificity); (3) **Critical prognostic features** (AJCC 8th): **Breslow thickness**, **ulceration**, **mitotic rate** (for T1 specifically); (4) **Subtypes**: superficial spreading (most common, BRAF), nodular, lentigo maligna (chronic sun-damage, NF1/KIT), acral (KIT, no BRAF often), mucosal (KIT, NF1), uveal (GNAQ/GNA11 — BAP1 loss aggressive — distinct biology); desmoplastic (TERT promoter, NF1); (5) **Molecular**: **BRAF V600E/K** ~ 50% cutaneous; NRAS, NF1; KIT in acral/mucosal; TERT promoter ubiquitous; (6) **SLNB indication**: T1b (≥ 0.8 mm or ulceration), all T2+; staging — MSLT-II showed CLND no benefit in SLN+ → observation + nodal US; (7) **Treatment by stage**: - In situ: wide local excision; - Stage I-II: WLE + SLNB; adjuvant for IIB+ (pembro/nivo) or BRAF-targeted (dab+tram BRAF+); - Stage III resected: adjuvant nivolumab or pembrolizumab; BRAF+ — dab + tram; - Stage IV metastatic: nivo + ipi or nivo + relatlimab (RELATIVITY-047 LAG3) or pembro; BRAF+ — chemo-IO or targeted; brain mets — combination important; - Neoadjuvant pembro before resection (S1801, NADINA) emerging standard for high-risk resectable; (8) **TIL therapy** (lifileucel) approved 2024 for refractory metastatic

---

Melanoma: pagetoid + atypia + Breslow + ulceration + mitoses. SOX10/S100/HMB-45/Melan-A/PRAME. BRAF V600 ~50%; subtypes differ molecularly. SLNB T1b+. Adjuvant IO IIB+; metastatic nivo+ipi or nivo+rela; neoadjuvant pembro emerging.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'pathology'
  and scenario = 'ผู้ป่วยอายุ 55 ปี — pigmented skin lesion excision: atypical melanocytes with pagetoid spread + asymmetry + Breslow thickness 2.3 mm + ulceration present + mitoses 4/mm²; IHC: S100+, SOX10+, HMB-45+, Melan-A+; molecular: BRAF V600E mutation positive';

update public.mcq_questions
set choices = '[{"label":"A","text":"Melanoma"},{"label":"B","text":"Basal Cell Carcinoma (BCC)"},{"label":"C","text":"Refuse"},{"label":"D","text":"Hospice"},{"label":"E","text":"Cyst"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Basal Cell Carcinoma (BCC): (1) **Histology**: basaloid cells with peripheral palisading + retraction artifact (cleft between epithelium + stroma due to mucin) + mucinous stroma + variable mitoses; (2) **Subtypes**: nodular (most common), superficial, infiltrative/morpheaform (aggressive — ill-defined margin), micronodular (aggressive), basosquamous (intermediate aggressiveness, can metastasize rarely), pigmented; (3) **IHC**: BerEP4+, BCL2+, EMA negative, CK20 (negative — distinguishes from Merkel cell ca), Ki-67 variable; (4) **Risk factors**: UV exposure cumulative + intermittent, fair skin, immunosuppression (transplant — high frequency + aggressive), prior RT, arsenic, Gorlin (NBCCS — PTCH1, basal cells nevus syndrome — multiple BCCs young); (5) **Molecular pathway**: **Hedgehog (SMO/PTCH1/GLI)** dysregulation; (6) **Behavior**: locally invasive, rarely metastasize; perineural invasion + deep extension important; (7) **Treatment**: - **Low-risk**: surgical excision with margins (4 mm), curettage + electrodesiccation; - **High-risk** (H-zone face, larger > 2 cm trunk, recurrent, aggressive subtypes, PNI, immunosuppressed): **Mohs micrographic surgery** (preferred), wider excision; - **RT** for non-surgical candidates; - **Topical** imiquimod / 5-FU for superficial BCC; PDT; - **Locally advanced/metastatic**: **Hedgehog inhibitors** (vismodegib, sonidegib); - **Immunotherapy** (cemiplimab) approved for HHi-refractory or intolerant; (8) **Surveillance**: yearly full skin exam (high risk for second BCC + other skin ca); sun protection; (9) **Gorlin syndrome**: genetic testing + multi-disciplinary

---

BCC: basaloid + peripheral palisading + cleft; BerEP4+/BCL2+. HH pathway. Subtypes (nodular/infiltrative/morpheaform). Mohs for high-risk facial. HHi (vismodegib) + cemiplimab for advanced. Gorlin if multiple/young.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'pathology'
  and scenario = 'ผู้ป่วยอายุ 72 ปี — pearly papule with telangiectasias on nose × 1 year → shave biopsy: nests of basaloid cells with peripheral palisading + cleft (retraction) artifact + myxoid stroma; IHC: BerEP4+, EMA-, CK20-; การวินิจฉัยและการรักษา';

update public.mcq_questions
set choices = '[{"label":"A","text":"Tissue ดีขึ้น"},{"label":"B","text":"Tissue Fixation Principles"},{"label":"C","text":"Skip fixation"},{"label":"D","text":"Use boiling water"},{"label":"E","text":"Discard"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Tissue Fixation Principles: (1) **10% NBF (neutral buffered formalin)** = standard — cross-links proteins (methylene bridges) — penetrates ~ 1 mm/h — recommended **6-72 hours** fixation (per CAP/ASCO HER2/ER guidelines for breast); **cold ischemia time ≤ 1 hour** breast specimens; (2) **Over-fixation (> 72 h)**: degrades antigenicity (false-negative IHC for ER/HER2), fragments nucleic acids (poor PCR/NGS), but tissue stable for histology; (3) **Under-fixation**: incomplete penetration → autolysis center → poor morphology + variable IHC; (4) **Alternative fixatives**: - Bouin''s (picric acid) — better nuclear detail, but degrades nucleic acids — testes, bones; - Zenker''s (HgCl2) — sharper nuclei but mercury toxic, environmental; - B5 — hematopathology classic, mercury concern, fading use; - Alcohol-based (95% ethanol) — preserves nucleic acid better, used in cytology + molecular pathology — protects RNA; - **PAXgene Tissue System** — preserves DNA/RNA + morphology — for molecular pathology; - Frozen (snap-freeze) — best for molecular + immunofluorescence (renal, muscle, tumor banking); (5) **Processing**: dehydration (graded ethanols) → clearing (xylene) → paraffin infiltration → embedding → microtome sectioning (3-5 μm) → H&E stain; (6) **Decalcification for bone**: EDTA preferred (preserves IHC + molecular) vs acid (faster but damages); (7) **Quality assurance**: cold ischemia, fixation time, processing tracking essential for biomarker accuracy + reproducibility (CAP checklists)

---

10% NBF standard, 6-72h fixation; cold ischemia ≤1h for breast biomarkers. Over-fix degrades IHC + nucleic acids; under-fix → autolysis. Alternatives: Bouin''s (testes/bone), PAXgene (molecular), alcohol (cytology), frozen (IF/molecular). EDTA for bone.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'pathology'
  and scenario = 'นักศึกษาแพทย์สงสัยหลักการ tissue fixation และ processing: เนื้อเยื่อใส่ใน 10% neutral buffered formalin เกินไป 48 ชม จะมีผลอย่างไร และ alternatives สำหรับ molecular testing';

commit;
