-- ===============================================================
-- UPDATE chunk 8/8: rehab_medicine (25 questions)
-- ===============================================================

begin;

update public.mcq_questions
set choices = '[{"label":"A","text":"Blame individuals"},{"label":"B","text":"QI in Rehab — RCA + Improvement"},{"label":"C","text":"No analysis needed"},{"label":"D","text":"Single intervention"},{"label":"E","text":"No measurement"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** QI in Rehab — RCA + Improvement: (1) **QI cycle** (PDSA): - Plan (problem ID + analysis + intervention design); - Do (small-scale test); - Study (data analysis); - Act (scale + standardize or revise); (2) **Tools**: - **Fishbone (Ishikawa) diagram**: cause categories — people, process, equipment, environment, materials, methods, management; - **5 Whys**: drill down to root cause; - **Pareto chart**: 80/20 — focus on vital few; - **Process map / value stream mapping**: visualize workflow; - **Control charts** (SPC): track variation; - **FMEA** (Failure Mode and Effects Analysis): proactive risk; - **A3 problem-solving**: structured one-page; (3) **Adverse event analysis**: - **Root cause analysis (RCA)**: post-event systematic + non-punitive (just culture) + identify systems factors + corrective actions + tracking; - **"Sharp end" (proximal — clinician)** vs **"blunt end" (latent — system)**: address both; - **Hindsight bias** beware; (4) **High-reliability organization (HRO) principles**: - Preoccupation w/ failure; - Reluctance to simplify; - Sensitivity to operations; - Commitment to resilience; - Deference to expertise; (5) **Improvement methodologies**: - **Lean** (waste reduction: defects, overproduction, waiting, non-utilized talent, transportation, inventory, motion, extra-processing — DOWNTIME); - **Six Sigma** (DMAIC — Define, Measure, Analyze, Improve, Control); - **Hybrid Lean Six Sigma**; - **Theory of constraints**; (6) **Rehab-specific applications**: - Reducing falls; - Pressure injury prevention; - Sepsis recognition + treatment; - Hospital-acquired conditions; - Discharge efficiency + planning; - Re-admission reduction; - Patient experience improvement; - Throughput + flow; - Team communication; (7) **Patient + family involvement**: co-design; (8) **Data + measurement**: pre/post + control + sustainability; (9) **Sustainability**: standardization, training, monitoring, leadership; (10) **Spread** + scaling successful interventions; (11) **Culture**: just + learning + psychological safety; **Modern**: data-driven + AI-enabled + co-designed + sustainable

---

QI: PDSA cycle. Tools (fishbone, 5 Whys, Pareto, process map, FMEA, A3). RCA non-punitive (just culture) — sharp + blunt end. HRO principles. Lean (DOWNTIME) + Six Sigma (DMAIC). Apps falls/PrI/sepsis/DC. Patient involvement. Sustainability. Modern: data-driven.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'rehab_medicine'
  and scenario = 'Quality improvement project — root cause analysis + interventions';

update public.mcq_questions
set choices = '[{"label":"A","text":"No disparities exist"},{"label":"B","text":"Rehab Equity + Disparities"},{"label":"C","text":"Equity not relevant rehab"},{"label":"D","text":"No interventions possible"},{"label":"E","text":"Single solution"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Rehab Equity + Disparities: (1) **Disparities documented**: - **Access**: rural, rural, racial/ethnic minorities, lower SES, Medicaid, uninsured, language barriers, disabilities, LGBTQ+ — less likely to receive IRF, intensive rehab; - **Outcomes**: poorer functional gains, longer LOS, higher complications; - **Specific conditions**: stroke, SCI, TBI, hip fx; (2) **Social Determinants of Health (SDOH)**: housing, food security, transportation, employment, education, social support, environment, healthcare access — major drivers; (3) **Structural racism + systemic factors**: historical + ongoing; healthcare embedded; (4) **Frameworks**: - **Healthy People 2030** SDOH focus; - **IHI Triple Aim + Quadruple Aim** + Health Equity (Quintuple); - **CMS Office of Minority Health**; - **WHO Commission Social Determinants**; (5) **Interventions to reduce disparities in rehab**: - **Screen for SDOH** routinely (CMS now requires hospitals); - **Address language** (interpreters, translated materials, bilingual staff); - **Cultural humility + competency training**; - **Workforce diversity**; - **Community partnerships**: CHWs (community health workers), peer mentors, faith-based; - **Telehealth + technology** w/ digital equity considerations; - **Mobile + community-based rehab**; - **Insurance navigation + financial assistance**; - **Transportation programs**: paratransit + ride-share; - **Universal design + accessibility**; - **Advocacy + policy**: insurance coverage, ADA enforcement, accessibility; (6) **Quality measurement disaggregated** by race/ethnicity/language/disability/insurance — track + address disparities; (7) **Patient + family voice + co-design**: lived experience input; (8) **Disability community**: "nothing about us without us" — incorporating disability community perspectives + leadership; (9) **Inclusive research**: representation in clinical trials + outcomes; (10) **Continuous learning + improvement**: equity as core quality dimension; (11) **Funding + resources** advocacy: voc rehab, Medicaid, DME, durable medical equipment, long-term services + supports; **Modern**: integrated SDOH + equity + community-centered + policy advocacy

---

Rehab equity: documented disparities (access, outcomes — racial/SES/rural/disability). SDOH drivers. Frameworks (Healthy People 2030, Quintuple Aim, equity). Interventions: SDOH screening + language + cultural humility + community + telehealth equitable + policy. Disaggregated measurement. Disability community voice. Modern: integrated equity.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'rehab_medicine'
  and scenario = 'Healthcare disparities + equity in rehabilitation';

update public.mcq_questions
set choices = '[{"label":"A","text":"No preparedness needed"},{"label":"B","text":"Disaster + Emergency Preparedness Rehab"},{"label":"C","text":"Single facility only"},{"label":"D","text":"No equipment continuity"},{"label":"E","text":"Ignore disabilities"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Disaster + Emergency Preparedness Rehab: (1) **Rehab populations vulnerable**: SCI, TBI, stroke, MS, ALS, ventilator-dependent, complex equipment users — disproportionate impact; (2) **Preparedness planning**: - **Patient-level**: emergency plan + supplies (medications 14+ d, equipment, batteries, oxygen, formula, manual W/C backup, caregiver info, evacuation plan + accessibility), medical ID, registries (disability + medical needs); - **Facility-level**: emergency operations plan, mass casualty, evacuation, sheltering in place, business continuity, surge capacity, supply chain, mutual aid; - **System-level**: regional coordination, AHRQ, state HSPD, ESF-8 (Health + Medical); (3) **Common disasters**: natural (hurricane, flood, earthquake, wildfire, tornado), pandemic, mass casualty (mass shooting, bombing, MVC), infrastructure failure (power, water), cyber; (4) **Specific rehab considerations**: - Medication access (anticonvulsants, anti-spasmodics, baclofen pump — withdrawal emergency, antibiotics, autonomic medications); - Equipment continuity (W/C charging, ventilator, oxygen, suction, feeding pump, ITB pump); - Sheltering accessibility (ADA-compliant); - Transportation accessibility; - Communication needs (AAC, sign language, accessible alert systems); - Caregiver support; (5) **Mass casualty rehab response**: - Acute → rehab integration (e.g., post-Boston Marathon bombing amputees + burns + blast); - Surge in IRF, SNF, community rehab needs; - Mental health (PTSD, acute stress); - Community rehabilitation; (6) **Pandemic-specific (COVID-19 lessons)**: - PPE + infection control; - Telerehab expansion; - Post-acute COVID rehab needs (PASC); - ICU-AW + PICS surge; - Healthcare workforce wellness; - Health equity disparities amplified; (7) **Recovery + resilience**: long-term mental health + community + economic + functional impacts; rehab essential in recovery phase; (8) **Workforce preparedness + training**: emergency response training; (9) **Equity in disaster**: disabilities + minority + elderly + poor disproportionately impacted — explicit equity planning; (10) **International + humanitarian rehab**: post-conflict, refugees, displaced — capacity building (WHO, Handicap International, ICRC); **Modern**: integrated emergency + climate change adaptation + equity-focused

---

Disaster prep rehab: vulnerable populations. Patient + facility + system levels. Medication + equipment continuity (baclofen pump withdrawal!). Accessibility shelter + transport + comm. Mass casualty surge. Pandemic lessons. Equity. International. Modern: integrated.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'rehab_medicine'
  and scenario = 'Disaster + emergency preparedness — rehab services + considerations';

update public.mcq_questions
set choices = '[{"label":"A","text":"Blame culture"},{"label":"B","text":"Patient Safety Culture in Rehab"},{"label":"C","text":"No reporting needed"},{"label":"D","text":"Single safety champion"},{"label":"E","text":"No measurement"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Patient Safety Culture in Rehab: (1) **Definition**: organization values, attitudes, perceptions, competencies, behaviors related to safety; (2) **High-reliability** principles (Weick & Sutcliffe): preoccupation w/ failure, reluctance to simplify, sensitivity to operations, commitment to resilience, deference to expertise; (3) **Just culture**: balance accountability + system thinking; differentiate human error (console), at-risk behavior (coach), reckless behavior (discipline); avoid blame for honest mistakes — encourages reporting; (4) **Components of safety culture**: - **Leadership commitment** (CEO/CMO visible); - **Teamwork + communication**: TeamSTEPPS, SBAR, huddles, time-outs; - **Reporting culture**: anonymous + non-punitive event reporting + near-miss; - **Learning culture**: from events + sharing; - **Patient + family engagement**: partners in safety; - **Wellness + staffing** (burnout → errors); (5) **Measurement**: AHRQ Hospital Survey on Patient Safety Culture (HSOPSC), Safety Attitudes Questionnaire (SAQ), event rates, near-miss reports, harm rates; (6) **Common safety issues in rehab**: - Falls + injuries; - Pressure injuries; - Medication errors (polypharmacy + complex meds — baclofen pump, anticoagulation); - Equipment-related (W/C, transfer, lifts); - Infection (CAUTI, CLABSI, C. difficile); - VTE; - Communication failures (handoff); - Patient identification; - Restraint use; - Adverse drug events; (7) **Improvement strategies**: - Standardized protocols + bundles; - Checklists + time-outs; - Simulation training; - Root cause analysis (RCA) + corrective actions; - FMEA proactive risk assessment; - Walk-rounds (leadership); - Speak-up culture; - Patient + family engagement; (8) **Burnout + wellness** as safety issue: workforce well-being → patient safety; (9) **Equity in safety**: disparities documented + address; (10) **Continuous improvement**: feedback loops, transparency, learning organization; **Modern**: just culture + HRO + equity + workforce wellness + patient-engaged

---

Patient safety culture: HRO principles + just culture (differentiate error/at-risk/reckless). Leadership + teamwork (TeamSTEPPS, SBAR) + reporting + learning + patient engagement + wellness. AHRQ HSOPSC measure. Common issues + improvement strategies. Burnout = safety. Equity. Modern: just culture + wellness.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'rehab_medicine'
  and scenario = 'Patient safety culture in rehab — building + sustaining + just culture';

update public.mcq_questions
set choices = '[{"label":"A","text":"No standardization"},{"label":"B","text":"ICF Core Sets — Clinical Application"},{"label":"C","text":"Single category"},{"label":"D","text":"Not used clinically"},{"label":"E","text":"Replaces all assessment"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** ICF Core Sets — Clinical Application: (1) **ICF Core Sets**: condition-specific subsets of ICF categories most relevant — facilitate documentation + outcome + research + team communication; (2) **Brief vs Comprehensive Core Sets** for each condition: - Brief (~10-30 categories) for clinical use; - Comprehensive (~100+) for research; (3) **Common Core Sets**: stroke, SCI (acute, post-acute, chronic), TBI, MS, RA, OA, LBP, chronic pain, depression, diabetes, CV, cancer, geriatrics, vocational rehabilitation, post-acute; > 30+ developed; (4) **Application steps**: - Select appropriate Core Set; - Assessment of patient using each category w/ qualifier (0-4 severity); - Identify problems + facilitators + barriers; - Goal-setting + intervention planning + team communication; - Outcome measurement (re-rate post-intervention); (5) **Linkage rules**: linking outcome measures + EHR data to ICF — facilitates integration; (6) **Rehab Cycle**: Assessment (ICF-based) → Goal Setting → Intervention → Evaluation → re-cycle; promotes structured + patient-centered care; (7) **Goal-setting**: SMART within ICF framework — capture body + activity + participation + environmental + personal; (8) **Multidisciplinary team common language**: PT, OT, SLP, nursing, physician all use ICF terms; (9) **Outcome measurement linked to ICF**: PROMIS, FIM, condition-specific measures can be mapped; (10) **Documentation**: structured ICF-based progress notes + reports; (11) **Education**: training in ICF takes time; (12) **Strengths**: comprehensive + biopsychosocial + universal + non-stigmatizing language; (13) **Limitations**: complexity + time + need for tools + variable implementation; (14) **Examples by condition**: e.g., stroke Brief Core Set includes b110 consciousness, b144 memory, b730 muscle power, d450 walking, d540 dressing, d710 social interaction, e125 communication products, e310 immediate family + many more; **Modern**: e-rehabilitation w/ ICF + standardized + value-based + outcomes-tracked

---

ICF Core Sets: condition-specific subsets. Brief (clinical) vs Comprehensive (research). > 30 developed. Apply via Rehab Cycle (assess → goal → intervene → evaluate). SMART goals within ICF. Team common language. Outcome linkage. Documentation + education + value-based.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'rehab_medicine'
  and scenario = 'International Classification of Functioning (ICF) — clinical application + core sets';

update public.mcq_questions
set choices = '[{"label":"A","text":"Expert opinion only"},{"label":"B","text":"Evidence-Based Practice in Rehab"},{"label":"C","text":"No translation needed"},{"label":"D","text":"Single discipline research"},{"label":"E","text":"Ignore patient values"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Evidence-Based Practice in Rehab: (1) **EBP** (Sackett): integration of best research evidence + clinical expertise + patient values + circumstances; (2) **Levels of evidence**: - **Systematic reviews + meta-analyses** of RCTs (highest); - **RCTs**; - **Cohort studies**; - **Case-control**; - **Case series + reports**; - **Expert opinion** (lowest); (3) **Evidence in rehab — challenges**: - Heterogeneous interventions + patients; - Difficulty blinding (sham PT); - Variable outcomes; - Multidisciplinary interventions (complex); - Underfunded research; - Translation gap; (4) **5-step EBP process**: - Ask focused question (PICO — Population, Intervention, Comparison, Outcome); - Acquire evidence (PubMed, Cochrane, PEDro for PT, OTseeker for OT); - Appraise critically (CASP, GRADE for quality + strength); - Apply to patient; - Assess outcomes + adjust; (5) **Knowledge translation** (KT) — implementation science: - KT-A (Knowledge-to-Action) cycle; - Barriers + facilitators identification; - Strategies (audit + feedback, education, reminders, champions, decision support); - Sustainability + spread; (6) **Clinical practice guidelines** (CPGs) + clinical decision support; (7) **Patient-centered research**: PCORI, patient + family engagement, PROs, real-world data; (8) **Big data + AI**: registries, EHR analytics, machine learning for prediction + personalization; (9) **Practice-based research networks**: real-world evidence + improvement; (10) **Funding sources**: NIH (NCMRR), NIDILRR, PCORI, foundations, industry; (11) **Outcomes research + comparative effectiveness**; (12) **Cost-effectiveness + value-based care**: economic evaluation; (13) **Research training + mentorship + protected time**; (14) **Multidisciplinary research teams**; (15) **Equity in research**: representation, accessibility, community partnerships; **Modern**: implementation science + real-world + value-based + equity-focused

---

EBP rehab: integration evidence + expertise + values. Levels (SR/MA → RCT → cohort → case). 5-step PICO. Knowledge translation cycle. CPGs. Patient-centered research (PCORI). Big data + AI. Cost-effective + value. Equity. Modern: implementation + real-world.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'rehab_medicine'
  and scenario = 'Research + evidence-based practice in rehab — translating evidence to care';

update public.mcq_questions
set choices = '[{"label":"A","text":"Single profession"},{"label":"B","text":"Interprofessional Education + Workforce"},{"label":"C","text":"No IPE needed"},{"label":"D","text":"Burnout ignore"},{"label":"E","text":"No diversity"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Interprofessional Education + Workforce: (1) **Workforce challenges in rehab**: - Aging population — increased demand; - Workforce shortages (PT, OT, SLP, physiatry, rehab nursing); - Maldistribution (rural underserved); - Burnout + attrition; - Diversity gaps; (2) **Interprofessional education (IPE)** (WHO + IPEC core competencies): - **Values + ethics**: respect + dignity across professions; - **Roles + responsibilities**: clarity + understanding; - **Interprofessional communication**: effective + respectful; - **Teams + teamwork**: principles + processes; (3) **IPE modalities**: - Joint classroom teaching; - Simulation (interprofessional); - Clinical placement w/ multiple disciplines; - Case-based learning; - Service-learning; (4) **Continuing professional development** + CME/CEU requirements; specialty certification (ABPMR, ABPTS, AOTA, etc.); (5) **Mentorship + sponsorship**: critical for development + retention; (6) **Diversity, equity, inclusion (DEI)**: workforce demographics + inclusive culture + community partnership + pipeline programs + bias training; (7) **Burnout + wellness**: high in healthcare — interventions: workload management, organizational change, peer support, mental health, recognition; (8) **Leadership development**: distributed leadership, succession planning, training; (9) **Global health + workforce sharing**: humanitarian, capacity building (WHO), brain drain considerations; (10) **Technology + workforce**: telehealth opportunities + tools + AI augmentation; (11) **Scope of practice** evolution — task shifting, advanced practice, telerehab; (12) **Generational considerations**: Boomer to Gen Z workforce; (13) **Resilience + sustainability**: wellness as core; (14) **Patient + family + community as team**: extension of team beyond healthcare; (15) **Quintuple aim** focus: outcomes, experience, cost, workforce well-being, equity; **Modern**: IPE + DEI + wellness + flexible + value-based

---

Workforce + IPE: WHO/IPEC competencies (values, roles, comm, teamwork). Modalities (joint classroom, sim, clinical, case). DEI + burnout + leadership + global + tech + scope evolution + generations + resilience + community + Quintuple Aim. Modern: IPE + wellness.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'rehab_medicine'
  and scenario = 'Workforce + interprofessional education in rehab';

update public.mcq_questions
set choices = '[{"label":"A","text":"No AI in rehab"},{"label":"B","text":"AI + Digital Transformation in Rehab"},{"label":"C","text":"AI replaces clinicians"},{"label":"D","text":"No ethics needed"},{"label":"E","text":"Single application"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** AI + Digital Transformation in Rehab: (1) **Current applications**: - **EHR + clinical decision support**: documentation, alerts, evidence-based reminders; - **Telerehab platforms**: synchronous + async; - **Wearables + sensors**: gait, activity, falls, sleep, HR — continuous monitoring; - **Smart equipment**: robotic gait trainers, exoskeletons, smart prostheses (microprocessor knees, myoelectric w/ pattern recognition); - **Virtual + augmented reality**: motor + cognitive rehab, vestibular, pain (VR analgesia), exposure therapy; - **AI for imaging**: MRI/CT/X-ray interpretation; - **Predictive analytics**: risk stratification, prognosis, falls, re-admission; - **NLP**: clinical documentation, voice; - **Generative AI**: education, documentation assistance, patient communication; - **Brain-computer interface (BCI)**: severe motor disability; (2) **Emerging applications**: - **Personalized medicine**: genomics + biomarkers + AI; - **Digital therapeutics** (FDA-approved apps for specific conditions); - **Robotic surgery + rehab**; - **Smart homes + IoT**: aging-in-place, environmental control; - **Digital twins**: simulation + planning; (3) **Benefits**: personalization + access + efficiency + outcomes + engagement + scaling; (4) **Risks + ethics**: - **Privacy + data security** (HIPAA + beyond); - **Bias + equity**: training data + algorithm bias — disparities risk amplification; - **Transparency + explainability**: black-box AI; - **Accountability + liability**; - **Digital divide**: equity in access (rural, low SES, elderly, disabled); - **Overreliance + automation bias** — clinical judgment essential; - **Job displacement** considerations + reskilling; - **Patient agency + informed consent** for AI; (5) **Regulation evolving** (FDA SaMD — software as medical device); (6) **Implementation**: change management + training + workflow integration + outcomes evaluation; (7) **Multidisciplinary**: clinicians + IT + data science + ethics + patient + family; (8) **Continuous evaluation**: outcomes + safety + equity + efficiency; (9) **Patient + family engagement**: co-design; (10) **Workforce upskilling**: digital literacy; **Modern**: human-centered + equitable + ethical + integrated + evidence-based AI

---

Digital + AI in rehab: EHR + telerehab + wearables + smart equipment + VR/AR + AI imaging + predictive + NLP + GenAI + BCI. Benefits + risks (privacy + bias + transparency + equity + overreliance). Regulation evolving. Implementation + workforce + co-design. Modern: human-centered + ethical + equitable.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'rehab_medicine'
  and scenario = 'Digital transformation + AI in rehabilitation — applications + ethics';

update public.mcq_questions
set choices = '[{"label":"A","text":"Single discipline"},{"label":"B","text":"Multimorbid Stroke + HF + DM + CKD"},{"label":"C","text":"Bedrest"},{"label":"D","text":"Discharge no follow-up"},{"label":"E","text":"Aggressive workup w/o coordination"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Multimorbid Stroke + HF + DM + CKD: (1) **Multidisciplinary team**: physiatry + neurology + cardiology + endocrinology + nephrology + geriatrics + PT + OT + SLP + nursing + dietitian + pharmacy + psychology + social work + family; (2) **Stroke rehab core**: motor + cognitive + speech + ADL + dysphagia + secondary prevention; (3) **HF rehab integration**: - Coordinate w/ HF team; - GDMT optimization (ARNI/ACEi/ARB + BB + MRA + SGLT2i — last benefits CKD + DM also); - Exercise prescription RPE 11-13 + monitor weight + symptoms; - Daily weight + low Na + fluid management; (4) **DM optimization**: - Glycemic targets relaxed older (A1c 7-8%); - SGLT2i (CV + renal + HF benefit) + GLP-1 if able; - Avoid hypoglycemia + sulfonylurea; - Foot care + neuropathy assessment; - Nutrition; (5) **CKD considerations**: - Renal-adjusted dosing; - Avoid nephrotoxins (NSAIDs, contrast, aminoglycosides); - Fluid + Na + K balance; - Anemia + bone/mineral disease (CKD-MBD) management; - Coordinate nephrology + dialysis planning if approaching; (6) **Falls prevention**: comprehensive — multifactorial assessment + intervention; (7) **Polypharmacy review** (Beers + STOPP/START + ACB): - Statin + antiplatelet (post-stroke); - GDMT HF; - Anticoagulant if AF; - Adjust for CKD; - Deprescribe sedating + anticholinergic; (8) **Goals of care**: realistic function + QOL + values + advance planning; (9) **Caregiver + family education + respite**; (10) **Mental health**: depression high — screen + treat; (11) **Discharge planning**: home + services + community; (12) **Long-term**: continued multidisciplinary + chronic disease + transitions; (13) **Equity considerations**: SDOH; **Modern**: integrated chronic disease + rehab + value-based + technology-enabled

---

Multimorbid stroke + HF + DM + CKD: multidisciplinary integration. Stroke rehab + HF GDMT (SGLT2i benefits all) + DM (relaxed targets, SGLT2/GLP-1) + CKD (renal dosing, avoid nephrotoxin) + falls + polypharmacy + GoC + caregiver + mental health. Modern integrated.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'rehab_medicine'
  and scenario = 'ผู้ป่วยอายุ 70 ปี — stroke + HF + DM + chronic kidney disease + falls + polypharmacy — integrative rehab';

update public.mcq_questions
set choices = '[{"label":"A","text":"Single discipline"},{"label":"B","text":"Complex TBI + OUD + Mental Health + SDOH"},{"label":"C","text":"Discharge to shelter only"},{"label":"D","text":"Opioid escalation"},{"label":"E","text":"Bedrest"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Complex TBI + OUD + Mental Health + SDOH: (1) **Multidisciplinary integrated**: physiatry + neuropsych + addiction medicine + psychiatry + pain medicine + PT + OT + SLP + social work + housing navigator + peer support + spiritual care + family; (2) **TBI rehab**: cognitive (attention, memory, executive — APT, external aids), behavioral, mood, sleep, communication; (3) **Chronic pain**: multimodal opioid-sparing — adjuvants (gabapentinoid + TCA/SNRI + topical), PT + active, CBT/ACT/mindfulness, interventional selected; pain neuroscience education; (4) **OUD treatment** (integrated dual diagnosis): - **MAT (Medication for OUD)**: buprenorphine/naloxone (Suboxone) — gold standard; methadone (clinic-based); naltrexone (XR) for selected; - **Counseling + behavioral**: CBT, motivational interviewing, contingency management; - **Peer support + recovery community**; - **Harm reduction**: naloxone, syringe services if needed; - **Address pain w/ MAT** — buprenorphine has analgesic effects; coordinate w/ pain team; (5) **PTSD treatment**: trauma-focused CBT (CPT, PE), EMDR, SSRI/SNRI + prazosin (nightmares); (6) **Depression**: SSRI/SNRI, CBT, integrated; (7) **Sleep**: CBT-I, sleep hygiene; (8) **Suicide risk** assessment + safety planning; (9) **Housing — Housing First** model: stable housing first → engagement + treatment; supportive housing; navigate housing services + benefits; (10) **Social support + benefits + financial**: SS disability, food, transportation, ID; (11) **Trauma-informed care**: throughout — recognize trauma history (ACEs); (12) **Cultural humility + advocacy**; (13) **Outcome**: function + QOL + engagement + housing + recovery + mental health; (14) **Long-term integrated chronic care**; **Modern**: integrated + trauma-informed + harm reduction + Housing First + equity

---

TBI + OUD + PTSD + depression + homeless: integrated multidisciplinary + Housing First. TBI cog + pain multimodal + MAT buprenorphine + trauma-focused CBT + SSRI/SNRI + sleep + suicide risk + housing + benefits + trauma-informed + cultural humility. Modern: integrated equity.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'rehab_medicine'
  and scenario = 'ผู้ป่วยอายุ 55 ปี — TBI + chronic pain + opioid use disorder + PTSD + depression + homelessness';

update public.mcq_questions
set choices = '[{"label":"A","text":"Single specialist"},{"label":"B","text":"Complex Pediatric CP Comprehensive Care"},{"label":"C","text":"No family involvement"},{"label":"D","text":"Bedrest"},{"label":"E","text":"Discharge no follow-up"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Complex Pediatric CP Comprehensive Care: (1) **Multidisciplinary clinic + medical home**: pediatrician + dev-behavioral peds + physiatry + neurology + ortho + neurosurgery + GI + nutrition + ENT + ophthalmology + dentistry + PT + OT + SLP + special ed + social work + child life + family + caregivers; (2) **GMFCS IV considerations**: self-mobility limited; power w/c selected; transfers w/ assistance; need adaptive equipment + home modifications; (3) **Epilepsy management**: appropriate AED, ketogenic diet selected, VNS/RNS selected, surgery refractory; AED interaction w/ rehab meds (sedation, cognition); rescue plan; (4) **Cognitive/ID**: educational accommodations IEP, communication (AAC + assistive tech), behavioral support, family + school coordination; (5) **GI feeding**: dysphagia evaluation + management (SLP + GI), thickeners, modified textures, G-tube for safety + nutrition; GERD common (PPI selected); constipation (laxative regimen); nutritional optimization (dietitian); growth monitoring (specific CP curves); (6) **Scoliosis**: regular monitoring (radiograph); bracing limited evidence in neuromuscular; surgical fusion for progressive curves (typically > 50° + skeletal maturity considerations) — improves comfort + positioning + pulmonary; (7) **Pulmonary**: aspiration risk, recurrent pneumonia, restrictive lung disease (scoliosis + weakness), airway clearance + cough assist; vaccination; (8) **Hip surveillance**: regular radiograph — high dislocation risk GMFCS IV-V (40-90%); preventive (PT + BoNT + surgery for subluxation); (9) **Spasticity management**: BoNT focal, ITB for generalized severe; (10) **Pain assessment + management**: non-verbal — observational tools (FLACC, NCCPC); multimodal; (11) **Mental health + behavioral**: sleep, mood, behavior — comprehensive; (12) **Family support**: caregiver burden HIGH — respite + peer + mental health + financial + advocacy; siblings; (13) **Transition planning** to adult care (age 14+ start); (14) **Goals of care** + advance directives; (15) **Equity + advocacy**; **Modern**: medical home + family-centered + transition + integrated multidisciplinary

---

Complex peds CP GMFCS IV: multidisciplinary medical home. Epilepsy + ID + dysphagia/G-tube + scoliosis + pulm + hip surveillance + spasticity + non-verbal pain + mental health + caregiver burden (HIGH) + transition + GoC. Family-centered. Modern: medical home.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'rehab_medicine'
  and scenario = 'ผู้ป่วยเด็กอายุ 8 ปี — CP GMFCS IV + epilepsy + intellectual disability + GI feeding issues + scoliosis — family-centered care';

update public.mcq_questions
set choices = '[{"label":"A","text":"Standard antipsychotic for psychosis"},{"label":"B","text":"PD + Dementia + Falls + Caregiver"},{"label":"C","text":"Single specialty"},{"label":"D","text":"Bedrest"},{"label":"E","text":"Increase PD meds always"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** PD + Dementia + Falls + Caregiver: (1) **PDD vs DLB**: PDD if dementia > 1 yr after motor PD; DLB if cognition + motor < 1 yr; treatment similar; (2) **Multidisciplinary**: movement disorder neurology + physiatry + geriatrics + neuropsych + PT + OT + SLP + pharmacy + social work + palliative + family; (3) **PD motor**: levodopa mainstay + adjuncts (DA agonists, MAO-B selected); avoid amantadine + anticholinergics + DA agonists in dementia (worsen cognition + psychosis); DBS NOT appropriate w/ dementia usually; (4) **Cognitive treatment**: rivastigmine (FDA approved PDD), donepezil; (5) **Behavioral + psychotic symptoms** (BPSD + PD psychosis 40% w/ DLB/PDD): - **First**: rule out delirium contributors (infection, meds, dehydration, pain, sleep); - **Non-pharm** first; - **Pimavanserin** (FDA for PD psychosis — selective 5HT2A inverse agonist); - **Clozapine** (effective but agranulocytosis monitor); - **Quetiapine** (off-label); - **AVOID typical antipsychotics + most atypicals** in PDD/DLB (neuroleptic sensitivity — severe rxn); (6) **Falls** comprehensive: PT/OT balance + strength + home + cueing for freezing + equipment + footwear + vision + medication review (orthostatic — fludrocortisone/midodrine if BP issue); osteoporosis Tx; (7) **Sleep**: RBD treatment (melatonin, clonazepam selected), OSA, insomnia — CBT-I + melatonin (avoid benzo + zolpidem); (8) **Autonomic**: orthostatic hypotension + GI (constipation, gastroparesis) + bladder; (9) **Caregiver support — KEY**: education + skills + respite + peer + mental health + financial + advocacy; depression high; (10) **Goals of care + advance planning + palliative integration** (progressive neurodegenerative — hospice eligibility in advanced); (11) **Polypharmacy review** + careful additions; (12) **Driving + safety + finances + legal** capacity; (13) **Long-term care planning**; (14) **Equity + cultural** considerations; **Modern**: integrated + family-centered + palliative

---

PDD/DLB + falls + caregiver: PD meds careful (avoid amantadine/anticholinergic). Pimavanserin / clozapine for psychosis — AVOID typical AP (neuroleptic sensitivity!). Falls comprehensive. Sleep + autonomic. Caregiver support KEY. GoC + palliative + advance planning. Modern integrated.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'rehab_medicine'
  and scenario = 'ผู้ป่วยอายุ 60 ปี — Parkinson + dementia + multiple falls + caregiver stress + medication side effects';

update public.mcq_questions
set choices = '[{"label":"A","text":"Single discipline"},{"label":"B","text":"Polytrauma Comprehensive Integrative Care"},{"label":"C","text":"No family involvement"},{"label":"D","text":"Bedrest"},{"label":"E","text":"Discharge no follow-up"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Polytrauma Comprehensive Integrative Care: (1) **Polytrauma rehab — multiple major injuries simultaneously** — common military/veterans + MVC/blast injuries; VA Polytrauma System established; (2) **Multidisciplinary expanded team**: trauma + physiatry + neurology + neurosurgery + ortho + plastics + psychiatry + neuropsych + addiction + pain medicine + PT + OT + SLP + prosthetist + nursing + social work + spiritual + peer + family; (3) **SCI rehab**: ASIA/ISNCSCI + bladder/bowel + skin + autonomic + mobility + ADL + equipment; (4) **Amputee rehab**: stage-appropriate (residual limb + prosthesis selection + training); K-level + advanced prosthetic technology integration; TMR considerations; (5) **TBI rehab**: cognitive + behavioral + emotional + sleep + fatigue + headache + vestibular; severity-stratified; (6) **PTSD treatment**: trauma-focused CBT (CPT, PE), EMDR; SSRI/SNRI + prazosin (nightmares); integrated w/ rehab — graded exposure to triggers; (7) **Chronic pain multimodal**: neuropathic + nociceptive + phantom limb — multimodal opioid-sparing + interventional selected + CBT + mindfulness; (8) **Sleep + mood + substance use** screen + treat; (9) **Family support**: traumatic + ongoing — family therapy + education + respite + financial + advocacy; high divorce rate in polytrauma — preventive; (10) **Vocational + community reintegration**: voc rehab + supported employment + ADA accommodations + military transition (veterans); (11) **Driving evaluation** + adapted vehicle; (12) **Peer support** + survivor groups — key for recovery; (13) **Long-term comprehensive care**: lifelong + transitions; (14) **Goals of care + values + identity** discussion — life-altering; (15) **Spiritual care + meaning-making**; (16) **Outcome**: function + QOL + family + community + employment + mental health; **Modern**: VA Polytrauma model + integrated + peer-supported + trauma-informed

---

Polytrauma integrative: VA Polytrauma model. Multidisciplinary — SCI + amputee + TBI + PTSD + chronic pain + sleep/mood/substance + family + vocational + peer + spiritual. Trauma-focused CBT + EMDR. TMR + advanced prosthetics. Long-term. Modern: integrated trauma-informed.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'rehab_medicine'
  and scenario = 'ผู้ป่วยอายุ 30 ปี — SCI + traumatic amputation + TBI + PTSD + family disruption — polytrauma';

update public.mcq_questions
set choices = '[{"label":"A","text":"Discharge — survived cancer"},{"label":"B","text":"Cancer Survivorship + Multimorbid"},{"label":"C","text":"Single specialty"},{"label":"D","text":"Bedrest"},{"label":"E","text":"Aggressive without coordination"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Cancer Survivorship + Multimorbid: (1) **Multidisciplinary survivorship**: oncology + survivorship clinic + cardio-oncology + physiatry + cardiology + neuropsych + PT + OT + nutrition + psychology + social work + family; (2) **Cancer-specific late effects management**: - **Lymphedema** (BC-related): CDT + maintenance garment + skin care + exercise; - **CIPN**: duloxetine + exercise + PT/OT balance + fall prevention; - **Chemo-brain (cognitive)**: neuropsych assessment + cognitive rehab + external aids + accommodations; - **Cardiotoxicity** (anthracycline + radiation): cardiology surveillance (echo, biomarkers) + cardiac rehab; cardio-oncology integrated; - **Secondary malignancy risk**: surveillance schedules; - **Fertility/menopause issues**; - **Sexual health**; - **Endocrine** (chemo-induced); - **Psychosocial** (PTSD, depression, fear of recurrence); (3) **Cardiac rehab integrated**: post-MI Phase II then Phase III maintenance; risk factor modification; coordinate w/ cardio-oncology for treatment effects; (4) **Cognitive impairment** assessment + intervention; consider contributors (chemo, radiation, sleep, mood, meds, vascular); cognitive rehab + accommodations; (5) **Health behaviors**: exercise (key for cancer outcomes + CV + cognition + mood), nutrition (Mediterranean, plant-forward), weight management, smoking cessation, alcohol moderation, sleep, sun protection; (6) **Comprehensive long-term FU**: COG-like for adult survivors; care plan + treatment summary + surveillance + lifestyle; (7) **Mental health**: depression + anxiety + fear of recurrence — CBT, mindfulness, SSRI; peer support; (8) **Palliative integration** appropriate; (9) **Goals of care + advance planning** discussion appropriate; (10) **Equity considerations**: disparities in survivorship; (11) **Family + community**; **Modern**: integrated survivorship + value-based + tech-enabled + equity

---

Cancer survivorship + multimorbid: multidisciplinary integrated. Late effects (lymphedema, CIPN, chemo-brain, cardiotoxicity, 2° malignancy, fertility/sexual/endocrine). Cardiac rehab + cardio-oncology. Cognitive rehab. Health behaviors. Mental health. Palliative. Equity. Modern integrated.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'rehab_medicine'
  and scenario = 'ผู้ป่วยอายุ 65 ปี — cancer survivorship (breast + colorectal) + cardiac (post-MI) + cognitive impairment — integrative';

update public.mcq_questions
set choices = '[{"label":"A","text":"Single discipline"},{"label":"B","text":"Progressive MS Complex Integrative Care"},{"label":"C","text":"DMT alone"},{"label":"D","text":"No relationship address"},{"label":"E","text":"Bedrest"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Progressive MS Complex Integrative Care: (1) **Multidisciplinary MS clinic**: neurology MS + physiatry + PT + OT + SLP + urology + ophthalmology + neuropsych + psychiatry + sexual health + social work + voc rehab + family; (2) **Disease-modifying therapy (DMT)** discussion + selection (ocrelizumab for PPMS + active SPMS, siponimod selected, others); risk-benefit; (3) **Symptom-targeted multidisciplinary rehab**: - **Mobility + weakness**: PT + AFO + assistive devices + FES + dalfampridine; - **Spasticity**: stepwise + BoNT + ITB; - **Bladder/bowel**: urodynamics-guided + CIC + meds; - **Cognitive**: rehab + accommodations; - **Visual**: ophthalmology; - **Sexual**: counseling + PDE5i + lubrication + multidisciplinary; - **Sleep**: CBT-I + treat contributors; (4) **Chronic pain — multimodal**: neuropathic (gabapentin, pregabalin, duloxetine, amitriptyline, cannabinoids), MSK (PT, multimodal), spasms (baclofen + cool); opioid-sparing; CBT; mindfulness; PT; (5) **Depression treatment**: SSRI/SNRI + CBT + integrated rehab; suicide risk assessment; (6) **Relationship + family**: couples counseling, family education, intimacy + sexual counseling + adaptive strategies, role redefinition; high divorce rate — preventive support; peer support; (7) **Vocational**: voc rehab assessment + accommodations (ADA): scheduling, fatigue management, cooling, heat avoidance (Uthoff), telework, ergonomic + cognitive accommodations; supported employment for severe; (8) **Caregiver support**: education + respite + peer + mental health; (9) **Adaptive recreation + community** integration; (10) **Equipment + home modifications**; (11) **Wellness + lifestyle**: exercise (counters disease!), Mediterranean diet, smoking cessation, vitamin D, weight management, sleep, mood; (12) **Goals of care + advance planning** progressive disease; (13) **Driving**: cognitive + visual + motor; (14) **Health equity** + access advocacy; **Modern**: comprehensive MS clinic + symptom-targeted + lifestyle + DMT-integrated + family-centered

---

MS progressive integrative: comprehensive MS clinic. Symptom-targeted (mobility, spasticity, bladder, cognitive, visual, sexual, sleep) + pain multimodal + depression + relationship/family + vocational + caregiver + equipment + wellness + GoC. DMT integrated. Modern: family-centered.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'rehab_medicine'
  and scenario = 'ผู้ป่วยอายุ 45 ปี — MS progressive + chronic pain + depression + relationship + vocational issues';

update public.mcq_questions
set choices = '[{"label":"A","text":"Aggressive rehab without discussion"},{"label":"B","text":"Frail Elderly Integrative + Goals of Care"},{"label":"C","text":"No goals discussion"},{"label":"D","text":"Single discipline"},{"label":"E","text":"Bedrest"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Frail Elderly Integrative + Goals of Care: (1) **Comprehensive geriatric assessment (CGA)**: medical, functional (ADL, IADL, gait, balance), cognitive (MoCA), nutritional, polypharmacy, mood, sensory, social, environmental, advance directives, values; (2) **Multidisciplinary**: geriatrician + physiatry + PCP + PT + OT + dietitian + pharmacy + social work + chaplain + palliative + family + caregiver + nursing; (3) **Goals of care discussion** (Serious Illness Conversation Guide, Ariadne Labs): - Open-ended: "What''s most important to you?"; - Understanding (illness + prognosis); - Worries; - Sources of strength; - Critical abilities; - Trade-offs; - Family discussions; document; (4) **Advance care planning**: living will + healthcare POA + POLST/MOLST (specific medical orders — DNR/DNI, intubation, antibiotics, artificial nutrition); revisit periodically; (5) **Function-focused care**: maintain ADL/IADL where possible; energy conservation (4 P); adaptive equipment; home modifications; safety; (6) **Symptom management**: pain (multimodal — Beers-cautious), fatigue, dyspnea, depression, anxiety, sleep, constipation, anorexia; (7) **Polypharmacy review + deprescribing** (Beers, STOPP/START); align w/ goals; (8) **Hospitalization prevention**: care coordination, home health, telehealth, medication adherence, education, vaccination, fall prevention; (9) **Re-admission focus**: transitional care models (CMS); (10) **Hospice eligibility consideration**: prognosis ≤ 6 mo + comfort focus; hospice provides comprehensive home + team + meds + equipment + 24/7 + respite + bereavement; (11) **Caregiver burden + respite + mental health + financial + advocacy**; (12) **Cultural humility** + values; (13) **Spiritual care + meaning + dignity**; (14) **Equity + access**; (15) **Death + dying planning**: location preferences (often home), pronouncement, bereavement; **Modern**: integrated geriatric + palliative + value-based + family-centered + community-supported

---

Frail elderly integrative + GoC: CGA. Multidisciplinary + palliative. GoC discussion (Ariadne) + advance care planning (POLST). Function-focused. Symptom mgmt + deprescribe. Re-admission prevention. Hospice consideration. Caregiver + cultural + spiritual + equity. Modern integrated.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'rehab_medicine'
  and scenario = 'ผู้ป่วยอายุ 75 ปี — frail + multiple comorbidities + recurrent hospitalizations + goals of care discussion';

update public.mcq_questions
set choices = '[{"label":"A","text":"Pediatric care continues forever"},{"label":"B","text":"Adult w/ Down Syndrome + Transition Care"},{"label":"C","text":"No transition planning"},{"label":"D","text":"Single discipline"},{"label":"E","text":"Discharge"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Adult w/ Down Syndrome + Transition Care: (1) **Adult medical issues** in Down syndrome: - **Cardiac**: congenital + acquired (mitral valve, AS); echo periodic; - **Endocrine**: hypothyroidism (high — annual screen); DM; - **Hematologic**: leukemia (childhood — risk persists), polycythemia; - **GI**: celiac (5-15%, screen w/ symptoms), constipation, GERD; - **Atlantoaxial instability** (10-30%): symptomatic screening + flexion-extension XR — sports + surgical implications; - **Cervical spine** myelopathy risk; - **Sleep apnea** (high prevalence — PSG + CPAP/surgery); - **Vision** (cataracts, refractive, keratoconus): annual; - **Hearing loss**: annual; - **Dental**: regular; - **Mental health**: depression, anxiety, behavioral; OCD; psychosis selected; ADHD; autism comorbid; - **Early Alzheimer disease** (50+): screen — APP gene chromosome 21; (2) **Functional + cognitive variability**: ID + adaptive; ongoing assessment; (3) **Multidisciplinary adult clinic** (preferred): physiatry + adult medicine + cardiology + endocrinology + neurology + psychiatry + dentistry + ophthalmology + audiology + PT + OT + SLP + social work + family; (4) **Transition from pediatric (age 14+)**: gradual + planned + portable medical summary + adult-oriented; (5) **Functional optimization**: PT + OT + SLP + cognitive support + adaptive equipment + community integration + vocational (supported employment) + recreation; (6) **Family caregiver — aging considerations**: succession planning (future caregivers), special needs trust + financial, sibling involvement, adult day programs, group home transition planning, advance directives + GoC; (7) **Decision-making capacity** + supported decision-making frameworks vs guardianship; (8) **Healthy lifestyle**: exercise + Mediterranean + weight management + smoking cessation + sleep; (9) **Dementia screening** (modified for baseline ID): NTG-EDSD, CAMDEX-DS; reversible factors first; (10) **Advance care planning**: family-involved + simplified; (11) **Equity + advocacy + neurodiversity**; **Modern**: integrated adult medical home + family-centered + lifespan

---

Adult Down syndrome: cardiac + thyroid + AAI + OSA + vision/hearing + mental health + early AD screening. Multidisciplinary adult clinic. Transition from peds. Functional optimization + vocational. Family aging — succession planning, trust, group home, GoC. Decision-making support. Modern integrated.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'rehab_medicine'
  and scenario = 'ผู้ป่วยอายุ 35 ปี — Down syndrome adult + multiple comorbidities + transition adult care + family caregiver aging';

update public.mcq_questions
set choices = '[{"label":"A","text":"Surgery first-line"},{"label":"B","text":"Chronic LBP + Multiple Comorbidities Biopsychosocial Care"},{"label":"C","text":"Opioid escalation"},{"label":"D","text":"Single discipline"},{"label":"E","text":"Disability without trial"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Chronic LBP + Multiple Comorbidities Biopsychosocial Care: (1) **Biopsychosocial assessment**: bio (LBP + stenosis + DM + obesity), psychological (depression, fear-avoidance, catastrophizing), social (work, finances, family); (2) **Comprehensive multidisciplinary**: physiatry + pain medicine + PT + OT + psychology + dietitian + endocrinology + voc rehab + employer + family; (3) **LBP + stenosis approach**: - **Conservative** (most): PT (flexion-based for stenosis, McKenzie selected, core stabilization + general conditioning), pain education, multimodal pharmacology (NSAIDs cautious DM/CKD, gabapentin for neurogenic claudication evidence, opioid-sparing); - **Interventional**: epidural steroid (selected), facet/MBB/RFA for facet component; - **Surgical**: severe stenosis w/ disabling claudication or neuro deficit — laminectomy ± fusion; outcomes good in appropriate candidates; (4) **DM optimization + weight management**: GLP-1 RA (semaglutide, tirzepatide) — major benefit for both DM + weight + CV; nutrition + exercise; (5) **Obesity treatment**: lifestyle + GLP-1/dual + bariatric for severe — addresses multiple conditions; reduces LBP + improves function; (6) **Depression + fear-avoidance**: CBT (KEY) + SSRI/SNRI (duloxetine — also analgesic); pain neuroscience education; address catastrophizing; (7) **Exercise (KEY)**: general aerobic + resistance + flexibility — addresses LBP + DM + obesity + mood simultaneously; supervised initially → independent; (8) **Vocational rehab**: FCE + worksite + ergonomic + graded RTW + accommodations + voc rehab counselor + retraining selected; (9) **Sleep + stress management**: integral; (10) **Smoking cessation** + alcohol; (11) **Patient education + self-management**: chronic disease self-management programs (Stanford CDSMP); (12) **Address SDOH**; (13) **Long-term**: lifestyle changes + multidisciplinary support; (14) **Outcomes**: function (ODI, RMDQ), pain, RTW, weight, A1c, depression; **Modern**: biopsychosocial + lifestyle (GLP-1) + integrated chronic disease + value-based

---

Chronic LBP + DM + obesity + depression: biopsychosocial multidisciplinary. PT + interventional + selective surgery. GLP-1 RA major benefit (DM + weight). CBT + duloxetine for depression + pain. Exercise KEY (multiple conditions). Vocational. Self-management. Modern: lifestyle + integrated.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'rehab_medicine'
  and scenario = 'ผู้ป่วยอายุ 50 ปี — chronic LBP + lumbar stenosis + diabetes + obesity + depression + work disability';

update public.mcq_questions
set choices = '[{"label":"A","text":"Surgery delay 1 wk"},{"label":"B","text":"Geriatric Hip Fracture + Dementia Integrative"},{"label":"C","text":"Bedrest"},{"label":"D","text":"Single discipline"},{"label":"E","text":"No delirium prevention"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Geriatric Hip Fracture + Dementia Integrative: (1) **Multidisciplinary**: orthogeriatrics co-management (improves outcomes + reduces mortality): ortho + geriatrician + physiatry + nursing + PT + OT + nutrition + pharmacy + social work + palliative + family; (2) **Acute medical optimization + delirium**: - Surgery early (< 24-48 h) reduces mortality + morbidity + delirium; - HELP bundle for delirium prevention + management: orientation, mobility, sleep, hydration, vision/hearing aids, family; - Avoid contributors (anticholinergic, opioid excess, benzo); - Multimodal pain — opioid-sparing + nerve blocks (fascia iliaca, FNB); - Address: infection (UTI, pneumonia), constipation, urinary retention, dehydration, hypoxia, metabolic, withdrawal; - Continuous reassessment CAM; (3) **Mobilization day 1 (KEY)** w/ ortho + weight-bearing as appropriate (typically WBAT modern); reduces complications + improves outcomes; (4) **Dementia adaptations to rehab**: simple instructions + consistency + structure + family + cuing + supervision + safety + behavioral approaches; (5) **Falls prevention** comprehensive: multifactorial — medications, vision, environment, bone health, exercise; (6) **Bone health (KEY)** secondary prevention: - DEXA + osteoporosis Tx (bisphosphonate IV common, denosumab); - Vitamin D + Ca; - Fracture Liaison Service (FLS) reduces re-fracture 50%; (7) **Nutrition optimization**: protein 1.2-1.5 g/kg, oral nutrition supplements (evidence reduces complications); (8) **Pain management**: multimodal opioid-sparing (acetaminophen + nerve block + non-pharm + careful adjuvants); (9) **Caregiver support + education**: discharge planning + home safety + DME + community resources + respite + mental health; caregiver burden HIGH dementia; (10) **Discharge planning**: home w/ services vs SNF vs LTC — function + caregiver capacity + cognitive status; (11) **Goals of care + advance directives**: prognosis (25-30% mortality 1 yr); function trajectory; values; (12) **Palliative integration appropriate**; (13) **Multifactorial**: comprehensive integrated; (14) **Outcomes**: mortality, function, falls, re-admission, QOL, caregiver well-being; **Modern**: orthogeriatric co-management + FLS + integrated multidisciplinary + family-centered

---

Geriatric hip fx + dementia: orthogeriatrics co-management. Early surgery (< 24-48h). HELP bundle delirium prevent. Multimodal pain (nerve block). Mobilize day 1. Bone health + FLS 50% reduction. Nutrition. Caregiver. GoC. Modern: co-management + FLS.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'rehab_medicine'
  and scenario = 'ผู้ป่วยอายุ 70 ปี — post-hip fracture + dementia + delirium + falls history + caregiver burden';

update public.mcq_questions
set choices = '[{"label":"A","text":"Single discipline"},{"label":"B","text":"Refugee + SCI Trauma Integrative + Cultural"},{"label":"C","text":"Family interpreter only"},{"label":"D","text":"Discharge — refer elsewhere"},{"label":"E","text":"No cultural consideration"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Refugee + SCI Trauma Integrative + Cultural: (1) **Multidisciplinary culturally-humble team**: physiatry + neuropsych + trauma-informed mental health + cultural broker + interpreters + social work + immigration + community support + family + peer; (2) **Trauma-informed care principles** (SAMHSA): - Safety (physical + emotional); - Trustworthiness + transparency; - Peer support; - Collaboration; - Empowerment + voice + choice; - Cultural + historical + gender humility; (3) **SCI rehab core**: ASIA + bladder/bowel + skin + autonomic + mobility + ADL + equipment; (4) **PTSD treatment**: trauma-focused CBT (CPT, PE), EMDR; SSRI/SNRI + prazosin (nightmares); CULTURALLY-ADAPTED interventions essential; community-based + culturally-relevant; (5) **Language access** (KEY): qualified medical interpreters (not family for clinical), translated written materials, bilingual staff; (6) **Cultural humility + competency**: - Understanding values, beliefs, practices, family structure, religion, decision-making norms; - Avoiding assumptions; - Co-creating care plan; - Cultural broker/community liaison; - Address cultural conceptions of disability + rehabilitation + mental health; (7) **Immigration + insurance navigation**: - Refugee resettlement agencies; - Public insurance enrollment (Medicaid varies by state + status); - Charity care; - Volunteer + community providers; - Refugee health screening; (8) **Social determinants address**: - Housing (refugee resettlement + accessible); - Food security; - Transportation; - Employment + vocational rehab (work authorization + voc training + ESL); - Education + ESL; - Social connections + community + religious; (9) **Mental health**: trauma + adjustment + depression + grief + survivor + family separation; integrated; (10) **Family + community**: family reunification efforts; community + religious organizations; (11) **Peer support**: refugee + disability peer mentors; (12) **Spiritual care + meaning-making + hope**; (13) **Advocacy**: systemic + individual + policy; (14) **Long-term integrated care + community building**; **Modern**: trauma-informed + culturally-humble + community-partnered + equity-focused + integrated

---

Refugee SCI + PTSD: trauma-informed care (safety + trust + peer + collaboration + empowerment + culture). SCI core + culturally-adapted PTSD Tx. Medical interpreters + translated materials. Cultural humility. Immigration + insurance navigation. SDOH + community. Spiritual. Advocacy. Modern: equity-focused integrated.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'rehab_medicine'
  and scenario = 'ผู้ป่วยอายุ 25 ปี — refugee + SCI from war injury + PTSD + cultural + language + insurance issues';

update public.mcq_questions
set choices = '[{"label":"A","text":"Opioid escalation"},{"label":"B","text":"Multimorbid Central Sensitization Chronic Disease"},{"label":"C","text":"Single discipline"},{"label":"D","text":"Bedrest"},{"label":"E","text":"Discharge"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Multimorbid Central Sensitization Chronic Disease: (1) **Multidisciplinary team**: physiatry + pain medicine + rheumatology + sleep medicine + psychiatry + PT + OT + dietitian + psychology + social work + family; (2) **Central sensitization spectrum**: fibromyalgia + chronic widespread pain + IBS + chronic fatigue + migraine — overlapping mechanisms; (3) **Comprehensive assessment**: pain (multidimensional), function (PROMIS), mood (PHQ-9, GAD-7, PCS), sleep (PSQI, ISI, screen OSA), substance use; (4) **Sleep apnea diagnosis + treatment** (KEY): PSG, CPAP — improves pain + mood + cognition + CV + fatigue; addresses contributing factor; (5) **Weight management** integrated: nutrition (Mediterranean) + exercise + behavioral; GLP-1 RA (semaglutide/tirzepatide) — major benefit weight + cardiometabolic — also may reduce inflammation; bariatric surgery selected; (6) **Exercise — KEY** despite pain: aerobic (low-impact: walking, cycling, aquatic) + resistance + mind-body (yoga, Tai Chi); start LOW + go slow + sustain; helps pain + sleep + mood + weight + cardiometabolic; (7) **CBT/ACT/mindfulness**: KEY for chronic pain + depression + anxiety + sleep; pain neuroscience education; (8) **Pharmacotherapy rationalize**: - Duloxetine (SNRI) — pain + depression + fibromyalgia FDA; - Milnacipran or pregabalin for fibromyalgia FDA; - Amitriptyline; - SSRI for depression; - Avoid opioid + benzo; - Melatonin for sleep adjunct; - GLP-1 weight; (9) **Sleep**: CBT-I + sleep hygiene + treat OSA + treat contributors (pain, mood); (10) **Address mood + anxiety**: integrated; (11) **Self-management**: Stanford CDSMP, pacing, activity diary, peer support; (12) **Social + vocational support**: workplace accommodations, peer support, family education; (13) **Outcomes**: pain, function, sleep, mood, weight, cardiometabolic; (14) **Long-term integrated chronic disease model**; **Modern**: central sensitization framework + lifestyle (GLP-1 + exercise + sleep) + integrated multidisciplinary + value-based

---

Multimorbid chronic central sensitization: multidisciplinary. OSA Dx + CPAP KEY. Weight (GLP-1 major). Exercise KEY (low-impact start). CBT/ACT/mindfulness + PNE. Duloxetine/pregabalin FDA. Avoid opioid/benzo. CBT-I sleep. Self-management. Modern integrated.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'rehab_medicine'
  and scenario = 'ผู้ป่วยอายุ 60 ปี — chronic pain + fibromyalgia + obesity + sleep apnea + depression + anxiety — chronic disease';

update public.mcq_questions
set choices = '[{"label":"A","text":"Single discipline"},{"label":"B","text":"Adolescent TBI Comprehensive Care"},{"label":"C","text":"No school involvement"},{"label":"D","text":"Bedrest"},{"label":"E","text":"Discharge no transition"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Adolescent TBI Comprehensive Care: (1) **Adolescent considerations**: developmental stage (identity + autonomy + peer + risk-taking + brain development continues through 20s); psychosocial complexities; (2) **Multidisciplinary**: pediatric/adolescent physiatry + neurology + neuropsych + psychiatry + adolescent medicine + PT + OT + SLP + dietitian + special ed + school + family + adolescent + peer; (3) **Cognitive rehab**: APT, GMT, metacognitive strategies, external aids (apps + smartphone), tutoring + school re-integration; (4) **Behavioral + emotional**: TBI behavioral changes + adolescent + identity formation; CBT, behavioral interventions, family therapy, motivational interviewing; address contributors (sleep, mood, pain, substance); (5) **School re-integration**: - IEP/504 (US): accommodations — extended time, reduced workload, frequent breaks, quiet testing, scribe, note-taker, technology, modified schedule; - Gradual return + monitoring; - Education staff + peers; - Mental health support in school; (6) **Mental health**: depression, anxiety, PTSD common post-TBI + adolescent — screen + treat (CBT + SSRI selected); suicide risk assessment + safety planning; (7) **Sleep**: adolescent + TBI — common — CBT-I + sleep hygiene + screen OSA; melatonin selected; (8) **Substance use**: increased risk post-TBI; screen + integrated treatment; harm reduction; (9) **Driving**: cognitive + visual + motor + neuropsych evaluation + driving rehab; restrictions until ready; (10) **Vocational + future planning**: long-term — career considerations adapted to abilities; transition planning; (11) **Family support**: education + counseling + sibling + respite + financial; family adjustment; (12) **Adolescent autonomy + advocacy**: voice + choice + privacy + assent + emerging adulthood; (13) **Peer support + group**: TBI youth groups + general adolescent; (14) **Recreation + community + social**: meaningful activities; (15) **Long-term FU through transition to adult care**; (16) **Equity + advocacy**: school + community + insurance; **Modern**: adolescent-centered + family + school-integrated + transition-focused

---

Adolescent TBI: developmental considerations. Multidisciplinary + family + school. Cognitive rehab + external aids. Behavioral + emotional + identity. School re-integration IEP/504. Mental health + suicide + sleep + substance use. Driving. Vocational + transition. Family. Peer. Modern: adolescent-centered.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'rehab_medicine'
  and scenario = 'เด็กอายุ 16 ปี — post-traumatic brain injury + behavioral + academic decline + family + school issues — adolescent rehab';

update public.mcq_questions
set choices = '[{"label":"A","text":"Amputate primarily"},{"label":"B","text":"Diabetic Foot + Limb Preservation Integrative"},{"label":"C","text":"Single discipline"},{"label":"D","text":"No offloading"},{"label":"E","text":"Discharge"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Diabetic Foot + Limb Preservation Integrative: (1) **High-risk diabetic foot**: prior amputation = highest contralateral risk (~50% in 5 yr); urgent + comprehensive prevention + management; (2) **Multidisciplinary limb preservation team**: podiatry + vascular surgery + endocrinology + ID + WOCN + plastic surgery + nutrition + physiatry + PT + OT + prosthetist + nursing + diabetes educator + behavioral health + family; (3) **Ulcer management**: - **Wagner/UT classification**; - **TIME framework**: tissue debridement + infection control + moisture balance + edge advancement; - **Sharp debridement**; - **Dressings**: depth + exudate-matched (alginate, foam, hydrogel, antimicrobial selected); - **NPWT** (VAC) for deep + cavitary; - **Offloading (KEY)**: total contact cast (TCC) gold standard, removable cast walker, healing sandals — without consistent offloading wound won''t heal; - **Infection management**: clinical + sometimes biopsy; oral abx for mild, IV for deep + systemic; osteomyelitis (probe-to-bone, MRI) — long course IV or oral; surgical debridement; - **Adjunctive**: HBO selected (Wagner 3+), biologics (Apligraf, Dermagraft, PRP), skin graft, flap; (4) **Vascular optimization**: ABI, duplex, angiography — revascularization (endovascular preferred where feasible, open bypass selected) — critical for healing CLI; (5) **Glycemic + metabolic**: A1c < 7-8% (older relaxed) — SGLT2i + GLP-1 + others; nutrition + protein + micronutrients (vit D, zinc, vit C); smoking cessation CRITICAL; (6) **Pain management**: neuropathic (gabapentinoid, SNRI, TCA, topical) + procedural (during dressing changes) + opioid-sparing; (7) **Footwear + offloading long-term**: custom diabetic shoes + insoles + accommodative (Medicare benefit); (8) **Education + self-monitoring**: daily inspection (mirror), no barefoot, shoe checks, prompt reporting any wound; (9) **Patient + family + caregiver education + adherence + access**; (10) **Mental health + social**: depression high; address SDOH; (11) **Cardiac + renal optimization**: high-risk CV + CKD; (12) **Long-term**: lifelong surveillance + multidisciplinary; (13) **Outcomes**: healing, infection control, limb salvage, mortality, function, QOL; **Modern**: integrated limb preservation team + advanced therapeutics + tele-monitoring

---

Diabetic foot + limb preservation: multidisciplinary team. Ulcer mgmt — TIME + debride + offload TCC (KEY) + infection + adjunctive (NPWT, HBO, biologics). Vascular optimization (revasc). Glycemic + smoking. Pain. Footwear. Education. Mental health. Modern: integrated limb preservation team.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'rehab_medicine'
  and scenario = 'ผู้ป่วยอายุ 70 ปี — diabetes + PAD + diabetic foot ulcer + previous amputation + chronic pain — limb preservation';

update public.mcq_questions
set choices = '[{"label":"A","text":"Single discipline"},{"label":"B","text":"Geriatric Dyadic Care + Advance Planning"},{"label":"C","text":"Patient only — no caregiver"},{"label":"D","text":"Aggressive without planning"},{"label":"E","text":"No GoC"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Geriatric Dyadic Care + Advance Planning: (1) **Dyadic care approach**: patient + primary caregiver as unit of care — both have needs + influence each other; (2) **Comprehensive geriatric assessment** (patient + caregiver): - Patient: medical + functional + cognitive + psychosocial + advance directives + values; - Caregiver: physical health + mental health + Zarit Burden + skills + resources + respite needs + employment; (3) **Multidisciplinary**: geriatrician + physiatry + PT + OT + nursing + dietitian + pharmacy + social work + chaplain + palliative + family; (4) **Chronic pain management**: multimodal opioid-sparing (acetaminophen + topical + gabapentinoid careful + duloxetine), non-pharm (PT, CBT, mindfulness, modalities), interventional selected; Beers + STOPP/START careful; (5) **Cognitive decline assessment + treatment**: - Etiology workup (reversible — meds, B12, thyroid, depression); - Cholinesterase inhibitors selected; - Non-pharm first BPSD; - Address contributors; - Cognitive + functional accommodations; - Safety + supervision + driving + finances + legal; (6) **Polypharmacy** review + deprescribe; (7) **Functional optimization**: PT + OT + adaptive equipment + home modifications + safety; (8) **Falls prevention** comprehensive; (9) **Caregiver support (KEY)**: - **Education + skills**: condition + caregiving + managing behaviors + symptoms; - **Respite care**: home + day + short-stay; - **Peer support + community**: Alzheimer Association + local groups; - **Mental health**: caregiver depression high — screen + treat; - **Financial + legal**: planning + benefits + special needs; - **Advance planning + GoC** for caregiver future; - **Acknowledgment + appreciation + recognition**; (10) **Advance care planning** (KEY): - Serious Illness Conversation Guide; - Living will + healthcare POA + POLST/MOLST; - Hospice eligibility consideration; - Cultural + spiritual considerations; - Re-visit periodically; - Family meetings; (11) **Palliative integration**; (12) **Long-term care planning**: in-home services, assisted living, nursing home as needed; (13) **Equity + access**; (14) **Continuity + transitions**: hospital + clinic + home + community + EOL; **Modern**: dyadic + integrated geriatric + palliative + value-based + family-centered + community-supported

---

Geriatric dyadic + advance planning: dyad = patient + caregiver. Comprehensive assessment both. Multidisciplinary + palliative. Chronic pain multimodal. Cognitive decline + reversible. Polypharmacy. Functional + falls. CAREGIVER SUPPORT KEY. Advance care planning (Serious Illness Conv). Long-term planning. Modern: dyadic + integrated.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'rehab_medicine'
  and scenario = 'ผู้ป่วยอายุ 80 ปี — multimorbid + caregiver dyad + chronic pain + cognitive decline + advance care planning';

update public.mcq_questions
set choices = '[{"label":"A","text":"Standard pregnancy management"},{"label":"B","text":"SCI + Pregnancy Integrative Care"},{"label":"C","text":"C-section all SCI"},{"label":"D","text":"No epidural"},{"label":"E","text":"Bedrest"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** SCI + Pregnancy Integrative Care: (1) **Multidisciplinary**: high-risk obstetrics + SCI specialist (physiatry) + neurology + urology + anesthesiology + nursing + PT + OT + nutrition + social work + family + peer + lactation; pre-conception planning ideal; (2) **Pregnancy considerations w/ SCI**: - **Bladder**: increased UTI risk — surveillance + treatment, optimize CIC + meds, anticholinergic safety pregnancy; - **Bowel**: constipation + impaction risk worsen — optimize program; - **Skin**: pressure injury risk — weight + posture changes + equipment adjustment; - **DVT/PE**: increased risk in pregnancy + SCI — prophylaxis + activity; - **Anemia + nutrition** monitor; - **Spasticity**: may worsen — adjust meds (some teratogenic — baclofen reasonable, careful gabapentin/pregabalin); - **Respiratory** (high SCI): assess VC + diaphragm; - **Equipment**: W/C modifications as belly grows; transfers more difficult; (3) **Autonomic dysreflexia (AD) — KEY risk in T6+** during pregnancy + labor: - Increased baseline frequency; - Triggers (UTI common, constipation, ROM, contractions during labor); - Labor — "silent labor" presentation w/ AD instead of pain; - Anesthesia: EPIDURAL ANALGESIA essential (T10+) — prevents AD via blocking afferents; (4) **Delivery planning**: - Vaginal delivery possible most SCI — assisted delivery (forceps/vacuum) common due to abdominal weakness; - C-section per OB indications; - Anesthesia plan; - Multidisciplinary in-hospital team; (5) **Postpartum**: - Skin + bladder + bowel + AD continued surveillance; - Breastfeeding (most can; T4+ may have milk let-down issues — adjustments); - Transfers + ADLs w/ infant — adaptive equipment + family/caregiver assistance; - Mental health postpartum (depression risk + SCI); (6) **Equipment + home modifications**: infant care + transfer + cribs adapted + carriers; (7) **Parenting + family adaptation**: peer mentors + family support + community resources; (8) **Long-term**: continuity for both SCI + parenting; (9) **Outcomes**: maternal-fetal health, function, satisfaction; **Modern**: pre-conception planning + specialized centers + peer support + family-centered

---

SCI + pregnancy: multidisciplinary high-risk OB + SCI. Bladder/bowel/skin/DVT/anemia/spasticity (med adjust)/respiratory/equipment. AD KEY risk T6+ labor — EPIDURAL essential. Vaginal delivery possible w/ assisted. Postpartum skin/AD/breastfeeding/mental health. Adaptive equipment infant care. Modern: integrated.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'rehab_medicine'
  and scenario = 'ผู้ป่วยอายุ 40 ปี — chronic spinal cord injury + new pregnancy + multidisciplinary planning';

commit;
