-- ===============================================================
-- UPDATE chunk 5/8: rehab_medicine (25 questions)
-- ===============================================================

begin;

update public.mcq_questions
set choices = '[{"label":"A","text":"Surgery first-line"},{"label":"B","text":"Meniere Disease — Multimodal"},{"label":"C","text":"VRT during acute attacks only"},{"label":"D","text":"No counseling"},{"label":"E","text":"Discharge"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Meniere Disease — Multimodal: (1) **Diagnosis (AAO-HNS 2015)**: definite — 2+ spontaneous vertigo episodes ≥ 20 min, fluctuating low-mid freq SNHL one ear, fluctuating aural symptoms; (2) **Management staged**: - **Diet + lifestyle**: low-Na (< 2 g/d) + reduce caffeine + alcohol + nicotine; stress reduction; - **Pharmacologic**: betahistine (limited evidence US), diuretic (HCTZ + triamterene — modest); intratympanic steroid for refractory; - **Vestibular suppressants** for acute episode only; antiemetics; - **Intratympanic gentamicin**: chemical ablation for refractory unilateral — risk hearing loss; - **Surgery**: endolymphatic sac decompression (limited evidence), labyrinthectomy (terminal, deaf), vestibular nerve section (selected hearing-sparing); (2) **VRT role**: between attacks for chronic imbalance + de-compensation; targets central compensation; not effective during acute; not first-line for vertigo episodes; (3) **Counseling**: episode management + safety (don''t drive during) + fall prevention; (4) **Hearing aid** + tinnitus management (sound therapy, CBT); (5) **Cognitive + psychological**: anxiety + depression high — CBT + SSRI; (6) **Multidisciplinary**: ENT + audiology + vestibular PT + psychology + physiatry; (7) **Education + advocacy + peer support**; (8) **Bilateral 30-50% over years**; **Modern**: stepped care + outcomes-driven + counseling integration

---

Meniere: stepped care. Diet (low Na) + diuretic + betahistine + intratympanic steroid → gentamicin/surgery refractory. VRT between attacks for de-compensation (not acute). Audiology + tinnitus + psych. Multidisciplinary.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'rehab_medicine'
  and scenario = 'ผู้ป่วย Meniere disease confirmed — fluctuating hearing + tinnitus + vertigo — referred VRT';

update public.mcq_questions
set choices = '[{"label":"A","text":"Surgery"},{"label":"B","text":"Vestibular Migraine — Diagnosis + Management"},{"label":"C","text":"No prevention — only acute"},{"label":"D","text":"Single discipline"},{"label":"E","text":"Bedrest"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Vestibular Migraine — Diagnosis + Management: (1) **Bárány Society + IHS criteria**: ≥ 5 episodes vestibular symptoms 5 min - 72 h moderate-severe + current/past migraine + migraine features in ≥ 50% (HA migraine type, photo/phonophobia, aura) + not better by other; (2) **Common — possibly most common cause episodic vertigo** + often missed; (3) **Treatment** — analogous to migraine: - **Lifestyle**: regular sleep + hydration + meals + exercise + stress management + trigger avoidance (caffeine, alcohol, MSG, aged cheese, others identified by diary); - **Acute**: triptans, NSAID, antiemetic, vestibular suppressant (limited); - **Preventive** (≥4 episodes/mo or significant disability): TCA (amitriptyline, nortriptyline), BB (propranolol, metoprolol), AED (topiramate, valproate), CCB (verapamil, flunarizine), CGRP mAb emerging selected; (4) **Vestibular rehab**: helpful for inter-ictal balance/imbalance + chronic dizziness; (5) **CBT** for chronic; (6) **Comorbidities**: anxiety/depression high — treat; PPPD overlap; sleep; (7) **Multidisciplinary**: neurology/HA + ENT + vestibular PT + physiatry + psychology; (8) **Headache diary** for identification + treatment response; (9) **Patient education**: chronic but manageable condition; (10) **Outcomes**: episode frequency, severity, function, DHI; **Modern**: CGRP-era + integrated care

---

Vestibular migraine: Bárány criteria. Likely most common episodic vertigo. Lifestyle + acute (triptan) + preventive (TCA/BB/AED/CCB/CGRP). VRT for inter-ictal. CBT + mood + sleep. Multidisciplinary. Modern: CGRP.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'rehab_medicine'
  and scenario = 'ผู้ป่วยอายุ 50 ปี vestibular migraine — episodic vertigo + headache + sound/light sensitivity';

update public.mcq_questions
set choices = '[{"label":"A","text":"Single discipline only"},{"label":"B","text":"Multifactorial Dizziness + Falls — Geriatric"},{"label":"C","text":"Medication alone"},{"label":"D","text":"Bedrest"},{"label":"E","text":"Discharge"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Multifactorial Dizziness + Falls — Geriatric: (1) **Multifactorial in elderly**: vestibular (bilateral vestibular hypofunction common — "presbyastasis"), proprioceptive (DM neuropathy, B12, cervical), visual (cataract, macular degen, contrast), CV (orthostatic, vasovagal), cognitive (executive, dual-task), polypharmacy (sedating, anticholinergic, antihypertensive, hypoglycemic), MSK (gait, weakness, sarcopenia); (2) **Comprehensive geriatric assessment**: gait, balance (Berg, TUG, mini-BESTest, FGA), vestib (vHIT, dynamic visual acuity, posturography), proprioception, vision, CV (orthostatic, ECG), cognition (MoCA), medication review (Beers, STOPP/START), home safety, social; (3) **Multimodal intervention**: - **Exercise + balance training** (KEY): Otago, Tai Chi, group classes, individualized PT; - **Vestibular rehab** if vestib component; - **Medication review** + deprescribing (Beers); - **Vision + hearing optimization**; - **Vitamin D + Ca** + bone health; - **Address orthostatic hypotension** (volume, compression, midodrine selected); - **Home safety + OT eval**; - **Footwear + assistive device** appropriate; - **Cognitive considerations**; (4) **Evidence**: multifactorial intervention reduces falls 30%+ (Cochrane); (5) **Multidisciplinary**: geriatrician + physiatry + PT + OT + neurology + cardiology + ophthalmology + pharmacy; (6) **CDC STEADI** framework; (7) **Education + family + community resources**; (8) **Outcome**: falls (diary), function, confidence (ABC scale); **Modern**: integrated comprehensive falls clinics + community programs

---

Multifactorial dizziness + falls elderly: comprehensive geriatric assessment. Multimodal — exercise/balance + VRT + meds deprescribe + vision/hearing + ortho/HoTN + vit D + home safety. Multidisciplinary. STEADI.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'rehab_medicine'
  and scenario = 'ผู้ป่วยอายุ 75 ปี chronic dizziness + multiple falls + multifactorial — geriatric vestibular evaluation';

update public.mcq_questions
set choices = '[{"label":"A","text":"Cast immobilization 6 wk"},{"label":"B","text":"Flexor Tendon Repair Zone II — Rehab"},{"label":"C","text":"Aggressive early active motion w/o protocol"},{"label":"D","text":"Discharge — no therapy"},{"label":"E","text":"Surgical revision day 14"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Flexor Tendon Repair Zone II — Rehab: (1) **Zone II ("no man''s land")**: fibro-osseous tunnel — historically poor outcomes due to adhesions; modern: early controlled motion essential; (2) **Modern strong repair** (4-6 strand core + epitendinous) tolerates early loading; (3) **Protocols**: - **Modified Duran (early passive motion)**: passive flex w/ hand therapist + dorsal blocking splint (wrist 20-30° flex, MCP 50-70° flex, IPs extended) × 4-6 wk; - **Kleinert (rubber-band traction)**: passive flexion via rubber band + active extension into splint; - **Early active motion (EAM)**: place-and-hold + true active — used w/ strong repairs (Indianapolis Saint Mary''s), Manchester protocols; better outcomes w/ modern repairs; (4) **Phased progression**: - 0-4 wk: dorsal block + early controlled motion; - 4-6 wk: composite + tendon glide; - 6-8 wk: discontinue splint + AROM, light functional; - 8-12 wk: strengthening progressive; - 12+ wk: return to full activity + heavy use; (5) **Hand therapist (CHT)** essential — protocols precise; (6) **Complications**: rupture (premature loading), adhesion (insufficient gliding), joint stiffness; (7) **Outcomes**: TAM (total active motion), strength, function (DASH, MHQ); (8) **Multidisciplinary**: hand surgeon + CHT + OT + patient/family education + adherence; (9) **Tenolysis** if adhesion-limited refractory; **Modern**: strong repair + early active motion + CHT

---

Flexor Z II: early controlled motion w/ dorsal block. Modified Duran/Kleinert/EAM. Strong modern repair tolerates EAM. Phased. CHT essential. Complications rupture vs adhesion. Outcomes TAM/DASH.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'rehab_medicine'
  and scenario = 'ผู้ป่วยอายุ 50 ปี post-flexor tendon repair Zone II 2 wk — hand therapy protocol';

update public.mcq_questions
set choices = '[{"label":"A","text":"Long-term opioid"},{"label":"B","text":"Carpal Tunnel Syndrome Management"},{"label":"C","text":"Casting 3 mo"},{"label":"D","text":"No treatment"},{"label":"E","text":"Discharge"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Carpal Tunnel Syndrome Management: (1) **Diagnosis**: symptoms (median distribution paresthesia, nocturnal, Phalen/Tinel/median compression test), exam (sensory, motor — thenar, two-point), EDS (NCS — distal latency, amplitude, axonal; EMG if motor); MSK US emerging; (2) **Severity**: mild (sensory + intermittent), moderate (positive EDS + frequent), severe (motor + atrophy + denervation); (3) **Management staged**: - **Mild-moderate**: nocturnal splint (neutral wrist), activity modification, ergonomics, NSAID short-term, gabapentin selected; - **Steroid injection**: temporary; diagnostic + therapeutic; multiple injections discouraged; - **Surgical (CTR)**: failed conservative ≥ 3-6 mo OR severe (motor, atrophy, advanced EDS) — open or endoscopic similar outcomes; (4) **Post-op rehab**: wound care + early ROM (no immobilization usually) + scar massage + gradual loading + return to activity 4-6 wk light, full 6-12 wk; (5) **Hand therapy** (CHT-led): tendon + nerve gliding exercises, ergonomics, education; (6) **Pre-op + post-op**: address contributors (DM, hypothyroidism, pregnancy resolves spontaneously, RA, obesity, repetitive); (7) **Severe atrophy**: opponensplasty selected; (8) **Outcomes**: BCTQ (Boston Carpal Tunnel Questionnaire), DASH, symptom resolution, return to work; (9) **Workers compensation**: ergonomic mod + RTW planning; **Modern**: US-guided injection + endoscopic + ultra-minimally invasive emerging

---

CTS staged: mild-mod splint + NSAID + ergonomics + steroid Inj. Surgical for failed conservative or severe. Post-op rehab + CHT. Contributors. BCTQ outcomes. Modern: US-guided + endoscopic.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'rehab_medicine'
  and scenario = 'ผู้ป่วยอายุ 55 ปี carpal tunnel syndrome moderate — failed splint + meds — considering options';

update public.mcq_questions
set choices = '[{"label":"A","text":"Bedrest"},{"label":"B","text":"Hueston tabletop test"},{"label":"C","text":"Single intervention without rehab"},{"label":"D","text":"Amputation first"},{"label":"E","text":"Discharge — no Tx"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Dupuytren Contracture: (1) **Pathology**: fibroproliferative disorder palmar fascia → nodules + cords + flexion contracture; genetic + northern European > African descent; risk DM, alcohol, smoking, age, male; (2) **Assessment**: nodule + cord exam, **Hueston tabletop test** (cannot lay hand flat → likely need intervention), MCP + PIP contracture measurement; functional impact; (3) **Indications for treatment**: MCP contracture ≥ 30°, any PIP contracture, functional limit; (4) **Treatment options**: - **Needle aponeurotomy (NA, percutaneous)**: in-office, immediate, MCP > PIP responsive, higher recurrence (50-80% 5 yr); - **Collagenase clostridium histolyticum (CCH)** — Xiaflex: enzyme injection + day 2-3 manipulation; effective; modest recurrence; pricey, availability varies; - **Open fasciectomy**: surgical removal cord/diseased fascia; lower recurrence (~20-30% at 5 yr); longer recovery, complications (nerve, skin, infection); - **Dermofasciectomy + skin graft**: severe/recurrent; - **PIP arthrodesis or amputation**: last resort severe long-standing; (5) **Post-procedure rehab — CHT-led**: splinting (extension), ROM (active + passive), edema, scar, functional; commitment important; (6) **Recurrence common** — discuss expectations; (7) **Address contributors**: DM, alcohol; (8) **Patient-centered selection**: trade-offs (recurrence vs invasiveness vs recovery time); **Modern**: minimally invasive options + early intervention + CHT

---

Dupuytren: tabletop test + contracture measure. Indications MCP ≥30° or PIP. Options: NA + CCH + fasciectomy + skin graft + arthrodesis. CHT post-procedure splint + ROM. Recurrence common. Patient-centered.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'rehab_medicine'
  and scenario = 'ผู้ป่วยอายุ 60 ปี Dupuytren contracture digit ring + small — flexion contracture MCP + PIP — functional';

update public.mcq_questions
set choices = '[{"label":"A","text":"Bedrest immobilization 6 wk"},{"label":"B","text":"Trigger Finger Management"},{"label":"C","text":"Inject into tendon directly"},{"label":"D","text":"Amputation"},{"label":"E","text":"Discharge"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Trigger Finger Management: (1) **Pathology**: stenosing tenosynovitis A1 pulley → triggering/locking finger flexor tendon; thumb common — FPL through A1; risk DM, RA, repetitive use; (2) **Quinnell grade**: 1 uneven motion → 2 actively correctable triggering → 3 passively correctable → 4 fixed contracture; (3) **Treatment stepwise**: - **Conservative**: activity modification, NSAID short-term, splint (MCP extension blocking 4-6 wk evidence in mild); - **Corticosteroid injection** into tendon sheath (NOT tendon — risk rupture): success 70-90% first injection, lower w/ repeated; DM lower success + caution glucose; - **Surgical release A1 pulley**: failed 2+ injections OR severe Gr 3-4 — open or percutaneous; excellent outcomes; (4) **Pediatric trigger thumb**: often resolves spontaneously; surgery after age 1-2 if persistent; (5) **Post-op**: early ROM + return to function 1-2 wk; CHT brief OK; (6) **Complications**: bowstringing rare, nerve, recurrence; (7) **DM** higher recurrence + failure → address glycemic; (8) **Multidigit involvement**: consider underlying (RA, DM, mucopolysaccharidoses); (9) **Patient education + ergonomics**; **Modern**: US-guided injection + percutaneous release

---

Trigger finger: A1 pulley tenosynovitis. Conservative (splint + NSAID) → steroid injection sheath (NOT tendon) 70-90% → surgical release. Quinnell grading. DM lower success. CHT brief. Modern: US-guided.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'rehab_medicine'
  and scenario = 'ผู้ป่วยอายุ 45 ปี trigger finger (stenosing tenosynovitis) — flexor digitorum profundus thumb — locking';

update public.mcq_questions
set choices = '[{"label":"A","text":"Cast 12 wk"},{"label":"B","text":"Post-Distal Radius Fracture (ORIF) Rehab"},{"label":"C","text":"Aggressive ROM immediately heavy"},{"label":"D","text":"No therapy"},{"label":"E","text":"Hospice"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Post-Distal Radius Fracture (ORIF) Rehab: (1) **Common fragility fracture** (post-menopausal, elderly); high-energy in young; (2) **Post-op phases**: - **0-2 wk**: protect, edema control (compression, elevation), pain, immobilization or removable splint depending stability, fingers ROM; - **2-6 wk**: progressive wrist + forearm ROM (active assisted → active), continued edema + scar mgmt; - **6-12 wk**: strengthening (progressive — putty → grippers → resisted), proprioception, functional, gradual loading; - **12+ wk**: heavy loading + return to sport/work; (3) **Hand therapist (CHT)** central; (4) **Common issues + management**: - **Stiffness**: dynamic + static splinting + ROM; - **CRPS** (5-30% risk): vit C 500 mg/d preventive (Zollinger); early identification + Tx (GMI, mobilization, multimodal); - **Tendon issues**: EPL rupture (~5%) — Lister tubercle; tendon transfer (EIP to EPL); - **Carpal tunnel** post-injury; - **Malunion** functional impact assessment; (5) **Functional rehab**: ADLs, work simulation, ergonomics; (6) **Pain**: multimodal opioid-sparing; (7) **Bone health**: DXA + osteoporosis Tx in fragility fx (FLS — fracture liaison service); fall prevention; (8) **Outcomes**: PRWE, DASH, ROM, grip strength; (9) **Address contributors**: smoking, vit D, nutrition; **Modern**: early motion + CRPS prevention + bone health integration

---

DRF ORIF rehab: phased — protect + edema → ROM → strengthening → return. CHT central. Stiffness + CRPS (vit C prevention) + EPL rupture + carpal tunnel risks. Bone health FLS. PRWE/DASH outcomes.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'rehab_medicine'
  and scenario = 'ผู้ป่วยอายุ 50 ปี post-distal radius fracture (intra-articular) ORIF 6 wk — hand therapy';

update public.mcq_questions
set choices = '[{"label":"A","text":"Bedrest — prevent falls"},{"label":"B","text":"Falls — Comprehensive Multifactorial Assessment + Intervention"},{"label":"C","text":"Single intervention"},{"label":"D","text":"Restraints continuous"},{"label":"E","text":"Discharge — no follow-up"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Falls — Comprehensive Multifactorial Assessment + Intervention: (1) **AGS/BGS + CDC STEADI** approach; (2) **Screening (annual)**: 3 questions (falls past yr, fear, unsteadiness); (3) **Multifactorial assessment** for high-risk: - History + circumstances of falls + meds + comorbidities; - **Gait + balance**: TUG (>13.5 s risk), 5× sit-to-stand, BBS, gait speed, FGA, mini-BESTest, dynamic gait; - **Strength**: 5× STS, hand grip; - **Cognition**: MoCA + executive; - **Vision**: acuity, contrast; - **Hearing**; - **Vestibular**: vHIT, posturography; - **Proprioception** + sensory; - **CV**: orthostatic vital signs, ECG; - **Foot + footwear**; - **Polypharmacy** (Beers, STOPP/START — FRIDS: fall-risk-increasing drugs); - **Home environment**; - **Mood + sleep**; - **Bone health + vit D + Ca**; - **Continence**; - **Social**; (4) **Multifactorial Intervention** (KEY — strong evidence): - **Exercise** (strongest): Otago, Tai Chi (especially), group + individualized + balance + strength; - **Medication review + deprescribing**; - **Vision + hearing optimization**; - **Vitamin D ≥ 800-1000 IU/d** if deficient; - **Home modifications** (OT); - **Cataract surgery**; - **Cardiovascular Tx** (pacemaker if syncope/cardioinhibitory); - **Footwear** + assistive devices; - **Cognitive considerations**; (5) **Bone health** (osteoporosis Tx, fracture liaison); (6) **Multidisciplinary**: geriatrician + physiatry + PT + OT + pharmacy + neurology + cardiology + ophth + audiology; (7) **Family + caregiver education + community resources**; (8) **Outcomes**: falls (diary), function, fear (ABC), confidence; **Modern**: comprehensive falls clinics + community + technology (wearables, AI)

---

Falls multifactorial: AGS/CDC STEADI. Comprehensive assessment + multifactorial intervention (Cochrane reduces 30%). Exercise (Tai Chi, Otago) KEY. Deprescribe FRIDS. Vision + vit D + home + bone health. Multidisciplinary.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'rehab_medicine'
  and scenario = 'ผู้ป่วยอายุ 80 ปี recurrent falls 3× past 6 mo — multifactorial — comprehensive evaluation';

update public.mcq_questions
set choices = '[{"label":"A","text":"Bedrest"},{"label":"B","text":"Sarcopenia + Frailty Management"},{"label":"C","text":"Single discipline"},{"label":"D","text":"Nutritional supplement only"},{"label":"E","text":"Discharge no intervention"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Sarcopenia + Frailty Management: (1) **Definitions**: - **Sarcopenia** (EWGSOP2 2019): low muscle strength (grip, chair stand) + low muscle quantity (DXA, BIA, US, MRI) + low physical performance (gait speed, SPPB, TUG) — confirmatory; - **Frailty** (Fried 5 phenotype): weight loss, exhaustion, weakness (grip), slowness, low activity; or accumulation index (Rockwood); (2) **Assessment**: SARC-F screen (sarcopenia), CFS (Clinical Frailty Scale), comprehensive geriatric assessment; (3) **Multimodal intervention (KEY)**: - **Exercise — resistance** training (1-3 sets, 8-12 reps, 2-3 d/wk, 60-80% 1RM) — STRONGEST evidence; + aerobic + balance; - **Nutritional**: protein 1.0-1.5 g/kg/d (higher in older), leucine-enriched + amino acids, vitamin D supplementation (≥ 800-1000 IU/d if deficient), adequate calories; - **Address comorbidities**: chronic disease, polypharmacy, mood, sleep, social isolation; - **Polypharmacy review** + deprescribing; (4) **Specific pharmacotherapy**: investigational (myostatin inhibitors, anamorelin); testosterone selected; (5) **Cognitive + mood**; (6) **Social** + community programs + group exercise; (7) **Multidisciplinary**: geriatrician + physiatry + PT + dietitian + pharmacy + social work + nursing; (8) **Outcomes**: SPPB, gait speed, grip, IADL, falls, hospitalizations; (9) **Goals of care** + advance planning + values; (10) **Family + caregiver**; **Modern**: integrated geriatric rehab + community + technology-enabled

---

Sarcopenia/frailty: EWGSOP2 + Fried/Rockwood. SARC-F + CFS. Multimodal: resistance exercise STRONGEST + protein 1.0-1.5 + vit D + address comorbidity + deprescribe + social. Multidisciplinary. SPPB outcomes.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'rehab_medicine'
  and scenario = 'ผู้ป่วยอายุ 78 ปี frailty + sarcopenia + dependent ADL trajectory — community-dwelling';

update public.mcq_questions
set choices = '[{"label":"A","text":"Standard rehab no adaptations"},{"label":"B","text":"Cognitive Impairment Rehab Adaptations"},{"label":"C","text":"Sedate continuously"},{"label":"D","text":"Bedrest"},{"label":"E","text":"Discharge"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Cognitive Impairment Rehab Adaptations: (1) **Comprehensive evaluation**: cognitive (MoCA, MMSE, neuropsych), function (IADL, ADL), behavior, mood, safety, caregiver; etiology (Alzheimer''s, vascular, Lewy body, FTD); medication review; (2) **Rehab adaptations**: - Simple + clear instructions, one step at a time; - Demonstration + tactile cuing; - Consistent staff + routine + environment; - Visual + auditory cues + reminders; - Errorless learning + spaced retrieval (good evidence MCI/early); - Task-specific functional training; - Environmental modifications (signs, labels, simplified); - Shorter, more frequent sessions; - Family + caregiver engagement central; (3) **Exercise**: aerobic + resistance + balance — preserves function, mood, possibly cognition (mixed evidence MCI/dementia); group classes; supervision; (4) **OT**: ADL retraining + adaptive equipment + home safety + cognitive aids (apps, calendars, reminders); (5) **PT**: gait, balance, falls prevention; (6) **SLP**: communication + swallow assessment + cognitive-communication; (7) **Mood**: depression high in dementia — non-pharm first + SSRI selected; (8) **Behavioral + psychological symptoms (BPSD)**: identify triggers + behavioral approaches first; cautious pharm (avoid antipsychotic when possible — boxed warning); (9) **Caregiver education + support + respite**; (10) **Goals of care + advance directives**: stage-appropriate; (11) **Driving + safety + finances + legal**; (12) **Multidisciplinary**: geriatrician/cognitive neurology + physiatry + PT + OT + SLP + neuropsych + social work + family; **Modern**: person-centered + dementia-friendly care + caregiver-focused

---

Cognitive impairment rehab: adaptations (simple + routine + cues + errorless learning + family). Exercise preserves function. OT + PT + SLP. Mood + BPSD non-pharm first. Caregiver. GoC. Multidisciplinary. Person-centered.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'rehab_medicine'
  and scenario = 'ผู้ป่วยอายุ 82 ปี mild cognitive impairment + early dementia — rehab considerations + adaptations';

update public.mcq_questions
set choices = '[{"label":"A","text":"Continue all medications"},{"label":"B","text":"Geriatric Polypharmacy + Deprescribing"},{"label":"C","text":"Discontinue all medications immediately"},{"label":"D","text":"No review"},{"label":"E","text":"Discharge"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Geriatric Polypharmacy + Deprescribing: (1) **Polypharmacy**: ≥5 meds — common in older + multimorbid; associated falls, ADRs, cognitive impairment, hospitalization, mortality, nonadherence; (2) **Comprehensive medication review**: - **Beers Criteria** (AGS): potentially inappropriate medications older adults — avoid or use w/ caution; - **STOPP/START** (European): STOPP = stop list; START = start list (e.g., bone health, anticoagulation indicated); - **MAI** (Medication Appropriateness Index); - Anticholinergic burden (ACB scale); - Drug-drug + drug-disease interactions; - Renal + hepatic dosing; (3) **Deprescribing process** (Reeve, Scott): - List all meds; - Identify potentially inappropriate; - Determine if can be deprescribed; - Plan + monitor + adjust; - Shared decision w/ patient + family; (4) **Common targets**: - **Benzodiazepines + Z-drugs**: falls, cognition — taper; - **Anticholinergics**: cognition; - **PPIs**: long-term re-evaluate; - **Antipsychotics for BPSD**: black box mortality; - **NSAIDs**: GI, renal, CV; - **Statins** if limited life expectancy + primary prevention discussion; - **Antihypertensives**: orthostatic risk — reassess targets; - **Antidiabetics**: hypoglycemia — relax A1c targets older; (5) **Critical not to under-prescribe**: pain, depression, bone health, anticoagulation when indicated; (6) **Multidisciplinary**: physiatry + geriatrician + pharmacy + PCP + nursing + family; (7) **Continuity** across transitions; (8) **Outcomes**: functional, falls, hospitalizations, QOL; **Modern**: technology (CDS — clinical decision support) + integrated team-based

---

Polypharmacy: Beers/STOPP/START + ACB. Deprescribing process: identify + assess + plan + monitor + shared decision. Common targets: benzo, anticholinergic, PPI, AP, NSAID, statin reassess. Avoid under-prescribing. Multidisciplinary.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'rehab_medicine'
  and scenario = 'ผู้ป่วยอายุ 80 ปี polypharmacy (15 medications) — referred for review + functional decline';

update public.mcq_questions
set choices = '[{"label":"A","text":"Sedate w/ benzodiazepine"},{"label":"B","text":"Delirium in Rehab Setting"},{"label":"C","text":"Bedrest"},{"label":"D","text":"Restraint primary"},{"label":"E","text":"Discontinue rehab"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Delirium in Rehab Setting: (1) **Detection**: CAM (Confusion Assessment Method) — acute change + fluctuating + inattention + (disorganized thinking OR altered LOC); 4AT brief; (2) **Hypoactive (more common older + missed) vs hyperactive vs mixed**; (3) **Etiology workup**: DELIRIUMS mnemonic + thorough search — infection (UTI, pneumonia, CDIff), meds (anticholinergic, opioid, benzo, steroid, polypharmacy), metabolic (Na, glucose, Ca, BUN/Cr), hypoxia, alcohol/sedative withdrawal, constipation/retention, pain, sleep disruption, sensory deprivation, hospital environment, stroke/TBI; (4) **Non-pharmacological FIRST (KEY)**: - **HELP/ABCDEF bundle elements**: orientation, mobility, sleep, hydration, vision/hearing aids, sensory, music, family presence, normalize environment; - Reduce restraint (use selectively); - Optimize meds — remove offending; - Treat pain (multimodal opioid-sparing); - Address constipation, urinary retention, sleep; - Family + familiar objects; (5) **Pharmacological** (only for severe agitation/safety when non-pharm fails): - Low-dose haloperidol (0.5-1 mg) — risk EPS + QTc; - Atypical (quetiapine, risperidone) — risk; - AVOID benzodiazepines (worsen except alcohol/sedative withdrawal) + anticholinergics; - Caution dexmedetomidine; (6) **Rehab adjustments**: continue mobility (helps delirium!), shorter sessions, structure, supervision, safety; (7) **Family + caregiver education + presence**; (8) **Post-delirium**: cognitive sequelae monitoring (PICS); (9) **Multidisciplinary**: geriatrician + physiatry + PT + OT + nursing + family + psych selected; **Modern**: ABCDEF + HELP + delirium-aware rehab

---

Delirium: CAM Dx. DELIRIUMS workup (meds, infection, metabolic, pain, sleep, urine/stool). Non-pharm FIRST (HELP, ABCDEF). Continue mobility. Pharm last resort low-dose AP. AVOID benzo. Family + multidisciplinary.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'rehab_medicine'
  and scenario = 'ผู้ป่วยอายุ 85 ปี delirium during inpatient rehab — interfering with progress';

update public.mcq_questions
set choices = '[{"label":"A","text":"Aggressive rehab to baseline"},{"label":"B","text":"End-of-Life + Home-Based Care"},{"label":"C","text":"Hospital LTC"},{"label":"D","text":"Single discipline"},{"label":"E","text":"Refuse home services"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** End-of-Life + Home-Based Care: (1) **Patient-centered + goals-based**: what matters most — function, comfort, dignity, family, location of death; advance directives + POLST/MOLST; (2) **Multidisciplinary team**: physiatry + palliative care/hospice + PCP + nursing + PT/OT + SLP + social work + chaplain + family + caregiver; (3) **Functional optimization within prognosis**: - Maintain mobility + ADL where possible; - Energy conservation (4 P); - Adaptive equipment + DME for home (hospital bed, W/C, commode, raised toilet, shower bench, lift); - Home modifications + safety; (4) **Symptom management**: pain (multimodal w/ adequate opioid in advanced disease), dyspnea (opioid, fan, position, O2 selected), nausea, constipation, anorexia, anxiety, depression; (5) **Caregiver education + support + respite + 24/7 contact**; (6) **Advance care planning + values discussion**: aligned care + avoid burdensome treatments; (7) **Spiritual care + meaning-making**: chaplain + family rituals; (8) **Hospice eligibility + transition**: prognosis ≤ 6 mo + comfort focus; hospice provides team + meds + equipment + 24/7 + respite + bereavement; (9) **Bereavement support**: family throughout + after; (10) **Cultural humility + preferences**; (11) **Death at home logistics**: pronouncement, mortuary, post-death support; (12) **Outcomes**: comfort, QOL, satisfaction, family well-being; **Modern**: integrated palliative rehab + home-based hospice + family-centered

---

End-of-life home: patient-centered + goals. Multidisciplinary including hospice. Functional optimization w/in prognosis. Symptom mgmt. Caregiver. Advance planning. Spiritual. Hospice eligibility. Bereavement. Cultural. Modern integrated.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'rehab_medicine'
  and scenario = 'ผู้ป่วยอายุ 78 ปี end-of-life — declining function + wishes to remain home — interdisciplinary planning';

update public.mcq_questions
set choices = '[{"label":"A","text":"Bedrest"},{"label":"B","text":"Parkinson Disease Rehab — Multidisciplinary"},{"label":"C","text":"Single discipline"},{"label":"D","text":"No exercise — risk falls"},{"label":"E","text":"Discharge"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Parkinson Disease Rehab — Multidisciplinary: (1) **Multidisciplinary**: movement disorder neurology + physiatry + PT + OT + SLP + neuropsych + nursing + social work + family; (2) **Stage-based** (Hoehn-Yahr): - Early: exercise + education + activity; - Mid (this patient): structured rehab + assistive devices; - Late: care needs + transitions; (3) **PT (evidence-based)**: - **LSVT BIG**: amplitude-based motor — 4 wk × 4 d/wk × 1 h evidence improves bradykinesia + gait + ADLs; - **Tango/dance therapy** — evidence; - **Tai Chi** — balance + falls; - **Aerobic + resistance**; - **Treadmill** training; - **Gait + cueing strategies for freezing**: auditory (metronome), visual (lines on floor), attention; large amplitude, conscious; weight-shifting; - **Balance + falls prevention**; (4) **OT**: ADLs, fine motor, handwriting (LSVT effective for micrographia), home safety; (5) **SLP**: - **LSVT LOUD**: voice amplitude — evidence improves loudness, intelligibility; - Dysphagia: VFSS/FEES + targeted therapy; - Cognitive-communication; (6) **Medication optimization**: levodopa + adjuncts (DA agonist, MAO-B, COMT); DBS for selected refractory; (7) **Non-motor symptoms**: depression (SSRI, ECT, rTMS), anxiety, sleep (RBD), constipation, autonomic, cognitive (donepezil/rivastigmine for PDD), psychosis (pimavanserin, clozapine, quetiapine — NOT typical AP); (8) **Caregiver + family support**; (9) **Advanced disease**: DBS, levodopa-carbidopa intestinal gel, apomorphine, palliative; (10) **Outcomes**: UPDRS, MDS-UPDRS, BERG, TUG, 10MWT, PDQ-39; **Modern**: LSVT + exercise + multidisciplinary + advanced therapies

---

PD rehab: stage-based multidisciplinary. LSVT BIG (PT) + LSVT LOUD (SLP) evidence-based. Tai Chi + dance. Cueing for freezing. OT + meds optimize + DBS selected. Non-motor. Caregiver. Modern integrated.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'rehab_medicine'
  and scenario = 'ผู้ป่วย Parkinson disease (Hoehn-Yahr 3) — gait freezing + falls + tremor — comprehensive rehab';

update public.mcq_questions
set choices = '[{"label":"A","text":"Avoid all exercise"},{"label":"B","text":"Multiple Sclerosis Rehab"},{"label":"C","text":"Single discipline"},{"label":"D","text":"Bedrest"},{"label":"E","text":"Discharge"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Multiple Sclerosis Rehab: (1) **Multidisciplinary**: neurology MS + physiatry + PT + OT + SLP + neuropsychology + urology + ophthalmology + psychiatry + social work + family; (2) **Symptom-targeted rehab**: - **Fatigue** (KEY symptom): energy conservation (4 P), graded aerobic + resistance exercise (NOT contraindicated — improves fatigue), cooling strategies, sleep hygiene, mood addressing; pharmacologic — amantadine, modafinil; - **Spasticity**: PT stretching + strengthening + spasm prevention; oral baclofen, tizanidine; ITB for severe; BoNT focal; SDR rare adult; - **Weakness + gait**: exercise + AFO + assistive devices; FES (Walkaide, Bioness); dalfampridine (4-AP) improves gait speed in selected; - **Balance + falls**: PT balance + Tai Chi; - **Bladder dysfunction**: urodynamics + CIC + anticholinergic/β3 + BoNT detrusor; - **Bowel**: scheduled, fiber/fluids; - **Cognitive**: neuropsych + cognitive rehab + accommodations; - **Visual**: optic neuritis + INO management; - **Mood**: depression (high), suicide risk, anxiety, pseudobulbar affect (dextromethorphan/quinidine); - **Sexual + reproductive**: counseling, pregnancy planning, DMT considerations; - **Pain**: neuropathic + spasm + MSK + multimodal; (3) **Disease-modifying therapy (DMT) coordination**; (4) **Exercise** safe + beneficial (HIIT emerging) — counters deconditioning; (5) **Uthoff phenomenon** — heat sensitivity — cooling strategies; (6) **Vocational rehab + ADA + RTW + adaptive equipment**; (7) **Family + caregiver support**; (8) **Modern**: comprehensive MS clinics + DMTs era + integrated rehab

---

MS rehab: symptom-targeted multidisciplinary. Fatigue energy conserve + exercise + amantadine. Spasticity + weakness/gait (dalfampridine, FES) + bladder (CIC) + cognitive + mood + sexual + pain. DMT. Exercise safe. Modern: comprehensive.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'rehab_medicine'
  and scenario = 'ผู้ป่วยอายุ 35 ปี relapsing-remitting MS — 5 yr disease — moderate disability + fatigue + spasticity';

update public.mcq_questions
set choices = '[{"label":"A","text":"Single discipline"},{"label":"B","text":"ALS Multidisciplinary Care"},{"label":"C","text":"No advance planning"},{"label":"D","text":"Aggressive resistance exercise"},{"label":"E","text":"Discharge"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** ALS Multidisciplinary Care: (1) **ALS Multidisciplinary Clinic** (gold standard): neurology + pulmonology + physiatry + PT + OT + SLP + nutrition + nursing + social work + respiratory therapist + psychology + chaplain — improves QOL + survival; (2) **Symptom-targeted**: - **Dysphagia**: SLP swallow eval (VFSS); compensatory + diet modification (IDDSI); preserve oral safely; PEG for nutrition (early before FVC < 50%); - **Dysarthria + communication**: SLP + AAC (alternative + augmentative — devices, eye-gaze, brain-computer interface — emerging); speech banking for personalized synthesis; - **Nutrition**: high-calorie + protein + supplements; PEG early; weight maintenance prognostic; - **Pulmonary**: serial PFT (FVC), NIV when SOB or FVC ≤ 50% or sniff < 60% — extends survival + improves QOL; cough assist; trach ventilation discussed; - **Mobility + weakness**: PT (preserve function, ROM, no aggressive resistance — avoid overuse), assistive devices (walker, w/c power), home modifications; - **Spasticity**: baclofen, tizanidine; - **Cramps + fasciculations**: quinine selected, gabapentin; - **Sialorrhea**: glycopyrrolate, BoNT salivary glands, scopolamine; - **Pseudobulbar affect**: dextromethorphan/quinidine; - **Depression + anxiety**: SSRI + counseling; - **Pain**: multimodal; (3) **Disease-modifying**: riluzole (modest), edaravone, AMX0035 (recently FDA), tofersen for SOD1; (4) **Advance care planning EARLY + ongoing**: ventilation + nutrition + end-of-life; (5) **Hospice integration**; (6) **Caregiver + family support critical** — burden high; (7) **Outcomes**: ALSFRS-R, FVC, QOL; **Modern**: multidisciplinary clinic + emerging therapeutics + advance planning

---

ALS multidisciplinary clinic (improves survival). Symptom-targeted: dysphagia/PEG + AAC + NIV + cough assist + mobility (no overuse) + spasticity + sialorrhea + PBA + mood. DMT (riluzole etc). Advance planning early. Caregiver.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'rehab_medicine'
  and scenario = 'ผู้ป่วยอายุ 60 ปี ALS — bulbar onset 1 yr — dysphagia + dysarthria + weight loss';

update public.mcq_questions
set choices = '[{"label":"A","text":"Ignore caregiver"},{"label":"B","text":"Advanced MS + Caregiver-Centered Care"},{"label":"C","text":"Single discipline"},{"label":"D","text":"Bedrest"},{"label":"E","text":"Hospice — no rehab"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Advanced MS + Caregiver-Centered Care: (1) **Comprehensive evaluation**: function, complications (pressure injuries, contractures, infections, DVT), psychosocial, caregiver; (2) **Multidisciplinary**: neurology + physiatry + PT + OT + SLP + nursing + social work + psychology + palliative care + family; (3) **Maintain quality of life + dignity**: - Mobility (power w/c, transfers, lift); - ADLs + adaptive equipment + personal care; - Communication (AAC if dysarthria/cognitive); - Nutrition + swallow safety; - Bladder/bowel; - Skin (pressure injury prevention); - Spasticity + pain management; - Cognitive + mood; - Sexual + intimacy; (4) **Caregiver burden assessment** (Zarit Burden Interview): physical + emotional + financial; (5) **Caregiver support** (KEY): - Education + training + skill-building; - Respite care (home, day, short-stay); - Peer support + MS Society resources; - Mental health (caregiver depression high); - Financial + legal + advocacy; - Family meetings + communication; - Acknowledgment + appreciation; (6) **Adaptive equipment + home modifications**: increase independence + reduce caregiver burden; (7) **Community resources**: MS Society, day programs, transportation; (8) **Advance care planning + GoC**: progressive trajectory; advance directives; palliative integration; hospice when appropriate; (9) **Crisis planning**: respite, hospital transitions; (10) **Cultural humility**; (11) **Outcomes**: function, complications, QOL (patient + caregiver), caregiver burden, satisfaction; **Modern**: caregiver-inclusive + technology + community + integrated palliative

---

Advanced MS + caregiver: multidisciplinary. Maintain QOL/dignity. Caregiver assessment (Zarit) + education + respite + peer + mental health + financial + family meeting. Adaptive equipment. GoC. Modern: caregiver-inclusive.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'rehab_medicine'
  and scenario = 'ผู้ป่วย MS — secondary progressive — wheelchair-bound 5 yr — caregiver burnout';

update public.mcq_questions
set choices = '[{"label":"A","text":"Wait — bedrest"},{"label":"B","text":"Early PD — Exercise as Disease-Modifying"},{"label":"C","text":"Single discipline reactive only"},{"label":"D","text":"Discharge no follow-up"},{"label":"E","text":"Hospice"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Early PD — Exercise as Disease-Modifying: (1) **Diagnosis confirmed**: motor (bradykinesia + rest tremor/rigidity) + supportive (response to levodopa); referral movement disorder; (2) **Exercise** (evidence growing — possibly disease-modifying): - **Aerobic moderate-vigorous** (cycling, treadmill — Park-in-Shape, SPARX trials show benefit) — recommended 150 min/wk moderate or 75 vigorous; - **Resistance** 2-3 d/wk; - **Balance + flexibility**; - **Tai Chi, dance (tango), boxing** — popular w/ evidence; - **PWR! Moves, LSVT BIG** for amplitude; (3) **Lifestyle**: Mediterranean diet, sleep hygiene, social engagement, cognitive engagement, smoking cessation, moderate caffeine (?protective); (4) **Mood + cognition** baseline + monitor: depression, anxiety, RBD, MCI; (5) **Education**: disease, expectations, support groups; (6) **Vocational + driving** counseling; (7) **Pharmacotherapy initiation** (timing controversial — symptom-based; levodopa mainstay; MAO-B inhibitor for mild; DA agonist; amantadine for dyskinesia later; deprenyl); (8) **Non-motor screen + management** (RBD, constipation, autonomic, anosmia, mood — often precede motor); (9) **Multidisciplinary involvement EARLY** (not just advanced) improves outcomes; (10) **Driving + safety**: cognitive + visual + motor + driving eval; (11) **Patient empowerment + self-management**; **Modern**: "Exercise as Medicine" + early multidisciplinary + emerging neuromodulation

---

Early PD: exercise as Rx (aerobic + resistance + balance + Tai Chi/boxing/dance) — possibly disease-modifying. Lifestyle. Multidisciplinary EARLY. Mood + cognition + non-motor screen. Pharma initiation. Education.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'rehab_medicine'
  and scenario = 'ผู้ป่วยอายุ 55 ปี early Parkinson disease — newly diagnosed — exercise + lifestyle counseling';

update public.mcq_questions
set choices = '[{"label":"A","text":"Foley indefinitely"},{"label":"B","text":"MS Neurogenic Bladder Management"},{"label":"C","text":"No assessment"},{"label":"D","text":"Single discipline"},{"label":"E","text":"Discharge"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** MS Neurogenic Bladder Management: (1) **Common in MS** (~75-90% over disease course); impacts QOL; (2) **Symptom-based assessment + urodynamics**: pattern — detrusor overactivity (most common — urgency, frequency, urge incontinence), DSD (incomplete emptying, hesitancy, infections), failure to store + failure to empty combined; (3) **Workup**: urodynamics + PVR (post-void residual) + UA/Cx + renal US selected; (4) **Conservative**: timed voiding, fluid management, pelvic floor PT (Kegels, biofeedback), avoid caffeine/alcohol; (5) **Storage failure (overactivity)**: - **Anticholinergics** (oxybutynin, tolterodine, solifenacin, darifenacin) — caution cognitive SE in MS; - **β3-agonist** (mirabegron) — less cognitive; - **BoNT-A detrusor injection** refractory; - **Sacral neuromodulation** selected; (6) **Empty failure (DSD, atony)**: - **Clean intermittent catheterization (CIC)** preferred when PVR elevated; - α-blockers (tamsulosin) selected; - Suprapubic catheter rarely; (7) **UTI**: treat symptomatic, NOT asymptomatic bacteriuria; address contributors; (8) **Renal preservation**: avoid high storage pressure; surveillance; (9) **Education + adaptive equipment + community + sexual** integration; (10) **Multidisciplinary**: urology + neurology + physiatry + pelvic floor PT + nursing + sexual health; (11) **Outcomes**: PROs (KHQ, OAB-q), QOL, UTI rate, function; **Modern**: target therapies + neuromodulation + integrated

---

MS bladder: urodynamics-guided. Storage (overactivity) — anticholinergic/β3/BoNT/SNM. Emptying — CIC. Pelvic floor PT. Treat sympt UTI only. Renal preservation. Multidisciplinary. Modern: targeted + neuromodulation.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'rehab_medicine'
  and scenario = 'ผู้ป่วย MS — bladder dysfunction (urgency, frequency, incontinence) — referred urology + rehab';

update public.mcq_questions
set choices = '[{"label":"A","text":"Aggressive maximal exercise"},{"label":"B","text":"Post-GBS Rehabilitation"},{"label":"C","text":"Bedrest"},{"label":"D","text":"Single discipline"},{"label":"E","text":"Discharge"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Post-GBS Rehabilitation: (1) **Multidisciplinary**: neurology + physiatry + PT + OT + SLP + RT + nutrition + psychology + family; (2) **Phased approach**: - **Plateau/early recovery**: mobility (transfers, sitting, standing tolerance, gait initiation), strength training (CAREFUL — avoid overwork weakness; submaximal eccentric/concentric, monitor fatigue + delayed weakness), endurance, ADLs, equipment; - **Recovery**: progressive strength, endurance, balance, functional + return-to-prior-activity, vocational; (3) **Avoid overuse weakness** (Bensman): submaximal, monitor symptoms post-exercise; (4) **Pulmonary**: IS, breathing exercises, IMT, cough assist if weak; airway clearance; serial vital capacity in recovering patients; (5) **Cardiovascular dysautonomia**: orthostatic hypotension common — gradual upright training, compression, fluids, salt, midodrine selected; arrhythmia monitor; (6) **Pain**: neuropathic + back/joint — gabapentin, TCA, multimodal; (7) **Fatigue**: significant + lasting — energy conservation, graded exercise, pacing; (8) **Mood**: depression + anxiety + PTSD common — screen, CBT, SSRI; (9) **Sensory**: numbness + dysesthesia — desensitization; (10) **Cranial nerve**: dysphagia + facial — SLP eval, swallow strategies; (11) **DVT prevention** during immobility phase; (12) **Family + caregiver education + support**; (13) **Long-term**: most recover but residual common (20%); fatigue often persistent; vocational + community reintegration; **Modern**: structured rehab + outcomes-tracked + multidisciplinary

---

GBS rehab: phased multidisciplinary. AVOID overuse weakness (submaximal). Pulm (cough assist, IMT, VC). Dysautonomia (ortho). Pain + fatigue + mood + sensory + dysphagia. DVT. Family. Long-term residual. Modern structured.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'rehab_medicine'
  and scenario = 'ผู้ป่วยอายุ 25 ปี Guillain-Barré syndrome (AIDP) post-ICU — 6 wk post — significant weakness — admit rehab';

update public.mcq_questions
set choices = '[{"label":"A","text":"No splint"},{"label":"B","text":"Burn Rehabilitation — Comprehensive"},{"label":"C","text":"Bedrest"},{"label":"D","text":"Single discipline"},{"label":"E","text":"Discharge — no scar mgmt"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Burn Rehabilitation — Comprehensive: (1) **Multidisciplinary burn center team**: burn surgeon + physiatrist + PT + OT + RT + nutrition + psychology + child life (peds) + nursing + social work; (2) **Phases**: - **Acute/critical**: resuscitation + early ROM/positioning + splinting (anti-deformity — neck ext, shoulder abducted, elbow ext, wrist neutral, hip ext, knee ext, ankle neutral), wound care, nutrition, pain; - **Surgical**: excision + grafting; rehab during inter-operative; - **Rehabilitative (this patient)**: aggressive ROM + strengthening + scar management + functional + community; - **Long-term**: continued; (3) **Splinting + positioning (KEY)**: prevents contractures — anti-deformity positions; serial casting/dynamic splinting for established; custom orthoses (CHT/OT); (4) **Range of motion**: aggressive + frequent — even painful; address potential burn-specific contractures (axillary, antecubital, popliteal, cervical); (5) **Strengthening + endurance**: progressive; (6) **Scar management** (KEY): - **Pressure garments** 23 h/d × 12-18+ mo (custom, 15-25 mmHg) — reduces hypertrophy; - **Silicone gel sheeting** evidence for hypertrophy; - **Massage** (scar mobilization); - **Moisturizer + sun protection**; - **Laser** (PDL, fractional CO2) — emerging strong evidence for hypertrophic scar + contracture; - **Steroid injection** for hypertrophic/keloid; - **Surgical scar revision/Z-plasty** for contracture refractory; (7) **Pain management**: multimodal — opioid + adjuvants (gabapentin), NSAID + non-pharm (VR distraction, hypnosis); (8) **Psychosocial**: PTSD, anxiety, depression, body image, family — CBT; (9) **Nutrition**: high-protein, calories, vit C, zinc; (10) **Functional + RTW + driving + return-to-community**; (11) **Pediatric considerations**: growth, contracture risk w/ growth, family; **Modern**: laser + biologics + multidisciplinary burn rehab

---

Burn rehab: multidisciplinary phased. Anti-deformity splinting + aggressive ROM + scar mgmt (pressure garments + silicone + laser + steroid). Pain multimodal + non-pharm. Psychosocial. Nutrition. Long-term. Modern: laser/biologics.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'rehab_medicine'
  and scenario = 'ผู้ป่วย post-burn 30% TBSA — deep partial + full-thickness — 3 wk post — rehab planning';

update public.mcq_questions
set choices = '[{"label":"A","text":"Cast 6 wk"},{"label":"B","text":"Hand Burn — Rehabilitation"},{"label":"C","text":"No splint"},{"label":"D","text":"Bedrest"},{"label":"E","text":"Amputation"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Hand Burn — Rehabilitation: (1) **Functional significance**: small surface but high impact; aggressive rehab essential; (2) **Acute management**: wound care + early surgery (excision + graft if deep), edema control (elevation), splinting ("position of safety" — wrist 20-30° ext, MCP 60-70° flex, IP ext, thumb opposition/abduction) — prevents intrinsic-minus + extrinsic shortening; (3) **Early ROM**: as soon as possible — daily PROM/AROM (even painful) by hand therapist (CHT); preserves tendon glide + joint motion; (4) **Post-graft phase**: typically 5-7 d immobilization → active ROM; protect graft initially; (5) **Specific issues**: - **Palmar burn** + deep — risk web space syndactyly, claw deformity, scar contracture (especially MCP flex contracture if not splinted); - **Dorsal burn** — risk boutonniere from PIP swelling/extensor injury; - **Web space** scar contracture — splinting + Z-plasty; (6) **Edema control**: elevation + compression (Coban) + active ROM; (7) **Scar management**: pressure gloves (custom, 12-18 mo), silicone, massage, laser (PDL, fractional CO2); (8) **Strengthening progressive**: putty + grippers + functional; (9) **Sensory re-education**: desensitization + protective sensation; (10) **Functional + ADL + fine motor + work**: integrated; (11) **CHT-led** central; (12) **Patient + family education + adherence**: home program critical; (13) **Outcomes**: TAM, DASH, MHQ, function; **Modern**: early surgery + aggressive rehab + laser scar + CHT

---

Hand burn: position of safety splinting (wrist ext, MCP flex, IP ext, thumb abduct). Early ROM by CHT. Edema control. Scar mgmt (pressure glove + silicone + laser). Specific issues palmar vs dorsal. Sensory + functional. CHT-led.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'rehab_medicine'
  and scenario = 'ผู้ป่วย post-burn hand — palmar burn deep partial — early management';

update public.mcq_questions
set choices = '[{"label":"A","text":"Bedrest no splint"},{"label":"B","text":"Pediatric Neck Burn Contracture"},{"label":"C","text":"Cast neck flexed"},{"label":"D","text":"Single discipline"},{"label":"E","text":"Discharge"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Pediatric Neck Burn Contracture: (1) **Pediatric considerations**: contractures more severe relative to body growth; psychological + body image developmental impact; (2) **Multidisciplinary**: burn surgeon + plastic + physiatry + PT/OT (CHT) + child life + psychology + family; (3) **Anti-deformity positioning (KEY)** from acute: neck extension — no pillow under head, rolled towel under shoulders; sustained — splints + neck conformers (silicone neck collar, soft neck conformer day, more rigid splint night); (4) **Cervical contracture management**: - Sustained stretching + splinting; - Serial casting/dynamic; - Pressure garment + silicone (neck conformer); - Laser (PDL hypertrophy + fractional CO2 contracture); - Steroid injection + intralesional 5-FU; (5) **Surgical scar release**: - Z-plasty + W-plasty for linear contracture; - Local + regional flap; - Skin grafting; - Tissue expansion; - Free flap for severe; - Timing — mature scar (~12+ mo) usually, earlier for severe functional; (6) **Recurrence prevention**: long-term splinting + pressure + monitoring through growth — recurrence risk in pediatric high w/ growth; (7) **Functional + activity**: integration; (8) **Psychosocial + school**: peer support, school reintegration, body image, mental health; (9) **Family education + adherence + advocacy**; (10) **Camp + peer programs** improve outcomes psychosocial; (11) **Long-term follow-up** through growth + adulthood; **Modern**: laser + tissue expansion + integrated multidisciplinary + child life

---

Pediatric neck burn contracture: anti-deformity positioning (extension) + splinting + scar mgmt + surgical release (Z-plasty, flap, expansion). Pediatric risk recurrence w/ growth. Multidisciplinary + child life. Long-term FU.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'rehab_medicine'
  and scenario = 'เด็กอายุ 7 ปี post-burn — รุนแรง full-thickness anterior neck — 1 yr post — cervical flexion contracture';

update public.mcq_questions
set choices = '[{"label":"A","text":"No psych intervention"},{"label":"B","text":"Burn Psychosocial + Vocational"},{"label":"C","text":"Bedrest"},{"label":"D","text":"Single discipline"},{"label":"E","text":"Discharge"}]'::jsonb,
    explanation = '<!-- choice-detail --> **ตัวเลือก B (รายละเอียด):** Burn Psychosocial + Vocational: (1) **Psychological sequelae prevalent** post-burn: PTSD (~20-40%), depression (~25%), anxiety, body image, sleep disturbances, substance use; predicts QOL > burn severity; (2) **Screening + assessment**: PCL-5, PHQ-9, GAD-7, body image scales, sleep, substance use, QOL (BSHS-B — Burn Specific Health Scale-Brief); (3) **Multimodal treatment**: - **Trauma-focused CBT**: gold standard PTSD; - **Prolonged exposure + EMDR**; - **SSRI/SNRI** for PTSD + depression + anxiety; - **Sleep**: CBT-I + meds selected; - **Body image therapy + scar camouflage** (makeup, clothing, tattoo to scar — adjuncts); - **Peer support + burn survivor groups**; - **Family therapy**; (4) **Substance use** integrated treatment; (5) **Vocational rehabilitation**: - Comprehensive assessment (function + cognitive + psych + job demands); - Worksite assessment + accommodations (ADA): scheduling, heat tolerance, sun protection, scar care breaks; - Graded RTW; - Job coach selected; - Vocational re-training if cannot return; (6) **Driving evaluation** if needed; (7) **Community + recreation reintegration**: burn camps, adaptive recreation, peer support; (8) **Family + caregiver + spouse considerations**: relationship + sexual concerns; (9) **Pediatric considerations**: school reintegration, peer/bullying, family; (10) **Multidisciplinary**: psychiatry + psychology + physiatry + voc rehab + peer + family + social work; **Modern**: integrated trauma-informed + survivor-centered + burn psychology

---

Burn psychosocial: PTSD/depression/anxiety/body image high. Screen. Trauma-focused CBT + EMDR + SSRI. Body image + peer support + camouflage. Vocational: assessment + accommodations + graded RTW + job coach. Family. Multidisciplinary.'
where exam_source = 'AI-generated-board-seed'
  and board_specialty = 'rehab_medicine'
  and scenario = 'ผู้ป่วย post-burn 6 mo — PTSD + depression + body image + difficulty returning work';

commit;
