// Batch 1: Q31-60 — Trauma + Acute Abdomen
export default [
  {
    scenario: "ชายไทยอายุ 24 ปี ขับมอเตอร์ไซค์ชนเสาไฟฟ้า ถูกนำส่ง ER ใส่ collar มา\n\nV/S: BP 92/60, HR 124, RR 28, SpO2 91% room air\nGen: somnolent, GCS E2V3M5 = 10\nNeck vein flat\nChest: right side decreased breath sound + hyperresonance + tracheal deviation to left + subcutaneous emphysema\nAbdomen: soft, no peritonitis\n\nคำถาม: ขั้นตอนแรกที่ต้องทำคืออะไร",
    choices: [
      { label: "A", text: "Chest X-ray portable ก่อนแล้วค่อยตัดสินใจ" },
      { label: "B", text: "**Tension pneumothorax — immediate needle decompression** ที่ 5th intercostal space anterior axillary line (ATLS 10th edition update — เดิมคือ 2nd ICS MCL แต่ผนังหน้าอกหนาในผู้ใหญ่ทำให้เข็ม 5 cm ไม่ถึง pleural space ในบางคน) ตามด้วยการใส่ **tube thoracostomy** (chest tube 28-32 Fr) อย่างเร่งด่วน; การวินิจฉัย tension pneumothorax เป็น clinical diagnosis ไม่ต้องรอ CXR (รอ imaging = death); concurrent resuscitation + secure airway" },
      { label: "C", text: "CT chest urgent" },
      { label: "D", text: "Intubate before chest decompression" },
      { label: "E", text: "Pericardiocentesis" },
    ],
    correct_answer: "B",
    explanation: "Tension pneumothorax เป็น clinical diagnosis — air ใน pleural space ทำให้ mediastinum เคลื่อน, vena cava ถูกกด, venous return ลดลง, obstructive shock เกิดได้เร็ว Classic findings: respiratory distress, tracheal deviation away from affected side, hyperresonance, decreased breath sounds, distended neck veins (อาจ flat ถ้า hypovolemia), hemodynamic compromise ATLS 10th edition: ตำแหน่ง needle decompression สำหรับ adult = 5th ICS anterior axillary line (เข็ม 14G 5 cm) เพราะ chest wall thickness ที่ 2nd ICS MCL อาจมากกว่า 5 cm ใน 30-50% ของคนไข้. ในเด็กยังคงใช้ 2nd ICS MCL. หลัง decompression แล้ว ต้อง tube thoracostomy เสมอ. A ผิด — ห้ามรอ CXR ใน tension pneumothorax. C ผิด — ห้ามส่ง CT. D ผิด — positive pressure ventilation จะทำให้อาการแย่ลงเร็ว ควร decompress ก่อน intubate ถ้าทำได้. E ผิด — ไม่ใช่ pericardial.",
    difficulty: "easy",
    board_section: "clinical_decision",
    board_topic: "trauma",
    board_age_group: "adult",
    reference_source: "ATLS Advanced Trauma Life Support 10th Edition — Chapter 4 Thoracic Trauma; Inaba K et al. J Trauma 2011 (needle thoracostomy depth)",
  },
  {
    scenario: "หญิงไทยอายุ 36 ปี รถยนต์ชนต้นไม้ความเร็วสูง คาดเข็มขัดนิรภัย air bag ทำงาน\n\nV/S: BP 78/40, HR 138, RR 26, SpO2 96%\nGen: pale, diaphoretic, JVP elevated, muffled heart sounds, Beck's triad positive\nChest: clear breath sounds bilaterally\nAbdomen: soft\n\nFAST exam: pericardial effusion มาก, RV collapse in diastole",
    choices: [
      { label: "A", text: "IV fluid bolus 2 liter normal saline" },
      { label: "B", text: "**Cardiac tamponade — emergent decompression**: (1) IV fluid bolus to optimize preload (bridge); (2) **Emergent pericardiocentesis** (subxiphoid approach with US guidance) — temporizing; (3) **Definitive: emergent median sternotomy หรือ left anterior thoracotomy** (resuscitative thoracotomy) for traumatic tamponade เพื่อ relieve tamponade + repair cardiac injury; (4) Trauma + CT surgery activation; type & cross 6 units PRC; massive transfusion protocol on standby; (5) Avoid intubation with high PEEP — จะลด venous return ทำให้ shock แย่ลง" },
      { label: "C", text: "Beta-blocker IV เพื่อลด HR" },
      { label: "D", text: "CT chest with contrast ก่อนตัดสินใจ" },
      { label: "E", text: "Observation in ICU" },
    ],
    correct_answer: "B",
    explanation: "Cardiac tamponade — Beck's triad: hypotension + muffled heart sounds + distended neck veins (Kussmaul sign = paradoxical JVD on inspiration). Pulsus paradoxus > 10 mmHg. FAST sensitivity 90-95% สำหรับ pericardial effusion. ในผู้ป่วย penetrating trauma หรือ blunt cardiac injury ที่มี tamponade ต้องเปิด pericardium ทันที — pericardiocentesis อาจช่วยชั่วคราว แต่ definitive คือ thoracotomy/sternotomy. ใน blunt trauma มักจาก cardiac rupture, ใน penetrating จาก stab wound. Resuscitative ED thoracotomy พิจารณาใน penetrating chest trauma with signs of life within 15 min. A เป็น bridge แต่ไม่ definitive. C ผิด — beta-blocker จะทำให้ cardiac output ลด. D ผิด — ห้ามรอ CT. E ผิดอย่างยิ่ง.",
    difficulty: "medium",
    board_section: "clinical_decision",
    board_topic: "trauma",
    board_age_group: "adult",
    reference_source: "ATLS 10th Ed; EAST Guidelines: Penetrating Cardiac Injuries 2019; WSES Cardiac Trauma Guidelines",
  },
  {
    scenario: "ชายไทยอายุ 45 ปี ตกจากที่สูง 4 เมตร ปวดเชิงกรานรุนแรง\n\nV/S: BP 84/52, HR 130, RR 24, GCS 15\nPelvis: instability on compression, hematoma scrotum +, blood at urethral meatus\nFAST: negative free fluid abdomen\nCXR: clear\nPelvic X-ray: open-book pelvic fracture with > 2.5 cm pubic diastasis\n\nคำถาม: ขั้นตอนต่อไป",
    choices: [
      { label: "A", text: "Foley catheterization immediately" },
      { label: "B", text: "**Unstable open-book pelvic fracture with hemorrhagic shock + urethral injury**: (1) **Pelvic binder** (or circumferential sheet) at level greater trochanters — first-line mechanical stabilization to reduce volume + tamponade; (2) **Resuscitation**: 2 large-bore IV + massive transfusion protocol 1:1:1; (3) **Source of bleeding**: pelvic fracture (FAST negative — abdominal source unlikely); arterial bleed → **angioembolization** (preferred if available); venous/bony bleed → **preperitoneal pelvic packing** + external fixation; (4) **REBOA Zone 3** in extremis as bridge to definitive control; (5) **Suspect urethral injury** (blood at meatus, high-riding prostate) → **retrograde urethrogram (RUG)** before any Foley attempt — DO NOT pass Foley until urethra confirmed intact; suprapubic catheter if needed; (6) Trauma + Ortho + Urology + IR multidisciplinary" },
      { label: "C", text: "Definitive ORIF pelvis immediately" },
      { label: "D", text: "Observation + serial Hb" },
      { label: "E", text: "MRI pelvis" },
    ],
    correct_answer: "B",
    explanation: "Open-book pelvic fracture (APC type) — high mortality (20-40%) จาก venous plexus + arterial bleed + soft tissue. Pelvic binder ลด pelvic volume → tamponade + ลดเลือดออก. Source of major hemorrhage: 85% venous/bony, 15% arterial. Hemodynamically unstable + pelvic fracture without intra-abdominal source: arterial bleed suspected → angioembolization. If no IR: preperitoneal pelvic packing + external fixator (รวดเร็ว, control venous + bony). Sequence per WSES guidelines: binder → resuscitate → if FAST positive → laparotomy; if FAST negative + unstable → IR or packing. Urethral injury — blood at meatus / scrotal hematoma / high-riding prostate → RUG ก่อน Foley. A ผิด — Foley before RUG อาจทำให้ urethra injury แย่ลง. C ผิด — definitive surgery รอ stable. D ผิดอย่างยิ่ง. E ผิด — ไม่ใช่ทำเลย.",
    difficulty: "hard",
    board_section: "clinical_decision",
    board_topic: "trauma",
    board_age_group: "adult",
    reference_source: "WSES Pelvic Trauma Guidelines 2017; EAST Guidelines: Pelvic Fracture; AAST Pelvic Fracture Grading",
  },
  {
    scenario: "ชายไทยอายุ 28 ปี ขับรถยนต์ชนกับรถกระบะ ใช้เข็มขัดนิรภัย ไม่มีอาการขณะรับรู้\n\nV/S: BP 124/78, HR 88, RR 16, GCS 15, room air SpO2 99%\nAbdomen: tender LUQ, no peritonitis, no bruising\nFAST: small free fluid Morrison's pouch\nCT abdomen: splenic laceration grade III with active blush + free fluid moderate amount; no other injury\n\nHb 11.8 g/dL stable\n\nคำถาม: management",
    choices: [
      { label: "A", text: "Emergency splenectomy" },
      { label: "B", text: "**Splenic injury grade III + active blush + hemodynamically stable → angioembolization + non-operative management (NOM)**: (1) ICU admission + serial abdominal exam + serial Hb q4-6h × 24-48h; (2) **Splenic artery angioembolization (SAE)** for active blush (contrast extravasation) — proximal embolization for grade IV-V; distal/selective for focal pseudoaneurysm; improves NOM success rate (90% with SAE vs 60% without in grade III-IV); (3) NPO initially, bedrest 24-48h; (4) Vaccination prophylaxis NOT needed unless splenectomy; (5) Failure criteria → hemodynamic instability, ongoing transfusion > 2 units/24h, peritonitis → laparotomy + splenectomy/splenorrhaphy; (6) Activity restriction 6-8 weeks post-discharge" },
      { label: "C", text: "Discharge home with outpatient follow-up" },
      { label: "D", text: "Total body MRI" },
      { label: "E", text: "Diagnostic laparoscopy" },
    ],
    correct_answer: "B",
    explanation: "Blunt splenic injury — AAST grading I-V. NOM success rate decreases with grade: I-II ~95%, III ~80%, IV-V ~50-70%. SAE เพิ่ม NOM success rate ใน grade III-V + contrast blush. Indications สำหรับ angioembolization (WSES + EAST): contrast extravasation, pseudoaneurysm, AV fistula, grade IV-V even without blush in selected centers. Hemodynamically unstable + splenic injury = laparotomy. ผู้ป่วยรายนี้ stable + grade III + blush → ideal for SAE-NOM. Post-splenectomy vaccinations (S. pneumoniae, H. influenzae, N. meningitidis) ถ้าตัดม้าม. A ผิด — stable + NOM candidate. C ผิดอย่างยิ่ง. D ผิด — CT done. E ผิด — no indication.",
    difficulty: "medium",
    board_section: "clinical_decision",
    board_topic: "trauma",
    board_age_group: "adult",
    reference_source: "WSES Splenic Trauma Guidelines 2017; EAST Practice Management Guidelines: Selective NOM Blunt Splenic Injury; Stassen NA et al. J Trauma 2012",
  },
  {
    scenario: "หญิงไทยอายุ 62 ปี underlying COPD GOLD C มาด้วยอาการปวดท้องรุนแรงทันทีทันใด มา 3 ชั่วโมง ปวดทั้งท้อง ไม่ผ่ายลม ไม่ถ่าย\n\nV/S: BP 102/68, HR 116, RR 24, Temp 38.4°C\nAbdomen: rigid abdomen, generalized rebound tenderness, absent bowel sound\n\nUpright CXR: free air under bilateral diaphragm\nLab: WBC 18,400, Lactate 3.6\n\nคำถาม: management",
    choices: [
      { label: "A", text: "Observation + IV antibiotic 24 hours" },
      { label: "B", text: "**Perforated viscus with generalized peritonitis — emergent exploratory laparotomy**: (1) **Pre-op resuscitation**: 2 large-bore IV, IV fluid 1-2 L crystalloid, type & cross, foley + NG decompression, IV broad-spectrum antibiotic (e.g., piperacillin-tazobactam OR ceftriaxone + metronidazole); (2) **Source identification**: PUD perforation most common (60-70%) — duodenal > gastric; ตำแหน่งอื่น: appendix, sigmoid (diverticulitis, cancer), small bowel; (3) **Operative repair**: PUD perforation < 2 cm → Graham omental patch + biopsy + H. pylori workup; large perforation → Billroth I/II or vagotomy/antrectomy (rarely needed now); ล้างช่องท้องด้วย NSS; place drain; (4) **Postop**: continue antibiotic 5-7 days, PPI long-term, H. pylori eradication, ICU monitoring; (5) Laparoscopic approach if surgeon experienced + stable" },
      { label: "C", text: "Endoscopy + clip closure" },
      { label: "D", text: "Conservative non-operative management (Taylor approach) for all" },
      { label: "E", text: "CT abdomen ก่อนแล้วค่อยตัดสินใจ" },
    ],
    correct_answer: "B",
    explanation: "Free air under diaphragm + peritonitis = perforated viscus = emergent surgery. Causes: PUD (60-70%), appendiceal perforation, diverticulitis perforation, colon cancer perforation, traumatic, iatrogenic, ischemic. Mortality of perforated PUD: 5-15%, higher in elderly + delayed presentation. Graham omental patch — pedicled omentum on perforation + interrupted sutures. Boey score predicts mortality: shock, comorbidity, delayed presentation > 24h. Taylor non-operative approach (NG suction, antibiotics, PPI, NPO) considered ONLY in selected stable patients with sealed perforation on Gastrografin — rarely first-line. CT useful if diagnosis unclear แต่ patient ที่ peritonitis + free air ชัด ไม่ต้องรอ CT. A ผิด — peritonitis + free air ต้องผ่า. C ผิด — perforation > endoscopic. D ผิด — selected only. E controversial แต่ถ้า diagnosis ชัด ไม่จำเป็น.",
    difficulty: "easy",
    board_section: "clinical_decision",
    board_topic: "gi",
    board_age_group: "adult",
    reference_source: "WSES Guidelines for Perforated Peptic Ulcer 2020; ACS Surgery Principles; Søreide K et al. Lancet 2015",
  },
  {
    scenario: "ชายไทยอายุ 72 ปี atrial fibrillation on warfarin (INR 2.4) มาด้วยปวดท้องรุนแรง 6 ชั่วโมง ปวดทั้งท้องไม่ระบุตำแหน่ง pain out of proportion to exam findings\n\nV/S: BP 128/76, HR 116 irregular, RR 22, Temp 36.8°C\nAbdomen: soft, mild tenderness diffuse, no peritonitis, bowel sound active\n\nLab: WBC 16,800, Lactate 4.8, BE -8, Cr 1.6, LDH 480\nCT abdomen with IV contrast: SMA occlusion + bowel wall thickening + pneumatosis intestinalis at jejunum",
    choices: [
      { label: "A", text: "Observation + IV antibiotic + bowel rest" },
      { label: "B", text: "**Acute mesenteric ischemia (AMI) — SMA embolism (likely cardioembolic from AF)**: (1) **Immediate resuscitation** + IV broad-spectrum antibiotic (e.g., piperacillin-tazobactam — covers bowel translocation); (2) **Therapeutic anticoagulation** (heparin IV) once decision-made; (3) **Vascular intervention**: **endovascular thrombectomy/thrombolysis** (catheter-directed) if no peritonitis + viable bowel — first-line in modern era OR **open SMA embolectomy via laparotomy**; (4) **Exploratory laparotomy** if peritonitis, pneumatosis with full-thickness necrosis suspected — **assess bowel viability** → resect non-viable bowel + **second-look laparotomy 24-48h** if uncertain; (5) Avoid vasopressors that constrict splanchnic flow (norepi preferred ถ้าจำเป็น); (6) Mortality 60-80% — early diagnosis + revascularization critical" },
      { label: "C", text: "Stat angiogram only without intervention" },
      { label: "D", text: "Heparin infusion alone without revascularization" },
      { label: "E", text: "Diagnostic peritoneal lavage" },
    ],
    correct_answer: "B",
    explanation: "Acute Mesenteric Ischemia (AMI) — high mortality (60-80%) จาก delayed diagnosis. Etiology: 1) **Arterial embolism** 50% (AF, MI, valve dz — SMA most common embolic destination) 2) **Arterial thrombosis** 25% (atherosclerosis at SMA origin) 3) **Non-occlusive mesenteric ischemia (NOMI)** 20% (low flow, vasoconstriction — shock, vasopressors, dialysis) 4) **Mesenteric venous thrombosis** 5% (hypercoagulable). Classic: 'pain out of proportion to physical findings' + AF/atherosclerosis. CT angiography is diagnostic gold standard. Pneumatosis intestinalis + portal venous gas = late sign with high mortality. Modern management trend: endovascular-first (thrombectomy ± stenting) for arterial occlusion without peritonitis. Open surgery if peritonitis OR endovascular failure. Damage control + second-look. A ผิด — observation = death. C ผิด — diagnostic only ไม่พอ. D ผิด — heparin alone ไม่พอ. E ผิดล้าสมัย.",
    difficulty: "hard",
    board_section: "clinical_decision",
    board_topic: "vascular",
    board_age_group: "adult",
    reference_source: "WSES Guidelines for Acute Mesenteric Ischemia 2017; ESVS Mesenteric Arterial Disease 2017; Bala M et al. World J Emerg Surg",
  },
  {
    scenario: "หญิงไทยอายุ 78 ปี มา ED ด้วยอาการปวดท้องน้อยซ้าย 3 วัน ไข้ ปวดเวลาถ่าย ถ่ายลำบาก\n\nV/S: BP 132/82, HR 96, RR 18, Temp 38.6°C\nAbdomen: tenderness LLQ + palpable mass + guarding localized, no generalized peritonitis\n\nLab: WBC 15,200, CRP 142\nCT abdomen: sigmoid diverticulitis + pericolic abscess 4.5 cm, no free air, no generalized peritonitis (Hinchey II)",
    choices: [
      { label: "A", text: "Emergency Hartmann's procedure" },
      { label: "B", text: "**Hinchey II diverticulitis (pericolic abscess > 3-4 cm)**: (1) **Percutaneous CT-guided drainage** of abscess (IR) + IV broad-spectrum antibiotics (ceftriaxone + metronidazole or piperacillin-tazobactam) × 10-14 days; (2) NPO → clear liquid → low residue as tolerated; (3) Repeat imaging if not improving in 48-72h; (4) **Interval consideration of elective resection 6-8 weeks** post-recovery — current evidence (DIABOLO + others) shows elective sigmoidectomy NOT mandatory after single uncomplicated episode; consider in patients with complicated diverticulitis (abscess, fistula, stricture), immunocompromised, recurrent attacks, persistent symptoms — individualized; (5) Colonoscopy 6-8 weeks post-attack to exclude malignancy (controversial in mild cases per Cochrane); (6) Lifestyle: high-fiber diet, hydration" },
      { label: "C", text: "Antibiotic alone without drainage" },
      { label: "D", text: "Discharge home with oral antibiotics" },
      { label: "E", text: "Diverting colostomy" },
    ],
    correct_answer: "B",
    explanation: "Hinchey classification of complicated diverticulitis: I) pericolic abscess (< 4 cm), II) pelvic/distant abscess (> 4 cm), III) purulent peritonitis, IV) fecal peritonitis. Management: - **Uncomplicated (Hinchey 0-Ia)**: outpatient antibiotics OR observation alone in selected cases (DIABOLO trial — antibiotic non-inferior to observation in uncomplicated) - **Hinchey I (< 3-4 cm)**: IV antibiotic alone usually adequate - **Hinchey II (> 4 cm)**: percutaneous drainage + IV antibiotic - **Hinchey III**: laparoscopic lavage (controversial — Ladies/SCANDIV trials mixed) OR sigmoidectomy with primary anastomosis ± diverting loop ileostomy (modern preferred over Hartmann's in selected) - **Hinchey IV (fecal peritonitis)**: emergent Hartmann's OR primary anastomosis with diversion in selected stable patients Elective sigmoidectomy after recovery — individualized, not for all single episodes. A ผิด — emergency Hartmann's สำหรับ Hinchey III-IV. C ผิด — abscess > 3-4 cm ต้อง drain. D ผิด — รุนแรงเกิน outpatient. E ผิด — ไม่มี indication.",
    difficulty: "medium",
    board_section: "clinical_decision",
    board_topic: "gi",
    board_age_group: "adult",
    reference_source: "WSES Guidelines for Acute Left Sided Colonic Diverticulitis 2020; ASCRS Clinical Practice Guidelines Diverticulitis; Daniels L et al. Br J Surg 2017 (DIABOLO)",
  },
  {
    scenario: "ชายไทยอายุ 58 ปี มาด้วยอาเจียน 5 ครั้ง 24 ชั่วโมง ท้องอืด ไม่ผ่ายลม ไม่ถ่าย previous appendectomy 10 ปีก่อน\n\nV/S: BP 118/76, HR 102, RR 18, Temp 37.2°C\nAbdomen: distended, high-pitched bowel sound, tender diffuse, no peritonitis, no hernia\n\nUpright X-ray: multiple air-fluid levels + dilated small bowel loops + no free air\nCT abdomen: small bowel obstruction with transition point at right lower quadrant + adhesion suspected; no closed loop, no pneumatosis, no fat stranding\n\nคำถาม: initial management",
    choices: [
      { label: "A", text: "Emergent exploratory laparotomy" },
      { label: "B", text: "**Adhesive small bowel obstruction (ASBO), uncomplicated → conservative management trial**: (1) **NPO + NG decompression**; (2) **IV fluid + electrolyte correction** (K, Cl losses common); (3) **Serial abdominal exam** + serial labs (WBC, lactate); (4) **Water-soluble contrast challenge (Gastrografin)** — both diagnostic + therapeutic: contrast reaching colon within 24h = predictive of resolution + may itself promote passage (osmotic effect); 75% resolve with conservative trial; (5) **Surgery indicated** if: peritonitis, ischemia/strangulation suspected (fever, leukocytosis, lactate, CT signs — closed loop, pneumatosis, mesenteric edema), failure of conservative trial 48-72h, no transit on contrast study; (6) Surgical options: laparoscopic adhesiolysis (selected) vs open; address etiology; (7) **Prevention**: adhesion barrier (e.g., hyaluronic acid) at index surgery" },
      { label: "C", text: "Discharge home with oral antibiotic" },
      { label: "D", text: "Colonoscopy" },
      { label: "E", text: "Sigmoid decompression tube" },
    ],
    correct_answer: "B",
    explanation: "Adhesive SBO — most common cause of SBO in adults (60-75%). Conservative management resolves 70-80% of uncomplicated ASBO. **Bologna Guidelines (WSES) + ASBO management**: 1. Initial: NPO, NG, IV fluid, electrolyte correction 2. Identify warning signs of strangulation: fever, tachycardia, focal tenderness, lactate, WBC, CT signs (closed loop, mesenteric edema, pneumatosis, free fluid, lack of bowel wall enhancement) 3. Gastrografin challenge: 100 mL via NG, follow-up X-ray at 24h — if contrast in colon, predicts resolution + may aid passage 4. Trial 48-72h max; longer trial increases ischemia risk 5. Surgical indication: failed conservative, suspected ischemia, complete obstruction without resolution, closed loop, virgin abdomen (high malignancy risk) Strangulation = surgical emergency. A ผิด — no strangulation signs. C ผิดอย่างยิ่ง. D ผิด — small bowel not colon. E ผิด — for volvulus.",
    difficulty: "easy",
    board_section: "clinical_decision",
    board_topic: "gi",
    board_age_group: "adult",
    reference_source: "WSES Bologna Guidelines for ASBO 2017; Maung AA et al. EAST PMG; Di Saverio S et al. World J Emerg Surg",
  },
  {
    scenario: "ชายไทยอายุ 68 ปี ปวดท้องน้อยซ้าย ท้องอืดมาก 5 วัน ไม่ผ่ายลม no flatus\n\nV/S: BP 142/86, HR 96, RR 20, Temp 37.0°C\nAbdomen: massive distention, asymmetric, no peritonitis\n\nAbdominal X-ray: 'coffee bean' sign / 'omega loop' centred to RUQ\nCT abdomen: sigmoid volvulus with whirl sign + dilated loop without bowel wall ischemia signs",
    choices: [
      { label: "A", text: "Emergency sigmoidectomy" },
      { label: "B", text: "**Sigmoid volvulus without ischemia → endoscopic detorsion first**: (1) **Flexible sigmoidoscopy / colonoscopy decompression + rectal tube placement** — successful in 70-90% of cases without ischemia; assess viability of mucosa during scope; (2) **NG decompression**, IV fluid, electrolyte correction; (3) **Sentinel sigmoidectomy during same admission** (within 2-7 days) after detorsion — recurrence rate ~50-90% if not resected; one-stage sigmoidectomy with primary anastomosis preferred; (4) **Emergent surgery** if: failed endoscopic detorsion, signs of ischemia/gangrene (peritonitis, mucosal necrosis on scope, fever, lactate), perforation → Hartmann's procedure or sigmoidectomy with primary anastomosis ± diverting stoma; (5) Post-recovery: nutrition, mobility, bowel regimen" },
      { label: "C", text: "Observation + bowel rest only" },
      { label: "D", text: "Barium enema" },
      { label: "E", text: "Discharge with laxatives" },
    ],
    correct_answer: "B",
    explanation: "Sigmoid volvulus — common in elderly, institutionalized, chronic constipation, neurogenic. Coffee bean / omega sign on X-ray; whirl sign on CT. Management: 1. **No ischemia + stable**: endoscopic detorsion successful 70-90%; rectal tube placement post-detorsion 2. **Definitive**: sigmoidectomy ภายใน same admission — recurrence > 50% if not resected 3. **Ischemia / failed endoscopic / perforation**: emergent surgery — Hartmann's (classic) OR sigmoidectomy + primary anastomosis ± diverting stoma per surgeon judgment + patient status Cecal volvulus (different): NOT amenable to endoscopic detorsion typically; emergent right hemicolectomy. A ผิด — รุนแรงเกินไป first-line, แต่ definitive needed. C ผิด — รอจะเกิด ischemia. D ผิด — เก่า + ไม่ therapeutic. E ผิดอย่างยิ่ง.",
    difficulty: "medium",
    board_section: "clinical_decision",
    board_topic: "gi",
    board_age_group: "adult",
    reference_source: "ASCRS Clinical Practice Guidelines Sigmoid Volvulus 2016; WSES Acute Colonic Obstruction Guidelines",
  },
  {
    scenario: "หญิงไทยอายุ 56 ปี underlying gallstones มา ED ด้วยปวด RUQ severe 12 ชั่วโมง ไข้สูง หนาวสั่น ตัวเหลืองตาเหลือง confusion mild\n\nV/S: BP 92/58, HR 124, RR 22, Temp 39.4°C\nAbdomen: tender RUQ, Murphy's + , no peritonitis generalized\n\nLab: WBC 22,000, Total bili 6.8, Direct bili 5.2, ALP 480, GGT 320, AST 188, ALT 142, Cr 1.7\nUS: gallbladder distention + sludge + CBD dilatation 12 mm + intrahepatic duct dilatation\nMRCP pending\n\nคำถาม: most appropriate next step",
    choices: [
      { label: "A", text: "Immediate cholecystectomy" },
      { label: "B", text: "**Acute cholangitis with Reynolds' pentad — severe (Tokyo Grade III)**: (1) **Resuscitation**: IV crystalloid bolus, vasopressors as needed for septic shock; (2) **IV broad-spectrum antibiotic** ASAP (within 1 hr of recognition) — piperacillin-tazobactam OR meropenem + cover ESBL/anaerobes given severity; (3) **Urgent biliary decompression within 24h** — **ERCP with sphincterotomy + stone extraction + biliary stent** (preferred — therapeutic); alternative if ERCP failed/unavailable: **PTC (percutaneous transhepatic cholangiogram + drain)** or open biliary decompression as last resort; (4) ICU monitoring; (5) **Cholecystectomy delayed** until cholangitis resolved (typically 4-6 weeks) — gallstone source; same admission cholecystectomy if mild-moderate cholangitis post-ERCP, delayed if severe" },
      { label: "C", text: "Antibiotic alone × 7 days, no procedure" },
      { label: "D", text: "Open CBD exploration immediately" },
      { label: "E", text: "Endoscopic ultrasound only" },
    ],
    correct_answer: "B",
    explanation: "Acute cholangitis (ascending cholangitis) — biliary tract infection from obstruction (stones > stricture > malignancy). **Charcot's triad**: fever + RUQ pain + jaundice (50-70% present) **Reynolds' pentad**: + hypotension + altered mental status (severe/suppurative). Tokyo Guidelines 2018 grading: - **Grade I (mild)**: no organ dysfunction, responds to antibiotics, no urgent drainage needed - **Grade II (moderate)**: 2+ of (WBC > 12k or < 4k, fever > 39, age > 75, hyperbili > 5, hypoalbumin < 0.7x LL) - **Grade III (severe)**: organ dysfunction (CV, neuro, resp, renal, hepatic, hematologic) — **urgent drainage required** Treatment principles: 1. Antibiotics (within 1 hr): broad-spectrum covering gram-neg + anaerobes; piperacillin-tazobactam, meropenem in severe 2. Biliary decompression timing: - Grade I: elective or within 24-48h if not improving - Grade II: early (within 24-48h) - Grade III: urgent (within 24h) 3. ERCP preferred — therapeutic + diagnostic 4. Cholecystectomy delayed until cholangitis resolved A ผิด — cholecystectomy โดยไม่ decompress = mortality. C ผิด — drainage essential. D ผิด — open last resort. E ผิด — EUS diagnostic only.",
    difficulty: "medium",
    board_section: "clinical_decision",
    board_topic: "gi",
    board_age_group: "adult",
    reference_source: "Tokyo Guidelines 2018 (TG18) for Acute Cholangitis; WSES Guidelines Acute Calculous Cholecystitis 2020; Miura F et al. J Hepatobiliary Pancreat Sci 2018",
  },
  {
    scenario: "ชายไทยอายุ 48 ปี ดื่มแอลกอฮอล์หนัก ปวดท้องรุนแรงตรงกลางท้อง 24 ชั่วโมง ปวดร้าวไปหลัง คลื่นไส้อาเจียน\n\nV/S: BP 96/64, HR 124, RR 28, Temp 38.4°C, SpO2 92% room air\nAbdomen: tender epigastric, distended, decreased bowel sound\n\nLab: WBC 19,200, Lipase 3,200 (normal < 60), Glucose 220, Ca 7.6, BUN 32, Cr 1.8, LDH 480, AST 220, Hct 48\nABG: pH 7.30, PaO2 64, HCO3 18\nCT abdomen with contrast (day 3): pancreatic necrosis 40% + peripancreatic fluid collection + no infection signs",
    choices: [
      { label: "A", text: "Immediate necrosectomy day 1" },
      { label: "B", text: "**Severe acute pancreatitis (predicted by APACHE-II, BISAP, modified Marshall) with sterile necrosis — multidisciplinary critical care management**: (1) **Aggressive but goal-directed IV fluid** (Ringer lactate, target UO 0.5 ml/kg/hr, MAP > 65, Hct 35-44; avoid over-resuscitation — increases organ failure); recent trend: moderate fluid resuscitation per WATERFALL trial 2022 (aggressive worsens outcomes); (2) **ICU admission** for organ support — ventilator, vasopressor, CRRT as needed; (3) **Enteral nutrition early** (NG/NJ within 24-72h) — better than TPN (reduces infection, mortality); (4) **No prophylactic antibiotic** in sterile necrosis (no mortality benefit, increases fungal/resistant infections — current evidence); (5) **Pain control**, **PPI**, **DVT prophylaxis**; (6) **Treat underlying cause** — gallstone → urgent ERCP if cholangitis or persistent obstruction; alcohol → cessation + thiamine; (7) **Necrosis intervention indication**: infected necrosis suspected (clinical decline, gas in necrosis, positive FNA) — **delay 4 weeks** if possible for walled-off necrosis (WON), then **step-up approach** per PANTER trial: percutaneous drainage → endoscopic/MIS necrosectomy if not resolved → open necrosectomy last resort" },
      { label: "C", text: "Routine prophylactic antibiotic infusion 14 days" },
      { label: "D", text: "TPN only, no enteral feeding" },
      { label: "E", text: "ERCP for all severe pancreatitis" },
    ],
    correct_answer: "B",
    explanation: "Acute pancreatitis severity assessment: **Atlanta Classification 2012**: - Mild: no organ failure, no complications - Moderately severe: transient organ failure < 48h OR local/systemic complications - Severe: persistent organ failure > 48h **Scoring**: Ranson, APACHE-II, BISAP (5 variables, simple), Marshall (modified) Etiology: GET SMASHED — Gallstones (40%), Ethanol (30%), Trauma, Steroids, Mumps, Autoimmune, Scorpion, Hypertriglyceridemia/Hypercalcemia, ERCP, Drugs Key evidence-based management updates: 1. **Fluid resuscitation**: WATERFALL trial (NEJM 2022) — moderate (Ringer 1.5 mL/kg/h) BETTER than aggressive (3 mL/kg/h + bolus) re: organ failure, persistent SIRS 2. **Nutrition**: Early enteral (NJ ดีกว่า NG controversial — but both OK) > TPN — reduces infectious complications, organ failure 3. **Antibiotics**: NOT prophylactic in sterile necrosis. Use only for documented infection 4. **Necrosis intervention**: PANTER trial (NEJM 2010) — step-up approach (percutaneous drainage → minimally invasive necrosectomy) better than open. Delay until walled-off (4+ weeks) for elective 5. **ERCP** in pancreatitis: indicated for gallstone pancreatitis + cholangitis OR persistent obstruction; NOT for all severe A ผิด — delay 4 weeks for WON. C ผิด — no prophylactic abx. D ผิด — enteral preferred. E ผิด — selected only.",
    difficulty: "hard",
    board_section: "clinical_decision",
    board_topic: "gi",
    board_age_group: "adult",
    reference_source: "Atlanta Classification 2012; IAP/APA Acute Pancreatitis Guidelines; WSES Severe Acute Pancreatitis 2019; van Santvoort HC et al. NEJM 2010 (PANTER); de-Madaria E et al. NEJM 2022 (WATERFALL)",
  },
  {
    scenario: "ชายไทยอายุ 60 ปี ติด HBV chronic 30 ปี cirrhosis Child-Pugh A เคยตรวจ AFP > 400 ng/mL\n\nCT 4-phase liver: 4.5 cm enhancing mass at segment VI with arterial hyperenhancement + washout in portal venous + delayed phases (LI-RADS 5)\n\nNo extrahepatic disease, no portal vein thrombosis\nBilirubin 1.0, INR 1.1, Albumin 3.8, no ascites, no encephalopathy\nMELD 7\n\nคำถาม: management",
    choices: [
      { label: "A", text: "Sorafenib alone" },
      { label: "B", text: "**HCC stage Barcelona Clinic Liver Cancer (BCLC) A — single nodule, preserved liver function, no portal HTN**: best candidate for **curative therapy**: (1) **Surgical resection** = first-line if: no significant portal HTN (HVPG < 10), preserved function (Child A), feasible anatomical resection with adequate remnant; this patient meets criteria — segmentectomy/lobectomy of segment VI; (2) **Alternatives**: - **Liver transplantation** if within Milan criteria (1 lesion ≤ 5 cm OR 2-3 lesions each ≤ 3 cm, no extrahepatic, no vascular invasion) — particularly if Child B/C or significant portal HTN; - **Ablation (RFA/MWA)** for tumors ≤ 3 cm — comparable to resection in small HCC, less invasive; (3) **Adjuvant therapy**: no proven adjuvant therapy post-resection (atezolizumab + bevacizumab in adjuvant trial IMbrave050 ongoing); (4) **Surveillance**: AFP + imaging q3 mo × 2 yr then q6 mo; (5) **Treat underlying HBV** — antiviral (entecavir or tenofovir) lifelong" },
      { label: "C", text: "TACE only" },
      { label: "D", text: "Observation" },
      { label: "E", text: "Whipple procedure" },
    ],
    correct_answer: "B",
    explanation: "HCC management (BCLC staging — primary algorithm): - **BCLC 0 (very early)**: single ≤ 2 cm, Child A, PS 0 — resection or ablation - **BCLC A (early)**: single OR up to 3 nodules ≤ 3 cm, Child A-B, PS 0 — resection / transplant / ablation - **BCLC B (intermediate)**: multinodular, Child A-B, PS 0 — TACE - **BCLC C (advanced)**: portal vein invasion, extrahepatic spread, Child A-B, PS 1-2 — systemic therapy (atezolizumab + bevacizumab first-line per IMbrave150; alternatives: durvalumab + tremelimumab, lenvatinib, sorafenib) - **BCLC D (terminal)**: Child C, PS 3-4 — best supportive care **Milan criteria** (transplant): 1 lesion ≤ 5 cm OR 2-3 lesions each ≤ 3 cm + no vascular invasion + no extrahepatic — 5-yr survival 70-75% Patient: BCLC A (4.5 cm single, Child A, no portal HTN, no extrahepatic) — resection candidate; transplant alternative; ablation > 3 cm less optimal. A ผิด — sorafenib BCLC C. C ผิด — TACE BCLC B. D ผิดอย่างยิ่ง. E ผิด — HCC not pancreas.",
    difficulty: "medium",
    board_section: "clinical_decision",
    board_topic: "hemato_onco",
    board_age_group: "adult",
    reference_source: "AASLD HCC Practice Guidance 2023; EASL Clinical Practice Guidelines HCC 2018; BCLC Strategy 2022 Update (J Hepatol); Finn RS et al. NEJM 2020 (IMbrave150)",
  },
  {
    scenario: "หญิงไทยอายุ 62 ปี มาด้วยอาการเลือดออกทางทวารหนัก 3 เดือน + น้ำหนักลด 5 กิโลกรัม + ท้องอืด ท้องผูกสลับท้องเสีย\n\nColonoscopy: circumferential mass at sigmoid 25 cm from anal verge, biopsy = moderately differentiated adenocarcinoma\nCT chest/abdomen/pelvis: 4 cm sigmoid mass + perirectal stranding + 3 enlarged regional LNs + 2 liver lesions (1.8 cm and 1.2 cm) suspicious metastatic; no lung disease\nCEA 12.4\n\nMolecular: KRAS wild-type, NRAS wild-type, BRAF wild-type, MSI-stable",
    choices: [
      { label: "A", text: "Palliative surgery alone, no chemotherapy" },
      { label: "B", text: "**Stage IV colorectal cancer with potentially resectable liver metastases (oligometastatic)**: multidisciplinary tumor board: (1) **Restaging + assessment of resectability** — MRI liver, PET-CT to rule out other metastases, hepatobiliary surgery consultation; (2) **Genetic profiling** done — KRAS/NRAS/BRAF wild-type + MSS → candidate for anti-EGFR (cetuximab/panitumumab) **left-sided primary** with chemo (FOLFOX or FOLFIRI + anti-EGFR — preferred in left-sided RAS WT per CALGB/SWOG 80405); (3) **Approach options**: a) **Synchronous resection** (primary + liver met) if low-volume + technically feasible + good surgical team; b) **Staged**: primary first then liver (classic) OR **liver-first (reverse)** in selected — particularly large liver disease with at-risk primary; c) **Perioperative chemotherapy** (3 mo neoadjuvant + 3 mo adjuvant per EPOC trial) before resection if resectable but high risk; (4) **Locally advanced primary**: consider neoadjuvant chemo + adjuvant; (5) **Adjuvant chemo** for 6 mo total perioperative; (6) **Surveillance**: CEA + imaging q3-6 mo × 2 yr then q6 mo; (7) Genetic counseling (Lynch syndrome MSI testing done — stable)" },
      { label: "C", text: "Sigmoid resection only without addressing liver" },
      { label: "D", text: "Chemotherapy alone, no surgery" },
      { label: "E", text: "Radiation only" },
    ],
    correct_answer: "B",
    explanation: "Stage IV CRC with oligometastatic liver disease — 20-30% of stage IV potentially curable. Multidisciplinary critical. **Resectability of liver mets**: anatomical (preserve adequate remnant function, vascular margin) > number/size. Modern era: aggressive approach including major hepatectomy, two-stage hepatectomy, ALPPS, portal vein embolization. **Sidedness** matters: - Left-sided primary (splenic flexure-rectum): better prognosis; RAS WT → anti-EGFR effective - Right-sided primary (cecum-transverse): poorer; RAS WT → anti-VEGF (bevacizumab) preferred over EGFR **Sequencing options for resectable mCRC**: 1. Synchronous resection — selected (limited mets, experienced center) 2. Staged primary-first → adjuvant → liver — classic 3. Liver-first (reverse) — large/symptomatic mets, asymptomatic primary 4. Perioperative chemo (FOLFOX 3+3 months per EPOC) — high-risk **Adjuvant systemic therapy**: backbone FOLFOX or FOLFIRI; biologics by RAS/sidedness; total 6 months perioperative **Surveillance**: CEA, CT, colonoscopy A ผิด — palliative สำหรับ unresectable. C ผิด — ต้องดูแล liver mets ด้วย. D ผิด — primary obstruction. E ผิด — RT ไม่ใช่ first-line สำหรับ sigmoid.",
    difficulty: "hard",
    board_section: "clinical_decision",
    board_topic: "hemato_onco",
    board_age_group: "adult",
    reference_source: "NCCN Colon Cancer 2024; ESMO Metastatic CRC 2023; Venook AP et al. JAMA 2017 (CALGB/SWOG 80405); Nordlinger B et al. Lancet 2013 (EPOC)",
  },
  {
    scenario: "หญิงไทยอายุ 32 ปี G2P1 อายุครรภ์ 28 สัปดาห์ มา ED ด้วยอาการปวดท้องน้อยขวา 18 ชั่วโมง คลื่นไส้อาเจียน\n\nV/S: BP 118/72, HR 98, RR 18, Temp 38.0°C\nAbdomen: tenderness at right flank — appendix displaced superiorly + laterally per pregnancy; rebound mild\nFetal HR 142 bpm regular\n\nLab: WBC 16,800 (normal in pregnancy 6-16k), CRP 88, urinalysis normal\nUS abdomen: appendix not well visualized due to gravid uterus, mild free fluid RLQ\n\nคำถาม: next step",
    choices: [
      { label: "A", text: "CT abdomen with IV contrast" },
      { label: "B", text: "**Suspected acute appendicitis in pregnancy, US non-diagnostic → MRI abdomen without gadolinium** (no radiation, no contrast, sensitivity > 90% for appendicitis in pregnancy); if MRI confirms or strongly suggests appendicitis → **proceed to appendectomy** (laparoscopic preferred in 1st-2nd trimester; open feasible in 3rd trimester depending on surgeon preference + body habitus); (1) **Perioperative**: continuous fetal monitoring (≥ 24 wk), left lateral tilt to avoid IVC compression, OB consultation; (2) **Tocolysis** prophylactic NOT recommended; treat preterm contractions if occur; (3) **Antibiotic**: pregnancy-safe (cefoxitin, ampicillin-sulbactam, or cefazolin + metronidazole as per appendix status) prophylactic single dose, continue if perforation; (4) **Avoid CT** if alternative imaging (MRI) available — minimize fetal radiation; (5) Negative appendectomy rate higher in pregnancy (20-30%) but missed appendicitis = perforation = 35% fetal loss → low threshold to operate; (6) Postoperative VTE prophylaxis + fetal surveillance",
      },
      { label: "C", text: "Observation 24 hr without imaging" },
      { label: "D", text: "Conservative antibiotic only, no surgery" },
      { label: "E", text: "Cesarean delivery + appendectomy together" },
    ],
    correct_answer: "B",
    explanation: "Appendicitis in pregnancy — most common non-OB surgical emergency (1:1,500 pregnancies). Diagnosis challenging — appendix migrates upward + lateral as pregnancy advances. Classic Alvarado less reliable. WBC physiologically elevated. **Imaging in pregnancy**: 1. **Ultrasound** — first-line, but sensitivity drops as pregnancy advances (limited visualization 3rd trimester) 2. **MRI without gadolinium** — preferred next; sensitivity > 90%, specificity > 95%; safe in pregnancy (gadolinium AVOID — crosses placenta) 3. **CT** — reserved if MRI unavailable; fetal radiation < 5 mSv per CT abdomen pelvis is below teratogenic threshold but minimize **Surgical approach**: - Laparoscopic appendectomy safe in 1st-2nd trimester, feasible in 3rd (depends on uterus size) - Lower CO2 pressure (10-12 mmHg) - Left lateral tilt to avoid aortocaval compression - Trocar placement adjusted for gravid uterus **Risks**: - Negative appendectomy 20-30% (acceptable to avoid missed dx) - Perforation → 35% fetal loss; non-perforated 5% - Maternal mortality < 1% **Antibiotic**: pregnancy-safe; cefazolin, ampicillin-sulbactam, cefoxitin OK; tetracycline + fluoroquinolone avoid A ผิด — CT avoid if MRI available. C ผิด — high stakes ต้อง diagnose. D ผิด — controversial in pregnancy, surgical safer. E ผิด — ไม่มี indication delivery 28 wk.",
    difficulty: "medium",
    board_section: "clinical_decision",
    board_topic: "obgyn",
    board_age_group: "adult",
    reference_source: "SAGES Guidelines Laparoscopic Surgery in Pregnancy; ACOG Committee Opinion 723; ACR Appropriateness Criteria; Tolcher MC et al. Am J Obstet Gynecol 2018",
  },
  {
    scenario: "ชายไทยอายุ 55 ปี โดนน้ำร้อนลวก ทั้งหน้า + ขาทั้งสองข้าง + แขนซ้าย + ลำตัวด้านหน้า\n\nV/S: BP 102/68, HR 116, RR 22, Temp 37.0°C, SpO2 96%\nGen: alert, voice hoarse, singed nasal hair, soot in oropharynx\nBurn: partial + full thickness — face 9% + bilateral leg ant. 18% + left arm anterior 4.5% + anterior trunk 18% ≈ 49.5% TBSA\nWeight 70 kg",
    choices: [
      { label: "A", text: "Lactate Ringer 4 mL/kg/%TBSA × 24h start" },
      { label: "B", text: "**Severe burn 49.5% TBSA + suspected inhalational injury — comprehensive resuscitation**: (1) **Airway**: signs of inhalational injury (singed nasal hair, soot, hoarse voice, facial burn, closed-space fire) → **early intubation** before edema obstructs airway — do NOT wait; bronchoscopy to assess; carboxyhemoglobin level (CO poisoning) — 100% O2; HCN poisoning (close-space fire) → hydroxocobalamin; (2) **Fluid resuscitation Parkland formula**: 4 mL × 70 kg × 49.5% = **13,860 mL Lactated Ringer's over 24h** — first half (6,930 mL) over 8h from BURN time (not arrival), second half over 16h; adjust to UO 0.5 mL/kg/hr (30-50 mL/hr adult); recent trend toward lower volume to avoid 'fluid creep' — start 2 mL/kg/%TBSA in mod severity, 4 mL/kg/%TBSA in severe + inhalation; (3) **Tetanus prophylaxis**; (4) **Wound care**: cool burn wounds with room-temp NSS-soaked gauze (NOT ice), debride loose epidermis, topical silver sulfadiazine or silver dressings; **escharotomy** for circumferential full-thickness burns (limbs, chest) — vascular/respiratory compromise; (5) **Pain control**: IV opioids; (6) **Nutrition**: early enteral high-protein high-calorie (3000-4000 kcal/day); (7) **Transfer to burn center** if > 10% TBSA + inhalation OR > 20% TBSA OR major burn (face, hands, feet, genitalia, joints); (8) ICU monitoring",
      },
      { label: "C", text: "Oral hydration + outpatient" },
      { label: "D", text: "Surgery immediate full debridement day 1" },
      { label: "E", text: "Steroid IV high dose for inhalational" },
    ],
    correct_answer: "B",
    explanation: "Major burn management — ABA criteria: > 10% TBSA full-thickness, > 20% TBSA total, special areas (face, hands, feet, perineum, joints), chemical, electrical, inhalational, comorbidities → burn center **TBSA calculation**: Rule of Nines (adult): head 9%, each arm 9%, each leg 18% (9 ant + 9 post), trunk anterior 18%, posterior 18%, perineum 1% — Lund-Browder more accurate (pediatric) **Burn depth**: - Superficial (1st°): epidermis, erythema, painful — heal 3-7 days, exclude from TBSA - Superficial partial (2nd°): dermis (papillary), blisters, painful — heal 7-21 days - Deep partial (2nd°): deep dermis, less pain, slow heal 3-6 wk → may need grafting - Full thickness (3rd°): all skin, painless, leathery — graft - 4th°: muscle/bone — extensive **Parkland formula**: 4 mL/kg/%TBSA Lactated Ringer's first 24h from burn time; ½ in first 8h, ½ next 16h; target UO 0.5 mL/kg/hr (adult), 1 mL/kg/hr (peds). Modified Brooke (2 mL/kg/%TBSA) — lower volume option. **Inhalational injury**: 30-40% mortality if extensive burns; early intubation, FOB diagnosis, bronchodilator, suctioning. **Escharotomy**: circumferential burns chest (limit ventilation) or limbs (compartment syndrome). A partial — formula correct but inhalation/airway crucial. C ผิดอย่างยิ่ง. D ผิด — early total excision 5-7 days. E ผิด — steroid harmful in inhalation.",
    difficulty: "medium",
    board_section: "clinical_decision",
    board_topic: "trauma",
    board_age_group: "adult",
    reference_source: "ABLS Provider Manual 2018; ISBI Practice Guidelines for Burn Care 2016; Parkland Formula (Baxter & Shires 1968); Pham TN et al. J Burn Care Res 2008",
  },
  {
    scenario: "ชายไทยอายุ 45 ปี รักษาที่บ้านจากแมลงสัตว์กัด ขาขวา 2 วัน ขาขวาบวมแดงร้อนมาก ไข้สูง\n\nV/S: BP 78/48, HR 138, RR 28, Temp 39.8°C\nLeg: erythema rapidly spreading + bullae hemorrhagic + crepitus on palpation + pain out of proportion + skin necrosis patches\nLab: WBC 24,000 with bands 18%, Cr 2.4, lactate 5.2, glucose 280, Na 128, CK 4800, LRINEC score = 9\n\nคำถาม: management",
    choices: [
      { label: "A", text: "Oral antibiotic + outpatient" },
      { label: "B", text: "**Necrotizing fasciitis — surgical emergency + septic shock**: (1) **Immediate resuscitation** + IV fluid + vasopressor (norepinephrine first-line); ICU; (2) **Emergent surgical debridement** within HOURS of diagnosis (mortality increases ~9% per hour delay) — wide debridement of ALL non-viable tissue, may need amputation; second-look debridement 24-48h; goal aggressive debridement until viable bleeding tissue; (3) **Empiric broad-spectrum IV antibiotics** ASAP — coverage: gram-positive (incl MRSA: vancomycin/linezolid), gram-negative, anaerobes — **piperacillin-tazobactam + vancomycin + clindamycin** (clindamycin = toxin suppression key for Strep + Staph); de-escalate per culture; (4) **Gram stain + cultures** at debridement: Type I polymicrobial 70% (mixed aerobic/anaerobic incl Bacteroides, E. coli) Type II monomicrobial (GAS, S. aureus incl MRSA, V. vulnificus marine) Type III (Clostridium gas gangrene — Fournier's gangrene perineum); (5) **Adjunctive**: IVIG (Type II Strep TSS — controversial benefit), hyperbaric oxygen (selected centers — Clostridial), no proven survival benefit but considered; (6) Wound VAC after debridement; reconstruction later; (7) Mortality 25-35%",
      },
      { label: "C", text: "Antibiotic only, no surgery" },
      { label: "D", text: "Wait for culture results before debridement" },
      { label: "E", text: "Topical antibiotic" },
    ],
    correct_answer: "B",
    explanation: "Necrotizing soft tissue infection (NSTI) — life-threatening, surgical emergency. Mortality 25-40%. **Risk factors**: DM (most common), trauma, IVDU, immunocompromise, NSAID use (delays diagnosis), pre-existing skin lesion. **LRINEC score** (Laboratory Risk Indicator for NF): CRP > 150, WBC, Hb, Na < 135, Cr > 1.6, Glucose > 180; score ≥ 6 high suspicion, ≥ 8 high risk. Not perfectly sensitive — clinical suspicion paramount. **Clinical**: pain out of proportion (early sign), rapid spread, bullae, crepitus (gas), skin necrosis (late), sepsis. **Types**: I) Polymicrobial (DM, abdominal, perineum/Fournier's) — 70% II) Monomicrobial — GAS, S. aureus, V. vulnificus (marine exposure) III) Clostridial myonecrosis (gas gangrene) — trauma, post-surgery **Treatment principles**: 1. EMERGENT wide surgical debridement (best predictor of survival) 2. Broad-spectrum antibiotics with anti-toxin (clindamycin) 3. ICU resuscitation, source control, repeat OR q24-48h 4. Late: reconstruction Imaging (CT, MRI) helpful but DO NOT delay surgery if clinical diagnosis. A C E ผิดอย่างยิ่ง — antibiotic alone = death. D ผิด — wait = death.",
    difficulty: "easy",
    board_section: "clinical_decision",
    board_topic: "id",
    board_age_group: "adult",
    reference_source: "IDSA Skin and Soft Tissue Infection Guidelines 2014; Stevens DL et al. CID 2014; Wong CH et al. Crit Care Med 2004 (LRINEC); WSES Necrotizing Soft Tissue Infections 2018",
  },
  {
    scenario: "หญิงไทยอายุ 28 ปี G1P0 28 weeks GA appendicitis + appendectomy 5 วันก่อน admission กลับมาด้วยไข้ ปวดท้องน้อยขวา\n\nV/S: BP 116/72, HR 102, RR 18, Temp 38.6°C\nAbdomen: RLQ tender, no peritonitis\nFetal HR 140 reactive\n\nLab: WBC 17,200, CRP 198\nUS abdomen: fluid collection 5x4 cm at RLQ deep to wound site, suspected abscess",
    choices: [
      { label: "A", text: "Re-exploration laparotomy" },
      { label: "B", text: "**Post-operative intra-abdominal abscess in pregnancy**: (1) **CT-guided or US-guided percutaneous drainage** — preferred over re-exploration (less morbidity, preserve gestation); US-guided preferred in pregnancy to avoid radiation; (2) **IV broad-spectrum antibiotic** — pregnancy-safe (e.g., piperacillin-tazobactam, ceftriaxone + metronidazole) × 10-14 days; (3) **Drain management** — culture-directed antibiotic adjustment, output monitoring, drain in place until resolution; repeat imaging q4-7 days; (4) **Maternal-fetal monitoring** — fetal HR, contractions, infection markers, growth scan; OB co-management; (5) **Surgical re-exploration** if: failure of percutaneous drainage, hemodynamic instability, peritonitis, generalized sepsis, multi-loculated abscess inaccessible; (6) **Nutritional support** maternal; (7) Postpartum follow-up; consider underlying immune state",
      },
      { label: "C", text: "Oral antibiotic outpatient" },
      { label: "D", text: "Observation alone" },
      { label: "E", text: "Cesarean delivery preterm to access" },
    ],
    correct_answer: "B",
    explanation: "Post-operative intra-abdominal abscess — 4-10% after appendectomy (higher post perforation). Pregnancy considerations: avoid CT if possible, use US/MRI guidance. Percutaneous drainage success rate 80-90% for accessible unilocular abscess. Re-exploration reserved for failure or complications. Antibiotics in pregnancy: penicillins, cephalosporins, clindamycin, metronidazole all category B; avoid tetracyclines, fluoroquinolones (cartilage), sulfa (3rd trimester — kernicterus). Premature delivery NOT indicated for maternal infection unless severe sepsis + viable gestation + maternal life-threatening. A ผิด — invasive. C ผิด — IV. D ผิดอย่างยิ่ง. E ผิด — preterm at 28 wk significant fetal morbidity.",
    difficulty: "medium",
    board_section: "clinical_decision",
    board_topic: "id",
    board_age_group: "adult",
    reference_source: "ACOG Committee Opinion; WSES Intra-abdominal Infection Guidelines 2017; Sartelli M et al. World J Emerg Surg",
  },
  {
    scenario: "ชายไทยอายุ 45 ปี post-op day 4 laparotomy for perforated peptic ulcer ตื่นมาบ่นปวดท้อง ไข้ขึ้น 39°C\n\nV/S: BP 88/52, HR 128, RR 26, Temp 39.4°C\nAbdomen: distended, tender diffuse, surgical wound serosanguinous discharge\n\nLab: WBC 22,400, lactate 4.2, Cr 1.8\nCT abdomen: 3 fluid collections + free fluid moderate + suspected anastomotic leak\n\nคำถาม: management",
    choices: [
      { label: "A", text: "Observation + IV antibiotic only" },
      { label: "B", text: "**Postoperative anastomotic leak with intra-abdominal sepsis — surgical emergency**: (1) **Resuscitation** + vasopressor + ICU; (2) **Broad-spectrum IV antibiotic** + antifungal (Candida if persistent leak/TPN) — piperacillin-tazobactam ± vancomycin ± fluconazole; (3) **Source control** — re-exploration laparotomy preferred over percutaneous in unstable / generalized peritonitis: identify + control leak (primary repair, diversion stoma, exteriorization, or end stoma), wash out, place drains, consider damage control with open abdomen + temporary closure (Bogota bag, vacuum-assisted) for severe contamination; (4) **Nutritional support** — TPN initially, transition enteral when feasible (NJ tube past leak); (5) **Drain management** + serial imaging; (6) **Reconstruction** delayed 3-6 months after recovery + nutritional optimization; (7) **Treat ongoing risk factors**: control DM, optimize nutrition, smoking cessation",
      },
      { label: "C", text: "Endoscopic clip closure first" },
      { label: "D", text: "Discharge home for outpatient antibiotic" },
      { label: "E", text: "Total parenteral nutrition only" },
    ],
    correct_answer: "B",
    explanation: "Anastomotic leak — major cause of post-op morbidity + mortality after GI surgery (mortality 5-20%, higher with sepsis). Risk factors: tension at anastomosis, poor blood supply, contamination, malnutrition, smoking, steroids, DM, emergency surgery, hemodynamic instability. **Diagnosis**: high index of suspicion in post-op day 3-7 patient with sepsis, tachycardia, ileus, wound drainage. CT with oral + IV contrast — extravasation, free fluid, fluid collections, free air. **Management principles** (controlled vs uncontrolled): - **Controlled leak**: contained collection, stable patient, adequate drainage — percutaneous drain + IV antibiotic + NPO + bowel rest - **Uncontrolled leak**: generalized peritonitis, sepsis, hemodynamic instability — emergent re-operation **Surgical options**: - Primary repair (small early leak, healthy tissue) - Diverting loop ileostomy/colostomy + drain - Resection + end stoma (Hartmann's-type) - Damage control if unstable: control + temporary closure + return Endoscopic options: clips (small), stents (selected esophagogastric), endoscopic vacuum (selected anastomotic). A ผิด — sepsis ต้อง source control. C ผิด — clip ไม่พอ severe. D ผิดอย่างยิ่ง. E ผิด — TPN ไม่ใช่ definitive.",
    difficulty: "hard",
    board_section: "clinical_decision",
    board_topic: "gi",
    board_age_group: "adult",
    reference_source: "ESCP Anastomotic Leak Consensus 2020; WSES Surgical Sepsis Guidelines; Hyman N et al. Dis Colon Rectum",
  },
  {
    scenario: "หญิงไทยอายุ 35 ปี มาด้วยอาการคลำได้ก้อนนมข้างขวา quadrant 3 cm ขนาด 4 ซม. นาน 6 เดือน ไม่เจ็บ ไม่มี nipple discharge\n\nMammogram: BI-RADS 4C (suspicious — 5-95% probability)\nUS: solid mass 4 cm, hypoechoic, irregular margin\nCore biopsy: invasive lobular carcinoma, grade 2, ER 99%+, PR 80%+, HER2 0, Ki-67 12%\nAxillary US: 1 enlarged node 1.5 cm cortical thickening — FNAC positive metastatic carcinoma\n\nStaging CT: no distant metastasis\nClinical T2 (4cm) N1 M0",
    choices: [
      { label: "A", text: "Lumpectomy alone, no axillary surgery" },
      { label: "B", text: "**Stage IIB invasive lobular carcinoma, cN1 — multimodal management**: (1) **Neoadjuvant approach considered**: ILC less chemosensitive than IDC + HR-strong + Ki-67 low → **neoadjuvant endocrine therapy (aromatase inhibitor for postmenopausal, ovarian suppression + AI or tamoxifen premenopausal)** — alternative to neoadjuvant chemo in luminal A-like; (2) **Surgical**: - **Mastectomy** often preferred for ILC (multifocal, infiltrative pattern, MRI more accurate for extent) — or BCS if margins achievable + acceptable cosmesis - **Axillary management**: with biopsy-confirmed nodal disease (cN1) → **axillary lymph node dissection (ALND)** standard (post-neoadjuvant may convert to SLNB with dual tracer + clip per ACOSOG Z1071); (3) **Radiation**: post-mastectomy RT for T3/T4 OR ≥ 4 + nodes; consider in T2N1 high-risk; post-BCS WBRT mandatory + regional nodal irradiation; (4) **Adjuvant systemic**: - **Endocrine therapy 5-10 years** + abemaciclib if high-risk per monarchE (≥ 4 nodes OR 1-3 nodes + high-risk feature) - **Adjuvant chemo** controversial in low-Ki-67 ILC; Oncotype DX has caveats in ILC (lower utility); often endocrine alone if T2N1 luminal A; (5) **Genetic testing** — younger age + family history + lobular (CDH1 = E-cadherin germline → hereditary diffuse gastric ca + lobular breast); (6) Survivorship + surveillance + lifestyle",
      },
      { label: "C", text: "Tamoxifen alone, no surgery" },
      { label: "D", text: "Observation only" },
      { label: "E", text: "Mastectomy alone, no systemic therapy" },
    ],
    correct_answer: "B",
    explanation: "Invasive Lobular Carcinoma (ILC) — 10-15% of breast cancer. Characteristics: - E-cadherin loss (CDH1) — single-file infiltrative pattern - Often multifocal, multicentric, bilateral - Mammographic occult (infiltrative without mass) — MRI more accurate for extent - Usually HR-positive (95%), HER2 low/neg, lower Ki-67 → luminal A-like - Less chemosensitive than IDC; more endocrine-sensitive - Metastatic pattern: peritoneum, GI tract, ovary, leptomeninges (unusual sites) **Management nuances**: 1. MRI breast pre-op to assess extent (multifocal common) 2. Mastectomy more often than BCS due to extent + margin difficulty 3. SLNB acceptable for clinically node-negative; ALND if N1+ confirmed (or post-neoadjuvant per Z1071) 4. Neoadjuvant chemo less effective; consider neoadjuvant endocrine in HR-strong + postmenopausal 5. Adjuvant: long-term endocrine 5-10 years; abemaciclib (monarchE) for high-risk HR+/HER2- 6. Oncotype DX has lower utility in ILC than IDC (validation issues) 7. Genetic — CDH1 germline assoc with HDGC (hereditary diffuse gastric ca) — refer A ผิด — nodal disease ต้อง axillary surgery. C ผิด — surgery essential. D ผิดอย่างยิ่ง. E ผิด — adjuvant systemic ต้องมี.",
    difficulty: "hard",
    board_section: "clinical_decision",
    board_topic: "hemato_onco",
    board_age_group: "adult",
    reference_source: "NCCN Breast Cancer 2024; St Gallen 2023; ASCO Guidelines on Endocrine Therapy; Johnston SRD et al. JCO 2020 (monarchE)",
  },
  {
    scenario: "ชายไทยอายุ 52 ปี underlying DM, HT มาด้วยอาการ painful neck mass 3 วัน หนาวสั่น ไข้สูง กลืนเจ็บ\n\nV/S: BP 108/68, HR 116, RR 22, Temp 39.4°C\nNeck: tender mass anterior to SCM left side 6 cm + erythema + tenderness + trismus + drooling\nOral: poor dentition, swelling lower jaw + floor of mouth tenderness, tongue elevated\n\nLab: WBC 22,400, CRP 240, glucose 380\nCT neck with contrast: deep neck space infection involving submandibular + parapharyngeal + retropharyngeal spaces + airway narrowing 50%",
    choices: [
      { label: "A", text: "Oral antibiotic + outpatient" },
      { label: "B", text: "**Ludwig's angina + deep neck space infection — airway emergency**: (1) **Airway first**: anticipate difficult airway → **awake fiberoptic intubation** or **early surgical airway (tracheostomy)** in OR with surgical airway backup; avoid sedation that loses airway; (2) **ICU admission**; (3) **IV broad-spectrum antibiotic** ASAP — cover oral flora (strep + anaerobes incl Bacteroides) — **ampicillin-sulbactam OR clindamycin + ceftriaxone OR piperacillin-tazobactam**; add vancomycin if MRSA risk; (4) **Surgical drainage** of deep neck space infection — incision + drainage of involved spaces (submandibular, submental, parapharyngeal, retropharyngeal as needed) + dental extraction if odontogenic source; obtain cultures; (5) **DM control** — IV insulin, glucose monitoring; (6) **Monitor for complications**: descending mediastinitis (CT chest if suspected — high mortality), Lemierre's syndrome (jugular thrombophlebitis), sepsis, airway compromise; (7) Dental/ENT consultation; (8) Postdischarge dental care",
      },
      { label: "C", text: "Wait for airway compromise then intubate" },
      { label: "D", text: "Antibiotic only without drainage" },
      { label: "E", text: "Steroids high dose alone" },
    ],
    correct_answer: "B",
    explanation: "Ludwig's angina — bilateral submandibular + sublingual + submental space cellulitis. Usually odontogenic (lower molars). Rapid spread + airway threat + descending mediastinitis risk. **Mortality**: 50%+ pre-antibiotic, 5-10% modern era. **Anatomy of deep neck spaces**: - Submandibular (Ludwig's) - Parapharyngeal — communicates with retropharyngeal, mediastinum - Retropharyngeal — extends to mediastinum (danger space) - Prevertebral - Carotid sheath **Airway management** critical: - Early intubation BEFORE airway loss - Anticipate difficulty (trismus, floor mouth edema, tongue displacement) - Awake fiberoptic preferred - Surgical airway (tracheostomy or cricothyroidotomy) ready - Avoid blind intubation, paralytics if uncertain **Antibiotics**: cover oral flora — strep, anaerobes (Bacteroides, Prevotella, Fusobacterium); β-lactam/inhibitor + clindamycin standard. Vanco if MRSA suspected. **Surgical**: drain abscesses, address source (dental). **Complications**: - Descending necrotizing mediastinitis (50% mortality) — high CT chest if persistent fever, chest symptoms - Lemierre's syndrome — Fusobacterium necrophorum jugular thrombophlebitis with septic emboli A ผิด — ผู้ป่วยรุนแรง. C ผิดอย่างยิ่ง — pre-emptive airway. D ผิด — ต้อง drain. E ผิด — steroid bukan first-line.",
    difficulty: "hard",
    board_section: "clinical_decision",
    board_topic: "id",
    board_age_group: "adult",
    reference_source: "IDSA Skin/Soft Tissue Infection Guidelines; UpToDate Ludwig's Angina; Vieira F et al. Otolaryngol Clin North Am",
  },
  {
    scenario: "ชายไทยอายุ 22 ปี ดื่มเหล้าหนัก พบในที่เกิดเหตุไม่รู้สึกตัว มี alcohol smell ตกบันได\n\nGCS = 6 (E1V2M3), pupils unequal — right 5mm fixed dilated, left 3mm reactive; ทั่วศีรษะมี laceration + scalp hematoma right side\nV/S: BP 168/96, HR 56, RR 12 irregular (Cushing's reflex)\nNo other obvious injury\n\nCT brain: right acute subdural hematoma 12 mm + midline shift 8 mm + uncal herniation\n\nคำถาม: management",
    choices: [
      { label: "A", text: "Observation + serial neurological exam" },
      { label: "B", text: "**Severe TBI + acute SDH with uncal herniation — neurosurgical emergency**: (1) **ABC + protect airway** — RSI intubation (cervical spine precaution) with neuroprotective induction (avoid hypotension + hypoxia which double mortality); (2) **Maintain CPP > 60-70 mmHg**, MAP > 80, avoid hypotension (SBP > 110 if no other contraindication per BTF 4th ed), avoid hypoxia (SpO2 > 94%); (3) **Temporary measures for raised ICP / herniation**: - **Head of bed 30°**, head midline (jugular drainage) - **Hyperventilation TARGET PaCO2 30-35** (briefly, for impending herniation — vasoconstriction reduces ICP; not prolonged → ischemia) - **Mannitol 1 g/kg IV OR hypertonic saline 3% bolus 250 mL** — osmotic ICP reduction - **Sedation + analgesia**; paralytic if needed for asynchrony; (4) **Emergent neurosurgical decompression** — craniotomy + SDH evacuation ± decompressive craniectomy; (5) **ICP monitoring** post-op (intraventricular catheter preferred — diagnostic + therapeutic CSF drainage); (6) **TXA** — CRASH-3 trial: IV TXA within 3h of mild-moderate TBI reduces head injury death; (7) **Avoid steroids** (CRASH-1 — increased mortality in TBI); (8) **Anti-seizure** prophylaxis 7 days (levetiracetam preferred); (9) **DVT prophylaxis** — mechanical until 24-72h post-stable head CT, then chemical; (10) ICU + multidisciplinary",
      },
      { label: "C", text: "Steroid IV high dose" },
      { label: "D", text: "Aggressive hyperventilation PaCO2 < 25 sustained" },
      { label: "E", text: "Wait CT repeat tomorrow" },
    ],
    correct_answer: "B",
    explanation: "Severe TBI management — Brain Trauma Foundation (BTF) 4th edition + ATLS: **Primary brain injury** (initial trauma) + **secondary brain injury** (hypotension, hypoxia, ↑ICP, hypoglycemia, hyperthermia, seizures) — preventable secondary injury is target. **Severe TBI**: GCS ≤ 8 — intubate, ICP monitoring **Surgical SDH evacuation indications**: > 10 mm thickness OR midline shift > 5 mm OR GCS deteriorating OR pupillary abnormality OR ICP > 20 mmHg sustained **CPP** (Cerebral Perfusion Pressure = MAP - ICP): target 60-70 (BTF) — too high → ARDS risk; too low → ischemia **ICP** management tiered: 1. Head elevation, sedation, normothermia, normoglycemia 2. Osmotic therapy: mannitol 0.25-1 g/kg OR hypertonic saline 3. CSF drainage via EVD 4. Hyperventilation (rescue — brief) PaCO2 30-35; avoid PaCO2 < 30 (ischemia) 5. Decompressive craniectomy 6. Barbiturate coma (last resort) **CRASH-3** trial 2019: TXA within 3h of mild-moderate TBI reduces head injury-related death. **Glucose**: 140-180 target — avoid hyperglycemia + hypoglycemia. **Avoid**: prolonged severe hyperventilation, steroids, hypotension, hypoxia. A C E ผิดอย่างยิ่ง. D ผิด — brief PaCO2 30-35 OK, not < 25 sustained.",
    difficulty: "hard",
    board_section: "clinical_decision",
    board_topic: "trauma",
    board_age_group: "adult",
    reference_source: "Brain Trauma Foundation Guidelines 4th Edition 2017; CRASH-3 Trial Lancet 2019; ATLS 10th Ed; SIBICC Algorithm",
  },
  {
    scenario: "หญิงไทยอายุ 25 ปี ไม่มีโรคประจำตัว มาด้วยอาการ neck mass บริเวณ thyroid โตขึ้น 6 เดือน ไม่มี hyperthyroid symptoms\n\nExamination: 2 cm hard nodule right lobe + cervical lymphadenopathy ipsilateral\nUS thyroid: 2 cm hypoechoic solid nodule with microcalcifications + irregular margin + taller-than-wide + TIRADS 5\nFNA: papillary thyroid carcinoma (PTC)\n\nTFTs: euthyroid; calcitonin normal\nStaging CT neck: no distant metastasis, several ipsilateral central + lateral compartment lymph nodes suspicious",
    choices: [
      { label: "A", text: "Thyroid lobectomy alone, no node dissection" },
      { label: "B", text: "**Papillary thyroid carcinoma cT2N1b (lateral nodal disease) — extensive surgery**: (1) **Total thyroidectomy** — indicated for tumors > 4 cm, gross extrathyroidal extension, clinically apparent nodal disease, distant metastases, prior head/neck radiation; this patient: nodal disease present → total thyroidectomy preferred over lobectomy; (2) **Central compartment lymph node dissection (level VI)** — therapeutic for clinically positive central nodes; prophylactic for select high-risk; (3) **Modified radical neck dissection (lateral compartment levels II-V)** — therapeutic for biopsy-proven lateral nodal disease (functional dissection preserving SCM, IJ, spinal accessory n. when possible); (4) **Postop**: serum thyroglobulin (Tg) + anti-Tg Ab — surveillance marker; calcium monitoring (hypoparathyroidism risk); recurrent laryngeal n. evaluation; (5) **Radioactive iodine (RAI I-131) ablation** — indicated for higher risk: > 4 cm, extrathyroidal extension, nodal disease (esp. > 5 nodes OR > 1 cm OR extranodal extension), distant metastases; dose 30-150 mCi; (6) **TSH suppression** with levothyroxine — target TSH < 0.1 in high-risk, 0.1-0.5 intermediate, 0.5-2 low-risk; (7) **Long-term surveillance**: serum Tg, neck US, possible whole-body scan; (8) Genetic counseling if family history",
      },
      { label: "C", text: "Active surveillance only" },
      { label: "D", text: "Chemotherapy first-line" },
      { label: "E", text: "Radiation alone, no surgery" },
    ],
    correct_answer: "B",
    explanation: "Papillary Thyroid Carcinoma (PTC) — most common (80-85% of thyroid Ca). Excellent prognosis overall (10-year survival > 95% in localized). **ATA Risk stratification** (2015 guidelines): - **Low risk**: intrathyroidal PTC ≤ 4 cm, no nodal/distant mets, no aggressive variant - **Intermediate**: gross extrathyroidal extension, vascular invasion, > 5 LN involved (small), aggressive histology - **High**: gross extrathyroidal invasion, incomplete resection, distant mets, large nodal disease **Surgical extent**: - **Lobectomy** for ≤ 4 cm, intrathyroidal, no nodes, low-risk — recent trend - **Total thyroidectomy** for: > 4 cm, gross ETE, distant mets, nodal disease, bilateral, prior H&N RT, contralateral nodule **Lymph node dissection**: - Therapeutic central (VI) for clinically involved central nodes - Therapeutic lateral (II-V) for biopsy-proven lateral nodes (modified radical) - Prophylactic central — controversial; consider T3/T4 **RAI ablation**: post-total thyroidectomy, intermediate-high risk — destroys residual + treats microscopic + mets **TSH suppression** with LT4 reduces recurrence in higher risk **Active surveillance** — selected microcarcinoma (≤ 1 cm) no node/ETE — not appropriate here (2 cm, N1b) A ผิด — N1 + 2cm ต้อง total + dissection. C ผิด — N1 disease ไม่ใช่ active surveillance candidate. D ผิด — chemo ไม่ใช่ first-line PTC. E ผิด — RAI not external RT.",
    difficulty: "medium",
    board_section: "clinical_decision",
    board_topic: "endocrine_metabolic",
    board_age_group: "adult",
    reference_source: "ATA Guidelines for Thyroid Nodules and Differentiated Thyroid Cancer 2015; NCCN Thyroid Carcinoma 2024; Haugen BR et al. Thyroid 2016",
  },
  {
    scenario: "ชายไทยอายุ 68 ปี smoker 60 pack-yr มาด้วยอาการปวดน่อง ขณะเดิน 100 เมตร 6 เดือน รุนแรงขึ้นเป็น 50 เมตร 2 สัปดาห์ ขาขวาเย็น ปวดเวลานอน\n\nExamination: cool right foot, absent right popliteal + dorsalis pedis + posterior tibial pulses, capillary refill > 4 sec, ulcer 1 cm at heel non-healing\nABI: right 0.32 (severe), left 0.78 (mild-moderate)\nDoppler: monophasic flow right SFA + popliteal\nCT angiography: long-segment SFA occlusion right + multilevel atherosclerosis\n\nคำถาม: management",
    choices: [
      { label: "A", text: "Continue medical therapy only" },
      { label: "B", text: "**Critical limb-threatening ischemia (CLTI, formerly CLI) — limb salvage approach**: (1) **Risk factor modification + medical optimization**: smoking cessation (most important), statin (high-intensity), antiplatelet (aspirin or clopidogrel; consider DOAC + aspirin per VOYAGER PAD — rivaroxaban 2.5 BID + ASA), BP control, glycemic control, supervised exercise (claudication only); (2) **Revascularization** indicated for CLTI — improves limb salvage + survival: - **Endovascular**: angioplasty ± stent (drug-eluting), atherectomy — preferred first in many; appropriate for short-segment, focal disease - **Open bypass**: femoropopliteal, fem-distal bypass with autologous vein (saphenous) — better long-term patency for long-segment disease; prosthetic if vein unavailable - **BEST-CLI trial (NEJM 2022)**: surgical bypass with adequate vein conduit superior to endovascular for major adverse limb events + need for re-intervention in CLTI; endovascular alternative if no good vein; (3) **Wound care + offloading** for foot ulcer; podiatry; (4) **Multidisciplinary** vascular surgery + IR + wound care + diabetes + podiatry; (5) **Amputation only if not revascularizable / non-salvageable limb**; (6) Lifelong surveillance + medical therapy",
      },
      { label: "C", text: "Primary amputation" },
      { label: "D", text: "Beta-blocker + observation" },
      { label: "E", text: "Anticoagulation alone" },
    ],
    correct_answer: "B",
    explanation: "**Peripheral Artery Disease (PAD)** classification (Rutherford / Fontaine): - **Claudication (Rutherford 1-3 / Fontaine II)**: pain with exertion - **CLTI (Rutherford 4-6 / Fontaine III-IV)**: rest pain (4), ulceration (5), gangrene (6) — limb-threatening **Diagnosis**: ABI (0.9-1.4 normal; < 0.9 PAD; < 0.4 severe); TBI in non-compressible (DM, ESRD — vessel calcification); duplex; CT/MR angio; conventional angio. **ABI > 1.4** suggests non-compressible — get TBI/PVR. **CLTI Management** (ESVS + AHA 2022 + Global Vascular Guidelines): - Medical: smoking cessation, statin, antiplatelet, glycemic, BP - Revascularization always considered if limb salvageable - WIfI score (Wound, Ischemia, foot Infection) — stratify - **BEST-CLI (NEJM 2022)**: bypass with adequate vein > endovascular for MALE outcomes in CLTI with single-segment GSV - **BASIL-2 (Lancet 2023)**: endovascular non-inferior in some subgroups - **Antithrombotic** — VOYAGER PAD: rivaroxaban 2.5 BID + ASA reduces MALE post-revascularization; COMPASS regimen for stable PAD **Claudication only** (not CLTI): - First-line: supervised exercise + medical + risk factor - Revascularization if lifestyle-limiting after trial - Cilostazol — phosphodiesterase inhibitor for symptoms A ผิด — CLTI ต้อง revascularize. C ผิด — limb still salvageable. D E ผิด — ไม่พอ.",
    difficulty: "medium",
    board_section: "clinical_decision",
    board_topic: "vascular",
    board_age_group: "adult",
    reference_source: "Global Vascular Guidelines on Management of CLTI (ESVS/SVS/WFVS 2019); AHA/ACC PAD 2016; Farber A et al. NEJM 2022 (BEST-CLI); Bonaca MP et al. NEJM 2020 (VOYAGER PAD)",
  },
  {
    scenario: "เด็กชายไทยอายุ 6 สัปดาห์ มาด้วยอาเจียนพุ่งเป็นน้ำนม 2 สัปดาห์ น้ำหนักลด ตาลึก ปัสสาวะน้อย\n\nExam: alert but lethargic, dehydrated, palpable olive-shaped mass RUQ, visible peristalsis epigastric\nWeight 4.0 kg (10th percentile)\n\nLab: Na 128, K 2.8, Cl 84, HCO3 36, BUN 22, Cr 0.6, glucose 76\nABG: pH 7.52, PaCO2 48, HCO3 38 (hypochloremic hypokalemic metabolic alkalosis)\nUS: pyloric muscle thickness 5 mm, length 18 mm, target sign — diagnosis of pyloric stenosis",
    choices: [
      { label: "A", text: "Emergency pyloromyotomy immediately" },
      { label: "B", text: "**Hypertrophic pyloric stenosis — surgical disease but MEDICAL EMERGENCY of correcting metabolic alkalosis + dehydration FIRST**: (1) **NPO + NG decompression**; (2) **IV fluid resuscitation + electrolyte correction** — D5 ½NS with 20-40 mEq KCl/L after urine output established; goal: correct dehydration, normalize Cl > 100, HCO3 < 30, K > 3.5, urine output > 1 mL/kg/hr — usually takes 24-48 hr; (3) **Then surgery**: Ramstedt **pyloromyotomy** (open or laparoscopic) — split serosa + muscularis longitudinally without breaching mucosa; (4) **Postop feeding**: ad lib feeding within hours (recent evidence) OR scheduled advance; vomiting common 24-48h then resolves; (5) **Avoid emergency surgery before correction** — anesthesia in alkalotic patient → hypoventilation + respiratory acidosis + hypoxia + apnea; mortality risk; (6) **Outcome**: excellent — > 99% cure",
      },
      { label: "C", text: "Oral rehydration + delay surgery 1 week" },
      { label: "D", text: "Surgery without fluid correction" },
      { label: "E", text: "Atropine medical therapy only" },
    ],
    correct_answer: "B",
    explanation: "**Hypertrophic Pyloric Stenosis (HPS)** — 2-12 weeks of age, more common in firstborn males. Etiology multifactorial — genetic + environmental (macrolides in infancy assoc), idiopathic muscle hypertrophy. **Classic presentation**: non-bilious projectile vomiting + visible peristalsis + palpable 'olive' RUQ + dehydration + failure to thrive. **Lab signature**: hypochloremic hypokalemic metabolic alkalosis (loss of HCl from vomiting; renal compensation by H+ retention worsens alkalosis; paradoxical aciduria when severe). **Imaging**: US gold standard — muscle thickness ≥ 4 mm, length ≥ 16 mm, target/donut sign, elongated channel **Management critical principle**: PYLORIC STENOSIS IS NOT A SURGICAL EMERGENCY — IT IS A MEDICAL EMERGENCY OF FLUID + ELECTROLYTE CORRECTION FIRST. - Anesthesia + surgery in alkalotic patient = postop apnea (CNS depression from alkalosis + hypoventilation compensation) - Correct: Cl > 100, HCO3 < 30, K > 3.5, normal urine output - Usually 24-48 hours of IV resuscitation **Surgery**: Ramstedt pyloromyotomy — extramucosal splitting; laparoscopic = open in modern era for outcomes. Atropine medical therapy — historical, rarely used now. A ผิด — ห้ามผ่าตัดก่อน correct lab. C ผิด — IV ไม่ใช่ oral. D ผิดอย่างยิ่ง — anesthetic risk. E ผิด — surgery definitive.",
    difficulty: "easy",
    board_section: "clinical_decision",
    board_topic: "pediatrics",
    board_age_group: "infant",
    reference_source: "APSA Pediatric Surgery Handbook; Pandya S et al. Pediatr Surg Int; Aspelund G, Langer JC. Semin Pediatr Surg",
  },
  {
    scenario: "เด็กชายไทยอายุ 9 เดือน มาด้วยอาการร้องไห้เป็นพักๆ ทุก 15-30 นาที + อาเจียน 6 ชั่วโมง + ถ่ายเป็นเลือดสีน้ำตาลแดง currant jelly stool 2 ครั้ง\n\nExam: lethargic between crying spells, palpable sausage-shaped mass RUQ, dance's sign (empty RLQ)\nVS: BP 80/50, HR 144, RR 30, Temp 37.6°C\n\nUS abdomen: target sign / pseudokidney sign at ileocolic region — intussusception confirmed; no signs of perforation",
    choices: [
      { label: "A", text: "Emergency laparotomy" },
      { label: "B", text: "**Ileocolic intussusception in pediatric patient — air enema reduction first-line if stable**: (1) **Resuscitation** + IV fluid + NG decompression + surgical consultation on standby; (2) **Air (pneumatic) enema reduction** under fluoroscopy — preferred over hydrostatic (barium/saline) due to better visualization, less mess if perforation, equally effective; success rate 80-90% (lower if symptoms > 24h, small bowel only); contraindications: peritonitis, perforation, hemodynamic instability; (3) **Hydrostatic enema** alternative (US-guided saline) — also effective, no radiation; (4) **Confirm reduction** — air through ileocecal valve into ileum + clinical improvement; observe 24h for recurrence (5-10%); (5) **Surgery** indicated for: failed enema reduction, peritonitis, perforation, pathological lead point (Meckel's, polyp, lymphoma — older child > 5 yr suspect lead point), recurrence > 3 times → laparoscopic / open reduction + resection if non-viable / lead point; (6) **Postop care + follow-up**",
      },
      { label: "C", text: "Observation 24 hr without intervention" },
      { label: "D", text: "Oral contrast study only" },
      { label: "E", text: "Discharge home with follow-up" },
    ],
    correct_answer: "B",
    explanation: "**Intussusception** — invagination of bowel into distal segment. Most common < 2 years, peak 5-9 months. Ileocolic most common. **Etiology**: idiopathic (peak age 3 mo - 3 yr) — viral-induced lymphoid hyperplasia (Peyer's patches); rotavirus vaccine RotaShield withdrawn 1999. **Pathological lead point** more likely > 5 yr — Meckel's, polyp, lymphoma, duplication, cyst. **Classic triad** (only 25%): crying spells + vomiting + currant jelly stool **Dance sign**: empty RLQ + sausage RUQ. **US** investigation of choice (target/donut, pseudokidney). **Reduction**: - **Air enema** preferred (pneumatic) — fluoroscopy-guided air insufflation; 80-90% success; perforation risk 0.4-2.5% - **Hydrostatic** (saline/water-soluble contrast under US, OR barium under fluoroscopy) — alternative - Contraindications: peritonitis, free air, hemodynamic instability, prolonged symptoms with signs of ischemia **Surgery indications**: failed non-operative reduction, peritonitis, perforation, lead point, recurrence (3+). **Recurrence** ~5-10% — usually within 24h. A ผิด — first-line non-operative. C ผิด — delay = ischemia. D ผิด — therapeutic enema. E ผิดอย่างยิ่ง.",
    difficulty: "medium",
    board_section: "clinical_decision",
    board_topic: "pediatrics",
    board_age_group: "infant",
    reference_source: "APSA Pediatric Surgery Handbook; Applegate KE Pediatr Radiol; Marsicovetere P et al. Clin Colon Rectal Surg",
  },
  {
    scenario: "ทารกแรกเกิดอายุ 1 วัน term, มาด้วยอาเจียน bilious + ท้องอืดเล็กน้อย ผ่าน meconium ปกติ 12 ชั่วโมงแรก\n\nVS stable, abdomen non-distended, no peritonitis\nUpper GI series: 'corkscrew' appearance of duodenum + small bowel — concerning for malrotation with midgut volvulus",
    choices: [
      { label: "A", text: "Observation + NG decompression only" },
      { label: "B", text: "**Neonatal midgut volvulus with malrotation — SURGICAL EMERGENCY**: (1) **Immediate resuscitation**: NG decompression, IV fluid bolus, broad-spectrum antibiotic, type & crossmatch; (2) **EMERGENT laparotomy** (within hours) for **Ladd's procedure**: (a) detorsion (counterclockwise) of volvulus, (b) division of Ladd's bands (peritoneal bands compressing duodenum), (c) widening of mesenteric base, (d) appendectomy (because appendix ends up LUQ → future atypical presentation), (e) place small bowel right, colon left; (3) **Assess bowel viability** — non-viable bowel resection; massive necrosis → damage control + second look 24-48h; (4) **Postop**: ICU, NG, gradual enteral; (5) **Time-critical** — bowel ischemia within hours → short gut syndrome if extensive necrosis or death",
      },
      { label: "C", text: "Outpatient referral pediatric surgery" },
      { label: "D", text: "Contrast enema" },
      { label: "E", text: "Endoscopic correction" },
    ],
    correct_answer: "B",
    explanation: "**Midgut volvulus with malrotation** — true surgical emergency in newborn. Embryologic basis: incomplete rotation of midgut (270° CCW) + fixation → narrow mesenteric base around SMA → volvulus risk. **Presentation**: bilious vomiting in newborn = malrotation with volvulus until proven otherwise → emergent workup. **Classic age**: 50% within 1 month, 75% within 1 year, can occur any age. **Diagnosis**: - **Upper GI series gold standard**: duodenojejunal junction (DJJ) right of midline / inferior to pylorus = malrotation; 'corkscrew' duodenum + jejunum = volvulus - US — SMA/SMV relationship reversal supportive - X-ray: limited, may show double bubble; some atypical **Time = bowel**: every hour of volvulus → more ischemia → catastrophic short gut syndrome (massive resection → lifelong TPN) **Ladd's procedure**: 1. Counterclockwise detorsion 2. Lyse Ladd's bands 3. Widen mesentery 4. Appendectomy (anatomic relocation) 5. Place bowel in non-rotation position **Appendectomy** because cecum + appendix moved → atypical pain location later. A ผิดอย่างยิ่ง — emergency. C D E ผิด.",
    difficulty: "easy",
    board_section: "clinical_decision",
    board_topic: "pediatrics",
    board_age_group: "neonate",
    reference_source: "APSA Pediatric Surgery Handbook; Strouse PJ Pediatr Radiol; Adams SD, Stanton MP Surg Childhood",
  },
  {
    scenario: "ชายไทยอายุ 65 ปี ผ่า colorectal cancer (sigmoid) ผ่านไป 6 ชั่วโมง post-op ผู้ป่วยมา ICU vitals stable แต่สังเกตเห็น oliguria 0.2 mL/kg/hr × 4 ชั่วโมง\n\nVS: BP 118/72, HR 96, RR 16, Temp 37.0°C\nLab: Hb 9.8 stable, Cr 1.6 (baseline 1.0), K 4.2, lactate 2.4\nFluid balance + 2 L positive intraop + 800 mL post-op\nUO 80 mL last 4 hr\nUS Bladder: 60 mL urine in catheter functional\n\nคำถาม: management of oliguria",
    choices: [
      { label: "A", text: "Large fluid bolus 2L NSS" },
      { label: "B", text: "**Post-operative oliguria — systematic evaluation + fluid challenge**: (1) **Differential**: pre-renal (hypovolemia, hypotension, anemia, low cardiac output), renal (ATN from hypotension, sepsis, contrast, drugs, transfusion), post-renal (bladder/ureter obstruction, kink, catheter); (2) **Assess volume status**: dynamic measures preferred — passive leg raise, pulse pressure variation, SVV (if ventilated), bedside US (IVC, lung B-lines), urine sodium / osmolality / FENa < 1% = pre-renal; (3) **Confirm Foley patency** — bladder scan done (catheter functional), rule out kink/blockage; (4) **Modest fluid challenge** 250-500 mL crystalloid + reassess UO/HD parameters — avoid large bolus that worsens edema (third spacing, prolonged ileus); (5) **Optimize**: correct anemia (transfuse if Hb < 7 standard, < 8 cardiac), maintain MAP > 65, treat pain, check medications (NSAIDs, nephrotoxic); (6) **Goal-directed therapy** ERAS-aligned — avoid liberal fluid (causes worse outcomes per ERAS evidence + Shin CH NEJM 2018); restrictive moderate strategy; (7) **Persistent oliguria** → nephrology consult, consider AKI workup, renal US, urine studies; (8) **Monitor Cr trend**",
      },
      { label: "C", text: "Furosemide IV bolus 80 mg" },
      { label: "D", text: "Renal replacement therapy immediately" },
      { label: "E", text: "Stop all fluids" },
    ],
    correct_answer: "B",
    explanation: "**Postoperative oliguria** — UO < 0.5 mL/kg/hr × > 6h (KDIGO AKI Stage 1 criterion). Don't reflex bolus. Modern ERAS + perioperative fluid management has shifted away from liberal fluids toward goal-directed + restrictive. **Differential**: 1. **Pre-renal**: hypovolemia (intraop loss, third space), low cardiac output, vasodilation (sepsis, anesthetic) 2. **Renal (intrinsic)**: ATN from prolonged hypotension/hypovolemia, drug-induced (NSAID, contrast, aminoglycoside), interstitial nephritis (antibiotics), rhabdomyolysis 3. **Post-renal**: catheter obstruction (kink, clot), bladder outlet, ureteral injury intraop (esp pelvic/colorectal — 0.5-1%) **Assessment**: - Check Foley patency, bladder scan - Vital signs trend - Fluid balance, weight - Lab: Cr, BUN/Cr ratio, electrolytes - Urine: Na, osmolality, FENa - Hemodynamics: dynamic measures preferred over CVP (CVP poorly predicts fluid responsiveness) - Bedside US: IVC, lung B-lines, cardiac function **Modern goal-directed**: small fluid challenges with reassessment, avoid over-resuscitation. **Avoid loop diuretics** for pre-renal oliguria — worsens AKI. Use only after volume optimized + persistent fluid overload. **Avoid contrast** for imaging if possible in AKI. A ผิด — large bolus harmful. C ผิด — loop in pre-renal harmful. D ผิด — RRT for refractory severe AKI. E ผิด — need maintenance.",
    difficulty: "medium",
    board_section: "clinical_decision",
    board_topic: "renal_gu",
    board_age_group: "adult",
    reference_source: "KDIGO AKI Guidelines 2012; ERAS Society Guidelines for Colorectal Surgery; Shin CH et al. JAMA 2018; Myles PS et al. NEJM 2018 (RELIEF)",
  },
  {
    scenario: "ชายไทยอายุ 72 ปี post-op day 1 right hemicolectomy for cecal mass admit ICU มาขอ consultation ว่าผู้ป่วยมี atrial fibrillation new onset HR 140 BP 95/60\n\nVS: BP 96/58, HR 142 irregular, RR 22, SpO2 94% room air, Temp 37.8°C\nGen: dyspneic\nLab: Hb 9.6, K 3.4, Mg 1.6, troponin negative, TSH normal\n\nคำถาม: management",
    choices: [
      { label: "A", text: "Electrical cardioversion immediately" },
      { label: "B", text: "**Postoperative new-onset atrial fibrillation (POAF) with rapid ventricular response + borderline hemodynamics**: (1) **Identify + correct precipitants** — common: pain, hypoxia, electrolyte derangements (K, Mg), hypovolemia/overload, anemia, sepsis, MI, PE, withdrawal; replete K to 4-4.5, Mg to > 2; (2) **Rate vs rhythm control**: hemodynamically stable enough to attempt rate control first — **IV beta-blocker (metoprolol 5 mg q5 min × 3 doses)** OR **diltiazem 10-20 mg bolus then infusion** — caution in HFrEF (diltiazem CI); avoid amiodarone first in stable rate control (more pro-arrhythmic, hypotension); (3) **Hemodynamically unstable** (severe hypotension, ischemia, severe HF) → **synchronized DC cardioversion** 120-200 J biphasic + sedation; (4) **Rhythm control with amiodarone IV** consider if rate control inadequate or rhythm desired (150 mg load, then drip) — also good in critically ill; (5) **Anticoagulation**: CHA2DS2-VASc score in POAF — controversial; transient POAF may not warrant long-term AC but risk of stroke during episode + recurrence high; consult per guidelines + bleeding risk balance; postop bleeding risk weigh; (6) **Address underlying causes**, optimize hemodynamics; (7) Cardiology consult; (8) Outpatient follow-up — many POAF persistent or recurrent",
      },
      { label: "C", text: "Digoxin alone for rate control" },
      { label: "D", text: "Observation only" },
      { label: "E", text: "Warfarin start immediately" },
    ],
    correct_answer: "B",
    explanation: "**Postoperative Atrial Fibrillation (POAF)** — incidence 10-30% post non-cardiac surgery, 30-50% post cardiac. Risk factors: age, HT, valvular disease, COPD, electrolyte disturbance, intraop volume shifts. **Management**: 1. **Identify precipitants**: pain, hypoxia, K/Mg deficiency, anemia, sepsis, fluid status, MI, PE 2. **Hemodynamic stability assessment**: - Stable: rate vs rhythm control - Unstable: synchronized cardioversion immediately 3. **Rate control**: - First-line: beta-blocker (metoprolol, esmolol) OR non-DHP CCB (diltiazem, verapamil) — caution in HFrEF - Digoxin: slow onset, less effective in stress states; adjunct only - Amiodarone: rhythm + rate; reasonable in critically ill, HF 4. **Rhythm control**: amiodarone IV; ibutilide; cardioversion 5. **Anticoagulation** in POAF: - CHA2DS2-VASc + HAS-BLED - Postop bleeding risk → individualized - Recent meta-analyses: POAF assoc with long-term AF recurrence + stroke risk — increasing recognition to anticoagulate persistent POAF beyond initial episode 6. **Long-term**: outpatient follow-up; many persist or recur **Special**: post-cardiac surgery — prophylactic beta-blocker, amiodarone proven to reduce POAF (PAPABEAR, others). A ผิด — stable enough for rate control trial. C ผิด — digoxin slow. D ผิด — RVR + hypotension. E ผิด — long-term decision later.",
    difficulty: "medium",
    board_section: "clinical_decision",
    board_topic: "cardiovascular",
    board_age_group: "adult",
    reference_source: "AHA/ACC/HRS Atrial Fibrillation Guidelines 2023; ESC Atrial Fibrillation 2020; Dobrev D et al. Nat Rev Cardiol 2019 (POAF)",
  },
  {
    scenario: "ชายไทยอายุ 40 ปี ทำงานก่อสร้าง post-op day 3 elective open inguinal hernia repair (mesh) มาด้วยอาการ shortness of breath ตื่นปวด chest, calf swelling left leg\n\nVS: BP 124/82, HR 116, RR 24, SpO2 89% room air, Temp 37.4°C\nLeg: left calf swollen 3 cm > right + tender + Homan's positive\nChest: clear, mild tachypnea\n\nLab: Hb 13.8, D-dimer 4,200 (elevated)\nCT pulmonary angiography: bilateral segmental PE; right ventricle:left ventricle ratio 0.9 (normal)\nUS Doppler legs: extensive DVT left femoropopliteal\nWell's score for PE high, Hestia low risk (no shock, no RV strain)",
    choices: [
      { label: "A", text: "Observation + bed rest" },
      { label: "B", text: "**Acute proximal DVT + segmental PE (low-risk by Hestia/sPESI, hemodynamically stable, normal RV function) → therapeutic anticoagulation**: (1) **Anticoagulation initiation** — choices: - **DOAC** (apixaban 10 mg BID × 7 days then 5 mg BID; OR rivaroxaban 15 mg BID × 21 days then 20 mg daily) — first-line per ACCP + CHEST; no overlap needed; - **LMWH** (enoxaparin 1 mg/kg q12h or 1.5 mg/kg daily) — for early use, particularly if uncertain bleeding risk, pregnancy, severe renal dz, cancer (LMWH historically preferred for cancer, now DOAC also acceptable per CLOT/Caravaggio); - **UFH IV** if hemodynamic concern, severe renal impairment, planned procedure; - Warfarin requires bridging with LMWH/UFH until INR 2-3 — rarely first choice now; (2) **Duration**: provoked (surgery-associated) → 3 months; unprovoked or persistent risk → consider extended; (3) **Postop bleeding risk** assessment — recent surgery 3 days = bleeding risk; balance vs PE/DVT mortality; usually proceed with anticoagulation with monitoring; (4) **Bleeding**: monitor wound, Hb, drains; consider IVC filter if true contraindication to anticoagulation (recent intracranial surgery, active bleeding) — retrievable filter; (5) **Outpatient management** acceptable for low-risk PE per HoT-PE / others — if reliable patient + outpatient anticoagulation feasible; (6) **No thrombolytics** for low-risk PE (only massive/hemodynamic instability or selected submassive with RV dysfunction)",
      },
      { label: "C", text: "Surgical thrombectomy" },
      { label: "D", text: "Systemic thrombolytics for all PE" },
      { label: "E", text: "Aspirin only" },
    ],
    correct_answer: "B",
    explanation: "**VTE management** — anticoagulation cornerstone. **Risk stratification of PE** (PESI / sPESI / Hestia): - Low risk: stable, no RV dysfunction, no biomarker elevation, no comorbidities — outpatient OR short observation - Intermediate-low: RV dysfunction OR biomarker elevation alone - Intermediate-high: BOTH RV dysfunction AND biomarker elevation - High (massive) PE: shock/hypotension SBP < 90 → thrombolytics, embolectomy, ECMO **Anticoagulation choice**: - **DOAC** first-line for most (CHEST 2021): apixaban, rivaroxaban (initial loading); dabigatran, edoxaban (require initial parenteral) - **LMWH** — pregnancy, cancer (alternative to DOAC), severe renal dz - **UFH** — hemodynamic instability, procedure planned, severe renal - **VKA** — historical, mechanical valves, antiphospholipid syndrome (recent evidence) **Duration**: - Provoked (surgery, immobilization): 3 months - Unprovoked: 3 months minimum; consider extended (D-dimer, sex, residual thrombus) - Active cancer: indefinite while active - Recurrent unprovoked: indefinite **Thrombolytics**: only for high-risk (massive) PE OR selected intermediate-high with deterioration. **IVC filter**: only if true contraindication to anticoagulation; retrievable preferred; not for prophylaxis. **Postop VTE** — provoked but high recurrence risk if cancer-associated; weigh bleeding. A ผิด — ต้อง anticoagulate. C ผิด — selected only. D ผิด — low-risk PE no thrombolytics. E ผิด — aspirin ไม่พอ.",
    difficulty: "medium",
    board_section: "clinical_decision",
    board_topic: "cardiovascular",
    board_age_group: "adult",
    reference_source: "CHEST Guidelines on Antithrombotic Therapy 2021; ESC Pulmonary Embolism 2019; Kearon C et al. CHEST 2016; Stevens SM et al. CHEST 2021",
  },
];
