// Algorithm/Flowchart data-driven structure
// Each algorithm = list of decision/action steps. Some have branches.
// step: { id, kind:'check'|'action'|'goto'|'call', text, detail?, tone?, yesNextId?, noNextId?, nextId? }

export const algorithms = [
  {
    id: 'cpr',
    title: 'CPR ผู้ใหญ่ (Hands-only)',
    icon: 'Heart',
    color: '#DC2626',
    summary: 'การช่วยฟื้นคืนชีพแบบกดหน้าอกอย่างเดียว',
    steps: [
      { id: 's1', kind: 'check', text: 'ปลอดภัยพอที่จะเข้าใกล้หรือไม่?',
        yesNextId: 's2', noNextId: 'stop-danger' },
      { id: 'stop-danger', kind: 'action', tone: 'danger',
        text: 'ห้ามเข้าใกล้ — โทร 1669 จากที่ปลอดภัย', terminal: true },
      { id: 's2', kind: 'check', text: 'ตอบสนองเมื่อเรียก/เขย่าไหล่?',
        yesNextId: 'awake', noNextId: 's3' },
      { id: 'awake', kind: 'action', text: 'ดูแลให้อยู่ในท่าที่สบาย — สังเกตอาการ ถ้าผิดปกติโทร 1669', terminal: true },
      { id: 's3', kind: 'call', tone: 'danger', text: 'โทร 1669 และขอเครื่อง AED ทันที', nextId: 's4' },
      { id: 's4', kind: 'check', text: 'หายใจปกติหรือไม่ (10 วินาที)?',
        yesNextId: 'recovery', noNextId: 's5' },
      { id: 'recovery', kind: 'action', text: 'จัดท่าตะแคง (Recovery position) เฝ้าสังเกต', terminal: true },
      { id: 's5', kind: 'action', text: 'กดหน้าอกกลางอก ลึก 5–6 ซม. 100–120 ครั้ง/นาที', nextId: 's6' },
      { id: 's6', kind: 'check', text: 'AED มาถึงแล้วหรือไม่?',
        yesNextId: 'aed', noNextId: 's5' },
      { id: 'aed', kind: 'goto', text: 'ไปที่ flowchart การใช้ AED', targetId: 'aed', terminal: true },
    ],
  },
  {
    id: 'aed',
    title: 'การใช้ AED',
    icon: 'Zap',
    color: '#2563EB',
    summary: 'เครื่องกระตุกหัวใจอัตโนมัติ',
    steps: [
      { id: 's1', kind: 'action', text: 'เปิดเครื่อง AED — ปฏิบัติตามเสียง', nextId: 's2' },
      { id: 's2', kind: 'action', text: 'ติดแผ่นกับหน้าอกผู้ป่วยตามภาพ', nextId: 's3' },
      { id: 's3', kind: 'action', tone: 'warning', text: 'ทุกคนถอย — ปล่อยให้เครื่องวิเคราะห์', nextId: 's4' },
      { id: 's4', kind: 'check', text: 'เครื่องสั่งให้ช็อกหรือไม่?',
        yesNextId: 's5', noNextId: 's6' },
      { id: 's5', kind: 'action', tone: 'danger', text: 'ตะโกน "ทุกคนถอย" → กดปุ่มช็อก', nextId: 's6' },
      { id: 's6', kind: 'action', text: 'ทำ CPR ต่อ 2 นาที — เครื่องจะวิเคราะห์ซ้ำเอง', terminal: true },
    ],
  },
  {
    id: 'choking',
    title: 'สำลัก (Choking)',
    icon: 'AlertCircle',
    color: '#D97706',
    summary: 'อุดกั้นทางเดินหายใจจากสิ่งแปลกปลอม',
    steps: [
      { id: 's1', kind: 'check', text: 'ผู้ป่วยไอออกได้ดีหรือพูดได้หรือไม่?',
        yesNextId: 'cough', noNextId: 's2' },
      { id: 'cough', kind: 'action', text: 'ให้กำลังใจให้ไอต่อ — เฝ้าใกล้ ๆ ห้ามตบหลัง', terminal: true },
      { id: 's2', kind: 'check', text: 'ผู้ป่วยอายุ 1 ปีขึ้นไปหรือไม่?',
        yesNextId: 's3', noNextId: 'infant' },
      { id: 'infant', kind: 'action', tone: 'warning',
        text: 'เด็กเล็ก: นอนคว่ำบนแขน ตบหลัง 5 ครั้ง สลับนอนหงายกดอก 5 ครั้ง', terminal: true },
      { id: 's3', kind: 'action', text: 'ตบกลางหลัง 5 ครั้ง', nextId: 's4' },
      { id: 's4', kind: 'check', text: 'หลุดออกหรือยัง?',
        yesNextId: 'done', noNextId: 's5' },
      { id: 's5', kind: 'action', text: 'รัดท้อง (Heimlich) 5 ครั้ง', nextId: 's6' },
      { id: 's6', kind: 'check', text: 'ผู้ป่วยหมดสติหรือไม่?',
        yesNextId: 'cpr', noNextId: 's3' },
      { id: 'cpr', kind: 'goto', text: 'โทร 1669 และเริ่ม CPR', targetId: 'cpr', terminal: true },
      { id: 'done', kind: 'action', text: 'เฝ้าสังเกต ถ้ามีอาการผิดปกติพาไป รพ.', terminal: true },
    ],
  },
  {
    id: 'bleeding',
    title: 'ห้ามเลือด',
    icon: 'Droplet',
    color: '#DC2626',
    summary: 'จัดการบาดแผลและเลือดออก',
    steps: [
      { id: 's1', kind: 'action', text: 'ใส่ถุงมือ/ถุงพลาสติกป้องกันตัวเอง', nextId: 's2' },
      { id: 's2', kind: 'action', text: 'กดแผลตรง ๆ ด้วยผ้าสะอาด', nextId: 's3' },
      { id: 's3', kind: 'action', text: 'ยกอวัยวะให้สูงกว่าหัวใจ ถ้าทำได้', nextId: 's4' },
      { id: 's4', kind: 'check', text: 'เลือดหยุดภายใน 10 นาทีหรือไม่?',
        yesNextId: 'done', noNextId: 'call' },
      { id: 'call', kind: 'call', tone: 'danger', text: 'โทร 1669 — กดต่อจนรถพยาบาลถึง', terminal: true },
      { id: 'done', kind: 'action', text: 'พันแผลให้แน่นพอ — เฝ้าสังเกตอาการ', terminal: true },
    ],
  },
  {
    id: 'burns',
    title: 'แผลไหม้',
    icon: 'Flame',
    color: '#EA580C',
    summary: 'น้ำร้อนลวก ไฟไหม้ เคมี',
    steps: [
      { id: 's1', kind: 'action', text: 'ย้ายผู้ป่วยออกจากแหล่งความร้อน', nextId: 's2' },
      { id: 's2', kind: 'action', text: 'ราดน้ำสะอาดอุณหภูมิห้องไหลผ่าน 15–20 นาที', nextId: 's3' },
      { id: 's3', kind: 'action', tone: 'danger',
        text: 'อย่าใส่ยาสีฟัน น้ำปลา ครีม น้ำมัน หรือน้ำแข็งโดยตรง', nextId: 's4' },
      { id: 's4', kind: 'check',
        text: 'แผลใหญ่กว่าฝ่ามือ / ไหม้ที่ใบหน้า มือ เท้า อวัยวะเพศ / มีตุ่มพอง?',
        yesNextId: 'call', noNextId: 'done' },
      { id: 'call', kind: 'call', tone: 'danger', text: 'พาไป รพ. หรือโทร 1669', terminal: true },
      { id: 'done', kind: 'action', text: 'พันด้วยผ้าสะอาด — สังเกตอาการ 24 ชม.', terminal: true },
    ],
  },
  {
    id: 'fracture',
    title: 'กระดูกหัก',
    icon: 'Bone',
    color: '#7C3AED',
    summary: 'ดามและจัดท่าก่อนนำส่ง',
    steps: [
      { id: 's1', kind: 'action', tone: 'warning', text: 'ห้ามดึงให้กระดูกเข้าที่', nextId: 's2' },
      { id: 's2', kind: 'check', text: 'มีกระดูกโผล่ออกมาจากผิวหนัง?',
        yesNextId: 'open', noNextId: 's3' },
      { id: 'open', kind: 'action', tone: 'danger',
        text: 'ปิดแผลด้วยผ้าสะอาด ห้ามดันกลับ → โทร 1669', terminal: true },
      { id: 's3', kind: 'action', text: 'ดามด้วยอุปกรณ์แข็ง (กระดาน หนังสือพิมพ์ม้วน) ยาวคร่อมข้อทั้งสองข้าง', nextId: 's4' },
      { id: 's4', kind: 'action', text: 'พันด้วยผ้าให้แน่น แต่ไม่รัดจนเลือดไม่เดิน', nextId: 's5' },
      { id: 's5', kind: 'action', text: 'นำส่ง รพ.', terminal: true },
    ],
  },
  {
    id: 'fainting',
    title: 'เป็นลม/หมดสติชั่วคราว',
    icon: 'User',
    color: '#0EA5E9',
    summary: 'จัดท่านอนและประเมินอาการ',
    steps: [
      { id: 's1', kind: 'action', text: 'จัดให้นอนหงาย ยกขาสูง 30 ซม.', nextId: 's2' },
      { id: 's2', kind: 'action', text: 'คลายเสื้อผ้าที่รัดคอ/เอว', nextId: 's3' },
      { id: 's3', kind: 'check', text: 'รู้สึกตัวภายใน 1 นาทีหรือไม่?',
        yesNextId: 'wake', noNextId: 'call' },
      { id: 'wake', kind: 'action', text: 'ให้นอนพักต่อ 5–10 นาที — ดื่มน้ำหวานเล็กน้อย', terminal: true },
      { id: 'call', kind: 'goto', text: 'โทร 1669 และเริ่มประเมินตาม flowchart CPR', targetId: 'cpr', terminal: true },
    ],
  },
  {
    id: 'seizure',
    title: 'ชัก',
    icon: 'Activity',
    color: '#7C3AED',
    summary: 'ระหว่างชักและหลังชัก',
    steps: [
      { id: 's1', kind: 'action', text: 'เคลียร์ของแข็งรอบตัว รองหัวด้วยของนุ่ม', nextId: 's2' },
      { id: 's2', kind: 'action', tone: 'danger', text: 'ห้ามใส่อะไรในปาก ห้ามจับกดให้หยุดดิ้น', nextId: 's3' },
      { id: 's3', kind: 'action', text: 'จับเวลาว่าชักนานเท่าไร', nextId: 's4' },
      { id: 's4', kind: 'check', text: 'ชักนานเกิน 5 นาที หรือชักซ้ำ?',
        yesNextId: 'call', noNextId: 's5' },
      { id: 'call', kind: 'call', tone: 'danger', text: 'โทร 1669 ทันที', terminal: true },
      { id: 's5', kind: 'action', text: 'เมื่อหยุดชัก จัดท่าตะแคง (Recovery position)', terminal: true },
    ],
  },
  {
    id: 'drowning',
    title: 'จมน้ำ',
    icon: 'Wind',
    color: '#0EA5E9',
    summary: 'การช่วยเหลือผู้จมน้ำ',
    steps: [
      { id: 's1', kind: 'action', tone: 'warning',
        text: 'อย่ากระโดดลงไป — ใช้หลัก "ตะโกน-โยน-ยื่น"', nextId: 's2' },
      { id: 's2', kind: 'action', text: 'ตะโกนเรียกความช่วยเหลือ + โยนวัตถุลอย + ยื่นไม้/ผ้า', nextId: 's3' },
      { id: 's3', kind: 'check', text: 'นำขึ้นมาแล้ว — หายใจหรือไม่?',
        yesNextId: 'recovery', noNextId: 'cpr' },
      { id: 'recovery', kind: 'action', text: 'จัดท่าตะแคง รักษาความอบอุ่น พาไป รพ.', terminal: true },
      { id: 'cpr', kind: 'goto', text: 'เริ่ม CPR ทันที — ห้ามล้วงน้ำออก', targetId: 'cpr', terminal: true },
    ],
  },
  {
    id: 'snake-bite',
    title: 'งูกัด',
    icon: 'Shield',
    color: '#15803D',
    summary: 'การปฐมพยาบาลผู้ถูกงูกัด',
    steps: [
      { id: 's1', kind: 'action', text: 'ให้ผู้ป่วยอยู่นิ่ง ๆ ระดับแผลต่ำกว่าหัวใจ', nextId: 's2' },
      { id: 's2', kind: 'action', tone: 'danger',
        text: 'ห้ามดูดพิษ ห้ามรัด ห้ามกรีดแผล ห้ามประคบน้ำแข็ง', nextId: 's3' },
      { id: 's3', kind: 'action', text: 'ถอดแหวน/นาฬิกาออก เพราะอาจบวม', nextId: 's4' },
      { id: 's4', kind: 'action', text: 'จดจำลักษณะงู (สี ลาย) ถ้าทำได้ — ไม่ต้องไล่จับ', nextId: 's5' },
      { id: 's5', kind: 'call', tone: 'danger', text: 'โทร 1669 ทันที — นำส่ง รพ. เร็วที่สุด', terminal: true },
    ],
  },
  {
    id: 'heat-stroke',
    title: 'ลมแดด',
    icon: 'Sun',
    color: '#D97706',
    summary: 'Heat Stroke — ภาวะฉุกเฉิน',
    steps: [
      { id: 's1', kind: 'check',
        text: 'ตัวร้อน (>40°C) ผิวแดงแห้ง สับสน หรือหมดสติ?',
        yesNextId: 's2', noNextId: 'mild' },
      { id: 'mild', kind: 'action',
        text: 'อาจเป็นเพลียแดด — ย้ายเข้าที่ร่ม ดื่มน้ำเกลือแร่ พัก 30 นาที', terminal: true },
      { id: 's2', kind: 'call', tone: 'danger', text: 'โทร 1669 ทันที', nextId: 's3' },
      { id: 's3', kind: 'action', text: 'ย้ายเข้าที่ร่มเย็น คลายเสื้อ', nextId: 's4' },
      { id: 's4', kind: 'action',
        text: 'วางผ้าเย็นที่คอ รักแร้ ขาหนีบ — พ่นละอองน้ำเข้าตัว', nextId: 's5' },
      { id: 's5', kind: 'action', text: 'พัดให้ระเหย — เฝ้าจนรถพยาบาลถึง', terminal: true },
    ],
  },
  {
    id: 'anaphylaxis',
    title: 'แพ้รุนแรง / EpiPen',
    icon: 'AlertTriangle',
    color: '#DC2626',
    summary: 'Anaphylaxis — นาทีชีวิต',
    steps: [
      { id: 's1', kind: 'check',
        text: 'หายใจไม่ออก หน้าบวม ปากบวม ลมพิษทั่วตัว หรือช็อก?',
        yesNextId: 's2', noNextId: 'mild' },
      { id: 'mild', kind: 'action',
        text: 'อาการเบา — สังเกตอาการต่อ 30 นาที ให้กินยาแก้แพ้ถ้ามี', terminal: true },
      { id: 's2', kind: 'call', tone: 'danger', text: 'โทร 1669 ทันที', nextId: 's3' },
      { id: 's3', kind: 'check', text: 'ผู้ประสบภัยมี EpiPen ติดตัวหรือไม่?',
        yesNextId: 's4', noNextId: 'wait' },
      { id: 'wait', kind: 'action', tone: 'warning',
        text: 'ไม่มียา → จัดท่านอนราบ ยกขาสูง รอทีมกู้ชีพ', nextId: 'cpr-check' },
      { id: 's4', kind: 'action',
        text: 'ถอดปลอกหัว EpiPen — กำตัวปากกาแน่น (ห้ามจับด้านปลาย)', nextId: 's5' },
      { id: 's5', kind: 'action', tone: 'danger',
        text: 'แทงปลายปากกาเข้ากล้ามเนื้อต้นขา ทะลุเสื้อผ้าได้ ค้าง 10 วินาที', nextId: 's6' },
      { id: 's6', kind: 'action', text: 'นวดบริเวณที่ฉีด 10 วินาที — จดเวลาที่ฉีด', nextId: 'cpr-check' },
      { id: 'cpr-check', kind: 'check', text: 'ปลุกไม่ตื่น/ไม่หายใจ?',
        yesNextId: 'cpr', noNextId: 'done' },
      { id: 'cpr', kind: 'goto', text: 'เริ่ม CPR ทันที', targetId: 'cpr', terminal: true },
      { id: 'done', kind: 'action', text: 'เฝ้าสังเกตจนทีมกู้ชีพถึง', terminal: true },
    ],
  },
  {
    id: 'chest-pain',
    title: 'เจ็บหน้าอก / Heart Attack',
    icon: 'Heart',
    color: '#DC2626',
    summary: 'หัวใจขาดเลือดเฉียบพลัน',
    steps: [
      { id: 's1', kind: 'check',
        text: 'แน่นหน้าอกคล้ายโดนทับ ร้าวไปกราม/แขน/หลัง?',
        yesNextId: 's2', noNextId: 'observe' },
      { id: 'observe', kind: 'action',
        text: 'อาจเป็นอาการอื่น — สังเกตอาการ ถ้าแย่ลงโทร 1669', terminal: true },
      { id: 's2', kind: 'action', text: 'ให้ผู้ประสบภัยนั่งพัก สงบจิตใจ', nextId: 's3' },
      { id: 's3', kind: 'call', tone: 'danger', text: 'โทร 1669 + เตรียม AED', nextId: 's4' },
      { id: 's4', kind: 'check',
        text: 'ไม่แพ้ ASA + ไม่เป็นโรคกระเพาะ + ไม่เป็นโรคเลือด?',
        yesNextId: 'asa', noNextId: 'no-asa' },
      { id: 'asa', kind: 'action',
        text: 'ให้ Aspirin เคี้ยว 1 เม็ดทันที', nextId: 'cpr-check' },
      { id: 'no-asa', kind: 'action', tone: 'warning',
        text: 'ห้ามให้ Aspirin — รอทีมกู้ชีพ', nextId: 'cpr-check' },
      { id: 'cpr-check', kind: 'check', text: 'ปลุกไม่ตื่น/ไม่หายใจ?',
        yesNextId: 'cpr', noNextId: 'done' },
      { id: 'cpr', kind: 'goto', text: 'เริ่ม CPR + ติด AED', targetId: 'cpr', terminal: true },
      { id: 'done', kind: 'action', text: 'อยู่ข้างผู้ประสบภัย เฝ้าสังเกตจนรถพยาบาลถึง', terminal: true },
    ],
  },
  {
    id: 'stroke',
    title: 'อัมพาต (Stroke)',
    icon: 'Brain',
    color: '#7C3AED',
    summary: 'ชั่วโมงทอง — จดเวลาเริ่มอาการ',
    steps: [
      { id: 's1', kind: 'check',
        text: 'F.A.S.T — หน้าเบี้ยว / แขนข้างใดข้างหนึ่งอ่อนแรง / พูดไม่ชัด?',
        yesNextId: 's2', noNextId: 'observe' },
      { id: 'observe', kind: 'action',
        text: 'ไม่ใช่อัมพาตชัดเจน — สังเกตอาการ ถ้าผิดปกติโทร 1669', terminal: true },
      { id: 's2', kind: 'action', tone: 'danger',
        text: 'จด/จำเวลาที่เริ่มมีอาการ — สำคัญที่สุดสำหรับการรักษา', nextId: 's3' },
      { id: 's3', kind: 'call', tone: 'danger', text: 'โทร 1669 + เตรียม AED', nextId: 's4' },
      { id: 's4', kind: 'action', text: 'ให้นอนพักท่าสบาย ห้ามให้กิน/ดื่ม', nextId: 'cpr-check' },
      { id: 'cpr-check', kind: 'check', text: 'ปลุกไม่ตื่น/ไม่หายใจ?',
        yesNextId: 'cpr', noNextId: 'done' },
      { id: 'cpr', kind: 'goto', text: 'เริ่ม CPR ทันที', targetId: 'cpr', terminal: true },
      { id: 'done', kind: 'action', text: 'เฝ้าจนรถพยาบาลถึง — แจ้งเวลาที่จดไว้', terminal: true },
    ],
  },
  {
    id: 'hypoglycemia',
    title: 'น้ำตาลตก',
    icon: 'Candy',
    color: '#F59E0B',
    summary: 'ผู้ป่วยเบาหวานที่สับสน/เหงื่อแตก',
    steps: [
      { id: 's1', kind: 'check',
        text: 'ผู้ป่วยเบาหวาน — สับสน เหงื่อแตก หิวจัด หรือชัก?',
        yesNextId: 's2', noNextId: 'other' },
      { id: 'other', kind: 'action',
        text: 'อาจเป็นภาวะอื่น — ประเมินตามอาการ', terminal: true },
      { id: 's2', kind: 'check', text: 'รู้สึกตัวดี กลืน/นั่งได้?',
        yesNextId: 'feed', noNextId: 'unconscious' },
      { id: 'feed', kind: 'action',
        text: 'ให้น้ำผลไม้/นม/น้ำตาล/น้ำผึ้ง ทันที (ห้ามให้ช็อกโกแลต/ไดเอท)', nextId: 's3' },
      { id: 'unconscious', kind: 'action', tone: 'danger',
        text: 'ห้ามใส่อะไรในปาก (จะอุดทางเดินหายใจ)', nextId: 's3' },
      { id: 's3', kind: 'call', tone: 'danger', text: 'โทร 1669', nextId: 'cpr-check' },
      { id: 'cpr-check', kind: 'check', text: 'ปลุกไม่ตื่น/ไม่หายใจ?',
        yesNextId: 'cpr', noNextId: 'done' },
      { id: 'cpr', kind: 'goto', text: 'เริ่ม CPR ทันที', targetId: 'cpr', terminal: true },
      { id: 'done', kind: 'action', text: 'เฝ้าจนรถพยาบาลถึง', terminal: true },
    ],
  },
  {
    id: 'spine',
    title: 'บาดเจ็บคอ/หลัง',
    icon: 'Bone',
    color: '#0EA5E9',
    summary: 'ระวังไขสันหลัง — ห้ามขยับ',
    steps: [
      { id: 's1', kind: 'check',
        text: 'ตกที่สูง/รถชน/กระแทกศีรษะ + เจ็บคอ/หลัง หรือชา/อ่อนแรง?',
        yesNextId: 's2', noNextId: 'observe' },
      { id: 'observe', kind: 'action',
        text: 'สงสัยน้อย — สังเกตอาการ ถ้ามีอาการใหม่โทร 1669', terminal: true },
      { id: 's2', kind: 'action', tone: 'danger',
        text: 'ห้ามขยับศีรษะ/คอ/หลัง — รักษาให้นิ่งที่สุด', nextId: 's3' },
      { id: 's3', kind: 'call', tone: 'danger', text: 'โทร 1669 — รอทีมกู้ชีพ', nextId: 's4' },
      { id: 's4', kind: 'check', text: 'อาเจียน/มีน้ำในปาก?',
        yesNextId: 'roll', noNextId: 'cpr-check' },
      { id: 'roll', kind: 'action', tone: 'warning',
        text: 'ค่อยๆ ตะแคงทั้งตัวพร้อมกัน (log roll) ให้คอ-หลังขยับน้อยที่สุด', nextId: 'cpr-check' },
      { id: 'cpr-check', kind: 'check', text: 'ปลุกไม่ตื่น/ไม่หายใจ?',
        yesNextId: 'cpr', noNextId: 'done' },
      { id: 'cpr', kind: 'goto', text: 'เริ่ม CPR (จำเป็นต้องขยับ — ป้องกันให้น้อยที่สุด)', targetId: 'cpr', terminal: true },
      { id: 'done', kind: 'action', text: 'เฝ้าสังเกตจนทีมกู้ชีพถึง', terminal: true },
    ],
  },
  {
    id: 'chemical',
    title: 'สารเคมีอันตราย',
    icon: 'Skull',
    color: '#7C3AED',
    summary: 'สูดดม/สัมผัสผิวหนัง/เข้าตา/กลืน',
    steps: [
      { id: 's1', kind: 'check', text: 'พื้นที่ปลอดภัยสำหรับผู้ช่วยหรือไม่?',
        yesNextId: 's2', noNextId: 'stay-out' },
      { id: 'stay-out', kind: 'action', tone: 'danger',
        text: 'ห้ามเข้าพื้นที่ — ให้ผู้ประสบภัยออกมาเอง / รอทีมที่มี PPE ครบ', terminal: true },
      { id: 's2', kind: 'action', text: 'ใส่ PPE ครบ (ถุงมือ แว่น หน้ากาก)', nextId: 's3' },
      { id: 's3', kind: 'call', tone: 'danger', text: 'โทร 1669 + เปิด MSDS', nextId: 's4' },
      { id: 's4', kind: 'check', text: 'สารเคมีเข้าทางใด?',
        yesNextId: 'skin', noNextId: 'skin' },
      { id: 'skin', kind: 'action',
        text: 'สัมผัสผิว/เข้าตา → ถอดเสื้อ/เครื่องประดับ → ล้างน้ำไหล 20+ นาที (กัดกร่อน 60 นาที)', nextId: 's5' },
      { id: 's5', kind: 'check', text: 'กลืนสารเคมี + รู้สึกตัวดี?',
        yesNextId: 'drink', noNextId: 'no-drink' },
      { id: 'drink', kind: 'action',
        text: 'ดื่มน้ำ 240-300 ซีซี — ห้ามทำให้อาเจียน', nextId: 'cpr-check' },
      { id: 'no-drink', kind: 'action', tone: 'warning',
        text: 'ไม่มีสติ → ห้ามให้สารใดทางปาก', nextId: 'cpr-check' },
      { id: 'cpr-check', kind: 'check', text: 'ปลุกไม่ตื่น/ไม่หายใจ?',
        yesNextId: 'cpr-mask', noNextId: 'done' },
      { id: 'cpr-mask', kind: 'action', tone: 'danger',
        text: 'CPR ด้วยหน้ากากช่วยหายใจเท่านั้น — ห้ามเป่าปาก', terminal: true },
      { id: 'done', kind: 'action', text: 'เก็บข้อมูลสารเคมีให้ทีมกู้ชีพ', terminal: true },
    ],
  },
]

export const algorithmsById = Object.fromEntries(algorithms.map(a => [a.id, a]))
