// Scenario / Simulation — decision-tree practice for laypersons
// ดัดแปลงจาก: คู่มือการปฐมพยาบาลเบื้องต้น ฉบับประชาชนทั่วไป โดย หมอเจี่ย (Jia1669.com)
//
// แต่ละฉากผูกกับบทเรียนผ่าน `lessonId` + `chapter` เพื่อให้ "ฝึก" ตรงกับ "บทเรียน"
// ครอบคลุมครบทั้ง 24 บทเรียน — หลายฉากต่อหัวข้อ เพื่อให้ได้ฝึกเยอะๆ
//
// shape: { id, chapter, lessonId, bonus?, title, summary, minutes, icon, color,
//          steps: [{ id, prompt, image?, choices: [{id, text, correct, feedback, nextStepId | 'end'}] }] }
// score: +1 per correct, max = number of decision steps (ผ่านเกณฑ์ 70%)
//
// bonus:true = ฉากเสริมที่สอนเทคนิคนอกคู่มือต้นฉบับ (เช่น เด็กสำลัก-ตบหลัง, จมน้ำ-ตะโกนโยนยื่น)
//   เนื้อหาถูกต้องตามหลักสากล แต่ไม่อยู่ในคู่มือ จึงทำเครื่องหมายไว้

const CH = { 1: '#16A34A', 2: '#DC2626', 3: '#D97706', 4: '#7C3AED' }

export const scenarios = [
  // ═══════════════ บทที่ 1 — ความรู้พื้นฐานการปฐมพยาบาล ═══════════════
  {
    id: 'duty-consent',
    chapter: 1, lessonId: 'duty',
    title: 'ขออนุญาตก่อนช่วย',
    summary: 'เพื่อนร่วมงานหกล้ม รู้สึกตัวดี คุณจะเข้าช่วยอย่างไรให้ถูก',
    minutes: 3, icon: 'Hand', color: CH[1],
    steps: [
      {
        id: 's1',
        prompt: 'เพื่อนร่วมงานหกล้ม เข่าถลอก นั่งกุมเข่าอยู่ รู้สึกตัวดี คุยได้ — สิ่งแรกที่ควรทำ?',
        choices: [
          { id: 'a', text: 'เข้าไปแตะดูแผลทันที', correct: false,
            feedback: 'ผู้ที่รู้สึกตัวดี ต้องขออนุญาตก่อนแตะตัวเสมอ', nextStepId: 's2' },
          { id: 'b', text: 'แนะนำตัวว่าเป็นอาสาปฐมพยาบาล แล้วถาม "ให้ช่วยไหม?"', correct: true,
            feedback: 'ถูกต้อง — แนะนำตัวและขออนุญาตก่อนแตะตัวผู้ที่รู้สึกตัวดี', nextStepId: 's2' },
          { id: 'c', text: 'ยืนดูเฉยๆ รอจนเขาร้องขอเอง', correct: false,
            feedback: 'เสนอความช่วยเหลือได้เลย เพียงแต่ต้องขออนุญาตก่อน', nextStepId: 's2' },
        ],
      },
      {
        id: 's2',
        prompt: 'เขาตอบ "ช่วยหน่อยครับ" — ขั้นต่อไป?',
        choices: [
          { id: 'a', text: 'เริ่มปฐมพยาบาลได้เลย', correct: true,
            feedback: 'ถูก — ตอบตกลงแล้วเริ่มช่วยได้', nextStepId: 's3' },
          { id: 'b', text: 'โทร 1669 ก่อนเสมอทุกกรณี', correct: false,
            feedback: 'แผลถลอกเล็กน้อยไม่จำเป็นต้องโทร 1669 — โทรเมื่อเป็นภาวะฉุกเฉิน', nextStepId: 's3' },
          { id: 'c', text: 'รอหัวหน้ามาตัดสินใจ', correct: false,
            feedback: 'ช่วยได้เลยเมื่อได้รับอนุญาต', nextStepId: 's3' },
        ],
      },
      {
        id: 's3',
        prompt: 'อีกมุมห้องมีคนนั่งซึม สับสน ตอบคำถามไม่ได้ — กับคนนี้คุณควร?',
        choices: [
          { id: 'a', text: 'ต้องให้เขาอนุญาตให้ได้ก่อนเท่านั้น', correct: false,
            feedback: 'ผู้ที่สับสน/ตอบไม่ได้ ให้เข้าช่วยได้ทันทีโดยไม่ต้องรอคำอนุญาต', nextStepId: 'end' },
          { id: 'b', text: 'เข้าช่วยได้ทันที (เพราะสับสน/ตอบไม่ได้) และโทร 1669', correct: true,
            feedback: 'ถูกต้อง — กรณีสับสนหรือตอบไม่ได้ เข้าช่วยได้ทันที', nextStepId: 'end' },
          { id: 'c', text: 'ปล่อยไว้เพราะยังไม่ได้ขออนุญาต', correct: false,
            feedback: 'ห้ามปล่อยไว้ — คนสับสน/ตอบไม่ได้ถือว่าเป็นเหตุให้ช่วยได้ทันที', nextStepId: 'end' },
        ],
      },
    ],
  },
  {
    id: 'safety-scene-ppe',
    chapter: 1, lessonId: 'safety',
    title: 'ประเมินความปลอดภัย + PPE',
    summary: 'เสียงล้มในห้องเก็บสารเคมีที่มีควัน คุณจะเข้าช่วยอย่างปลอดภัยอย่างไร',
    minutes: 3, icon: 'ShieldCheck', color: CH[1],
    steps: [
      {
        id: 's1',
        prompt: 'ได้ยินเสียงล้มในห้องเก็บสารเคมี เปิดประตูเจอควันฉุนและเพื่อนนอนอยู่ — ทำอะไรก่อน?',
        choices: [
          { id: 'a', text: 'วิ่งเข้าไปลากออกมาทันที', correct: false,
            feedback: '"ผู้ที่เจ็บป่วย/บาดเจ็บ ช่วยผู้อื่นไม่ได้" — ต้องประเมินความปลอดภัยก่อน', nextStepId: 's2' },
          { id: 'b', text: 'ไม่เข้าพื้นที่อันตราย เรียกให้เขาออกมาเอง/เรียกทีม แล้วโทร 1669', correct: true,
            feedback: 'ถูก — สถานการณ์ไม่ปลอดภัย ต้องหลบอันตรายและขอความช่วยเหลือก่อน', nextStepId: 's2' },
          { id: 'c', text: 'กลั้นหายใจแล้ววิ่งเข้าไป', correct: false,
            feedback: 'อันตราย — ควันพิษทำให้คุณหมดสติได้ จะกลายเป็นผู้ประสบภัยอีกคน', nextStepId: 's2' },
        ],
      },
      {
        id: 's2',
        prompt: 'พาออกมาที่ปลอดภัยแล้ว ก่อนสัมผัสตัวเพื่อปฐมพยาบาล ควร?',
        choices: [
          { id: 'a', text: 'ใส่ถุงมือ + แว่นตานิรภัย + หน้ากากอนามัย (PPE)', correct: true,
            feedback: 'ถูก — ใส่ PPE ทุกครั้งเพื่อกันสารคัดหลั่ง/เลือด', nextStepId: 's3' },
          { id: 'b', text: 'สัมผัสได้เลยเพราะรีบ', correct: false,
            feedback: 'เลือด/สารคัดหลั่งนำเชื้อโรคได้ — ต้องใส่ PPE ก่อน', nextStepId: 's3' },
          { id: 'c', text: 'ล้างมืออย่างเดียวพอ ไม่ต้อง PPE', correct: false,
            feedback: 'ล้างมือดี แต่ยังต้องใส่ถุงมือ/แว่น/หน้ากากด้วย', nextStepId: 's3' },
        ],
      },
      {
        id: 's3',
        prompt: 'ระหว่างช่วย เลือดของเขากระเด็นเข้าตาคุณ — ทำอย่างไร?',
        choices: [
          { id: 'a', text: 'เช็ดออกแล้วช่วยต่อ', correct: false,
            feedback: 'ไม่พอ — ต้องล้างตาด้วยน้ำมากๆ', nextStepId: 'end' },
          { id: 'b', text: 'ล้างตาด้วยน้ำสะอาดปริมาณมาก นานกว่า 15 นาที แล้วไปสถานพยาบาล', correct: true,
            feedback: 'ถูก — เลือดเข้าตา/ปาก/จมูก ล้างน้ำมากๆ >15 นาที แล้วส่งสถานพยาบาล', nextStepId: 'end' },
          { id: 'c', text: 'หยอดยาหยอดตาแล้วทำงานต่อ', correct: false,
            feedback: 'ต้องล้างน้ำออกให้มากที่สุดก่อน แล้วไปพบแพทย์', nextStepId: 'end' },
        ],
      },
    ],
  },
  {
    id: 'call-1669-alone',
    chapter: 1, lessonId: 'call-1669',
    title: 'อยู่คนเดียว พบคนหมดสติ',
    summary: 'ลำดับการขอความช่วยเหลือและโทร 1669 ที่ถูกต้อง',
    minutes: 3, icon: 'PhoneCall', color: CH[1],
    steps: [
      {
        id: 's1',
        prompt: 'อยู่คนเดียวในออฟฟิศตอนเย็น เพื่อนล้มหมดสติ — ลำดับแรกสุด?',
        choices: [
          { id: 'a', text: 'รีบ CPR เลย ค่อยโทรทีหลัง', correct: false,
            feedback: 'ตะโกนเรียกก่อน — ถ้าไม่มีใครค่อยโทร 1669 และหยิบ AED', nextStepId: 's2' },
          { id: 'b', text: 'ตะโกนขอความช่วยเหลือก่อน', correct: true,
            feedback: 'ถูก — ตะโกนเรียกคนช่วยเป็นอันดับแรก', nextStepId: 's2' },
          { id: 'c', text: 'ถ่ายคลิปขอความช่วยเหลือออนไลน์', correct: false,
            feedback: 'เสียเวลามาก — โทร 1669 ตรงๆ เร็วกว่า', nextStepId: 's2' },
        ],
      },
      {
        id: 's2',
        prompt: 'ไม่มีใครตอบรับ — ขั้นต่อไป?',
        choices: [
          { id: 'a', text: 'โทร 1669 แล้วหยิบกล่องปฐมพยาบาล + AED มาด้วย', correct: true,
            feedback: 'ถูก — โทร 1669 และหยิบกล่องปฐมพยาบาล + AED ก่อนกลับมาช่วย', nextStepId: 's3' },
          { id: 'b', text: 'นั่งรอจนมีคนเดินผ่าน', correct: false,
            feedback: 'รอไม่ได้ — ทุกวินาทีมีค่า โทร 1669 เลย', nextStepId: 's3' },
          { id: 'c', text: 'ขับรถพาไปโรงพยาบาลเอง', correct: false,
            feedback: 'รถกู้ชีพมี AED/ออกซิเจน + เริ่มรักษาระหว่างทางได้ — เร็วและปลอดภัยกว่า', nextStepId: 's3' },
        ],
      },
      {
        id: 's3',
        prompt: 'เจ้าหน้าที่ 1669 รับสายและถามรายละเอียด คุณ?',
        choices: [
          { id: 'a', text: 'รีบวางสายไปช่วยก่อน', correct: false,
            feedback: 'ห้ามรีบวางหู — 1669 ต้องการข้อมูลครบเพื่อไปถึงให้เร็วที่สุด', nextStepId: 'end' },
          { id: 'b', text: 'ตอบคำถามจนครบ และฟังคำแนะนำ CPR ทางสาย', correct: true,
            feedback: 'ถูก — 1669 บอกขั้นตอนปฐมพยาบาล/CPR ทางโทรศัพท์ได้ ควรทำตาม', nextStepId: 'end' },
          { id: 'c', text: 'บอกแค่ที่อยู่แล้ววางสาย', correct: false,
            feedback: 'ควรอยู่ในสายตอบคำถามจนครบ', nextStepId: 'end' },
        ],
      },
    ],
  },
  {
    id: 'mall-collapse',
    chapter: 1, lessonId: 'assess',
    title: 'ชายวัย 50 ล้มลงในห้าง',
    summary: 'พบชายอายุ 50 ปี ล้มลงหน้าร้านอาหารกะทันหัน ไม่ขยับ',
    minutes: 5,
    icon: 'AlertCircle',
    color: CH[1],
    steps: [
      {
        id: 's1',
        prompt: 'คุณเห็นชายล้มลงตรงทางเดินกลางห้าง คนเริ่มมุงดู คุณจะทำอะไรก่อน?',
        choices: [
          { id: 'a', text: 'รีบเขย่าให้ตื่น', correct: false,
            feedback: 'ก่อนเข้าไปต้องดูปลอดภัยก่อน — และยังไม่ได้เรียกความช่วยเหลือ', nextStepId: 's2' },
          { id: 'b', text: 'ดูรอบ ๆ ว่าปลอดภัย แล้วเรียกชื่อ-เขย่าไหล่เบา ๆ', correct: true,
            feedback: 'ถูกต้อง! หลัก Danger → Response', nextStepId: 's2' },
          { id: 'c', text: 'ถ่ายคลิปแล้วโพสต์ขอความช่วยเหลือออนไลน์', correct: false,
            feedback: 'เสียเวลามาก — โทร 1669 ตรง ๆ เร็วกว่าเยอะ', nextStepId: 's2' },
        ],
      },
      {
        id: 's2',
        prompt: 'เขย่าแล้วผู้ป่วยไม่ตอบสนอง ไม่หายใจ ขั้นต่อไป?',
        choices: [
          { id: 'a', text: 'รีบกดหน้าอกทันที', correct: false,
            feedback: 'ต้องเรียก 1669 และขอ AED ก่อน — แล้วค่อยเริ่ม CPR', nextStepId: 's3' },
          { id: 'b', text: 'ตะโกนสั่งคนรอบ ๆ ให้โทร 1669 และวิ่งหา AED', correct: true,
            feedback: 'ถูก! Designate คนช่วยชัดเจน เช่น "คุณเสื้อแดงโทร 1669, คุณเสื้อฟ้าวิ่งหา AED"', nextStepId: 's3' },
          { id: 'c', text: 'เป่าปาก 2 ครั้งก่อน', correct: false,
            feedback: 'สำหรับประชาชน ใช้ Hands-only CPR — ไม่ต้องเป่าปาก', nextStepId: 's3' },
        ],
      },
      {
        id: 's3',
        prompt: 'คุณเริ่ม CPR แล้ว 2 นาที AED มาถึง คุณควร?',
        choices: [
          { id: 'a', text: 'หยุดกดหน้าอก เปิด AED ติดแผ่นทันที', correct: true,
            feedback: 'ใช่ — หยุด CPR ชั่วคราว ติดแผ่นเร็วที่สุด', nextStepId: 's4' },
          { id: 'b', text: 'รอ CPR จบ 5 รอบก่อน', correct: false,
            feedback: 'AED เป็นการรักษาที่ effective ที่สุด — ติดทันทีที่ทำได้', nextStepId: 's4' },
          { id: 'c', text: 'ให้คนอื่นใช้ AED คุณยังกดต่อ', correct: false,
            feedback: 'การกดต่อขณะติดแผ่นทำให้แผ่นไม่ติดสนิท — หยุดสั้น ๆ เพื่อติด', nextStepId: 's4' },
        ],
      },
      {
        id: 's4',
        prompt: 'AED บอก "Shock advised" ขั้นต่อไป?',
        choices: [
          { id: 'a', text: 'กดปุ่มช็อกทันที', correct: false,
            feedback: 'ต้องเช็คว่าไม่มีใครแตะตัวผู้ป่วยก่อน — เสี่ยงโดนช็อกตามไปด้วย', nextStepId: 'end' },
          { id: 'b', text: 'ตะโกน "ทุกคนถอย" แล้วกดปุ่มช็อก', correct: true,
            feedback: 'ถูกต้อง — clear แล้วกด', nextStepId: 'end' },
          { id: 'c', text: 'รอเครื่องกดเอง', correct: false,
            feedback: 'AED รุ่นที่ใช้ในห้าง/สนามบิน ต้องกดปุ่มเอง', nextStepId: 'end' },
        ],
      },
    ],
  },
  {
    id: 'assess-recovery',
    chapter: 1, lessonId: 'assess',
    title: 'ปลุกไม่ตื่นแต่ยังหายใจ',
    summary: 'ตรวจการรู้สึกตัว การหายใจ และจัดท่า Recovery',
    minutes: 3, icon: 'Stethoscope', color: CH[1],
    steps: [
      {
        id: 's1',
        prompt: 'พบคนนอนอยู่ ตบบ่าเรียก "คุณๆ ตื่นๆ" ไม่ตอบสนอง — ขั้นต่อไป?',
        choices: [
          { id: 'a', text: 'ตรวจการหายใจ', correct: true,
            feedback: 'ถูก — ประเมินภาวะถึงชีวิตก่อน คือดูการหายใจ', nextStepId: 's2' },
          { id: 'b', text: 'จับลุกนั่งพิงกำแพง', correct: false,
            feedback: 'ยังไม่ควรขยับ — ต้องตรวจการหายใจก่อน', nextStepId: 's2' },
          { id: 'c', text: 'ให้ดื่มน้ำ', correct: false,
            feedback: 'ผู้ปลุกไม่ตื่นห้ามป้อนน้ำ เสี่ยงสำลัก', nextStepId: 's2' },
        ],
      },
      {
        id: 's2',
        prompt: 'พบว่า "ยังหายใจปกติ" แต่ปลุกไม่ตื่น — ควรจัดท่าอย่างไร?',
        choices: [
          { id: 'a', text: 'นอนหงายราบไว้', correct: false,
            feedback: 'นอนหงายเสี่ยงลิ้นตก/สำลัก', nextStepId: 's3' },
          { id: 'b', text: 'จับนอนตะแคง (ท่า Recovery)', correct: true,
            feedback: 'ถูก — นอนตะแคงป้องกันลิ้นอุดทางเดินหายใจและสำลัก', nextStepId: 's3' },
          { id: 'c', text: 'นั่งพิงกำแพง', correct: false,
            feedback: 'ผู้ปลุกไม่ตื่นควรนอนตะแคง ไม่ใช่นั่ง', nextStepId: 's3' },
        ],
      },
      {
        id: 's3',
        prompt: 'ระหว่างรอทีมกู้ชีพ คุณควรหาข้อมูลใดของผู้ประสบภัย?',
        choices: [
          { id: 'a', text: 'ค้นกระเป๋าสตางค์/ป้ายชื่อ หาชื่อ-โรคประจำตัว-ยา-เบอร์ญาติ', correct: true,
            feedback: 'ถูก — ช่วยให้ส่งต่อรักษาได้อย่างมีประสิทธิภาพ', nextStepId: 'end' },
          { id: 'b', text: 'ไม่ต้องหา รอเจ้าหน้าที่อย่างเดียว', correct: false,
            feedback: 'ข้อมูลประจำตัวช่วยทีมรักษาได้มาก ควรค้นหาไว้', nextStepId: 'end' },
          { id: 'c', text: 'ถ่ายรูปหน้าโพสต์ตามหาญาติ', correct: false,
            feedback: 'ไม่เหมาะ — ใช้ข้อมูลในกระเป๋า/ป้ายชื่อแทน', nextStepId: 'end' },
        ],
      },
    ],
  },
  {
    id: 'aftercare-handover',
    chapter: 1, lessonId: 'aftercare',
    title: 'ส่งต่อทีมกู้ชีพ',
    summary: 'หน้าที่หลังช่วย — ให้ข้อมูลและรักษาความลับ',
    minutes: 2, icon: 'ClipboardList', color: CH[1],
    steps: [
      {
        id: 's1',
        prompt: 'ทีมกู้ชีพมาถึงเพื่อรับผู้ป่วยที่คุณเพิ่งช่วย — ควรบอกอะไร?',
        choices: [
          { id: 'a', text: 'ปล่อยให้เขาประเมินเองทั้งหมด', correct: false,
            feedback: 'คุณมีข้อมูลที่ช่วยการรักษาได้ ควรส่งต่อ', nextStepId: 's2' },
          { id: 'b', text: 'โรคประจำตัว แพ้ยา แพ้อาหาร หมู่เลือด และสิ่งที่ทำไปแล้ว', correct: true,
            feedback: 'ถูก — ให้ข้อมูลเหล่านี้แก่ทีมฉุกเฉิน', nextStepId: 's2' },
          { id: 'c', text: 'บอกแค่ชื่อก็พอ', correct: false,
            feedback: 'ควรให้ข้อมูลโรคประจำตัว/แพ้ยา/สิ่งที่ทำไปด้วย', nextStepId: 's2' },
        ],
      },
      {
        id: 's2',
        prompt: 'ข้อมูลสุขภาพของพนักงานที่คุณทราบ ควรจัดการอย่างไร?',
        choices: [
          { id: 'a', text: 'เล่าให้เพื่อนร่วมงานฟังได้', correct: false,
            feedback: 'ข้อมูลสุขภาพต้องเป็นความลับ', nextStepId: 's3' },
          { id: 'b', text: 'เก็บเป็นความลับ ใช้เฉพาะกรณีฉุกเฉินโดยทีมฉุกเฉิน', correct: true,
            feedback: 'ถูก — ข้อมูลสุขภาพเป็นความลับ ใช้เฉพาะกรณีฉุกเฉิน', nextStepId: 's3' },
          { id: 'c', text: 'โพสต์อัปเดตอาการลงกลุ่มบริษัท', correct: false,
            feedback: 'ห้ามเด็ดขาด — ละเมิดความลับข้อมูลสุขภาพ', nextStepId: 's3' },
        ],
      },
      {
        id: 's3',
        prompt: 'เพื่อให้พร้อมรับมือครั้งต่อไป องค์กรควร?',
        choices: [
          { id: 'a', text: 'บันทึกประวัติโรคประจำตัวพนักงานก่อนเข้าทำงาน + อบรมปฐมพยาบาลทุก 2 ปี', correct: true,
            feedback: 'ถูก — เตรียมข้อมูลล่วงหน้าและอบรมสม่ำเสมอทุก 2 ปี', nextStepId: 'end' },
          { id: 'b', text: 'ไม่ต้องเตรียมอะไรล่วงหน้า', correct: false,
            feedback: 'ควรเก็บประวัติและอบรมไว้ก่อน', nextStepId: 'end' },
          { id: 'c', text: 'รออบรมเมื่อเกิดเหตุแล้ว', correct: false,
            feedback: 'สายเกินไป — ควรอบรมล่วงหน้าและทบทวนสม่ำเสมอ', nextStepId: 'end' },
        ],
      },
    ],
  },
  {
    id: 'beach-drowning',
    chapter: 1, lessonId: 'assess', bonus: true,
    title: 'เด็กจมน้ำที่ชายหาด',
    summary: 'พบเด็กอายุ 10 ขวบลอยคว่ำในน้ำ',
    minutes: 3,
    icon: 'Wind',
    color: CH[1],
    steps: [
      {
        id: 's1',
        prompt: 'เห็นเด็กลอยคว่ำห่างฝั่ง 5 เมตร คุณว่ายน้ำไม่เก่ง ทำ?',
        choices: [
          { id: 'a', text: 'กระโดดลงไปคว้ามา', correct: false,
            feedback: 'อันตราย — คุณอาจจมตามไปด้วย', nextStepId: 's2' },
          { id: 'b', text: 'ตะโกนเรียกคนช่วย + โยนห่วงยาง/ขวดน้ำ + ยื่นไม้', correct: true,
            feedback: 'ถูก — หลัก "ตะโกน-โยน-ยื่น"', nextStepId: 's2' },
          { id: 'c', text: 'ถ่ายคลิปขอความช่วย', correct: false,
            feedback: 'ทุกวินาทีสำคัญ — ทำตามหลัก reach-throw-go', nextStepId: 's2' },
        ],
      },
      {
        id: 's2',
        prompt: 'นำเด็กขึ้นมาแล้วไม่หายใจ ทำอะไร?',
        choices: [
          { id: 'a', text: 'อุ้มกระแทกไล่น้ำออก', correct: false,
            feedback: 'ผิด — เสียเวลา และอาจสำลักอาเจียนเข้าปอด', nextStepId: 's3' },
          { id: 'b', text: 'เริ่ม CPR ทันที + โทร 1669', correct: true,
            feedback: 'ใช่ — เริ่ม CPR ทันทีไม่ต้องไล่น้ำ', nextStepId: 's3' },
          { id: 'c', text: 'พลิกคว่ำตบหลัง', correct: false,
            feedback: 'นั่นสำหรับสำลัก — เด็กจมน้ำที่ไม่หายใจต้อง CPR', nextStepId: 's3' },
        ],
      },
      {
        id: 's3',
        prompt: 'CPR 5 รอบ เด็กไอน้ำออกมาและร้องไห้ คุณ?',
        choices: [
          { id: 'a', text: 'จบภารกิจ ปล่อยกลับบ้านได้', correct: false,
            feedback: 'แม้ดูดีขึ้น ก็ยังต้องไป รพ. เพราะอาจมี "Secondary drowning" ภายใน 24 ชม.', nextStepId: 'end' },
          { id: 'b', text: 'จัดท่าตะแคง รักษาอบอุ่น พาไป รพ.', correct: true,
            feedback: 'ใช่ — Recovery position และพาไปตรวจปอด', nextStepId: 'end' },
          { id: 'c', text: 'ให้ดื่มน้ำชา', correct: false,
            feedback: 'ห้ามให้กิน-ดื่ม จนกว่าจะตรวจที่ รพ.', nextStepId: 'end' },
        ],
      },
    ],
  },

  // ═══════════════ บทที่ 2 — เจ็บป่วยฉุกเฉิน ═══════════════
  {
    id: 'asthma-attack',
    chapter: 2, lessonId: 'breathing',
    title: 'หอบหืดกำเริบ',
    summary: 'เพื่อนหายใจมีเสียงวี้ด พูดไม่จบประโยค ช่วยพ่นยา',
    minutes: 3, icon: 'Wind', color: CH[2],
    steps: [
      {
        id: 's1',
        prompt: 'เพื่อนหายใจมีเสียง "วี้ด" พูดได้น้อยคำ บอกว่าเป็นหอบหืด — ทำอะไรก่อน?',
        choices: [
          { id: 'a', text: 'ให้นอนราบลงกับพื้น', correct: false,
            feedback: 'ผู้ป่วยหายใจลำบากควรนั่งหลังตรง ไม่ใช่นอนราบ', nextStepId: 's2' },
          { id: 'b', text: 'ถามหายาพ่นประจำตัว แล้วช่วยหยิบ/ประกอบให้', correct: true,
            feedback: 'ถูก — ผู้ป่วยหอบหืดมักมียาพ่นติดตัว ควรถามหาและช่วยหยิบ', nextStepId: 's2' },
          { id: 'c', text: 'ตบหลังแรงๆ ให้โล่ง', correct: false,
            feedback: 'ไม่ใช่การสำลัก — การตบหลังไม่ช่วย', nextStepId: 's2' },
        ],
      },
      {
        id: 's2',
        prompt: 'เขามียาพ่น (Inhaler) คุณช่วยอย่างไรให้ถูกขั้นตอน?',
        choices: [
          { id: 'a', text: 'เขย่ายา ประกอบกระบอก ให้นั่งหลังตรง อมแล้วกดยาพร้อมหายใจเข้าช้าๆ ลึกๆ กลั้น 10 วินาที', correct: true,
            feedback: 'ถูก — ตรงตามขั้นตอนการพ่นยา และตรวจสอบความถูกต้องของยาทุกครั้ง', nextStepId: 's3' },
          { id: 'b', text: 'พ่นยา 5 ครั้งรวดให้แน่ใจ', correct: false,
            feedback: 'ทำตามขนาดที่ถูกต้อง ไม่พ่นรัวๆ', nextStepId: 's3' },
          { id: 'c', text: 'พ่นยาตอนเขาหายใจออก', correct: false,
            feedback: 'ต้องกดยาพร้อมหายใจ "เข้า" ช้าๆ ลึกๆ', nextStepId: 's3' },
        ],
      },
      {
        id: 's3',
        prompt: 'พ่นยาแล้วอาการแย่ลง พูดไม่ได้ ซึมลง — ทำอย่างไร?',
        choices: [
          { id: 'a', text: 'พ่นยาเพิ่มเรื่อยๆ แล้วรอดูอาการ', correct: false,
            feedback: 'อาการแย่ลงต้องโทร 1669 ทันที', nextStepId: 'end' },
          { id: 'b', text: 'โทร 1669 ทันที ถ้าปลุกไม่ตื่น/ไม่หายใจ ให้ปั๊มหัวใจ', correct: true,
            feedback: 'ถูก — ไม่มียา/พ่นแล้วไม่ดีขึ้น/แย่ลง ให้โทร 1669; ปลุกไม่ตื่น ไม่หายใจ → ปั๊มหัวใจ', nextStepId: 'end' },
          { id: 'c', text: 'ให้ดื่มน้ำเย็นๆ', correct: false,
            feedback: 'ไม่ช่วย — ต้องโทร 1669 ทันที', nextStepId: 'end' },
        ],
      },
    ],
  },
  {
    id: 'adult-choking',
    chapter: 2, lessonId: 'choking',
    title: 'ผู้ใหญ่สำลักอาหาร',
    summary: 'เพื่อนเอามือกุมคอ ไอไม่มีเสียง — กระทุ้งท้อง Heimlich',
    minutes: 3, icon: 'Activity', color: CH[2],
    steps: [
      {
        id: 's1',
        prompt: 'เพื่อนกำลังกินข้าว จู่ๆ เอามือกุมคอ ไอไม่มีเสียง พูดไม่ได้ — หมายถึง?',
        choices: [
          { id: 'a', text: 'สำลักรุนแรง ต้องเข้าช่วยทันที', correct: true,
            feedback: 'ถูก — ไอไม่มีเสียง/พูดไม่ได้/กุมคอ คือสำลักรุนแรง', nextStepId: 's2' },
          { id: 'b', text: 'สำลักเบา รอสังเกตอาการ', correct: false,
            feedback: 'อาการเบาคือยังไอมีเสียง/พูดได้ — กรณีนี้รุนแรง ต้องช่วยทันที', nextStepId: 's2' },
          { id: 'c', text: 'แค่เผ็ด ให้ดื่มน้ำ', correct: false,
            feedback: 'การให้ดื่มน้ำจะทำให้สำลักหนักขึ้น', nextStepId: 's2' },
        ],
      },
      {
        id: 's2',
        prompt: 'คุณเข้าช่วย ตำแหน่งวางมือกระทุ้งท้อง (Heimlich) ที่ถูกต้อง?',
        choices: [
          { id: 'a', text: 'กำมือ ชูหัวแม่มือ กดที่ "หัวเข็มขัด/เหนือสะดือเล็กน้อย" กอดแน่นและเร็ว', correct: true,
            feedback: 'ถูก — กดตำแหน่งหัวเข็มขัด เหนือสะดือเล็กน้อย', nextStepId: 's3' },
          { id: 'b', text: 'กดที่คอ', correct: false,
            feedback: 'ห้ามกดคอ — ตำแหน่งคือเหนือสะดือเล็กน้อย', nextStepId: 's3' },
          { id: 'c', text: 'กดใต้สะดือ', correct: false,
            feedback: 'ต้อง "เหนือ" สะดือเล็กน้อย ไม่ใช่ใต้สะดือ', nextStepId: 's3' },
        ],
      },
      {
        id: 's3',
        prompt: 'กระทุ้งไปสักพักเขาหมดสติ ปลุกไม่ตื่น — ทำอย่างไร?',
        choices: [
          { id: 'a', text: 'กระทุ้งท้องต่อทั้งที่หมดสติ', correct: false,
            feedback: 'เมื่อหมดสติให้เปลี่ยนเป็นปั๊มหัวใจ', nextStepId: 'end' },
          { id: 'b', text: 'เริ่มปั๊มหัวใจทันที กดหน้าอก 30 ครั้ง แล้วเปิดปากดูสิ่งแปลกปลอม', correct: true,
            feedback: 'ถูก — สำลักหมดสติ ให้กดหน้าอก 30 ครั้ง เปิดทางเดินหายใจดูสิ่งแปลกปลอมทุกครั้ง', nextStepId: 'end' },
          { id: 'c', text: 'ยกขาขึ้นสูง', correct: false,
            feedback: 'ไม่ใช่ — ต้องเริ่มปั๊มหัวใจ', nextStepId: 'end' },
        ],
      },
    ],
  },
  {
    id: 'pregnant-choking',
    chapter: 2, lessonId: 'choking',
    title: 'หญิงตั้งครรภ์สำลัก',
    summary: 'ห้ามกดหน้าท้อง — ใช้กระดูกหน้าอกแทน',
    minutes: 2, icon: 'Activity', color: CH[2],
    steps: [
      {
        id: 's1',
        prompt: 'หญิงตั้งครรภ์สำลักอาหาร ไอไม่มีเสียง หายใจไม่ออก — ต่างจากคนทั่วไปอย่างไร?',
        choices: [
          { id: 'a', text: 'กดหน้าท้องเหมือนปกติ', correct: false,
            feedback: 'ห้ามกดหน้าท้องหญิงตั้งครรภ์เด็ดขาด', nextStepId: 's2' },
          { id: 'b', text: 'โอบรอบรักแร้ กดที่กระดูกหน้าอกแทน', correct: true,
            feedback: 'ถูก — หญิงตั้งครรภ์ให้กดที่กระดูกหน้าอก (กลางอก)', nextStepId: 's2' },
          { id: 'c', text: 'ให้นอนราบแล้วกดท้อง', correct: false,
            feedback: 'ห้ามกดหน้าท้อง — ใช้กระดูกหน้าอกแทน', nextStepId: 's2' },
        ],
      },
      {
        id: 's2',
        prompt: 'ทำไมจึงห้ามกดหน้าท้องในหญิงตั้งครรภ์?',
        choices: [
          { id: 'a', text: 'จะมีผลต่อเด็กในครรภ์', correct: true,
            feedback: 'ถูก — การกดหน้าท้องมีผลต่อเด็กในครรภ์', nextStepId: 's3' },
          { id: 'b', text: 'ไม่มีเหตุผล ทำได้ปกติ', correct: false,
            feedback: 'มีเหตุผล — กระทบเด็กในครรภ์', nextStepId: 's3' },
          { id: 'c', text: 'เพราะเจ็บมากกว่าเท่านั้น', correct: false,
            feedback: 'เหตุผลหลักคือกระทบเด็กในครรภ์', nextStepId: 's3' },
        ],
      },
      {
        id: 's3',
        prompt: 'สิ่งแปลกปลอมหลุดแล้ว เธอหายใจได้ — ต่อไป?',
        choices: [
          { id: 'a', text: 'จบ ปล่อยกลับได้เลย', correct: false,
            feedback: 'ควรโทร 1669 ทุกครั้งหลังกระทุ้ง', nextStepId: 'end' },
          { id: 'b', text: 'โทร 1669 ทุกครั้ง เพราะอาจมีภาวะอื่นต้องตรวจเพิ่ม', correct: true,
            feedback: 'ถูก — หลังกระทุ้งท้อง/หน้าอกควรโทร 1669 ทุกครั้ง', nextStepId: 'end' },
          { id: 'c', text: 'ให้กินข้าวต่อ', correct: false,
            feedback: 'ควรให้แพทย์ตรวจก่อน', nextStepId: 'end' },
        ],
      },
    ],
  },
  {
    id: 'child-choking',
    chapter: 2, lessonId: 'choking', bonus: true,
    title: 'เด็ก 4 ขวบสำลักลูกอม',
    summary: 'ลูกของเพื่อนคุณ อายุ 4 ขวบ สำลักลูกอม',
    minutes: 3,
    icon: 'Baby',
    color: CH[2],
    steps: [
      {
        id: 's1',
        prompt: 'เด็กจับคอ พูดไม่ออก ไอแห้ง คุณ?',
        choices: [
          { id: 'a', text: 'ล้วงในปากหาลูกอม', correct: false,
            feedback: 'อันตราย — อาจดันลูกอมลงไปอีก', nextStepId: 's2' },
          { id: 'b', text: 'ตบหลังกลางสะบัก 5 ครั้ง', correct: true,
            feedback: 'ใช่ — ตบหลังก่อน 5 ครั้ง', nextStepId: 's2' },
          { id: 'c', text: 'ให้ดื่มน้ำ', correct: false,
            feedback: 'ทำให้สำลักหนักกว่าเดิม', nextStepId: 's2' },
        ],
      },
      {
        id: 's2',
        prompt: 'ตบ 5 ครั้งแล้วยังไม่หลุด ต่อไป?',
        choices: [
          { id: 'a', text: 'รัดท้อง (Heimlich) 5 ครั้ง', correct: true,
            feedback: 'ถูก — เด็กอายุ >1 ปี ใช้ Heimlich ได้ (กำมือเหนือสะดือ ดึงเข้า-ขึ้น)', nextStepId: 's3' },
          { id: 'b', text: 'อุ้มกลับหัวเขย่า', correct: false,
            feedback: 'ไม่แนะนำ — เสี่ยงคอเคล็ดและไม่ได้ผล', nextStepId: 's3' },
          { id: 'c', text: 'รอให้หมดสติก่อน', correct: false,
            feedback: 'รอไม่ได้ — สมองขาดออกซิเจน 4 นาทีเริ่มเสียหาย', nextStepId: 's3' },
        ],
      },
      {
        id: 's3',
        prompt: 'ลูกอมหลุดออก เด็กไอและร้องไห้ ขั้นต่อไป?',
        choices: [
          { id: 'a', text: 'พาไป รพ. เพื่อตรวจ', correct: true,
            feedback: 'ใช่ — อาจมีเศษค้างหรือบาดเจ็บภายใน', nextStepId: 'end' },
          { id: 'b', text: 'ปล่อยเล่นต่อได้เลย', correct: false,
            feedback: 'ควรให้แพทย์ตรวจดูทางเดินหายใจ', nextStepId: 'end' },
          { id: 'c', text: 'ให้นอนพักก่อน', correct: false,
            feedback: 'ควรให้แพทย์ตรวจก่อน', nextStepId: 'end' },
        ],
      },
    ],
  },
  {
    id: 'anaphylaxis-epipen',
    chapter: 2, lessonId: 'anaphylaxis',
    title: 'แพ้อาหารทะเลรุนแรง',
    summary: 'หน้าบวม หายใจไม่ออกใน 2-3 นาที ใช้ EpiPen',
    minutes: 3, icon: 'Syringe', color: CH[2],
    steps: [
      {
        id: 's1',
        prompt: 'เพื่อนกินอาหารทะเลแล้วหน้าบวม ตาบวม หายใจไม่ออกอย่างรวดเร็วใน 2-3 นาที — คือ?',
        choices: [
          { id: 'a', text: 'แพ้รุนแรง (Anaphylaxis) — นาทีชีวิต', correct: true,
            feedback: 'ถูก — อาการแพ้ลุกลามเร็วใน 2-3 นาที ช่วยเร็วเพิ่มโอกาสรอด', nextStepId: 's2' },
          { id: 'b', text: 'อาหารเป็นพิษธรรมดา', correct: false,
            feedback: 'หน้าบวม/หายใจไม่ออกเร็วคืออาการแพ้รุนแรง', nextStepId: 's2' },
          { id: 'c', text: 'เป็นลมเฉยๆ', correct: false,
            feedback: 'อาการบวม/หายใจไม่ออกบ่งบอกการแพ้รุนแรง', nextStepId: 's2' },
        ],
      },
      {
        id: 's2',
        prompt: 'เขามีปากกาฉีดยา (EpiPen) ติดตัว — ใช้อย่างไรให้ถูก?',
        choices: [
          { id: 'a', text: 'ถอดปลอกหัว กำให้แน่น (ห้ามจับด้านปลาย) แทงเข้ากล้ามเนื้อต้นขา ทะลุเสื้อผ้าได้ ค้าง 10 วินาที', correct: true,
            feedback: 'ถูก — ฉีดกล้ามเนื้อต้นขา ค้าง 10 วินาที ห้ามจับด้านปลายเข็ม', nextStepId: 's3' },
          { id: 'b', text: 'ฉีดเข้าเส้นเลือดที่แขน', correct: false,
            feedback: 'ฉีดที่กล้ามเนื้อต้นขา ไม่ใช่เส้นเลือด', nextStepId: 's3' },
          { id: 'c', text: 'ฉีดที่หน้าท้อง โดยจับด้านปลายไว้', correct: false,
            feedback: 'ห้ามจับด้านปลาย (เข็ม) — ฉีดที่ต้นขา', nextStepId: 's3' },
        ],
      },
      {
        id: 's3',
        prompt: 'ฉีดยาเรียบร้อยแล้ว ต้องทำอะไรต่อ?',
        choices: [
          { id: 'a', text: 'โทร 1669 + จดเวลาที่ฉีด ถ้าปลุกไม่ตื่นให้ปั๊มหัวใจ', correct: true,
            feedback: 'ถูก — เรียก 1669 จดเวลาฉีด และเฝ้าระวัง; หมดสติ ไม่หายใจ → ปั๊มหัวใจ', nextStepId: 'end' },
          { id: 'b', text: 'ให้เขาขับรถกลับบ้านเอง', correct: false,
            feedback: 'อันตราย — อาการอาจกลับมา ต้องส่งสถานพยาบาล', nextStepId: 'end' },
          { id: 'c', text: 'เก็บปากกาใส่กระเป๋า ไม่ต้องโทร', correct: false,
            feedback: 'ต้องโทร 1669 และจดเวลาที่ฉีดไว้เสมอ', nextStepId: 'end' },
        ],
      },
    ],
  },
  {
    id: 'workplace-heart-attack',
    chapter: 2, lessonId: 'chest-pain',
    title: 'เพื่อนร่วมงานแน่นหน้าอก',
    summary: 'พนักงานชาย 55 ปี กำลังประชุม จู่ๆ ก็ยกมือกุมหน้าอก เหงื่อแตก',
    minutes: 4,
    icon: 'HeartPulse',
    color: CH[2],
    steps: [
      {
        id: 's1',
        prompt: 'เพื่อนร่วมงานบ่นแน่นหน้าอก ร้าวไปแขนซ้าย เหงื่อท่วม แต่ปฏิเสธว่า "ไม่เป็นไร เดี๋ยวก็หาย" คุณ?',
        choices: [
          { id: 'a', text: 'เชื่อเขา ปล่อยให้พักห้อง', correct: false,
            feedback: 'อันตราย — ผู้ป่วยหัวใจขาดเลือดมักปฏิเสธ อย่าเชื่อ', nextStepId: 's2' },
          { id: 'b', text: 'โทร 1669 ทันที + ส่งคนไปเอา AED + กล่องปฐมพยาบาล', correct: true,
            feedback: 'ถูกต้อง — อาการคลาสสิคของ heart attack ต้องเรียกฉุกเฉินแม้ผู้ป่วยปฏิเสธ', nextStepId: 's2' },
          { id: 'c', text: 'ขับรถพาไป รพ. เอง', correct: false,
            feedback: 'รถกู้ชีพมีอุปกรณ์ + AED + ให้ออกซิเจนได้ระหว่างทาง — เร็วและปลอดภัยกว่า', nextStepId: 's2' },
        ],
      },
      {
        id: 's2',
        prompt: 'เขาบอกว่า "เคยกิน Aspirin ได้ ไม่เป็นโรคกระเพาะ" — กล่องปฐมพยาบาลมี Aspirin คุณ?',
        choices: [
          { id: 'a', text: 'ให้เคี้ยว Aspirin 1 เม็ดทันที', correct: true,
            feedback: 'ถูก — ตรวจสอบแล้วไม่แพ้/ไม่มีโรคกระเพาะ/ไม่มีโรคเลือด → ให้เคี้ยว 1 เม็ด', nextStepId: 's3' },
          { id: 'b', text: 'รอ รพ. ปลอดภัยกว่า', correct: false,
            feedback: 'Aspirin เคี้ยวทันทีช่วยลดอัตราตายจาก heart attack — ถ้าไม่ห้าม ให้เลย', nextStepId: 's3' },
          { id: 'c', text: 'ให้กิน Paracetamol แทน', correct: false,
            feedback: 'Paracetamol ไม่ช่วยอะไรในกรณีนี้ — Aspirin มี mechanism ป้องกันเลือดแข็งตัวที่อุดเส้นเลือด', nextStepId: 's3' },
        ],
      },
      {
        id: 's3',
        prompt: 'จู่ๆ เขาหมดสติ ไม่หายใจ คุณ?',
        choices: [
          { id: 'a', text: 'เริ่ม CPR ทันที + ติด AED', correct: true,
            feedback: 'ใช่ — กดหน้าอกกลางอก 100-120 ครั้ง/นาที + ติด AED เมื่อมาถึง', nextStepId: 'end' },
          { id: 'b', text: 'เรียกชื่อ ตบหน้าให้ฟื้น', correct: false,
            feedback: 'ไม่ช่วย — ทุกวินาทีของ CPR ที่ล่าช้า ลดโอกาสรอด 10%', nextStepId: 'end' },
          { id: 'c', text: 'ยกขาขึ้นสูง', correct: false,
            feedback: 'ไม่ใช่กรณีเป็นลม — ต้องเริ่ม CPR เลย', nextStepId: 'end' },
        ],
      },
    ],
  },
  {
    id: 'chest-pain-elderly',
    chapter: 2, lessonId: 'chest-pain',
    title: 'ผู้สูงอายุ อาการไม่จำเพาะ',
    summary: 'คุณยายเบาหวาน แสบร้อนอก ปวดร้าวต้นคอ เหงื่อแตก',
    minutes: 3, icon: 'HeartPulse', color: CH[2],
    steps: [
      {
        id: 's1',
        prompt: 'คุณยายเป็นเบาหวาน บ่นแสบร้อนกลางอก เหมือนอาหารไม่ย่อย ปวดร้าวต้นคอ เหงื่อแตก — ควรคิดถึง?',
        choices: [
          { id: 'a', text: 'แค่อาหารไม่ย่อย ให้ยาลดกรด', correct: false,
            feedback: 'ผู้สูงอายุ/เบาหวาน อาการหัวใจขาดเลือดมักไม่จำเพาะ — อย่าประมาท', nextStepId: 's2' },
          { id: 'b', text: 'อาจเป็นหัวใจขาดเลือดแบบไม่จำเพาะ ต้องระวัง', correct: true,
            feedback: 'ถูก — กลุ่มนี้มาด้วยแสบร้อนอก/ปวดหลัง-คอ-บ่า/คลื่นไส้ได้', nextStepId: 's2' },
          { id: 'c', text: 'อ่อนเพลียธรรมดา ให้นอนพัก', correct: false,
            feedback: 'อาการอาจซ่อนภาวะหัวใจ — ต้องประเมินจริงจัง', nextStepId: 's2' },
        ],
      },
      {
        id: 's2',
        prompt: 'ท่านปฏิเสธ "ไม่เป็นไร เป็นประจำ ไม่ต้องตื่นตระหนก" คุณ?',
        choices: [
          { id: 'a', text: 'เชื่อท่านแล้วปล่อยไป', correct: false,
            feedback: 'ผู้ป่วยมักปฏิเสธการรักษา — อย่าเชื่อ', nextStepId: 's3' },
          { id: 'b', text: 'ไม่เชื่อคำปฏิเสธ โทร 1669 + เอา AED', correct: true,
            feedback: 'ถูก — แม้ผู้ป่วยปฏิเสธก็ต้องโทร 1669', nextStepId: 's3' },
          { id: 'c', text: 'รอดูอาการอีก 1 ชั่วโมง', correct: false,
            feedback: 'รอไม่ได้ — โทร 1669 ทันที', nextStepId: 's3' },
        ],
      },
      {
        id: 's3',
        prompt: 'ท่านไม่แพ้แอสไพริน ไม่เป็นโรคกระเพาะ/โรคเลือด — ให้อะไร?',
        choices: [
          { id: 'a', text: 'Aspirin เคี้ยว 1 เม็ดทันที', correct: true,
            feedback: 'ถูก — ให้เคี้ยว 1 เม็ดเมื่อไม่มีข้อห้าม', nextStepId: 'end' },
          { id: 'b', text: 'ยานอนหลับให้พัก', correct: false,
            feedback: 'ไม่ใช่ — ให้ Aspirin เคี้ยว', nextStepId: 'end' },
          { id: 'c', text: 'ไม่ให้อะไรเลยทุกกรณี', correct: false,
            feedback: 'เมื่อไม่มีข้อห้ามควรให้ Aspirin เคี้ยว 1 เม็ด', nextStepId: 'end' },
        ],
      },
    ],
  },
  {
    id: 'fainting-event',
    chapter: 2, lessonId: 'fainting',
    title: 'ยืนนานจนจะเป็นลม',
    summary: 'คนยืนนานกลางแดด หน้าซีด เวียนหัว',
    minutes: 2, icon: 'Activity', color: CH[2],
    steps: [
      {
        id: 's1',
        prompt: 'ในงานพิธี มีคนยืนนานกลางแดด เริ่มหน้าซีด เวียนศีรษะ จะเป็นลม — ทำอย่างไร?',
        choices: [
          { id: 'a', text: 'ให้นอนราบลงกับพื้น', correct: true,
            feedback: 'ถูก — ให้นอนราบ เพื่อให้เลือดไปเลี้ยงสมองพอ', nextStepId: 's2' },
          { id: 'b', text: 'จับเขย่าให้ตื่นตัว', correct: false,
            feedback: 'ควรให้นอนราบ ไม่ใช่เขย่า', nextStepId: 's2' },
          { id: 'c', text: 'ให้วิ่งเรียกเลือดลม', correct: false,
            feedback: 'ตรงข้าม — ให้นอนราบพัก', nextStepId: 's2' },
        ],
      },
      {
        id: 's2',
        prompt: 'เขาวูบหมดสติแป๊บเดียวแล้วฟื้น รู้สึกตัวดี — ต่อไป?',
        choices: [
          { id: 'a', text: 'ให้รีบลุกยืนเดินต่อทันที', correct: false,
            feedback: 'อาจวูบซ้ำ — ให้นอนต่อจนหายเวียนแล้วค่อยๆ ลุก', nextStepId: 's3' },
          { id: 'b', text: 'ให้นอนต่อจนหายเวียน ค่อยๆ ลุกนั่งช้าๆ และตรวจว่ามีแผลจากการล้มไหม', correct: true,
            feedback: 'ถูก — นอนต่อ ลุกช้าๆ และตรวจการบาดเจ็บจากการล้ม', nextStepId: 's3' },
          { id: 'c', text: 'ให้กินยาทันที', correct: false,
            feedback: 'ไม่จำเป็น — ให้พักและลุกช้าๆ', nextStepId: 's3' },
        ],
      },
      {
        id: 's3',
        prompt: 'เมื่อไหร่ควรโทร 1669?',
        choices: [
          { id: 'a', text: 'ถ้าอาการไม่ดีขึ้น หรือ ปลุกไม่ตื่น', correct: true,
            feedback: 'ถูก — อาการไม่ดีขึ้น/ปลุกไม่ตื่น ให้โทร 1669', nextStepId: 'end' },
          { id: 'b', text: 'ไม่ต้องโทรเลย เป็นลมธรรมดา', correct: false,
            feedback: 'ถ้าไม่ฟื้น/อาการแย่ ต้องโทร 1669', nextStepId: 'end' },
          { id: 'c', text: 'โทรเฉพาะตอนกลางคืน', correct: false,
            feedback: 'ขึ้นกับอาการ ไม่ใช่เวลา', nextStepId: 'end' },
        ],
      },
    ],
  },
  {
    id: 'hypo-conscious',
    chapter: 2, lessonId: 'hypoglycemia',
    title: 'เบาหวานน้ำตาลตก (ยังรู้สึกตัว)',
    summary: 'เพื่อนเบาหวานสับสน เหงื่อแตก มือสั่น แต่ยังกลืนได้',
    minutes: 2, icon: 'Candy', color: CH[2],
    steps: [
      {
        id: 's1',
        prompt: 'เพื่อนเป็นเบาหวาน วันนี้กินข้าวน้อย เริ่มสับสน เหงื่อแตก มือสั่น ยังรู้สึกตัวและกลืนได้ — ทำ?',
        choices: [
          { id: 'a', text: 'ให้ดื่ม/กินน้ำตาลทันที เช่น น้ำผลไม้ นม น้ำหวาน', correct: true,
            feedback: 'ถูก — ยังกลืนได้ ให้น้ำตาลทันที', nextStepId: 's2' },
          { id: 'b', text: 'ให้เครื่องดื่มสูตรลดน้ำหนัก', correct: false,
            feedback: 'ผิด — เครื่องดื่มลดน้ำหนักไม่มีน้ำตาล', nextStepId: 's2' },
          { id: 'c', text: 'ให้นอนเฉยๆ รอหายเอง', correct: false,
            feedback: 'น้ำตาลตกหากไม่ช่วยมักเสียชีวิต — ต้องให้น้ำตาล', nextStepId: 's2' },
        ],
      },
      {
        id: 's2',
        prompt: 'ทำไมช็อกโกแลตจึงไม่เหมาะสำหรับภาวะน้ำตาลตก?',
        choices: [
          { id: 'a', text: 'มีน้ำตาลน้อยเกินไปสำหรับภาวะน้ำตาลตก', correct: true,
            feedback: 'ถูก — ช็อกโกแลตมีน้ำตาลน้อยไป', nextStepId: 's3' },
          { id: 'b', text: 'มีคาเฟอีน', correct: false,
            feedback: 'เหตุผลคือน้ำตาลน้อยเกินไป', nextStepId: 's3' },
          { id: 'c', text: 'เพราะเป็นของแข็ง', correct: false,
            feedback: 'เหตุผลคือปริมาณน้ำตาลไม่พอ', nextStepId: 's3' },
        ],
      },
      {
        id: 's3',
        prompt: 'หลังให้น้ำตาลแล้ว ควรทำอะไรต่อ?',
        choices: [
          { id: 'a', text: 'ให้นั่งช้าๆ/นอนลง แล้วโทร 1669', correct: true,
            feedback: 'ถูก — ให้นั่ง/นอน แล้วโทร 1669', nextStepId: 'end' },
          { id: 'b', text: 'ให้ออกกำลังกายเรียกเหงื่อ', correct: false,
            feedback: 'ตรงข้าม — ให้นั่ง/นอนพัก', nextStepId: 'end' },
          { id: 'c', text: 'ให้กลับไปทำงานต่อทันที', correct: false,
            feedback: 'ควรพักและโทร 1669', nextStepId: 'end' },
        ],
      },
    ],
  },
  {
    id: 'hypo-unconscious',
    chapter: 2, lessonId: 'hypoglycemia',
    title: 'น้ำตาลตก (กลืนไม่ได้)',
    summary: 'ผู้ป่วยซึมลง กลืนไม่ได้ — ห้ามป้อนอาหาร',
    minutes: 2, icon: 'Candy', color: CH[2],
    steps: [
      {
        id: 's1',
        prompt: 'เพื่อนเบาหวานซึมลงมาก ปลุกแทบไม่ตื่น นั่งไม่ได้ กลืนไม่ได้ — จะป้อนน้ำหวานไหม?',
        choices: [
          { id: 'a', text: 'ป้อนน้ำหวานทันที', correct: false,
            feedback: 'ห้าม — กลืนไม่ได้จะอุดกั้นทางเดินหายใจ/สำลัก', nextStepId: 's2' },
          { id: 'b', text: 'ห้ามป้อน เพราะกลืนไม่ได้จะสำลัก/อุดทางเดินหายใจ', correct: true,
            feedback: 'ถูก — ผู้ที่กลืน/นั่งไม่ได้ ห้ามให้กิน/ดื่ม', nextStepId: 's2' },
          { id: 'c', text: 'ป้ายน้ำผึ้งในปากเยอะๆ', correct: false,
            feedback: 'ห้าม — เสี่ยงสำลักเข้าปอด', nextStepId: 's2' },
        ],
      },
      {
        id: 's2',
        prompt: 'แล้วต้องทำอะไรแทน?',
        choices: [
          { id: 'a', text: 'โทร 1669 ทันที', correct: true,
            feedback: 'ถูก — กลืนไม่ได้ ให้โทร 1669 ทันที', nextStepId: 's3' },
          { id: 'b', text: 'รอให้รู้สึกตัวเองก่อน', correct: false,
            feedback: 'รอไม่ได้ — ต้องโทร 1669', nextStepId: 's3' },
          { id: 'c', text: 'เขย่าให้ตื่นแรงๆ', correct: false,
            feedback: 'ไม่ช่วย — โทร 1669 ทันที', nextStepId: 's3' },
        ],
      },
      {
        id: 's3',
        prompt: 'ถ้าเขาปลุกไม่ตื่นและหยุดหายใจ?',
        choices: [
          { id: 'a', text: 'เริ่มปั๊มหัวใจทันที', correct: true,
            feedback: 'ถูก — ปลุกไม่ตื่น ไม่หายใจ → ปั๊มหัวใจทันที', nextStepId: 'end' },
          { id: 'b', text: 'รอทีมกู้ชีพอย่างเดียว', correct: false,
            feedback: 'ต้องเริ่มปั๊มหัวใจระหว่างรอ', nextStepId: 'end' },
          { id: 'c', text: 'ยกขาสูง', correct: false,
            feedback: 'ไม่ใช่ — ต้องปั๊มหัวใจ', nextStepId: 'end' },
        ],
      },
    ],
  },
  {
    id: 'stroke-fast',
    chapter: 2, lessonId: 'stroke',
    title: 'ปากเบี้ยว แขนอ่อนแรงข้างเดียว',
    summary: 'อาการอัมพาตเฉียบพลัน — จดเวลา โทร 1669',
    minutes: 2, icon: 'Brain', color: CH[2],
    steps: [
      {
        id: 's1',
        prompt: 'เพื่อนจู่ๆ พูดไม่ชัด ปากเบี้ยว แขนขวาอ่อนแรงยกไม่ขึ้น เกิดขึ้นเฉียบพลัน — คิดถึงภาวะใด?',
        choices: [
          { id: 'a', text: 'อัมพาต (Stroke) — ชั่วโมงทอง', correct: true,
            feedback: 'ถูก — อ่อนแรง/ชาข้างเดียว พูดไม่ชัด คืออัมพาต', nextStepId: 's2' },
          { id: 'b', text: 'เหน็บชาธรรมดา', correct: false,
            feedback: 'อาการข้างเดียวเฉียบพลันคืออัมพาต ไม่ใช่เหน็บชา', nextStepId: 's2' },
          { id: 'c', text: 'ง่วงนอน', correct: false,
            feedback: 'เป็นสัญญาณอัมพาต ต้องรีบช่วย', nextStepId: 's2' },
        ],
      },
      {
        id: 's2',
        prompt: 'สิ่งที่สำคัญมากที่ต้องทำ/จดไว้?',
        choices: [
          { id: 'a', text: 'จด/จำ "เวลาที่เริ่มมีอาการ" + โทร 1669 + เอา AED', correct: true,
            feedback: 'ถูก — เวลาที่เริ่มมีอาการสำคัญมากต่อการรักษา', nextStepId: 's3' },
          { id: 'b', text: 'ให้กินยาละลายลิ่มเลือดเอง', correct: false,
            feedback: 'ห้าม — ต้องให้แพทย์ประเมินก่อน', nextStepId: 's3' },
          { id: 'c', text: 'ให้นอนหลับรอดูอาการ', correct: false,
            feedback: 'รอไม่ได้ — โทร 1669 และจดเวลา', nextStepId: 's3' },
        ],
      },
      {
        id: 's3',
        prompt: 'ระหว่างรอ เขาเริ่มปลุกไม่ตื่น ไม่หายใจ?',
        choices: [
          { id: 'a', text: 'ปั๊มหัวใจทันที', correct: true,
            feedback: 'ถูก — ปลุกไม่ตื่น ไม่หายใจ → ปั๊มหัวใจ', nextStepId: 'end' },
          { id: 'b', text: 'เขย่าเรียกอย่างเดียว', correct: false,
            feedback: 'ต้องปั๊มหัวใจ', nextStepId: 'end' },
          { id: 'c', text: 'ให้ดื่มน้ำ', correct: false,
            feedback: 'ห้ามป้อนน้ำ — ปั๊มหัวใจ', nextStepId: 'end' },
        ],
      },
    ],
  },
  {
    id: 'seizure-care',
    chapter: 2, lessonId: 'seizure',
    title: 'ชักเกร็งกลางที่ทำงาน',
    summary: 'ดูแลขณะชักและหลังชัก — ห้ามงัดปาก',
    minutes: 2, icon: 'Zap', color: CH[2],
    steps: [
      {
        id: 's1',
        prompt: 'เพื่อนล้มลงชักเกร็ง มือเท้ากระตุก น้ำลายฟูมปาก — ขณะชัก ทำอย่างไร?',
        choices: [
          { id: 'a', text: 'จับตัวกดไว้ให้หยุดดิ้น', correct: false,
            feedback: 'ห้ามกดตัว — ป้องกันบาดเจ็บโดยเคลียร์ของรอบตัวแทน', nextStepId: 's2' },
          { id: 'b', text: 'ย้ายของรอบตัวออก ใช้ผ้า/หมอนหนุนศีรษะ + โทร 1669', correct: true,
            feedback: 'ถูก — ป้องกันการบาดเจ็บ ย้ายของอันตราย หนุนศีรษะ', nextStepId: 's2' },
          { id: 'c', text: 'เอาช้อนงัดปากกันกัดลิ้น', correct: false,
            feedback: 'ห้ามเด็ดขาด — งัดปากทำให้กั้นทางเดินหายใจ ฟันหัก', nextStepId: 's2' },
        ],
      },
      {
        id: 's2',
        prompt: 'เพื่อนข้างๆ จะเอาช้อนใส่ปากกันกัดลิ้น คุณ?',
        choices: [
          { id: 'a', text: 'ห้าม! ห้ามใช้ช้อน/ของแข็งงัดปาก', correct: true,
            feedback: 'ถูก — เสี่ยงกั้นทางเดินหายใจ ฟันหัก กัดมือคนช่วย', nextStepId: 's3' },
          { id: 'b', text: 'ช่วยกันงัดปาก', correct: false,
            feedback: 'ห้ามเด็ดขาด', nextStepId: 's3' },
          { id: 'c', text: 'ใช้นิ้วล้วงลิ้นออก', correct: false,
            feedback: 'อันตราย — อาจถูกกัดและกั้นทางเดินหายใจ', nextStepId: 's3' },
        ],
      },
      {
        id: 's3',
        prompt: 'ชักหยุดแล้ว มีน้ำลาย/อาเจียนไหลจากปาก (ไม่มีบาดเจ็บคอ/ศีรษะ) — ทำ?',
        choices: [
          { id: 'a', text: 'จับนอนตะแคง ป้องกันสำลัก', correct: true,
            feedback: 'ถูก — ตะแคงตัวเมื่อไม่มีบาดเจ็บศีรษะ/คอ', nextStepId: 'end' },
          { id: 'b', text: 'นอนหงายราบ', correct: false,
            feedback: 'เสี่ยงสำลัก — ควรตะแคง', nextStepId: 'end' },
          { id: 'c', text: 'ปลุกให้ลุกเดินทันที', correct: false,
            feedback: 'ให้พัก ถ้าซึม/สับสนส่งสถานพยาบาล', nextStepId: 'end' },
        ],
      },
    ],
  },
  {
    id: 'shock-bleeding',
    chapter: 2, lessonId: 'shock',
    title: 'ภาวะช็อกจากเสียเลือด',
    summary: 'ซีด เหงื่อเย็น กระสับกระส่าย — นอนราบ ห่มผ้า',
    minutes: 2, icon: 'Activity', color: CH[2],
    steps: [
      {
        id: 's1',
        prompt: 'คนงานเสียเลือดมาก ตอนนี้ซีด ปลายมือเท้าซีดเย็น เวียนหัว กระสับกระส่าย — ภาวะใด?',
        choices: [
          { id: 'a', text: 'ช็อก (เลือดไปเลี้ยงร่างกายไม่พอ)', correct: true,
            feedback: 'ถูก — อาการเหล่านี้คือภาวะช็อก', nextStepId: 's2' },
          { id: 'b', text: 'แค่หิวข้าว', correct: false,
            feedback: 'อาการซีดเย็น/สับสนคือช็อก', nextStepId: 's2' },
          { id: 'c', text: 'ง่วงนอน', correct: false,
            feedback: 'เป็นภาวะช็อก ต้องช่วยด่วน', nextStepId: 's2' },
        ],
      },
      {
        id: 's2',
        prompt: 'ท่าและการดูแลที่เหมาะสม?',
        choices: [
          { id: 'a', text: 'ให้นอนราบ ห่มผ้าให้อบอุ่น + โทร 1669', correct: true,
            feedback: 'ถูก — นอนราบ ห่มผ้า โทร 1669 และเอา AED', nextStepId: 's3' },
          { id: 'b', text: 'ให้ยืนเดินไปมา', correct: false,
            feedback: 'ตรงข้าม — ให้นอนราบ', nextStepId: 's3' },
          { id: 'c', text: 'ให้นั่งดื่มกาแฟร้อน', correct: false,
            feedback: 'ไม่เหมาะ — ให้นอนราบและห่มผ้า', nextStepId: 's3' },
        ],
      },
      {
        id: 's3',
        prompt: 'ถ้าเขาปลุกไม่ตื่น ไม่หายใจ?',
        choices: [
          { id: 'a', text: 'ปั๊มหัวใจทันที', correct: true,
            feedback: 'ถูก — ปลุกไม่ตื่น ไม่หายใจ → ปั๊มหัวใจ', nextStepId: 'end' },
          { id: 'b', text: 'รออย่างเดียว', correct: false,
            feedback: 'ต้องเริ่มปั๊มหัวใจ', nextStepId: 'end' },
          { id: 'c', text: 'ตบหน้าให้ฟื้น', correct: false,
            feedback: 'ไม่ช่วย — ปั๊มหัวใจ', nextStepId: 'end' },
        ],
      },
    ],
  },

  // ═══════════════ บทที่ 3 — บาดเจ็บฉุกเฉิน ═══════════════
  {
    id: 'bleeding-direct',
    chapter: 3, lessonId: 'bleeding',
    title: 'ห้ามเลือดด้วยการกด',
    summary: 'มีดบาดแขน เลือดไหล — Direct pressure',
    minutes: 2, icon: 'Droplet', color: CH[3],
    steps: [
      {
        id: 's1',
        prompt: 'เพื่อนถูกมีดบาดที่แขน เลือดไหลปานกลาง — วิธีห้ามเลือดที่ดีที่สุด?',
        choices: [
          { id: 'a', text: 'ใส่ถุงมือ วางผ้าสะอาดบนแผล กดตรงๆ (direct pressure)', correct: true,
            feedback: 'ถูก — กดที่จุดเลือดออกตรงๆ ง่ายและได้ผลที่สุด', nextStepId: 's2' },
          { id: 'b', text: 'รัดเหนือแผลทันที', correct: false,
            feedback: 'การรัด (tourniquet) ใช้เฉพาะเลือดออกมากที่กดแล้วไม่หยุด', nextStepId: 's2' },
          { id: 'c', text: 'ราดแอลกอฮอล์ลงแผล', correct: false,
            feedback: 'ไม่ช่วยห้ามเลือด — ให้กดแผลตรงๆ', nextStepId: 's2' },
        ],
      },
      {
        id: 's2',
        prompt: 'กดแล้วเลือดยังซึมผ่านผ้า — ทำอย่างไร?',
        choices: [
          { id: 'a', text: 'เปิดผ้าออกดูแผลบ่อยๆ', correct: false,
            feedback: 'อย่าเปิดผ้าเดิม — จะรบกวนการแข็งตัวของเลือด', nextStepId: 's3' },
          { id: 'b', text: 'เพิ่มผ้าพันแผลซ้อนทับ แล้วกดให้แน่นขึ้น', correct: true,
            feedback: 'ถูก — วางผ้าซ้อนเพิ่มและกดแน่นขึ้น ไม่เอาผ้าเดิมออก', nextStepId: 's3' },
          { id: 'c', text: 'เอาผ้าเดิมออกเปลี่ยนใหม่', correct: false,
            feedback: 'ห้ามเอาผ้าเดิมออก — ให้ซ้อนทับแทน', nextStepId: 's3' },
        ],
      },
      {
        id: 's3',
        prompt: 'เลือดหยุดแล้วแต่ต้องกดนาน — ทำอย่างไร?',
        choices: [
          { id: 'a', text: 'ใช้ผ้าพันแผลพันรอบให้แน่นคาไว้', correct: true,
            feedback: 'ถูก — พันรอบแผลให้แน่นเพื่อกดต่อในตัว', nextStepId: 'end' },
          { id: 'b', text: 'ปล่อยมือทันที', correct: false,
            feedback: 'ควรพันแผลให้แน่นไว้ ไม่ปล่อยเฉยๆ', nextStepId: 'end' },
          { id: 'c', text: 'ล้างแผลใหญ่ด้วยน้ำแรงๆ', correct: false,
            feedback: 'แผลใหญ่ให้ห้ามเลือดก่อน ไม่ล้างแรงๆ', nextStepId: 'end' },
        ],
      },
    ],
  },
  {
    id: 'bleeding-tourniquet',
    chapter: 3, lessonId: 'bleeding',
    title: 'เลือดพุ่งจากแขน — รัดห้ามเลือด',
    summary: 'กดไม่หยุด เลือดออกมาก ใช้ Tourniquet',
    minutes: 3, icon: 'Droplets', color: CH[3],
    steps: [
      {
        id: 's1',
        prompt: 'อุบัติเหตุ เลือดพุ่งจากต้นแขนไม่หยุด กดแผลแล้วยังไหลแรง เสี่ยงชีวิต — ทำ?',
        choices: [
          { id: 'a', text: 'ใช้ชุดรัด (tourniquet) เหนือแผลประมาณ 2 นิ้ว รัดจนเลือดหยุด', correct: true,
            feedback: 'ถูก — เลือดออกมากจากแขน/ขา กดไม่หยุด ใช้การรัดเหนือแผล ~2 นิ้ว', nextStepId: 's2' },
          { id: 'b', text: 'กดเบาๆ รอดูต่อ', correct: false,
            feedback: 'เลือดออกมากเสี่ยงชีวิต ต้องรัดห้ามเลือด', nextStepId: 's2' },
          { id: 'c', text: 'ยกแขนขึ้นเฉยๆ', correct: false,
            feedback: 'ไม่พอ — ต้องรัดห้ามเลือด', nextStepId: 's2' },
        ],
      },
      {
        id: 's2',
        prompt: 'หลังรัดห้ามเลือดได้แล้ว สิ่งสำคัญที่ต้องทำ?',
        choices: [
          { id: 'a', text: 'จดเวลาที่เริ่มรัด + โทร 1669 + ส่ง รพ. เร็วที่สุด', correct: true,
            feedback: 'ถูก — จดเวลาที่รัดและรีบส่งสถานพยาบาล', nextStepId: 's3' },
          { id: 'b', text: 'คลายชุดออกทุก 5 นาที', correct: false,
            feedback: 'ห้ามไขออก/ปลดเด็ดขาด — ให้เจ้าหน้าที่กู้ชีพจัดการ', nextStepId: 's3' },
          { id: 'c', text: 'ถอดออกเมื่อเลือดหยุด', correct: false,
            feedback: 'ห้ามถอด — ให้เจ้าหน้าที่จัดการต่อ', nextStepId: 's3' },
        ],
      },
      {
        id: 's3',
        prompt: 'ในกล่องไม่มีชุดรัดสำเร็จรูป — ทำอย่างไร?',
        choices: [
          { id: 'a', text: 'ใช้ผ้าสะอาดพันรอบ + แท่งไม้/ปากกา/ตะเกียบ หมุนรัด', correct: true,
            feedback: 'ถูก — ใช้ผ้า + ไม้/ปากกา/ตะเกียบ ผูกแล้วหมุนรัด (ผ้าสามเหลี่ยมดีที่สุด)', nextStepId: 'end' },
          { id: 'b', text: 'ใช้ลวดเส้นเล็กรัด', correct: false,
            feedback: 'ลวดเล็กบาดเนื้อ — ใช้ผ้ากว้าง ~1 นิ้ว', nextStepId: 'end' },
          { id: 'c', text: 'ไม่ทำอะไร รอกู้ชีพ', correct: false,
            feedback: 'เลือดออกมากรอไม่ได้ — ทำชุดรัดชั่วคราว', nextStepId: 'end' },
        ],
      },
    ],
  },
  {
    id: 'nosebleed',
    chapter: 3, lessonId: 'wounds',
    title: 'เลือดกำเดาไหล',
    summary: 'ท่านั่งและการบีบจมูกที่ถูกต้อง',
    minutes: 2, icon: 'Droplet', color: CH[3],
    steps: [
      {
        id: 's1',
        prompt: 'เพื่อนเลือดกำเดาไหล — ควรอยู่ในท่าใด?',
        choices: [
          { id: 'a', text: 'นั่งเอนตัวไปข้างหน้า', correct: true,
            feedback: 'ถูก — เอนไปข้างหน้าเพื่อไม่ให้เลือดไหลลงคอ', nextStepId: 's2' },
          { id: 'b', text: 'เงยหน้าขึ้น', correct: false,
            feedback: 'ห้ามเงยหน้า — เลือดจะไหลลงคอ ทำให้สำลัก/อาเจียน', nextStepId: 's2' },
          { id: 'c', text: 'นอนหงาย', correct: false,
            feedback: 'เลือดจะไหลลงคอ — ให้นั่งเอนไปข้างหน้า', nextStepId: 's2' },
        ],
      },
      {
        id: 's2',
        prompt: 'ทำต่ออย่างไรให้เลือดหยุด?',
        choices: [
          { id: 'a', text: 'ใช้นิ้วบีบปีกจมูกทั้งสองข้าง 2-3 นาทีจนหยุด', correct: true,
            feedback: 'ถูก — บีบปีกจมูก 2-3 นาที ถ้ายังไม่หยุดบีบแน่นขึ้น', nextStepId: 's3' },
          { id: 'b', text: 'เอากระดาษยัดรูจมูกลึกๆ', correct: false,
            feedback: 'ไม่แนะนำ — ให้บีบปีกจมูก', nextStepId: 's3' },
          { id: 'c', text: 'สั่งน้ำมูกแรงๆ', correct: false,
            feedback: 'จะยิ่งเลือดออก — ให้บีบจมูกนิ่งๆ', nextStepId: 's3' },
        ],
      },
      {
        id: 's3',
        prompt: 'เมื่อไหร่ต้องโทร 1669?',
        choices: [
          { id: 'a', text: 'บีบ 15 นาทีแล้วไม่หยุด / เลือดออกมากขึ้น / หายใจไม่ได้', correct: true,
            feedback: 'ถูก — เกณฑ์โทร 1669 สำหรับเลือดกำเดา', nextStepId: 'end' },
          { id: 'b', text: 'ทันทีที่เริ่มไหล', correct: false,
            feedback: 'ส่วนใหญ่หยุดได้เอง — โทรเมื่อเข้าเกณฑ์', nextStepId: 'end' },
          { id: 'c', text: 'ไม่ต้องโทรเลยทุกกรณี', correct: false,
            feedback: 'ถ้าไม่หยุด/ออกมาก/หายใจไม่ได้ ต้องโทร', nextStepId: 'end' },
        ],
      },
    ],
  },
  {
    id: 'amputation',
    chapter: 3, lessonId: 'wounds',
    title: 'นิ้วขาดจากเครื่องจักร',
    summary: 'ห้ามเลือด + เก็บชิ้นส่วนให้แพทย์ต่อ',
    minutes: 3, icon: 'Scissors', color: CH[3],
    steps: [
      {
        id: 's1',
        prompt: 'เครื่องจักรตัดนิ้วคนงานขาด เลือดออกมาก — ลำดับแรกกับตัวผู้ประสบภัย?',
        choices: [
          { id: 'a', text: 'โทร 1669 + ใส่ถุงมือ + กดห้ามเลือดที่แผล (กดนาน)', correct: true,
            feedback: 'ถูก — ช่วยคนก่อน: โทร 1669 และกดห้ามเลือดให้นาน', nextStepId: 's2' },
          { id: 'b', text: 'วิ่งไปหานิ้วที่ขาดก่อน', correct: false,
            feedback: 'ห้ามเลือดที่ตัวคนก่อน แล้วค่อยหาชิ้นส่วน', nextStepId: 's2' },
          { id: 'c', text: 'ราดน้ำล้างแผลใหญ่', correct: false,
            feedback: 'ให้ห้ามเลือดก่อน ไม่ล้างแผลใหญ่', nextStepId: 's2' },
        ],
      },
      {
        id: 's2',
        prompt: 'เก็บชิ้นนิ้วที่ขาดอย่างไรให้ถูกต้อง?',
        choices: [
          { id: 'a', text: 'ล้างน้ำสะอาด ห่อผ้าสะอาด ใส่ถุงพลาสติก แล้วใส่ถุงซ้อนอีกใบที่มีน้ำแข็ง+น้ำ', correct: true,
            feedback: 'ถูก — ห่อแล้วใส่ถุงซ้อน ป้องกันชิ้นส่วนโดนน้ำแข็ง/น้ำโดยตรง', nextStepId: 's3' },
          { id: 'b', text: 'แช่นิ้วลงในน้ำแข็งโดยตรง', correct: false,
            feedback: 'ห้าม — โดนน้ำแข็ง/น้ำโดยตรงทำให้ชิ้นส่วนเสียหาย', nextStepId: 's3' },
          { id: 'c', text: 'ใส่กระเป๋ากางเกงไว้เฉยๆ', correct: false,
            feedback: 'ต้องล้าง ห่อ ใส่ถุงซ้อน และแช่เย็นอย่างถูกวิธี', nextStepId: 's3' },
        ],
      },
      {
        id: 's3',
        prompt: 'ส่งโรงพยาบาลอย่างไร?',
        choices: [
          { id: 'a', text: 'แปะป้ายชื่อ/วันที่/เวลาที่เก็บ ส่งไปพร้อมผู้ประสบภัยทันที', correct: true,
            feedback: 'ถูก — ติดป้ายข้อมูลและส่งไปพร้อมผู้ประสบภัย', nextStepId: 'end' },
          { id: 'b', text: 'ส่งนิ้วตามไปทีหลังวันรุ่งขึ้น', correct: false,
            feedback: 'ต้องส่งไปพร้อมกันทันที', nextStepId: 'end' },
          { id: 'c', text: 'ทิ้งไป ต่อไม่ได้แล้ว', correct: false,
            feedback: 'เก็บไว้ดีๆ แพทย์อาจต่อกลับได้', nextStepId: 'end' },
        ],
      },
    ],
  },
  {
    id: 'impaled-object',
    chapter: 3, lessonId: 'wounds',
    title: 'ถูกของมีคมทิ่มคา',
    summary: 'เหล็กเส้นทิ่มคาขา — ห้ามดึงออก',
    minutes: 2, icon: 'AlertCircle', color: CH[3],
    steps: [
      {
        id: 's1',
        prompt: 'คนงานถูกเหล็กเส้นทิ่มคาที่ขา ยังคาอยู่ มีเลือดออก — ทำอย่างไร?',
        choices: [
          { id: 'a', text: 'ดึงเหล็กออกทันที', correct: false,
            feedback: 'ห้ามดึง — จะทำให้แผลกว้างขึ้น เลือดออกมากขึ้น', nextStepId: 's2' },
          { id: 'b', text: 'ห้ามดึง/แตะ/ขยับ + โทร 1669 + ห้ามเลือดรอบๆ ที่เห็น', correct: true,
            feedback: 'ถูก — ปล่อยของมีคมคาไว้ ห้ามเลือดรอบๆ แล้วโทร 1669', nextStepId: 's2' },
          { id: 'c', text: 'หมุนคลายออกช้าๆ', correct: false,
            feedback: 'ห้ามขยับ/หมุน — แผลจะกว้างขึ้น', nextStepId: 's2' },
        ],
      },
      {
        id: 's2',
        prompt: 'ระหว่างรอทีมกู้ชีพ?',
        choices: [
          { id: 'a', text: 'ห้ามผู้ประสบภัยขยับตัว', correct: true,
            feedback: 'ถูก — ให้อยู่นิ่ง ป้องกันแผลขยาย', nextStepId: 's3' },
          { id: 'b', text: 'ให้ลุกเดินไปนั่งรถ', correct: false,
            feedback: 'ห้ามขยับ — รอทีมกู้ชีพ', nextStepId: 's3' },
          { id: 'c', text: 'โยกเหล็กดูว่าลึกแค่ไหน', correct: false,
            feedback: 'ห้ามแตะ/ขยับเด็ดขาด', nextStepId: 's3' },
        ],
      },
      {
        id: 's3',
        prompt: 'ใครควรเป็นคนเอาเหล็กออก?',
        choices: [
          { id: 'a', text: 'แพทย์/เจ้าหน้าที่ที่โรงพยาบาลเท่านั้น', correct: true,
            feedback: 'ถูก — ให้ผู้เชี่ยวชาญจัดการที่สถานพยาบาล', nextStepId: 'end' },
          { id: 'b', text: 'ใครก็ได้ที่แข็งแรง', correct: false,
            feedback: 'ห้าม — ต้องเป็นแพทย์/เจ้าหน้าที่', nextStepId: 'end' },
          { id: 'c', text: 'ตัวผู้ประสบภัยเอง', correct: false,
            feedback: 'ห้ามดึงเอง — ให้แพทย์จัดการ', nextStepId: 'end' },
        ],
      },
    ],
  },
  {
    id: 'internal-bleeding',
    chapter: 3, lessonId: 'internal-bleeding',
    title: 'ตกเลือดภายใน',
    summary: 'ไม่เห็นเลือดออก แต่มีสัญญาณช็อก',
    minutes: 2, icon: 'AlertCircle', color: CH[3],
    steps: [
      {
        id: 's1',
        prompt: 'คนตกจากที่สูง/รถชน บ่นปวดท้องมาก หายใจถี่ ซีด แต่ไม่เห็นเลือดออกภายนอก — สงสัยภาวะใด?',
        choices: [
          { id: 'a', text: 'ตกเลือดภายใน (มองไม่เห็นด้วยตา)', correct: true,
            feedback: 'ถูก — บาดเจ็บหน้าอก/ท้องอาจตกเลือดภายในโดยไม่เห็นเลือด', nextStepId: 's2' },
          { id: 'b', text: 'ปวดท้องธรรมดา', correct: false,
            feedback: 'หลังกระแทกแล้วซีด/หายใจถี่ ให้สงสัยตกเลือดภายใน', nextStepId: 's2' },
          { id: 'c', text: 'แค่ตกใจ', correct: false,
            feedback: 'อาการเหล่านี้อันตราย — สงสัยตกเลือดภายใน', nextStepId: 's2' },
        ],
      },
      {
        id: 's2',
        prompt: 'ทำอย่างไร?',
        choices: [
          { id: 'a', text: 'โทร 1669 + ใส่ถุงมือ/PPE + ให้นอนนิ่งๆ และตรวจอาการช็อก', correct: true,
            feedback: 'ถูก — โทร 1669 ให้นอนนิ่ง และเฝ้าระวังช็อก', nextStepId: 's3' },
          { id: 'b', text: 'ให้ลุกเดินคลายปวด', correct: false,
            feedback: 'ห้าม — ให้นอนนิ่งๆ', nextStepId: 's3' },
          { id: 'c', text: 'ให้กินยาแก้ปวด', correct: false,
            feedback: 'ไม่ควร — รอแพทย์ประเมิน', nextStepId: 's3' },
        ],
      },
      {
        id: 's3',
        prompt: 'เขาปลุกไม่ตื่น ไม่หายใจ?',
        choices: [
          { id: 'a', text: 'ปั๊มหัวใจทันที', correct: true,
            feedback: 'ถูก — ปลุกไม่ตื่น ไม่หายใจ → ปั๊มหัวใจ', nextStepId: 'end' },
          { id: 'b', text: 'รอเฉยๆ', correct: false,
            feedback: 'ต้องเริ่มปั๊มหัวใจ', nextStepId: 'end' },
          { id: 'c', text: 'นวดท้อง', correct: false,
            feedback: 'ไม่ใช่ — ปั๊มหัวใจ', nextStepId: 'end' },
        ],
      },
    ],
  },
  {
    id: 'car-accident',
    chapter: 3, lessonId: 'spine',
    title: 'อุบัติเหตุรถจักรยานยนต์',
    summary: 'พบผู้ขับขี่นอนข้างถนน ใส่หมวกกันน็อก',
    minutes: 4,
    icon: 'Car',
    color: CH[3],
    steps: [
      {
        id: 's1',
        prompt: 'เห็นผู้ขับขี่นอนข้างถนน รถยังเลื่อนอยู่ใกล้ ๆ ทำอะไรก่อน?',
        choices: [
          { id: 'a', text: 'รีบเข้าไปอุ้มออกมาทันที', correct: false,
            feedback: 'อันตราย — อาจมีรถวิ่งมาชน และเคลื่อนย้ายผิดวิธีอาจทำให้พิการ', nextStepId: 's2' },
          { id: 'b', text: 'เตือนรถคันอื่นด้วยไฟฉาย/เสื้อสะท้อนแสง แล้วโทร 1669', correct: true,
            feedback: 'ถูก — Scene safety ก่อน', nextStepId: 's2' },
          { id: 'c', text: 'ถ่ายรูปหลักฐานก่อน', correct: false,
            feedback: 'ทำได้ทีหลัง — ความปลอดภัยและการเรียก 1669 มาก่อน', nextStepId: 's2' },
        ],
      },
      {
        id: 's2',
        prompt: 'ผู้ป่วยใส่หมวกกันน็อกอยู่ หายใจอยู่ คุณ?',
        choices: [
          { id: 'a', text: 'ถอดหมวกกันน็อกออกทันที', correct: false,
            feedback: 'อาจทำให้คอบาดเจ็บเพิ่ม — รอเจ้าหน้าที่ ยกเว้นหายใจไม่ออก', nextStepId: 's3' },
          { id: 'b', text: 'ปล่อยหมวกไว้ ประคองคอให้นิ่ง ๆ', correct: true,
            feedback: 'ใช่ — สงสัย C-spine injury เสมอในอุบัติเหตุ', nextStepId: 's3' },
          { id: 'c', text: 'นั่งให้ตรง', correct: false,
            feedback: 'ห้ามขยับคอ', nextStepId: 's3' },
        ],
      },
      {
        id: 's3',
        prompt: 'ขาของผู้ป่วยมีเลือดออกพุ่ง คุณ?',
        choices: [
          { id: 'a', text: 'กดแผลตรง ๆ ด้วยผ้าสะอาด ใส่ถุงมือก่อน', correct: true,
            feedback: 'ถูก — direct pressure ปลอดภัยที่สุด และป้องกันตัวเอง', nextStepId: 'end' },
          { id: 'b', text: 'รัดเหนือแผลด้วยเชือก', correct: false,
            feedback: 'ใช้เฉพาะเมื่อกดไม่หยุดและเลือดพุ่ง (life-threatening) — ปกติกดก่อน', nextStepId: 'end' },
          { id: 'c', text: 'ราดน้ำล้างแผล', correct: false,
            feedback: 'อย่าล้างแผลใหญ่ — ห้ามเลือดก่อน', nextStepId: 'end' },
        ],
      },
    ],
  },
  {
    id: 'spine-fall',
    chapter: 3, lessonId: 'spine',
    title: 'ตกบันได เจ็บคอ ขยับไม่ได้',
    summary: 'สงสัยบาดเจ็บไขสันหลัง — ห้ามขยับคอ',
    minutes: 2, icon: 'AlertCircle', color: CH[3],
    steps: [
      {
        id: 's1',
        prompt: 'คนตกบันได นอนนิ่ง บ่นเจ็บคอ ขยับขาไม่ได้ รู้สึกชา — สงสัยภาวะใด?',
        choices: [
          { id: 'a', text: 'บาดเจ็บไขสันหลัง/คอ (ภาวะ "หลังหัก")', correct: true,
            feedback: 'ถูก — แขนขาอ่อนแรง/ชา + เจ็บคอ คือสัญญาณบาดเจ็บไขสันหลัง', nextStepId: 's2' },
          { id: 'b', text: 'เคล็ดธรรมดา', correct: false,
            feedback: 'อาการชา/ขยับไม่ได้บ่งบอกไขสันหลังบาดเจ็บ', nextStepId: 's2' },
          { id: 'c', text: 'เป็นตะคริว', correct: false,
            feedback: 'ไม่ใช่ — สงสัยบาดเจ็บไขสันหลัง', nextStepId: 's2' },
        ],
      },
      {
        id: 's2',
        prompt: 'หลักการที่สำคัญที่สุด?',
        choices: [
          { id: 'a', text: 'ป้องกันไม่ให้ศีรษะ/คอ บิด เอน ขยับ + โทร 1669', correct: true,
            feedback: 'ถูก — ขยับศีรษะ/คอให้น้อยที่สุด และโทร 1669', nextStepId: 's3' },
          { id: 'b', text: 'อุ้มลุกนั่งให้สบาย', correct: false,
            feedback: 'ห้ามขยับคอ — เสี่ยงพิการ', nextStepId: 's3' },
          { id: 'c', text: 'ดัดคอให้ตรง', correct: false,
            feedback: 'ห้ามเด็ดขาด — ให้คออยู่นิ่งที่สุด', nextStepId: 's3' },
        ],
      },
      {
        id: 's3',
        prompt: 'เขาอาเจียน เสี่ยงสำลัก — ทำอย่างไร?',
        choices: [
          { id: 'a', text: 'ใส่ PPE แล้วค่อยๆ ตะแคงตัว ให้ศีรษะ-คอขยับน้อยที่สุด', correct: true,
            feedback: 'ถูก — ตะแคงอย่างระวัง ให้ศีรษะ/คอขยับน้อยที่สุด', nextStepId: 'end' },
          { id: 'b', text: 'ปล่อยนอนหงายไว้', correct: false,
            feedback: 'เสี่ยงสำลัก — ต้องตะแคงอย่างระวัง', nextStepId: 'end' },
          { id: 'c', text: 'ยกหัวขึ้นสูงเร็วๆ', correct: false,
            feedback: 'ห้ามขยับคอแรงๆ', nextStepId: 'end' },
        ],
      },
    ],
  },
  {
    id: 'fracture-ankle',
    chapter: 3, lessonId: 'fracture',
    title: 'ข้อเท้าผิดรูป สงสัยกระดูกหัก',
    summary: 'ประคบเย็นและเข้าเฝือกอย่างง่าย',
    minutes: 2, icon: 'Bone', color: CH[3],
    steps: [
      {
        id: 's1',
        prompt: 'ข้อเท้าเพื่อนบวม ผิดรูป สีเริ่มเขียวคล้ำ ขยับแล้วเจ็บมาก — สงสัย?',
        choices: [
          { id: 'a', text: 'กระดูกหัก (ไม่แน่ใจให้สงสัยไว้ก่อน)', correct: true,
            feedback: 'ถูก — หากไม่แน่ใจให้สงสัยว่ากระดูกหัก', nextStepId: 's2' },
          { id: 'b', text: 'แค่เมื่อยกล้ามเนื้อ', correct: false,
            feedback: 'บวม/ผิดรูป/เจ็บมาก ให้สงสัยกระดูกหัก', nextStepId: 's2' },
          { id: 'c', text: 'ปกติ ไม่เป็นไร', correct: false,
            feedback: 'อาการชัดเจน — สงสัยกระดูกหัก', nextStepId: 's2' },
        ],
      },
      {
        id: 's2',
        prompt: 'ปฐมพยาบาลเบื้องต้น?',
        choices: [
          { id: 'a', text: 'วางผ้าบางๆ รอง ประคบด้วยถุงน้ำแข็งประมาณ 20 นาที', correct: true,
            feedback: 'ถูก — ประคบเย็น ~20 นาที (น้ำ+น้ำแข็งดีกว่าเจลเย็น)', nextStepId: 's3' },
          { id: 'b', text: 'ประคบร้อนเพื่อลดบวม', correct: false,
            feedback: 'ผิด — ต้องประคบเย็น ไม่ใช่ร้อน', nextStepId: 's3' },
          { id: 'c', text: 'ดึงข้อให้เข้าที่', correct: false,
            feedback: 'ห้ามจับ/ยืดส่วนที่ผิดรูป', nextStepId: 's3' },
        ],
      },
      {
        id: 's3',
        prompt: 'อยู่ที่ห่างไกล (เช่น ปีนเขา) ต้องเข้าเฝือกอย่างง่าย — ทำอย่างไร?',
        choices: [
          { id: 'a', text: 'ดามด้วยไม้/นิตยสาร จากข้อบนถึงข้อล่าง พันหลวมๆ พอสอดนิ้วได้', correct: true,
            feedback: 'ถูก — ดามคร่อมข้อบน-ล่าง พันหลวมๆ ไม่แน่นเกินไป', nextStepId: 'end' },
          { id: 'b', text: 'มัดให้แน่นที่สุดเท่าที่ทำได้', correct: false,
            feedback: 'ห้ามแน่นเกินไป — ต้องสอดนิ้วเข้าได้', nextStepId: 'end' },
          { id: 'c', text: 'ดามเฉพาะจุดที่หักจุดเดียว', correct: false,
            feedback: 'ต้องดามคร่อมจากข้อบนถึงข้อล่าง', nextStepId: 'end' },
        ],
      },
    ],
  },
  {
    id: 'kitchen-burn',
    chapter: 3, lessonId: 'burns',
    title: 'น้ำมันลวก',
    summary: 'แม่บ้านราดน้ำมันร้อนใส่แขนตัวเอง',
    minutes: 3,
    icon: 'Flame',
    color: CH[3],
    steps: [
      {
        id: 's1',
        prompt: 'แม่ของคุณราดน้ำมันร้อนใส่แขน เห็นผิวแดงและเริ่มพอง สิ่งแรกที่ทำ?',
        choices: [
          { id: 'a', text: 'ใส่ยาสีฟัน', correct: false,
            feedback: 'ผิด! ทำให้แผลติดเชื้อ', nextStepId: 's2' },
          { id: 'b', text: 'ราดน้ำสะอาดอุณหภูมิห้องไหลผ่าน 15–20 นาที', correct: true,
            feedback: 'ถูกต้อง — ลดความร้อนและบรรเทาปวด', nextStepId: 's2' },
          { id: 'c', text: 'ใช้น้ำแข็งประคบโดยตรง', correct: false,
            feedback: 'น้ำแข็งทำให้เนื้อเยื่อตายเพิ่ม', nextStepId: 's2' },
        ],
      },
      {
        id: 's2',
        prompt: 'หลังราดน้ำ เห็นตุ่มพองขนาดเท่าเหรียญสิบ ปวดมาก ขั้นต่อไป?',
        choices: [
          { id: 'a', text: 'เจาะตุ่มน้ำให้ออก', correct: false,
            feedback: 'ห้ามเจาะ — เสี่ยงติดเชื้อ ปล่อยให้ตุ่มทำหน้าที่ป้องกัน', nextStepId: 's3' },
          { id: 'b', text: 'ปิดด้วยผ้าก๊อซสะอาด ไม่ทาอะไร แล้วพาไป รพ.', correct: true,
            feedback: 'ใช่ — แผลพองที่หน้า/มือ/ใหญ่ ควรให้แพทย์ดู', nextStepId: 's3' },
          { id: 'c', text: 'ทาว่านหางจระเข้สด', correct: false,
            feedback: 'ของสดอาจมีเชื้อแบคทีเรีย ทำให้แผลติดเชื้อ', nextStepId: 's3' },
        ],
      },
      {
        id: 's3',
        prompt: 'ระหว่างพาไป รพ. แม่บอกว่าเหนื่อย ใจสั่น ทำอะไร?',
        choices: [
          { id: 'a', text: 'ให้ดื่มน้ำเปล่าจิบ ๆ', correct: true,
            feedback: 'ใช่ — แผลไหม้ทำให้เสียน้ำ การดื่มน้ำช่วยได้ ถ้าไม่อาเจียน', nextStepId: 'end' },
          { id: 'b', text: 'ให้กินยาแก้ปวดเอง', correct: false,
            feedback: 'รอให้แพทย์ประเมินก่อน อาจใช้ยาที่แรงกว่าได้', nextStepId: 'end' },
          { id: 'c', text: 'ไม่ต้องทำอะไร เดี๋ยวก็ดี', correct: false,
            feedback: 'อาการใจสั่นอาจเป็นสัญญาณ shock — แจ้งคนขับให้รีบ', nextStepId: 'end' },
        ],
      },
    ],
  },
  {
    id: 'fire-electric',
    chapter: 3, lessonId: 'burns',
    title: 'ไฟไหม้ตัว และไฟฟ้าช็อต',
    summary: 'Stop-Drop-Roll, แผลใหญ่ห่มผ้าแห้ง, ปิดสะพานไฟ',
    minutes: 3, icon: 'Flame', color: CH[3],
    steps: [
      {
        id: 's1',
        prompt: 'เสื้อเพื่อนติดไฟลุกขึ้น — ทำอย่างไร?',
        choices: [
          { id: 'a', text: 'ให้ "หยุด-ล้มตัวนอน-ม้วนตัวบนพื้น" (Stop-Drop-Roll) แล้วห่มด้วยผ้าเปียก', correct: true,
            feedback: 'ถูก — Stop, Drop, Roll แล้วห่มผ้าเปียกดับไฟ', nextStepId: 's2' },
          { id: 'b', text: 'ให้วิ่งหนีไปเรื่อยๆ', correct: false,
            feedback: 'ยิ่งวิ่งไฟยิ่งลุก — ต้องล้มตัวม้วนกับพื้น', nextStepId: 's2' },
          { id: 'c', text: 'ราดน้ำมันเพื่อความเย็น', correct: false,
            feedback: 'อันตรายมาก — น้ำมันติดไฟ', nextStepId: 's2' },
        ],
      },
      {
        id: 's2',
        prompt: 'ไฟดับแล้ว แต่แผลไหม้ขนาดใหญ่มาก — ห่มด้วยอะไร?',
        choices: [
          { id: 'a', text: 'ผ้าแห้ง + โทร 1669', correct: true,
            feedback: 'ถูก — แผลไหม้ใหญ่ห่มผ้า "แห้ง" ป้องกันการเสียความร้อน', nextStepId: 's3' },
          { id: 'b', text: 'ผ้าเปียกตลอดเวลา', correct: false,
            feedback: 'แผลใหญ่ห่มผ้าแห้ง (ผ้าเปียกใช้ตอนดับไฟเท่านั้น)', nextStepId: 's3' },
          { id: 'c', text: 'น้ำแข็งประคบทั่วตัว', correct: false,
            feedback: 'ห้ามใช้น้ำแข็ง — ทำให้แย่ลง', nextStepId: 's3' },
        ],
      },
      {
        id: 's3',
        prompt: 'อีกกรณี เพื่อนถูกไฟฟ้าช็อตและยังติดสายไฟอยู่ — ลำดับแรก?',
        choices: [
          { id: 'a', text: 'ปิดสะพานไฟใหญ่ก่อน', correct: true,
            feedback: 'ถูก — กระแสไฟนำผ่านคน/กิ่งไม้ได้ ปิดสะพานไฟก่อนทุกครั้ง', nextStepId: 'end' },
          { id: 'b', text: 'ดึงตัวออกด้วยมือเปล่า', correct: false,
            feedback: 'อันตราย — คุณจะถูกช็อตด้วย', nextStepId: 'end' },
          { id: 'c', text: 'ราดน้ำดับ', correct: false,
            feedback: 'ห้าม — น้ำนำไฟฟ้า ปิดสะพานไฟก่อน', nextStepId: 'end' },
        ],
      },
    ],
  },

  // ═══════════════ บทที่ 4 — อุบัติเหตุรอบตัวและสารเคมี ═══════════════
  {
    id: 'snake-bite',
    chapter: 4, lessonId: 'bites',
    title: 'งูกัดในสวน',
    summary: 'อยู่นิ่ง สงบ — ห้ามดูด/กรีด/รัด',
    minutes: 3, icon: 'Bug', color: CH[4],
    steps: [
      {
        id: 's1',
        prompt: 'คนงานถูกงูกัดที่ขาในสวน ไม่ทราบชนิดงู — ทำอย่างไร?',
        choices: [
          { id: 'a', text: 'สงสัยงูพิษไว้ก่อน ให้อยู่นิ่งและสงบ ห้ามขยับส่วนที่ถูกกัด + โทร 1669', correct: true,
            feedback: 'ถูก — ไม่ทราบชนิดให้สงสัยงูพิษ ให้อยู่นิ่ง ลดการกระจายพิษ', nextStepId: 's2' },
          { id: 'b', text: 'วิ่งกลับออฟฟิศเร็วๆ', correct: false,
            feedback: 'การขยับ/วิ่งทำให้พิษกระจายเร็ว — ต้องอยู่นิ่ง', nextStepId: 's2' },
          { id: 'c', text: 'ขยับขาบ่อยๆ ให้เลือดไหลพิษออก', correct: false,
            feedback: 'ผิด — ยิ่งขยับยิ่งกระจายพิษ', nextStepId: 's2' },
        ],
      },
      {
        id: 's2',
        prompt: 'สิ่งที่ "ห้ามทำ" เด็ดขาดกับงูกัด?',
        choices: [
          { id: 'a', text: 'ห้ามดูดพิษด้วยปาก ห้ามกรีดแผล ห้ามรัดเหนือแผล', correct: true,
            feedback: 'ถูก — ห้ามดูด/กรีด/รัด', nextStepId: 's3' },
          { id: 'b', text: 'ล้างแผลด้วยน้ำสะอาด', correct: false,
            feedback: 'อันนี้ทำได้ — ที่ห้ามคือดูด/กรีด/รัด', nextStepId: 's3' },
          { id: 'c', text: 'ถอดเครื่องประดับ/เสื้อแน่นออก', correct: false,
            feedback: 'อันนี้ทำได้ — ที่ห้ามคือดูด/กรีด/รัด', nextStepId: 's3' },
        ],
      },
      {
        id: 's3',
        prompt: 'งูตัวนั้นนอนนิ่งอยู่ใกล้ๆ ดูเหมือนตาย — ทำอย่างไร?',
        choices: [
          { id: 'a', text: 'ถอยห่าง ห้ามแตะ (งูบาดเจ็บ/ตายยังกัดได้) ถ้าต้องขยับใช้พลั่วตัก', correct: true,
            feedback: 'ถูก — งูบาดเจ็บ/ตายยังกัดได้ ห้ามแตะ', nextStepId: 'end' },
          { id: 'b', text: 'จับมาถ่ายรูปใกล้ๆ', correct: false,
            feedback: 'อันตราย — งูยังกัดได้', nextStepId: 'end' },
          { id: 'c', text: 'เอามือเขี่ยดูว่าตายจริงไหม', correct: false,
            feedback: 'ห้ามแตะเด็ดขาด', nextStepId: 'end' },
        ],
      },
    ],
  },
  {
    id: 'dog-bite',
    chapter: 4, lessonId: 'bites',
    title: 'สุนัขกัดทะลุผิวหนัง',
    summary: 'ล้างแผล ห้ามเลือด และเสี่ยงพิษสุนัขบ้า',
    minutes: 2, icon: 'Bug', color: CH[4],
    steps: [
      {
        id: 's1',
        prompt: 'ถูกสุนัขจรกัดทะลุผิวหนัง มีเลือดออก — ทำอย่างไร?',
        choices: [
          { id: 'a', text: 'ล้างแผลด้วยน้ำ (ฟอกสบู่ถ้ามี) ทันที + ห้ามเลือด/พันแผล + โทร 1669', correct: true,
            feedback: 'ถูก — ล้างแผลทันที ห้ามเลือด พันแผล และโทร 1669', nextStepId: 's2' },
          { id: 'b', text: 'ปิดแผลไว้เฉยๆ ไม่ต้องล้าง', correct: false,
            feedback: 'ต้องล้างแผลทันทีเพื่อลดเชื้อ', nextStepId: 's2' },
          { id: 'c', text: 'ดูดเลือดออกจากแผล', correct: false,
            feedback: 'ไม่ช่วย — ล้างน้ำและสบู่แทน', nextStepId: 's2' },
        ],
      },
      {
        id: 's2',
        prompt: 'ทำไมต้องไปสถานพยาบาล?',
        choices: [
          { id: 'a', text: 'เสี่ยงพิษสุนัขบ้า (สุนัข แมว ค้างคาว หนู สัตว์ป่า) ต้องรับการรักษา/วัคซีน', correct: true,
            feedback: 'ถูก — แผลทะลุผิวเสี่ยงพิษสุนัขบ้า ต้องส่งสถานพยาบาล', nextStepId: 's3' },
          { id: 'b', text: 'ไม่จำเป็น แผลเล็ก', correct: false,
            feedback: 'แผลกัดทะลุผิวต้องไปสถานพยาบาล', nextStepId: 's3' },
          { id: 'c', text: 'แค่ทายาเองที่บ้านพอ', correct: false,
            feedback: 'ต้องให้แพทย์ประเมินเรื่องพิษสุนัขบ้า', nextStepId: 's3' },
        ],
      },
      {
        id: 's3',
        prompt: 'แผลบวม ช้ำ แดง — ทำอย่างไร?',
        choices: [
          { id: 'a', text: 'ประคบเย็นด้วยผ้าหุ้มถุงน้ำแข็ง ~20 นาที', correct: true,
            feedback: 'ถูก — ประคบเย็น 20 นาทีลดบวม', nextStepId: 'end' },
          { id: 'b', text: 'ประคบร้อน', correct: false,
            feedback: 'ใช้ประคบเย็น ไม่ใช่ร้อน', nextStepId: 'end' },
          { id: 'c', text: 'บีบหนอง/เลือดออก', correct: false,
            feedback: 'ห้ามบีบ — ประคบเย็นและส่งแพทย์', nextStepId: 'end' },
        ],
      },
    ],
  },
  {
    id: 'bee-sting',
    chapter: 4, lessonId: 'bites',
    title: 'ผึ้งต่อย',
    summary: 'ขูดเหล็กในออก ห้ามรีด เฝ้าระวังแพ้ 30 นาที',
    minutes: 2, icon: 'Bug', color: CH[4],
    steps: [
      {
        id: 's1',
        prompt: 'ถูกผึ้งต่อย เห็นเหล็กในคาอยู่ที่ผิว — เอาออกอย่างไร?',
        choices: [
          { id: 'a', text: 'ขูดออกด้วยวัสดุขอบมน เช่น บัตรแข็ง', correct: true,
            feedback: 'ถูก — ขูดเอาเข็มและถุงพิษออกด้วยบัตรแข็ง', nextStepId: 's2' },
          { id: 'b', text: 'ใช้นิ้วบีบรีดถุงพิษออก', correct: false,
            feedback: 'ห้ามรีด — จะดันพิษเข้าสู่ร่างกาย', nextStepId: 's2' },
          { id: 'c', text: 'ใช้แหนบบีบดึง', correct: false,
            feedback: 'การบีบดันพิษเข้าตัว — ให้ขูดด้วยบัตรแข็ง', nextStepId: 's2' },
        ],
      },
      {
        id: 's2',
        prompt: 'หลังเอาเหล็กในออก ล้างแผล ประคบเย็นแล้ว ต้องเฝ้าดูอะไร?',
        choices: [
          { id: 'a', text: 'สังเกตอาการแพ้รุนแรงอย่างน้อย 30 นาที', correct: true,
            feedback: 'ถูก — เฝ้าระวังการแพ้รุนแรงอย่างน้อย 30 นาที', nextStepId: 's3' },
          { id: 'b', text: 'ไม่ต้องเฝ้าดู', correct: false,
            feedback: 'ต้องเฝ้าระวังการแพ้รุนแรง 30 นาที', nextStepId: 's3' },
          { id: 'c', text: 'ดูแค่ 5 นาทีพอ', correct: false,
            feedback: 'อย่างน้อย 30 นาที', nextStepId: 's3' },
        ],
      },
      {
        id: 's3',
        prompt: 'เขาเริ่มหน้าบวม หายใจไม่ออก (แพ้รุนแรง) — ทำอย่างไร?',
        choices: [
          { id: 'a', text: 'ใช้ EpiPen (ถ้ามี) + โทร 1669', correct: true,
            feedback: 'ถูก — แพ้รุนแรงให้ใช้ EpiPen และโทร 1669', nextStepId: 'end' },
          { id: 'b', text: 'ให้กินยาแก้แพ้แล้วรอ', correct: false,
            feedback: 'แพ้รุนแรงต้อง EpiPen + 1669 ทันที', nextStepId: 'end' },
          { id: 'c', text: 'ประคบเย็นอย่างเดียว', correct: false,
            feedback: 'ไม่พอ — ต้อง EpiPen และโทร 1669', nextStepId: 'end' },
        ],
      },
    ],
  },
  {
    id: 'heat-stroke',
    chapter: 4, lessonId: 'heat',
    title: 'ลมแดด (Heat Stroke)',
    summary: 'คนงานล้มกลางแดด สับสน — ลดอุณหภูมิด่วน',
    minutes: 3, icon: 'Sun', color: CH[4],
    steps: [
      {
        id: 's1',
        prompt: 'คนงานทำงานกลางแดดจัด จู่ๆ ล้มลง สับสน ปัสสาวะราด ตัวร้อนจัด — สงสัยภาวะใด?',
        choices: [
          { id: 'a', text: 'ลมแดด (Heat stroke) ภาวะถึงชีวิต', correct: true,
            feedback: 'ถูก — สับสน/ปัสสาวะราด/ชัก คือลมแดด ภาวะถึงชีวิต', nextStepId: 's2' },
          { id: 'b', text: 'แค่เหนื่อยธรรมดา', correct: false,
            feedback: 'อาการรุนแรงนี้คือลมแดด ต้องช่วยด่วน', nextStepId: 's2' },
          { id: 'c', text: 'ขี้เกียจทำงาน', correct: false,
            feedback: 'เป็นภาวะฉุกเฉินถึงชีวิต', nextStepId: 's2' },
        ],
      },
      {
        id: 's2',
        prompt: 'สิ่งที่ต้องทำเร็วที่สุด?',
        choices: [
          { id: 'a', text: 'โทร 1669 + ย้ายที่เย็น + วางผ้าเย็นที่คอ รักแร้ ขาหนีบ ทันที', correct: true,
            feedback: 'ถูก — ต้องลดอุณหภูมิให้รวดเร็วในนาทีแรก (คอ รักแร้ ขาหนีบ)', nextStepId: 's3' },
          { id: 'b', text: 'ให้ดื่มน้ำเย็นจัดมากๆ', correct: false,
            feedback: 'ถ้าซึม/กลืนไม่ได้ห้ามให้ดื่ม — เน้นลดอุณหภูมิภายนอก', nextStepId: 's3' },
          { id: 'c', text: 'ห่มผ้าหนาๆ', correct: false,
            feedback: 'ตรงข้าม — ต้องลดอุณหภูมิ ไม่ใช่เพิ่ม', nextStepId: 's3' },
        ],
      },
      {
        id: 's3',
        prompt: 'เขาปลุกไม่ตื่น ไม่หายใจ?',
        choices: [
          { id: 'a', text: 'ปั๊มหัวใจทันที', correct: true,
            feedback: 'ถูก — ปลุกไม่ตื่น ไม่หายใจ → ปั๊มหัวใจ', nextStepId: 'end' },
          { id: 'b', text: 'รอให้ตัวเย็นก่อน', correct: false,
            feedback: 'ต้องปั๊มหัวใจทันที', nextStepId: 'end' },
          { id: 'c', text: 'เทน้ำเข้าปาก', correct: false,
            feedback: 'ห้าม — ปั๊มหัวใจ', nextStepId: 'end' },
        ],
      },
    ],
  },
  {
    id: 'heat-cramp-exhaustion',
    chapter: 4, lessonId: 'heat',
    title: 'ตะคริวแดด / เพลียแดด',
    summary: 'พัก เข้าที่ร่ม ดื่มเกลือแร่ ลดอุณหภูมิ',
    minutes: 2, icon: 'Thermometer', color: CH[4],
    steps: [
      {
        id: 's1',
        prompt: 'ทำงานหนักกลางอากาศร้อน เป็นตะคริวที่น่อง เหงื่อแตก — ทำอย่างไร?',
        choices: [
          { id: 'a', text: 'หยุดพัก เข้าที่ร่ม ดื่มน้ำเกลือแร่/น้ำผลไม้ ยืด-นวดกล้ามเนื้อ', correct: true,
            feedback: 'ถูก — พักในที่ร่ม ดื่มเกลือแร่ และยืด/นวดกล้ามเนื้อ', nextStepId: 's2' },
          { id: 'b', text: 'ฝืนทำงานต่อ', correct: false,
            feedback: 'ควรหยุดพักเข้าที่ร่มก่อน', nextStepId: 's2' },
          { id: 'c', text: 'ให้กินยาคลายกล้ามเนื้อเอง', correct: false,
            feedback: 'ไม่จำเป็น — พัก ดื่มเกลือแร่ และยืดกล้ามเนื้อ', nextStepId: 's2' },
        ],
      },
      {
        id: 's2',
        prompt: 'อาการแบบใดคือ "เพลียแดด" ที่หนักกว่าตะคริว?',
        choices: [
          { id: 'a', text: 'เหงื่อออกมาก คลื่นไส้ เวียนศีรษะ อ่อนเพลีย จะเป็นลม', correct: true,
            feedback: 'ถูก — เพลียแดดเป็นอาการก่อนลมแดด', nextStepId: 's3' },
          { id: 'b', text: 'แค่ปวดกล้ามเนื้อเล็กน้อย', correct: false,
            feedback: 'นั่นคือตะคริว — เพลียแดดมีคลื่นไส้/เวียนหัว/จะเป็นลม', nextStepId: 's3' },
          { id: 'c', text: 'หิวข้าว', correct: false,
            feedback: 'ไม่ใช่ — เพลียแดดคือเหงื่อมาก คลื่นไส้ อ่อนเพลีย', nextStepId: 's3' },
        ],
      },
      {
        id: 's3',
        prompt: 'เพลียแดด ปฐมพยาบาลอย่างไร?',
        choices: [
          { id: 'a', text: 'โทร 1669 ให้นอนที่เย็น ถอดเสื้อ ลดอุณหภูมิ (พ่นละอองน้ำ/ผ้าเย็น) ดื่มเกลือแร่', correct: true,
            feedback: 'ถูก — พาเข้าที่เย็น ลดอุณหภูมิ และให้เกลือแร่', nextStepId: 'end' },
          { id: 'b', text: 'ให้วิ่งต่อให้เหงื่อออก', correct: false,
            feedback: 'ตรงข้าม — ต้องพักและลดอุณหภูมิ', nextStepId: 'end' },
          { id: 'c', text: 'ห่มผ้าให้ร้อนขึ้น', correct: false,
            feedback: 'ต้องลดอุณหภูมิ ไม่ใช่เพิ่ม', nextStepId: 'end' },
        ],
      },
    ],
  },
  {
    id: 'hypothermia',
    chapter: 4, lessonId: 'cold',
    title: 'ตัวเย็น (Hypothermia)',
    summary: 'ทำงานห้องเย็น ตัวสั่น แล้วหยุดสั่น = อันตราย',
    minutes: 2, icon: 'Snowflake', color: CH[4],
    steps: [
      {
        id: 's1',
        prompt: 'คนงานออกจากห้องเย็น ตัวสั่น ผิวเย็น สับสน ง่วงซึม — ภาวะใด?',
        choices: [
          { id: 'a', text: 'ภาวะตัวเย็น/อุณหภูมิร่างกายต่ำ (Hypothermia)', correct: true,
            feedback: 'ถูก — เป็นภาวะฉุกเฉินถึงชีวิตได้', nextStepId: 's2' },
          { id: 'b', text: 'แค่หนาวธรรมดา', correct: false,
            feedback: 'มีสับสน/ซึมร่วมด้วย = ภาวะตัวเย็นอันตราย', nextStepId: 's2' },
          { id: 'c', text: 'ง่วงนอน', correct: false,
            feedback: 'เป็นภาวะตัวเย็น ต้องรีบช่วย', nextStepId: 's2' },
        ],
      },
      {
        id: 's2',
        prompt: 'ปฐมพยาบาลอย่างไร?',
        choices: [
          { id: 'a', text: 'ย้ายเข้าที่อบอุ่น ถอดชุดเปียก เปลี่ยนชุดแห้ง ห่มผ้า + โทร 1669', correct: true,
            feedback: 'ถูก — ย้ายเข้าที่อุ่น เปลี่ยนชุดแห้ง ห่มผ้า โทร 1669', nextStepId: 's3' },
          { id: 'b', text: 'เอาน้ำร้อนจัดราดตัว', correct: false,
            feedback: 'ห้าม — ห้ามนำของร้อนจัด/น้ำร้อนสัมผัสผู้ประสบภัย', nextStepId: 's3' },
          { id: 'c', text: 'ให้ออกไปตากแดดแรงๆ', correct: false,
            feedback: 'ให้เข้าที่อบอุ่น ค่อยๆ รักษาอุณหภูมิ', nextStepId: 's3' },
        ],
      },
      {
        id: 's3',
        prompt: 'เขาเคยตัวสั่น แต่ตอนนี้ "หยุดสั่น" แล้ว — แปลว่าอะไร?',
        choices: [
          { id: 'a', text: 'อันตรายมาก ร่างกายปรับอุณหภูมิไม่ไหวแล้ว — รีบส่ง รพ. ถ้าไม่หายใจให้ปั๊มหัวใจ', correct: true,
            feedback: 'ถูก — หยุดสั่น = อุณหภูมิต่ำมาก อันตรายมาก', nextStepId: 'end' },
          { id: 'b', text: 'ดีขึ้นแล้ว หายแล้ว', correct: false,
            feedback: 'ตรงข้าม — หยุดสั่นคือสัญญาณอันตราย', nextStepId: 'end' },
          { id: 'c', text: 'ปกติ ไม่เป็นไร', correct: false,
            feedback: 'หยุดสั่นคืออันตรายมาก ต้องรีบส่ง รพ.', nextStepId: 'end' },
        ],
      },
    ],
  },
  {
    id: 'chemical-splash',
    chapter: 4, lessonId: 'chemical',
    title: 'สารเคมีกระเด็นเข้าตา',
    summary: 'พนักงานล้างถังเคมีในโรงงาน กระเด็นเข้าตา',
    minutes: 4,
    icon: 'Skull',
    color: CH[4],
    steps: [
      {
        id: 's1',
        prompt: 'พนักงานวิ่งมาบอกว่าโดน "น้ำยาล้าง" กระเด็นเข้าตา ตอนนี้แสบมาก คุณ?',
        choices: [
          { id: 'a', text: 'รีบพาไปฝักบัวล้างพิษ — ล้างต่อเนื่อง 20 นาที+', correct: true,
            feedback: 'ถูก — เวลาเป็นเรื่องสำคัญ ล้างทันทีที่เกิดเหตุ', nextStepId: 's2' },
          { id: 'b', text: 'หยอดยาหยอดตาก่อน', correct: false,
            feedback: 'อันตราย — ต้องล้างน้ำปริมาณมากออกก่อน ยาหยอดตาทำให้พิษค้าง', nextStepId: 's2' },
          { id: 'c', text: 'ขยี้ตาแรงๆ ให้น้ำตาออก', correct: false,
            feedback: 'ห้ามขยี้ — ทำให้พิษซึมเข้าเนื้อเยื่อมากขึ้น', nextStepId: 's2' },
        ],
      },
      {
        id: 's2',
        prompt: 'ระหว่างล้างตา คุณควรระวังอะไร?',
        choices: [
          { id: 'a', text: 'ให้ผู้ป่วยหลับตาให้แน่น', correct: false,
            feedback: 'ต้องลืมตาขณะล้าง + มองซ้าย-ขวา-บน-ล่าง ให้น้ำเข้าทั่วถึง', nextStepId: 's3' },
          { id: 'b', text: 'น้ำที่ล้างต้องไม่ไหลเข้าตาข้างที่ไม่ถูกพิษ', correct: true,
            feedback: 'ถูก — จัดท่าให้น้ำไหลออกข้างที่โดน ไม่ปนเข้าตาอีกข้าง', nextStepId: 's3' },
          { id: 'c', text: 'ใช้น้ำเดือดเพื่อฆ่าสารเคมี', correct: false,
            feedback: 'อันตรายมาก — ใช้น้ำสะอาดอุณหภูมิห้องเท่านั้น', nextStepId: 's3' },
        ],
      },
      {
        id: 's3',
        prompt: 'ขณะที่ส่งไป รพ. — ทีมฉุกเฉินขอข้อมูล คุณบอกอะไร?',
        choices: [
          { id: 'a', text: '"น้ำยาล้าง" ก็พอแล้ว', correct: false,
            feedback: 'ไม่พอ — ต้องระบุชื่อสาร เปิด MSDS แจ้งทีม', nextStepId: 'end' },
          { id: 'b', text: 'ชื่อสารเคมี (จาก MSDS) + ปริมาณ + เวลาที่เกิดเหตุ + อาการ', correct: true,
            feedback: 'ถูก — ข้อมูลครบช่วยให้แพทย์เลือกการรักษาที่ถูกต้อง', nextStepId: 'end' },
          { id: 'c', text: 'ปล่อยให้แพทย์ตรวจเอง', correct: false,
            feedback: 'การวิเคราะห์สารเคมีใช้เวลานาน — ข้อมูลที่คุณมีช่วยให้รักษาเร็วขึ้นมาก', nextStepId: 'end' },
        ],
      },
    ],
  },
  {
    id: 'chemical-swallow',
    chapter: 4, lessonId: 'chemical',
    title: 'กลืนสารเคมี',
    summary: 'ห้ามทำให้อาเจียน — CPR ต้องใช้หน้ากาก',
    minutes: 2, icon: 'Skull', color: CH[4],
    steps: [
      {
        id: 's1',
        prompt: 'คนงานเผลอกลืนสารเคมีกัดกร่อน ยังรู้สึกตัวดี — สิ่งที่ "ห้าม" ทำ?',
        choices: [
          { id: 'a', text: 'ห้ามทำให้อาเจียน', correct: true,
            feedback: 'ถูก — กลืนสารเคมีห้ามทำให้อาเจียนเด็ดขาด', nextStepId: 's2' },
          { id: 'b', text: 'ให้ดื่มน้ำ', correct: false,
            feedback: 'กรณีมีสติดีดื่มน้ำได้ — ที่ห้ามคือทำให้อาเจียน', nextStepId: 's2' },
          { id: 'c', text: 'โทร 1669', correct: false,
            feedback: 'ต้องโทร 1669 — ที่ห้ามคือทำให้อาเจียน', nextStepId: 's2' },
        ],
      },
      {
        id: 's2',
        prompt: 'เขามีสติดี กลืนสารกัดกร่อน — ควรให้?',
        choices: [
          { id: 'a', text: 'ลุกขึ้นดื่มน้ำ 240-300 ซีซี ทันที (มีนมให้ดื่มตามหลัง)', correct: true,
            feedback: 'ถูก — สารกัดกร่อน + รู้สึกตัวดี ให้ดื่มน้ำ 240-300 ซีซี', nextStepId: 's3' },
          { id: 'b', text: 'ล้วงคอให้อาเจียนออกมา', correct: false,
            feedback: 'ห้ามทำให้อาเจียนเด็ดขาด', nextStepId: 's3' },
          { id: 'c', text: 'ห้ามให้อะไรเลย', correct: false,
            feedback: 'มีสติดีให้ดื่มน้ำได้ 240-300 ซีซี', nextStepId: 's3' },
        ],
      },
      {
        id: 's3',
        prompt: 'ถ้าต้องปั๊มหัวใจผู้ที่ถูกสารเคมี ต้องระวังอะไร?',
        choices: [
          { id: 'a', text: 'ใช้หน้ากากช่วยหายใจ ห้ามเป่าปาก (สารพิษจะติดผู้ช่วย)', correct: true,
            feedback: 'ถูก — ต้องใช้หน้ากากเสมอ ห้ามเป่าปาก', nextStepId: 'end' },
          { id: 'b', text: 'เป่าปากได้ตามปกติ', correct: false,
            feedback: 'ห้าม — สารพิษจะติดผู้ช่วย ต้องใช้หน้ากาก', nextStepId: 'end' },
          { id: 'c', text: 'ไม่ต้องปั๊มหัวใจ', correct: false,
            feedback: 'ต้องปั๊ม แต่ใช้หน้ากากช่วยหายใจ', nextStepId: 'end' },
        ],
      },
    ],
  },
  {
    id: 'chemical-skin',
    chapter: 4, lessonId: 'chemical',
    title: 'สารเคมีโดนผิวหนัง',
    summary: 'ใส่ชุดป้องกัน ปัดผง ล้างตัว และให้ข้อมูล MSDS',
    minutes: 2, icon: 'Skull', color: CH[4],
    steps: [
      {
        id: 's1',
        prompt: 'สารเคมีกระเด็นโดนผิวหนัง/ตัวคนงาน — ลำดับแรก?',
        choices: [
          { id: 'a', text: 'เคลื่อนย้ายออกจากพื้นที่ ใส่ชุดป้องกันก่อนสัมผัส ถอดชุดเปื้อน ล้างตัวที่ฝักบัวล้างพิษ', correct: true,
            feedback: 'ถูก — ผู้ช่วยต้องใส่ชุดป้องกันก่อนสัมผัส แล้วถอดชุดเปื้อน ล้างตัว', nextStepId: 's2' },
          { id: 'b', text: 'เอาผ้าเช็ดแล้วทำงานต่อ', correct: false,
            feedback: 'ต้องล้างตัวที่ฝักบัวล้างพิษ ไม่ใช่แค่เช็ด', nextStepId: 's2' },
          { id: 'c', text: 'ทาครีมทับบริเวณที่โดน', correct: false,
            feedback: 'ห้าม — ต้องล้างสารออกด้วยน้ำ', nextStepId: 's2' },
        ],
      },
      {
        id: 's2',
        prompt: 'สารเป็นผงไม่ละลายน้ำติดอยู่บนผิว — ทำอะไรก่อนล้าง?',
        choices: [
          { id: 'a', text: 'ใช้ผ้า/แปรงปัดผงออกก่อน แล้วจึงล้างน้ำ', correct: true,
            feedback: 'ถูก — สารไม่ละลายน้ำ ให้ปัด/ซับออกก่อนล้าง', nextStepId: 's3' },
          { id: 'b', text: 'ราดน้ำเลยทันที', correct: false,
            feedback: 'สารผงไม่ละลายน้ำควรปัดออกก่อน', nextStepId: 's3' },
          { id: 'c', text: 'ถูให้ซึมเข้าผิว', correct: false,
            feedback: 'ห้าม — ปัดออกแล้วล้าง', nextStepId: 's3' },
        ],
      },
      {
        id: 's3',
        prompt: 'ข้อมูลที่ต้องเตรียมให้ทีมฉุกเฉิน?',
        choices: [
          { id: 'a', text: 'ชื่อสาร (จาก MSDS) ปริมาณ เวลาที่เกิดเหตุ และอาการ', correct: true,
            feedback: 'ถูก — ให้ข้อมูลจาก MSDS เพื่อการรักษาที่ถูกต้อง', nextStepId: 'end' },
          { id: 'b', text: 'แค่บอกว่า "โดนน้ำยา"', correct: false,
            feedback: 'ไม่พอ — ต้องระบุชื่อสารจาก MSDS', nextStepId: 'end' },
          { id: 'c', text: 'ไม่ต้องบอกอะไร', correct: false,
            feedback: 'ข้อมูลช่วยให้รักษาเร็วและถูกต้อง', nextStepId: 'end' },
        ],
      },
    ],
  },
]

export const scenariosById = Object.fromEntries(scenarios.map(s => [s.id, s]))
