-- Per-user study plan: generated by Claude, stored as JSON on the profile.

ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS exam_date date,
  ADD COLUMN IF NOT EXISTS study_plan jsonb,
  ADD COLUMN IF NOT EXISTS study_plan_generated_at timestamptz;
